### ISSUE TITLE
CMake Tools uses too much status bar space, especially with long kit names like  "Visual Studio Enterprise 2019 Preview - x86"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#1005]
See the screenshot:
![image](https://user-images.githubusercontent.com/19859882/72396699-656f4d00-36f2-11ea-9376-5bc995b8f053.png)

Can something be done to reduce the status bar space?

It's a problem for me because I can't see the C/C++ database or flame icons anymore after switching to a git branch with a long name. Also, the GitLens status bar items disappears as well.

If the "Visual Studio Enterprise 2019 Preview - x86" kit name could be reduced to something small that would be good enough for me. That is only useful for clicking to change the kit, so if it just showed an icon or something, I could click it or hover to see the longer kit name if I wanted to know.

**Comment by sean-mcmanus** [comment]
Certain kits are even worse:
![image](https://user-images.githubusercontent.com/19859882/76671114-b4e6c380-6551-11ea-86a0-a22fe1f8a8c4.png)
It's a problem on my laptop because the C/C++ flame/database icons are no longer viewable.

**Comment by ghuser404** [comment]
I'd prefer a better UI too, something else than the status bar... maybe a drop-down in the menu bar, like in Visual Studio.

**Comment by sean-mcmanus** [comment]
I don't believe VS Code yet has an API for extensions to add items to the main menu bar.

**Comment by dvirtz** [comment]
It would be nice to be able to choose which widgets to display. I, for example, never uses the `Run CTest` button.

**Comment by ghuser404** [comment]
@bobbrow How do you change active target in "icon" mode?

**Comment by sean-mcmanus** [comment]
@ghuser404 You could use the `CMake: Set Build Target` command or use the settings:
```
    "cmake.statusbar.visibility": "icon",
    "cmake.statusbar.advanced": {
        "buildTarget": {
            "visibility": "compact"
        }
    }
```

The build target doesn't have an icon, so an alternative design would be to give it an icon. Maybe we someone could open a new issue for that.

**Comment by ghuser404** [comment]
@sean-mcmanus A "configure" icon/button would be great too. I'll create a ticket for that later.
