### ISSUE TITLE
Select a Kit dropdown appears for non-CMake projects after installation or when activation by an extension takes too long

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#1007]
Bug#1: Install CMake Tools with a non-CMake project and the Select a Kit dropdown appears.
Bug#2: Put a breakpoint in the activation() method of another extension (e.g. the C/C++ extension) or otherwse cause "too slow" activation, which causes VS Code's "workspace contains **/CMakeLists.txt" activation to switch to "*" activation, causing "Select a Kit" to appear for non-CMake projects.

The fix for both of these would be to be to check on activation if the real activation conditions really occurred or not, similar to what the C/C++ extension does. Other fixes might be possible too.

Bug#3: When the above bugs are hit, then the select a kits also appears after adding a new workspace folder for a non-CMake folder.

**Comment by Zingam** [comment]
Can we also get rid of CMake extension related UI widgets/elements like these:
![image](https://user-images.githubusercontent.com/3337419/73017788-0cf22b00-3e29-11ea-9be5-02a42cc8fed5.png)
If there is no "CMakeLists.txt" in the folder?

**Comment by sean-mcmanus** [comment]
This occurs very frequently in cold start scenarios, such as when a TypeScript/non-CMake folder is opened for the first time. Also seems to occur more often when extensions are updated.

**Comment by andreeis** [comment]
Fixed by PR https://github.com/microsoft/vscode-cmake-tools/pull/1689.

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.
