### ISSUE TITLE
cmake-tools-kits gets overwritten

### ISSUE THREAD

**Issue by sfspeiser** [microsoft/vscode-cmake-tools#1010]
### Brief Issue Summary

If I add a custom cmake kit to the cmake-tools-kits.json (Edit User local Kits)  and then scan for kits, the json wil get replaced with the same content as before. Only if I save the json, restart VSCode and then scan for kits, my custom kits are detected and the json is not overwritten.

### Expected:

1.Edit cmake-tools-kits.json
2. Save file
3. Scan for Kits
4. Use custom kits

### Apparent Behavior:

1. Edit cmake-tools-kits.json
2. Save file
3. Scan for kits
4. cmake-tools-kits.json is replaced with same content as before edit.

workaround:

1.Edit cmake-tools-kits.json
2. Save file
3. restart VSCode
4. Scan for kits
5. use custom kit

### CMake Tools Log

```
[kit] Not reading non-existent kits file: c:\Users\<USER>\WORKSPACE\<PROJECT>\.vscode\cmake-kits.json
[kit] Reading kits file C:\Users\<USER>\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 4 kits from C:\Users\<USER>\AppData\Local\CMakeTools\cmake-tools-kits.json
[main] Safe constructing new CMakeTools instance
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[variant] Loaded new set of variants
[main] CMakeTools instance initialization complete.
[main] Injecting new Kit into CMake driver
[kit] Reading kits file C:\Users\<USER>\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 4 kits from C:\Users\<USER>\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Not reading non-existent kits file: c:\Users\<USER>\WORKSPACE\<PROJECT>\.vscode\cmake-kits.json
[main] Injecting new Kit into CMake driver
```
**I had 5 Kits declared in my JSON file, but it only picked up 4 and deleted the 5th**
### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: <!-- Windows 10>
- **CMake Version**: <!-- 3.13.1 >
- **VSCode Version**: <!-- 1.41.1 >
- **CMake Tools Extension Version**: <!-- 1.2.3 >
- **Compiler/Toolchain**: <!-- QNX compiler QCC 5.4>

**Comment by bxknoblauch** [comment]
I still see this issue on OSX 1.48.2 version

Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z (1 wk ago)

**Comment by listenerri** [comment]
confirmed +1

**Comment by astewart-xmos** [comment]
Still seeing this in `v1.10.5`.  The work-around mentioned in OP does not help.

There does not appear to be _any way_ to use a custom kit, as before I can configure it always rescans and clobbers any custom kits.

Why can't the auto-scanned kits just go into a different file?

**Comment by arealibusadrealiora** [comment]
Still happening to me on v1.13.45.
Making cmake-tools-kits.json read-only didn't help.

**Comment by emtKazys** [comment]
I've been having the same frustration, but I'm trying a new workaround. Configure `"cmake.additionalKits" in your workspace settings. For example

In VSCode settings:

```json
    "cmake.additionalKits": [
        "${workspaceFolder}/.vscode/cmake-tools-additional-kits.json"
    ]
```

Contents of `cmake-tools-additional-kits.json`

```json
[
    {
        "name": "Clang",
        "compilers": {
            "C": "/usr/bin/clang",
            "CXX": "/usr/bin/clang++"
        },
        "isTrusted": true
    }
]```

This seems to survive running: `CMake: Scan for Kits`

**Comment by gcampbell-msft** [comment]
@emtKazys Thank you for posting this! I think that this is the correct way to have additional kits, so I'll close this in favor of the workaround you posted.
