### ISSUE TITLE
Option to Combine User/Workspace Scoped Settings

### ISSUE THREAD

**Issue by P-N-L** [microsoft/vscode-cmake-tools#1012]
Feature request.

### Brief Issue Summary

It would be convenient to have the option of combining, instead of overriding, the various CMake arguments settings (Build Args, Build Tool Args, Configure Args, Ctest Args, Mingw Search Dirs, etc.).

### Expected:

As an example:
1. Add a User-scope build argument "-j2" to limit builds to two cores for an under-powered machine, for any project built on it.
2. Add a Workspace-scope build argument "--debug=v" to a workspace that should print additional verbose output.

### Other Notes/Information

With some of the projects I work on, it can be convenient to have these shared system-wide settings that stack with specific settings at a workspace level. Manually re-defining the same items from the user level at the workspace level is doable, just moderately inconvenient.

**Comment by bobbrow** [comment]
This should be possible via the `WorkspaceConfiguration.inspect` API.  We would probably want to require some additional syntax to instruct the extension to do this sort of lookup though.  I think automatic stacking of variables would confuse people.

It would behave similar to how you can add to variables in CMake, for example:
```
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ... ...")
```

Perhaps like this:
```
"cmake.configureArgs": ["${cmake.configureArgs}", "..."],
```
This would only work for the array-of-string settings.

**Comment by P-N-L** [comment]
This feature has not been implemented yet. I am adding a comment to ensure it doesn't get closed yet. I will likely let it expire next time.

**Comment by gcampbell-msft** [comment]
@P-N-L Due to the age of this issue, and due to the fact that this would actually somewhat go against the design goals and the structure of the VS Code settings, so with those things in mind, we likely won't get to this issue. Closing. 

Thanks for the feedback request and please continue to open issues if you have ideas or requests!
