### ISSUE TITLE
An Exception when "cmake.sourceDirectory":  is set

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#1014]
I get an exception with the attached sample project configured as is
![72662919-470c9880-39f5-11ea-9530-2c9eef3c333c](https://user-images.githubusercontent.com/3337419/72834438-8525e880-3c91-11ea-8e86-12046aa4c746.png)
[CMakeMultiProject.zip](https://github.com/microsoft/vscode-cmake-tools/files/4093138/CMakeMultiProject.zip)

Ref: https://github.com/microsoft/vscode-cmake-tools/pull/958#issuecomment-576806267

**Comment by bobbrow** [comment]
Thanks @Zingam!

The takeaway from this is that the error is unclear and the developer doesn't know what is wrong.  In the event that the developer adds `CMakeLists.txt` to the `sourceDirectory` setting, we could potentially trim that from the path and proceed without error.
