### ISSUE TITLE
Cannot select CMake Active Folder

### ISSUE THREAD

**Issue by optimarch** [microsoft/vscode-cmake-tools#1023]
### Brief Issue Summary
In a workspace composed by two folders, I cannot change the current active folder.
### Expected:
1a. Press the Active folder button on the Status Bar
-OR-
1b. Open the command palette and run `>CMake: Select Active Folder`
THEN
2. The Command Palette opens, listing the Active Folders available, and asks to select the new Active Folder
3. The Active Folder selected by CMake for the build changes, the targets list changes, and I can launch a build for the newly selected Active Folder.
### Apparent Behavior:
1a. Press the Active folder button on the Status Bar
-OR-
1b. Open the command palette and run `>CMake: Select Active Folder`
THEN
2. Nothing happens.

### CMake Tools Log

```
[variant] Loaded new set of variants
[kit] Successfully loaded 3 kits from /home/dteod/.local/share/CMakeTools/cmake-tools-kits.json
[variant] Loaded new set of variants
[main] Configuring folder: Project1 
[main] Configuring folder: Project2 
[cmake] Configuring done
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.
[cmake] 
[cmake] 
[cmake] Configuring done
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.
[cmake] 
[cmake] 
[cmake] Generating done
[cmake] Generating done
```
(this is the log after VSCode startup, nothing comes out either from pressing the button on the Status Bar or launching the command from the Command Palette)

### Developer Tools Log
Whenever I press the button or launch the command from the Command Palette this comes out in the developer window:
```
console.ts:137 [Extension Host] [CMakeTools] 2020-01-24T21:33:34.154Z [debug] [extension] [2944] cmake.selectActiveFolder started
console.ts:137 [Extension Host] [CMakeTools] 2020-01-24T21:33:34.156Z [debug] [extension] [2944] cmake.selectActiveFolder finished (returned undefined)
```

### Platform and Versions
- **Operating System**: Arch Linux x64 5.4.13-arch-1-1
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.41.1
- **CMake Tools Extension Version**: 1.3.0-beta
- **Compiler/Toolchain**: Clang 9.0.0

### Other Notes/Information
CMake Tools correctly launches CMake on the different folders at startup. It just returns undefined when the Select Active Folder command is executed; it lets me select only the targets to build of the last project (Project 2).

**Comment by bobbrow** [comment]
Thank you for trying out our multi-root support!  I experienced this same issue while I was using it and submitted a fix for this earlier today.  It will be in the final release (and any subsequent betas).  https://github.com/microsoft/vscode-cmake-tools/pull/1021

In the meantime, you can make it work by disabling the `cmake.autoSelectActiveFolder` setting, or setting focus (in the editor) on a file from the folder you want to activate.

**Comment by optimarch** [comment]
Changing the focus between the files worked!
Thank you very much for your support.

**Comment by andreeis** [comment]
Closing since this is fixed in CMake Tools Beta2. Please reactivate if you encounter any other symptoms of this issue.
