### ISSUE TITLE
Generator selection

### ISSUE THREAD

**Issue by caiuspb** [microsoft/vscode-cmake-tools#104]
In my opinion, the preferredGenerators settings is pretty well hidden within the settings.json. I would find it quite useful if your tool would be able to check for the preferredGenerator setting when a cmake project shall be configured. But if this setting is not set it would be great to display a dropdown field similar to cmake gui (windows):

![image](https://cloud.githubusercontent.com/assets/1751865/22055701/bece1ffe-dd5c-11e6-95d2-b2cf2eb7e52b.png)

What is your opinion on this feature request @vector-of-bool ?

**Comment by vector-of-bool** [comment]
It's definitely a viable option, especially now that CMake Server provides a listing of available generators. I'll see about getting something like this in.
