### ISSUE TITLE
Error: connect ENOENT whenever I use any CMake build command

### ISSUE THREAD

**Issue by Inglonias** [microsoft/vscode-cmake-tools#1040]
### Brief Issue Summary
I'm trying to configure a project for CMake tools in VS Code, but I'm hitting an error message when I try to do pretty much anything resembling a build. I'm all but certain this is a config issue and not a bug, but the closest existing report is #713, and that's not quite the same as what I'm doing. These are the errors I see when I try to press "CMake Debug: Ready" on my project:

`[rollbar] Unhandled exception: Unhandled Promise rejection: Changing build variant Error: connect ENOENT \\?\pipe\d:\My Documents\GitHub\Cataclysm-DDA\.vscode\.cmserver-pipe {}`
`[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant Error: connect ENOENT \\?\pipe\d:\My Documents\GitHub\Cataclysm-DDA\.vscode\.cmserver-pipe {}`

### Expected:

I honestly don't know. I do expect to see the project start debugging, I guess.

### Apparent Behavior:
`[rollbar] Unhandled exception: Unhandled Promise rejection: Changing build variant Error: connect ENOENT \\?\pipe\d:\My Documents\GitHub\Cataclysm-DDA\.vscode\.cmserver-pipe {}`
`[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant Error: connect ENOENT \\?\pipe\d:\My Documents\GitHub\Cataclysm-DDA\.vscode\.cmserver-pipe {}`

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.15.5
- **VSCode Version**: 1.41.1
- **CMake Tools Extension Version**: 1.2.3
- **Compiler/Toolchain**: GCC and G++ 9.2.0 running through MSys.

### Other Notes/Information
Not gonna lie: I'm pretty confused here, and I'm posting this here because I don't know what else to do.

**Comment by Inglonias** [comment]
Issue is no longer relevant. Sorry to bother everyone.

I ended up just hooking VS Code up to GDB and GCC directly to compile the software.

**Comment by bobbrow** [comment]
I can't say I know much about the msys environment, but we did just post a beta of the extension with cmake-file-api support which shouldn't attempt to use pipes to communicate with a CMake server.

If you'd like to try it out and see if it helps, the pre-release link is here:
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.3.0-beta2
