### ISSUE TITLE
Change the configuration provider id to "ms-vscode.cmake-tools"

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#1045]

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
