### ISSUE TITLE
How to specify CMake Toolchain?

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#1046]
- **Operating System**: Windows
- **CMake Version**: 3.16.4
- **VSCode Version**: 1.42.0-insiders
- **CMake Tools Extension Version**: 1.3.0-beta2

I am using a g++ cross-compiler to target Linux, built on Windows, so I need to specify my build tools in a CMake toolchain file.  From the command line I configure the build using:

    cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=../../CMake/toolchain.cmake.txt ..

In VS Code settings I have:

		"cmake.configureArgs": [
			"-DCMAKE_TOOLCHAIN_FILE=${workspaceFolder}/CMake/toolchain.cmake.txt"
		],
		"cmake.buildDirectory": "${workspaceFolder}/build_ThebeAP",
		"cmake.buildToolArgs": [
			"-v"
		],
		"cmake.sourceDirectory": "${workspaceFolder}/source/ThebeAP_cmake",
		"cmake.generator": "Ninja",
		"cmake.configureSettings": {
			"CMAKE_TOOLCHAIN_FILE" : "${workspaceFolder}/source/CMake/toolchain.cmake.txt"
		}

I have selected 'No active kit'.

When I try to build with cmake-tools I see:

```
[main] Building folder: software 
[main] Configuring folder: software 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=c:\SVNProj\Thebe\trunk\software/CMake/toolchain.cmake.txt -DCMAKE_TOOLCHAIN_FILE:STRING=c:\SVNProj\Thebe\trunk\software/source/CMake/toolchain.cmake.txt -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -Hc:/SVNProj/Thebe/trunk/software/source/ThebeAP_cmake -Bc:/SVNProj/Thebe/trunk/software/build_ThebeAP -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Build type is 'Debug'
[cmake] -- The CXX compiler identification is unknown
[cmake] -- The C compiler identification is unknown
[cmake] CMake Error at CMakeLists.txt:26 (project):
[cmake]   No CMAKE_CXX_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
[cmake]   to the compiler, or to the compiler name if it is in the PATH.
```
What is the correct way to use a toolchain?

**Comment by DavidA2014** [comment]
I fixed this issue by specifying the toolchain in cmake-kits.json.

**Comment by bobbrow** [comment]
Sorry we didn't get back to you sooner.  I wanted to test out the toolchain in cmake-kits.json before suggesting it, but we were busy prepping the 1.3.0 release so we didn't get to it yet.  I'm glad that that worked for you.

**Comment by DavidA2014** [comment]
@bobbrow Thanks for your reply.

**Comment by MaJerle** [comment]
Do we know if this is now the correct way of doing it?
