### ISSUE TITLE
Variable substitution does not work

### ISSUE THREAD

**Issue by jorisvanderpol** [microsoft/vscode-cmake-tools#1056]
Variable substitution in cmake-kits.json does not work properly:

    {
        "name": "gcc-arm-none-eabi",
        "toolchainFile": "${workspaceFolder:BuildSystem}/toolchains/gcc-arm-none-eabi.cmake"
    }

If I use ${workspaceFolder}/../BuildSystem for example, it works.

Same problem in the settings.json file:

    "cmake.configureSettings": {
        "BUILDSYSTEM_DIRECTORY": "${workspaceFolder:BuildSystem}"
    }

Visual Studio Code: 1.42
CMake Tools: 1.3.0

**Comment by bobbrow** [comment]
This might be addressed by PR #991.  @andreeis can you check?

**Comment by bobbrow** [comment]
To clarify, this is not currently supported, but we do plan to support it in the future.

**Comment by btgoodwin** [comment]
It sounds like this is resolved, based on that _fixed (release pending)_ label.  Is there an estimate for when this might be resolved?

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.5.0 which was published today.
Let us know if you encounter any issues with this release.

**Comment by btgoodwin** [comment]
Excellent, thank you.  This seems to have fixed it for me.
