### ISSUE TITLE
Variable substitution and active target

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#1057]
- **Operating System**: Windows
- **CMake Version**: 3.16.4
- **VSCode Version**: 1.43.0-insider
- **CMake Tools Extension Version**: 1.3.0
- **Compiler/Toolchain**: g++ cross-compiler

I have a workspace that contains 3 CMakeLists.txt files.  Two  CMakeLists.txt files specify two separate executables and one is a library, common to both.  So I have two targets.  I can select the active target by clicking the Build button in the status bar.  But I want to specify a separate build directory for each target.  I can specify such a directory using "cmake.buildDirectory". Currently I have:

"cmake.buildDirectory": "${workspaceFolder}/source/TargetA_cmake/build_TargetA_${buildType}"

My question is how can I specify a separate build directory for each target, i.e. TargetA and TargetB?

I guess I would achieve that using variable substitution. But which variable would I use?  

Is the intention to use the ${variant:VARIANTNAME} syntax?  This doesn't feel right as I want to specify a target name not a variant name.

**Comment by andreeis** [comment]
Please give us more details about your project and what you would like to accomplish. In general, a different build folder is required for different variants (debug/release/etc..), or for different kits, not as much for different targets which usually are built in the same place.
Maybe you mean a separate sub-directory for each target, but within the same build folder?
One build folder is set during the configure operation. Currently we don't support setting more than one build folders during the process of configuring.

**Comment by DavidA2014** [comment]
@andreeis Thanks for your reply. I have reworked my project to use one build directory for both targets that it produces and it seems to work well.
