### ISSUE TITLE
cmake-kits.json and cmake-variants.json ignored when next to workspace file

### ISSUE THREAD

**Issue by DexterMagnific** [microsoft/vscode-cmake-tools#1061]
### Brief Issue Summary

When cmake-variants.jsons and cmake-kits.json are next to the code-workspace file, they are ignored.

Here is my layout:

```
projectRoot/
   ide/VScode/myproject.code-workspace
   ide/VScode/cmake-kits.json
   ide/VScode/cmake-variants.json
   src/    # all sources are here, as well as the top CMakeLists.txt
```

Here is my workspace file contents:

```
{
	"folders": [
		{
			"path": "../../src"
		}
	],
	"settings": {
		"C_Cpp.default.configurationProvider": "vector-of-bool.cmake-tools",
		"cmake.buildDirectory": "${workspaceRoot}/../build/${buildType}/${variant:audioConfig}",
		"cmake.sourceDirectory": "${workspaceRoot}",
		"cmake.configureOnOpen": true,
       }
}
```

### Expected:

These files are taken into account by CMake tools

### Apparent Behavior:

These files are ignored by CMake tools. I have to put them inside a ``.vscode/`` dir inside ``src/`` to be taken into account.

### Platform and Versions

- **Operating System**: Linux
- **CMake Version**: 3.13.4
- **VSCode Version**: 1.41.1
- **CMake Tools Extension Version**: 1.3.0
- **Compiler/Toolchain**: standard gcc 8.3.0

### Other Notes/Information

I can add the variants inline inside the workspace file using "cmake.defaultVariants". But I cannot do the same for kits.

**Comment by andreeis** [comment]
The extension currently does not support this scenario, but we are looking at building on the PR https://github.com/microsoft/vscode-cmake-tools/pull/744.
