### ISSUE TITLE
Scan for MinGW kits is not working

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#1064]
Just for the record: Maybe I am doing something wrong but it seems to me that `cmake.mingwSearchDirs` is not loaded from the configuration and thus ` kit_options.minGWSearchDirs` is undefined and no scan for MinGW kits is performed:
```
    if (isWin32 && kit_options.minGWSearchDirs) {
      for (const dir of convertMingwDirsToSearchPaths(kit_options.minGWSearchDirs)) {
        scan_paths.add(dir);
      }
    }
```
This needs further investigation for me to confirm it.

**Comment by bobbrow** [comment]
Are you planning to take a look at this, or did you want us to investigate?

**Comment by andreeis** [comment]
I confirm that scanForKits has undefined kit_options.minGWSearchDirs, even if I define them in settings.json.

**Comment by Zingam** [comment]
I wouldn't mind if you look at this.

**Comment by Zingam** [comment]
This made me wonder about the following: Clang doesn't have a variable `cmake.mingwSearchDirs` but has the hardcoded default paths. The path to MinGW is set in `package.json`. Perhaps it makes sense to align the implementations - add a hardcoded value to MinGW and a variable to Clang.
Or a better option could be just to add a generic variable `cmake.compilerSearchPaths` (I don't think there is one) to replace:
```
"cmake.mingwSearchDirs": [
  "C:\\MinGW"
]
```
and use it everywhere for current and future compilers.

**Comment by ZUIcat** [comment]
I have the same problem.
