### ISSUE TITLE
Multi-root workspaces don't provide per-folder browse configuration info

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#1073]
With a multi-root workspace, provideBrowseConfiguration is only returning info on one workspace folder and canProvideBrowseConfigurationsPerFolder should return true...if it that's impossible it should return the browse data for all the workspace folders instead of one.

This isn't working for the existing cpptools or our pending 1.0 release that has a completely different multi-root implementation.

**Comment by sean-mcmanus** [comment]
In cpptools.ts, CppConfigurationProvder._workspaceBrowseConfiguration data just gets overwritten by the 2nd workspace folder data.

@xisui-MSFT @andreeis Are any of you able to work on this? This is a high priority for our cpptools 1.0 release.

**Comment by sean-mcmanus** [comment]
Looks like provideFolderBrowseConfiguration also needs to be implemented.

**Comment by sean-mcmanus** [comment]
I figured out a potential hack/workaround via skipping the bogus browse configuration if none of the paths share the same workspace folder, which is usually the case when we're given browse config info for the wrong workspace folder.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
