### ISSUE TITLE
Where to setup the "cmake option profile"?

### ISSUE THREAD

**Issue by huming2207** [microsoft/vscode-cmake-tools#1079]
Hi all,

I would like to know is there a function in VSCode has a similar function to set the option profile, similar to CLion's Profile setting?  

I have a single embedded project that has a few different hardware to support, like this:

![screenshot](https://user-images.githubusercontent.com/4463497/74514568-f2f7c400-4f60-11ea-901a-264ceee56dac.png)

Assuming a project called `Foobar` and I have 3 different boards with different microcontrollers on it. In the profile list, it has 6 different profiles, every two matches a different board (Debug or Release). Then for board Baz, the profile has a CMake option `-DFOOBAR_T ARGET=BAZ-BOARD`.

![screenshot2](https://user-images.githubusercontent.com/4463497/74515217-3d2d7500-4f62-11ea-8311-ec8c47fed0b7.png)

Then later if I need to select one compile target, I just need to pick the profile from the list at the top right corner and start the build.

Is there a similar way to do so in this CMake plugin? Thanks in advance!

Regards,
Jackson

**Comment by bobbrow** [comment]
We have a concept called "variants" where you can configure something similar.  Take a look at this documentation and let us know if that will address your question.

**Comment by huming2207** [comment]
@bobbrow Thanks!
