### ISSUE TITLE
Localization settings

### ISSUE THREAD

**Issue by fghzxm** [microsoft/vscode-cmake-tools#1083]
Version: 1.3.0

### Brief Issue Summary
This extension picks the system locale automatically for displaying localized strings, but there isn't a setting for controlling this behavior (which locale to use) explicitly.

### Expected:
Please add such setting.

**Comment by bobbrow** [comment]
VS Code manages the locale settings.  We just provide the strings for the locales.  Have you tried selecting a language with the "Configure Display Language" command?

**Comment by fghzxm** [comment]
When I explicitly configure the display language, this extension displays strings in that language without problem; when the display language was initially left unconfigured however, VSCode defaulted to displaying in English, but this extension used the system locale (which on my machine is not English).  It may be regarded as a bug in Code or in this extension depending on your decision, but is definitely an inconsistency.

**Comment by bobbrow** [comment]
Yes, I agree there is an inconsistency here.  The VS Code team releases their language support as separate language extensions that you have to install.  Most extensions bundle the language support.

We opened this issue for them to consider: https://github.com/microsoft/vscode/issues/82791
