### ISSUE TITLE
More options for command palette

### ISSUE THREAD

**Issue by Shadowblitz16** [microsoft/vscode-cmake-tools#1085]
### Brief Issue Summary

I have a few suggestions for the command palette.

- `add library` allows you to select a project to add a library to and a library to add
- `remove library` allows you to select a project to remove a library a the library to remove
- `change project type` allows you to change one of your project types. for example to a static library

**Comment by bobbrow** [comment]
Thank you for your suggestion.

**Comment by gcampbell-msft** [comment]
@Shadowblitz16 Thanks for your suggestion. However, due to the age of this issue, and the likelihood of us getting to this item being low, we will close this as not planned. 

Thanks!
