### ISSUE TITLE
The 1st time after the C/C++ extension is installed, CMake Tools doesn't send config info (only browse info)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#1087]
1. Have CMake Tools installed.
2. Open some C/C++ project that uses CMake and open some file that requires includePaths to be set correctly.
3. Install the C/C++ extension.

Bug: The logging shows the C/C++ extension receives the custom browse configuration, but not the regular confiuguration info for the includePath, etc.

The workaround is to Reload Window.

**Comment by bobbrow** [comment]
@sean-mcmanus, does cpptools send a provideCustomConfiguration request?  cmake-tools won't know to send the config unless it is asked.

**Comment by sean-mcmanus** [comment]
updateCustomBrowseConfiguration is sent, but provideCustomConfiguration is not sent. My guess is that the config provider is not getting setup correctly. Yeah, could be a C/C++ bug.
