### ISSUE TITLE
Scan for kits cannot find Visual Studio

### ISSUE THREAD

**Issue by toramoor** [microsoft/vscode-cmake-tools#1095]
### Brief Issue Summary

When I try to scan for kits no Visual Studio kit is found even though I have Visual Studio 2019 Build Tools insatalled.

### Expected:

1. Select "Scan for kits"
2. Visual Studio kit is found

### Apparent Behavior:

1. Select "Scan for kits"
2. There is no Visual Studio option

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.15.4
- **VSCode Version**: 1.42.1
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Visual C++ 2019

**Comment by andreeis** [comment]
I am not able to reproduce this. Did you do anything different than the defaults during your installation?
