### ISSUE TITLE
Custom browse configuration path irregularities

### ISSUE THREAD

**Issue by RobRuckOB** [microsoft/vscode-cmake-tools#1099]
(I initially mistakenly reported this bug to the C/C++ extension team)

Whilst looking at another unrelated issue with the C/C++ extension I turned on debug logging and saw something unusual in the paths listed in the "Custom browse configuration received:" section. Specifically, there are repeated lower-cased versions of paths (I can just about believe that's intentional due to platform differences) and/or paths with the workspace folder appended twice (I can't think of any reason for this). If this is a somewhat scattergun approach to finding things, that's not ideal, but it also doesn't seem to work quite right - I see some paths in the lower case or repeated style that don't appear correctly in the list of paths at all.

- OS and Version: OSX 10.14.6
- VS Code Version: 1.42.1
- C/C++ Extension Version: 0.26.3
- CMake Version: 3.16.2
- CMake Tools Extension Version: 1.3.1
- Compiler/Toolchain: clang 9.1.0

**To Reproduce**
My c_cpp_properties.json:
`{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**",
                "~/.conan/data/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/usr/bin/clang",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "configurationProvider": "vector-of-bool.cmake-tools"
        }
    ],
    "version": 4
}`
I simply start up VS Code, and the paths issue is visible in the start up debug output from the extension.

**Expected behavior**
Only valid paths are set in the browse configuration.

**Screenshots**
Lower casing of path (Notice /users):
<img width="442" alt="image" src="https://user-images.githubusercontent.com/42342894/75325319-83db7300-5870-11ea-9d8c-a089a64b6200.png">

Lower casing of path and repetition of the workspace folder:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/42342894/75324793-9c975900-586f-11ea-8751-4c43d694eea9.png">

Subsequent errors:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/42342894/75325022-fdbf2c80-586f-11ea-92d5-f455b535c041.png">

**Comment by bobbrow** [comment]
Thanks for reporting this.  I can reproduce this locally.

**Comment by KoeMai** [comment]
I was not able to reconstruct the problem.
Does it work if you change `cmake.cmakeCommunicationMode` setting back to `ServerAPI`?

**Comment by bobbrow** [comment]
I don't think this has anything to do with that.  I added code to cpptools.ts that aggregates the paths for all of the projects into the browse configuration.  The path normalization code for macOS is running before the paths are added to the Set.  I had assumed that it would follow the linux normalization rules, but it is following the Windows rules instead since macOS supports case-insensitive paths.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
