### ISSUE TITLE
Add support for Objective-C and Objective-C++

### ISSUE THREAD

**Issue by marksisson** [microsoft/vscode-cmake-tools#1108]
### Brief Issue Summary

When including OBJC and OBJCXX languages in C++/C projects, vscode-cmake-tools is logging "Unknown language" warnings for C++/C language standard versions.  These same C++/C language standards are used by Objective-C and Objective-C++ in CMake project.

### Expected:

Objective-C and Objective-C++ are strict supersets of C and C++ respectively, and CMake added official support for these as languages in 3.16.5, there should be no warnings for associated C++/C language standard versions.

### CMake Tools Log

[cpptools] Unknown language: -std=c++1z
[cpptools] Unknown language: -std=c11

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.16.5
- **VSCode Version**: 1.43.0
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: clang11

**Comment by andreeis** [comment]
Closing this report since this is fixed in 1.4.
