### ISSUE TITLE
Unhandled Promise rejection: ... Cannot read property 'length' of undefined {}

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#1110]
- **Operating System**: Windows 10
- **VSCode Version**: 1.42.1
- **CMake Tools Extension Version**: 1.3.1

One of our users is just getting started with a CMake project using VS Code.  He sees this exception:

    [rollbar] Unhandled exception: Unhandled Promise rejection: build TypeError: Cannot read property 'length' of undefined {}

What might be the cause of this?

Could the error message be improved?

**Comment by bobbrow** [comment]
If you go to "Help" -> "Toggle Developer Tools" from the menu bar, do you see a callstack in the console?  If you could share that with us, that would help us locate exactly where the error is.

**Comment by bobbrow** [comment]
I might have found the error in our telemetry.  I have a PR open for it: https://github.com/microsoft/vscode-cmake-tools/pull/1113

**Comment by DavidA2014** [comment]
@bobbrow Hopefully this is what you need:
[kay.txt](https://github.com/microsoft/vscode-cmake-tools/files/4313874/kay.txt)

**Comment by DavidA2014** [comment]
Is there a workaround?

**Comment by bobbrow** [comment]
Can you try pointing to a specific version of cmake using the `cmake.cmakePath` setting?

**Comment by bobbrow** [comment]
(this looks like the same issue I just submitted a fix for)

**Comment by DavidA2014** [comment]
CMake was not installed. We've installed it now and the exception does not occur.
