### ISSUE TITLE
[loc][Query][vscode-azure-sphere-tools] Localizability of string: 0; "package.cmake-tools.command.cmake.cleanRebuildAll.title"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#1111]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Clean Rebuild All Projects

File:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
What does "Clean Rebuild All Projects" mean?
It can be "Clean 'rebuilding all projects'"?
Or "Clean-rebuilding 'all projects'"? (like "clean-installing")
Would you please confrim that "Clean" can be understood as 'completely' just like a 'clean boot?"

All the affected resource ids:

0; "package.cmake-tools.command.cmake.cleanRebuildAll.title"
0; "package.cmake-tools.command.cmake.outline.cleanConfigureAll.title"

**Comment by bobbrow** [comment]
It means to run the "Clean Rebuild" command on all projects.  So the translation should be similar to "Clean Rebuild", but also adding that this command applies to all projects.

**Comment by andreeis** [comment]
@PDostalek, please reactivate this issue if more details are needed for the translation.

**Comment by PDostalek** [comment]
Thank you @andreeis

**Comment by PDostalek** [comment]
@andreeis 

does it mean "Clean Rebuild   of All Projects" or "Clean and Rebuild All Projects"?
does   it mean "Clean Reconfigure of All Projects" or "Clean and   Reconfigure All Projects"?

I suppose the 1st one, please confirm

**Comment by andreeis** [comment]
Yes, first one.
