### ISSUE TITLE
 [loc][Query][vscode-azure-sphere-tools] Localizability of string: 0; "./src/tree.error.update.code.model.on.nonexist.folder"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#1112]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Could you help please? Thanks!**

Source:
Updating code model on folder that does not yet exist?

File:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Please, explain better this sentence.
Do we need the question mark in this string?

**Comment by bobbrow** [comment]
We don't need the question mark.  I will remove it.

**Comment by PDostalek** [comment]
Could you please tell us the meaning of this sentence?

**Comment by andreeis** [comment]
@xisui-MSFT , maybe this error message is not needed after all? What do you think? A short explanation might be confusing for the user seeing it in the log window. A long and clear explanation might not be worth it. The system recovers. How often and under what circumstances this would happen?
Or changing it with a logging message (not an error) about "Creating folder X".
What do you think?

**Comment by xisui-MSFT** [comment]
@andreeis Ideally this should never happen. It's fine to change it to a log message, although that would just be a little bit harder to debug.

**Comment by PDostalek** [comment]
Any news @bobbrow ?

**Comment by bobbrow** [comment]
This is an error that happens when we try to load the outline for a project that has not been loaded by the extension yet.  The "code model" is the data structure that we use to populate the outline.

I just changed the English message to "Updating code model on folder that has not yet been loaded."

**Comment by PDostalek** [comment]
Thanks @bobbrow
