### ISSUE TITLE
how to add "build->install" option to build targets?

### ISSUE THREAD

**Issue by eachout** [microsoft/vscode-cmake-tools#1117]
question:
When I use this tool in Windows, build->install is available to choose.
It's very useful cuz I have a lot of additional scripts to install before debug.
![image](https://user-images.githubusercontent.com/9478695/76590158-4ab92900-6527-11ea-9f90-2987254577e8.png)

But when I use this tool in wsl with the same project, build->install disppeared....
Pls help!
![image](https://user-images.githubusercontent.com/9478695/76589760-0d07d080-6526-11ea-8e6e-6ef0cf94b1e3.png)

**Comment by andreeis** [comment]
I am not reproducing this. I tried to define the install target as similar as I see in your snippet. It appears fine from within my WSL environment.
If you still have trouble with this, maybe you can craft a standalone repro for us, in case there are other factors involved that we didn't identify.

**Comment by hitagisol** [comment]
I recently switch into VsCode and meet the same problem when trying to compile my project. It seems the install option will not appear if your install command in cmake do not has a "target", aka. you only use install to copy necessary files to the target directory. Then I figure out I can use Command Palette (Ctrl+Shift+P) and choose "CMake:install" to manually run the install command.

**Comment by bobbrow** [comment]
Unfortunately, we do not have enough information to investigate this issue.  @eachout, if you can provide more information for us (perhaps a project we can clone or download), then we can investigate further.  Thank you.
