### ISSUE TITLE
FEATURE REQUEST: Option to clear terminal before 'Compile active file'

### ISSUE THREAD

**Issue by BlakeTheAwesome** [microsoft/vscode-cmake-tools#1122]
### Brief Issue Summary

There is currently an option to `Clear Output Before Build` which clears the output window "CMake/Build" when you run the `CMake: Build` command, but there is no option to clear the output when running `CMake: Compile Active File` which has its output in the terminal window.

I would like an option to clear the output before compiling the active file, either by clearing the terminal, or making that command redirect to the same "CMake/Build" output window used by the build command.

### Expected:

1. Run `CMake: Compile Active File`
2. Scroll to top of terminal window to find the first error to fix

### Apparent Behavior:

1. Run `CMake: Compile Active File`
2. Scroll to top of terminal window and see errors from an earlier run
3. Manually clear the terminal and try again

**Comment by bobbrow** [comment]
Would there be any concern with having the setting be interpreted to clear both the output and the terminal?  The change to support that is easy enough.

**Comment by BlakeTheAwesome** [comment]
I'd certainly be fine with that.
It's probably what most people would expect to happen.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.

**Comment by mqtthiqs** [comment]
Hello, I found this issue google for a way to clear the Output tab when Building+running.
The new option does clear the output when running "CMake: Build" but not when running "CMake: Run without debugging". Woudn't it be more consistent if the option also acted on the other ways to build?
