### ISSUE TITLE
Wrong "Ninja" generator selected when I select "Visual Studio Community 2019 Release - amd64"

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [microsoft/vscode-cmake-tools#1123]
### Brief Issue Summary

When I select "Visual Studio Community 2019 Release - amd64" as Kit, vscode-cmake-tools switch to the "Ninja" CMake generator instead of "Visual Studio 16 2019" with platform "x64".

### Expected:

1. F1 -> CMake: Select a Kit -> Visual Studio Community 2019 Release - amd64
2. Output should display: 
  - Switching to kit: Visual Studio Community 2019 Release - amd64
  - Configuring using the "Visual Studio 16 2019" CMake generator with platform "x64" and toolset {}
3. F1 -> CMake: Configure
4. Build solution should be a visual studio solution for VS 2019

### Apparent Behavior:

1. F1 -> CMake: Select a Kit -> Visual Studio Community 2019 Release - amd64
2. Output displays: 
  - Switching to kit: Visual Studio Community 2019 Release - amd64
  - **Configuring using the "Ninja" CMake generator**
3. F1 -> CMake: Configure
4. **Build solution is a ninja solution targetting VS2019 compiler**

### CMake Tools Log

When selecting kit:
```
[driver] Switching to kit: Visual Studio Community 2019 Release - amd64
[cms-client] Configuring using the "Ninja" CMake generator
```

When configuring:
```
[main] Configuring folder: LightPathExpressions-git 
[cms-client] Configuring using the "Ninja" CMake generator
[cmake] The C compiler identification is MSVC 19.23.28106.4
[cmake] The CXX compiler identification is MSVC 19.23.28106.4
[cmake] Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
[cmake] Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
[cmake] Detecting C compiler ABI info
[cmake] Detecting C compiler ABI info - done
[cmake] Detecting C compile features
[cmake] Detecting C compile features - done
[cmake] Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
[cmake] Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
[cmake] Detecting CXX compiler ABI info
[cmake] Detecting CXX compiler ABI info - done
[cmake] Detecting CXX compile features
[cmake] Detecting CXX compile features - done
[cmake] Configuring done
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.
[cmake] 
[cmake] 
[cmake] Generating done
```

### Platform and Versions

- **Operating System**: Windows 10 1903 64bits
- **CMake Version**: 3.16.5
- **VSCode Version**: 1.43.0
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Visual C++ 2019

### Other Notes/Information

As a side note: everything is fine with Visual Studio 2017, the solution generated is correct. What is strange is that my cmake-tools-kits.json seems correct, VS 2017 and VS 2019 entries are similar:
```json
{
    "name": "Visual Studio Community 2017 Release - amd64",
    "visualStudio": "05246a08",
    "visualStudioArchitecture": "amd64",
    "preferredGenerator": {
      "name": "Visual Studio 15 2017",
      "platform": "x64"
    }
 }
```
```json
{
    "name": "Visual Studio Community 2019 Release - amd64",
    "visualStudio": "da769ae6",
    "visualStudioArchitecture": "amd64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64"
    }
}
```
So I don't understand what vscode-cmake-tools is doing on top of the configuration of kits that could lead it to generate a Ninja solution instead of a VS2019 one.

**Comment by bobbrow** [comment]
Thank you for reporting this issue.  It is currently being tracked by #1084.

**Comment by Celeborn2BeAlive** [comment]
Gosh, I was the one reporting the previous issue #1084 Totally forgotten -_-' I probably need some sleep.
Sorry for my own duplicate and thank you for your work.
