### ISSUE TITLE
CMake Cache Entries with double quotes produce error with CMake Tools

### ISSUE THREAD

**Issue by tmaslach** [microsoft/vscode-cmake-tools#1124]
### Brief Issue Summary
We have set statements like this in our CMakeLists.txt files:
`set("PROJECT_COMPONENT:${PROJECT_NAME}" controller CACHE STRING)
`

This causes the CMakeCache entry to have double quotes in it: 
`"PROJECT_COMPONENT:controller":STRING=controller
`

I believe the double quotes cause the following warning to get generated in the CMake output:
`[rollbar] Cache entry '"PROJECT_COMPONENT' has unknown type: 'controller":STRING' {}
`

If I had only a few of these, it wouldn't be an issue.  But, we have hundreds of entries that are getting double quotes, meaning the output is overwhelming.  I assume these messages are being printed by VSCode while it is extracting the values from CMakeCache.txt

Is there any way to fix this? Or at a minimum turn the warnings off?  The project builds fine, but many get confused because of the long list of messages.

### Expected:
If we have a set statement like this in our CMakeLists.txt file:
`set("PROJECT_COMPONENT:${PROJECT_NAME}" controller CACHE STRING)
`
I would expect no errors to be produced in the CMake/build output terminal.

### Platform and Versions
- **Operating System**: Linux and Windows 
- **CMake Version**: cmake-3.16.4
- **VSCode Version**: 1.43
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: GCC & VSProfessional

**Comment by tmaslach** [comment]
I took a look at the code and this looked pretty easy to fix.  So, I will initiate a pull request.  Please let me know if you have issues with the code.  Tests all passed on Travis for linux, I'm waiting on Mac, but I don't expect any issues.

**Comment by bobbrow** [comment]
Thanks for the PR.  We'll take a look. 😃

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by tmaslach** [comment]
It's looking good so far!  

It is wonderful to not see 1000+ cache entry errors after building! :)

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
