### ISSUE TITLE
Ensure settings changes are honored in the extension

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#1127]
When you change certain settings, it is expected that they take effect immediately.  There are some settings where this is not the case.  We need to do an audit of all the settings and make sure that they are being updated properly.

**Comment by SchweizS** [comment]
`cmake.cmakeCommunicationMode` is not updated

**Comment by RReverser** [comment]
Just adding from my comment on #630: `cmake.configureSettings` is also subject to this issue.

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.5.0 which was published today.
Let us know if you encounter any issues with this release.
