### ISSUE TITLE
Confusing notification "configure projects on opening"

### ISSUE THREAD

**Issue by guillemglez** [microsoft/vscode-cmake-tools#1131]
When the suggest _"Configure this project?"_ is rejected after opening, a _"Never configure projects?"_ notification is given.

I understand the point of it, but I think that the given actions' effect is confusing:
![image](https://user-images.githubusercontent.com/25482726/77050917-bdfce800-69ca-11ea-93b6-27793b19cb2a.png)

I'd suggest something like _"Configure projects on opening?"_ => [_Never_ | _Not in this workspace_] to be more clear towards the end user.

**Comment by bobbrow** [comment]
I agree we should revisit this.  It would also be nice if we could word this in a way that we just have to display one message instead of two.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
