### ISSUE TITLE
Enabling code analysis?

### ISSUE THREAD

**Issue by thomthom** [microsoft/vscode-cmake-tools#1136]
Is there any way to enable code analysis via this VSCode/C++/CMakeTools workflow?
Something akin to what you get in Visual Studio?

**Comment by bobbrow** [comment]
Not currently.  For context, are you developing just on Windows, or do you also do linux/mac development?

**Comment by bobbrow** [comment]
And I'm not saying it's not doable through `tasks.json` or some other mechanism.  I'm just saying it's not integrated into any extensions yet.

**Comment by thomthom** [comment]
I am doing Windows an Mac development. VSCode with CMakeTools has been a really nice workflow improvement over using two different editors on each platform (in particularly it's been nice not having to use XCode). (And I'm also excited that Remote development is now in beta for mac, that will save me from using other remote tools in many cases.)

It would be nice with cross platform code analysis, but I'm guessing the VS code analysis might be tied to msvc? In any case, my main platform is Windows, so having VS code analysis only on Windows would still be a nice thing to have.

I have been sniffing at clang's tools. With VS's recent clang support it might be a more reasonable cross platform code analysis tool. Though I haven't yet tried to use the clang compiler on Windows.

One of the code analysis ruleset I liked to us in VS that I'd hope to get set up on VSCode was the Cpp Core Guidelines.

**Comment by bobbrow** [comment]
I see that clang-tidy offers support for some of the cpp core guidelines. https://clang.llvm.org/extra/clang-tidy/checks/list.html

I recently put together a basic `tasks.json` that runs some basic code analysis tools (on linux).  The only trouble right now is that it most of them only run on a per-file basis (not as part of the build).  Perhaps this will be of help:

```
{
    "tasks": [
        {
            "type": "shell",
            "label": "valgrind leak check",
            "command": "valgrind",
            "args": [
                "--leak-check=yes",
                "${command:cmake.launchTargetPath}"
            ],
            "problemMatcher": []
        },
        {
            "type": "shell",
            "label": "clang-tidy",
            "command": "clang-tidy-8",
            "args": [
                "${file}"
            ],
            "problemMatcher": [
                {
                    "fileLocation": "autoDetect",
                    "base": "$gcc"
                }
            ]
        },
        {
            "type": "shell",
            "label": "cppcheck",
            "command": "cppcheck",
            "args": [
                "${file}"
            ],
            "problemMatcher": [
                {
                    "pattern": {
                        "regexp": "^\\[(.+):(\\d+)\\]:\\s*\\((.+)\\)\\s*(.*)$",
                        "file": 1,
                        "location": 2,
                        "severity": 3,
                        "message": 4
                    },
                    "fileLocation": "autoDetect"
                }
            ]
        }
    ],
    "version": "2.0.0"
}
```
