### ISSUE TITLE
Problem with Remote SSH

### ISSUE THREAD

**Issue by HeejinJeong** [microsoft/vscode-cmake-tools#1137]
### Brief Issue Summary
Hi, there
Thanks for your hard work.
I would like to ask you one question.
I'm trying to use CMake plug-in with Remote SSH.
And when I'm trying to configure my project, I'm having below error messages.
Could you advise me how to solve the issue? Not sure it is because of wrong configuration.

### Expected:
1. Set up a new project with Remote SSH
2. Install CMake plugin
3. open a project on the server and try to configure it with CMake plug in
4. everything should work without any issue ( if cmakefile is correct )

### Apparent Behavior:
When I clicked the button for configuration, I got below messages.
[rollbar] Unhandled exception: Unhandled Promise rejection: Changing build variant Error: connect ENOENT /tmp/cmake-server-0.13223042035826182 {}
[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant Error: connect ENOENT /tmp/cmake-server-0.02756772912171601 {}

### CMake Tools Log

[variant] Loaded new set of variants
[kit] Successfully loaded 5 kits from /home/konghk78/.local/share/CMakeTools/cmake-tools-kits.json
[main] Configuring folder: myProject 
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: connect ENOENT /tmp/cmake-server-0.8017231712958777 {"folder":{"uri":{"$mid":1,"fsPath":"/home/konghk78/work/myProject","external":"file:///home/konghk78/work/myProject","path":"/home/konghk78/work/myProject","scheme":"file"},"name":"myProject","index":0}}
[main] Configuring folder: myProject 
[rollbar] Unhandled exception: Unhandled Promise rejection: Changing build variant Error: connect ENOENT /tmp/cmake-server-0.9413902446518128 {}
[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant Error: connect ENOENT /tmp/cmake-server-0.4001499207086423 {}
[kit] Found Kit: GCC for c89 7.5.0
[kit] Found Kit: GCC for c99 7.5.0
[kit] Found Kit: GCC 7.5.0
[kit] Found Kit: GCC 7.5.0
[kit] Found Kit: GCC for x86_64-linux-gnu 7.5.0
[kit] Found Kit: GCC for x86_64-linux-gnu 7.5.0
[kit] Successfully loaded 5 kits from /home/konghk78/.local/share/CMakeTools/cmake-tools-kits.json
[main] Configuring folder: myProject 
[rollbar] Unhandled exception: Unhandled Promise rejection: Changing build variant Error: connect ENOENT /tmp/cmake-server-0.13223042035826182 {}
[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant Error: connect ENOENT /tmp/cmake-server-0.02756772912171601 {}

### Platform and Versions
- **Operating System**: Windows10 ( server Ubuntu 18.04 )
- **CMake Version**: 3.10.3
- **VSCode Version**: 1.43.1
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: g++ (GCC) 7.4.0

**Comment by bobbrow** [comment]
Are you able to use a newer version of cmake?  I tried the same configuration (Windows 10 -> Ubuntu18.04) and I do not have any problem though I have cmake 3.14.6 on my linux machine.
