### ISSUE TITLE
Terminal is focused after running "CMake: Run Without Debugging"

### ISSUE THREAD

**Issue by STaRDoGGCHaMP** [microsoft/vscode-cmake-tools#1138]
### Brief Issue Summary
When running the `CMake: Run Without Debugging` command, the terminal gets focused after the program has finished its execution.

### Expected:

The extension should not put focus on the terminal or an option should be provided to control this behavior.

### Apparent Behavior:

Focus is put on the terminal and no option is given to control this behavior.

### Platform and Versions

- **Operating System**: `Windows 10`
- **CMake Version**: `3.16.19112601-MSVC_2`
- **VSCode Version**: `1.43.1
fe22a9645b44368865c0ba92e2fb881ff1afce94
x64`
- **CMake Tools Extension Version**: `0.0.17`
- **Compiler/Toolchain**: `Visual Studio 2019 version 16.5`

**Comment by bobbrow** [comment]
I believe the code is supposed to just show the active terminal window.  Is it taking focus away from another window?  It seems easy enough to fix, but not a high priority relative to the other bugs we're looking at right now.  If someone wants to submit a PR, we'll review it.

**Comment by STaRDoGGCHaMP** [comment]
> Is it taking focus away from another window?
Yes. Most importantly, it takes away focus from the editor.
