### ISSUE TITLE
Outline view - ignore folder

### ISSUE THREAD

**Issue by thomthom** [microsoft/vscode-cmake-tools#1142]
Is it possible to tell the CMake Outliner to ignore a directory?

I got a project where I use a in-project build directory (yes, I know it's generally recommended with an out-of-build directory).

It appear that when you have a in-project build directory the Outliner picks up `CMakeLists.txt` files from the build directory:

![image](https://user-images.githubusercontent.com/192418/77630990-40962200-6f4c-11ea-9efc-300212e18831.png)

**Comment by bobbrow** [comment]
It looks like a bug in the outline when CTest is enabled.
