### ISSUE TITLE
Provide a sensible error message when CMake is not installed

### ISSUE THREAD

**Issue by JanPokorny** [microsoft/vscode-cmake-tools#1146]
### Brief Issue Summary

When I try to run `CMake: Configure` without CMake installed, no useful error message is provided.

### Expected:

1. Execute `CMake: Configure` without having CMake installed
2. Extension says `You don't have CMake installed you dummy`

### Apparent Behavior:

Extension says `[rollbar] Unhandled exception: Unhandled Promise rejection: configure TypeError: Cannot read property 'length' of undefined {}`

**Comment by alan-wr** [comment]
![image](https://user-images.githubusercontent.com/68377984/87739338-31e0bd00-c812-11ea-94db-260e94befefe.png)

I test it with CMake Tools v1.4.1

Report Error Message like this:
Bad CMake executable "". Is it installed or settings contain the correct path (cmake.cmakePath)?

I think it is fine, this defect should be closed.
