### ISSUE TITLE
Support ARM IntelliSenseModes for vscode-cpptools extension

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cmake-tools#1155]
The extension vscode-cpptools is adding ARM IntelliSenseModes https://github.com/microsoft/vscode-cpptools/issues/4271.

Support the new IntelliSenseModes when they are available.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
