### ISSUE TITLE
Target debugging is no longer supported with the legacy driver

### ISSUE THREAD

**Issue by okanakyuz** [microsoft/vscode-cmake-tools#1157]
Hello I get flowing message "Target debugging is no longer supported with the legacy driver" 
The command is: Command + Shift + P ==> CMAKE:Debug

Operating System: MacOs Catalina 10.15.4
CMake Version: cmake version 3.17.0 {CMake suite maintained and supported by Kitware (kitware.com/cmake)}
VSCode Version: Version: 1.43.2 { Electron: 7.1.11 }
CMake Tools Extension Version:  1.3.1
Compiler/Toolchain: CLang 11.0.0

**Comment by bobbrow** [comment]
Can you check your settings and see what is set for `cmake.cmakeCommunicationMode`?  You shouldn't be on the legacy driver by default if you have a version of CMake greater than 3.7.

It's also possible that the extension didn't find your CMake binary?  We have a setting `cmake.cmakePath` where you can point us to the binary if it's not being auto-detected.

**Comment by okanakyuz** [comment]
I uninstall Cmake tools 1.5.2 It doesn't give any error but It freezes without stoping on any breakpoint. 

[build] Build finished with exit code 0
[proc] Executing command: /usr/bin/lldb-mi --version
[proc] Executing command: /usr/bin/gdb --version
[proc] Executing command: /usr/bin/lldb --version
[proc] Executing command: /usr/bin/lldb --version

I don't have lldb-mi on macOS system

**Comment by bobbrow** [comment]
The extension is looking for binaries, but this is unrelated to the problem you're having.  Could you take a look at my comment above and answer the questions I asked?
