### ISSUE TITLE
Unknown C standard control flag

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#1159]
I'm using CmakeTools 1.3.1 with Cadence/Tensilica cross compiler 14.02 (it's a variant of GCC/Clang).   I'm getting...

[cpptools] Unknown C standard control flag: -std=c++11

I need the flag so it compiles correctly (their build defaults to C++98).  It seems everything functions properly except the error/warning received after configure and build.

_Originally posted by @schnort in https://github.com/microsoft/vscode-cmake-tools/issues/926#issuecomment-609914742_

**Comment by bobbrow** [comment]
Hi @schnort

The warning message implies that a C++ standard is being set for a C file.  Can you share a bit more information about your project?  Are you able to build it in your Terminal window?

**Comment by schnort** [comment]
Ah, that might be the trick.  I added             

add_compile_options(-std=c++11)        

I should have used 

add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-std=c++11>)

I changed to that and the issue went away.

Thanks for the tip in the right direction.  I never would have found that.

**Comment by bobbrow** [comment]
Glad to help!
