### ISSUE TITLE
launch.json parameters do not fully support cmake settings

### ISSUE THREAD

**Issue by matthewdhunt** [microsoft/vscode-cmake-tools#1165]
### Brief Issue Summary

Although you can refer to various CMake (vector-of-bool plugin) settings in launch.json, they cannot contain any variables.  For example, in a launch.json, it is valid to write:

     {
        "name": "MFDApp Launch",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "${config:cmake.buildDirectory}/MFDApp/MFDApp.exe",
        <etc...>
    },

However, if the cmake.buildDirectory contains any variables itself, this will not work.  For example:

     "cmake.buildDirectory": "../SomeDir/${buildKit}/${buildType}"

If this is done, when you attempt to launch the program, it will look for folders literally named ${buildKit}/${buildType} without substitution, which will of course fail.  This means you can't use any relative paths in the cmake variables if they appear in the launch.json.

### Expected:

When launching an application, VSCode would properly substitude paths for variables such as ${buildKit} or ${buildType}

### Apparent Behavior:

When launching an application, VSCode treats cmake variables as string literals.

### Platform and Versions

- **Operating System**: Windows 10 or Ubuntu 18.04
- **CMake Version**: 3.12 or 3.14
- **VSCode Version**: 1.44.0
- **CMake Tools Extension Version**: 1.3.1

**Comment by bobbrow** [comment]
Does it work if you use:
```
"cmake.buildDirectory": "../SomeDir/${command:cmake.buildKit}/${command:cmake.buildType}"
```

**Comment by bobbrow** [comment]
Though looking past the specific details of the question, you may also be interested to know that you can update your `launch.json` to use:
```
  "program": "${command:cmake.launchTargetPath}"
```
which will point to the target selected through the status bar UI or the "Set Debug Target" command.

**Comment by matthewdhunt** [comment]
No, I'm not sure exactly what it does if you use ${command:cmake.buildKit}/${command:cmake.buildType}.  It seems to replace the entire contents of what is in " " with an absolute path of just "build" or something like that.  It definitely doesn't just substitute the variables.  I'll see if I can figure out what it's doing in a test project without messing with the build folder of the main project.

But, the tip of command:cmake.launchTargetPath is very helpful!  That might resolve my use case although not really this bug.
