### ISSUE TITLE
Prevent CMake Tools activation when CMakeLists.txt is not in the workspace folder or at cmake.SourceDirectory

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#1167]
Since CMake Tools changed the activation condition from CMakeLists.txt found in the root to anywhere inside the workspace, we get into situations when it activates for non CMake repos. One example is when a non CMake repo contains some tests that have CMake files.

Preventing the activation or programmatically deactivating the extension might not be possible, but at least we would like to disable the features until the state of the workspace changes (it becomes a real valid CMake repo).

Integrate this functionality with the message box asking about QuickStart or cmake.sourceDirectory, providing a third option, to ignore this folder.

**Comment by parched** [comment]
This looks great, thank you. It's not clear to me though if this is something I can set in setting.json. I would like to share share my multiroot workspace with my team and they not get the popup about missing CMakeLists at all. Will that be possible?

**Comment by bobbrow** [comment]
Not in 1.4.0.  If you want to open a new issue to request we add a setting for it, we can consider doing that for a future release.

You can try out the experience today by installing the beta on our [releases page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta)

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
