### ISSUE TITLE
CMake tools default keybinding conflicts with default editor keybinding

### ISSUE THREAD

**Issue by mtrp12** [microsoft/vscode-cmake-tools#1170]
### Brief Issue Summary

![image](https://user-images.githubusercontent.com/6695345/79037499-45253080-7c04-11ea-8f1b-010a46abefc5.png)

vscode cmake tools out of the box key binding does contradictory action compared to the editor keybinding. As a result, breakpoint triggers even if I select run without debug from editor menu. Also, debugging started from editor using launch.json does not end after pressing SHIFT+f5(editor default). Instead it runs cmake tools: run without debugging. While I can rebind the keys, I think default keybindings should not conflict with main editor defaults. In my observation, I noticed cmake tools keybinding is overriding editor keybinding. If that is so, it should have the same keybinding for same task as main editor. Alternatively, a non conflicting keybinding.

### Expected:

Editor keybindings to work.

### Apparent Behavior:

CMake tools key binding triggers

### Platform and Versions

- **Operating System**: Ubuntu 18.04
- **CMake Version**: 3.10
- **VSCode Version**: 1.44.0
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: gcc7.4

**Comment by bobbrow** [comment]
That is a problem.  The tricky thing about this is that (I think) this extension was using the keybinding before VS Code was, so changing it now could confuse our existing users.  We currently employ a strategy to enable this keybinding only when a CMake project is open in the editor.

The fix for SHIFT+F5 is simple though.  It just needs to add logic to not be active during a debug session.

**Comment by ghuser404** [comment]
@bobbrow I think anyone coming from the VS background, expects F5 to start with debugger and Ctrl+F5 to start without debugger. It's very unfortunate that the defaults are mixed, and I hope they can be changed at some point.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.

**Comment by marcomeyerVFX** [comment]
doesn't work for me, it looks like the change was undone by another commit 52b4ccfec5f8bf39ee2ddaf5e89398a8dbd8c77b

**Comment by bobbrow** [comment]
☹️ @andreeis can you add `!inDebugMode` condition back to the `shift+f5` keybinding in `package.json`?

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.4.1 which was published today.
Let us know if you encounter any issues with this release.
