### ISSUE TITLE
Running Targets (with arguments) Without a Debugger

### ISSUE THREAD

**Issue by thomthom** [microsoft/vscode-cmake-tools#1177]
### Brief Issue Summary

I'm playing with libFuzzer and I'm looking for convenient ways to trigger it from VSCode + CMakeTools. What I'm running into is that the target needs arguments for max time and corpus input etc. When I use "Running Targets Without a Debugger" it will execute the fuzzer with no arguments which will cause it to run for a long time (unless it finds anything.)

### Expected:

Would be good if it was possible to configure the arguments to the target being run. 
A project will have different targets, so I was hoping to find a per-target solution.

**Comment by bobbrow** [comment]
The extension doesn't have a mechanism to enable this right now.  You can use `tasks.json` to configure this in the meantime.  You will need to invoke the "Debug: Run (Start without Debugging)" command instead of the CMake command to make this work.
![image](https://user-images.githubusercontent.com/12818240/79389515-58494080-7f23-11ea-8762-e61c14bf312a.png)

An example `tasks.json` here:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Target",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/path/to/target",
            "args": [ "arg1", "arg2" ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false
        }
    ]
}
```

**Comment by thomthom** [comment]
I presume you meant `lanch.json` for that example, right?

Meanwhile I found a Task setup that works for now. It doesn't auto detect targets, not let me expand CMake variables, but does the trick for the specific case:

```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run Fuzzer",
      "type": "shell",
      "command": "${workspaceFolder}/build/${input:buildConfig}/fuzzers/${input:fuzzer}",
      "args": [
        "-max_total_time=${input:fuzzerMaxTime}",
        "${workspaceFolder}/fuzzers/corpus/${input:fuzzer}/"
      ],
      "group": "test",
      "presentation": {
        "reveal": "always"
      },
      "runOptions": { "reevaluateOnRerun": false }
    }
  ],
  "inputs": [
    {
      "id": "buildConfig",
      "type": "pickString",
      "description": "Choose build configuration",
      "options": ["Debug", "Release"],
      "default": "Release"
    },
    {
      "id": "fuzzer",
      "type": "pickString",
      "description": "Choose fuzzer",
      "options": ["fuzz_parse_license"]
    },
    {
      "id": "fuzzerMaxTime",
      "type": "promptString",
      "description": "Max total time (seconds)",
      "default": "10"
    }
  ]
}
```

This uses 3 inputs to pick configuration, target and max run time. Thanks for this comment;
https://github.com/microsoft/vscode/issues/65066#issuecomment-447304260 - I learned about `"runOptions": { "reevaluateOnRerun": false}` and can easily rerun last run using the Rerun Last Task without having to enter input every time.

**Comment by bobbrow** [comment]
> I presume you meant `lanch.json` for that example, right?

Yes, I did.  I updated my comment.

**Comment by andreeis** [comment]
Closing as dupe of https://github.com/microsoft/vscode-cmake-tools/issues/924.
