### ISSUE TITLE
Output not cleared before build when running tests

### ISSUE THREAD

**Issue by nbraem** [microsoft/vscode-cmake-tools#1179]
### Brief Issue Summary

When running tests, Build is run first, but output is not cleared, although `Clear Output Before Build` is turned on.

### Expected:

1. Turn on `Clear Output Before Build` option.
2. Run `CMake: Run Tests`
3. Run `CMake: Run Tests` again

I expect that output is cleared every time that tests are run, because it firsts builds.

### Apparent Behavior:

Output is not cleared, although it's building and `Clear Output Before Build` is turned on

### Other Notes/Information

Clearing output is especially useful when running tests, because you typically run tests repeatedly and want to inspect the output of of failing tests, which can be large. So you typically search in the output, but don't want to find matches in the previous output.

If you don't think clearing output before test is appropriate if the option `Clear Output Before Build` is turned on, I suggest addding an option `Clear Output Before Run Tests`

**Comment by Stephenmccaul** [comment]
Not sure if this is worth a separate issue but the output is also not cleared when "Launch debugger for selected target" is clicked..

I think it safe to say that if "Clear Output Before Build" is true the output should be cleared before any cmake, build or test invocation.

**Comment by andreeis** [comment]
@Stephenmccaul, no let's not open a new issue for this, it's an easy fix all around. Thank you for pointing out the additional scenario.
