### ISSUE TITLE
No indication of active workspace in CMake project outline.

### ISSUE THREAD

**Issue by SchweizS** [microsoft/vscode-cmake-tools#1183]
### Summary
Currently there is no indication which workspace is active in multi root workspaces.

### Expected
![active_workspace](https://user-images.githubusercontent.com/18433748/79553646-12b08300-809d-11ea-8fbb-0ae9d5b55e4b.JPG)

### Suggestion
Add an active indication and a context menu/button to change workspace in the tree view.

### Required changes:
see: [Schweizs/vscode-cmake-tools/fix-issue-1183](https://github.com/SchweizS/vscode-cmake-tools/tree/fix-issue-1183)

i'm not quite sure how to localize this, so no pull request yet.
i guess new loca keys for "Workspace Folder" and "Workspace Folder (active)".
"Workspace Folder" is currently hardcoded.

### Platform and Versions
- **VSCode Version**:  1.44.0
- **CMake Tools Extension Version**: 1.3.1 / 2a56936a86fdd10ae1e197470b3dc1ccb0660095

**Comment by andreeis** [comment]
@SchweizS, thank you for looking into this. Please start the PR and we will help with the changes needed for localization.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
