### ISSUE TITLE
Gripes

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode-cmake-tools#1186]
* Doesn't syntax highlight CMakeLists.txt.
* Doesn't understand that some nested project directories may not have their CMakeLists.txt at VCS top-level.

**Comment by SchweizS** [comment]
Syntax highlightig isn't support by the extension (yet), but there is an open issue #534.
Currently you need a separate extension to do that (e.g. [CMake](https://marketplace.visualstudio.com/items?itemName=twxs.cmake))

The second point might be related to #533 and #1167.

**Comment by bobbrow** [comment]
@SchweizS is correct.  We are tracking these requests with other issues.  I invite you to upvote those issues to help us with prioritization.  To upvote, click on the reaction button for the first comment in the issue and add a 👍.

Thank you!
