### ISSUE TITLE
VSCode C++ IntelliSense bug when adding new files

### ISSUE THREAD

**Issue by Yuri6037** [microsoft/vscode-cmake-tools#1187]
### Brief Issue Summary

VSCode C++ tools bugs when adding new files in a project manged by ms-vscode.cmake-tools.

When adding a new hpp/cpp file in the project workspace CMakeLists.txt, the VSCode C++ IntelliSense gets bugged and refuses to process correctly the new hpp/cpp file. It is needed to close VSCode, run cmake .. inside the build folder in a Powershell and then re-open VSCode in order to get it to work.

### Expected:

When saving the CMakeLists.txt of a CMake sub-directory, VSCode C++ tools should automatically be refreshed with the new files. That behaviour is already fine under Visual Studio Community 2019.

### Apparent Behavior:

VSCode C++ tools IntelliSense does not get refreshed with the new files and requires full editor reload with powershell console in order to rebuild the cmake project.

### Platform and Versions

- **Operating System**: Windows 10 x64
- **CMake Version**: cmake version 3.16.0-rc3
- **VSCode Version**: 1.42.1
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Visual Studio Community 2019 Release - amd64

### Other Notes/Information

Tested on a projected first initialized with cmake Visual Studio 2019 generator.

**Comment by andreeis** [comment]
Another workaround (besides reloading) is to configure after editing the CMakeLists.txt. Hopefully not that inconvenient before we get to fix this.

**Comment by Yuri6037** [comment]
I can try to do it myself, at least if I can get a VSCode development environment working...

**Comment by andreeis** [comment]
That would be great. Let us know if you have any questions about the code base or if you encounter any issues during developing the fix for this issue. We'll be happy to review a PR when you send one.

**Comment by Yuri6037** [comment]
I've got something working in local where I can add new files, edit my CMake, and right on CMake save it runs CMake configure which then updates intellisense, a pretty quick fix

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
