### ISSUE TITLE
CMakeTools is missing to send some Include paths to CppTools

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#1194]
Migrating from CppTools GitHub: https://github.com/microsoft/vscode-cpptools/issues/5266 

@bobbrow I believe there is some path under /opt/target/1.1.1/sysroots/corei7-64-target-linux/usr/include/ that CMake is using to build, but for which they don't send it to our includePath -- we only get the "Custom" folder under that path. The 2 compiler-provided includePaths appear to be correct. Bob, can you move this to the CMake Tools repo? I'm not familiar enough to CMake Tools to know if there's a way to get more diagnostics from there.

**Comment by bobbrow** [comment]
I'm not confident this is our issue yet.  We can transfer the issue over if we determine that it is.
