### ISSUE TITLE
Latest develop branch broken

### ISSUE THREAD

**Issue by Yuri6037** [microsoft/vscode-cmake-tools#1195]
### Brief Issue Summary

I just tried to setup this extension in development mode, but everytime I run it on existing CMake C++ projects it fails with the following error in console:
"The path to the compiler for one or more source files was not found in the CMake cache. If you are using a toolchain file, this probably means that you need to specify the CACHE option when you set your C and/or C++ compiler path"

### Expected:

I suppose it should not have thrown an error.

### CMake Log

[variant] Loaded new set of variants
[kit] Successfully loaded 14 kits from C:\Users\Yuri Edward\AppData\Local\CMakeTools\cmake-tools-kits.json
[main] Configuring folder: Framework 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE "-Hc:/Users/Yuri Edward/BlockProject3D/Framework" "-Bc:/Users/Yuri Edward/BlockProject3D/Framework/build" -G "Visual Studio 16 2019"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
[cmake] Writing module descriptor "BPF.cmake"...
[cmake] -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: C:/Users/Yuri Edward/BlockProject3D/Framework/build/Tests/googletest-download
[cmake] Microsoft (R) Build Engine version 16.3.1+1def00d3d for .NET Framework
[cmake] Copyright (C) Microsoft Corporation. All rights reserved.
[cmake] 
[cmake]   Performing update step for 'googletest'
[cmake]   Current branch master is up to date.
[cmake]   No configure step for 'googletest'
[cmake]   No build step for 'googletest'
[cmake]   No install step for 'googletest'
[cmake]   No test step for 'googletest'
[cmake]   Completed 'googletest'
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: C:/Users/Yuri Edward/BlockProject3D/Framework/build

### CMake Tools Log (part of cause it's so large)

[Extension Host] [CMakeTools] 2020-04-22T15:48:21.555Z [debug] [cmakefileapi-parser] Found index files: ["cache-v2-b1d7fbf2ef37f81c93f2.json","codemodel-v2-1569c2dd023714517cd5.json","index-2020-04-22T15-48-21-0535.json","target-ALL_BUILD-Debug-0670742a43bdc391a3ac.json","target-ALL_BUILD-Debug-40d7e487fdc067424fb5.json","target-ALL_BUILD-Debug-4d40e66a6ee1da5af6ae.json","target-ALL_BUILD-Debug-60d2de6adefdb97c4e4f.json","target-ALL_BUILD-Debug-722527c0848867bc3d4a.json","target-ALL_BUILD-Debug-d6448b12b0266ef81938.json","target-ALL_BUILD-Debug-e1ff50ed44238dd91de9.json","target-ALL_BUILD-MinSizeRel-0670742a43bdc391a3ac.json","target-ALL_BUILD-MinSizeRel-40d7e487fdc067424fb5.json","target-ALL_BUILD-MinSizeRel-4d40e66a6ee1da5af6ae.json","target-ALL_BUILD-MinSizeRel-60d2de6adefdb97c4e4f.json","target-ALL_BUILD-MinSizeRel-722527c0848867bc3d4a.json","target-ALL_BUILD-MinSizeRel-d6448b12b0266ef81938.json","target-ALL_BUILD-MinSizeRel-e1ff50ed44238dd91de9.json","target-ALL_BUILD-Release-0670742a43bdc391a3ac.json","target-ALL_BUILD-Release-40d7e487fdc067424fb5.json","target-ALL_BUILD-Release-4d40e66a6ee1da5af6ae.json","target-ALL_BUILD-Release-60d2de6adefdb97c4e4f.json","target-ALL_BUILD-Release-722527c0848867bc3d4a.json","target-ALL_BUILD-Release-d6448b12b0266ef81938.json","target-ALL_BUILD-Release-e1ff50ed44238dd91de9.json","target-ALL_BUILD-RelWithDebInfo-0670742a43bdc391a3ac.json","target-ALL_BUILD-RelWithDebInfo-40d7e487fdc067424fb5.json","target-ALL_BUILD-RelWithDebInfo-4d40e66a6ee1da5af6ae.json","target-ALL_BUILD-RelWithDebInfo-60d2de6adefdb97c4e4f.json","target-ALL_BUILD-RelWithDebInfo-722527c0848867bc3d4a.json","target-ALL_BUILD-RelWithDebInfo-d6448b12b0266ef81938.json","target-ALL_BUILD-RelWithDebInfo-e1ff50ed44238dd91de9.json","target-BPF-Debug-3da0815842daf1f41de9.json","target-BPF-MinSizeRel-6b2019cc7f79c85caffc.json","target-BPF-Release-fc70ddd484e681bf0d2a.json","target-BPF-RelWithDebInfo-e9b5dfa9bf0d18e712f4.json","target-BPF.Tests-Debug-e84a71df20fee75ecf11.json","target-BPF.Tests-MinSizeRel-db18c94ecf850dea93c3.json","target-BPF.Tests-Release-9759a015c38d1849eaf7.json","target-BPF.Tests-RelWithDebInfo-691ae0896e4fa85002f0.json","target-BPF.Tests.Console-Debug-65adb3227a3e81204cad.json","target-BPF.Tests.Console-MinSizeRel-3216315061b89c2092e0.json","target-BPF.Tests.Console-Release-6480f01ec803738ce7d0.json","target-BPF.Tests.Console-RelWithDebInfo-9f66edc3b84a63eadda6.json","target-gmock-Debug-ebdbc2baa4ecd3e0474d.json","target-gmock-MinSizeRel-84da96f7922067f2bf2e.json","target-gmock-Release-daf0c30e155c21394e10.json","target-gmock-RelWithDebInfo-2a656450448f79d37935.json","target-gmock_main-Debug-a256323d76e2d52a7672.json","target-gmock_main-MinSizeRel-a8afa204a8af81be4efe.json","target-gmock_main-Release-37838694602b0582a1f0.json","target-gmock_main-RelWithDebInfo-84bc9db7bb01acdece71.json","target-gtest-Debug-bf79790c84b5e4235f57.json","target-gtest-MinSizeRel-1db559508d79c9bb9bcf.json","target-gtest-Release-4b830a233798a06d2eb4.json","target-gtest-RelWithDebInfo-7a06b0c11bc87b066b87.json","target-gtest_main-Debug-894255e88dec91b43609.json","target-gtest_main-MinSizeRel-577927f3bb5157b7304b.json","target-gtest_main-Release-b08a7e7a3fb37c751464.json","target-gtest_main-RelWithDebInfo-f5445d3fbb779913daa3.json","target-ZERO_CHECK-Debug-3764af2b22833ece3f36.json","target-ZERO_CHECK-MinSizeRel-3764af2b22833ece3f36.json","target-ZERO_CHECK-Release-3764af2b22833ece3f36.json","target-ZERO_CHECK-RelWithDebInfo-3764af2b22833ece3f36.json"] (at SingletonLogger._log (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:61604:29))
console.ts:137 [Extension Host] [CMakeTools] 2020-04-22T15:48:21.863Z [debug] [cache] Reading CMake cache file c:/Users/Yuri Edward/BlockProject3D/Framework/build/CMakeCache.txt (at SingletonLogger._log (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:61604:29))
console.ts:137 [Extension Host] [CMakeTools] 2020-04-22T15:48:21.866Z [debug] [cache] Parsing CMake cache string (at SingletonLogger._log (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:61604:29))
console.ts:137 [Extension Host] varsForVSInstallation path:'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community' version:16.3.29411.108 host arch:amd64 - target arch:x64 (at varsForVSInstallation (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:60563:13))
console.ts:137 [Extension Host] [CMakeTools] 2020-04-22T15:48:22.535Z [debug] [cache] Reading CMake cache file c:/Users/Yuri Edward/BlockProject3D/Framework/build/CMakeCache.txt (at SingletonLogger._log (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:61604:29))
console.ts:137 [Extension Host] [CMakeTools] 2020-04-22T15:48:22.536Z [debug] [cache] Parsing CMake cache string (at SingletonLogger._log (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:61604:29))
console.ts:137 [Extension Host] Error running C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat amd64_x64, can not found INCLUDE (at collectDevBatVars (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:60476:17))
console.ts:137 [Extension Host] varsForVSInstallation path:'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community' version:16.3.29411.108 host arch:amd64 - target arch:x64 (at varsForVSInstallation (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:60563:13))
notificationsAlerts.ts:40 The path to the compiler for one or more source files was not found in the CMake cache. If you are using a toolchain file, this probably means that you need to specify the CACHE option when you set your C and/or C++ compiler path
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:582
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] updateCustomBrowseConfiguration (at c:\Users\Yuri Edward\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:35773:21)
console.ts:137 [Extension Host] provideCustomConfiguration (at DefaultClient.<anonymous> (c:\Users\Yuri Edward\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:35880:25))
console.ts:137 [Extension Host] Error running C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat amd64_x64, can not found INCLUDE (at collectDevBatVars (c:\Users\Yuri Edward\Documents\VSCode_Cmake_Tools\vscode-cmake-tools\dist\main.js:60476:17))
console.ts:137 [Extension Host] provideCustomConfiguration (at DefaultClient.<anonymous> (c:\Users\Yuri Edward\.vscode\extensions\ms-vscode.cpptools-0.27.0\dist\main.js:35880:25))

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: cmake version 3.16.0-rc3
- **VSCode Version**: 1.42.1
- **CMake Tools Extension Version**: The latest version from develop branch time is 5:53 PM UTC+1
- **Compiler/Toolchain**: Visual Studio Community 2019 Release - amd64

### Other Notes/Information

I ran those tests with a version of the extension with a single console.log to check it was actually running the correct extension and I ran a git checkout to revert to the initial downloaded version and same error.
Note that the project on which this extension is tested works fine when using the latest extension released in VSCode store.

**Comment by andreeis** [comment]
Yes, it should not have complained and it's possible one of our last commits introduced this. We will investigate and fix this behavior. Anyway, you don't need a kit when developing in CMake Tools. To prevent any more CMake Tools operations being run just set "Do not use a kit". Let us know if anything else is blocking you from running the extension in development mode.

**Comment by andreeis** [comment]
@Yuri6037, sorry I understood wrong. You are running the development mode just fine, right? Are you hitting breakpoints in the code bsae?
It's just that when you load any existing project you see that error, correct?

I do not reproduce for latest develop branch and a small CMake project created with QuickStart.
You might have some settings regarding kits and toolchains. 

We need to be able to reproduce that error to identify if there's something you do wrong on your side or if the extension has a bug.

Also, for you to work on a fix for issue 1187 you can ignore that error. Is it blocking the development of the fix in any way?

**Comment by andreeis** [comment]
I noticed something in your log and I have a suspicion, investigating. I hope you are unblocked though.

**Comment by andreeis** [comment]
Oh, one of our last PRs introduced a kits breaking change. We will make sure to document that when we release. You need to rescan for kits.
Also we have another GitHub issue tracking a different workflow regarding scanning for kits (like always scan for kits in the background which if it was in, it would have  prevented you from having this problem).
I have some issues with the machine where I was testing this (lost connection). I will get back to confirm whether you need to also re-select your kit and clean reconfigure after scanning for kits. That is what I did before I had the project work fine but not all the steps might be necessary. While trying to redo the steps I lost the VM. In the mean time, you can get unblocked.

**Comment by Yuri6037** [comment]
Thank you indeed that fixed it CTRL+SHIFT+P > type kits > Scan for kits.
Also I have something in local.

**Comment by bobbrow** [comment]
Leaving this open until the PR is complete.
