### ISSUE TITLE
CMake Build Type Not Passed to Configure

### ISSUE THREAD

**Issue by P-N-L** [microsoft/vscode-cmake-tools#1197]
### Brief Issue Summary

I am trying to build my project with build type RelWithDebInfo, using the build variant button at the bottom of VSCode.

### Expected:

CMake configures with the appropriate build type (via -DCMAKE_BUILD_TYPE=<build type>) and builds with the appropriate build type (--config <build type>), in my case RelWithDebInfo.

### Apparent Behavior:

CMake does not configure with the appropriate build type, causing it to always default to Debug. However, the builds do use the appropriate build type, in my case RelWithDebInfo. Since this does not match the incorrectly-used Debug type from configure time, I get an error that the build files are not set up properly.

### Platform and Versions

- **Operating System**: Windows 10 x64
- **CMake Version**: 3.14.7
- **VSCode Version**: 1.44.2
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Visual C++ 2017 x64

### Other Notes/Information

The current workaround that I am using is manually passing the correct build type to the configure command manually via the cmake.configureArgs setting in VSCode. I use -DCMAKE_BUILD_TYPE=RelWithDebInfo and it seems to work. However, every time I want to change build types between Debug and RelWithDebInfo, I have to make sure this configure argument is kept in sync with the build variant button/setting, which makes it far less convenient than if it were handled automatically.

**Comment by andreeis** [comment]
@P-N-L, I don't reproduce this with CMake Tools 1.3.1 on a simple project (created via Quick Start). Maybe there is something specific in your code base that is causing the configuration process to not work correctly. If you can share that, maybe it will help.
Also, let us see a verbose "CMake/Build" log (from Output pane in VSCode). Maybe we will notice something.
Does the same happen for a clean reconfigure (command ">CMake: Delete cache and reconfigure")?

**Comment by P-N-L** [comment]
Thanks for your reply. I set up a really simple test project and realized that it did not have the same problem as my actual project, so I did a bit more looking around and think I understand my issue a bit better.

For reasons that I only partially understand, my project is set up to only be configured with one build type allowed allowed at a time, which is achieved by taking in the CMAKE_BUILD_TYPE (which we assume is Debug by default) and setting the CMAKE_CONFIGURATION_TYPES to match only the CMAKE_BUILD_TYPE. So, if you want to build Debug, you configure Debug; and if you want to build RelWithDebInfo, you configure RelWithDebInfo. There is no way to configure once and be able to build for both.

I do believe that this use case runs into a little trouble with #128, but that is a fairly minor inconvenience, because once our build type has been set, we want it to be locked to that single value anyways. No big deal.

The real issue for my project is that since the build variant is not passed to CMake at configure time, my project can't use that information, which is why I have to provide it manually as a configuration argument. I do not think that it would cause any problems for other projects to add -DCMAKE_BUILD_TYPE=<current_build_variant> at configure time, since it is just additional information. If that does not seem unreasonable and the CMake Tools folks would like, I can take a shot at putting that change together.

If you need more information or my explanation didn't make sense, I can spend more time getting that example put together.

Thank you.

PS - When I was fiddling with verbose output, I did notice a typo (that I assume is in CMake Tools): "[driver] Runnnig pre-configure checks and steps", "Running" is spelled wrong. =)

**Comment by andreeis** [comment]
If it's not too inconvenient, a repro would help us debug and identify the root cause faster.  Your explanation sounds reasonable.

**Comment by P-N-L** [comment]
No problem. Please see the link to the repo below. I tried to add enough commentary and logs to explain the problem.

Please let me know if there is anything else I can do to help, and thanks!

https://github.com/P-N-L/dummy-project

**Comment by bobbrow** [comment]
Just checking... are you using the Ninja generator?

According to https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html, this value is only needed for single-config generators.  I suspect we can always provide it as long as we make sure it doesn't affect the Visual Studio generator incorrectly.

**Comment by P-N-L** [comment]
Unfortunately, I am trying to handle Visual Studio (as well as Make for other platforms). We are more or less trying to make Visual Studio behave in a similar manner to those single-configuration generators by setting the CMAKE_CONFIGURATION_TYPES to only match the CMAKE_BUILD_TYPE.

**Comment by andreeis** [comment]
I reproduce how the defines in CMakeLists are ignored (which is the other bug) but I don't reproduce the configure versus build mismatch you mention. Also, in the logs I produce with your repro, I am seeing that the first "message" you wrote does return something, is not empty like in your logs. 
I have no other generator special settings anywhere. I tried several kits, 2017, 2019, x86, amd64.
Also, from your RelWithDebInfo log, the build fails because of toolset old version. 
What kit do you have, when you mention "Visual C++ 2017 x64", that is Community? When you installed VS did you change default inclusion of components?

**Comment by P-N-L** [comment]
Interesting... not sure how you would be getting a CMAKE_BUILD_TYPE for the first message when I don't... It looks like I missed the actual cmake command used for the Debug Configure command, I have added that to the repo and pushed. When I added the missing lines, the files' contents are now identical; no information about the build type is passed at configure time. Does the "Executing command" line when you configure with different build types have something extra/different?

The old toolset version is an odd manifestation of a build type mismatch that I have seen before when I have made a mistake configuring and building. It occurs when the project is configured for (and limited to) one build type, but a build is attempted for another. Since the RelWithDebInfo configure incorrectly defaults to a Debug build type, when the RelWithDebInfo build is started, it gets confused because the RelWithDebInfo files that it expects to find do not exist.

For this example, I am using Visual Studio Professional 2017 x64. However, I have the same issue for Visual Studio Professional 2015 x64. I have added these files to the repo as well. They were both installed for my by the IT department, and with the exception of installing updates, I do not believe that either of them has been modified from their original installations.

**Comment by andreeis** [comment]
Ok, comparing the two lines I realized I did have Ninja generator picked, but not because I set it anywhere. All releases up to 1.3.1 had a bug that if Ninja is installed, it's always picked even if a preferred generator is defined. We fixed this in 1.4. You did not have Ninja installed but that could be a workaround for you?
What's important is that I reproduced the problem and we are going to fix it.
Thanks.

**Comment by P-N-L** [comment]
Thank you, that is great news!

I do not have Ninja installed but can definitely look into that as a temporary workaround. Good to know about the bug and upcoming fix.

If there is anything else I can do to support, please let me know. I appreciate the effort and responsiveness.

**Comment by piwaneczko** [comment]
Hi

Try to add following CMake configure setting into setting.json:
```
"cmake.configureSettings": {
    "CMAKE_BUILD_TYPE": "${buildType}"
},
```
It helped for me.

**Comment by P-N-L** [comment]
This issue has not been resolved yet.

**Comment by gcampbell-msft** [comment]
@P-N-L Does this suggestion: https://github.com/microsoft/vscode-cmake-tools/issues/1197#issuecomment-825449848, work for you? Thanks!

**Comment by gcampbell-msft** [comment]
@P-N-L Are you using Kits or Presets?

**Comment by P-N-L** [comment]
I am selecting a Kit in the VSCode UI for Visual Studio Build Tools 2022. I set up my example project again today to test it and the behavior is the same. I did notice that the problem appears to be Windows-specific; the CMAKE_BUILD_TYPE variable was correctly populated on Linux.

**Comment by Yingzi1234** [comment]
@P-N-L Thank you for your github issue! We are trying to reproduce your problem but it is not reproducing, the reproduction steps are as follows, could you help us to see if it is a problem with the steps?

**Repro steps:**
1. Open this project https://github.com/P-N-L/dummy-project
2. Click CMake> Configure> Debug> RelWithDebInfo to configure this project
3. Check what the CMake-Build-Type is the Output window

**Actual result:**
The CMake-Build-Type is RelWithDebInfo
Repro steps video: https://microsoft-my.sharepoint.com/:i:/p/v-frankwang/EVev9GTRdDRKszlojOlqgysBWtauVf9z_zy2yNdWLsE29w?e=HZbaJu

**Comment by P-N-L** [comment]
Thanks for reaching out. I am having trouble accessing your video.

I tried again today on a Windows Server 2022 machine (which I expect would behave equivalently to Windows 10 or 11) and followed these steps:

1. Clone the repo.
2. Ensure the appropriate kit is selected (I am using Visual Studio Build Tools 2022).
3. Select `RelWithDebInfo`, `Release, or `MinSizeRel` (anything other than `Debug`).
4. Click "Delete Cache and Reconfigure"

The output is below, showing that the `CMAKE_BUILD_TYPE` variable is not populated at configure time. If it were, there would be `RelWithDebInfo` at the end of the first message, and it would not default to `Debug` in the next message.

![image](https://github.com/microsoft/vscode-cmake-tools/assets/30122827/883e6877-7dfd-47b8-b6fd-cd75c5aeba21)

I am using:

VSCode IDE:

```
Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.20348
```

CMake Tools extension:

```
Name: CMake Tools
Id: ms-vscode.cmake-tools
Description: Extended CMake support in Visual Studio Code
Version: 1.17.17
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools
```

CMake extension:

```
Name: CMake
Id: twxs.cmake
Description: CMake langage support for Visual Studio Code
Version: 0.0.17
Publisher: twxs
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=twxs.cmake
```

**Comment by bobbrow** [comment]
Based on what I see in your screenshot, you are using one of the Visual Studio generators (-G "Visual Studio 17 2022").  These generators are "multi-config" generators, so you cannot set CMAKE_BUILD_TYPE during "Configure."  The build type can only be set during the Build.

The option you have available to influence build types during Configure for a multi-config generator is [CMAKE_CONFIGURATION_TYPES](https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIGURATION_TYPES.html).  This lets you select which build types you want the generator to make available for the Build.

If you want to do something with CMAKE_BUILD_TYPE in your CMakeLists.txt for the Configure step you will have to use a "single-config" generator like "Ninja" for those to take effect.

**Comment by P-N-L** [comment]
@bobbrow Thanks for responding. I think I understand what you are saying and why the behavior is how it is. I don't have much experience with using multi-config generators (or at least it seems like we have not been using them correctly!), but it makes sense that at configure time you would not have a single explicit build type since that would be used at build time instead.

I think this issue can be closed.
