### ISSUE TITLE
Parsing of cmake-kits.json fails regularly

### ISSUE THREAD

**Issue by andreasWallnerIFX** [microsoft/vscode-cmake-tools#1204]
### Brief Issue Summary

Quite often I get the error message `[kit] Failed to parse cmake-kits.json: {1}` when changing the `cmake-kits.json` file. After saving the file a few times (without modifications) parsing will succeed.
Sometimes this also seems to happen on start of VSCode.

### Expected:

Consistent behavior if `cmake-kits.json` does not change. In the example below I'd expect the parsing of the file to succeed all the time.

### CMake Tools Log

Log from saving a few times, `cmake.loggingLevel` is at `trace`.

    [kit] Reading kits file c:\work\git\poquid\.vscode\cmake-kits.json
    [kit] Failed to parse cmake-kits.json: {1}
    [kit] Reading kits file c:\work\git\poquid\.vscode\cmake-kits.json
    [kit] Failed to parse cmake-kits.json: {1}
    [kit] Reading kits file c:\work\git\poquid\.vscode\cmake-kits.json
    [kit] Successfully loaded 2 kits from c:\work\git\poquid\.vscode\cmake-kits.json
    [kit] Reading kits file c:\work\git\poquid\.vscode\cmake-kits.json
    [kit] Successfully loaded 2 kits from c:\work\git\poquid\.vscode\cmake-kits.json

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.15.1
- **VSCode Version**: 1.45.0-insider
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Keil ARMClang & Keil ARMCC with custom toolchain file

### Other Notes/Information
`cmake-kits.json` being used (with minor modifications to my productive one, but the same issue can be observed here):

    [
      {
        "name": "Keil armclang Chip1",
        "toolchainFile": "C:/work/git/cmake-keil/toolchain-keil-armclang.cmake",
        "cmakeSettings": {
          "TOOLCHAIN_PATH": "C:/ToolsRep",
          "DERIVATIVE": "Chip1",
          "LIB_PATH": "../lib"
        }
      },
      {
        "name": "Keil armcc Chip1",
        "toolchainFile": "C:/work/git/cmake-keil/toolchain-keil-armcc.cmake",
        "cmakeSettings": {
          "TOOLCHAIN_PATH": "C:/ToolsRep",
          "DERIVATIVE": "Chip1",
          "LIB_PATH": "../lib"
        }
      }
    ]

I know that the provided log is most likely quite insufficient to debug the issue. If there is any way I can provide additional information I'd be happy to do so.

**Comment by andreeis** [comment]
I can't reproduce this. Thinking of what else could be different and of what other info from your might help us find the root cause.

**Comment by andreasWallnerIFX** [comment]
This actually happens to multiple people in my organization, so your guess regarding environment might be correct. I just can't think of what this would be...

**Comment by andreeis** [comment]
Not giving up :).
Is the same happening if you remove the custom kits you have defined in the json file?
I found this similar issue https://stackoverflow.com/questions/59030041/json-parse-gives-error-occasionally-on-parsing-string, but you have no escaping in the snippet you shared. Are those two the only custom kits you define?

I'm still thinking of what else we can do and another idea comes to mind to help us find the root cause. Add some logging related to all it's happening before parsing the json. If it's too inconvenient for you to make your own CMake Tools for this test we can provide a vsix. But I'm thinking now on what to log and where, I'll get back to you.

In the mean time, how is parsing going without your custom kits.

**Comment by andreasWallnerIFX** [comment]
Just checked with an empty array in the file:

    [
    ]

This also fails regularly when parsing.

    [kit] Failed to parse cmake-kits.json: {1}
    [kit] Failed to parse cmake-kits.json: {1}
    [kit] Failed to parse cmake-kits.json: {1}
    [kit] Failed to parse cmake-kits.json: {1}
    [kit] Failed to parse cmake-kits.json: {1}
    [kit] Successfully loaded 0 kits from c:\work\git\poquid\.vscode\cmake-kits.json

It should not be a problem to run build my own CMake Tools, but I won't have time during company time ATM, so earliest during the weekend.

**Comment by andreeis** [comment]
Ok we are going to, brainstorm more about this.

**Comment by andreeis** [comment]
When you have a chance, if you say it's no problem to experiment with CMake Tools yourself, you can modify in src\kits.ts, readKitsFile the line with "failed.to.parse", like this:
log.error(localize('failed.to.parse', 'Failed to parse {0}: {1} : {2}', "cmake-kits.json", e.message, e.stack));
Send us back the output of that. 
And I don't know why the code as is now prints {1} for the exception, we'll make sure that will be printing something useful in future.

**Comment by andreasWallnerIFX** [comment]
@andreeis I'll do so, we have a public holiday on Friday anyways...

**Comment by andreasWallnerIFX** [comment]
@andreeis Here the stacktrace that you asked me for:

    [kit] Failed to parse cmake-kits.json: Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: "" : SyntaxError: Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
      at error (c:\work\git\vscode-cmake-tools\dist\main.js:38451:25)
      at word (c:\work\git\vscode-cmake-tools\dist\main.js:38788:13)
      at value (c:\work\git\vscode-cmake-tools\dist\main.js:38888:56)
      at Object.parse (c:\work\git\vscode-cmake-tools\dist\main.js:38903:18)
      at Object.readKitsFile (c:\work\git\vscode-cmake-tools\dist\main.js:61774:26)
      at async KitsController.readKits (c:\work\git\vscode-cmake-tools\dist\main.js:61947:31)

It weirdly seems that it's much harder to recreate the problem in the much slower running extension development host, but that is just a feeling, no hard data. The `cmake-kits.json` that I used was the one from the initial bugreport.

PS: In addition to the steps on the 'How to contribute' page of the help I had to do a `npm install yarn`, you might want to add that.

**Comment by andreeis** [comment]
Still no idea. I am seeing various other complains about json failing to parse occasionally but so far nothing that would help me with ideas for your scenario.

Can you try to temporarily get rid of your local .vscode/cmake-kits.json and move its content to the user level one? Wondering if this happens for the main central kits file.

Another thing you can do if it's not too inconvenient is to create or point us to a small standalone repro.

**Comment by andreasWallnerIFX** [comment]
I did some additional checking, and it seems that the issue occurs during reading of the file, not the parsing. I added an additional output in the error case to dump the read file content:

    ...
    } catch (e) {
      log.error(localize('failed.to.parse', 'Failed to parse {0}: {1} : {2}', "cmake-kits.json", e.message, e.stack));
      log.error(content_str)
      return [];
    }
    ...

Testing with a cmake-kits.json just containing `[]` I can see that the `content_str` is empty.

    [kit] Failed to parse cmake-kits.json: Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: "" : SyntaxError: Unexpected EOF at line 1 column 2 of the JSON5 data. Still to read: ""
      at error (c:\work\git\vscode-cmake-tools\dist\main.js:38451:25)
      at word (c:\work\git\vscode-cmake-tools\dist\main.js:38788:13)
      at value (c:\work\git\vscode-cmake-tools\dist\main.js:38888:56)
      at Object.parse (c:\work\git\vscode-cmake-tools\dist\main.js:38903:18)
      at Object.readKitsFile (c:\work\git\vscode-cmake-tools\dist\main.js:61774:26)
      at async KitsController.readKits (c:\work\git\vscode-cmake-tools\dist\main.js:61948:31)
    [kit] 

I've not seen a case where only part of the file was read, always either all or nothing.
Just a wild guess: could it be that it's reading the file in a state where the new content was not yet written? (assuming the write is not atomic)

**cmake-kits.json vs user level cmake-tools-kits.json:**
The issue occurs for the user-level file as well, it seems to be more infrequent though.

**Repro**
I'd be happy to provide a repository, but after the check of the user-level file I'm not sure that would help... I can reproduce the issue by opening a new workspace and placing a `.vscode/cmake-kits.json` file containing `[]` into it. Then I just repeatedly save the file. If you think it help I'd not have a problem generating that. Or just save the user-level kits file repeatedly.

**Comment by andreeis** [comment]
Thanks, that is a good idea for our investigation. No need for any additional information.

**Comment by andreasWallnerIFX** [comment]
Maybe useful: I'm more and more guessing that this is a problem with our virus scanner. (MS Defender) - I'm trying to get in touch with our IT to check if we can disable it for purposes of checking if that really is the reason.

I can pretty much get around the issue by inserting a sleep for 100 milliseconds before reading the file. (Interestingly I then get the log message for successful parsing 2-3 times).

**Comment by Riphiphip** [comment]
I have encountered a similar issue.

### Platform:
- **Operating system:** Windows 10
- **VSCode version:** 1.48.0-insider
- **Node version:** 12.13.0
- **CMakeTools version:** 1.4.1
Also happens in vscode version 1.47.1

Same symptoms and steps to reproduce as above. Error appears to be caused by the file being read as empty (checked by logging read file content). Setting a small delay (5-20ms) before reading the file seems to fix the issue.

**Comment by Neumann-A** [comment]
same issue here, deactivating Windows Defender does not help. (Working on a M2 SSD)
