### ISSUE TITLE
Support GNU language standard for vscode-cpptools extension

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cmake-tools#1208]
The extension vscode-cpptools is adding support for using GNU language standard to query a compiler for GNU defines. https://github.com/microsoft/vscode-cpptools/issues/2782

Have cmake-tools also use GNU language standard for vscode-cpptools.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
