### ISSUE TITLE
Stopping a build generates false dirty state that cause useless reconfigure

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#1214]
Private variables like _hadConfigurationChanged (cms-driver.ts) or _needsReconfigure (cmfileapi-driver.ts) are initialized with true when the driver is constructed (makes sense). Then they get set to false whenever a relevant change happens (variant, target or kit change).
When the build is stopped before finishing, the driver gets destroyed and recreated, so that for the next build operation (or launch or debug), the extension detects a false dirty state and reconfigures.

Need to rewrite parts of this implementation to avoid this.

Not a regression.

**Comment by prudhomm** [comment]
This issue is really a problem, not only does it redo cmake but it also triggers in some cases a full recompilation which may take a lot of time. The current solution is to wait for the Build step to finish and trigger again Build for example.
