### ISSUE TITLE
CMake Error: Could not create named generator with VSCode, CMake, mingw

### ISSUE THREAD

**Issue by singhgaurav1302** [microsoft/vscode-cmake-tools#1215]
CMake version 3.17.2
VS Code version 1.44.2
mingw64 version 7

I am trying to build my project using cmake in vscode on Windows. Compiler used are provided by mingw64.

Build task in tasks.json fails giving below error
CMake Error: Could not create named generator

tasks.json
    "tasks": [
        {
            "label": "My CMake Release",
            "type": "shell",
            "options": {
                "cwd": "${workspaceRoot}/build"
            },
            "command": "cmake",
            "args": [
                "-G 'MinGW Makefiles' .."
            ],
        },

settings.json
{
    "C_Cpp.updateChannel": "Insiders",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "window.zoomLevel": 0,
    "cmake.cmakePath": "C:\\Program Files\\CMake\\bin",
    "cmake.mingwSearchDirs": [
            "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin"
        ],
    "cmake.generator": "-G MinGW Makefiles",
    "cmake.configureOnOpen": true
}

cmake-tools-kits.json
[
  {
    "name": "GCC 8.1.0",
    "compilers": {
      "C": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\gcc.exe",
      "CXX": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\g++.exe"
    },
    "preferredGenerator": {
      "name": "MinGW Makefiles"
    },
    "environmentVariables": {
      "CMT_MINGW_PATH": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin"
    }
  },
  {
    "name": "GCC for i686-w64-mingw32 8.1.0",
    "compilers": {
      "C": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\i686-w64-mingw32-gcc.exe",
      "CXX": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\i686-w64-mingw32-g++.exe"
    },
    "preferredGenerator": {
      "name": "MinGW Makefiles"
    },
    "environmentVariables": {
      "CMT_MINGW_PATH": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin"
    }
  }
]

On powershell if I run cmake -G "MinGW Makefiles" .. it works but through VSCode

**Comment by bobbrow** [comment]
Can you try removing `-G` from the `cmake.generator` setting?  And you shouldn't need the `tasks.json` file to configure with cmake because this extension doesn't make use of it.

**Comment by singhgaurav1302** [comment]
Using tasks.json I was trigerring CMake to generate Makefiles and run generator to generate MinGW Makefiles.
Now If I remove the CMake task from tasks.json 
1. how do I generate MinGW Makefiles?
2. Where should I include CMake then?

**Comment by bobbrow** [comment]
The standard workflow is to use the buttons in the status bar to select your compiler, configure the project, and build & debug targets.

You can also use the built-in commands for selecting "kits" (compilers) and configuring/building with CMake if you prefer a more keyboard-centric development environment.
