### ISSUE TITLE
Compile Active File chooses wrong build folder

### ISSUE THREAD

**Issue by juxeii** [microsoft/vscode-cmake-tools#1217]
### Expected:

1. Push button Compile Active File
2. The active single source file being compiled

### Apparent Behavior:

1. Push button Compile Active File
2. Wrong build folder chosen in opened terminal window, resulting in compile errors of missing include files

### Platform and Versions

- **Operating System**: Linus
- **CMake Version**: 3.16.2
- **VSCode Version**: 1.44.2
- **CMake Tools Extension Version**: 1.31
- **Compiler/Toolchain**: gcc 9.0

Hi,

whenever I want to compile a .cpp file with the button `Compile Active File` I get a compile error.
The reason is that the active terminal(which is opened automatically if none is there) path is wrong.
My build folder is in `${workspaceRoot}/build` but the button opens the terminal in `${workspaceRoot}`.
This cannot work since then the relative include paths are wrong.
Which setting do I need to change in cmaketools?

Funny enough, if I change the path in the active terminal manually(`cd build`) then all subsequent compilations are fine.
So I think that cmaketools opens a new terminal if none is existed and chooses the wrong path.
If there is already a terminal, cmaketools uses that one and does not change the current path and the compile command executes fine.

**Comment by andreeis** [comment]
I can't reproduce this. Is it possible for you to share with us a small contained project?

**Comment by juxeii** [comment]
I am sure that I misconfigured something, but what could possibly go wrong in the settings?
