### ISSUE TITLE
Workspace Button doesn't always show up

### ISSUE THREAD

**Issue by SchweizS** [microsoft/vscode-cmake-tools#1219]
## Brief Issue Summary
Workspace Button doesn't show up in Statusbar if a second directory is added to a workspace.

### workaround
Reopen VS-Code after adding a second directory

### Expected:
Workspace Button gets visible

### Apparent Behavior:
Workspace Button is hidden.

### Reproduction steps
1. create a new workspace (only one directory)
2. add a second directory to that workspace
3. check if the button is visible

### Platform and Versions
- **Operating System**:  Windows 10
- **CMake Version**:  3.17.0
- **VSCode Version**: 1.44.2
- **CMake Tools Extension Version**:  0ee9aaf2c972ff231e332f72afc15d67d08abd72 1.3.1

### Other Notes/Information
#1200

**Comment by andreeis** [comment]
I am not able to reproduce the missing button. Your description is good and clear, I understand it. I tried several ways that could fit the above steps. Let's figure out if maybe a trigger factor is missing from the repro scenario.

**Comment by SchweizS** [comment]
i don't know what i did differently yesterday, but all 3 versions i tried it with work today. (dev/1.3.1/#1200)

i'll try to find the trigger as soon as i'm able to reproduce it myself again.
