### ISSUE TITLE
Compile active file parses spaces as argument

### ISSUE THREAD

**Issue by mjvankampen** [microsoft/vscode-cmake-tools#1221]
### Brief Issue Summary

If compile_commands.json contains a few extra spaces these are parsed as an argument when using Compile Active File.

I.e. compilecommands.json containing:
```
{
  "directory": "C:/build",
  "command": "C:\\compiler\g++.exe   -IC:/include -o src/main.cpp.o -c C:\\src\\main.cpp",
  "file": "C:\\src\\main.cpp"
}
```
results in: 
```
C:\\compiler\g++.exe "" -IC:/include -o src/main.cpp.o -c C:\\src\\main.cpp
```

Note the extra spaces/quotes after g++.exe. This fails as g++ takes this as an empty argument and cannot find a file with no name. 

I am aware I need to look into why this happens but the project compiles just fine. Not sure if this is just cmake or something on my end, I did try various cmake versions and compilers.

### Platform and Versions
- **Operating System**: Windows
- **CMake Version**: 3.16.3 & 3.16.5
- **VSCode Version**: 1.44.2
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: QNX 7 (based on GCC 5.4.0), Mingw, make and ninja

**Comment by andreeis** [comment]
I am not able to reproduce this problem. Can you help with providing us a standalone project that would manifest this issue?

**Comment by Trass3r** [comment]
Yes spaces are not handled properly. I have a codebase that defines a macro containing spaces: `-DMYMACRO=\"\\\"Text with spaces\\\"\"`. Compile active file does not work because of that.
I had similar issues in the cxx compiler explorer extension which I solved with `spawn`'s `shell: true`  option.

**Comment by Trass3r** [comment]
@andreeis 
```cmake
add_executable(test test.cpp)
target_compile_definitions(test PRIVATE -DFOO="a b")
```

**Comment by elahehrashedi** [comment]
follow this issue from here: https://github.com/microsoft/vscode-cmake-tools/issues/1414
