### ISSUE TITLE
Project directory structure for "modern CMake"

### ISSUE THREAD

**Issue by ShamanTcler** [microsoft/vscode-cmake-tools#1226]
### Brief Issue Summary
First I am new to VS Code and vscode-cmake-tools, so this may be a case of total ignorance.

In general we try to layout our CMake projects alog the lines of :  https://cliutils.gitlab.io/modern-cmake/chapters/basics/structure.html

So we have dir structure that look like:
- CMakeLists.txt
- docs
- src
  - CMakeLists.txt
  - fred.cpp
  - sue.f90    (Yes we still use FORTRAN)
- test
  - CMakeLists.txt
  - test1.cpp

I am having issues with VS-Code following the hierarchy  .... should it be able to follow the sub dirs?

Thanks.

**Comment by bobbrow** [comment]
This should work fine.  Could you explain what isn't working?

**Comment by ShamanTcler** [comment]
Sorry it took a while to get back to this. I think I have things working fairly well. Let me discuss a few of my issues:

1) My projects can take a while for a clean build, sometimes up to an hour. This makes the single binary "build" dir inconvenient as it gets purged every time you toggle build types.  This little gem get's me around that issue: ( in the settings.json file)
 `cmake.buildDirectory": "${workspaceRoot}/build/${buildType}`

2) I use Conan (conan.io) as my C/C++/FORTRAN package manager across Win/*nix OS ... to get Intellisense to work : ( again in the settings.json file)
```
"C_Cpp.default.includePath": [
        "c:\\Users\\${env.USERNAME}\\.conan\\data\\**",
        "C:\\.conan\\**"
    ]

This last one is a little weird because conan could be installed in two locations.  For a normal user, in $HOME, for my Jenkins build node just on c:\

Overall I am still quite positive on VS Code. I am a mechanical engineer by training and know the value of a tool that feels "right" in your hand as you use it.  (Think of a hammer :), you know what to do with it when you pick it up )

So this tool has to fit in my work flow task list ...

- Check code in/out of Git
- Edit Code
- Build debug/release code
- Generate developer & user doc 
- Run unit test
- Perform static code analysis
- sure I missed something here .....

VS Code seems to do a reasonable job.  ( I may sound jaded but after ~40 yrs in the business you see tools come and go, and it is hard to get TOOOO excited )

Thanks and regards

```

**Comment by andreeis** [comment]
Thank you for the feedback. 
Regarding bullet (2.), you don't need to set any include paths if you allow CMake Tools to be the configuration provider.
Try to set C_Cpp.default.configurationProvider to "ms-vscode.cmake-tools" in your project settings.
Let us know if conan isn't working for you in this case.
