### ISSUE TITLE
cmake.launchTargetPath is sometimes broken when launching vscode from command line

### ISSUE THREAD

**Issue by omcnoe** [microsoft/vscode-cmake-tools#1229]
Using the `${command:cmake.launchTargetPath}` in my launch.json only works when I do `cd myproj; code .`. If I do `code myproj` when I try to start debugging vscode complains `launch: program 'myproj' does not exist`. I'm opening the same directory in vscode in both cases.

The cmake-tools debug button has the same behaviour, though there is an additional issue there preventing debugging from working even when I launch vscode with `code .`. It finds the myproj binary & lldb ok, but the debugging doesn't work (no output, have to kill lldb). I think I spotted an lldb log at some point that said `unrecognized option `--interpreter=mi'`, perhaps this is the issue with the debug button?

Regardless, the behaviour of my launch.json should not break depending on whether I `cd myproj; code .` (works) vs `code myproj` (broken, myproj not found)!

- **Operating System**: macOS 10.15.4
- **CMake Version**: 3.17.2
- **VSCode Version**: 1.45.0
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Apple clang version 11.0.3 (clang-1103.0.32.59)

**Comment by axel-dd** [comment]
I can confirm this. Same problem under linux.

OS: Linux x64 5.4.40-1-MANJARO
CMake Version: 3.17.2
VSCode Version: 1.44.2
CMake Tools Extension Version: 1.3.1
Compiler: gcc version 10.1.0 (GCC)  
Debugger: GNU gdb (GDB) 9.1

**Comment by hubutui** [comment]
I can confirm this issue too.
OS: ArchLinux
cmake: 3.17.3
gcc: 10.1.0
gdb: 9.2
vs code: 1.46.0
cmake tools extension: 1.4.0

**Comment by bobbrow** [comment]
I am unable to reproduce this behavior on Ubuntu 18.04.  The working directory of the terminal at the time vscode is launched hasn't made any difference to me.  Are you still seeing this behavior with the latest version of the extension?

On macOS there have been issues with LLVM no longer distributing the lldb-mi binary required for debugging with our extensions.  The experience should be improved with CMake Tools 1.4.1.

**Comment by hubutui** [comment]
I can confirm that this issue is fixed.
OS: ArchLinux
cmake: 3.18.0
vs code: 1.47.2, The Open Source build of vs code from ArchLinux repo
clang: 10.0.0
gdb: 9.2
cmake tools extension: 1.4.1
