### ISSUE TITLE
How to stop CMakeTools from passing CMAKE_BUILD_TYPE to cmake?

### ISSUE THREAD

**Issue by selassje** [microsoft/vscode-cmake-tools#1231]
Conan will not generate multi config file otherwise.

**Comment by andreeis** [comment]
What generator are you using?
CMake Tools is passing CMAKE_BUILD_TYPE only for single-config generators.
https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html
https://cmake.org/cmake/help/v3.9/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html
