### ISSUE TITLE
CMake project loading error

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cmake-tools#1232]
Issue Type: <b>Bug</b>

win10, msvc142 toolchain, 
c:\\dev\\workspace\\fd1 - is a root of cmake project. I'm working with it in clion for a long time successfully, without any issues. doesn't seem that cmake scripts error there...

"[main] Configuring folder: fd1 
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open TypeError: Cannot read property 'length' of undefined {"folder":{"uri":{"$mid":1,"fsPath":"c:\\dev\\workspace\\fd1","_sep":1,"external":"file:///c%3A/dev/workspace/fd1","path":"/c:/dev/workspace/fd1","scheme":"file"},"name":"fd1","index":0}}
"

Extension version: 1.3.1
VS Code version: Code - Insiders 1.46.0-insider (2b472d1e4aaaecdda5ca96289869f90ae82de3a1, 2020-05-11T10:00:12.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.87GB (5.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andreeis** [comment]
Please confirm if cmake is in the path. We fixed a similar error triggered by that scenario. 
There is also this setting to help the extension find it: cmake.cmakePath.

**Comment by amigo421** [comment]
confirmed. that was an issue, sorry for my inattention
