### ISSUE TITLE
Using command variables in task with CMake Tools

### ISSUE THREAD

**Issue by stlkr** [microsoft/vscode-cmake-tools#1234]
### Brief Issue Summary

Tried to use  this in tasks.json:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "CMake Build",
            "command": "${command:cmake.build}",
            "type": "shell",
            "group": "build",
            "problemMatcher": []
        }
    ]
}
```
Or

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "CMake Build All",
            "command": "${command:cmake.buildAll}",
            "type": "shell",
            "group": "build",
            "problemMatcher": []
        }
    ]
}
```
### Expected:

CMake Tools to build project as when running "CMake: Build" or "CMake: BuildAll" command from command palette.

### Apparent Behavior:

Got error:
For "CMake Build": 
```
[rollbar] Unhandled exception: Unhandled Promise rejection: build TypeError: Cannot read property 'fsPath' of undefined {}
```
For "CMake Build All":
```
[rollbar] Unhandled exception: Unhandled Promise rejection: buildAll TypeError: str.replace is not a function {}
```
After "CMake Build All" task CMake tools becomes broken, and even from CMake side panel gives an error:

```
A CMake task is already running. Stop it before trying to build.
```

### Platform and Versions

- **Operating System**: Linux Mint 19
- **CMake Version**: 3.5.1
- **VSCode Version**: 1.38.1
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: arm-none-eabi-gcc 4.8

**Comment by bobbrow** [comment]
It looks like the tasks pass in an unexpected argument to our commands.

**Comment by stlkr** [comment]
Also, if(or when) command variable feature becomes working, it would be nice to publish the command IDs for CMake Tools somewhere in documentation. Because I wasn't able to find it anywhere except CMake Tools's sources.

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.5.0 which was published today.
Let us know if you encounter any issues with this release.

**Comment by fjeremic** [comment]
@andreeis I just tried this via:

```
{
	"version": "2.0.0",
	"tasks": [
        {
            "label": "CMake Build",
            "command": "${command:cmake.build}",
            "type": "shell",
            "group": "build",
            "problemMatcher": []
        }
	]
} 
```

And it does not work. I get a notification saying:

> Cannot substitute command variable 'cmake.build' because command did not return a result of type string.

The command seems to get printed, but it definitely doesn't execute:

```
[main] Building folder: openj9-openjdk-jdk8 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm --config Debug --target all -- -j 18
[build] Build finished with exit code 0
```

Where as if I revert back to `"cmake.buildTask": false` I get:
```
[main] Building folder: openj9-openjdk-jdk8 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm --config Debug --target all -- -j 18
[build] [  0%] Built target j9nls
[build] [  0%] Built target jpp
[build] [  0%] Built target pugixml
[build] [  1%] Built target j9vm_m4gen
[build] [  1%] Built target objectmodel
[build] [  1%] Built target trace
[build] [  2%] Built target ddrgentest
[build] [  2%] Built target j9jit_generate
[build] [  3%] Built target omr_ddr_ir
...
[build] [ 80%] Built target j9vrb
[build] [ 80%] Generating ut_j9jit.c, ut_j9jit.h, ut_j9jit.pdat
[build] [100%] Built target j9jit
[build] Build finished with exit code 0
```

Could we reopen this issue?

**Comment by andreeis** [comment]
I think the example at the beginning of the issue (which you used) is the old way of attempting to do this.
Try to apply the below changes to your example and let us know how that works:
            "command": "build",
            "type": "cmake",

**Comment by fjeremic** [comment]
Thanks! That works great. Cheers!

**Comment by KaDw** [comment]
> 
> 
> I think the example at the beginning of the issue (which you used) is the old way of attempting to do this.
> Try to apply the below changes to your example and let us know how that works:
> "command": "build",
> "type": "cmake",

Is there any list of "command" that are allowed for type "cmake"? I would like to create a configure or rebuild task but all I get is 
```
Error: The cmake task detection didn't contribute a task for the following configuration:
{
    "label": "CMake build",
    "type": "cmake",
    "command": "configure",
    "problemMatcher": []
}
```

I tried to search the repo for allowed commands but no luck

**Comment by KaDw** [comment]
> 
> 
> > I think the example at the beginning of the issue (which you used) is the old way of attempting to do this.
> > Try to apply the below changes to your example and let us know how that works:
> > "command": "build",
> > "type": "cmake",
> 
> Is there any list of "command" that are allowed for type "cmake"? I would like to create a configure or rebuild task but all I get is
> 
> ```
> Error: The cmake task detection didn't contribute a task for the following configuration:
> {
>     "label": "CMake build",
>     "type": "cmake",
>     "command": "configure",
>     "problemMatcher": []
> }
> ```
> 
> I tried to search the repo for allowed commands but no luck


@andreeis Can we use any other "command" than "build"? Is there any documentation about this feature?

**Comment by andreeis** [comment]
No, currently only the build command. We'll look into hooking up more commands.
I'm referencing a documentation update for this in here: https://github.com/microsoft/vscode-cmake-tools/issues/1246.

**Comment by qu1ck** [comment]
@andreeis the new method doesn't always work.
I have a project that builds fine if I use
```
"command": "${command:cmake.build}",
"type": "shell",
```
in tasks.json even though it pops up "Cannot substitute command variable" message

but build fails if I use
```
"command": "build",
"type": "cmake",
```
because it can't find standard system headers like stddef.h, windows.h

Something in the environment of how the two calls to cmake work differs.

I would like to use the new method because that allows me to use the task in preLaunchTask of launch.json but it's just broken.

**Comment by andreeis** [comment]
Set "cmake.loggingLevel" to "Debug" in your .vscode.settings.json and for both cases (shell and cmake type) share with us the "CMake/Build" output channel content when you build invoking the task.

**Comment by qu1ck** [comment]
Here: https://gist.github.com/qu1ck/a05a72b8f9ccae08eaf9b417a5923b87

Cmake type output is at the bottom of the gist (2nd file).

Note, when using cmake type it doesn't output to CMake/Build output channel, it spits everything into a new powershell terminal. Output of that obviously has no debug logging which is another indicator that it ignores some variables in settings.

**Comment by qu1ck** [comment]
These are my cmake settings from .settings.json
```
    "cmake.installPrefix": "D:\\Kicad\\msvc-build",
    "cmake.configureSettings": {
        "KICAD_PCM": "ON",
        "Boost_NO_BOOST_CMAKE": "ON",
        "CMAKE_TOOLCHAIN_FILE": "D:/devtools/vcpkg//scripts/buildsystems/vcpkg.cmake",
        "KICAD_SCRIPTING_PYTHON3": "ON",
        "KICAD_SCRIPTING_WXPYTHON_PHOENIX": "ON",
        "KICAD_USE_OCC": "ON",
    },
    "cmake.configureEnvironment": {
        "PATH": "D:\\devtools\\swigwin-4.0.2;D:\\devtools\\vcpkg\\installed\\x64-windows\\bin;D:\\devtools\\vcpkg\\installed\\x64-windows\\tools\\python3;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\\\Extensions\\Microsoft\\IntelliCode\\CLI;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\VC\\VCPackages;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\bin\\Roslyn;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\\\MSBuild\\Current\\Bin;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja;${env.PATH}",
    },
    "cmake.buildEnvironment": {
        "PATH": "D:\\devtools\\swigwin-4.0.2;D:\\devtools\\vcpkg\\installed\\x64-windows\\bin;D:\\devtools\\vcpkg\\installed\\x64-windows\\tools\\python3;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\\\Extensions\\Microsoft\\IntelliCode\\CLI;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\VC\\VCPackages;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Current\\bin\\Roslyn;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Team Tools\\Performance Tools;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Common\\VSPerfCollectionTools\\vs2019\\;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.18362.0\\x64;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\\\MSBuild\\Current\\Bin;C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja;${env.PATH}",
    },
    "cmake.configureArgs": [
        "-GNinja"
    ],
    "cmake.loggingLevel": "debug",
    "cmake.generator": "Ninja",
    "cmake.buildDirectory": "${workspaceFolder}/build/vscode-msvc",
    "cmake.enableTraceLogging": true,
    "cmake.cmakeCommunicationMode": "fileApi",
```

**Comment by stanle-cs** [comment]
same thing is happening to me. Trying to use "cmake.cleanConfigure" in a task resulted in this error:
```
Cannot substitute command variable 'cmake.cleanConfigure' because command did not return a result of type string.
```
my task:
```json
{
    "label": "CMake clean",
    "type": "process",
    "command": "${command:cmake.cleanConfigure}",
    "group": "none",
    "problemMatcher": []
}
```
I am executing it using this keybinding:
```json
[
    {
        "key": "ctrl+shift+c",
        "command": "workbench.action.tasks.runTask",
        "args": "CMake clean"
      }
      
]
```
If this was fixed in 1.5.0 and I'm using 1.9.1 then do you know what I'm doing wrong?

**Comment by bobbrow** [comment]
The commands that return strings and can be used for substitution in `tasks.json` and `launch.json` are documented here: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#command-substitution.

We don't currently have one that returns the CMake command to clean the project, so if you want to open a new issue to request that feature, we can go from there.  But I would think that you could just bind your keyboard shortcut directly to `cmake.cleanConfigure` instead of `workbench.action.tasks.runTask`.

**Comment by stanle-cs** [comment]
Thank you very much!
As I can use my key binding to lauch `cmake.cleanConfigure` now, I consider this resolved!
