### ISSUE TITLE
Hyperlinks to files in OUTPUT tab not working

### ISSUE THREAD

**Issue by zrno** [microsoft/vscode-cmake-tools#1237]
Issue Type: <b>Bug</b>

The hyperlinks in the output tab stopped working somewhere in the last few days(weeks?). I am not sure what changed in my environment so this happened. Was it a VS code update or CMake Tools update. Before I could simply click (or was it ctrl + click) and it would lead me to the error in the editor.
I am usinc cmake to configure and I am buidling using the visual studio compiler, all code is C++.

Extension version: 1.3.1
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz (8 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

![image](https://user-images.githubusercontent.com/13214299/81879934-2984bf80-95e0-11ea-9f61-0c0b998a8042.png)

**Comment by osmondj** [comment]
I have the same issue. It used to work not that long ago :thinking:

**Comment by Torgee** [comment]
I had the same issue - coincided with colored output for me - and the culprit was the C++ TestMate extension. It was called C++ Catch2 and GTest extension or something before. This extension (recently?) introduces colored output, which also affects cmake-tools output. This somehow also disables the hyperlinks for me :(

**Comment by zrno** [comment]
@Torgee thanks for this! You saved me a lot of time. Did you report the bug to the C++ TestMate extension?

**Comment by Torgee** [comment]
https://github.com/matepek/vscode-catch2-test-adapter/issues/207

**Comment by bobbrow** [comment]
Thanks for figuring out the root cause @Torgee!

**Comment by SteveFrenchBOSS** [comment]
Issue remains on linux

**Comment by zrno** [comment]
@SteveFrenchBOSS it was mentioned by @Torgee that this was cause by another extension called C++ TestMate. Is that not the case in your situation?

**Comment by SteveFrenchBOSS** [comment]
No I haven't got testmate.
It doesn't work off of a vanilla install, Ubuntu 20.04, CMake-tools and C/C++ the only installed extensions.
I am cross compiling for ARM-none if that helps.

[2020-11-12 10:15:16.982] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cmake-tools {"startup":true,"extensionId":{"value":"ms-vscode.cmake-tools","_lower":"ms-vscode.cmake-tools"},"activationEvent":"workspaceContains:**/CMakeLists.txt"}
[2020-11-12 10:15:16.982] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/steve/.vscode/extensions/ms-vscode.cmake-tools-1.5.2/dist/main

**Comment by andreeis** [comment]
@SteveFrenchBOSS , please open a new issue if you still have the problem you mention. It would help if you craft a small standalone repro or if you point us to an open source project that exhibits this symptom.
