### ISSUE TITLE
the dreaded ENOENT error

### ISSUE THREAD

**Issue by whiffee** [microsoft/vscode-cmake-tools#1240]
### Brief Issue Summary
After pressing the Build button in the status bar or pressing F7, the error appears:

connect ENOENT /tmp/cmake-server-0.914484925403855

even though the CMake executable is in the environment path in /usr/local/bin

### Expected:
Normal build.

1. Push button
2. Thing happens

(exactly)

### Apparent Behavior:
Tools is unable to access the relevant path. It should be noted that Mint 17.1 is a guest vm,
the host is Xubuntu 19.10.

### CMake Tools Log

[main] Building folder: Feature-Preserving-Octree-Hex-Meshing-II 
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: connect ENOENT /tmp/cmake-server-0.960628869307933 {}

2020-05-14 15:44:45.802] [renderer1] [error] connect ENOENT /tmp/cmake-server-0.960628869307933: Error: connect ENOENT /tmp/cmake-server-0.960628869307933
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)

### Developer Tools Log
??

### Platform and Versions

- **Operating System**: Xubuntu 19.10=host; MInt 17.1=guest, VMWare Player 15.5.2
- **CMake Version**: 3.7.2
- **VSCode Version**: 1.42
- **CMake Tools Extension Version**: 1.31
- **Compiler/Toolchain**: any, example: GCC 4.6.4 Using compilers C=/usr/bin/gcc-4.6, CXX=/usr/bin/g++-4.6

### Other Notes/Information

Path integrity checked by launching cmake in terminal. Restarting VSCode, rebooting vm produced no change.

**Comment by whiffee** [comment]
Further info:
Mint 18 as guest vm does not show the same problem, works as expected. Unfortunately I want
the older distro. Raiding previous repository does not look that easy or inviting. 
Tried installing CMake 3.7.2 to a different location, and amending the path. This worked for
a terminal, but not for Tools. Tried substitutions in cmake.cmakePath, but either it didn't work
or my syntax was wrong (likely).

**Comment by bobbrow** [comment]
Are you able to try a newer version of CMake?  This looks like an issue with CMake Server.  CMake 3.15 and newer are preferred (which use cmake-file-api instead) as CMake Server support has been deprecated.

**Comment by whiffee** [comment]
Hi Bob,
I'm trying to build a very big and complex project and am not very familiar with it. Iwant to try to get as close to contemporary gcc, cmake, and dependencies as I can 
before I try to beat weeds. I know it can build.
Thanks for the info on CMake Server. It may help in my continuing experiments.
sincerelyGB
 
 
 
-----Original Message-----

**Comment by whiffee** [comment]
I decided to try your advice and substituted CMake 3.13.3. This worked out. I guess the important thing was that gcc and the libraries matched the scenery. Thanks for the suggestion.

**Comment by delaneyld** [comment]
I am also experiencing a connect EN0ENT error - 
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: connect ENOENT /tmp/cmake-server-0.08807646082633025

My version of CMake is 3.22.1, OS is macOS 10.14.6, VS Code version 1.63.2, compiler Clang 10.0.1. 

What steps do you recommend for troubleshooting?

**Comment by delaneyld** [comment]
CMake tools extension is v1.5.2

**Comment by bobbrow** [comment]
@delaneyld I recommend you use the cmake-file-api instead of cmake-server.  You can force it with the `cmake.cmakeCommunicationMode` setting.  Set it to `fileApi`.  I also recommend updating the extension to 1.9.2.  If you still have issues after that, please open a new issue and we can help you troubleshoot further.
