### ISSUE TITLE
 CMake build type doesn't work

### ISSUE THREAD

**Issue by Lw-Cui** [microsoft/vscode-cmake-tools#1245]
### Brief Issue Summary

 CMake build type(Release, Debug, MinSizeRel, and RelWithDebInfo) doesn't make a difference.

### Expected:

1. Build with `Debug` then default compiler flags like ` -g` are added

### Apparent Behavior:

1. Build with `Debug` 
2. `compile_commands.json` doesn't show `-g` flags

### CMake Tools Log

```
[proc] Executing command: /usr/bin/cmake --build /home/lc/HelloWorld/build --config Debug --target HelloWorld -- -j 
```

### Platform and Versions

- **Operating System**: Debian GNU/Linux 10 (buster)
- **CMake Version**: 3.13.4
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**:  GCC 8

### Other Notes/Information

I use Visual Studio Code Remote Development extensions but I don't believe it causes this problem.

**Comment by andreeis** [comment]
compile_commands.json is not used for building. Besides the switch -g missing from that generated file, is there anything that actually doesn't properly work for you? Are you able to debug? Do you see the -g switch being passed in a build log?

**Comment by Lw-Cui** [comment]
Thanks for reply. 

No I can't debug when building with the cmake extension due to lack of gdb symbol. However, If I do it manually `cmake .. -DCMAKE_BUILD_TYPE=Debug` it will pass the -g flag and debug works well.

Below is the build log, I suppose `--config Debug` doesn't work as expected at least in my case:
```
[main] Building folder: HelloWorld 
[main] Configuring folder: HelloWorld 
[cmake] Configuring done
[cmake] Generating done
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/lc/HelloWorld/build --config Debug --target HelloWorld -- -j 3
[build] Scanning dependencies of target HelloWorld
[build] [ 33%] Building CXX object CMakeFiles/HelloWorld.dir/main.cpp.o
[build] [ 66%] Linking CXX executable HelloWorld
[build] [100%] Built target HelloWorld
[build] Build finished with exit code 0
```

**Comment by andreeis** [comment]
What generator is used for configuring your project?
Same problems with debugging if you do a clean configure (the command "Delete cache and reconfigure" or a configure after deleting the build folder) after 'Debug' variant is selected?

**Comment by Lw-Cui** [comment]
I do the both and it's the same result. And in fact the `--config` argument seems making no difference.

Sorry but what do you mean "generator"? I use 
* CMake Tools Extension Version: 1.3.1
* CMake Version: 3.13.4

with a fairly simple `CMakefile.txt`:
```
cmake_minimum_required(VERSION 3.13)
project(HelloWorld)

set(CMAKE_CXX_STANDARD 17)

add_executable(HelloWorld main.cpp app.cpp)
```

**Comment by andreeis** [comment]
Any cmake.generator or cmake.preferredGenerators defined in your workspace settings or inherited from the user settings?

Set cmake.loggingLevel to trace, run "delete cache and reconfigure" and share the output.

**Comment by Lw-Cui** [comment]
I don't change generator config:
```
"cmake.generator": null
"cmake.preferredGenerators": [
  "Ninja",
  "Unix Makefiles"
]
```

Output after running `delete cache and reconfigure` & deleting the `build`:
```
[main] Building folder: HelloWorld 
[main] Saving open files before configure/build
[main] Configuring folder: HelloWorld 
[main] Saving open files before configure/build
[driver] Start configure 
[driver] Runnnig pre-configure checks and steps
[driver] Using compilers in GCC 8.3.0 for configure
[driver] Run _refreshExpansions
[cms-driver] Run doRefreshExpansions
[driver] Run _refreshExpansions cb
[cmake] The C compiler identification is unknown
[cmake] The CXX compiler identification is unknown
[cmake] Check for working C compiler: /usr/bin/gcc-8
[cmake] Check for working C compiler: /usr/bin/gcc-8 -- works
[cmake] Detecting C compiler ABI info
[cmake] Detecting C compiler ABI info - done
[cmake] Check for working CXX compiler: /usr/bin/g++-8
[cmake] Check for working CXX compiler: /usr/bin/g++-8 -- works
[cmake] Detecting CXX compiler ABI info
[cmake] Detecting CXX compiler ABI info - done
[cmake] Configuring done
[cmake] Generating done
[cache] Reading CMake cache file /home/lc/HelloWorld/build/CMakeCache.txt
[cache] Parsing CMake cache string
[build] Starting build
[driver] Start build HelloWorld
[driver] Runnnig pre-configure checks and steps
[proc] Executing command: /usr/bin/cmake --build /home/lc/HelloWorld/build --config Debug --target HelloWorld -- -j 3
[build] Scanning dependencies of target HelloWorld
[build] [ 66%] Building CXX object CMakeFiles/HelloWorld.dir/main.cpp.o
[build] [ 66%] Building CXX object CMakeFiles/HelloWorld.dir/app.cpp.o
[build] [100%] Linking CXX executable HelloWorld
[build] [100%] Built target HelloWorld
[driver] Run _refreshExpansions
[cms-driver] Run doRefreshExpansions
[driver] Run _refreshExpansions cb
[cache] Reading CMake cache file /home/lc/HelloWorld/build/CMakeCache.txt
[cache] Parsing CMake cache string
[build] Build finished with exit code 0
[extension] [7722] cmake.build finished (returned 0)
```

**Comment by fdk17** [comment]
@Lw-Cui The CMake documentation states that `--config <cfg> For multi-configuration tools, choose configuration <cfg>`.  Your examples are not using a multi-configuration generator, they are using a single configuration generation which is controlled by the `CMAKE_BUILD_TYPE` variable.  That is why the `--config <cfg>` option is ignored in the example.
