### ISSUE TITLE
[1.4.0-beta] cpptools reports unknown architecture flag

### ISSUE THREAD

**Issue by mjvk** [microsoft/vscode-cmake-tools#1249]
### Brief Issue Summary

In 1.4.0-beta a warning is shown that cpptools does not know the target architecture (as set using -march=broadwell in cmake). This warning was not present in the previous version.

### Expected:

No warnings

### Apparent Behavior:

Warning:
```[cpptools] Unknown target architecture flag: broadwell```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.40.0-beta
- **Compiler/Toolchain**: mingw

**Comment by bobbrow** [comment]
Thanks for reporting this.  @michelleangela, perhaps we should remove the warning message, or change it to just log the target detected?  We're trying to detect the bitness, but it's valid to pass in chip-specific strings here too.

**Comment by michelleangela** [comment]
Pull request created to remove warning logs. 
https://github.com/microsoft/vscode-cmake-tools/pull/1251

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
