### ISSUE TITLE
Environment variable substituion: Kit environment and buildDirectory

### ISSUE THREAD

**Issue by alex-che** [microsoft/vscode-cmake-tools#1250]
### Brief Issue Summary

`"cmake.buildDirectory" : "${env.VARNAME}"` does not work if `VARNAME` is set in active kit's `"environmentVariables"`. Empty string is used instead. Ditto for `"cmake.installPrefix"`.

Although, the following works fine:
1. `"cmake.buildDirectory" : "${buildKit}"`
2. `"cmake.configureSettings: { "SOME_SETTING" : "${env.VARNAME}" }`
3. `"cmake.buildDirectory" : "${env.VARNAME}"` - if `VARNAME` is set in environment before running vscode, instead of the kit. 

### Expected:

Values of variables set in active kit's `"environmentVariables"` to be used in `${env.XXX}` substitution for `"cmake.buildDirectory"` and `"cmake.installPrefix"`.

### Apparent Behavior:

1: `.vscode/cmake-kits.json`:
```
[
   {
      "name": "TEST_KIT",
      "environmentVariables": {"TEST_VAR": "TEST"}
   }
]
```
2: `.vscode/settings.json`:
```
   "cmake.configureSettings": {
      "TEST_SETTING": "${env.TEST_VAR}"
   },
   "cmake.buildDirectory": "${workspaceFolder}/__build/${env.TEST_VAR}-${buildKit}-${buildType}",
```
3. CMake: Select Kit => TEST_KIT

4. CMake: Delete Cache and Reconfigure

5. Output: CMake/Build 
see below

### CMake Tools Log
```
[proc] Executing command: /usr/local/bin/cmake --no-warn-unused-cli -DTEST_SETTING:STRING=TEST ... -B/home/user/project/__build/-TEST_KIT-Debug ...
```
### Platform and Versions

- **Operating System**: VSCode UI: Windows 10 1903, VSCode Server: Ubuntu 16 64bit
- **CMake Version**: 3.17.2 
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: GCC 5.4.0

### Other Notes/Information

Is it expected bahaviour, am I doing something wrong, or is it a bug?

BTW, thanks for the great extension!

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.

**Comment by alex-che** [comment]
Still not working for me with CMake tools 1.7.0.
settings.json:

`"cmake.buildDirectory": "${workspaceFolder}/__build/${env.VARNAME}-postfix",
`
cmake-kits.json:
```
"name": "TestKit",
...
"environmentVariables": {
         "VARNAME" : "var-value",
```

After selecting the kit and cleaning CMake cache I still have `${workspaceFolder}/__build/-postfix` as build directory, i.e. VARNAME is not taken from cmake-kits.json.

**Comment by andreeis** [comment]
You are right, I either didn't test this properly when I merged the PR targeting to fix this into the repository or it regressed with some of our latest unrelated PRs. I have a fix that we will review.

**Comment by andreeis** [comment]
CMake Tools 1.7.1 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.

**Comment by alex-che** [comment]
Now it's perfect. Many thanks!

**Comment by Fuzzy67** [comment]
I want to use this "feature" inside cmake.cmakePath in settings.json (in workspace). But it does not work. Neither with version 1.7.1 nor with the current version 1.9.1 od cmake-tools extension. The environment variable is always empty. VScode is version 1.62.2
