### ISSUE TITLE
Set debugger working directory

### ISSUE THREAD

**Issue by dhiegomaga** [microsoft/vscode-cmake-tools#1258]
I set up the cmake-tools to work as a debugger in C++. It works very well. 

Except inside my executable, I read a file with a relative path (such as `file = readFile("../folder/file.txt")` ) , and obviously it has to be relative to the location of the executable.

Even though running the executable it works great, when I debug I noticed it CAN'T find the file, and I suppose it is because the debugger is running on a different directory than the executable. How can I set this? I didn't find anything on the internet. 

Thanks.

**Comment by dhiegomaga** [comment]
Ok, I found a way to do it by using the launch.json as [described here](https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html) and then manually setting the flag:

```json
"cwd": "${workspaceFolder}/build",
```
But I'd like to avoid this manual work, isn't there a flag I could put inside `settings.json`?

**Comment by bobbrow** [comment]
This should be settable without using `launch.json` with:

```
  "cmake.debugConfig": {
    "cwd": "${workspaceFolder}/build"
  }
```

**Comment by WinformsWizard** [comment]
> This should be settable without using `launch.json` with:
> 
> ```
>   "cmake.debugConfig": {
>     "cwd": "${workspaceFolder}/build"
>   }
> ```
Is there any way to do this when I am not debugging?

**Comment by bobbrow** [comment]
@WinformsWizard, PR #1444 adds support for your request.
