### ISSUE TITLE
Wrong description on "Feature Contributions" tab

### ISSUE THREAD

**Issue by bad-ed** [microsoft/vscode-cmake-tools#1265]
### Brief Issue Summary

Incorrect descriptions of settings on "Feature Contributions" tab. See screenshot

![cmaketools-wrongdescr](https://user-images.githubusercontent.com/24456989/82893740-25e72600-9f5a-11ea-84a4-7715f5bdb541.png)

### Expected:

Correct descriptions

### Platform and Versions

- **Operating System**: macOs 10.14.5
- **CMake Version**: 3.14.5
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.4.0

**Comment by andreeis** [comment]
This started to happen with 1.3.1.

**Comment by bobbrow** [comment]
This is a VS Code bug: https://github.com/microsoft/vscode/issues/54111
