### ISSUE TITLE
`problemMatcher` not working when running `cmake.buildWithTarget` as a task

### ISSUE THREAD

**Issue by ce3a** [microsoft/vscode-cmake-tools#1266]
### Brief Issue Summary

I would like to use `cmake-tools` with a **custom build output diagnostics parser** for a proprietary C compiler. My approach is to run the `cmake.buildWithTarget` command as a (`tasks.json`) build task and to use a custom `problemMatcher`. However, my custom `problemMatcher` seems to be ignored. The build output seems to be parsed using the builtin OutputParsers.

### Expected:

1. I have configured a build task to run the `cmake.buildWithTarget` command:

```jsonc
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "command": "${command:cmake.buildWithTarget}",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                {
                    "fileLocation": "absolute",
                    "pattern": [
                        {
                            "regexp": "\"(.*)\", line (\\d+): (info|warning|(?:|fatal |catastrophic )error) \\((.*)\\): (.*)$",
                            "file": 1,
                            "line": 2,
                            "severity": 3,
                            "code": 4,
                            "message": 5
                        }
                    ]
                }
            ]
         }
     ]
    
```

2. The command is executed as expected, the target is built.
3. After the build, I would expect compiler warnings and errors to be shown in the *PROBLEMS* tab.

### Apparent Behavior:

Compiler warnings and errors are *not shown* in the *PROBLEMS* tab.

### Platform and Versions

- **Operating System**:  Windows 10
- **CMake Version**: 3.13.3-win64-x64
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.4.0
- **Compiler/Toolchain**: proprietary

### Other Notes/Information

Using a multi workspace setup.

I tried to disable build output parsing completely (in `settings.json` and `my.code-workspace`) using:

```json
		"cmake.parseBuildDiagnostics": false,
		"cmake.enabledOutputParsers": [],
```

This seems to be ignored. Makefile errors like `"recipe for target 'path/to/foo.c.obj"' failed` are still captured.

**Comment by bobbrow** [comment]
It appears that the parseBuildDiagnostics setting is no longer wired up to do what it is supposed to do.  I suspect the fix is to check the setting before running this code:
https://github.com/microsoft/vscode-cmake-tools/blob/54e487d10e29f889a6c95769961e6975f14b8fa6/src/cmake-tools.ts#L912
