### ISSUE TITLE
Partial CMT activation configuration for non CMake workspace folder not persistent

### ISSUE THREAD

**Issue by kurthardin** [microsoft/vscode-cmake-tools#1269]
### Brief Issue Summary

When connecting to a remote multi-root workspace where one folder doesn't contain a CMakeLists.txt file, clicking the "Don't show again" button on the "CMakeLists.txt was not found in the root of the folder..." notification does not persist, i.e. the notification appears each time the workspace is opened.

### Expected:

1. Connect to remote development environment via remote-ssh extension.
2. Open multi-root workspace with one root folder that doesn't contain a CMakeLists.txt file.
3. Click "Don't show again" button on the "CMakeLists.txt was not found in the root of the folder..." notification.
4. Close and re-open workspace.
5. "CMakeLists.txt was not found..." notification is not shown again.

### Apparent Behavior:

1. Connect to remote development environment via remote-ssh extension.
2. Open multi-root workspace with one root folder that doesn't contain a CMakeLists.txt file.
3. Click "Don't show again" button on the "CMakeLists.txt was not found in the root of the folder..." notification.
4. Close and re-open workspace.
5. "CMakeLists.txt was not found..." notification is shown again.

### Platform and Versions

- **Operating System**: Windows 10 (local), Ubuntu 19.10 (remote)
- **CMake Version**: cmake version 3.14.5
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.4.0
- **Compiler/Toolchain**: 8.0.0-3

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.4.1 which was published today.
Let us know if you encounter any issues with this release.
