### ISSUE TITLE
Problem Matcher cannot navigate to compilation error

### ISSUE THREAD

**Issue by BlurryLight** [microsoft/vscode-cmake-tools#1270]
### Expected:

1. Click the panel of compilation errors and then jump to the code where error exists
### Apparent Behavior:

1. Click the panel of compilation errors
2. The vscode continuously notifies me **Unable to open file xxxx**
3. The expected behaviour is **open the file then goto line 11st** but it seems that vscode is trying to open a file called **filename:11**
![截图_2020-05-29_14-33-34](https://user-images.githubusercontent.com/14940338/83228763-6db7b880-a1b9-11ea-8487-d0d3c95a8eac.png)

### CMake Tools Log

```
<!-- Paste the log contents HERE -->

<!-- For apparent bugs, place the contents of the developer tools console here. -->
[main] Building folder: DiRender DiRender
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /mnt/Gpan/QTC++/DiRender/build/vscode-Clang-10.0.0-Debug --config Debug --target DiRender -- -j 10
[build] [1/2  50% :: 0.554] Building CXX object CMakeFiles/DiRender.dir/src/utils/stb_image_wrapper.cc.o
[build] FAILED: CMakeFiles/DiRender.dir/src/utils/stb_image_wrapper.cc.o 
[build] /usr/bin/c++   -I../../src -g   -Wall -Wextra -pedantic -Werror -std=gnu++14 -MD -MT CMakeFiles/DiRender.dir/src/utils/stb_image_wrapper.cc.o -MF CMakeFiles/DiRender.dir/src/utils/stb_image_wrapper.cc.o.d -o CMakeFiles/DiRender.dir/src/utils/stb_image_wrapper.cc.o -c ../../src/utils/stb_image_wrapper.cc
[build] ../../src/utils/stb_image_wrapper.cc: 在成员函数‘bool DR::Image::write_image(const string&, bool)’中:
[build] ../../src/utils/stb_image_wrapper.cc:11:17: 错误：‘kBMPI’ is not a member of ‘DR::PicType’; did you mean ‘kBMP’?
[build]    11 |   case PicType::kBMPI:
[build]       |                 ^~~~~
[build]       |                 kBMP
[build] ninja: build stopped: subcommand failed.
[build] Build finished with exit code 1
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**:  Manjaro 20.0.1 Lysia X86_64
- **CMake Version**:  cmake version 3.17.2
- **VSCode Version**:  1.45.1
- **CMake Tools Extension Version**:  1.4.0
- **Compiler/Toolchain**:  clang 10.0/ gcc-9.0

### Other Notes/Information
I have downgraded vscode to 1.40, or downgraded CMake tools extension to 1.3.1,  switched  compiler between clang-10 and gcc-9,  the problem still keeps the same.  However, the remote ssh on a Ubuntu 18.04LTS and gcc 7.5 works as expected. I doubt whether it is related to the compiler version or cmake version but I have no clue about that.

**Comment by bobbrow** [comment]
It seems like a bug in the problem matcher regular expression.  The `错误：` should not be in the message.  It looks like the `:` character is different so it doesn't match the line correctly.

**Comment by BlurryLight** [comment]
@bobbrow  Confirmed. It seems that gcc/clang are trying to output some localization messages but the problem matcher cannot parse it.  

 I set `export LC_MESSAGES=en_US.UTF-8` and now everything works.
