### ISSUE TITLE
"Building" pop-up obscures the integrated terminal

### ISSUE THREAD

**Issue by willvousden** [microsoft/vscode-cmake-tools#1272]
### Brief Issue Summary

When compiling my project, the pop-up window hovers over the integrated terminal and cannot be dismissed.

Compiling can take some time, and for the duration I cannot use the terminal 🙁 

### Expected:

Compile stuff and still be able to use the terminal.

Either:
* Be able to dismiss the pop-up
* Be able to move it
* Be able to disable it completely

### Apparent Behavior:

<img width="701" alt="Screenshot 2020-05-26 at 17 02 26" src="https://user-images.githubusercontent.com/152388/83251995-cb90d400-a1aa-11ea-91cb-5936b6a05290.png">

### Platform and Versions

- **Operating System**: macOS
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.4.0

**Comment by bobbrow** [comment]
Are you able to hide it by clicking the bell icon in the status bar?  (You might have to click it twice)

![image](https://user-images.githubusercontent.com/12818240/85317699-b0e11080-b473-11ea-8dc0-e102ad6ecd0d.png)

**Comment by juxeii** [comment]
That one bothers me too, but double clicking at least hides the pop-up.
It would be great to have a generic vsc-wide solution for showing/hiding pop-ups.
