### ISSUE TITLE
Compiler path should be taken not from cache, but from CMakeLangCompiler.cmake

### ISSUE THREAD

**Issue by Dlougach** [microsoft/vscode-cmake-tools#1278]
### Brief Issue Summary

When compiler kit is set to `[Unspecified]` the compiler path is not always picked up correctly.

### Expected:

Create a project with CMakeLists.txt with the following contents:

```cmake
set(CMAKE_C_COMPILER "/path/to/gcc")
set(CMAKE_CXX_COMPILER "/path/to/g++")

project(myproject)

# some C/C++ libraries/binaries
```

Then load it into VsCode.

### Apparent Behavior:

You will get the following message:

> The path to the compiler for one or more source files was not found in the CMake cache. If you are using a toolchain file, this probably means that you need to specify the CACHE option when you set your C and/or C++ compiler path

The reason is compiler paths not being stored in cache.

### Other Notes/Information

There is a relevant "won't fix" issue on CMake website:
https://gitlab.kitware.com/cmake/cmake/-/issues/20225

It highlights the following alternative method of finding compiler paths: read files and `CMakeFiles/<version>/CMakeCCompiler.cmake` `CMakeFiles/<version>/CMakeCXXCompiler.cmake` in build directory. They will contain correct paths.

**Comment by bilderbuchi** [comment]
I'm seeing the same thing when using a toolchain file (without using  `CACHE`) .

> It highlights the following alternative method of finding compiler paths: read files and `CMakeFiles/<version>/CMakeCCompiler.cmake` `CMakeFiles/<version>/CMakeCXXCompiler.cmake` in build directory. They will contain correct paths.

The upstream issue has since been fixed "properly", and this information should be available from https://cmake.org/cmake/help/v3.26/manual/cmake-file-api.7.html#object-kind-toolchains

cf. upstream https://gitlab.kitware.com/cmake/cmake/-/issues/19514 https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5678

**Comment by jophippe** [comment]
I can confirm on my machine when using the latest version of the extension and CMake version 3.20 or greater that I do not see this message anymore, as the compiler paths should be obtained from the toolchain response file from the file API.
Can someone else confirm that this is fixed? @Dlougach @bilderbuchi 
Thanks!

**Comment by jophippe** [comment]
I'm going to assume this issue is fixed. Please open a new issue if this problem persists. Thanks!

**Comment by bilderbuchi** [comment]
> I'm going to assume this issue is fixed. Please open a new issue if this problem persists. Thanks!

I think so, I haven't noticed this in a while.
