### ISSUE TITLE
Add a command to reset all extension state

### ISSUE THREAD

**Issue by thothothotho** [microsoft/vscode-cmake-tools#1282]
### Brief Issue Summary

I have a project.  Everytime the extension tries to configure it, it destroyed the CMakeCache.txt.

### Expected:

Well, don't.
This is a follow up on #922.  I repeat the main point.  You're screwing the major selling point of this 
marvelous extension (gluing intellisense, launching a build, parsing compiler message) with additional feature not that valuable (attempting to change some cmake state).

### Apparent Behavior:

Here is some information about my project layout, in case that matters:

```
Client/
   CMakeLists.txt
   Build/                        cmake state
       CMakeCache.txt
   Sources/
   server/
       CMakeLists.txt
       build/                    another cmake state.
         CMakeCache.txt
       components/
           foo/
                CMakeList.txt
```

The toplevel `Build` folder is configured manually with a vcpkg toolchain.
The inner `build` folder (`Client/server/build`) might be there sometimes.  Sometimes it might even be 
a symlink to the `Client/Build` folder).  Essentially it should not play any role here.

I have configured cmake manually (we have  scripts for that, this is a rather complicated process because of the vcpkg toolchain + some more gory details)

I open vscode on the Client folder and lanch a Build (F7).  The extension tries to configure 
the project (fair enough, the first time it's opened) and it fails.
After the run, the content of the  `client/Build/CMakeCache.txt` appears reset.  Like if the extension took the silly initiative to reconfigure the project from `client/CMakeLists.txt`.  Since it has no knowledge of the vcpkg toolchain, it fails.

### CMake Tools Log

I activated the debug logs of the extension:
```
[main] Safe constructing new CMakeTools instance
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[variant] Loaded new set of variants
[main] CMakeTools instance initialization complete.
[kit] Reading kits file /home/fred/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Successfully loaded 4 kits from /home/fred/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: /home/fred/src/dual-client/.vscode/cmake-kits.json
[main] Injecting new Kit into CMake driver
[extension] [9577] cmake.setVariant started
[main] Active build variant changed
[main] Configuring folder: dual-client 
[main] Saving open files before configure/build
[main] Starting new CMake driver
[main] Starting CMake driver
[driver] CMakeDriver Kit set to clang
[driver] Trying to detect generator supported by system
[driver] Command version test return code 0
[driver] Run _refreshExpansions
[cms-driver] Run doRefreshExpansions
[driver] Run _refreshExpansions cb
[cms-client] Started new CMake Server instance with PID 861
[cache] Reading CMake cache file /home/fred/src/dual-client/Build/CMakeCache.txt
[cache] Parsing CMake cache string
[driver] Setting new variant , Optimize for speed - include debug information.
[driver] Run _refreshExpansions
[cms-driver] Run doRefreshExpansions
[driver] Run _refreshExpansions cb
[cms-client] Started new CMake Server instance with PID 866
[cache] Reading CMake cache file /home/fred/src/dual-client/Build/CMakeCache.txt
[cache] Parsing CMake cache string
[driver] Setting new variant , Optimize for speed - include debug information.
[driver] Run _refreshExpansions
[cms-driver] Run doRefreshExpansions
[driver] Run _refreshExpansions cb
[driver] Run _refreshExpansions
[cms-driver] Run doRefreshExpansions
[driver] Run _refreshExpansions cb
[driver] Start configure 
[driver] Runnnig pre-configure checks and steps
[driver] Using compilers in clang for configure
[driver] Run _refreshExpansions
[cms-driver] Run doRefreshExpansions
[driver] Run _refreshExpansions cb
[cmake] Found OpenSSL: /NQVCPKGROOT/7027d93e776daf0107de86af64dfcbccab782140/installed/x64-linux/debug/lib/libcrypto.a (found suitable version "1.1.1d", minimum required is "1")  
```
then follow the ususal cmake logs.

It ends with a failure because the CMakeCache.txt has been flushed (a crucial information one would like to be logged)

then
```
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.
[extension] [9577] cmake.setVariant finished (returned 0)
[extension] [3222] cmake.selectKit started
```

### Platform and Versions

- **Operating System**: ubuntu 18
- **CMake Version**: 3.13.3
- **VSCode Version**: 1.45.1
- **CMake Tools Extension Version**: 1.4.0
- **Compiler/Toolchain**: gcc-8

**Comment by thothothotho** [comment]
After a full clone of my sources in another directory, I can not reproduce the problem with the copy.
I still always have it with the original, even after removing the .vscode and blasting the `Client/Build` folder entirely.  It smells as if there is a hidden state  about the project somewhere else.

I try to cleanup some states in `.config/Code` with no success.  The problem is still there.

**Comment by thothothotho** [comment]
I decided to remove this state `/home/fred/.local/share/CMakeTools/cmake-tools-kits.json`.  That was an old stuff I did a looong time ago and that I'm not using anymore (I really prefer to change the cmake state myself, with cmake's tools)
And, surprise, the issue is gone.  Here was the kits:

```json
[
  {
    "name": "GCC 8.1.0",
    "compilers": {
      "CXX": "/usr/lib/ccache/g++-8",
      "C": "/usr/lib/ccache/gcc-8"
    }
  },
  {
    "name": "ccache zapcc",
    "compilers": {
      "CXX": "/usr/lib/ccache/zapcc++",
      "C": "/usr/lib/ccache/zapcc"
    },
    "keep": true
  },
  {
    "name": "clang",
    "compilers": {
      "CXX": "/home/fred/bin/clang++",
      "C": "/home/fred/bin/clang"
    },
    "keep": true
  },
  {
    "name": "zapcc",
    "compilers": {
      "CXX": "/home/fred/src/Various/llvm/build/bin/zapcc++",
      "C": "/home/fred/src/Various/llvm/build/bin/zapcc"
    },
    "keep": true
  }
]
```

**Comment by thothothotho** [comment]
Putting the state back, the bug did not reappear.  Apparently the hidden state heals himself.  It would be great that you document somewhere the nature of the hidden state.  Where it is stored.  
Ideally, this hidden state should not exist at all.  Or it should be kept inside the build dir, or in the .vscode and be very explicit (a readable .json file).  I really lost hours trying to diagnose this issue.

**Comment by bobbrow** [comment]
We're not sure what could have caused this, but we will take it as a feature request to add a command that resets all extension state.
