### ISSUE TITLE
wrong warning about  CMakeList.txt not found when working in multi folder workspace

### ISSUE THREAD

**Issue by fatfatson** [microsoft/vscode-cmake-tools#1283]
I'm working on a  workspace with multi folders and there's only one folder has CMakeList.txt, everytime I modify&save it, vscode always shows error about something like "no CMakeList in other folder"

![image](https://user-images.githubusercontent.com/5842874/83706465-1b0f4e00-a64a-11ea-827e-c0caab69b3dd.png)

![image](https://user-images.githubusercontent.com/5842874/83507071-9cf06180-a4fa-11ea-9760-a85ed91c8ae8.png)

even though I click the "Don't show again", it still appear everytime.

**Comment by bobbrow** [comment]
Sorry about that.  It looks like there was already an issue open to track this. I was coming back from time off and looked at issues in reverse order so I hadn't seen it yet.  This is #1269
