### ISSUE TITLE
CMake build fails with 'The "path" argument must be of type string'.

### ISSUE THREAD

**Issue by DmytroBubnov** [microsoft/vscode-cmake-tools#1285]
### Brief Issue Summary
CMake build fails with 'The "path" argument must be of type string'.

### Apparent Behavior:
I either push Build button on the toolbar or start it via CMake: Build or via F7 and it fails with an exception.

### CMake Tools Log
`[rollbar] Unhandled exception: Unhandled exception Promise: build TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined {}`

### Platform and Versions
- **Operating System**: Windows 10 Home
- **CMake Version**: ? (didn't install separately, can't invoke via cmd)
- **VSCode Version**: 1.45.1 (user setup)
- **CMake Tools Extension Version**: 1.4.0
- **Compiler/Toolchain**: Visual Studio Community 2017 Release - amd64_x86

### Other Notes/Information
The problem is in `dist/main.js` file at the line 5620: it checks `null !== paths_1.default.ninjaPath` while `paths_1.default.ninjaPath` is `undefined`. 
I replaced
`if (null !== paths_1.default.ninjaPath) {`
with
`if (null !== paths_1.default.ninjaPath && undefined !== paths_1.default.ninjaPath) {`
and now it works fine.

**Comment by bobbrow** [comment]
Keeping this open until we release the fix

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.4.1 which was published today.
Let us know if you encounter any issues with this release.

**Comment by DmytroBubnov** [comment]
Thank you, not it works fine on my system.
