### ISSUE TITLE
IntelliSense never finishes updating when using CMake 1.17 target_precompile_headers()

### ISSUE THREAD

**Issue by rybertm** [microsoft/vscode-cmake-tools#1287]
### Brief Issue Summary

IntelliSense never finishes updating, the parsing gets paused when I'm using `target_precompile_headers()`. The project itself builds just fine.

https://github.com/rybertm/vscode-pch-test

Without `target_precompile_headers()` everything works as expected.
### Platform and Versions

    **Operating System**: MacOS Catalina

    **CMake Version**: 3.17

    **VSCode Version**: 1.45.1
    **CMake Tools Extension Version**: 1.4.0

    **Compiler/Toolchain**: Apple Clang 11.0.3

**Comment by rybertm** [comment]
I tested in Windows(lastest) by cloning the repo above and can confirm the issue is present when using MSVC 16.6.0 and Clang 10.0.0 for MSVC

**Comment by andreeis** [comment]
Thank you for reporting this. We are tracking it with https://github.com/microsoft/vscode-cmake-tools/issues/1141.
