### ISSUE TITLE
Debugger stopped working after MacOS X Catalina update

### ISSUE THREAD

**Issue by coppersoft** [microsoft/vscode-cmake-tools#1293]
Hello all,

I'm using vscode 1.45.1 with vscode-cmake-tools 1.4.0 with MacOSX Catalina 10.15.5. I always had some trouble to use it, when I launch the debugger without any further configuration the debugger get stuck. After some searching I found a solution, adding this to settings.json

    "cmake.debugConfig": {
        "stopAtEntry": false,
        "MIMode": "lldb",
        "miDebuggerPath": "/Users/macdev/.vscode/extensions/ms-vscode.cpptools-0.28.1/debugAdapters/lldb-mi/bin/lldb-mi"
    }

and it started to work perfectly for months. Some day ago I received the Catalina update and now when I launch the debugger it stops with the following error: (it's translated from italian)

"Unable to find GDB in the predefined search path and in "/Users/macdev/.vscode/extensions/ms-vscode.cpptools-0.28.1/debugAdapters/lldb-mi/bin/lldb-mi".

I tried to remove the above configuration from the settings.json but everything go back to the initial situation, when the debugger get stuck after launch.

I don't know if it's a bug, but it's strange that everything worked perfectly for months and now stopped working.

Thank you in advance.

EDIT: Sorry, I had to update the miDebuggerPath to 0.28.2. Closing...

**Comment by coppersoft** [comment]
Sorry, I had to update the miDebuggerPath to 0.28.2. Closing...

**Comment by bobbrow** [comment]
Just wanted to note that 0.28.3 was released this morning so you'll need one more update until we update this extension to find it for you.
