### ISSUE TITLE
to visualize cmake configure command in cmake server mode

### ISSUE THREAD

**Issue by guochengli** [microsoft/vscode-cmake-tools#1294]
Issue Type: <b>Feature Request</b>

Currently after I run CMake/Configure for c++ project, I can't find the underlying cmake configure command in 'OUTPUT' window. Whereas cmake build command can be printed in 'OUTPUT' window if I trigger cmake build. For several times I need to know what exact cmake 'configure' command was generated. Is there any place I can find the generated cmake configure command? Or may I suggest to add this to the 'OUTPUT' window at the initial cmake configuring stage?
Sincerely.

Extension version: 1.4.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-1050-oem

**Comment by bobbrow** [comment]
It looks like we log the arguments for legacy and file-api modes, but not CMake Server mode.  If you are able to upgrade your CMake binary to 3.15 or newer, you should see the configure arguments when you enable the `"cmake.loggingLevel": "debug"` setting.

**Comment by guochengli** [comment]
You're right. My cmake version is 3.10 and I don't have the permission to upgrade it, unfortunately. It looks like I need to wait till I'm the boss :)

**Comment by gcampbell-msft** [comment]
This issue is over 4 years old, so I'll close this, please open a new issue if you're still facing problems with this. Thanks!
