### ISSUE TITLE
cmake.ctestArgs does pass command line arguments to CTest properly

### ISSUE THREAD

**Issue by e-rap** [microsoft/vscode-cmake-tools#1299]
### Brief Issue Summary
Unable to pass arguments to CTest when pressing the Run CTest button. looking at the output logs it seems that the arguments are passed with quotations to ctest. In my case i wanted to pass the argument  `-L unit` to filter by unit tests. but the argument was passed as `"-L unit"` to the end of the CTest command.

### Expected:
should pass all arguments to CTest without quotation marks surrounding the arguments
1. Set CTest Aruments
2. Push Run CTest
3. Pass CTest arguments without quotes

### Apparent Behavior:

Passes CTest arguments with quotation marks surrounding them, causing CTest to ignore it.

### CMake Tools Log

```
[build] Build finished with exit code 0
[proc] Executing command: ctest -j10 -C Debug -T test --output-on-failure "-L unit"
[ctest]    Site: ******************
[ctest]    Build name: Win32-mingw32-make
```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.17.0 
- **VSCode Version**: 1.45.1 
- **CMake Tools Extension Version**: 1.4.0 
- **Compiler/Toolchain**: mingw64(gcc) 
- **Terminal**: git bash for windows

**Comment by e-rap** [comment]
> Which way did you set the setting?
> 
> ```json
>     "cmake.ctestArgs": [
>         "-L unit"
>     ],
> ```
> 
> or
> 
> ```
>     "cmake.ctestArgs": [
>         "-L",
>         "unit"
>     ],
> ```
> 
> ?

i was using "-L unit"

my mistake did not know you had to separate the arg + input on separate lines. Tried it with "-L", "unit" and it worked,

Thanks

**Comment by bobbrow** [comment]
Glad to hear it's working for you!
