### ISSUE TITLE
Environment variables which the executable tries to read

### ISSUE THREAD

**Issue by danewalton** [microsoft/vscode-cmake-tools#1306]
### Brief Issue Summary

How do I set environment variables for executables which would call `getenv()`. The debug instance seems to run in a different shell than the integrated shell so how would I get those in there. The `cmake.environment` property doesn't seem to do this.

### Expected:

I should be able to set some kind of `cmake.debugEnvironment` setting to allow the program to read some env vars.

### Platform and Versions

- **Operating System**: Any but I'm using Ubuntu 20.04
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.46
- **CMake Tools Extension Version**: 1.4.0
- **Compiler/Toolchain**: GCC 9.3.0

**Comment by bobbrow** [comment]
If using `launch.json` to begin debugging, add this to your configuration in `launch.json`:
```
  "env": {
    "myvar": "myval",
    ...
  }
```

If using the `CMake: Debug` command or statusbar icons, add this to your VS Code `settings.json`:
```
  "cmake.debugConfig": {
    "env": {
      "myvar": "myval",
      ...
    }
  }
```

**Comment by danewalton** [comment]
ahhhh that's how you do it thanks a bunch @bobbrow

**Comment by danewalton** [comment]
Hey @bobbrow I'm trying to use what you posted in Codespaces and it seems it might not be picking up the env vars. Have you guys tested whether it works there or not?
