### ISSUE TITLE
Support for debugger path resolution in launch.json

### ISSUE THREAD

**Issue by GaskoCoding** [microsoft/vscode-cmake-tools#1311]
In order to support various debuggers with various options etc. it will be necessary to use the launch.json file with launch configurations.

With the case of having multiple targets, CMake Tools provides the ability to use the command "${command:cmake.launchTargetPath}" after "program" which gets resolved to the current executable.

I would like to suggest that a similar feature be implemented to resolve a value for the "miDebuggerPath" variable that points to the current kits debugger exe (whether this location has to be specified in the kit configuration using a variable or is automatically detected does not matter).

This would allow for a single launch configuration to be used for multiple debuggers.

I encountered that this was an issue when I wanted to make use of both MinGW 32-bit and 64-bit toolchains in the same project. The gdb.exe programs were "incompatible" and I could not simply use one path for both kits as doing so resulted in an error.

The command could potentially be named "${command:cmake.kitDebuggerPath}", but that is purely a suggestion.

Otherwise keep up the awesome work on the plugin!

**Comment by GaskoCoding** [comment]
I have realized that the issue is rather something to do with my 64-bit debugger not being familiar with my 32-bit executable strangely enough, and that (actually) this should work out of the box. It is therefore a separate issue and not CMake Tools related. I have closed the issue.

**Comment by seppeon** [comment]
I agree with this issue completely. 
Do you happen to have multiple debuggers on your system and is CMake Tools selecting the incorrect one for your current configuration (thats what is happening to me).

**Comment by bobbrow** [comment]
@seppeon I'm not sure that this is something CMake Tools would know how to resolve for you, but if you have more information about how you're selecting a debugger based on a configuration, perhaps there's a way.  For the debug button, CMake Tools has a simple strategy, but once you're using launch.json, you have full control and can create the debugger configuration in the way that you like.
