### ISSUE TITLE
Configure On Open - new option 'Do not ask for configure CMake project'

### ISSUE THREAD

**Issue by danielroedl** [microsoft/vscode-cmake-tools#1319]
### Brief Issue Summary

Currently I can only check in the configuration 'Automatically configure CMake project directories when they are opened.'
If I don't check this option the extension asks every time I open a folder if i want to configure it. But I only want to configure a CMake project directory explicit.

I need this because I use VSCode only secondary for CMake builds. And so most of the time I don't want to configure the CMake projects.

### Expected:

1. Check a configuration option 'Don't ask for configure a CMake project directory'
1. When I open a CMake project directory there is no popup shown with the question for configure the CMake directory.

### Current Workaround:

1. Do something other
1. Enable CMake Extension
1. Do CMake build stuff
1. Disable CMake Extension
1. Do something other

**Comment by bobbrow** [comment]
Can you try setting `"cmake.configureOnOpen": false` in your "User" settings? In the UI, you click on the link to open the settings.json file and paste it in there: 
![image](https://user-images.githubusercontent.com/12818240/85056059-6c900080-b153-11ea-89e0-ef930bb63d33.png)

There's currently a problem with the setting that requires you to set it in json.  Once you do that, the setting should show up as a checkbox.

**Comment by danielroedl** [comment]
The entry "cmake.configureOnOpen": false is set in the "User" settings.
I don't had this issue (There is no red warning like in the screenshot above).
I checked also the settings.json and the entry is correctly set there.

Some information about the versions of VSCode:
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:04.923Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-37-generic

**Comment by danielroedl** [comment]
I am confused. Now it is working as expected. I don't get what I have changed.
Anyway, thanks for the support!
