### ISSUE TITLE
Use powershell as a default CMake/Launch terminal

### ISSUE THREAD

**Issue by EJShim** [microsoft/vscode-cmake-tools#1322]
Your issue may have an existing solution
-->

If I configure cmake project and launch using Shift + F5 ( Build without debugging). I can see the output from vscode terminal. 
 I set my default terminal of vscode as powershell, but CMake/launch terminal is always using cmd.

Is there any way I can set up default terminal for CMake/Launch?

**Comment by bilderbuchi** [comment]
Has this been implemented?
