### ISSUE TITLE
Command 'CMake: Quick Start' resulted in an error

### ISSUE THREAD

**Issue by younger-1** [microsoft/vscode-cmake-tools#1327]
### Brief Issue Summary
Hi, I am a new user of cmake tools. I got stuck when I first use it. I followed [this vscode_docs](https://code.visualstudio.com/docs/cpp/cmake-linux) and when I run the **CMake: Quick Start command**, VSCode pops up an Error Notification at the lower right corner:

> Command 'CMake: Quick Start' resulted in an error (EPERM: operation not permitted, stat 'C:\Program Files\WindowsApps')

### Expected:

1. run the **CMake: Quick Start command**
2. Enter a project name. This will be written to CMakeLists.txt and a few initial source files.

### Apparent Behavior:

1. run the **CMake: Quick Start command**
2. VSCode pops up an Error Notification at the lower right corner

### CMake Tools Log

```
[variant] Loaded new set of variants
[kit] Detected kits definition version change from undefined to 2. Silently scanning for kits.
[kit] Failed to scan C:\Program Files\WindowsApps by exception: {1}
[kit] Failed to scan C:\Program Files\WindowsApps by exception: {1}
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: EPERM: operation not permitted, stat 'C:\Program Files\WindowsApps' {"folder":{"uri":{"$mid":1,"fsPath":"c:\\Users\\younger\\source\\cmakeQuickStart","_sep":1,"external":"file:///c%3A/Users/younger/source/cmakeQuickStart","path":"/c:/Users/younger/source/cmakeQuickStart","scheme":"file"},"name":"cmakeQuickStart","index":0}}
[kit] Failed to scan C:\Program Files\WindowsApps by exception: {1}
[rollbar] Unhandled exception: Unhandled Promise rejection: quickStart Error: EPERM: operation not permitted, stat 'C:\Program Files\WindowsApps' {}
[kit] Failed to scan C:\Program Files\WindowsApps by exception: {1}
```

### Developer Tools Log

```
[2020-06-21 09:37:24.047] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cmake-tools {"startup":false,"extensionId":{"value":"ms-vscode.cmake-tools","_lower":"ms-vscode.cmake-tools"},"activationEvent":"onCommand:cmake.quickStart"}
[2020-06-21 09:37:24.047] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/younger/.vscode/extensions/ms-vscode.cmake-tools-1.4.1/dist/main
```
```
[CMakeTools] 2020-06-21T02:10:43.442Z [warning] [kit] Failed to scan C:\Program Files\WindowsApps by exception: {1}
[CMakeTools] 2020-06-21T02:10:43.471Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: quickStart Error: EPERM: operation not permitted, stat 'C:\Program Files\WindowsApps' {}
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.17.3
- **VSCode Version**: 1.46.0
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: 
  - Visual Studio 2019
  - msys2's Mingw64(gcc version 10.1.0)
  - clang&LLDB (clang version 10.0.0)

**Comment by bobbrow** [comment]
Did you open a folder in VS Code first?  Or are you running the command without a workspace?

**Comment by bobbrow** [comment]
Nevermind, I see that you have a folder open in your log.

**Comment by younger-1** [comment]
> Did you open a folder in VS Code first? Or are you running the command without a workspace?

Yes, the folder is `C:/Users/younger/source/cmakeQuickStart`, which is an empty folder.
And I try it again and still faild to run **CMake: Quick Start command**

**Comment by bobbrow** [comment]
I still can't reproduce this error.  There is something different about your environment that is causing this problem, but I'm not sure what it is.

Is `C:\Program Files\WindowsApps` in your PATH environment variable?  Did you launch vscode from that protected folder by chance?

**Comment by younger-1** [comment]
After I removed `C:\Program Files\WindowsApps` from my PATH environment, all the things started to work! Thank you! 

By the way, I am using a zip-archived vscode, which was installed through `scoop`. And it runs without elevated permission.

My workspace is not a multi-root workspace. So `C:\Program Files\WindowsApps ` is not there. I didn't have permission to enter that directory, so as any other programs like cmakeTools.

So I think maybe cmakeTools will scan through every variable's content in PATH environment at the first time it launches?

**Comment by bobbrow** [comment]
I know it scans through the PATH when searching for compilers, but I'm not seeing where that could be affecting the QuickStart code.

**Comment by younger-1** [comment]
I don't know either :octocat:

**Comment by djairao** [comment]
I think ignoring folders without permissions would be a useful feature. 
I have a similar issue working on a cluster (I don't have admin rights) and there is an inaccessible entry in my PATH from some software module and have to depend on Admins to resolve, which takes time. 
This would also be an issue/challenge for novices trying to use vs-code.

**Comment by xprss** [comment]
I have this error: I'm learning how to use CMake and, following a youtube tutorial, I tried the quick start command, but it says cmake.quickStart is not found. May somebody help me?

**Comment by gcampbell-msft** [comment]
@v-frankwang FYI about this issue.

**Comment by v-frankwang** [comment]
@gcampbell-msft I verified this issue on three different platforms but none of them would reproduce the issue, here are the detailed results:

**ENV:**
CMake Tools:v1.18.43
C/C++: 1.20.5
vscode: 1.91.1
**windows:**
![image](https://github.com/user-attachments/assets/71a99aa5-c7a7-4922-ae7a-1c9251896f6b)
 **Liunx:**
![quickstart](https://github.com/user-attachments/assets/074e052b-cbe3-469c-b9fc-ee60c91593ba)

**Mac:**
<img width="1440" alt="quickstart" src="https://github.com/user-attachments/assets/10097aca-a8b8-4d3e-bad0-50320664e6d9">
