### ISSUE TITLE
"command:cmake.launchTargetPath" consistently 1 second slower than manual program path

### ISSUE THREAD

**Issue by gvcallen** [microsoft/vscode-cmake-tools#1328]
I am debugging a Qt target with VS Code and CMake Tools. For that reason, I assume Qt needs to store a reasonable amount of debug information in the executable. I am therefore getting around 5.5 seconds time from press of my debug key with the "program" path in my launch.json manually entered. This is expected (I run Qt Creator with the same project and got a very similar time).

However, when I make use of the ${command:cmake.launchTargetPath} to detect my executable location, this takes significantly slower (around 6.5 seconds). I understand that CMake tools needs to determine whether or not the build is up to date, but I can't believe that this should be taking 1 second. Is there something wrong?

I understand 1 second doesn't seem like much, but when you are constantly running your target, changing something in the gui, making sure the layout is correct etc. it can make a massive difference.

On a side note, running my release target via VS Code is incredibly slow compared to Qt Creator release mode (still about 5.5 on VS Code, and about 1 second on Qt Creator). What could be causing this in VS Code?

Compiler: MinGW 8.1.0 64-bit 
OS: Windows 10
Build system: Ninja
Debugger: GDB

**Comment by bobbrow** [comment]
Are you able to capture performance traces for us?  Ideally you could send us a trace from each scenario (one with the variable expansion, and one without).

1. Go to "Help" -> "Toggle Developer Tools"
2. Select the "Performance" tab
3. Click the record button to start a trace.
4. Run the scenario.
5. Click the "stop" button to stop the recording.
