### ISSUE TITLE
clang 10 from llvm.org not recognized

### ISSUE THREAD

**Issue by imag0r** [microsoft/vscode-cmake-tools#1330]
### Brief Issue Summary

VSCode fails to detect clang 10 from apt.llvm.org

Setup: VSCode with CMake tools 1.4.1 using SSH remote to Debian 10 machine with freshly installed clang-10 from https://apt.llvm.org/ (using the automatic installation script)

### Expected:
clang-10 kit detected and available for use

### Apparent Behavior:
kit not detected

### CMake Tools Log

2020-06-24T21:12:55.734Z [debug] [kit] Bad Clang binary /usr/bin/clang -v output: Debian clang version 10.0.1-++20200618012613+f5a9c661a35-1~exp1~20200617233238.175 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64

### Platform and Versions

- **Operating System**: Debian 10 (Buster)
- **CMake Version**: 3.13.4
- **VSCode Version**: 1.46.1 + Remote SSH 0.51.0
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: CLang 10, use automatic install script from https://apt.llvm.org/

**Comment by bobbrow** [comment]
I submitted a PR to fix this.  Thanks for the bug report!

**Comment by bobbrow** [comment]
This is available in [1.4.2](https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.2)
