### ISSUE TITLE
Feature, upgrade  vscode to @types/vscode

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#1336]
https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest

**Comment by bobbrow** [comment]
We did this in cpptools a few months ago. For reference: https://github.com/Microsoft/vscode-cpptools/commit/289562e44278c1aa2e0e4b0e967a647fd442e147
