### ISSUE TITLE
Per-workspace build directory

### ISSUE THREAD

**Issue by KyleFromKitware** [microsoft/vscode-cmake-tools#1345]
My workflow often involves build directories that were created outside of an IDE (on the command line), and they don't always have the same name or location. However, CMake Tools forces the build directory to always have the same name and location relative to the workspace. It would be nice if this could be configured on a per-workspace basis.

**Comment by bobbrow** [comment]
Have you seen the `cmake.buildDirectory` setting?  We default to `${workspaceFolder}/build` but you should be able to set the build location to wherever you want.  Or am I misunderstanding your issue?

**Comment by KyleFromKitware** [comment]
> Have you seen the `cmake.buildDirectory` setting?

Yes, I saw that in the settings, but that configures it at a global level. I might have one workspace where the build directory is at `build`, but another where it's at `build/ninja`, and I want to configure this on a per-workspace basis.

**Comment by bobbrow** [comment]
VS Code lets you do that too.  If you click on the "workspace" tab (or "Folder" for multi-root projects) you can select a different build directory for each folder you open.  This will end up saving a setting in the `${workspaceFolder}/.vscode/settings.json` file that overrides the global setting and applies just to that folder.

![image](https://user-images.githubusercontent.com/12818240/86277099-fe9ffc00-bb8a-11ea-9023-05a562f60070.png)

**Comment by KyleFromKitware** [comment]
D'oh! I see it now. I didn't realize settings in general could be configured on a per-workspace (and apparently per-folder) basis. Thanks for helping a n00b.

**Comment by bobbrow** [comment]
Glad that worked for you. Not to worry about not seeing that in the UI. It's very easy to miss.
