### ISSUE TITLE
CMake Tools configuration provider does not activate until project is built

### ISSUE THREAD

**Issue by KyleFromKitware** [microsoft/vscode-cmake-tools#1346]
### Brief Issue Summary

When I open VSCode and open an existing workspace, the CMake Tools configuration provider does not activate until I build the project, even if the build tree already exists (with the File API response present.)

### Expected:

1. Open VSCode
2. Open existing workspace with existing build tree which has File API response
3. Code model should be loaded from existing build tree

### Apparent Behavior:

1. Open VSCode
2. Open existing workspace with existing build tree which has File API response
3. Code model is not loaded until project is built, resulting in lots of missing files and symbols (due to some files being generated in the build tree), and "CMake Tools" is not available in "C/C++: Change Configuration Provider", but this is fixed once you build the project

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.18.0-rc2
- **VSCode Version**: 1.46.1
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: GCC 5.4

**Comment by bobbrow** [comment]
The integration with cpptools does not happen until you "configure" your project.  Doing a build will run the "configure" command.  There is also a setting to instruct CMake Tools to "configure" automatically when you open the folder.  Can you try setting `cmake.configureOnOpen` to true?

**Comment by bobbrow** [comment]
(we might also change the default for this setting to "true" as part of the fix for https://github.com/microsoft/vscode-cmake-tools/issues/1230)

**Comment by KyleFromKitware** [comment]
I can confirm that enabling "configure on open" solves this. However, I don't *want* it to configure automatically, only when I explicitly tell it to. The build tree already has the File API response files, which should be sufficient to load the codemodel without reconfiguring.

**Comment by bobbrow** [comment]
I understand. We only recently added cmake-file-api support and we have a request open to read the code model without configuring. #1149.
