### ISSUE TITLE
Unable to change generator without complete project rebuild

### ISSUE THREAD

**Issue by csorvagep** [microsoft/vscode-cmake-tools#1353]
### Brief Issue Summary
I'm unable to change generators without complete removal of build directory and reload VS Code.

### Expected:
Changing setting `cmake.generator` (and or related ones) and reconfigure / rebuild should work without deleting build and reload window.

After changing the generator setting and choosing _Clean Reconfigure All Projects_ the executed cmake command stays the same.

### Platform and Versions

- **Operating System**: Windows 10 1909
- **CMake Version**: 3.17.3
- **VSCode Version**: 1.46.1
- **CMake Tools Extension Version**: 1,4.1
- **Compiler/Toolchain**: Visual C++ 2019, GCC 10.1 (MinGW)

**Comment by bobbrow** [comment]
Thank you for reporting this issue.
I believe this should be covered by #1127
