### ISSUE TITLE
CMAKE_BUILD_TYPE value empty on configure and install using VS Code

### ISSUE THREAD

**Issue by karan-k-deepr** [microsoft/vscode-cmake-tools#1358]
I am using `VS Code` on `windows 10` since last year, and it is working perfectly with `vscode-cmake-tools`. 
Cmake command:
```
message("Build type of project is : " ${CMAKE_BUILD_TYPE})
```
The expectation is when I `configure` cmake project it should show the selected configuration.
When Debug build is selected from status bar of VS code.
Expected result would be:
```
Build type of project is : Debug
```
But unfortunately, it is not showing build type
```
Build type of project is : 
```

Same case happened when I `Cmake: Release` project.
It is not able to detect the selected build type. 
Can anyone please suggest what to do in this case to get selected values in `cmake_build_type` ?

**Comment by bobbrow** [comment]
Were you previously using the Ninja generator, and now CMake Tools has switched you to the Visual Studio generator (as of 1.4)?  If so, the solution is to add:
```
  "cmake.preferredGenerators": [ "Ninja" ]
```
to your settings.  This could be another vote for #1347

**Comment by karan-k-deepr** [comment]
> Were you previously using the Ninja generator, and now CMake Tools has switched you to the Visual Studio generator (as of 1.4)? If so, the solution is to add:
> 
> ```
>   "cmake.preferredGenerators": [ "Ninja" ]
> ```
> 
> to your settings. This could be another vote for #1347

Actually this setting is not set in the project, so it might use the default generator for the project.
I tried with changing `"cmake.prefferedGenerators": [ "Ninja" ]` but it doesn't make any change.

**Comment by andreeis** [comment]
Any change in generator settings needs a reload of the project in order to take effect. We have another issue for fixing this in future so that such reload would not be required.

**Comment by karan-k-deepr** [comment]
@andreeis What all changes is required to make things working like before. I am searching for it since I posted this issue, and it really hampers my performance. :(  Or I have to wait until there is a new release?

**Comment by andreeis** [comment]
Only one time close+reopen either your project or your workspace or VSCode should be sufficient for the setting cmake.prefferedGenerators to take effect.
You are saying that such close and reopen did not get you in the state before the last release?

**Comment by karan-k-deepr** [comment]
Yes, I tried close and re-open VS Code as well as restart system multiple times didn't help me either. I even tried with deleting all cache and reconfigure full project, but still, the issue remains the same.

**Comment by bobbrow** [comment]
I see a mispelling in your preferredGenerators setting from your response.  Can you confirm which generator is actually being selected?  CMAKE_BUILD_TYPE is not set when Visual Studio is the generator because it generates a project with all build types.  Ninja will set the CMAKE_BUILD_TYPE because it only generates one build type per variant.

**Comment by karan-k-deepr** [comment]
@bobbrow `preferredGenerators` was my typing mistake while writing a reply here. This is the one which I am using in my VS Code `settings.json`. 
```
        "cmake.preferredGenerators": [
            "Ninja"
        ],
```
Actually everything was working fine previously and I didn't make any change in VS Code settings which leads to this error.

**Comment by bobbrow** [comment]
Glad to hear it's working now!
