### ISSUE TITLE
launch in terminal with custom working directory

### ISSUE THREAD

**Issue by UniChen** [microsoft/vscode-cmake-tools#1359]
when I execute "launch in the terminal window"
![image](https://user-images.githubusercontent.com/12457245/87130949-42e77680-c2c6-11ea-86b2-64efa847b703.png)

my executable "main.exe" is working well.
But it will cause exception when loading external files, like below : 

```
D:\Test>"D:\Test\bin\simulator\main.exe"
Hello World

error: unable to open primary document entity 'D:\Test\test.config'
```

It looks like working directory is not my expected cause cannot find "test.config". 

In fact, test.config exists in D:\Test\bin\simulator

So, how can I setting working directory before launch ?

I think if I can setting working directory to "D:\Test\bin\simulator", everything is fine.

**Comment by bobbrow** [comment]
I'm not sure how we missed this issue, but we fixed it last year in the 1.5 release.  https://github.com/microsoft/vscode-cmake-tools/pull/1444

You can use the `cmake.debugConfig.cwd` setting to override the CWD for the "run in terminal" button.
