### ISSUE TITLE
Cmake hang up while trying to configure a folder

### ISSUE THREAD

**Issue by maschgit** [microsoft/vscode-cmake-tools#1372]
Due to @bobbrow suggestion I create an issue reffering [#1362 ](https://github.com/microsoft/vscode-cmake-tools/issues/1362#issuecomment-659562287)

### Brief Issue Summary

I repeat, what I wrote in in [#1362](https://github.com/microsoft/vscode-cmake-tools/issues/1362#issuecomment-659430864)
A problem with the current solution is that if path in which no CMakeLists.txt file is located the CMake Tool is stopping with further configuration of other paths, even if in the other paths CMakeLists.txt are located.
My workaround is to set the paths in which no CMakeLists.txt files are located after all paths where CMakeLists.txt are located.

While I'm writing this lines, I see, that I explained my problem not correct. Sorry for that.
Cmake stops, because the cmake tool is searching for a linker script file, which is set in a toolchain file, which is not available for this path. In this path is only a CMakeLists.txt file is available. This CMakeLists.txt file creates a library.
The structure is:
The top CMakeLists.txt file (let's say project 1) includes a Toolchain file in which a linker script file is set.
This CMakeLists.txt file of project 1 includes several subdirectories. Each subdirectory creates a library.
So the main CMakeLists.txt file of project 1 merges all libraries to one output file.
Each subdirectory, for example "drivers" contains a CMakeLists.txt file, which includes source files.
The output of this CMakeLists.txt is a drivers.lib.
I've added the path of drivers to the workspacesettings file to be able to see the folder in the file explorer.
Drivers is not located in a subpath of project 1. Drivers is a "standalone" path, because drivers is used by other projects, too.
CMake tool scans the workspacesettings file and add the drivers path to the cmake tool pane.
Because drivers cannot be created without a toolchain file, which is not available in the drivers folder, the cmake tool stops to configuring all other paths, which are given.
If the order of paths in the workspacesettings file is like:
- project 1
- project 2
- drivers
- project 3

Project 3 will never be created, altough project 3 contains a toolchain file and it is correct configured, because drivers path don't have a toolchain file.

The correct order needs to be:
- project 1
- project 2
- project 3
- drivers

In this order all three projects creates their correct output files and drivers cmake configuration will crash.

### Expected:

I think a setting where I can cmake tool tell, that only the main paths shall be configured.
I think this could be a little bit difficult, because e.g. drivers is a path which is needed by project 1.
Cmake tool needs to differe between calling drivers from project 1 and drivers direct.
If this could be possible, then cmake will detect drivers as standalone and stop to configure without "crash".

### Apparent Behavior:

Stop to configure project, because of missing toolchain file. 

### CMake Tools Log

The output of the configuration process is:
```
[main] Configuring folder: drivers 
[proc] Executing command: C:\msys64\mingw64\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=C:\GnuToolChain\9_2019_q4_major\bin\arm-none-eabi-gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=C:\GnuToolChain\9_2019_q4_major\bin\arm-none-eabi-g++.exe -Hd:/GitRepos/7700_software/drivers -Bd:/GitRepos/7700_software/drivers/build/Debug -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 9.2.1
[cmake] -- The CXX compiler identification is GNU 9.2.1
[cmake] -- Check for working C compiler: C:/GnuToolChain/9_2019_q4_major/bin/arm-none-eabi-gcc.exe
[cmake] -- Check for working C compiler: C:/GnuToolChain/9_2019_q4_major/bin/arm-none-eabi-gcc.exe - broken
[cmake] CMake Error at C:/msys64/mingw64/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "C:/GnuToolChain/9_2019_q4_major/bin/arm-none-eabi-gcc.exe"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: D:/GitRepos/7700_software/drivers/build/Debug/CMakeFiles/CMakeTmp
[cmake]     
[cmake]     Run Build Command(s):C:/msys64/usr/bin/make.exe cmTC_a065b/fast && /usr/bin/make  -f CMakeFiles/cmTC_a065b.dir/build.make CMakeFiles/cmTC_a065b.dir/build
[cmake]     make[1]: Entering directory '/d/GitRepos/7700_software/drivers/build/Debug/CMakeFiles/CMakeTmp'
[cmake]     Building C object CMakeFiles/cmTC_a065b.dir/testCCompiler.c.obj
[cmake]     C:/GnuToolChain/9_2019_q4_major/bin/arm-none-eabi-gcc.exe    -o CMakeFiles/cmTC_a065b.dir/testCCompiler.c.obj   -c D:/GitRepos/7700_software/drivers/build/Debug/CMakeFiles/CMakeTmp/testCCompiler.c
[cmake]     Linking C executable cmTC_a065b.exe
[cmake]     C:/msys64/mingw64/bin/cmake.exe -E rm -f CMakeFiles/cmTC_a065b.dir/objects.a
[cmake]     C:/msys64/mingw64/bin/ar.exe cr CMakeFiles/cmTC_a065b.dir/objects.a @CMakeFiles/cmTC_a065b.dir/objects1.rsp
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/GitRepos/7700_software/drivers/build/Debug/CMakeFiles/CMakeOutput.log".
[cmake] See also "D:/GitRepos/7700_software/drivers/build/Debug/CMakeFiles/CMakeError.log".
[cmake]     C:/GnuToolChain/9_2019_q4_major/bin/arm-none-eabi-gcc.exe      -Wl,--whole-archive CMakeFiles/cmTC_a065b.dir/objects.a -Wl,--no-whole-archive  -o cmTC_a065b.exe -Wl,--major-image-version,0,--minor-image-version,0 
[cmake]     c:/gnutoolchain/9_2019_q4_major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: unrecognized option '--major-image-version'
[cmake]     c:/gnutoolchain/9_2019_q4_major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: use the --help option for usage information
[cmake]     collect2.exe: error: ld returned 1 exit status
[cmake]     make[1]: *** [CMakeFiles/cmTC_a065b.dir/build.make:109: cmTC_a065b.exe] Error 1
[cmake]     make[1]: Leaving directory '/d/GitRepos/7700_software/drivers/build/Debug/CMakeFiles/CMakeTmp'
[cmake]     make: *** [Makefile:141: cmTC_a065b/fast] Error 2
[cmake]     
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:2 (project)
[cmake] 
[cmake]
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**:  Windows 10 build 2004
- **CMake Version**:  3.17
- **VSCode Version**: 1.47.1
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: gcc-arm-none-eabi-9-2019-q4-major

**Comment by bobbrow** [comment]
Thank you for opening an issue for this.
