### ISSUE TITLE
CMake Tools adds configurations with incorrect paths. 

### ISSUE THREAD

**Issue by salda** [microsoft/vscode-cmake-tools#1375]
see https://stackoverflow.com/questions/62962077/how-to-fix-linux-paths-created-by-cmake-tools-in-vscode-c-cpp-properties-json

**Comment by bobbrow** [comment]
CMake Tools does not create `c_cpp_properties.json` nor does it add configurations to that file. Do you have another extension that is writing those?

Check the status bar to see which configuration is active (Linux or Win32).
![image](https://user-images.githubusercontent.com/12818240/87838054-83a53980-c84a-11ea-83a0-2e9235108b7e.png)

If it shows the wrong one, click the text and a drop down menu will appear to change it to the Win32 config.  However, it looks like your Win32 config is missing: `"configurationProvider": "ms-vscode.cmake-tools",`

**Comment by salda** [comment]
1) You are right, there was Linux and changing it to Win32 fixed the problem. Thanks!
2) I have only following 3 extensions and the configuration could have been added by VSCode itself after I probably ctrl+shift+p and added the Win32 configuration, but then, how to add the Windows configuration correctly after moving the project from Linux? Why it chose the Linux configuration at first? I would expect that the Linux configuration wouldn't be used by default on Windows. 
![image](https://user-images.githubusercontent.com/3855627/87838700-2a63f700-c898-11ea-8218-4d3af52d0fb0.png)

**Comment by bobbrow** [comment]
I'm not sure why it would choose Linux at first.  Did you clone a project with these settings already committed to a file?  For new folders, the C++ extension doesn't create this file until you try to edit its properties.  And when it does, it only creates one that matches your current OS.  (BTW, the name actually isn't important, you can create as many configurations as you want with whatever name you want in that file)
