### ISSUE TITLE
Support more variables for the build directory name

### ISSUE THREAD

**Issue by strega-nil** [microsoft/vscode-cmake-tools#1382]
As far as I can tell, there is no way to name the build directory in a way that includes more information than just "is this Debug or Release"; I personally need a way to describe different target architectures, i.e., I want to be able to build for all of [x86, x64, ARM, ARM64] without having to delete and reconfigure the build directory. Is that a possibility?

**Comment by bobbrow** [comment]
I believe that PR #1337 will address this issue.

**Comment by strega-nil** [comment]
awesome, thanks @bobbrow :)

**Comment by strega-nil** [comment]
This seems to be complete 😄
