### ISSUE TITLE
Msys2 Mingw64 doesn't ship make.exe and cmake-tools is unable to detect mingw32-make.exe instead

### ISSUE THREAD

**Issue by Nek-12** [microsoft/vscode-cmake-tools#1384]
### Brief Issue Summary
On Windows, Msys2 doesn't ship make.exe with mingw64. (In fact, it doesn't ship any make.exe). The executable uses mingw32-make.exe in the same folder though.
### Expected:  
Cmake-tools detects and uses the appropriate make.exe automatically.  
### Apparent Behavior:
cmake-tools throws an error "Unable to determine what CMake generator to use." despite having detected all the other files automatically.  
### Platform and Versions  

- **Operating System**: Windows 10 x64   
- **CMake Version**: cmake 3.17.3 mingw-w64  
- **VSCode Version**: VSCodium 1.47.2  
- **CMake Tools Extension Version**: 1.4.1  
- **Compiler/Toolchain**: g++ and gcc (Rev3, Built by MSYS2 project) 10.1.0  
### Other Notes/Information
To fix the issue manually:  
1. Launch MSYS2 console.  
2. `cd /mingw64/bin`
3. `ln -s mingw32-make.exe make.exe`
4. In VSCode, execute command `>[Cmake] Select a kit`
5. -> [Scan for kits]
6. Your version of compiler should appear. 
Proper folders should be added to path.

**Comment by Riku32** [comment]
Bump

**Comment by bobbrow** [comment]
@Riku32 we track community reactions in our queries, so if you can add a 👍 reaction to the first comment, that will help us out.  Thanks!

**Comment by bilderbuchi** [comment]
Is this still an issue? I just started working on a cmake project, and it seemed to pick up mingw32-make without issue? My kit is displayed as GCC 8.1.0 x86_64-w64-mingw32. One potential difference - I installed mingw directly, not via msys.

**Comment by sspacelynx** [comment]
This is an issue on windows too, only present when using mingw64 via MSYS2. @bilderbuchi it does work fine when installing mingw directly. Simple workaround is to make a symlink with `mklink make.exe mingw32-make.exe`

**Comment by gcampbell-msft** [comment]
For now we are going to close this issue as there is a way to fix this, which is by installing mingw directly. Closing this issue for now and please open a new issue if you are still facing issues. 

Thanks.
