### ISSUE TITLE
Capitalization of CMake in the VsCode extension settings page is not standard

### ISSUE THREAD

**Issue by thalesx** [microsoft/vscode-cmake-tools#1387]
### Brief Issue Summary

Yes it's nitpicking, but the term shows up as "Cmake" instead of "CMake" (or even "cmake") in the UI for the extension's settings page, and AFAIK the standard capitalizations for it are "CMake" or "cmake".

![Cmake](https://user-images.githubusercontent.com/26282603/88833993-05b92a80-d188-11ea-8cbc-8668152ed10f.PNG)

### Platform and Versions

- **Operating System**: Windows
- **VSCode Version**: 1.47.3
- **CMake Tools Extension**: v1.4.1

**Comment by bobbrow** [comment]
I'm not aware of a way to fix this.  There are no [contribution points](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) available to modify the setting name.  VS Code itself does the capitalization based on settings names.  Could you open an issue for vscode to consider it?

**Comment by thalesx** [comment]
Absolutely! I had a hunch it could be VsCode. I'll follow up there.
