### ISSUE TITLE
Integration with tasks.json and launch.json

### ISSUE THREAD

**Issue by rasmus98** [microsoft/vscode-cmake-tools#1394]
### Brief Issue Summary

When setting up a cmake project, everything works fine, and I can build and enter the debugger by running cmake: debug. But this is completely disconnected from the usual debugging system (ctrl+b running tasks.json, F5 running launch.json). This extension generates the settings.json (which can thus be edited), but what happends when i press "cmake: build" and "cmake: debug" is completely opaque. 

I need to develop with OpenMPI, and thus when running release mode, launch the program with mpicc, and thus i really need to be able to edit the launch task. And it just seems very strange to not be able to use the default shortcuts and lauch buttons.

### Expected:

The extension should integrate into the existing build and run processes of vs code, ie cmake should make tasks.json and launch.json files, and cmake:build and cmake:debug should be aliases to those. Or the other way around. The same way that the extension is able to make a settings.json file which sets up propper include paths

It is very possible that this is somehow possible to set up, but it seems strange that a vs code build generator does not generate build and debug files that vs code can understand by default.

**Comment by bobbrow** [comment]
We are working on making this better (see PR #1268).

There is a way to amend the contents of the launch object that we generate.  You can use the `cmake.debugConfig` setting.  This has a few limitations and is something we have an issue open for (#1101).
