### ISSUE TITLE
Unhandled Promise rejection: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode-cmake-tools#1399]
For a while I've been getting `Unhandled Promise rejection` errors on pretty much every cmake task, e.g. when running the build task using `"cwd": "${command:cmake.buildDirectory}"` or configure:
```
[cmakefileapi-parser] Read reply folder: .../.cmake/api/v1/reply
[cmakefileapi-parser] Found index files: ["cache-v2-fda6177f19fa1b3ac154.json",....
[rollbar] Unhandled exception: Unhandled Promise rejection: buildDirectory SyntaxError: Unexpected end of JSON input {}
...
[rollbar] Unhandled exception: Unhandled Promise rejection: configure SyntaxError: Unexpected end of JSON input {}
```

After deleting the .cmake directory the problems disappeared so it must have been corrupt somehow.
A better error message would have saved me much time cause I thought it referred to the tasks.json or similar.

**Comment by bobbrow** [comment]
There was a bug in the logging which was fixed with https://github.com/microsoft/vscode-cmake-tools/pull/1348. It should be in the next release.  Thanks for letting us know!

**Comment by Trass3r** [comment]
Are you sure that will fix this? Doesn't sound related:
>  If an object is passed in, the {0} string will remain in the final output
