### ISSUE TITLE
Option to resolve build diagnostics relative to workspace folder

### ISSUE THREAD

**Issue by i-ky** [microsoft/vscode-cmake-tools#1401]
### Brief Issue Summary

It is a [known problem](https://cmake.org/pipermail/cmake/2011-December/048266.html) that achieving reproducible builds with CMake requires hacks and workarounds, especially if compiler in use does not support `-ffile-prefix-map`. In our project we apply some trickery to ensure that compiler is always invoked from the source root with a relative path to source file. As a result of that, compiler prints all errors and warnings with paths relative to the source root instead of absolute paths or paths relative to build directory:
```
[build] some/path/relative/to/source/root/foo.cpp:12:2: error: #error test
[build]  #error test
[build]   ^
```
This confuses CMake Tools, if extension detects that path is relative, it appends it to build directory. In _Problems_ tab we see something like:
```
foo.cpp build/directory/some/path/relative/to/source/root
#error test GCC [12, 2]
```
Some relevant code:
https://github.com/microsoft/vscode-cmake-tools/blob/8faa5dad3f7a07f7ddc83f069e1ce1c88fee3a2d/src/cmake-tools.ts#L912
https://github.com/microsoft/vscode-cmake-tools/blob/8faa5dad3f7a07f7ddc83f069e1ce1c88fee3a2d/src/diagnostics/build.ts#L43
https://github.com/microsoft/vscode-cmake-tools/blob/8faa5dad3f7a07f7ddc83f069e1ce1c88fee3a2d/src/diagnostics/build.ts#L71
https://github.com/microsoft/vscode-cmake-tools/blob/8faa5dad3f7a07f7ddc83f069e1ce1c88fee3a2d/src/diagnostics/build.ts#L82
https://github.com/microsoft/vscode-cmake-tools/blob/8faa5dad3f7a07f7ddc83f069e1ce1c88fee3a2d/src/util.ts#L127-L131

### Expected:

We need some sort of configuration option to be able to resolve compiler diagnostics relative to the source root.

### Apparent Behavior:

Currently, diagnostics are reported with wrong file path and cannot be opened by clicking on them.
```
Unable to open 'foo.cpp': Unable to read file '/workspace/folder/build/directory/some/path/relative/to/source/root/foo.cpp' (Error: Unable to resolve non-existing file '/workspace/folder/build/directory/some/path/relative/to/source/root/foo.cpp').
```

### Platform and Versions

- **Operating System**: Ubuntu 16.04
- **CMake Version**: 3.15.5
- **VSCode Version**: 1.47.3
- **CMake Tools Extension Version**: 0.29.0
- **Compiler/Toolchain**: GCC 4.9.3

**Comment by bobbrow** [comment]
If you would like to add a new setting (e.g. `cmake.buildDiagnosticsRootPath`) and do a PR for this feature, we would be happy to review and accept it.

**Comment by i-ky** [comment]
We managed to work around the issue using
```json
"cmake.buildTask": true
```
in `settings.json` and a custom build task in `tasks.json`:
```json
{
    "label": "Build selected configuration",
    "group": {
        "kind": "build",
        "isDefault": true
    },
    "type": "shell",
    "command": "/bin/bash",
    "args": [
        "-c",
        "${command:cmake.tasksBuildCommand}"
    ],
    "problemMatcher": "$gcc"
}
```
This way we gained control over `problemMatcher` and now it seems to be doing the right thing.

I have to say it took us a while to figure out how `cmake.buildTask` was supposed to work, it is a pity that #647 got merged without documentation update.

**Comment by dagar** [comment]
I've come across the same problem with the current workaround of using a custom build task that sets a relative file location for the problemMatcher.

``` json
        {
            "label": "build",
            "type": "shell",
            "command": "/bin/bash",
            "args": [
                "-c",
                "${command:cmake.tasksBuildCommand}"
            ],
            "options": {
                "cwd": "${command:cmake.buildDirectory}"
            },
            "group": {
                "kind": "build",
                "isDefault": true,
            },
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": ["relative", "${command:cmake.buildDirectory}"]
            }
        },
```

Is this not in general the right thing to do with cmake? With Ninja it doesn't appear to be possible to have non-relative paths.

**Comment by v-frankwang** [comment]
@i-ky We have attempted to verify this issue on CMake tools: v1.19.45, but we don't have detailed reproduction steps to reproduce it. Are you able to go and verify that the issue is fixed?

**Comment by i-ky** [comment]
Hi @v-frankwang!

The thing is, I reported this issue while working on a closed source commercial project. That's why there aren't too many details in the description. Since then I have switched a couple of workplaces, so I cannot verify if the fix is working for the original use case. I have reached out to my ex-colleague asking to verify and if I get any feedback I will let you know.

From what I see in #3780 the fix should be OK.

Maybe @fargies, the author of #3780, can provide detailed steps to reproduce?

As a last resort you can write a small script pretending to be a compiler and mock error messages using it.

**Comment by v-frankwang** [comment]
@i-ky Thank you very much for your reply, I hope you can update the review if you can verify this.
