### ISSUE TITLE
Automatically update CMakeLists when adding or removing a source file

### ISSUE THREAD

**Issue by amg98** [microsoft/vscode-cmake-tools#1402]
Would be interesting to avoid developers to do this by hand.

**Comment by bobbrow** [comment]
Thank you for the feature idea.

**Comment by djairao** [comment]
I think this is a great feature to have.

**Comment by stanle-cs** [comment]
Great Idea, I was looking for a way to do this. The GLOB feature seems to do just that but it is unfortunately not recommended by the CMake document. If the tool can handle this for us then... ;)

**Comment by amg98** [comment]
I think it could something simple, for example when adding or removing a file with *.cpp extension, look for the CMakeLists.txt file in the same folder and update a variable defined there with the list of source files.

**Comment by andreeis** [comment]
@amg98, we have a new issue opened for this exact idea: https://github.com/microsoft/vscode-cmake-tools/issues/2132. We didn't realize about the duplicate. We are closing this and keep 2132 since that already has some design discussion started from the community.
