### ISSUE TITLE
Failure on delivering Custom Configuration

### ISSUE THREAD

**Issue by srijanc** [microsoft/vscode-cmake-tools#1409]
I have been following up on an issue I started facing when update to C/C++ IntelliSense received an update to version 0.30.0-insider and the include files were throwing an error. The issue raised can be found [here](https://github.com/microsoft/vscode-cpptools/issues/5906) and I was requested to raise an issue here.

My OUTPUT under C/C++:
`Custom browse configuration received: {
  "browsePath": []
}`

All the config files and setting can be found on the issue raised (link provided above).

### CMake Tools Log
```
[variant] Loaded new set of variants
[kit] Successfully loaded 4 kits from /home/ubuntu/.local/share/CMakeTools/cmake-tools-kits.json
```

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.48.0
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: GCC 7.5.0

### Other Notes/Information

I have already provided all the log files requested in this [issue](https://github.com/microsoft/vscode-cpptools/issues/5906).

**Comment by bobbrow** [comment]
Thanks for reporting this issue.  The issue you linked is quite long and has tons of links to logs in it, can you please share the most relevant ones here?  Is this a project that we can clone to reproduce the behavior on our computers?

**Comment by srijanc** [comment]
@bobbrow I have found a potential mistake in my project setup and solving it might also solve this issue. Allow me few days to revert back on this.

**Comment by srijanc** [comment]
This issue has now been resolved. As stated in the linked issue, the CMake version 3.10 was buggy and is suggested to use any CMake v3.14 or higher.
