### ISSUE TITLE
Feature request: custom targets

### ISSUE THREAD

**Issue by tkielan** [microsoft/vscode-cmake-tools#1413]
When the CMake project utilizes CPack there is no way to choose "package" target to be built from the drop-down.
In addition it would be nice to have option (settings.json) to provide additional list of targets that can be chosen form the target menu (with descriptions) for the project.

**Comment by amurzeau** [comment]
related: https://github.com/microsoft/vscode-cmake-tools/issues/543, https://github.com/microsoft/vscode-cmake-tools/issues/2192

**Comment by gcampbell-msft** [comment]
Closing as a duplicate of #2192 since the most supported way that this can be done is CMake Package Presets.
