### ISSUE TITLE
Cross compiling using cmake-tools

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#142]

**Comment by frodak17** [comment]
@vector-of-bool Shouldn't this already be working?

For cross-compiling I simply use a toolchain.cmake file to setup the cross-compiler and then use a Makefile generator.

I haven't tried it yet using `cmake-tools` but aren't they already supported?'

From the documentation for kits:
> {
>     "name": "Emscripten",
>     "toolchainFile": "/path/to/emscripten/toolchain.cmake"
> }

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
