### ISSUE TITLE
cmake build Executing command cause OOM

### ISSUE THREAD

**Issue by TSKangetsu** [microsoft/vscode-cmake-tools#1422]
![image](https://user-images.githubusercontent.com/43801783/91631627-a1e78300-ea0d-11ea-8add-ed188b5f9fdd.png)

how to change the "-j 6" ? It cause OOM and raspberrypi3B stuck , and i try add "cmake.buildArgs"  , do not work...

**Comment by bobbrow** [comment]
Use the `cmake.parallelJobs` setting to reduce the number of build tasks.

**Comment by TSKangetsu** [comment]
It works well ! Thanks
