### ISSUE TITLE
Support for workspace dependencies

### ISSUE THREAD

**Issue by bzeller** [microsoft/vscode-cmake-tools#1424]
### Brief Issue Summary

When developing several projects together it would be helpful to being able to define inter dependencies between the projects.
For exampe I want to work on a project that is split between a library and a executable ( each is in its own CMake project seperate from each other ) , first the library should be built, then the executable. 

### Expected:

I can define which projects depend on each other on workspace level. 

### Apparent Behavior:

Currently there is no way to define project interdepenencies.

**Comment by mbodmer** [comment]
What about CMake Superbuilds as toplevel build dependency mgmt?
- https://blog.kitware.com/cmake-superbuilds-git-submodules/
- https://cmake.org/cmake/help/latest/module/ExternalProject.html

**Comment by andreeis** [comment]
Thank you for the feature idea. We will think whether/how this makes sense for our extension.

**Comment by bzeller** [comment]
> What about CMake Superbuilds as toplevel build dependency mgmt?
> 
>     * https://blog.kitware.com/cmake-superbuilds-git-submodules/
> 
>     * https://cmake.org/cmake/help/latest/module/ExternalProject.html

I know about ExternalProject but found its more a workaround than a real solution. 
A good example for this type of feature is the QtCreator IDE that makes using multiple cmake projects with inter dependencies in the same workspace pretty easy to use.

**Comment by gcampbell-msft** [comment]
@bzeller I don't believe that this is something that the extension should do, this sounds like it is more at the project setup level, which would be defined in the CMake project itself. 

I'm going to close this as not planned, but please create a new issue if this is something that is still affecting you.

**Comment by bzeller** [comment]
@gcampbell-msft Sometimes one has to work with projects where the CMake files are already there and are not aware of being built a subproject and the project maintainers also do not care about them being buildable as subprojects. I can work around it , still would've been a nice addition.  Thanks for the update though !
