### ISSUE TITLE
Support CUDA language

### ISSUE THREAD

**Issue by Synxis** [microsoft/vscode-cmake-tools#1428]
### Brief Issue Summary

I have a project that contains some CUDA source files (`*.cu`). I use CMake 3.18, and when configuring the project, I get spurious messages about the c++ standard. Please note that building still works as expected, it is just an issue of cluttered output.

### Apparent Behavior:

Log from CMake (in the Output window), when configuring:

    ...
    [cmake] -- Build files have been written to: /home/...
    [cpptools] Unknown language: -std=c++14
    [cpptools] Unknown language: -std=c++14
    [cpptools] Unknown language: -std=c++14
    [cpptools] Unknown language: -std=c++14
    [cpptools] Unknown language: -std=c++14

Basically, one `[cpptools] Unknown language: -std=c++14` for each CUDA source file.

### Expected:

Configuring CMake should *not* output `[cpptools] Unknown language: -std=c++14`, and especially not once for each source file.

### Platform and Versions

- **Operating System**: Ubuntu 18.04
- **CMake Version**: 3.18.2
- **VSCode Version**: 1.48.2
- **CMake Tools Extension Version**: 1.4.1
- **Compiler/Toolchain**: Clang 10 (*not relevant*)

### Other Notes/Information

I tracked this log to `cpptools.ts`, line 193:

https://github.com/microsoft/vscode-cmake-tools/blob/1def55f2ad3d866a57cfdee257b721911736a987/src/cpptools.ts#L193

Indeed, the code checks for `lang` being `CXX`, `OBJCXX`, `C`, `OBJC`, `undefined` **but not `CUDA`**, which I imagine is the source of the problem.

**Comment by bobbrow** [comment]
Thank you for your feature idea. We may not be able to implement it immediately, but we will track the community reactions to determine where this might fit into our backlog.

**Comment by Synxis** [comment]
@bobbrow Thanks for the answer !

I'm OK with no real support for CUDA until you have more demand for it. **In the mean time, can you just change the error message to either be less annoying, or to disable it completely ?**

This is the current concerned code, around line 193 in `cpptools.ts`: https://github.com/microsoft/vscode-cmake-tools/blob/c398e0b5acfe0b006d0eef94e882686165c6c690/src/cpptools.ts#L166-L195

Please change line 168 from

    if (lang === 'CXX' || lang === 'OBJCXX' ) {

to

    if (lang === 'CXX' || lang === 'OBJCXX' || lang === 'CUDA' ) {

That should get rid of the annoying message (see https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-altering-compiler-linker-behavior-std). I can do a PR if you want.

Thanks !

**Comment by bobbrow** [comment]
If you can do a PR, we'd be happy to review it.  If CUDA supports the same cpp standards as CXX, then that small fix sounds like it should do the trick.

One request to expedite getting the PR approved would be that you provide source to a small CUDA project that we can use to validate the change.  It doesn't have to be substantial.  Just a CMakeLists.txt and a source file or two should be sufficient.

**Comment by Synxis** [comment]
Thanks, I created a PR in #1502. I have a small CUDA project to test it, where do you want me to put it (in the `test` folder, I presume) ?

**Comment by bobbrow** [comment]
You can zip it and attach it to the PR (drag and drop into the comment window), or you can paste the file contents directly into the comment window.  Either way works for us!

**Comment by Synxis** [comment]
Right, I added the test case in a zip in #1502.

Glad to help :)

**Comment by bobbrow** [comment]
We forgot to close this issue when the fix was implemented.
