### ISSUE TITLE
IntelliSense cannot locate includes with clang-cl

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vscode-cmake-tools#1431]
**Type: LanguageService**

**Describe the bug**
- OS and Version: **Windows 10 Pro 2004**
- VS Code Version: **1.48.2**
- C/C++ Extension Version: **0.29.0**
- Other extensions you installed (and if the issue persists after disabling them): **CMake Tools**
- Does this issue involve using SSH remote to run the extension on a remote machine?: **No**

The extension generates a lot of errors "cannot open source file" for includes residing in directories specified with **-imsvc** flag in ```compile_commands.json```, while using the following CMake Kit:
```json
  {
    "name": "My Kit",
    "keep": true,
    "compilers": {
      "C": "C:\\LLVM\\bin\\clang-cl.exe",
      "CXX": "C:\\LLVM\\bin\\clang-cl.exe"
    },
    "visualStudio": "016af09d",
    "visualStudioArchitecture": "x86"
  }
```
However directories of all the unlocatable headers are present in "browsePath" reported by ```C/C++: Log Diagnostics``` command. Additionally the debug log contains "Processing folder (recursive)" entries for said directories, but no "tag parsing file" entries for nested headers.

Moreover the extension deduces incorrect Visual Studio installation -- ```016af09d``` on my system references "Visual Studio Build Tools 2017" whereas the extension picks up "Visual Studio Community 2019" (with id ```210b4dc8```). And as a result tag parser scans wrong runtime.

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 10.09.2020, 16:20:26
Version: 0.29.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "${vcpkgRoot}/x64-windows/include"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compilerArgs": [],
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${vcpkgRoot}/x64-windows/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        ### REDACTED ###
    ],
    "standard": "c++17",
    "compilerPath": "c:/llvm/bin/clang-cl.exe",
    "compilerArgs": [
        "/DWIN32",
        "/D_WINDOWS",
        "/W3",
        "/GR",
        "/EHsc",
        "/std:c++17",
        "/GS",
        "/W4",
        "/GF",
        "/Zi",
        "/MD",
        "-fms-compatibility",
        "-fms-compatibility-version=19.14",
        "-fmacro-backtrace-limit=5",
        "-Xclang",
        "-fcxx-exceptions",
        "-Xclang",
        "-fexceptions",
        "-Wconversion",
        "-Wsign-conversion",
        "-Wfloat-conversion",
        "-Wshorten-64-to-32",
        "-Wno-ignored-attributes",
        "-Wno-pragma-pack",
        "-Wno-#pragma-messages",
        "-Wno-ignored-pragma-intrinsic",
        "-Wno-switch",
        "-Wno-missing-field-initializers",
        "-Wno-macro-redefined",
        "-Wno-microsoft-include",
        "-Wno-nonportable-include-path",
        "-Werror-microsoft-exception-spec",
        "/Od",
        "/Ob0",
        "/DEBUG",
        "-fstandalone-debug",
        "-fdebug-macro",
        "-Werror",
        "-Wno-invalid-token-paste"
    ]
}
No active translation units.


```
</details>

**Comment by emptyVoid** [comment]
@sean-mcmanus, sadly your workarond just changes the set of unlocatable headers -- although with `C_Cpp.default.compileCommands` specified IntelliSense is able to locate headers located in directories specified by **-imsvc** flag, if fails to locate Windows SDK and Visual C++ Runtime headers.

<details>
  <summary><strong>Logs</strong></summary>


```
-------- Diagnostics - 11.09.2020, 23:09:20
Version: 0.29.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**",
        "${vcpkgRoot}/x64-windows/include"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "cStandard": "c11",
    "cppStandard": "c++17",
    "intelliSenseMode": "msvc-x64",
    "compileCommands": "${workspaceFolder}/../core-build/compile_commands.json",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "${vcpkgRoot}/x64-windows/include"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\path\to\some\source.cpp ]:
    D:\PATH\TO\SOME\SOURCE.CPP
Translation Unit Configurations:
[ D:\path\to\some\source.cpp ]:
    Process ID: 11984
    Memory Usage: 75 MB
	Includes:
		### PROJECT INCLUDE DIRECTORIES ###
		### DIRECTORIES SPECIFIED WITH -imsvc FLAG ###
    Defines:
        BOOST_ALL_NO_LIB
        BOOST_FILESYSTEM_DEPRECATED
        BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
        BOOST_MPL_LIMIT_LIST_SIZE=30
        BOOST_THREAD_USE_DLL
        BOOST_USE_WINDOWS_H
        CURL_STATICLIB=1
        NDEBUG
        NOGDI
        NOMINMAX
        NTDDI_VERSION=0x06000000
        UNICODE
        USE_CURL
        WIN32
        WIN32_CLANG
        WIN32_LEAN_AND_MEAN
        WINAPP
        WINVER=0x0600
        _CRT_NONSTDC_NO_WARNINGS
        _CRT_SECURE_NO_WARNINGS
        _ENABLE_ATOMIC_ALIGNMENT_FIX
        _HAS_AUTO_PTR_ETC=1
        _ITERATOR_DEBUG_LEVEL=0
        _NDEBUG
        _SCL_SECURE_NO_WARNINGS
        _UNICODE
        _WIN32_WINNT=0x0600
        _WINDOWS
        _WINSOCK_DEPRECATED_NO_WARNINGS
        WIN32
        _WINDOWS
    Standard Version: ms_c++17
    IntelliSense Mode: msvc-x64
Total Memory Usage: 75 MB
```
</details>

**Comment by sean-mcmanus** [comment]
For the compileCommands configuration, it will attempt to use the compiler found in the compile commands, which I guess is the incorrect one. You should be able to overwrite that by setting the compilerPath setting in c_cpp_properties.json to be the path cl.exe in your build tools SKU. Does setting the compilerPath work for you?

**Comment by emptyVoid** [comment]
First of all my `compile_commands.json` contains correct commands, here's a sample:
```json
"command": "C:\\LLVM\\bin\\clang-cl.exe  /nologo -TP -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_DEPRECATED ...
```
And setting `compilerPath` explicitly to `C:\\LLVM\\bin\\clang-cl.exe` doesn't change anything.

**Comment by sean-mcmanus** [comment]
Ah, yeah, our code for selecting the VC install based on the compilerPath only applies for cl.exe and clang-cl.exe. I think the VC directory to use might be chosen by clang-cl.exe itself (not sure)...it's possible there's some clang-cl.exe command line arg that can change the VC directories used, but I'm not sure if we'd react to those. @Colengms might know more.

**Comment by Colengms** [comment]
Clang-cl uses its own logic to choose MSVC and Windows SDK paths to use.  I suspect you may be able to control this by modifying the env paths when clang-cl is invoked.  It would be necessasry to configure the env VS Code is launched with,  as we invoke clang-cl from our own child process to probe it for paths.

**Comment by emptyVoid** [comment]
Can't VS Code deduce environment from the CMake kit?

**Comment by sean-mcmanus** [comment]
Yeah, CMake Tools might be able to handle CMake Kit. We were referring to an attempted workaround of using compileCommands with compilerPath.

**Comment by Neumann-A** [comment]
same issue. Switched `intelliSenseMode` to `clang-x64` to at least get rid of the red squirrels.

**Comment by Colengms** [comment]
(Revisiting this in the process of combing for issues I've been mentioned in that I might have overlooked).

@emptyVoid Is this still an issue for you?  A lot has changed in CMake Tools and cpptools since this issue was opened.

If you're still seeing an issue, could you provide updated logs, including the output of the C/C++ output channel (with `"C_Cpp.loggingLevel": "Debug"` set), and the output of the `C/C++: Log Diagnostics` command?

The existing logs in this issue seem to indicate that the custom configuration provider was not used to configure the file.  Our diagnostic logging has improved, so new logs may have better clues as to what's going on.

**Comment by emptyVoid** [comment]
@Colengms It's not. Though I'm not sure if the issue is truly gone or just being mitigated by some configuration tweaks I've employed to make **IntelliSense** bearable when used with **clang-cl** (although it's still unusable with `"C_Cpp.errorSquiggles": "Enabled"`).

**Comment by Colengms** [comment]
Hi @emptyVoid .  I'll close this for now.  I'm hoping this has been addressed.  If you can find any evidence otherwise, please let us know.  :)
