### ISSUE TITLE
Provide configuration option to hide the initial notification

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-cmake-tools#1435]
```
Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

![screenshot_2020-09-16_00-58-41](https://user-images.githubusercontent.com/41773861/93241620-309f2280-f7b8-11ea-971a-191b7aaa71a6.png)

**Comment by alan-wr** [comment]
"cmake.configureOnOpen": false,
    "cmake.configureOnEdit": false,

**Comment by tjx666** [comment]
> ```
> "cmake.configureOnOpen": false,
> "cmake.configureOnEdit": false,
> ```

It doesn't work.
