### ISSUE TITLE
Max command length cuts off Generator name.

### ISSUE THREAD

**Issue by API-Beast** [microsoft/vscode-cmake-tools#1439]
### Brief Issue Summary

When running CMake Tools to configure there seems to be a max line length, because of which not all parameters get passed correctly. In this example it should pass "Unix Makefiles" as Generator, but because of the limit it only passes "Uni", which is not a valid generator.

### CMake Tools Log

```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.exe" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=C:\msys64\mingw64\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=C:\msys64\mingw64\bin\g++.exe -Hc:/Projects/MyProject -BE:/_ColorTool/build -G Uni
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error: Could not create named generator Uni
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.16.2
- **VSCode Version**: 1.49.0
- **CMake Tools Extension Version**: v1.4.1
- **Compiler/Toolchain**: GCC 10.2.0, MSYS2

**Comment by bobbrow** [comment]
Thank you for reporting this issue.
