### ISSUE TITLE
Hardcoded CMAKE_EXPORT_COMPILE_COMMANDS getting in the way

### ISSUE THREAD

**Issue by treilly-nuodb** [microsoft/vscode-cmake-tools#1440]
### Brief Issue Summary

I had to hack the this extension to turn off CMAKE_EXPORT_COMPILE_COMMANDS.    It needs to be turned off when doing unity builds.  

### Expected:

There should be a way to override the default behavior of hardcoding CMAKE_EXPORT_COMPILE_COMMANDS to true.  Our typical workflow is to run cmake once with it on and then turn it off and run again with unity on.

**Comment by andreeis** [comment]
We almost have CMake Tools 1.6.0 release out the door. Until then, if you want, you can also verify if this problem has been fixed correctly by installing the vsix built here: https://github.com/microsoft/vscode-cmake-tools/actions/runs/557242002#artifacts.
