### ISSUE TITLE
Cross compiling for Android, missing "..../sysroot/usr/include" folder in the generated compile_commands.json

### ISSUE THREAD

**Issue by zrno** [microsoft/vscode-cmake-tools#1448]
Issue Type: <b>Bug</b>

Cross compiling on windows for Android using Android ndk's clang.
Intellisense has problems finding the `#include <jni.h>` because the folder where `jni.h` is located is not in the generated compile_commands.json file. 

Include folder that is missing in compile_commands.json is 
`C:/...toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include`

Relevant lines that are (correctly) inside compile_commands.json:
`--sysroot=C:/.../toolchains/llvm/prebuilt/windows-x86_64/sysroot`
`-IC:/.../toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1`

So `...sysroot/usr/include/c++/v1` is listed as an include folder but not `sysroot/usr/include`

I am not sure that the actual error is inside this extension. It could also be in the C/C++ extension or inside CMAKE itself.

Extension version: 1.4.2
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (12.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by andreeis** [comment]
Thank you for reporting this issue.
Our extension doesn't generate compile_commands.json, it only adds the flag to the command line to tell CMake to generate it.
Can you compare the logs and see if the command line we're generating during the configure step is the same as the command you are using in the terminal?

**Comment by zrno** [comment]
I believe it is connected to this issue https://github.com/microsoft/vscode-cpptools/issues/1575

**Comment by andreeis** [comment]
Upgrade your CppTools extension to latest and let us know if you still see this problem with CMake Tools.
