### ISSUE TITLE
How to set the working directory of cmake/launch(run in terminal) to be "${workspacefolder}" instead of the directory of target?

### ISSUE THREAD

**Issue by uiemUI** [microsoft/vscode-cmake-tools#1450]
How to set the working directory of cmake/launch(run in terminal) to be "${workspacefolder}" instead of the directory of target?

### Platform and Versions

- **Operating System**: <!-- Windows, >
- **CMake Version**: <3.18>
- **VSCode Version**: <1.49.1>
- **CMake Tools Extension Version**: <!v1.4.2>
- **Compiler/Toolchain**: <!-- Visual C++ 2019, >

**Comment by bobbrow** [comment]
Please see #1395 for a way to work around this change until we publish another update.
