### ISSUE TITLE
The ability to open build folder in system explorer

### ISSUE THREAD

**Issue by Shatur** [microsoft/vscode-cmake-tools#1451]
**Is your feature request related to a problem? Please describe**
When working with a project, I often need to open the open build folder in system explorer. Since CMake allow to have different build folders (Release, Debug, different compiler, etc.), it would be convenient to be able to open the current build folder via command palette.

**Describe the solution you'd like**
An action for command palette to open current build folder in explorer.

**Comment by bobbrow** [comment]
Thank you for your feature idea. We may not be able to implement it immediately, but we will track the community reactions to determine where this might fit into our backlog.  If anyone from the community is interested in helping out, we would also accept a PR for this feature.

**Comment by gcampbell-msft** [comment]
This was solved with #3620, closing.
