### ISSUE TITLE
Documentation for skipConfigureIfCachePresent

### ISSUE THREAD

**Issue by SandNet** [microsoft/vscode-cmake-tools#1455]
### Brief Issue Summary

Documentation for `skipConfigureIfCachePresent` intoduced in this PR: https://github.com/microsoft/vscode-cmake-tools/pull/1212 is missing from both https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html and https://github.com/microsoft/vscode-cmake-tools.

### Expected:

1. Visit documentation page
2. Find documentation about the `skipConfigureIfCachePresent` that explains what the command does and how to use it.

### Apparent Behavior:

1. Visit documentation page
2. No entry explaining `skipConfigureIfCachePresent`

**Comment by bobbrow** [comment]
@andreeis we should make sure the documentation is added for this.  If anyone in the community would like to help, we would also accept a PR.

**Comment by bam80** [comment]
Still not documented?

**Comment by benmcmorran** [comment]
As part of this documentation update, we should also see if we can add a deprecation banner to the `vector-of-bool` site.

**Comment by gcampbell-msft** [comment]
This is addressed in #3135, which should be out in pre-release soon!
