### ISSUE TITLE
cmake.configureSettings does not distinguish PATH and STRING

### ISSUE THREAD

**Issue by cdowen** [microsoft/vscode-cmake-tools#1457]
### Brief Issue Summary
CMake tool treats "cmake.configureSettings" as strings and append ":STRING" in generated commandlines. This causes passing path in the command line impossible.

### Expected:
1. Set a path in cmake.configureSettings to tell CMake where to look for a particular library;
2. Generated CMake command should be like "-DXXX_PATH=/aaa/bbb/..." and CMake finds the library.

### Apparent Behavior:
Generated CMake command be like "-DXXX_PATH:STRING=/aaa/bbb/..." and CMake tells it cannot find the library.

### CMake Tools Log
```
[proc] Executing command: /home/lz/.local/bin/cmake --no-warn-unused-cli -DOPENSSL_ROOT_DIR:STRING=/home/lz/.local/lib/ -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H/home/lz/workspace/trojan -B/home/lz/workspace/trojan/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The CXX compiler identification is GNU 5.5.0
[cmake] -- Check for working CXX compiler: /usr/bin/c++
[cmake] -- Check for working CXX compiler: /usr/bin/c++ -- works
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Looking for C++ include pthread.h
[cmake] -- Looking for C++ include pthread.h - found
[cmake] -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
[cmake] -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
[cmake] -- Check if compiler accepts -pthread
[cmake] -- Check if compiler accepts -pthread - yes
[cmake] -- Found Threads: TRUE  
[cmake] -- Found Boost: /home/lz/.local/lib/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.66.0") found components: system program_options 
[cmake] CMake Error at /home/lz/.local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
[cmake]   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
[cmake]   system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2g", but
[cmake]   required is at least "1.1.0" (found /home/lz/.local/lib/libcrypto.so)
[cmake] Call Stack (most recent call first):
[cmake]   /home/lz/.local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:391 (_FPHSA_FAILURE_MESSAGE)
[cmake]   /home/lz/.local/share/cmake-3.16/Modules/FindOpenSSL.cmake:449 (find_package_handle_standard_args)
[cmake]   CMakeLists.txt:46 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

### Platform and Versions

- **Operating System**: Windows as client, ubuntu as remote
- **CMake Version**: 3.16.1
- **VSCode Version**: 1.49.2
- **CMake Tools Extension Version**: 1.4.2
- **Compiler/Toolchain**: GCC 5.5.0

**Comment by bobbrow** [comment]
This may be a limitation of the map-style syntax of `cmake.configureSettings`.  If you use `cmake.configureArgs`, you should be able to pass in the switches exactly as you like.

**Comment by ishipachev** [comment]
@bobbrow 
But the documentation explicitly says that you SHOULDN'T pass -D flags with cmake.configureArgs. Like NEVER, NEVER.
Links:
[Links:](url)
[Some CMake doc](https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html)
[Official doc:](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md#variable-substitution)

> cmake.configureArgs -> Arguments to CMake that will be passed during the configure process. Prefer to use cmake.configureSettings or CMake variants.Do not pass -D arguments using this setting.

To be honest, after reading documentation for two hours I'm still struggle to understand how should I pass CMake flags with -D, for an example I have such cmake command to run which is generated by other python script:

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/some_path_2/colmap_build/__install__ -DCMAKE_INSTALL_PREFIX=/some_path_1/__install__ -DBOOST_ROOT=/some_path_3/software/Boost/1.67.0-fosscuda-2018b -DBoost_NO_BOOST_CMAKE=TRUE -DCUDA_ENABLED=ON -DCUDA_ARCHS=Auto -DOPENGL_ENABLED=OFF -DTESTS_ENABLED=OFF /some_path_4/colmap`

So I would like to pass it somehow to configuration settings. But I have no idea what to use. Some flags have a special fields for them, like CMAKE_INSTALL_PREFIX, some of them are not. I've tried to understand the connection between
cmake.configureSettings and cmake.configureArgs, but this issue with comments and its contradiction with documentation confused me completely.

May I ask you for a help here? What is the meaning behind those flags and how should be process those -D flags?

**Comment by bobbrow** [comment]
There's actually no technical reason prohibiting you from passing -D with configureArgs.  I believe that warning was written by vector-of-bool when he started this project and we haven't spent much time in the area yet. Based on what I see in the code I think it was to avoid conflicts between some of the "special" settings you mentioned.  These conflicts are resolved if you use configureSettings, but not when you use configureArgs.  I suspect it is easier to advise not to use configureArgs for `-D` arguments than to explain all of the potential conflicts.

I think a more correct warning would be not to use configureArgs to set the following properties:
```
CMAKE_EXPORT_COMPILE_COMMANDS
CMAKE_BUILD_TYPE
CMAKE_INSTALL_PREFIX
CMAKE_[LANGUAGE]_COMPILER
CMAKE_TOOLCHAIN_FILE
BUILD_SHARED_LIBS
```

**Comment by bobbrow** [comment]
Starting with version 1.13.28 tomorrow `cmake.configureSettings` will support objects of type: `{ "type": "PATH", "value": "/usr/bin/foo" }` if you need to set a specific value type.  You can also set the type to "" if you don't want any type information appended for your variable.
