### ISSUE TITLE
Allow selection of VS installations via different means than instance ID

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vscode-cmake-tools#1458]
### Brief Issue Summary

Problem: Want to share `cmake-kits.json` across pcs (workspace local).

example:
```
    {
        "name": "LLVM_VS2019_x64",
        "visualStudio": "VisualStudio.16.0",
        "visualStudioArchitecture": "amd64",
        "compilers": {
            "C": "${env:PROGRAMFILES}\\LLVM\\bin\\clang-cl.exe",
            "CXX": "${env:PROGRAMFILES}\\LLVM\\bin\\clang-cl.exe"
        },
        "preferredGenerator": {
            "name": "Ninja"
        }
    },
```
### Apparent Behavior:

Problem: selection of vsvars depend on installation order of Preview/Release (or to be more exact order vswhere displays them)

### Expected:

I can define the selection of Preview/Release without resorting to use PC bounded InstanceIDs which makes sharing kits impossible. 

### Solution:

please provide other means to select the correct VS instance. (e.g. by allowing the user to supply minor/patch versions. )

**Comment by bobbrow** [comment]
Thank you for your feature idea.  We're not immediately sure whether this is something we will implement in the near future but we will track the community reactions to the idea to determine where this might fit into our backlog.
