### ISSUE TITLE
Providing VS160COMNTOOLS in cmake-kits.json is overridden 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vscode-cmake-tools#1459]
### Brief Issue Summary

related to #1458 i tried providing environment variable `VS160COMNTOOLS` for cmake to select the right VS instance. E.g. by supplying:
```
"environmentVariables": {
            "VS160COMNTOOLS" : "${env:VS2019INSTALLDIR}/Common7/Tools}"
        },
```
in the kit. 
The problem is if the extension simply seems to override that value which its own found value for the kit installation. 

### Expected:

If `VS160COMNTOOLS` is explicitly given in a kit don't try to be clever unless `"visualStudio"` was given with an `instanceID`.

**Comment by bobbrow** [comment]
This might be possible today.  Tagging @andreeis 

If you create a custom kit without the 'visualStudio' properties, but set the compilers to the locations of clang that you want to use, you could potentially use the `environmentSetupScript` to run the version of vcvarsall.cmd that applies for you.

**Comment by andreeis** [comment]
I realize now that we don't have a way to set arguments for this script.
If the user wraps vcvarsall in something else which would include the exact parameters needed (architecture specific) then this works.
