### ISSUE TITLE
Changes of default CWD folder break targets run.

### ISSUE THREAD

**Issue by grapland0** [microsoft/vscode-cmake-tools#1460]
The change is introduced from #1395. Could we consider to revert this change?

This change silently breaks the feature behind launch/debug status bar shortcut, if the target uses some data with relative path to the work folder (e.g. data of unit tests). And it is not easy to find the root cause and fix without digging into that issue thread.

**Comment by bobbrow** [comment]
We can understand that it may be unclear at times how to override the defaults for our quick debug action and we're sorry that this caused you trouble.  We won't be reverting this change as we feel that ${workspaceFolder} is less likely to be the correct location, but it is overridable by using the `cmake.debugConfig` setting.

We should update the [documentation here](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md) to explicitly mention the `cmake.debugConfig` setting.

**Comment by xgdgsc** [comment]
This change feels stupid to me. How many people needs loading plugins from build folders? How many people needs loading config from workspaceFolder?

**Comment by grapland0** [comment]
let me close this to reduce backlog. I have fixed my launch settings, but still think this feature should be reconsidered.
