### ISSUE TITLE
colorization, auto completion and so on

### ISSUE THREAD

**Issue by KaungZawHtet** [microsoft/vscode-cmake-tools#1465]
Now I am using the extension, https://github.com/twxs/vs.language.cmake , for those features but sadly the proj look inactive or dead. Can those features be added into this extension or fork it or cooperate with that proj's developer or something ?

**Comment by bobbrow** [comment]
Thank you for your feature request.  We have another issue open tracking this request at issue #93 so we will close this as a duplicate.
