### ISSUE TITLE
Extension doesn't detect qt header files

### ISSUE THREAD

**Issue by krillxox** [microsoft/vscode-cmake-tools#1466]
**Type: LanguageService**

OS: 
**Describe the bug**
- OS and Version: Linux x64 5.8.8-arch1-1
- VS Code Version: 1.49.0
- C/C++ Extension Version:  	1.0.0

With new version of MS C/C++ extension it has stopped detecting qt header files, even though I've added it's path in include path. It gives red lines over that included header file and says path to header file not found.

**Expected behavior**

It should detect qt header files and intellisense should work.
![Screenshot_20200917_113509](https://user-images.githubusercontent.com/55268360/93426583-f62da680-f8d9-11ea-81b7-42ec84df6337.png)

<details>
  <summary><strong>Logs</strong></summary>

```
-------- Diagnostics - 9/17/2020, 11:32:10 AM
Version: 1.0.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "/home/krillxox/Qt/5.15.0/gcc_64/include",
        "/home/krillxox/Qt/5.15.0/gcc_64/lib",
        "/home/krillxox/Qt/5.15.0/wasm_32/include",
        "/home/krillxox/Qt/5.15.0/wasm_32/include",
        "/usr/include",
        "${workspaceFolder}/**",
        "/usr/include/qt/QtGui",
        "/usr/include/qt/QtWidgets",
        "/usr/include/qt/QtCore"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "c11",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "clang-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerArgs": [],
    "browse": {
        "path": [
            "/home/krillxox/Qt/5.15.0/gcc_64/include",
            "/home/krillxox/Qt/5.15.0/gcc_64/lib",
            "/home/krillxox/Qt/5.15.0/wasm_32/include",
            "/home/krillxox/Qt/5.15.0/wasm_32/include",
            "/usr/include",
            "${workspaceFolder}/**",
            "/usr/include/qt/QtGui",
            "/usr/include/qt/QtWidgets",
            "/usr/include/qt/QtCore"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/krillxox/Documents/build",
        "/home/krillxox/Documents/Qt Project/Quick/test/untitled",
        "/home/krillxox/Documents/build/untitled_autogen/include",
        "/usr/include/qt",
        "/usr/include/qt/QtWidgets",
        "/usr/include/qt/QtGui",
        "/usr/include/qt/QtCore",
        "/usr/lib/qt/mkspecs/linux-g++",
        "/home/krillxox/Documents/Qt Project/Quick/test/untitled/Documents/build/untitled_autogen",
        "/home/krillxox/Documents/Qt Project/Quick/test/untitled/Documents/build/CMakeFiles"
    ],
    "standard": "c++17",
    "compilerPath": "/usr/bin/c++",
    "compilerArgs": []
}
Translation Unit Mappings:
[ /home/krillxox/Documents/Qt Project/Quick/Calculator/Calculator2/mainwindow.cpp ]:
    /home/krillxox/Documents/Qt Project/Quick/Calculator/Calculator2/mainwindow.cpp
Translation Unit Configurations:
[ /home/krillxox/Documents/Qt Project/Quick/Calculator/Calculator2/mainwindow.cpp ]:
    Process ID: 3652
    Memory Usage: 59 MB
    Compiler Path: /usr/bin/c++
    Includes:
        /usr/include/c++/10.2.0
        /usr/include/c++/10.2.0/x86_64-pc-linux-gnu
        /usr/include/c++/10.2.0/backward
        /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include
        /usr/local/include
        /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: gcc-x64
    Other Flags:
        --g++
        --gnu_version=100200
Total Memory Usage: 59 MB

------- Workspace parsing diagnostics -------
Number of folders and files enumerated: 28104
Number of files discovered (not excluded): 26527
```
</details>

**Screenshots**

Given in attachment.
![Screenshot_20200917_113509](https://user-images.githubusercontent.com/55268360/93426839-676d5980-f8da-11ea-9bf2-be5c1dbfff76.png)

**Comment by sean-mcmanus** [comment]
It looks like the book1 project isn't setup to build with CMake or there's a CMake Tools configuration bug. Are you able to build mainwindow.cpp with CMake?

**Comment by krillxox** [comment]
Yes, I'm able to build book1 project by cmake through terminal. I ran vscode today after update it stopped showing build option for cmake and icon at the left is also gone.
![Screenshot_20201013_204011](https://user-images.githubusercontent.com/55268360/95879909-83a6ce00-0d94-11eb-97ab-1c387a858bf4.png)

**Comment by krillxox** [comment]
Not any error but I get this in output
```
[variant] Loaded new set of variants
[kit] Successfully loaded 5 kits from /home/krillxox/.local/share/CMakeTools/cmake-tools-kits.json
[expand] Invalid variable reference ${fileDirname} in string: ${fileDirname}/
[rollbar] "sourceDirectory" is not a directory {"sourceDirectory":"${fileDirname}"}
[cmakefileapi-parser] Code model version (2.1) of cmake-file-api is unexpected. Expecting (2.0). IntelliSense configuration may be incorrect.
[cmakefileapi-parser] Code model version (2.1) of cmake-file-api is unexpected. Expecting (2.0). IntelliSense configuration may be incorrect.
[expand] Invalid variable reference ${fileDirname} in string: ${fileDirname}/
[rollbar] "sourceDirectory" is not a directory {"sourceDirectory":"${fileDirname}"}
```

**Comment by bobbrow** [comment]
Did you set `cmake.sourceDirectory` to `${fileDirname}`?  That's not a valid value.  You can use something like `${workspaceFolder}` if that's the folder where CMakeLists.txt resides.  It appears that the extension failed to find your CMakeLists.txt and as a result never enabled the full set of features (like the icons).

**Comment by krillxox** [comment]
Ok, now I got it. If I set project folder as workspace then only it works. The reason for not detecting header files is it asks to make cmake tools as configuration provider for C/C++ extension if I allow it then it isn't able to detect those header files.

**Comment by christian780** [comment]
> Yes, I'm able to build book1 project by cmake through terminal. I ran vscode today after update it stopped showing build option for cmake and icon at the left is also gone. ![Screenshot_20201013_204011](https://user-images.githubusercontent.com/55268360/95879909-83a6ce00-0d94-11eb-97ab-1c387a858bf4.png)

Bro ve got similar issues..how do I update my vscode so it could detect the qt headers,.

**Comment by krillxox** [comment]
> > Yes, I'm able to build book1 project by cmake through terminal. I ran vscode today after update it stopped showing build option for cmake and icon at the left is also gone. ![Screenshot_20201013_204011](https://user-images.githubusercontent.com/55268360/95879909-83a6ce00-0d94-11eb-97ab-1c387a858bf4.png)
> 
> Bro ve got similar issues..how do I update my vscode so it could detect the qt headers,.

open only parent book1 folder in workspace and if it still dont detect change compiler path to /usr/bin/g++
