### ISSUE TITLE
Provide configuration information for nearby files 

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#1479]
CMake Tools currently only provides configurations to cpptools for files that are explicitly mentioned in the CMakeLists.txt.  If a project is currently being refactored, or new files are being added, but the CMakeLists.txt hasn't been updated yet, you won't get good IntelliSense for those files until the CMakeLists.txt has been updated and the "configure" command has run.

Since most source files residing in a folder are expected to compile with a similar configuration, the feature proposal here is that we could provide a configuration for source files not explicitly listed in CMakeLists.txt based on the configuration of files already in that folder.

**Comment by lygstate** [comment]
Also about same header that include by different c source have different meanings


When we use CTRL+mouse to navigate into a header file, that header file should use the compiler flags of that file.

Because header file may not appear in Cmakefilelists.txt, this applies to other build system.

**Comment by bobbrow** [comment]
> Also about same header that include by different c source have different meanings

That scenario is a challenge because cpptools does not support opening a header with multiple different configs yet.

> When we use CTRL+mouse to navigate into a header file, that header file should use the compiler flags of that file.

When you CTRL+click to navigate to the header it will already use the compiler flags of the "includer." That just how cpptools works.

> Because header file may not appear in Cmakefilelists.txt, this applies to other build system.

Header files can be added to CMakeLists.txt.  This was something that @vector-of-bool advocated too.
