### ISSUE TITLE
Compile errors in status.ts using ts 4.0+

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cmake-tools#1480]
Since classes overloading Button is defining members such as 'icon' as property, but Button defines them as accessor, there would be compile error when suing ts 4.0+.

This is not very urgent since cmake tools is still using 3.7. However, 4.0+ could be selected in VS Code and F5 uses this setting by default:
![image](https://user-images.githubusercontent.com/44103947/95630660-0fd49080-0a37-11eb-8072-5cbc93ab3ff0.png)

Would still be nice to change these members anyway just for coding style.

**Comment by bobbrow** [comment]
Basically, move the initialization into a constructor in the child classes.

E.g: 
![image](https://user-images.githubusercontent.com/12818240/96522038-7459d180-1227-11eb-8f9d-421a96ca1842.png)
