### ISSUE TITLE
Allow setting additional command line arguments in cmake-tools-kits.json

### ISSUE THREAD

**Issue by mpusz** [microsoft/vscode-cmake-tools#1486]
I am trying to use Clang with libc++ rather than libstdc++ via CMake. The perfect solution would be to have "args" parameter in cmake-tools-kits.json so I could setup:

```text
  {
    "name": "Clang 10.0.0",
    "compilers": {
      "C": "/bin/clang-10",
      "CXX": "/bin/clang++-10"
    },
    "args": "-stdlib=libstdc++"
  },
  {
    "name": "Clang 10.0.0 libc++",
    "compilers": {
      "C": "/bin/clang-10",
      "CXX": "/bin/clang++-10"
    },
    "args": "-stdlib=libc++"
  },
```

Is there any other easy way to do it currently?

**Comment by bobbrow** [comment]
This sounds like something you might want to create [Toolchains](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html) for.  You can use the `toolchainFile` property to point to a toolchain file that configures your compilers for you (and remove the `compilers` property).

Another option is to try the `cmakeSettings` property.  Any argument you pass to cmake via the command line should be settable here.  I haven't used the CLI to set compiler flags before, but it might be possible.  I think the preferred method is to instead modify the CMakeLists.txt to support the addition of the flag based on some control variable you might create (which could be passed in via a toolchain or the `cmakeSettings` property).

**Comment by mpusz** [comment]
Thanks for your answer. I am using `toolchainFile` already to setup warnings in CXX_FLAGS that should only be used during package development. By this, I mean that compilation warnings should not be embedded inside the library CMake file and should not be enforced for its customers.

As I wrote above I already use toolchain files for warnings and I would need another orthogonal toolchain set for setting a library. Unfortunately, it is not easy to externally stack toolchain files (i.e. one for standard library + another for warnings). In other words, I do not want to include warnings script from libc++ toolchain script. And I cannot provide a list of toolchain files to CMake...

>  I think the preferred method is to instead modify the CMakeLists.txt to support the addition of the flag

I do not agree. `CMakeLists.txt` file should only describe how to build a project and describe its constraints. It should not embed any additional logic (compiler warnings, static analysis steps, libc++ vs libstdc++ vs libstdc++11, etc.). Those are development environment properties rather than project-specific information. Thus it should not appear in the `CMakeLists.txt` file. You could also name them "development kits" ;-) This is why I am looking for a way to provide such information in CMake kit description (it would be trivial in `tasks.json` but with CMake we do not have easy access to it).

**Comment by bobbrow** [comment]
What does your `cmake` command look like?  (In other words... how do you switch between libraries when you're not using this extension?)  Perhaps this will help me make a better recommendation if you disagree with updating your CMakeLists.txt.

**Comment by mpusz** [comment]
I am not using cmake command line at all outside of VSCode. If I have to build a project from a command line I use Conan that handles all of this by itself.

**Comment by bobbrow** [comment]
If you can figure out the command line that Conan generates, then we might be able to cook up a solution that will work for you. Unfortunately, our team doesn't have much experience with Conan.
