### ISSUE TITLE
"Compile Active File" does not work with an empty define

### ISSUE THREAD

**Issue by dslijepcevic** [microsoft/vscode-cmake-tools#1493]
### Brief Issue Summary

It looks like "Compile Active File" incorrectly parses empty defines from `compile_commands.json`. Instead of passing `-DMY_DEFINE=` to the compiler, it passes an empty argument.

`CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.8 FATAL_ERROR)
project(test C)
add_executable(test test.c)
target_compile_definitions(test PUBLIC MY_DEFINE=)
```

`test.c`:
```c
int main()
{
    return 0;
}
```

`build/compile_commands.json`:
```json
[
{
  "directory": "/proj/test/build",
  "command": "/usr/bin/cc -DMY_DEFINE=\"\"  -g   -o CMakeFiles/test.dir/test.c.o   -c /proj/test/test.c",
  "file": "/proj/test/test.c"
}
]
```

"Compile Active File" output:
```sh
/usr/bin/cc "" -g -o CMakeFiles/test.dir/test.c.o -c /proj/test/test.c
/proj/test/build$ /usr/bin/cc "" -g -o CMakeFiles/test.dir/test.c.o -c /proj/test/test.c
cc: error: : No such file or directory
```

**Comment by andreeis** [comment]
Thank you for reporting this issue. We'll let you know if we need more info to investigate it.

**Comment by elahehrashedi** [comment]
"Compile Active File" does not work with any string define.
