### ISSUE TITLE
config generators issue

### ISSUE THREAD

**Issue by ferraja** [microsoft/vscode-cmake-tools#1501]
### Brief Issue Summary

It doesn't work to config Cmake: Generator
### Expected:

1. set `Cmake: Generator` to `MinGW Makefiles`
2. execute `cmake ..` in the build directory
3. generate `Makefile`  with MinGW Makefiles

### Apparent Behavior:

1. set `Cmake: Generator` to `MinGW Makefiles`
2. execute `cmake ..` in the build directory
3. instead of building with MinGW Makefiles, it builds with Visual Studio 16 2019 which is the default generators on the platform

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.27.29112.0
-- The CXX compiler identification is MSVC 19.27.29112.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.17.5
- **VSCode Version**: 1.50
- **CMake Tools Extension Version**: 1.4.2
- **Compiler/Toolchain**: MinGW-W64 8.1.0

### Other Notes/Information

I can get the correct execution by `cmake .. -G"MinGW Makefiles" in the `build` directory` and it succeeds.
Also, if I save the `CMakeLists.txt`, it will config automatically, which build via `MinGW Makefiles`, too.
I have confirmed that `Visual Studio 16 2019` is the default generators.
`cmake.preferredGenerators` won't correct it, either.

**Comment by bobbrow** [comment]
Which "Kit" did you select?  It would seem that either a Kit wasn't selected and we defaulted to Visual Studio, or that a MinGW Kit was not selected.

You can check the status bar to see.  It will be next to the "tools" icon:
![image](https://user-images.githubusercontent.com/12818240/96902626-9c287f80-1449-11eb-93ef-576a2c36c53b.png)

**Comment by culturecircle** [comment]
> Which "Kit" did you select? It would seem that either a Kit wasn't selected and we defaulted to Visual Studio, or that a MinGW Kit was not selected.
> 
> You can check the status bar to see. It will be next to the "tools" icon:
> ![image](https://user-images.githubusercontent.com/12818240/96902626-9c287f80-1449-11eb-93ef-576a2c36c53b.png)

@bobbrow 
I fogot to post that information.
Yes, I did select `GCC 8.1.0` as the kit. Actually, my selection on kit seems not work. No matter what I select, it just uses the default generator on this platform.
![image](https://user-images.githubusercontent.com/57833205/96946703-b2027700-1513-11eb-9d61-5c77368a80fb.png)

**Comment by bobbrow** [comment]
Is it possible you are hitting #1127?  Could you try running the "Reload Window" command and see if that fixes it?

**Comment by culturecircle** [comment]
> Is it possible you are hitting #1127? Could you try running the "Reload Window" command and see if that fixes it?

It doesn't work, but I found something else.

I have mentioned before that when I press `Ctrl + S` to save the `CMakeLists.txt`, it will work correctly, which gives a `Makefile` via `MinGW Makefiles` generator. In this case, I have complete and absolutely correct `build` directory. If now I enter `build` directory and execute `cmake ..`, it will run `MinGW Makefiles` generator, which is I expect. However, if I delete all files in `build` directory that generated by the `Ctrl + S` operator and then execute `cmake ..` to generate manually, it run the default generator `Visual Studio 16 2019` again.

**Comment by andreeis** [comment]
@culturecircle , do you have cmake.configureOnOpen set to false? Is any configure happening after you reload your project in VSCode? I am asking because the configure that is triggered automatically by your edits of CMakeLists.txt seems to work.

**Comment by culturecircle** [comment]
> @culturecircle , do you have cmake.configureOnOpen set to false? Is any configure happening after you reload your project in VSCode? I am asking because the configure that is triggered automatically by your edits of CMakeLists.txt seems to work.

`cmake.configureOnOpen` is set to `true`, so is `Configure On Open`. But I couldn't figure out why will this affect the issue?

**Comment by andreeis** [comment]
I thought that maybe the fact that you still don't have the correct generator working after a reload is that you didn't configure. You mentioned that a configure triggered by CMakeLists.txt edit did help, the configure that is automatically run after opening a project is the same, so I wondered what could be different between editing and saving the CMakeLists.txt and reloading your project in VSCode. We'll think some more and of course we'll figure out this.

**Comment by culturecircle** [comment]
@andreeis 
You're right. 
The auto-work by saving CMakeLists.txt or opening the project is driven by these two interface `Configure on open` and `Configure On Edit`. However, I couldn't look through it behind the interfaces, neither do `generator` settings, which is far away from how it works.
