### ISSUE TITLE
Unable to open source file outside workspaceFolder from project outline

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#1504]
hi @bobbrow, I am using 1.4.2 CMake Tools on macOS, but the issue is still there:
```
Unable to open 'main.cpp': Unable to read file '/Users/admin/Projects/A/console/Users/admin/Projects/A/src/main.cpp' (Error: Unable to resolve non-existing file '/Users/admin/Projects/A/console/Users/admin/Projects/A/src/main.cpp').
```

The project structure looks like: 
```
A $ tree -L 2 .
.
├── README.md
├── console
│   ├── build
│   └── CMakeLists.txt
├── src
│   └── main.cpp
└── third-party
```

with this simple setup:

```
set(MAIN_SOURCE_DIR "../src")

file(GLOB_RECURSE CPP_HEADERS ${MAIN_SOURCE_DIR}/*.hpp)
file(GLOB_RECURSE CPP_SOURCES ${MAIN_SOURCE_DIR}/*.cpp)

add_executable(
    A
    ${CPP_HEADERS}
    ${CPP_SOURCES}
)
```

As you can see, the error reports a path with `<CMakeLists Dir>+<Absolute Source Path>`, which is duplicate and totally wrong.
```
'/Users/admin/Projects/A/console/Users/admin/Projects/A/src/main.cpp'
```

**Platform and Versions**
Operating System:macOS
CMake Version:3.18.4
VSCode Version:1.50.1
CMake Tools Extension Version: 1.4.2
Compiler/Toolchain: Clang 11

_Originally posted by @mutoo in https://github.com/microsoft/vscode-cmake-tools/issues/1254#issuecomment-713215418_

**Comment by bobbrow** [comment]
@mutoo, can you provide a little more information for us?  Which folder in the structure you shared is the `${workspaceFolder}`?  I tried opening both `console` and `src` after replicating your folder structure, but am unable to repro on Windows.  I'll try again on Linux (I don't have a mac to try right now).

**Comment by mutoo** [comment]
@bobbrow, the `${workspaceFolder}` is the **console** `/Users/admin/Projects/A/console`.

**Comment by tvb377** [comment]
Me too:
I have a folder structure where two source folders are on the same level.
One of them contains the CMakeLists.txt and adds sources also from its sibling.

CMake Tools somehow understands that some source files are located together in another folder, and in the explorer subsumes them in a separate tree entry underneath the target.
But already in the explorer a wrong path to the folder appears: apparently relative to the build directory, but after ..\.. "\Users\name" gets prepended.
When I try to open a file of the library dir (the one not containing CMakeLists.txt), I get the message:
Unable to open 'byte_to_hex.c': Unable to read file 'c:\Users\name\Users\name\srclocal\avrlib\byte_to_hex.c' (Error: Unable to resolve non-existing file 'c:\Users\name\Users\name\srclocal\avrlib\byte_to_hex.c').
![image](https://user-images.githubusercontent.com/1702187/97300785-32e4aa00-1857-11eb-9052-0dcc02cf32d9.png)

Also, the file names communicated to intellisense seem to be wrong.

As you can see, this is on Windows.

**Comment by k0pernicus** [comment]
Hi everyone,
I have the exact same issue than @bobbrow.

If I don't make any mistake, we are following a tutorial to create a sort of graphic engine on multiple platforms, using C++ and SDL: https://marcelbraghetto.github.io/a-simple-triangle/2019/03/02/part-02/

In this part, the author shows how to configure it's own VSCode instance using Cmake and Cmake Tools (vector-of-bool version, not yet microsoft), but following the steps VSCode + extensions does not follow the rules and create another full path inside the current workspace folder.

I expect that the configuration of the extensions change, or something we missed, because using the scripts on the console directly works, check the code directly and build the binary.

**Comment by spaxt** [comment]
I also have this problem. I'm also using SDL like @k0pernicus, but I'm not following a tutorial (i.e. issue produced organically). For example, I might have a file structure like:
```
C:\Users\spaxt\
├── SDL2-2.0.12\
│   └── include\SDL.h
├── myProject\
    ├── main.cpp (includes SDL.h)
    └── CMakeLists.txt 
```
The add_library/add_executable call in CMakeLists could be using a relative or absolute path, and I still get the follow situation:
(Ember is the name of my project)
![image](https://user-images.githubusercontent.com/15821983/98446021-0ba89b00-20e9-11eb-9ba8-3db86a116adf.png)
Ok, that doesn't look bad, but the part of the path you can't see is "C:\Users", so the whole path resolves as:
C:\Users\Users\spaxt\SDL2-2.0.12\include\SDL.h

Obviously C:\Users\Users doesn't exist:
![image](https://user-images.githubusercontent.com/15821983/98446128-7c4fb780-20e9-11eb-9882-33fffc424908.png)

### Setup:
- Visual Studio Code 1.50.1
- CMake (twxs) version 0.0.17
- CMake Tools (Microsoft) version 1.5.1
- Other Extensions:
![image](https://user-images.githubusercontent.com/15821983/98446196-d781aa00-20e9-11eb-809d-78fa7fcfd5e4.png)

**Comment by andreeis** [comment]
Fixed by https://github.com/microsoft/vscode-cmake-tools/pull/1674

**Comment by Dyronix** [comment]
Would it be possible to receive a patch for this fix, it is blocking our entire workflow ... We have to switch IDE in order to edit our source files and switch back to run the CMake configuration. 

A workaround would also do the trick.

**Comment by sleiner** [comment]
I too would be very happy to have this fixed. If there is anything I can do to help, please reach out @bobbrow :-)

**Comment by bobbrow** [comment]
Thanks for the offer @sleiner!  If you have a repro and can debug the extension as it's building the tree view, that would help us get the information we need to understand the bug.  [Contribution doc](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/contribute.md)

The line I would set a breakpoint on is here:
https://github.com/microsoft/vscode-cmake-tools/blob/48c4a333c75608b4abdd923d0caf21a8bf29aad3/src/tree.ts#L232

I suspect that the `item.resourceUri` is incorrect in this case.

**Comment by sleiner** [comment]
Thanks for the helpful hint 😊 I actually came up with something that fixes the problem (at least on my Mac with a very simple project). I'll test it with a much larger project at work tomorrow 👍🏻

**Comment by andreeis** [comment]
@sleiner, your contribution is in 👍. If all goes according to plans, we should release CMake Tools 1.7.2 tomorrow. Until then, here's a vsix with your change, if needed: https://github.com/microsoft/vscode-cmake-tools/actions/runs/814930130.

**Comment by sleiner** [comment]
Thanks, guys 🙌🏻
