### ISSUE TITLE
Handle preset files from CMake 3.19

### ISSUE THREAD

**Issue by Edhebi** [microsoft/vscode-cmake-tools#1507]
CMake 3.19 introduces presets, using `CMakePresets.json` and `CMakeUserPresets.json`.
They are somewhat akin to Visual Studio's `CMakeSettings.json`, see [here](https://cmake.org/cmake/help/v3.19/manual/cmake.1.html#generate-a-project-buildsystem) for more details.

It would be nice it cmake-tools was able to detect the presence of preset files, and ask the users which preset to build.
I expect it would look a bit like how variants work right now.

The command can be run by hand right now, but it requires setting up a dev environment by hand, which can be tedious, in particular on windows.

I'm not entirely sure where to start, but I'd be happy to contribute.

**Comment by andreeis** [comment]
Thank you for the feature idea. We are tracking this with https://github.com/microsoft/vscode-cmake-tools/issues/529.
