### ISSUE TITLE
"externalConsole": true does nothing.

### ISSUE THREAD

**Issue by deiuch** [microsoft/vscode-cmake-tools#1508]
### Brief Issue Summary

Adding an option "externalConsole" in `launch.json` while using MSVC does nothing (no terminal is opened when debugging starts).

### Expected:

1. Set "externalConsole": true
2. Launch Debug session with Shift+F5 or with the "Bug" button at the bottom panel
3. Debug session starts in an external system terminal

### Apparent Behavior:

No terminal actually opens when a debug session is started.

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.16.0-rc1
- **VSCode Version**: 1.50.0
- **CMake Tools Extension Version**: 1.4.2
- **Compiler/Toolchain**: Visual C++ 2019

**Comment by bobbrow** [comment]
Sorry for the confusion here.  `launch.json` is not wired up to the "Quick Debug" feature in CMake Tools.  To get this to work with our Quick Debug feature, you have to use the `cmake.debugConfig` setting.

```
  "cmake.debugConfig": {
    "externalConsole": true
  }
```
