### ISSUE TITLE
Add list of all cmake-tools vscode commands (for command substitution) to documentation

### ISSUE THREAD

**Issue by svdHero** [microsoft/vscode-cmake-tools#1513]
The documentation [here](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md#debug-using-a-launchjson-file) mentions command substitution in `launch.json` like, e.g.,
```json
"program": "${command:cmake.launchTargetPath}"
```
My question is, what commands are available besides `cmake.launchTargetPath`. Where can I find a list of commands in the documentation? How do I find out which commands are available?

**Comment by bobbrow** [comment]
[This document](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md#command-substitution) has the list.

We should update the debugger documentation to link there.

**Comment by svdHero** [comment]
Thank you for the link.

**Comment by bobbrow** [comment]
The debugger documentation has been updated.  Thanks for helping us make it better!
