### ISSUE TITLE
Suggestion：Do not pop up a message to remind that cmake tools is initializing

### ISSUE THREAD

**Issue by chouzz** [microsoft/vscode-cmake-tools#1518]
Suggestion：

Please don't bother me when cmake tools extension activate.  Every time I open vscode, a pop-up window will pop up in the lower right corner to prompt **cmake tools initializing**, it may not be very user friendly for some people. There's no reason for me to know that cmake tools is initializing.

Maybe you can cancel this prompt or replace it with the status bar.

**Comment by andreeis** [comment]
Thank you for your idea. We may not be able to implement it immediately, but we will track the community reactions to determine where this might fit into our backlog.
