### ISSUE TITLE
Customize/ToggleTouch Bar support

### ISSUE THREAD

**Issue by henrytsangsh** [microsoft/vscode-cmake-tools#1527]
### Brief Issue Summary

I would like to be able to customize, or toggle on/off, the new touch bar support.

Feature enhancement like using icon instead of text, would be a great addition.

I currently use the Nasc VSCode Touchbar extension, and with the Cmake Tools addition, I am now limited to 4 icons from the Nasc extension.

### Expected:

A vscode extension setting to enable/disable touch bar support

### Apparent Behavior:

Currently always on.

### Platform and Versions

- **Operating System**: macOS
- **VSCode Version**: 1.51.0
- **CMake Tools Extension Version**: 1.5.0

**Comment by bobbrow** [comment]
Thank you for the feedback.  I'll see if we can get this into our next patch.

**Comment by bobbrow** [comment]
The setting has been added.  If you could please try it out and let us know how it works for you, we would appreciate it.

1. Go here and download `cmake-tools.vsix`: https://github.com/microsoft/vscode-cmake-tools/actions/runs/349908117
2. Unzip the download
3. Use the "Install from VSIX..." command to install it.

**Comment by andreeis** [comment]
This improvement is included in CMake Tools 1.5.1 which was just released today.
Let us know if you encounter any problems.
