### ISSUE TITLE
Add "Configure" button

### ISSUE THREAD

**Issue by ghuser404** [microsoft/vscode-cmake-tools#1533]
When working with CMake, one often wants to reconfigure their project. However, there isn't a "Configure" button in the status bar, so user has two ways to do that:
- Click on variants and select one (this is too much if they just want to reconfigure current variant, and too error-prone for a misclick if a project has many variants)
- Switch to the CMake extension view, reconfigure and go back to Explorer (this is too inconvenient as it includes too much context switching)

Add "Configure" button to the status bar that would interact with a build variant, the same way as:
- "Build" button interacts with build target
- "Debug" and "Run" buttons interact with launch target

**Comment by andreeis** [comment]
Thank you for your feature idea. We may not be able to implement it immediately, but we will track the community reactions to determine where this might fit into our backlog.

**Comment by S-Mohsen-H** [comment]
I'd recommend using [VSCode Action Buttons extension](https://marketplace.visualstudio.com/items?itemName=seunlanlege.action-buttons) and use the button with the following setting:
`{
	"name": "Configure",
	"command": "cmake.configure",
	"useVsCodeApi": true,
	"singleInstance": true,
}`
You can set the color and name of the button to your liking.
The extension is a very useful one.

**Comment by gcampbell-msft** [comment]
@S-Mohsen-H @ghuser404 There is also the option to use the CMake: Configure command from the command palette. There is also the buttons in the Project Outline and the Project Status view. Closing this item since there are those buttons and/or commands available.
