### ISSUE TITLE
Add icons for build and launch targets

### ISSUE THREAD

**Issue by ghuser404** [microsoft/vscode-cmake-tools#1534]
When using a setting `"cmake.statusbar.visibility": "icon"`, there is no way to change build and launch targets using the status bar. As variants and kits lists are accessible through their dedicated icons, it would make sense to be able to select build and launch targets using an icon.

**Comment by andreeis** [comment]
Thank you for your feature idea. We may not be able to implement it immediately, but we will track the community reactions to determine where this might fit into our backlog.

**Comment by bobbrow** [comment]
Can you try this combination of settings?  This appears to do what you are describing.

```
    "cmake.statusbar.visibility": "icon",
    "cmake.statusbar.advanced": {
        "buildTarget": {
            "visibility": "default"
        },
        "launchTarget": {
            "visibility": "default"
        }
    },
```

**Comment by ghuser404** [comment]
@bobbrow I've opened this issue as a result of discussion in #1005. For me personally, your solution works fine, but I still decided to open this issue, because I feel like those two things deserve their own icons (kit selection has its own icon), and your solution is more like a workaround for the lack of dedicated icons.

IMO, when someone sets `cmake.statusbar.visibility": "icon"` it should just work, and `cmake.statusbar.advanced"` should be there purely for customisability, not for workaround. Just my two cents.

**Comment by bobbrow** [comment]
When the feature was added, we didn't think there was any icon that made sense for these two items.  The value is in the text and in icon mode you'd have to hover over the icon to see which target was active.  Instead we put that text in the respective build/launch icon tooltips.

But the feedback is noted.  Perhaps we could add a new hybrid "visibility" for `cmake.statusbar.visibility` to make this easier.  Something like "iconsAndTargets" which would do what the current combination of icons and advanced settings does above.

**Comment by ghuser404** [comment]
Makes sense. What about kits though? It has an icon and serves as selection from the list. So you would have to hover over it to see the current one, like you described.

**Comment by bobbrow** [comment]
The non-action icons were made clickable as a convenience to change the state that was tied to it.  They behave the same as the action icons in the sense that they show the state in the tooltip when the text is not displayed in the status bar.
