### ISSUE TITLE
${env:PATH} on cmake.testEnvironment setting doesn't work

### ISSUE THREAD

**Issue by skhrshin** [microsoft/vscode-cmake-tools#1536]
### Brief Issue Summary

I tried setting cmake.testEnvironment at settings.json to append path to DLLs and found that ${env:PATH} was not properly substituted.

### Expected:

1. Create a directory named 'cmaketest'
2. Put CMakeLists.txt under the directory
```
cmake_minimum_required (VERSION 3.0.0)
project (cmaketest)
enable_testing ()
message (STATUS OK.)
```
3. Put .vscode/settings.json under the directory
```
{
    "cmake.testEnvironment": {
        "PATH": "${env:PATH}"
    }
}
```
4. Open the directory with VSCode
5. Run tests
6. The following line should appear on the output window.
```
[ctest] CTest finished with return code 0
```

### Apparent Behavior:

CTest returns -1 instead of 0.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.18.0
- **VSCode Version**: 1.51.0
- **CMake Tools Extension Version**: 1.5.1
- **Compiler/Toolchain**: Visual C++ 2017

**Comment by andreeis** [comment]
Thank you for reporting this issue. We reproduce it and we will let you know if we need anything else for the investigation.

**Comment by lygstate** [comment]
Yeap not work, need fix for it

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.
