### ISSUE TITLE
1.5.0 appears to have broken "Clean All Projects"

### ISSUE THREAD

**Issue by schnort** [microsoft/vscode-cmake-tools#1542]
### Brief Issue Summary

1.5.0, 1.5.1, and 1.5.2 seem to have broken the "Clean All projects" menu item from the CMake Project Outline tab

### Expected:

1. Open VSCode in cmake workspace
2. Choose 'configure' or 'clean configure', etc. from the '...' menu item on the top right of the CMake Project Outline tab
3. Choose 'Clean All Projects' from the '...' menu item

### Apparent Behavior:

On 1.5.0 and beyond, it calls cmake with --target all 
On 1.4.2 and before, it calls cmake with --target clean

### Platform and Versions

Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

- **CMake Version**: 3.18.0
- **CMake Tools Extension Version**: 1.5.0, 1.5.1, 1.5.2
- **Compiler/Toolchain**: [cmake] -- The C compiler identification is MSVC 19.26.28806.0

**Comment by andreeis** [comment]
Thank you for opening this issue. We reproduce on our side and identified the PR that introduced this bug. We'll keep you updated about the fix for this.

**Comment by andreeis** [comment]
This is fixed in the 1.5.3 release that was just published earlier.
Upgrade your CMake Tools extension in VSCode and let us know if you encounter any other problems.
