### ISSUE TITLE
Problem on CMAKE TOOLS

### ISSUE THREAD

**Issue by Aniket-lodh** [microsoft/vscode-cmake-tools#1547]
I'm getting a notification everytime i build my cpp file::::::::
Bad **CMake** executable "". **Is it installed or settings contain the correct path (cmake.cmakePath)?**

![Screenshot (13)](https://user-images.githubusercontent.com/63922607/98975397-0f4e7e80-253c-11eb-9d17-032a820eb60d.png)

Operating System:**Windows 10.**

**Comment by bobbrow** [comment]
Did you install CMake.exe on your Windows PC?  We don't bundle it with this extension.  The extension is unable to locate it so it is asking you to set the `cmake.cmakePath` setting to tell the extension where it is.

**Comment by bobbrow** [comment]
But I don't know why this message would appear when you use the C++ extension's "Build and Debug Active File" feature.  Are you saying it appears every time you run that task?  How are you invoking it?

**Comment by Aniket-lodh** [comment]
@bobbrow 
well it doesnot do anything .
basically when i build a code the "**MESSAGE JUST POPS UP**" but untill **yesterday** everything was fine .
Today i just debuged a code, after that it started appearing.

![Screenshot (14)](https://user-images.githubusercontent.com/63922607/98980965-5e4be200-2543-11eb-8ed1-d9e48344ebd1.png)

**Comment by bobbrow** [comment]
Is there a CMakeLists.txt file in your workspace folder?  Did you open multiple folders in the workspace and one of them has a CMakeLists.txt in it?  I'm not sure why the extension would be activating if you just have a source file in the workspace.  We need more information to figure out what's going on.

**Comment by Aniket-lodh** [comment]
Today i just reinstalled the vs code and the problem solved .Thanks for replying though.I think if i debug any code again this problem will show again

**Comment by bobbrow** [comment]
Ok.  Then we will close this for now.  If you see this again and have information that we can use to debug this, we can reopen it and investigate.
