### ISSUE TITLE
Install target is not found because in uppercase

### ISSUE THREAD

**Issue by Murazaki** [microsoft/vscode-cmake-tools#1561]
### Brief Issue Summary

CMake tools does not find the INSTALL target.

### Expected:

1. Run `CMake : Configure`
2. Run `CMake : Install` or `install` target from `CMake : Build Target`

### Apparent Behavior:

CMake tools tries to launch `install` target while the real name is `INSTALL`

```
"C:\Program Files\CMake\bin\cmake.EXE" --build e:/******/build --config RelWithDebInfo --target install -- /maxcpucount:50
```

### CMake Tools Log

```
[main] Building folder: ******* install
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build e:/******/build --config RelWithDebInfo --target install -- /maxcpucount:50
[build] Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
[build] Copyright (C) Microsoft Corporation. All rights reserved.
[build] 
[build] MSBUILD : error MSB1009: Project file does not exist.
[build] Switch: install
[build] Build finished with exit code 1
```

### Platform and Versions

- **Operating System**: Windows 10 Entreprise 10.0.18363 Build 18363
- **CMake Version**: CMake 3.18.4
- **VSCode Version**: 1.15.1
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: Visual Studio 2019 MSVC 14.27.29110

**Comment by andreeis** [comment]
Thank you for opening this issue. I wasn't aware that you can define INSTALL target.

It would help us if you share your CMakeLists.txt (or only how you define this target) and what happens in your terminal when the CMake extension is not involved, only the raw CMake tool. Does that handle install and INSTALL differently? Can you have both defined?

We can fix the extension to support anything that the build tool supports, of course.

**Comment by Murazaki** [comment]
I don't think INSTALL target has been renamed, though I did change `PREDEFINED_TARGETS_FOLDER` to the root folder.

I would advise to use INSTALL uppercase for a Visual Studio kit scenario (it has always been uppercase, to my knowledge) or at least let the Build Target finder find it.

**Comment by bobbrow** [comment]
I'm not sure what's different here besides maybe that you have a newer version of CMake.  We haven't ever seen this problem before and the CMake targets have always been upper cased.  Do you happen to have the case-sensitive file system enabled for the folder you're working in?

In any case, I believe #1511 would address this.
