### ISSUE TITLE
Extension activated on Show Tasks/Run Build Task even if not in a CMake project

### ISSUE THREAD

**Issue by rapgenic** [microsoft/vscode-cmake-tools#1562]
### Brief Issue Summary

When working on non CMake projects and using the "Tasks: Run Build Task" or simply "Show tasks" command, the cmake extension activates automatically asking to choose a kit, creating a new view and filling the statusbar with useless information (since there is no CMake project)

### Expected:

For a non CMake project I would expect that even though I run the "Build" task, the extension wouldn't turn on.

### Other Notes/Information

Looking at the package.json I can see that one of the activation events is `    onCommand:workbench.action.tasks.runTask`. This suggests to me that the originally desired behaviour was:

1. User asks to show tasks
2. Register a cmake task provider in case there were any tasks to provide

However i think that this activation event should be removed, leading to the following new behaviour:

1. If there is some reason to activate cmake on folder open (e.g. CMakeLists.txt present) load the full cmake extension (which is the actual behaviour as of now, for what I can see)
2. Since CMake is used and configured in the project, _only now_ register a task provider for cmake tasks

This would allow to reduce the UX clutter, because the CMake extension doesn't turn on apparently for no reason adding a lot of unwanted UI elements, and in my opinion is more correct, because there is no reason to register a cmake task provider if there is no cmake project in the first place

**Comment by andreeis** [comment]
Thank you for opening this issue, we will investigate and let you know if we need any other info.

**Comment by Trass3r** [comment]
Same here, for example this extension is active when working on TypeScript projects (vscode extensions).
It overrides Ctrl+F5 and asks for a kit for example, so I always have to go through the Run menu.
There are also annoying popups or configure attempts every now and then.

**Comment by bobbrow** [comment]
Sorry for the inconvenience.  We will be fixing this for the next release.

**Comment by andreeis** [comment]
We almost have CMake Tools 1.6.0 release out the door. Until then, if you want, you can also verify if this problem has been fixed correctly by installing the vsix built here: https://github.com/microsoft/vscode-cmake-tools/actions/runs/557242002#artifacts.

**Comment by rapgenic** [comment]
I tried it and I believe the issue is fixed now, thank you!
