### ISSUE TITLE
Intellisense: incomplete configuration provided to cpptools

### ISSUE THREAD

**Issue by akligman** [microsoft/vscode-cmake-tools#1563]
I'm getting few errors when using when using cmake tools as configuration provide for cpptools
1. #include errors detected based on information provided by the configurationProvider setting
2. cannot open source file
3. #define's are not reported (provides empty defines list)

CMake tool has no issue to configure/build project and detects correctly all targets.
If I switch cpptools to use **compileCommands** instead of **configurationProvider** and point to generated compile_commands.json intellisens works as expected, defines are not empty, and there is no include issues

**Comment by andreeis** [comment]
Thank you for opening this issue. Can you craft a small repro project for us?
Is this a regression with a recent CMake Tools release?

**Comment by akligman** [comment]
I'm not sure if it a regression since I've recently installed VSCode and this is my first time trying to build CMake project.
BTW I forgot to mentions versions: CMake Tools-1.5.3, CPP Tools-1.1.2
I'll try to reproduce with small custom project and will report back

**Comment by grigorig** [comment]
I'm not sure if I should open a new issue, but I also have this issue. It happens randomly and there's nothing special in the C++ extension logs. IntelliSense works perfectly, but then after triggering a build by pressing `F7`, it sometimes starts to fail and I get the "#include errors detected" error. Resetting the IntelliSense database works sometimes, and restarting extension host seems to fix it 100% of the time.

**Comment by bobbrow** [comment]
@grigorig, I created a new issue to discuss what's going on in your workspace.  #1621
