### ISSUE TITLE
Compile Active file is broken in some cases.

### ISSUE THREAD

**Issue by thothothotho** [microsoft/vscode-cmake-tools#1565]
### Brief Issue Summary

With a `compile_commands.json` like this:
```
...
  "command": "/usr/lib/ccache/cc -DIMGUI_USER_CONFIG=\"<NQimconfig.h>\"  -O2 -g -DNDEBUG   -o CMakeFiles/bla.dir/foo.c.o   -c /home/fred/src/foo/foo.c",
...

the button `Compile Active file` generate a bogus command.
```

```
/usr/lib/ccache/cc "<NQimconfig.h>" -O2 -g -DNDEBUG -o CMakeFiles/bla.dir/foo.c.o -c /home/fred/src/fred@Pecrennes:~/src/foo/build$ /usr/lib/ccache/cc "<NQimconfig.h>" -O2 -g -DNDEBUG -o CMakeFiles/bla.dir/foo.c.o -c /home/fred/src/foo/foo.c
cc: error: <NQimconfig.h>: No such file or directory
```

### CMake Tools Log

```
[main] Configuring folder: foo 
[cmake] Configuring done
[cmake] Generating done
```

### Steps to reproduce

  * Unzip the simple project attached
  * configure it.
  * open the file foo.c from vscode
  * click _Compile Active file_

The problem comes from this in the cmakelist:
```
target_compile_definitions(bla PRIVATE IMGUI_USER_CONFIG=<NQimconfig.h>)
```

The command stored in `build/compiled_commands.json` is correct.  Everything is properly escaped.
`make` correctly execute this command:
```
/usr/lib/ccache/cc -DIMGUI_USER_CONFIG="<NQimconfig.h>"   -MD -MT CMakeFiles/bla.dir/foo.c.o -MF CMakeFiles/bla.dir/foo.c.o.d -o CMakeFiles/bla.dir/foo.c.o   -c ../foo.c
```

somehow, the command executed by _Compile Active file_ is corrupted and this command is executed instead:
```
fred@Pecrennes:~/src/foo/build$ /usr/lib/ccache/cc "<NQimconfig.h>" -O2 -g -DNDEBUG -o CMakeFiles/bla.dir/foo.c.o -c /home/fred/src/foo/foo.c
cc: error: <NQimconfig.h>: No such file or directory
```

### Platform and Versions

- **Operating System**: Ubuntu 20
- **CMake Version**: cmake version 3.13.3
- **VSCode Version**: 1.51
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: gcc 9

[foo.zip](https://github.com/microsoft/vscode-cmake-tools/files/5574065/foo.zip)

**Comment by andreeis** [comment]
Thank you for opening this issue and for providing a small contained repro, this helps so much with our investigation.

**Comment by andreeis** [comment]
Possibly related with https://github.com/microsoft/vscode-cmake-tools/issues/1493 and possibly fixed by https://github.com/microsoft/vscode-cmake-tools/pull/1556. We'll verify and let you know.
