### ISSUE TITLE
Old cmake used when both VS2017 cmake and VS2019 cmake installed

### ISSUE THREAD

**Issue by linquize** [microsoft/vscode-cmake-tools#1567]
### Brief Issue Summary

Install VS2017 with C++ and cmake features
Install VS2019 with C++ and cmake features
Install VSCode with vscode-cmake-tools extension

No extra configuration is done.

### Expected:

CMake > Select a Kit: Clang 10.0 with Visual Studio 2019 Release (amd64)
CMake > Build

cmake.exe is used from VS2019.
I expect to use cmake from the latest Visual Studio by default.

My CMakeLists.txt has cmake minimum requirement `cmake_minimum_required(VERSION 3.14)`

### Apparent Behavior:

cmake.exe is used from VS2017

### Developer Tools Log

```
[main] Building folder: project1 
[cms-client] Configuring using the "Ninja" CMake generator
[main] Configuring folder: project1 
[cmake] CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
[cmake]   CMake 3.14 or higher is required.  You are running version
[cmake]   3.12.18081601-MSVC_2
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] See also "C:/project1/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "C:/project1/build/CMakeFiles/CMakeError.log".
[cms-driver] Error during CMake configure: 
	Error: Configuration failed.
	at CMakeServerClient._onMessage (c:\Users\User\.vscode\extensions\ms-vscode.cmake-tools-1.5.3\dist\main.js:22653:33)
	at CMakeServerClient._onMoreData (c:\Users\User\.vscode\extensions\ms-vscode.cmake-tools-1.5.3\dist\main.js:22626:18)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

### Platform and Versions

- **Operating System**: Windows 7
- **CMake Version**: 3.12.18081601-MSVC_2 (from VS2017), 3.18.20081302-MSVC_2 (from VS2019)
- **VSCode Version**: 1.51.1
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: Clang 10.0.0 (from VS2019)

**Comment by linquize** [comment]
Suggestion: add `-sort` flag when running `vswhere.exe` command

**Comment by andreeis** [comment]
Thank you for opening this issue. We will let you know if we need anything else for our investigation.
