### ISSUE TITLE
Platform name with space

### ISSUE THREAD

**Issue by Exidak** [microsoft/vscode-cmake-tools#1569]
Hello!

I am trying to configure my project and i get error:
`Failed to run MSBuild command`
I think it is because command line like that 
`-G "Visual Studio 16 2019" -A " Win32"`
(i set `cmake.configureArgs` before like `[ "-A Win32" ]` but then delete it). 
Why the platform still " Win32"? Where did it cache? How to fix platform name?

**Comment by andreeis** [comment]
Regarding the cache refresh: try the "CMake: Delete Cache and Reconfigure" command from the pallette. If that doesn't work for you, delete your build folder (usually the build subfolder in your workspace, unless you set it differently), reload VS and configure. Let us know the outcome of this.

Do you really need to use cmake.configureArgs? If you select the proper VS kit, CMake should get the proper architecture information for the tools to be run (the hosted compiler) and the code to generated (the target project binary). For example, run the "CMake: Select a Kit" command from the pallette, choose "Visual Studio Enterprise 2019 Release - x86" or "Visual Studio Enterprise 2019 Release - amd64_x86" and both should send the proper target architecture to CMake (which would be "win32", small cap w). If you don't have Enterprise, chose a similar name for your VS install.
