### ISSUE TITLE
warning: setlocale: LC_ALL: cannot change locale (en-US) on linux

### ISSUE THREAD

**Issue by djmittens** [microsoft/vscode-cmake-tools#1572]
### Brief Issue Summary
When compiling my code using cmake and Ninja generator, i get the following warning
```
[build] [435/436  99% :: 19.510] Linking CXX executable puzzle/puzzle
[build] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en-US)
[build] [435/436  99% :: 19.554] Linking CXX shared library vendor/bullet3/src/BulletSoftBody/libBulletSoftBody.so.3.05
[build] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en-US)
[build] [436/436 100% :: 19.565] Creating library symlink vendor/bullet3/src/BulletSoftBody/libBulletSoftBody.so
[build] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en-US)
[build] Build finished with exit code 0
```
It appears after every line and is very annoying.
When building from command line, i dont have issues like this, and it works great.

This warning makes sense as `en-US` is not a locale available in my linux environment. Why is it attempting to set it ? I have the following available
```
λ ~/src/c-gamedev/ master* locale -a                                                                                      
C
en_US.utf8
POSIX
```

This is the command that it builds with
```
[main] Building folder: c-gamedev 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/djmittens/src/c-gamedev/build --config Debug --target all -- -j 14
```

**Comment by djmittens** [comment]
Im closing this issue because it turns out to be an issue with electron, 
here is a link that has a solution in it, in case someone else runs into this.
https://github.com/microsoft/vscode/issues/110491

**Comment by bobbrow** [comment]
Thank you for linking to the solution.
