### ISSUE TITLE
Warnings/Erros from clang-cl not shown in Problem view

### ISSUE THREAD

**Issue by BenediktRombach** [microsoft/vscode-cmake-tools#1573]
### Brief Issue Summary

We have a Windows C++ application build with CMake. We are using the Buildtools from VS 2019, either the MSVC toolchain or the LLVM / Clang-cl toolchain packaged with Visual Studio.

VMake tools do a great job ad detecting the kits, triggering the buildprocess, etc. but the compile output when using clang-cl (and ninja) is not parsed correctly, so no Warnings / Errors are generated. When using the standard VS 2019 Buildchain with the VS Generator, this works; but we'd like to use clang-cl at least while developing, as the warning options are far more fine-grained and detailed compared to the MS Buildtools.

I suspect the wrong problem matcher is used to parse the compile output (as clang-cl lookl like Windows, but the output is actually Linux-y).

Unfortunately I don't have a self-installed LLVM toolchain on that machine, to check whther that one would parse warnings correctly.

### Expected:

1. Push compile button
2. See Warnings in Problems tab.

### Apparent Behavior:

1. Push compile button
2. Output has lines like 
```
[build] ..\.\include\myproject/serialization.h(21,1): warning: unused member function 'unused' [-Wunused-member-function]
[build] CEREAL_REGISTER_TYPE(CameraData);
[build] ^
[build] vcpkg_installed\x64-windows\include\cereal/types/polymorphic.hpp(91,3): note: expanded from macro 'CEREAL_REGISTER_TYPE'
[build]   CEREAL_BIND_TO_ARCHIVES(__VA_ARGS__)
[build]   ^
[build] vcpkg_installed\x64-windows\include\cereal/details/polymorphic_impl.hpp(78,9): note: expanded from macro 'CEREAL_BIND_TO_ARCHIVES'
[build]         CEREAL_BIND_TO_ARCHIVES_UNUSED_FUNCTION                          \
[build]         ^
[build] vcpkg_installed\x64-windows\include\cereal/details/polymorphic_impl.hpp(64,63): note: expanded from macro 'CEREAL_BIND_TO_ARCHIVES_UNUSED_FUNCTION'
[build]   #define CEREAL_BIND_TO_ARCHIVES_UNUSED_FUNCTION static void unused() { (void)b; }
[build]                                                               ^
[build] 5789 warnings generated.
[build] [37/37 100% :: 22.481] Linking CXX static library myproject.lib
```
but the problem tab stays empty.

### Platform and Versions

- **Operating System**: Windows 10 (1809)
- **CMake Version**: 3.18.4
- **VSCode Version**: 1.51.1
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: clang-cl from VS 2019

**Comment by andreeis** [comment]
Thank you for opening the issue. We are tracking this with https://github.com/microsoft/vscode-cmake-tools/issues/517.
