### ISSUE TITLE
Variants "generator" and "toolset" variables are ignored

### ISSUE THREAD

**Issue by ghuser404** [microsoft/vscode-cmake-tools#1574]
Variants define "generator" and "toolset" variables, but they have no effect. I see that 5cf27f3c88dcf0111f60ecca6ed9da44deeb99ad removed them from use. What is the reason for this?

I would like to configure different variants with various generator/toolset/platform variations. Can these variables be brought back, along with "platform" configuration?

**Comment by bobbrow** [comment]
This pre-dates our (Microsoft's) involvement with the extension, so we will have to do some investigation to determine what happened.  As it appears the feature has been removed, we'll consider this a feature request.  Thank you for bringing this to our attention.  We can't guarantee that we will address it immediately, but we will track the community reactions to determine where this might fit into our backlog.
