### ISSUE TITLE
Build every time all project

### ISSUE THREAD

**Issue by frenzisys** [microsoft/vscode-cmake-tools#1585]
I usually use QtCreator to compile my project. 
I started to use vscode for the best use of python with c ++.
Unfortunately vscode recompiles the whole project unlike qtcreator every time i try to start/debug/install my program.
I try to start compile from command line 

> cmake --build . --target all -j12

but doesn't change anything. 
I think there is some option i don't find.

This takes me 60 sec (vscode) vs 2 sec (qtcretor)

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.51
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: Clang 11 + ninja

**Comment by andreeis** [comment]
See if setting cmake.buildBeforeRun to false unblocks you.
When your project is up to date and VSCode triggers a build (which is expected unless you change the above setting), do you see compilation, linking or other build steps being run instead of skipped when their inputs-outputs are up to date? If that happens, we would like to investigate more and a repro from you would help.

**Comment by frenzisys** [comment]
So, if I set  cmake.buildBeforeRun=false, it doesn't compile and link, but my project remains out of date if i change something.
If i set cmake.buildBeforeRun=true, it compile all my project (not only link, but full compiled).
With QtCreator configuration, it compiles only files that have been changed.

**Comment by frenzisys** [comment]
In the build folder of QtCreator, there is another file like source_name.cbp because QtCreator use Codeblocks- Ninja as generator

**Comment by andreeis** [comment]
I see. We'll have a look. Do you happen to have a repro? It would save us time since this behavior doesn't happen normally and we might not find the trigger scenario that fast.

**Comment by frenzisys** [comment]
Sorry...Repro?

This is vscode build.ninja
[build.ninja.txt](https://github.com/microsoft/vscode-cmake-tools/files/5664468/build.ninja.txt)

And this is qtcreator build.ninja
[build.ninja.txt](https://github.com/microsoft/vscode-cmake-tools/files/5664475/build.ninja.txt)

I don't know what i have to see...

**Comment by frenzisys** [comment]
if i write ninja -d explain, say all file are dirty

> ...
> ninja explain: /include/x86_64-linux-gnu/c++/10/bits/c++allocator.h is dirty
> ninja explain: /include/c++/10/ext/new_allocator.h is dirty
> ninja explain: /include/c++/10/bits/ostream_insert.h is dirty
> ninja explain: /include/c++/10/bits/cxxabi_forced.h is dirty
> ninja explain: /include/c++/10/bits/stl_function.h is dirty
> ninja explain: /include/c++/10/backward/binders.h is dirty
> ninja explain: /include/c++/10/bits/range_access.h is dirty
> ninja explain: /include/c++/10/initializer_list is dirty
> ninja explain: /include/c++/10/bits/iterator_concepts.h is dirty
> ninja explain: /include/c++/10/concepts is dirty
> ninja explain: /include/c++/10/bits/range_cmp.h is dirty
> ninja explain: /include/c++/10/bits/basic_string.h is dirty
> ninja explain: /include/c++/10/ext/alloc_traits.h is dirty
> ninja explain: /include/c++/10/bits/alloc_traits.h is dirty
> ...

**Comment by frenzisys** [comment]
At the end of ninja.build the last instructions have a very different length between the two files

I think the command given to cmake to create the files, some options are missing

**Comment by andreeis** [comment]
Thank you for the extra info. It might be enough. We will investigate and let you know if we need anything else.

**Comment by frenzisys** [comment]
for now i changed my generator from "ninja" to "unix makefile", i don't know why cmake-tool doesn't configure ninja correctly

**Comment by andreeis** [comment]
Ignoring the CMake Tools extension for the moment, can you tell us if you have a CMake (+Ninja generator) build command which builds your project as expected if you run it from a terminal?

**Comment by frenzisys** [comment]
Ok, right now i reopened vscode after the last time, it has updated some
components and now it compiles only the changed parts

Il giorno mar 19 gen 2021 alle ore 23:48 Andreea Isac <
notifications@github.com> ha scritto:

**Comment by andreeis** [comment]
So good to hear this. Then I'm closing the report. Feel free to reopen if you see this happen again.
