### ISSUE TITLE
[Suggestion] Change very uninformative relative paths to absolute paths on the side bar

### ISSUE THREAD

**Issue by songyang-dev** [microsoft/vscode-cmake-tools#1586]
Hello. Currently, CMake tools use relative paths for build targets in the side bar. Sometimes the relative paths get very long, e.g. like in the picture, because of `../`'s. Is there an option to switch these paths to absolute paths? That would be more helpful to the human eye.
![image](https://user-images.githubusercontent.com/10444460/101422493-cd0f2780-38c4-11eb-8e85-9dc985984201.png)

# Version
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by andreeis** [comment]
Thank you for the idea. We may not be able to implement it right away, but we will track the community reactions to determine where this might fit into our backlog.
