### ISSUE TITLE
Build notification covers build log itself

### ISSUE THREAD

**Issue by vadi2** [microsoft/vscode-cmake-tools#1588]
![image](https://user-images.githubusercontent.com/110988/101659139-03c07b80-3a46-11eb-8f5e-6b797043dc88.png)

I can't see the latest of the build log because the notification covers it, which is a little problematic.

**Comment by andreeis** [comment]
Click on the bell icon on the bottom right (the one with a star on top of it). That should make the popup disappear. Let us know if it doesn't and if this works for you feel free to close this report.

**Comment by julienlavergne** [comment]
Yes it does, but a setting to always hide would be better.

**Comment by mdemoret-nv** [comment]
I agree with @julienlavergne. After stumbling upon this thread I find myself constantly double clicking the notification icon to hide the popup so I can get to the scroll bar and read the bottom lines of my build. An option to always hide this would be much better.

**Comment by bobbrow** [comment]
Agreed, it would be better to minimize this to the status bar or just remove it. The progress is there in the build log.
