### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by yazanqubati** [microsoft/vscode-cmake-tools#1589]
### Expected:

1. Push button
2. Thing happens

### Apparent Behavior:

1. Push button
2. Nothing happens

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: 
- **CMake Version**: 
- **VSCode Version**: 
- **CMake Tools Extension Version**: 
- **Compiler/Toolchain**:

**Comment by andreeis** [comment]
Did you publish this issue early by mistake? There is no information about anything :). No worries, we'll keep an eye on this report and we'll reply once you give more details.
