### ISSUE TITLE
Is it possible to add os/distro version to build folder buildDirectory settings?

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-cmake-tools#1590]
Is there a variable for os version like Ubuntu-20.04 or container name? I have to use one directory and build for multiple Ubuntu versions in docker containers. I' m looking for a way to separate build folder for different distros.

**Comment by andreeis** [comment]
Thank you for this idea. I am not sure I understand precisely. Can you give us more details about what you'd like to see implemented?

**Comment by xgdgsc** [comment]
A variable that generates `Ubuntu-20.04`, `Ubuntu-16.04`, `CentOS 7.6` to build folder like `build-Release-GCC 9.3.0-Ubuntu-20.04`.
