### ISSUE TITLE
"Edit Cmake Cache UI" not working

### ISSUE THREAD

**Issue by deimi** [microsoft/vscode-cmake-tools#1591]
### Brief Issue Summary

Changes made with the Cmake Cache UI editor don't get saved.

### Expected:

1. Press F1
2. Cmake: Edit Cmake Cache UI
3. Change anything
4. Press save
5. Close cache editor
6. The cmake cache file should now contain the changed values

### Apparent Behavior:

1. Press F1
2. Cmake: Edit Cmake Cache UI
3. Change anything
4. Press save
5. the star in the "file name" remains and indicates unsaved changes
![image](https://user-images.githubusercontent.com/8256985/101762363-a546dc00-3add-11eb-8455-57ab3fa83488.png)
6. Close cache editor
7. A popup appears which tells that there are unsaved changes
![image](https://user-images.githubusercontent.com/8256985/101762447-c14a7d80-3add-11eb-9368-fc49cbb4ca8f.png)
8. Press Yes
9. The cmake cache file don't contain any changes made in the UI

### CMake Tools Log

```
Nothing
```

### Developer Tools Log

```
Nothing
```

### Platform and Versions

- **Operating System**: Linux Mint 19 
- **CMake Version**: 3.16.3 
- **VSCode Version**: 1.51.1 snap version
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64

- **CMake Tools Extension Version**: v1.5.3 
- **Compiler/Toolchain**:

**Comment by andreeis** [comment]
I am not able to reproduce as you describe. Everything gets saved properly in all scenarios.
I do see the setting getting lost if the project is reconfigured, but that is expected, right?
Let's figure out what's different on your side...
When you press SAVE, do you see any bottom right popups? One that's temporary "Configuring project" and one that stays "CMake options have been saved". You mention you see nothing in the log. It almost looks like the button is not really pressed. Set cmake.loggingLevel to debug and try again.

**Comment by deimi** [comment]
No popups appear when I press the Save button.  
Yes of course the settings should get lost if you do a reconfigure. But I don't do this. I do a configure and afterwards I try to edit the Cache via UI, but those edits won't get saved.

Here are the cmake logs:
- When opening the UI
```
[extension] [3674] cmake.openConfiguration started
[cache] Reading CMake cache file /home/user/projects/asdf/_build/CMakeCache.txt
[cache] Parsing CMake cache string
[extension] [3674] cmake.openConfiguration finished (returned 0)
```
- When pressing the Save button
```
[cache] Reading CMake cache file /home/user/projects/asdf/_build/CMakeCache.txt
[cache] Parsing CMake cache string
```

- After closing the UI and answering the popup question "Do you want to save the latest cache edits?" with yes
```
[cache] Reading CMake cache file /home/user/projects/asdf/_build/CMakeCache.txt
[cache] Parsing CMake cache string
```

**Comment by andreeis** [comment]
This is still very mysterious because when I press SAVE I see lots more in the output channel.
A short in the dark, what exact setting you are modifying? Does it happen for all of them? Some are string, some are boolean...
I am running out of ideas to give you to try on your side. Can you make a small isolated repro for us?

**Comment by andrewmcdonald-oxb** [comment]
I have the same issue. The cache editor appears not to work at all. As described here, the * remains in the editor tab after pressing Save. The popup then asks if I'd like to save again. Subsequently running a configure doesn't include any of the changes.

**Comment by aemseemann** [comment]
@andrewmcdonald-oxb  It sounds like the SAVE button is not connected to any handler. You can verify this using the developer tools. While the cache editor is open, please run `Developer: Open Webview Developer Tools` from the command palette. Then select the SAVE button and have a look at the "Event Listeners" tab. There should be one entry as in the image below. If it is empty, this would explain your observed behavior.
![image](https://user-images.githubusercontent.com/51268362/116857288-d6df5180-abfc-11eb-9118-1f0fd2e02b78.png)

Furthermore, can you please check if there are any errors logged to the "Console" tab?

**Comment by deimi** [comment]
Yes, there is an event listener registered:

![image](https://user-images.githubusercontent.com/8256985/116862666-68eb5800-ac05-11eb-99a0-0ddf035a62d8.png)

Clicking on the button doesn't log anything in the console tab

**Comment by SpriteOvO** [comment]
Same problem. When I switched the page from another page to "CMake Cache Editor", the `Webview Developer Tools` console gave the following errors:

```
