### ISSUE TITLE
 cmake.testEnvironment doesn't documented yet

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#1597]
### Expected:

1. Push button
2. Thing happens

### Apparent Behavior:

1. Push button
2. Nothing happens

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: 
- **CMake Version**: 
- **VSCode Version**: 
- **CMake Tools Extension Version**: 
- **Compiler/Toolchain**:

**Comment by andreeis** [comment]
Thanks for keeping track with undocumented concepts in CMake Tools extension. We are going to address this together with other similar documentation work items.
We should ignore the expected/apparent, right? Let us know if there is also something wrong with any of the buttons, but in that case give more details.
