### ISSUE TITLE
Debug/Launch commands don't work when project name starts with capital letter

### ISSUE THREAD

**Issue by MonJamp** [microsoft/vscode-cmake-tools#1600]
### Brief Issue Summary

When the project name start with a capital letter (e.g. `project(DameEmu)`), the debug and launch buttons are unable to find or start the program. When changing the project name to start with a lower case letter (e.g. `project(dameEmu)`), the buttons work correctly. This issue is also present when using `${command:cmake.launchTargetPath}` in `launch.json`.

### Platform and Versions

- **Operating System**: Fedora
- **CMake Version**: 3.17.4
- **VSCode Version**: 1.52.0
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: GCC 10.1.1

### Other Notes/Information

This issue might also be preventing CMake Tools from properly configuring Intellisense. After changing the project name to start with a lower case letter, intellisense started working correctly. Before changing the project name I got red squiggles when including a wxWidgets header.

**Comment by andreeis** [comment]
Thank you for opening this report. We will let you know if we need anything else to address this.
Investigation and progress may be slow over the winter holidays.
