### ISSUE TITLE
Project Outline Feature Request: Alternative Target-based View

### ISSUE THREAD

**Issue by Spirrwell** [microsoft/vscode-cmake-tools#1606]
Hello!

![image](https://user-images.githubusercontent.com/8671884/102958384-b8c55000-44aa-11eb-9ee8-b26ed996f7e6.png)

In the project outline, the targets are organized under their folder paths. In the screenshot you see the GraphicsVK, Input, and ModelImport targets are under "graphics/vk", "input", and "modelimport" folders respectively.

However, I would greatly prefer an alternate target-based view where the targets themselves are on top, not their folders.

Something like this:

![image](https://user-images.githubusercontent.com/8671884/102958635-6173af80-44ab-11eb-974b-8e5a98a0672f.png)

As well as a right click context menu for the project itself (in my case "Thermite" and "FMT") which includes options for rebuilding\cleaning the entire project, similar to this:

![image](https://user-images.githubusercontent.com/8671884/102959247-f6c37380-44ac-11eb-9250-bc6a75ee3c7f.png)

----
To avoid confusion, this is similar to, but not a duplicate of this feature request issue here: https://github.com/microsoft/vscode-cmake-tools/issues/919 But I think both that request and this complement each other.

**Comment by mikaheli** [comment]
This would be awesome. Current CMake Project Outline get pretty messy with larger projects with many targets.

**Comment by bobbrow** [comment]
Thanks for the feature idea.  We may not be able to get to this immediately, but would definitely accept a pull request if anyone has the time to start investigating this now.  We would want to be able to toggle between this view and the existing one.

**Comment by Zingam** [comment]
I would vote for a complete overhaul of the project outline feature and the related functionality - like install targets aren't supported.

**Comment by Zingam** [comment]
Could the targets still keep the file hierarchy inside too and not just list them in a flat hierarchy?

**Comment by andreeis** [comment]
Great ideas, sounds good @Zingam

**Comment by gcampbell-msft** [comment]
Closing this issue because we now have a simple targets view in the project outline view! Thanks. 

Please feel free to create new issues if there are still requests you have that we haven't implemented.
