### ISSUE TITLE
Configuration provider always provides "Release" configuration.

### ISSUE THREAD

**Issue by laino** [microsoft/vscode-cmake-tools#1608]
### Brief Issue Summary

When selecting the "Visual Studio Build Tools 2019" in ``CMake: Select a Kit`` and "Debug" in ``CMake: Select Variant``, sections like

```C
#ifndef NDEBUG
printf("what\n");
#endif
```

will be incorrectly grayed out.

``C/C++: Log Diagnostics`` reports:

```
[...]
 Defines:
        WIN32
        _WINDOWS
        NDEBUG
[...]
```

which is incorrect, because it is built *without* NDEBUG when you run ``CMake: Build``.

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**:  3.19.2
- **VSCode Version**: 1.52.1
- **CMake Tools Extension Version**: 1.5.3

**Comment by bobbrow** [comment]
Can you enable "debug" logging for cpptools \[[link](https://code.visualstudio.com/docs/cpp/enable-logging-cpp)\], then restart VS Code and try again?  Then please share the logging output from cpptools.  That will help us determine whether this is a cpptools or cmake-tools issue.  Thank you!

**Comment by daiday** [comment]
I met the same problem. So I choose to use "_DEBUG", it worked well.
