### ISSUE TITLE
[Feature request] Options for a smaller size in the status bar

### ISSUE THREAD

**Issue by Inujel** [microsoft/vscode-cmake-tools#1612]
The finite space in the status bar of vscode is often a limiting factor of the UI. I often have to choose which extension I want to display or hide in order to see what I want.

I find sad that the cmake tools extension often takes about the half of my screen with a good part of it being not that useful.

![image](https://user-images.githubusercontent.com/1295051/103523931-fa77d280-4e7c-11eb-90e4-bc50cda4147a.png)

It would be great if the extension could provide some settings to reduce the usage of the space in the status bar.

My thoughts are:
 - ![image](https://user-images.githubusercontent.com/1295051/103524150-56daf200-4e7d-11eb-8b62-f2f39a8772dc.png)
    - Having the name of the current configuration is useful
    - I think the current icon does not convey any useful information. I'd rather have either
      - The CMake logo, which could indicate that this area of the status bar is used by cmake tools
      - An icon indicating that this button is used to switch between configurations (but I have no further idea)
    - The "CMake: " prefix is not useful
    - The information provided by the ": Ready" suffix could maybe be provided with an overlay of the button icon?

 - ![image](https://user-images.githubusercontent.com/1295051/103524549-0ca64080-4e7e-11eb-97cc-073a041ba4fd.png)
   -  This is the biggest offender. I rarely switch between kits and it takes a huge amount of space. I think having the button without text would be perfectly fine.

 - ![image](https://user-images.githubusercontent.com/1295051/103524791-70c90480-4e7e-11eb-8d75-80678ff49f1f.png)
   - The "Build" text should be redundant. The icon should suffice. However, maybe the gear is not the best choice of icon for this. Maybe something more [in the spirit of the compilation icon from Visual Studio](https://www.awicons.com/stock-icons/xp-artistic/compile-1/) would be clearer. Even without changing the icon, I think offering the option to remove the text would be great.
   - Offering the option to select different targets to build and to run might be useful in some cases, but I find it to be a burden more often than not. I think having the option to select a single target for both building and running would be good in itself, and would reduce the amount of space used by the extension.

 - ![image](https://user-images.githubusercontent.com/1295051/103525520-a91d1280-4e7f-11eb-835e-e4d7b81de347.png)
   - The text could be removed.

All in all, my ideal display would be something like 
![image](https://user-images.githubusercontent.com/1295051/103527006-fd28f680-4e81-11eb-98e0-e5517434d999.png)
(Done in paint with a trackpad, please be forgiving)

Thanks for reading this. Please keep in mind that I'm suggesting to add options, not to change the default look of the extension.

**Comment by bobbrow** [comment]
We added two settings in 1.4.0 to allow you to control how the status bar appears.

Please take a look at `cmake.statusbar.visibility` and `cmake.statusbar.advanced` which should give you full control over the appearance of the status bar.  In your case, I think you would want to set `cmake.statusbar.visibility` to `"icon"` and then under `cmake.statusbar.advanced` override the appropriate items to make them `visible` or `compact` according to your preference.

**Comment by Inujel** [comment]
Oh, this is great, I'm sorry I missed it. 

I did search for "status bar" before posting this, but it shows many many other unrelated issues before #212.

Anyway thx, this is perfect.
