### ISSUE TITLE
value of CMAKE_GENERATOR_TOOLSET:INTERNAL is getting prefixed with "host=" every time we try to configure a project

### ISSUE THREAD

**Issue by bvbasavaraju** [microsoft/vscode-cmake-tools#1613]
### Brief Issue Summary

After Making change in GUI, editing the CMake configuration using "Edit CMake Cache (UI)" and saving the changes,
value of "CMAKE_GENERATOR_TOOLSET:INTERNAL" in cache file will end up with prefixing the "host=" to already existing value.

Ex:
CMAKE_GENERATOR_TOOLSET:INTERNAL=host=x86

if above value is already present, I make the change in CMakeCache using Edit CMake Cache(UI) option and saving it will result in below statement in CMake cache file

CMAKE_GENERATOR_TOOLSET:INTERNAL=host=host=x86.

This will result in the error while configuring the project like below:
[cmake] CMake Error: Error: generator toolset: host=x86
[cmake] Does not match the toolset used previously: host=host=x86

I had to manually edit the CMakeCache file again, to have the correct value and configure again.

### Expected:

it should should prefix the value on every Save!

**Comment by bobbrow** [comment]
Thank you for reporting this.  I think we have enough information to investigate.  We'll let you know if we need anything else.

**Comment by andreeis** [comment]
We almost have CMake Tools 1.6.0 release out the door. Until then, if you want, you can also verify if this problem has been fixed correctly by installing the vsix built here: https://github.com/microsoft/vscode-cmake-tools/actions/runs/557242002#artifacts.
