### ISSUE TITLE
A small Chinese localization problem

### ISSUE THREAD

**Issue by Demonese** [microsoft/vscode-cmake-tools#1617]
### Brief Issue Summary

![image](https://user-images.githubusercontent.com/57629614/104594348-fd0fce80-56ab-11eb-8c59-6610389e4b30.png)
![image](https://user-images.githubusercontent.com/57629614/104594371-05680980-56ac-11eb-9474-9f5c07f84ec3.png)

### Expected:

should show `名称` or `键`, not `密钥`, because in Chinese `密钥` is similar to a password or the key to the lock.

**Comment by andreeis** [comment]
Thank you for opening this report. We will let you know if we need anything else in order to fix it.
