### ISSUE TITLE
No clang kits detected on Gentoo Linux due to issue with version regex

### ISSUE THREAD

**Issue by falbrechtskirchinger** [microsoft/vscode-cmake-tools#1622]
### Brief Issue Summary

When scanning for kits on a Gentoo Linux system, no clang kits are found.

### Expected:

clang binaries in PATH should be picked up by "Scan for Kits".

### Apparent Behavior:

Log indicates the binaries are probed, but rejected, because no version number can be matched in the output.
The version regex expects the version number to be followed by white space or a dash, which is not the case here.
Example output:
```
$ clang -v
clang version 12.0.0
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/12/bin
(snip)
```

### Platform and Versions

Gentoo Linux
Clang 11 and 12 (recent git build)

### Other Notes/Information

Fixed by #1620

**Comment by andreeis** [comment]
Thank you for investigating this problem and for the fix. We'll review the PR soon and we can include it in the next release. We are wrapping up another project. Thank you for your patience as we catch up with the PRs and high severity bugs.

**Comment by andreeis** [comment]
We almost have CMake Tools 1.6.0 release out the door. Until then, if you want, you can also verify if this problem has been fixed correctly by installing the vsix built here: https://github.com/microsoft/vscode-cmake-tools/actions/runs/557242002#artifacts.
