### ISSUE TITLE
Use version 5 of cpptools-api

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cmake-tools#1624]
- Use version 5 of cpptools-api https://github.com/microsoft/vscode-cpptools-api/pull/36
- Use new IntelliSense modes of cpptools.

**Comment by lygstate** [comment]
Will this be part of 1.7.0？

**Comment by bobbrow** [comment]
Unfortunately, no.  It will miss 1.7.0 but we could consider doing a follow up 1.7.1 with it.  We expect there may be some feedback from CMakePresets in 1.7 that would also be assigned to 1.7.1.
