### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by amir4z** [microsoft/vscode-cmake-tools#1625]
### Expected:

1. Push button
2. Thing happens

### Apparent Behavior:

1. Push button
2. Nothing happens

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: 
- **CMake Version**: 
- **VSCode Version**: 
- **CMake Tools Extension Version**: 
- **Compiler/Toolchain**:

**Comment by andreeis** [comment]
Was this issue created by mistake? We'll wait for the details for a few days, then close it if no update will be provided.
