### ISSUE TITLE
Request: Sort CMake Project Outline contents alphabetically

### ISSUE THREAD

**Issue by andrewmcdonald-oxb** [microsoft/vscode-cmake-tools#1631]
### Brief Issue Summary

The CMake Project Outline pane doesn't sort items alphabetically, which makes it painful to use in large codebases. Could this be sorted by default? Perhaps with a toggle option, if it's desired to see the order the targets and folders were parsed in (assuming this is what we have now).

### Expected:

1. Configure a folder with many targets in sub-folders
2. Visit CMake Project Outline pane
3. Folders and targets should be in alphabetical order

### Platform and Versions

- **Operating System**: macOS Catalina 10.15.6
- **CMake Version**: 3.18.4
- **VSCode Version**: 1.52.1
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: Ninja 1.10.2, Apple Clang 11.0.3

### Other Notes/Information

The folders are also all expanded by default which I don't find particularly helpful when there are many, but at least there's the "collapse all" button.

**Comment by andreeis** [comment]
Thank you for your feature idea. We may no be able to implement it right away, but we will consider for the future. Until then we will also track the community reactions to determine where this might fit into our backlog.

**Comment by andrewmcdonald-oxb** [comment]
This is still a valid request IMO - the folders and targets in the CMake panel are still not sorted alphabetically, which is the natural way to view such things. @andreeis any idea where this might fit in the backlog? I'd help but I wouldn't know where to start. I'd guess it's quite trivial to simply sort items in a tree view.

**Comment by gcampbell-msft** [comment]
@andrewmcdonald-oxb Thanks for following up and expressing interest. 
@snehara99 FYI as it relates to side views. 

Currently we don't have this work planned for the next release, but we'd be happy to take it into account and consider it in future planning. However, we often use the number of thumbs-up reactions to determine how many customers are desiring a certain bug fix or feature. Please upvote this issue to help it gain traction. 👍

**Comment by andrewmcdonald-oxb** [comment]
@gcampbell-msft has this been done somewhere in the background? Things look to be sorted alphabetically now, but I don't know if that's just coincidence in my project.

**Comment by gcampbell-msft** [comment]
@andrewmcdonald-oxb I don't see any PR that explicitly fixed it, but I guess it is possible that somewhere in the background it got fixed.

@mrbald I see that you've liked the original issue, could you confirm whether this has been fixed for you as well?

@andrewmcdonald-oxb If we don't hear any different, I think if it's fixed for you we can assume it's fixed, and you can feel free to close the issue. I'll wait to hear from you or @mrbald to confirm that it's fixed.

**Comment by andrewmcdonald-oxb** [comment]
It seems to have remained in alphabetical order for several versions/months now, so I assume it was fixed at some point. Perhaps deeper code diving/history archaeology would reveal when the fix came in, but I wouldn't know where to start. I'll close this off now (might pop in another request for the folders to start collapsed instead of expanded, but that's something else...)
