### ISSUE TITLE
Add support for Ctrl + Click Go to definition for functions and macros

### ISSUE THREAD

**Issue by gudnimg** [microsoft/vscode-cmake-tools#1634]
When I define a function or macro in `.cmake` or `CMakeLists.txt` file I cannot use `CTRL + Left Click` to see the function definition. I am specifically thinking of this: https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

I didn't find a similar issue for this.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**:  3.19.3
- **VSCode Version**: 1.52.1
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: GCC for x86_64-linux-gnu 9.3.0

### Other Notes/Information

I am using WSL on Windows. (Ubuntu 20.04)

**Comment by andreeis** [comment]
Thank you for this feature request. Currently, language service features for the CMake language are not on our road map. 
We will gladly accept help from the community for this.
Here's a similar GitHub report that is also about CMake langauge services: https://github.com/microsoft/vscode-cmake-tools/issues/534.
You can also check out https://marketplace.visualstudio.com/items?itemName=twxs.cmake.

**Comment by GunZi200** [comment]
Thanks for the reply, I have twxs.cmake installed and it doesn't support this either. https://github.com/twxs/vs.language.cmake the repo hasn't been updated in 15 months and has numerous syntax highlighting issues.

**Comment by andreeis** [comment]
I understand. I hope we'll have resources to address this scenario as well at some point. Until then, maybe someone in the community will step up.

**Comment by Zingam** [comment]
@andreeis Do you have any plans to integrate twxs functionality in this extension?

**Comment by andreeis** [comment]
Integration not yet, but we are currently testing a change that would cause the twxs extension to be recommended by VSCode when opening CMake projects, same way CMake Tools is recommended.

**Comment by benmcmorran** [comment]
Closing as covered by #93 which is on our upcoming roadmap.

**Comment by MiKom** [comment]
Shouldn't this be reopened? LSP is integrated but AFAIU, ctrl+click wasn't implemented.
