### ISSUE TITLE
Visibility of roadmap

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#1636]
Sorry if this is the wrong place to raise this, but I don't know where else to do so.  It seems quite hard to get visibility of the cmake-tools roadmap and there is very little commentary about the project from Microsoft (the latest blog post I found on Microsoft DevBlogs was February 7, 2020).

Would it be possible to have more communication about the progress of the project and its roadmap?

**Comment by DavidA2014** [comment]
Decided to close this issue as it is perhaps inappropriate.

**Comment by bobbrow** [comment]
Hi @DavidA2014.  Thank you for the suggestion.  It's a fair question to ask.  We probably haven't been as clear as we could be.

I think adding a roadmap to the repository could help, for sure.  I'm not sure if you've seen our Projects and Milestones, but we've tried to keep this repository at least tagged with information about the issues we're looking at for the next release.  We sometimes miss the estimates in the milestones by a bit depending on the circumstances, but our general strategy is to do an official release every 3 months.  Recently, we added Actions to the repository which build a "pre-release" version of CMake Tools that can be downloaded and installed after any given PR is completed.  At some point we'll use this for an "insiders" program for developers who want more frequent releases.

We should be blogging about our releases though, and I'll make sure we put that on our release checklist.

**Comment by bobbrow** [comment]
And for additional context, the developers who work on this repository also work on cpptools and the yet to be released Makefile Tools extension, so depending on the workload, we spend more or less time in this repository.  We're currently behind on accepting PR's here because of work we've prioritized in other extensions, but we're hoping to wrap up some of that and get this repo cleaned up again.

**Comment by DavidA2014** [comment]
Hi @bobbrow Thanks for your reply. Great to hear that development on this extension is still active. Looking forward to the next release.

**Comment by Zingam** [comment]
@bobbrow The same question was bothering me fora while now and I was about to write it. I am not sure even if it needs to be closed as inappropriate or keep it open as a place for a discussion.

I started using Visual Studio Code + C++ + CMake on Mac for Mac/Linux development in a professional setting full time recently so the state of the workflow is very dear to me right now.

This project needs the most modern C++/Objective C/Swift and Python in one package.
The project also requires building Linux targets in docker containers or other VMs. (I haven't yet explored that part VS Code's support.)

I don't have much to complain about the C++ extension. I really like that Visual Studio Code has now a super extension that combines multiple extensions related to C++.

I however feel that CMake support is lagging. There are a few new CMake features I'd like to see. And generally I'd like VSCode to have unified experience with Visual Studio.

**Comment by bobbrow** [comment]
> I however feel that CMake support is lagging. There are a few new CMake features I'd like to see. And generally I'd like VSCode to have unified experience with Visual Studio.

Which features in particular would you like to see?  We will be working on support for CMakePresets in 1.7.  I am estimating that we will only have capacity to do one major feature per release.  We have relied on the open source community for quite a few of the other recent features (e.g. cmake-file-api, status bar)

**Comment by DavidA2014** [comment]
CMakePresets support would be great 👍.

**Comment by Zingam** [comment]
@bobbrow Thank you about planning to implement the presets. This is one of the top features for me.
But also the project outliner. It doesn't even seem to work on Windows right now. For some strange reason it is empty:
![image](https://user-images.githubusercontent.com/3337419/106501129-5dd04100-64cb-11eb-8c6f-690041bdf38d.png)
Also I'd like to see install targets, including "install and debug" feature. I think that's important if you have *.dlls.

**Comment by andreeis** [comment]
Thank you for the feature ideas reminders. We will think how to better wire together the install and the debug features.
Regarding the project outliner, I am not able to reproduce the empty view. Please open a new report and give more details so that we can see the same symptom on our side.
