### ISSUE TITLE
Configuration Command Includes Unremovable Options

### ISSUE THREAD

**Issue by ChrisThrasher** [microsoft/vscode-cmake-tools#1639]
### Brief Issue Summary

It is not possible to not specify a CMAKE_BUILD_TYPE. More generally, CMake Tools appends many options to the `cmake` invocation that cannot be removed.

### Expected:

Allow configuration commands as simple as `cmake ..` from the build/ directory.

### Apparent Behavior:

Configuration commands include many more flags and typically look something like

```
/usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -H/Users/Thrasher/Projects/timecard -B/Users/Thrasher/Projects/timecard/build -G "Unix Makefiles"
```

without any way to remove these options and flags.

This becomes a problem on projects that require that users do not specify CMAKE_BUILD_TYPE.

### Platform and Versions

- **Operating System**: macOS 10.15.7
- **CMake Version**: 3.17.3
- **VSCode Version**: 1.52.1
- **CMake Tools Extension Version**: v1.5.3
- **Compiler/Toolchain**: Apple Clang version 12.0.0

**Comment by ChrisThrasher** [comment]
If this much complexity is in fact necessary then I apologize for my misunderstanding.

**Comment by andreeis** [comment]
Thank you for opening this report. We may look into implementing a possibility to remove the configure arguments sometime in future. We want to track the community reactions to this idea in order to correctly identify the priority in our backlog.

Regarding CMAKE_BUILD_TYPE, can you overwrite it to an empty string via settings cmake.configureSettings or cmake.configureArgs? Or by changing the cache variable entry (directly in CMakeCache.txt or with the command "CMake: Edit CMake Cache (UI)"?

**Comment by ChrisThrasher** [comment]
> can you overwrite it to an empty string via settings cmake.configureSettings or cmake.configureArgs?

I tried adding `-DCMAKE_BUILD_TYPE=""` to configureArgs but it appeared before the autogenerated `-DCMAKE_BUILD_TYPE:STRING=<some build type>` so I think the latter takes precedent.

```
[proc] Executing command: /usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE="" -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/local/bin/gcc-10 -DCMAKE_CXX_COMPILER:FILEPATH=/usr/local/bin/g++-10 -H/Users/Thrasher/Projects/serenity -B/Users/Thrasher/Projects/serenity/Build -G Ninja
```

> Or by changing the cache variable entry (directly in CMakeCache.txt or with the command "CMake: Edit CMake Cache (UI)"?

This didn't appear to fix the problem either.

**Comment by andreeis** [comment]
Thank you for pointing to a repo that is directly impacted by the impossibility to have an empty CMAKE_BUILD_TYPE. We'll look into fixing this.

**Comment by kleinesfilmroellchen** [comment]
I have the same issue with the same project, and other VSCode users in the SerenityOS developer community appear to struggle with it as well.
