### ISSUE TITLE
Incorrect target displayed in vscode status bar on startup

### ISSUE THREAD

**Issue by slgoldberg** [microsoft/vscode-cmake-tools#1649]
### Brief Issue Summary

When starting or loading a `vscode` project with `vscode-cmake-tools` enabled and shown in the `vscode` Status Bar at the bottom, the "active target" display always starts out as "`[all]`", even though a more specific target may have been saved/restored after project load (and will thus be applied if user presses the "`Build`" action in the Status Bar).

### Expected:

1. With `vscode-cmake-tools` displaying status in the `vscode` Status Bar:
2. click the target in the status bar to change it from e.g. "`[all]`" to e.g. "`[install]`".
3. Save project and window state and quit `vscode`.
4. Open `vscode` again, and load prior project and window state (if not already loaded automatically, depending of course on how you started `vscode`).
5. CMake "active target" *should* display in Status Bar as "`[install]`" since that's the actual active target. (See below.)

### Apparent Behavior:

In step _5_ above, CMake status instead displays as "`[all]`".  However, upon clicking on the active target field in the status bar, the status is immediately updated to reflect the *true* state of the active target, i.e., "`[install]`" in the example sequence above.

This is very confusing because it appears that pressing the "`Build`" action on the status bar will run `CMake` (for target `all`) -- however, it will in fact run `CMake install`, which is clearly a different result than just `CMake` (`all`).

This is evidently a *display* issue, not a state-restoring issue, as the active target is correctly restored from the previous session as `install`, but the control doesn't indicate such!

*Note: upon clicking the `Build` action, the status *does* in fact change from "`[all]`" to "`[install]`" immediately (without the user having to click on the active target field directly), the very first time the user clicks it.*

1. Open `vscode` after having previously set the active target to "`[install]`" per above steps.
2. Observe immediately after the project is loaded, that the active target is incorrectly displayed as "`[all]`".
3. Clicking the target *or* clicking `Build` will immediately refresh the state of the target displayed to "`[install]`". (Though of course, the user may not have meant to do an `install` since they didn't see that indicated at the time they clicked `Build` in the latter case.)

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.18.4
- **VSCode Version**: 1.53.0
- **CMake Tools Extension Version**: 1.5.3
- **Compiler/Toolchain**: Clang 12.0.0

### Other Notes/Information

I don't believe this is macOS-specific, though I have not verified this on other platforms. It seems like just an update bug for the initial state of the control in the `vscode` status bar UI as implemented by the `vscode-cmake-tools` plugin.

**Comment by andreeis** [comment]
Thank you for reporting this problem. I reproduce the wrong status bar label but only when no configure process is done. Do you have configureOnOpen set to false?
When you build, if no configure was run already, it will be performed before the build so that's why the status bar label is updated.
Even so, it's still a bug and we will address it. Just note that if your project configures immediately after being opened you won't see the inconsistency.

**Comment by gcampbell-msft** [comment]
@slgoldberg Please use the workaround to configureOnOpen. Please let us know if you're still facing issues. Closing this. Thanks!

**Comment by slgoldberg** [comment]
Thank you for taking a look at this!

Yes, that's correct, I did have "configureOnOpen" set to false -- I don't
recall ever doing that, but it's definitely true. Maybe it was because I
adopted this very early on, and something was broken back then. Who knows.

Anyway -- I modified my settings to change configureOnOpen to true, and I
believe this works correctly. Thanks again.

  Steve
