### ISSUE TITLE
Can the error parser be used in vscode outside of the extension?

### ISSUE THREAD

**Issue by vakokako** [microsoft/vscode-cmake-tools#1658]
This extension has a very nice error parsing, even putting template errors in a tree in `Problems view`!!

Unfortunately, I can't use it for build. Is there any way to provide this same nice error parsing outside, maybe with vscode tasks and `gcc` problem matcher?  Or maybe created as a separate problem matcher?

Thanks.

**Comment by andreeis** [comment]
Thank you for the question. Unfortunately no, what CMake Tools is doing is more than just regular expressions, there is also a lot of type script programming hooked up here and there. I can't think of a way to easily use that functionality outside of the extension.
