### ISSUE TITLE
Clean Rebuild suddenly doesn't work

### ISSUE THREAD

**Issue by WWology** [microsoft/vscode-cmake-tools#1659]
### Brief Issue Summary
When i Execute `CMake: Clean Rebuild` from VSCode, usually it works, but suddenly it's not working anymore

### Apparent Behavior:
[main] Building folder: Tutorial clean
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /home/wwology/School/CSCI336/Tutorial/build --config Debug --target clean -Wno-dev --
[build] Error: Building 'clean' and other targets together is not supported.
[build] Usage: cmake --build <dir> [options] [-- [native-options]]
[build] Options:
[build]   <dir>          = Project binary directory to be built.
[build]   --parallel [<jobs>], -j [<jobs>]
[build]                  = Build in parallel using the given number of jobs. 
[build]                    If <jobs> is omitted the native build tool's 
[build]                    default number is used.
[build]                    The CMAKE_BUILD_PARALLEL_LEVEL environment variable
[build]                    specifies a default parallel level when this option
[build]                    is not given.
[build]   --target <tgt>..., -t <tgt>... 
[build]                  = Build <tgt> instead of default targets.
[build]   --config <cfg> = For multi-configuration tools, choose <cfg>.
[build]   --clean-first  = Build target 'clean' first, then build.
[build]                    (To clean only, use --target 'clean'.)
[build]   --verbose, -v  = Enable verbose output - if supported - including
[build]                    the build commands to be executed. 
[build]   --             = Pass remaining options to the native tool.
[build] Build finished with exit code 1

This is the error message

I'm confused as to why this is happening

**Comment by andreeis** [comment]
Does this happen in the terminal, outside the context of the extension?
What version of cmake you have installed? What OS system?
With a quick try I didn't reproduce this but there are more situations of repro to explore.

**Comment by WWology** [comment]
Hi there, this happen in the extension on the command pallete, 

CMake Version: 3.19.4
OS is Pop_OS 20.04

**Comment by andreeis** [comment]
We also need to know if the same cmake command works or no in the terminal, because it might be a symptom of CMake itself and not of the extension.
Then, if you notice anything that is different than before with the command line as the extension generates it, let us know. Was it always like this?
[proc] Executing command: /usr/local/bin/cmake --build /home/wwology/School/CSCI336/Tutorial/build --config Debug --target clean -Wno-dev --

**Comment by WWology** [comment]
Tried executing the same command from the terminal. This is the result. Seems like it's a problem from CMake itself
```
Tutorial on  main [!?] via 喝 v3.19.4 
❯ /usr/local/bin/cmake --build /home/wwology/School/CSCI336/Tutorial/build --config Debug --target clean -Wno-dev --  
Error: Building 'clean' and other targets together is not supported.
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --parallel [<jobs>], -j [<jobs>]
                 = Build in parallel using the given number of jobs. 
                   If <jobs> is omitted the native build tool's 
                   default number is used.
                   The CMAKE_BUILD_PARALLEL_LEVEL environment variable
                   specifies a default parallel level when this option
                   is not given.
  --target <tgt>..., -t <tgt>... 
                 = Build <tgt> instead of default targets.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --verbose, -v  = Enable verbose output - if supported - including
                   the build commands to be executed. 
  --             = Pass remaining options to the native tool.
```

**Comment by andreeis** [comment]
Do you remember if this was the same command before when it worked or the extension added a tweak that also causes this? Can you experiment a bit with that command line in the terminal, maybe remove the last argument or move it earlier.... I would do this myself but this works for me (I also can install a newer cmake later to verify). If you also happen to have an older cmake somewhere else (or quickly install there an older one) and try it would also confirm this theory, before we end up opening a bug report to CMake.

**Comment by WWology** [comment]
Hi, i don't remember what commands were passed to cmake before it breaks. But i've always used the same command and it works. I've also tried removing the last argument or switching it up. it doesn't work.

**Comment by andreeis** [comment]
Ok, thanks for the follow up. Did you open a bug against the CMake repository?

**Comment by WWology** [comment]
Not yet. I had thought you already opened a bug issue there

**Comment by andreeis** [comment]
Ok we will. I was double checking you didn't so that we don't create a duplicate un-necessarily. Will follow up with the link of the report.
