### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by frisky1985** [microsoft/vscode-cmake-tools#1665]
- Issue Type: `Bug`
- Extension Name: `cmake-tools`
- Extension Version: `1.5.3`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.53.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bobbrow** [comment]
There is no actionable information in this issue.  If you could please summarize the problem you are experiencing and include any relevant data we will be happy to investigate.  Thank you!
