### ISSUE TITLE
When "cmake.useCMakeServer" is `true` the Visual C++ debugger isn't used

### ISSUE THREAD

**Issue by Som1Lse** [microsoft/vscode-cmake-tools#167]
I am using `ninja` as the build system. I am not sure what other info would be relevant, but feel free to ask if there is something more you need.

**Comment by bobbrow** [comment]
I am unable to reproduce the problem.  If you are still having a problem with this, please reply with more information about your workspace/configuration.

Thank you!

**Comment by Som1Lse** [comment]
This bug is over 2 years old. I believe it was fixed relatively shortly after, but never marked as such. Either way, I don't have it now.

**Comment by bobbrow** [comment]
Thanks for confirming.  Maintenance of the extension recently passed to us and we are starting to go through the issues and clean up the older ones.
