### ISSUE TITLE
How to perform a Release build when using VS2019 generator

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/vscode-cmake-tools#1673]
I just want to ask a quick question here, how can I perform a Release build in CMake with cmake-tools?  I did some research online but did not find any. Is there a way to do it or it's currently not supported.

**Comment by andreeis** [comment]
On the status bar, there is a button which defaults to "Debug", if you press it (or run the command "CMake: Select Variant" from the pallette), you should see a quick pick selection with the items Debug, Release, MinSizeRel and Rel WithDebInfo. Do you confirm this is the case?

**Comment by rustedwizard** [comment]
@andreeis Thanks for your answer, that's exactly what I am looking for!
