### ISSUE TITLE
Fine tune the focus of the output channel

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#1675]
For someone wishing to remain more in the Problems tab for example, the build is causing the output channel to get in focus too often. This focus is needed to bring attention to whatever happens but we can fine tune a few critical moments in the build when a focus switch would be necessary.

**Comment by anders-wind** [comment]
Is it possible to somehow stop this extension from stealing focus ever? Can it be added as an option as part of this PR?
