### ISSUE TITLE
integratedTerminal not working using cmake & nmake

### ISSUE THREAD

**Issue by KochC** [microsoft/vscode-cmake-tools#1677]
I used a Makefile with `nmake` in the past and the Debugging worked fine using the `integratedTerminal`. Now I switched to `CMake` and can build the project correctly. But the standard outputs are not in the `integratedTerminal` anymore. It does not even open automatically anymore.
```
"console": "integratedTerminal"
```
If I switch to `externalTerminal` or `internalConsole` the `std::cout` is shown.

In my `Makefile`is used `-7Z` to build a `debugger` version. In my new `CMakeLists.txt` I use `set(CMAKE_BUILD_TYPE Debug)`.

**Comment by andreeis** [comment]
I just tried a simple project (created with quick start command), on Windows, with VS2019 amd64 kit, VS generator, console=integratedTerminal (in launch.json) and I do see the output of std::cout in the terminal tab in VSCode.
Help us narrow down and reproduce your symptom. What OS, kit, generator... Does it happen the same with a simple project you create from scratch with quick start?

**Comment by KochC** [comment]
Ok i found out that it is not related to CMake, it also happens if I use nmake itself. In the newest release of `VSCode Insiders` the bug is not there. 
I made a new project with minimal settings. But I get the same issue, `integratedTerminal` is not opening
[https://github.com/KochC/vscode-integratedterminal-test](https://github.com/KochC/vscode-integratedterminal-test)

**Comment by andreeis** [comment]
What do you mean that in the latest VSCode Insiders the bug is not there. Do you have a problem with the integrated terminal for that version or not?

**Comment by KochC** [comment]
Well I use this `newest` version of VSCode.
```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042 
```
I don't really know what the difference between `VSCode` and `VSCode Insiders` is. They have different logos.
Sorry maybe I am in the wrong repository then.

**Comment by andreeis** [comment]
No worries, we'll help you redirect. But I still don't understand. If you have a version with the bug and a version without the bug it will help us investigate (or pass the info along). Do you confirm that there is a version of VSCode that is seeing the integrated terminal and output sent there? I am asking because you wrote "In the newest release of VSCode Insiders the bug is not there." in your second reply.

**Comment by KochC** [comment]
Yes. So I use the Version `1.53.2 of VSCode` where the bug is present and I basically can not debugg using the `integratedTerminal`. But I also installed the newest version of `VSCode Insiders 1.54.0` to test. In this version, the terminal works.
Is `VSCode Insiders` a newer version of VSCode? Or a prerelease? If so I guess the bug is fixed already.

**Comment by andreeis** [comment]
Great, most probably is. Adding @WardenGnaw from the debugger team to confirm.

**Comment by KochC** [comment]
after more tests and upgrading my extensions in VSCode Insiders the issue also affects this version. I guess it is an extension issue. I keep you updated.

**Comment by KochC** [comment]
The issue is caused by the newest releas of `ms-vscode.cpptools`.
Version `ms-vscode.cpptools v1.2.0` works fine.

After changing the version back to `1.2.0` `VSCode 1.53.2` as well as `1.54.0` are working perfectly.

**Comment by andreeis** [comment]
You're going to open a report in the CppTools repository?
