### ISSUE TITLE
Build task does not escape CMake path for PowerShell

### ISSUE THREAD

**Issue by benmcmorran** [microsoft/vscode-cmake-tools#1680]
### Brief Issue Summary

Tasks with `type` set to `cmake` and `command` set to `build` do not succeed on PowerShell when the path to CMake contains spaces (e.g. in Program Files). For example, create a simple CMake project on Windows with this `tasks.json`.

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "CMake build",
            "type": "cmake",
            "command": "build",
            "problemMatcher": []
        }
    ]
}
```

Ensure that `terminal.integrated.shell.windows` is set to PowerShell in `settings.json`. Attempt to run the build task.

### Expected:

CMake successfully starts to build.

### Apparent Behavior:

The build fails with this error:

```
> Executing task: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/repos/tools/deleteme/build --config Debug --target ALL_BUILD -- /maxcpucount:10 <

C:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ C:\Program Files\CMake\bin\cmake.EXE --build d:/repos/example/ ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command "C:\Program Files\CMake\bin\cmake.EXE" --build d:/repos/example --config Debug --target ALL_BUILD -- /maxcpucount:10" terminated with exit code: 1.
```

### CMake Tools Log

There is no output in the CMake/Build pane because the task routes output to a Terminal pane instead. That output is shown above.

### Developer Tools Log

No output.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.19.4
- **VSCode Version**: 1.53.2
- **CMake Tools Extension Version**: 1.6.0
- **Compiler/Toolchain**: Visual C++ 2019

### Other Notes

This issue is shell-specific. It does not repro when `terminal.integrated.shell.windows` is set to `cmd.exe`.

**Comment by andreeis** [comment]
Thank you for opening this report. I saw that and I was planning to open a report myself after playing more and understanding better when this happens and why. We will see how soon to fix this during our next triage meeting.

**Comment by elahehrashedi** [comment]
I am trying to make determine if this is a bug or not. 
By adding this option to your task definition (in tasks.json) you can run the task command correctly:

```
            "options": {
                "shell": {
                    "executable": "cmd.exe",
                    "args": [ "/c" ]
                }
            },
```

Here is a question, Do you have a specific reason that the task has to run on PowerShell? 
We are using a task provider from VsCode, that works fine on cmd. If users are using different terminals, they can add the mentioned option to their task definition to make sure the task is running without any issue. 

In cpptools extension, we have implemented a custom terminal to run the task commands on it 
(look at it here: https://github.com/microsoft/vscode-cpptools/blob/828589705d1fce13674b82090515a237784a9fd6/Extension/src/LanguageServer/cppBuildTaskProvider.ts#L337). 
My understanding is that this is more like a feature request. Let me know your thoughts on that.

**Comment by benmcmorran** [comment]
Manually specifying `cmd.exe` is the approach we're using right now to work around this issue on Windows. However, it's not ideal because by manually specifying `cmd.exe` in the configuration, the task no longer works on Linux. Ideally we'd be able to have a single cross-platform task configuration for CMake build.

If it seems difficult to get this working on PowerShell, another option would be to support [a `windows` key like built-in `shell` task type](https://code.visualstudio.com/docs/editor/tasks#_custom-tasks). If this pattern was supported on the `cmake` task type, we could selectively override the shell executable just for Windows and keep the task configuration cross-platform.

**Comment by elahehrashedi** [comment]
Thank you for your response. Currently, as we are using the TaskProvider from VsCode. So, there is not a quick way to provide this feature. However, we have a feature planned for the future which will cover this case. Please follow this feature from here:
https://github.com/microsoft/vscode-cmake-tools/issues/1656
