### ISSUE TITLE
Test explorer

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#1682]
Currently, the debugger can only lauch program without parameters,
And with ctest, we can specify parameters as much as possible,
So we'd better to add all possible ctest into debugger directly,
and the first parameter is the program to debug, we can checking
if the first parameter is an executable that's genreated by cmake, if that's ture
then add it to the debug list.

**Comment by andreeis** [comment]
If you use the CMake Tools command "CMake: Debug", the extension reads the setting "cmake.debugConfig.args" which is an array of string.
If you use the VSCode debugger command "Debug: Start Debugging" (or F5), VSCode will read "configurations[].args" from launch.json.

Is there something not properly working with this support? Are you suggesting additional functionality than what this args setting provides?

**Comment by lygstate** [comment]
> If you use the CMake Tools command "CMake: Debug", the extension reads the setting "cmake.debugConfig.args" which is an array of string.
> If you use the VSCode debugger command "Debug: Start Debugging" (or F5), VSCode will read "configurations[].args" from launch.json.
> 
> Is there something not properly working with this support? Are you suggesting additional functionality than what this args setting provides?

I am talking about ctest， this can preconfigure command line args in cmake file directly， without the need the config in vscode config， as we may have a large list of testing command

**Comment by bobbrow** [comment]
Have you tried this extension? https://marketplace.visualstudio.com/items?itemName=fredericbonnet.cmake-test-adapter

**Comment by lygstate** [comment]
> Have you tried this extension? https://marketplace.visualstudio.com/items?itemName=fredericbonnet.cmake-test-adapter

Looks good, is that proper to intergate these features into  vscode-cmake-tools?

**Comment by bobbrow** [comment]
We have talked about doing something like this, but it may be a while before we can get to it.  I'm going to rename the issue to cover it since I didn't find any others that appear to address this specifically.

**Comment by bobbrow** [comment]
The owner of the Test Explorer UI extension is working on getting the test UI moved into VS Code itself. 
https://github.com/microsoft/vscode/issues/107467

**Comment by Zingam** [comment]
@bobbrow Cool. Do you have any specific plans yet? I currently use gtest and the available 3rd party plugins. They mostly work but there is a lot to be desired. What I look forward in an IDE is always a Visual Studio-like experience. The VSCode set if *tools have really narrowed that gap lately. 

I hope that in the future a more tightly integrated and uniform debugging, testing experience with CMake/GTest/C++ could be achieved.
My current work environment is MacOS and Ubuntu 20.04 on VirtualBox. It is surprisingly good experience so far.

**Comment by bobbrow** [comment]
I haven't put this on our roadmap yet, but you should add a 👍 reaction to the first comment in this thread to help us prioritize it.

**Comment by Yanpas** [comment]
Test UI is finally built into vs code 1.59, I would be glad to see ctest support!
