### ISSUE TITLE
IntelliSense: cannot open source file

### ISSUE THREAD

**Issue by leungyauming** [microsoft/vscode-cmake-tools#1683]
### Brief Issue Summary

I'm using a Macbook.

I have installed Xcode, VSCode, C/C++, CMake Tools and CMake extensions.

But after I configure my folder with CMake Tools extension and include iostream.

It keeps showing "cannot open source file "wchar.h" (dependency of "iostream")".

I have tried to install the Xcode Command Line Tools (I have Xcode installed before trying Xcode Command Line Tools) but still the same.

### Expected:

1. Configure folder with CMake Tools extension
2. include iostream header
3. Should be no error

### Apparent Behavior:

1. Configure folder with CMake Tools extension
2. include iostream header
3. error with "cannot open source file "wchar.h" (dependency of "iostream")" is prompt 
4. install the Xcode Command Line Tools (tried Xcode before Xcode Command Line Tools)
5. error still presents

### CMake Tools Log

```
[variant] Loaded new set of variants
[kit] Successfully loaded 1 kits from /Users/{username}/.local/share/CMakeTools/cmake-tools-kits.json
[main] Configuring folder: {project_name}
[proc] Executing command: /usr/local/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -H/Users/{username}/Projects/cpp/{project_name} -B/Users/{username}/Projects/cpp/{project_name}/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /Users/{username}/Projects/cpp/{project_name}/build
```

### Platform and Versions

- **Operating System**: macOS Big Sur
- **CMake Version**: 3.19.5
- **VSCode Version**: 1.53.2
- **CMake Tools Extension Version**: 1.6.0
- **Compiler/Toolchain**: Clang 12

**Comment by leungyauming** [comment]
P.S. there are no problems with compiling but only IntelliSense, there are no errors for compiling

**Comment by andreeis** [comment]
Thank you for opening this report. Make sure you didn't dismiss the IntelliSense configuration provider popup that CppTools asks when you first load a C/C++ project built by CMake. Or verify that you have this in your project .vscode/settings.json
"C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools"

Next, let's see some logs. Run the command "C/C++: Log Diagnostics" while your VSCode has the C++ source opened. Paste the output in the "C/C++ Diagnostics" output channel.

Can you confirm if this happens for a simple project (create a new one with the command "CMake: Quick Start" and add "iostream" as a header in the "main.cpp" that's generated.

**Comment by leungyauming** [comment]
.vscode/settings.json:
<img width="565" alt="Screenshot 2021-02-24 at 8 01 07 AM" src="https://user-images.githubusercontent.com/50203211/108924880-85ec3380-7676-11eb-9a05-65a0f6c870a2.png">

logs:
<img width="1022" alt="Screenshot 2021-02-24 at 8 03 35 AM" src="https://user-images.githubusercontent.com/50203211/108925076-e5e2da00-7676-11eb-81a3-a51db82ec58a.png">
<img width="923" alt="Screenshot 2021-02-24 at 8 03 49 AM" src="https://user-images.githubusercontent.com/50203211/108925082-e8ddca80-7676-11eb-8319-cf01d8690b87.png">
<img width="983" alt="Screenshot 2021-02-24 at 8 03 59 AM" src="https://user-images.githubusercontent.com/50203211/108925088-eaa78e00-7676-11eb-94a1-5803f7f2b087.png">

CMakeLists.txt:
<img width="361" alt="Screenshot 2021-02-24 at 8 05 19 AM" src="https://user-images.githubusercontent.com/50203211/108925180-1296f180-7677-11eb-83fd-40ed6bf5ace1.png">

main.cc:
<img width="391" alt="Screenshot 2021-02-24 at 8 06 05 AM" src="https://user-images.githubusercontent.com/50203211/108925248-2e9a9300-7677-11eb-8425-3599a6a058f1.png">

**Comment by leungyauming** [comment]
I have gone into the std library headers and see if I can find anything interesting.
But in wchar.h, the IntelliSense just highlighted a line of code which I think there are nothing wrong.
<img width="763" alt="Screenshot 2021-02-24 at 8 08 52 AM" src="https://user-images.githubusercontent.com/50203211/108925592-e62fa500-7677-11eb-8e58-48dd5770fc42.png">

**Comment by andreeis** [comment]
Does it happen if main.cc is actually main.cpp?

**Comment by leungyauming** [comment]
It's the same, still the exact same error.
<img width="747" alt="Screenshot 2021-02-24 at 4 33 58 PM" src="https://user-images.githubusercontent.com/50203211/108972299-1d28a980-76be-11eb-956c-35c9c100ba2d.png">

**Comment by andreeis** [comment]
We fixed an issue like this in the CppTools extension: https://github.com/microsoft/vscode-cpptools/issues/6992. That fix is present in the insiders channel. Let us know if it doesn't work for you.
