### ISSUE TITLE
How to propagate settings in a workspace having multiple C++ projects?

### ISSUE THREAD

**Issue by kobalicek** [microsoft/vscode-cmake-tools#1687]
### Brief Issue Summary

I'm trying to create a workspace for multiple projects using cmake. My code-workspace looks like this:

```
{
  "folders": [
    {
      "path": "A",
      "settings": {
        "cmake.configureSettings": {
          "SOME_DEFINITION_IN_A": "VALUE"
        }
      }
    },
    {
      "path": "B"
    }
  ],
  "settings": {
    "cmake.buildDirectory": "${workspaceFolder}/build/${buildType}",
    "cmake.generator": "Ninja",
    "cmake.defaultVariants": {
      "buildType": {
        "default": "debug",
        "description": "The build type.",
        "choices": {
          "debug": {
            "short": "Debug",
            "buildType": "Debug",
          },
          "release": {
            "short": "Release",
            "buildType": "Release"
          }
        }
      }
    }
  }
}
````

However, when I configure project `A` the cmake invocation doesn't pass `-DSOME_DEFINITION_IN_A=VALUE` to cmake.

### Expected:

I would expect that `SOME_DEFINITION_IN_A` is passed to cmake when project `A` is configured.

### Platform and Versions

Linux, CMake Tools v1.6.0

- **Operating System**: Linux
- **CMake Version**: 3.18.4
- **VSCode Version**: 1.53.2
- **CMake Tools Extension Version**: 1.6.0

### Other Notes/Information

I'm not sure I'm using the workspace configuration properly. But I would expect that root settings would be read before folder settings and that folder settings would override root settings. Is there any other way of achieving what I had just described?

**Comment by andreeis** [comment]
Thank you for opening this report. An alternative is to define those settings in the .vscode/settings.json of each project folder. I verified and it works.
I am not sure if the scenario you describe (with the project settings being described in the workspace description file) is a bug or is by design. Indeed, I am not able to pass settings to the folders this way.
I'll dig more to identify if this is a bug and in the mean time you should be unblocked with my suggestion. Let me know if it doesn't work for you.

**Comment by kobalicek** [comment]
Hello,

thanks for the reply!

I can confirm that creating settings in each folder works, but then it kinda defeats the purpose of having multiple workspaces with multiple project configurations. For example I have a workspace for developing Project A, with one more project that I use as a playground, so I compile project A with tests, and my playground also uses project A, but without tests.

Then I have a different workspace having projects that use project A, so I still want project A in a workspace, but in general I don't want to have tests of A enabled in this workspace. I'm not sure how to fix this on my end without having a support for settings in `.code-workspace` file.

Anyway, thanks for a great extension!

**Comment by bobbrow** [comment]
Hi @kobalicek,

Unfortunately, it looks like the syntax you shared is not supported by VS Code.  I found [this document](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file-schema) which seems to suggest that you can't add settings to folders directly here.

I think it's actually a good feature idea and I would recommend you [open a feature request](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=feature_request.md) for the VS Code team.

Thanks!

**Comment by kobalicek** [comment]
Thank you guys.
