### ISSUE TITLE
CMake/Build output hyperlinks don't respect cmake.buildDirectory variable

### ISSUE THREAD

**Issue by mkucmpro** [microsoft/vscode-cmake-tools#1688]
### Brief Issue Summary

When I modify the `cmake.buildDirectory` variable (to enable out-of-source builds), the hyperlinks generated in the "Output" of "CMake/Build" don't work anymore.

### Expected:

1. Modify the `cmake.buildDirectory` variable by setting it to a path outside of the current source directory, e.g. `"cmake.buildDirectory": "${workspaceFolder}/../${workspaceRootFolderName}-buildtest/${buildType}"`
    * The idea is to have an out-of-source build directory, e.g. for "D:/test" it should be "D:/test-buildtest/Debug" 
2. Configure the project using CMake Tools
3. Click the link shown in the Output for "CMake/Build": 
![image](https://user-images.githubusercontent.com/73643378/109492591-7f512800-7a8b-11eb-8456-09372d1f7ad8.png)
At this point I expect a File Explorer to open in the given directory (which was just created)

### Apparent Behavior:

1. Following error message box appears:
![image](https://user-images.githubusercontent.com/73643378/109492793-c6d7b400-7a8b-11eb-873e-45650e2c9593.png)

### CMake Tools Log

```
[variant] Loaded new set of variants
[kit] Successfully loaded 9 kits from C:\Users\xyz\AppData\Local\CMakeTools\cmake-tools-kits.json
[main] Configuring folder: test 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_INSTALL_PREFIX:STRING=d:/test-install/Debug -Hd:/test -Bd:/test-buildtest/Debug -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is MSVC 19.16.27045.0
[cmake] -- The CXX compiler identification is MSVC 19.16.27045.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: D:/test-buildtest/Debug
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: Windows 
- **CMake Version**: 3.19.3
- **VSCode Version**: Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.14393
- **CMake Tools Extension Version**: v1.6.0
- **Compiler/Toolchain**: Visual C++ 2017

### Other Notes/Information

Repro: 
[test.zip](https://github.com/microsoft/vscode-cmake-tools/files/6061354/test.zip)

**Comment by andreeis** [comment]
Thank you for opening this report. I reproduce the problem and I suspect it is a VSCode bug. I am going to do some debugging and experimenting to make sure in what code base this issue fits in. I'll update you with what I find.

**Comment by andreeis** [comment]
This is not a CMake Tools bug. We recommend that you open a report in the VSCode repository on GitHub: https://github.com/microsoft/vscode/issues.
