### ISSUE TITLE
Problems with using gdb debugger on MAC

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#1691]
Opened from comment in report https://github.com/microsoft/vscode-cmake-tools/issues/884.

Zrealshadow commented 3 hours ago
I still face this problem in MacOS Catalina 10.15.4
And the cmake-tool verison is 1.6.0

When i try to debug,
the log is:
[build] Starting build
[proc] Executing command: /snap/cmake/current/bin/cmake --build /home/hristo/Projects/GitHub/GunBox/GunBox/GunBox/build --config Debug --target GunBox_Game -- -j 10
[build] ninja: no work to do.
[build] Build finished with exit code 0
[debugger] Unable to automatically determine debugger corresponding to compiler: /usr/local/bin/g++-8
[main] Failed to generate debugger configuration

My cmake tool setting:

    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
    "cmake.configureOnOpen":true,
    "cmake.debugConfig": {
        "stopAtEntry": false,
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/local/bin/gdb",
    }
Any solution to this problem ?

**Comment by andreeis** [comment]
This is not a CMake Tools bug. We recommend that you open a report in the VSCode repository on GitHub: https://github.com/microsoft/vscode/issues.

**Comment by andreeis** [comment]
Appologies, that text was meant for closing a different report, not this one.

**Comment by timoscs** [comment]
Is there any workaround for this at the moment?

**Comment by andreeis** [comment]
I am not sure it would work, but you can try to create an environment where lldb or lldb-mi would not be found in the path (hack the path environment variable). And also don't define miDebuggerPath (not an intuitive move, but I'm hoping it will go through a different code path that will enable you in the end to use gdb on mac).
We'll have a fix for this in 1.7 release and as soon as the fix is in I'll point you to a vsix to test (and unblock you) even earlier.

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.
