### ISSUE TITLE
"Configuring project" infinite loop

### ISSUE THREAD

**Issue by mpusz** [microsoft/vscode-cmake-tools#1704]
### Brief Issue Summary

Selecting a kit on a project without CMakeLists.txt opens:

![image](https://user-images.githubusercontent.com/506260/110124879-f0157e80-7dc2-11eb-9152-1256f299cf27.png)

When the `CMakeLists.txt` is manually added to a subdirectory in a project and selected with "Locate", the "Configuring project: Saving open files" message is not closed and remains in an infinite loop. This loop prevents CMake extension to work correctly. "CMake: Reset CMake Tools Extension State" is needed to make it work.

### Platform and Versions

- **Operating System**: WSL2 with Ubuntu or Ubuntu via Docker container (https://github.com/train-it-eu/workshop-tools)
- **CMake Version**: 3.19.0
- **VSCode Version**: 1.54.1
- **CMake Tools Extension Version**: 1.6.0
- **Compiler/Toolchain**: GCC 10.2.0

**Comment by andreeis** [comment]
Thank you for opening this report. We reproduce this problem and we will fix it. I am glad that you can be unblocked by a project reload.

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.
