### ISSUE TITLE
CMake/Launch Shell lacks any stdout

### ISSUE THREAD

**Issue by markusdd** [microsoft/vscode-cmake-tools#1705]
Hi, I've wasted like 2 hours now to understand why my tests seem to pass but there is no output whatsoever in the CMake/Launch shell.

I'm in a QT6 project on MinGW on Win10 and here is the difference:

CMake/Launch shell
![grafik](https://user-images.githubusercontent.com/25175069/110181288-bd43a880-7e0b-11eb-83d7-1372b2d2e79c.png)

bash
![grafik](https://user-images.githubusercontent.com/25175069/110181359-e5cba280-7e0b-11eb-88c9-ce6d8b203a28.png)

What is the reason for this and how can it be fixed? I was even inserting basic iostream std::out statements and absolutely nothing will print.
Using bash for calling manually is super inconventient, because I need to manually copy all generated dll's first.

**Comment by andreeis** [comment]
You can set your VSCode terminal to be bash. Go to the terminal window, open the combo box UI on the upper right of the terminal UI area, and experiment with "Select default shell" and "Configure terminal settings". I hope you will be able to select bash and get the behavior from your second snippet integrated in VSCode.

Then regarding the first snippet, what kind of terminal is that, usually we use cmd.exe on windows. If that is not displaying any output, can you double check from a similar terminal outside VSCode? We are trying to determine if that symptom could be a bug in VSCode terminal feature.

**Comment by markusdd** [comment]
Hi, there is some evidence, that this is a more widespread issue.

I noticed this when working on the appveyor.yml for the example above:
https://github.com/markusdd/qtcsv/blob/master/appveyor.yml

As you can see in the last line, to get meaningful output I have to call bash.exe. No matter if I use cmd or powershell, the output won't show.

Feel free to fork the example above and natively call the qtcsv_tests.exe instead of using bash.exe, you will see what I mean.

This is very, very odd. I have spend hours to understand why this is happening, but I gave up. with bash it works instantly.

**Comment by bobbrow** [comment]
Could you try what @andreeis suggested?  You can select the type of terminal you want VS Code to use.  Look here:
![image](https://user-images.githubusercontent.com/12818240/112047011-f4070780-8b09-11eb-9201-b1b671792b23.png)

**Comment by markusdd** [comment]
ah sorry I thought that was clear: it does not work with cmd and ps, it works with bash, just as in my appveyor example

**Comment by andreeis** [comment]
Yes, we understand. If you click the "Select Default Shell" option, it will open a quick pick UI for you to select which type of shell to use from now on. Then you can choose bash and next time VSCode will use bash instead of cmd.

**Comment by markusdd** [comment]
yes, that is what I am saying ;)

I can make it work using bash, but I do not consider this a real fix, as I think it should work cmd and ps as well.

Not a big issue for me personally right now, but it is nevertheless pretty confusing probably also for others.

**Comment by bobbrow** [comment]
We don't work on CMD or PS, so I'm afraid there's not much we can do for you in that respect.  If it works in a CMD or PS that is not embedded in the VS Code terminal (e.g. a standalone shell window), then this is a bug the VS Code team would need to investigate.

**Comment by markusdd** [comment]
I agree it seems to be a more widespread issue. I will comment if I find anything more.

Still, if anyone of you is willing to try you can use the linked qtcsv project above.

Simple CMake build, run the test suite and compare output for bash and cmd. Just to exclude it is something local that just affects me.

**Comment by Zingam** [comment]
Is this all related to the CMake extension or the C++ one or to VSCode itself?

On Linux when running and debugging the output goes to Terminal cppgdb and is nicely formatted. On MacOS the output goes to Debug Output and appears as raw string with additional "decorations" and maybe unreadable.
I haven't used Windows in a while with VSCode so don't remember the situation on Windows.

**Comment by seppeon** [comment]
I also have this issue.
Bash isn't really an option for everyone.

I also have mingw.
