### ISSUE TITLE
How do newly created files get added to build?

### ISSUE THREAD

**Issue by amirea** [microsoft/vscode-cmake-tools#1706]
I'm new to cmake tools and cmake in general and I'd like to know if I rename a file or add new files, do I have to manually edit/add them into CMakeLists.txt?
What's the procedure?

**Comment by bobbrow** [comment]
> if I rename a file or add new files, do I have to manually edit/add them into CMakeLists.txt?

Yes, currently CMake Tools doesn't attempt to manage the contents of CMakeLists.txt for you.  This is something we could investigate.  I know Visual Studio has some level of support for it.
