### ISSUE TITLE
CMake Tools is always in the installation state

### ISSUE THREAD

**Issue by Sunshine334419520** [microsoft/vscode-cmake-tools#1708]
Operating System : MacOS
CMake Version: 3.16
VSCode Version: newest

Remote Linux Developent for MacOS
Remote Linux Developent for MacOS
Remote Linux Developent for MacOS

CMake Tools is always in the installation state

**Comment by bobbrow** [comment]
We're glad you were able to resolve your issue.  Let us know if there's anything we can do to help.
