### ISSUE TITLE
Running cmake build scripts from IDE

### ISSUE THREAD

**Issue by sureshjoshi** [microsoft/vscode-cmake-tools#1709]
Is there currently any way to run CMake/CTest build scripts from the IDE directly? In my CI system, I've created a build.cmake file which uses the `ctest -S` command and it builds, tests, runs code coverage, etc.

In my day to day, I'd like to just build and test, or maybe occasionally build/test/coverage. I have scripts for all of these that I run from the terminal, but I was wondering if there was any way to speed up that workflow in the IDE.

I know there are some configuration parameters, but I would need to enumerate the various build scripts, then one of the IDE commands would need to run the selected script (or select and run the script). I haven't seen this functionality, but I'm not sure that it's not there either.

**Comment by bobbrow** [comment]
I think the documentation about [Custom Tasks](https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks) might be what you're looking for.  You can also bind [keyboard shortcuts](https://code.visualstudio.com/Docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks) to your custom tasks.

**Comment by sureshjoshi** [comment]
Thanks @bobbrow 
I'm back working on some C++ code, so I'll give this a shot and see how it works out and report back.
