### ISSUE TITLE
parse CMAKE_OSX_ARCHITECTURES before configuration or set x86_64;arm64 as default

### ISSUE THREAD

**Issue by mattetti** [microsoft/vscode-cmake-tools#1713]
### Brief Issue Summary

I'm working on a CMake project that is meant to compile for x64 and arm64 (intel and m1 macs). The CMake script contains 
`set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64" CACHE STRING "")` and I therefore expected my output to be built for those architectures. However, after running `lipo -info` on the output binary, I noticed it wasn't the case.

To fix the problem, I had to go into the extension settings and add the following argument when configuring: `-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64`

After doing so, I was able to properly compile my fat binary.

### Expected:

I somehow expected that the extension would detect the fact that I had defined the OSX architectures and the variable would be passed to the configuration. I do realize now, thinking about it, that this might not be trivial but it was my expectation.

Maybe, it might make sense to pass `-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64` by default on macOS since mac devs might expect to compile for both these days (and let those who don't, change that value in the configuration).

**Comment by andreeis** [comment]
As long as you define a CMake setting with "set" in CMakeLists.txt, I don't think you should need to use the extra -D arguments.
I don't know yet why your final binary is not as expected if you only rely on "set". If you do a clean configure and a clean build from a terminal (no VSCode extension) without providing the extra -D arguments, how is the final binary? This would help us identify if the problem relies in this extension or in CMake itself.

**Comment by wAuner** [comment]
I'm having the same issue with cmake on the terminal. I defined `set(CMAKE_OSX_ARCHITECTURES "x86_64;arm64")` and if I recall correctly, it worked as expected. But now when I try to build again (make generator) it gets ignored and builds only for one platform. If I use `cmake .. -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"` from the command line it builds a fat binary.
