### ISSUE TITLE
How to import existing project other than configure new one

### ISSUE THREAD

**Issue by timxx** [microsoft/vscode-cmake-tools#1718]
Say I configured a project outside of the source directory,  how can I import that one instead configure a new one?

I don't find any command to import. Because our project can't be built inside source tree, and have lots of cmake options to pass, it's not so easy to use the default configure profile.

**Comment by andreeis** [comment]
I am not sure I understand your scenario. If you can give more details about where is everything.
Where are you opening VSCode from? "Open Folder" on your code base sources root? We usually mean by "sourceDirectory" as the location of CMakeLists.txt. 
Also, how is the other outside project looking? Does that have source files too or only CMake scripts?
Do you happen to have this project on GitHub or can craft one easily?

Once VSCode opens a folder somewhere, it can always incorporate new independent projects with context menu "Add Folder to Workspace", if you R-Click on the file explorer area in VSCode.

**Comment by timxx** [comment]
The VSCode opened the source root that contains CMakeLists.txt, the build directory can be anywhere outside of the source tree, such as:
```
/workspace/project  --> VSCode opens this directory
/workspace/debug  --> the build directory contains a valid cmake build
/workspace/release --> for release build
```
I want to use the **/workspace/debug** and **/workspace/release** for /workspace/project, but it seems not possible.
Every time I make a build or configure, it just create another build directory in **/workspace/project**, and it fails to configure due to missing project specify options.

Use **Add Folder to Workspace** helps nothing

**Comment by andreeis** [comment]
Can you set "cmake.buildDirectory": "${workspaceFolder}/../${buildType}"? It should create and use the build folder from outside the workspace folder (which is /workspace/project, the location that is originally opened by VSCode).

**Comment by timxx** [comment]
The cmake.buildDirectory works, but it's still nice to have an option to import the existing builds. 

Now I have to set cmake.generator, cmake.configureSettings and cmake-kits.json to override the default settings. Such as ninja and compiler, specify CMAKE_CXX_COMPILER in cmake.configureSettings sections helps nothing.
Another problem is that I don't known how to configure different cmake.configureSettings for different buildType.

So if we can import those configures from existing builds directly, it can save us a lot of time. LoL

**Comment by andreeis** [comment]
Our next 1.7 release will support the presets feature that is described here:
https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html. 
Have a look at that CMake spec and let us know if you think it would cover all the scenarios that you need or if there is anything extra that wouldn't be supported even presets implementation.
