### ISSUE TITLE
Non-breakable space in VisualStudio displayName

### ISSUE THREAD

**Issue by x-santiaga-x** [microsoft/vscode-cmake-tools#1727]
### Brief Issue Summary

CMake Tools for VSCode uses Utf8 codepage while getting installed VisualStudio kit information. vswhere returns a kit description with a non-breaking space in displayName field between the name and the year (Visual Studio Community_ _2019). 
CMake: Build Directory set to '${workspaceFolder}/../build/${buildKit}'.
So buildKit gets into CMake keys and leads to the creation of a path containing non-breaking space. Some tools cannot work with such paths.

It might be worth converting strings that become filesystem paths so that they do not contain non-ASCI characters. 

### Expected:

Run CMake Configure with Visual Studio Community 2019 kit selected as 'Visual Studio Community 2019 Release - amd64'.
Expected 'build/Visual Studio Community 2019 Release - amd64' directory as build directory.

### Apparent Behavior:

Got 'build/Visual Studio Community\xC2\xA02019 Release - amd64' directory as build directory.

### Platform and Versions

- **Operating System**: Windows 7 (Windows_NT x64 6.1.7601)
- **CMake Version**: cmake version 3.19.20122902-MSVC_2
- **VSCode Version**: 1.55.0-insider (user setup)
- **CMake Tools Extension Version**: v1.6.0
- **Compiler/Toolchain**: Microsoft Visual Studio Community 2019 Version 16.9.2

**Comment by andreeis** [comment]
Thank you for opening this report. I do not have VS Community 2019 installed but with the "Enterprise Release - amd64" equivalent I am not able to get a bad build folder created.

Can you copy-paste the definition of the "Visual Studio Community 2019 Release - amd64" kit from your cmake-tools-kits.json? You can use the command "CMake: Edit user-local CMake kits" in the palette to have this file opened automatically in your current VSCode instance.

**Comment by x-santiaga-x** [comment]
That's it
```
  {
    "name": "Visual Studio Community 2019 Release - amd64",
    "visualStudio": "a24b7ebf",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "host=x64"
    }
  },
```
Here is the complete file [cmake-tools-kits.zip](https://github.com/microsoft/vscode-cmake-tools/files/6195111/cmake-tools-kits.zip) and vswhere output where nbsp first appeared [vswhere.txt](https://github.com/microsoft/vscode-cmake-tools/files/6195125/vswhere.txt)

**Comment by lygstate** [comment]
> Thank you for opening this report. I do not have VS Community 2019 installed but with the "Enterprise Release - amd64" equivalent I am not able to get a bad build folder created.
> 
> Can you copy-paste the definition of the "Visual Studio Community 2019 Release - amd64" kit from your cmake-tools-kits.json? You can use the command "CMake: Edit user-local CMake kits" in the palette to have this file opened automatically in your current VSCode instance.

Hi, it's because of using ${buildKit}, waiting for release 1.7 and not using ${buildKit} will resolve the issue

**Comment by andreeis** [comment]
Having your cmake-kits.json helped reproduce this issue. We will fix this.
