### ISSUE TITLE
add_custom_target with shell scripting that requires user interaction

### ISSUE THREAD

**Issue by ei06125** [microsoft/vscode-cmake-tools#1730]
Hello,

I have a CMakeLists.txt that has a add_custom_target with a COMMAND that runs a bash script.
The bash script prompts the user for a yes/no answer which is then sent upwards to the build execution.
It works on CLion and shell (bash/zsh).

Is that by design?

**Comment by andreeis** [comment]
Thank you for the idea. We will track the community votes to evaluate where this feature would fit in our backlog.

**Comment by TCB13** [comment]
> I have a CMakeLists.txt that has a add_custom_target with a COMMAND that runs a bash script.

Non related, can you share the `add_custom_target` part? I've been trying to do this with CLion without luck. Thank you.

**Comment by ei06125** [comment]
It was almost a year ago and I've since left the company so I don't have access to it anymore. And I haven't used it on my personal projects (yet).
