### ISSUE TITLE
Unable to perform CMake Quick Start

### ISSUE THREAD

**Issue by Kaszanas** [microsoft/vscode-cmake-tools#1733]
### Brief Issue Summary

Attempting to bootstrap new project with CMake Quick Start fails.

### Expected:

1. Use Quick Start feature to generate starting point of a project.
2. Have all of the files and a "hello world" starting point.

### Apparent Behavior:

1. Using Quick Start feature fails to execute with the following error

![image](https://user-images.githubusercontent.com/34846245/112774035-9d815800-9038-11eb-8f85-56adcf0b2e44.png)

This happens even though the workspace is empty and was opened in a new directory.

2. After opening a completely new workspace by closing the faulty one using instructions for closing workspaces derived from here (Ctrl + K, L) https://code.visualstudio.com/docs/editor/multi-root-workspaces the issue of "Unable to determine what CMake generator to use [...]" persists.

### CMake Tools Log

```
[variant] Loaded new set of variants
[kit] Successfully loaded 11 kits from C:\Users\kasza\AppData\Local\CMakeTools\cmake-tools-kits.json
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[main] Configuring folder: LCpp 
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.

```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: cmake version 3.20.0-rc4
- **VSCode Version**: 1.54.3 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8 x64
- **CMake Tools Extension Version**: 1.6.0

**Comment by Kaszanas** [comment]
While checking ```cmake.generator``` under User Settings. There is no default generator stated.

**Comment by andreeis** [comment]
I don't understand how the message "This workspace already contains a CMakeLists.txt" is possible when you invoke he quick start command in a new empty folder (which doesn't have that file present, maybe double check). Or does it happen that you set "cmake.sourceDirectory" (the setting used to track a CMakeLists.txt file) to some other folder where there is a "CMakeLists.txt" present? Double check your settings at the folder level, workspace level and user level (there are settings/preferences commands in the palette for all three cases).

Quick start works fine for me when invoked from a fresh new folder. Can you detail the steps that you are doing? Maybe a slight difference in the user scenario can trigger this and we'd be happy to fix it once we reproduce on our side. Maybe you do something special regarding a new empty workspace file (different than a new empty folder).

Just in case, do you see the same happening with one of our latest vsix (to confirm if it happened that we already fixed this, even if indirectly). Download the vsix from this linke and use the "Install from vsix" command in the palette.
https://github.com/microsoft/vscode-cmake-tools/actions/runs/687275647

**Comment by Kaszanas** [comment]
@andreeis 
If I remember correctly, the steps to reproduce could be as follows (I am not sure):
- Open a Visual Studio Code and initialize a project in a fresh folder (working fine) (Initializes workspace?)
- Delete all of the project files
- Open a new folder using the same VS Code instance by using "Open Folder" VS Code feature (outside of the scope of the old initialized project)
- Attempt to perform Quick Start using CMake Tools.
- Bug happens

The second thing is the generator problem which was probably due to the kit (Clang from LLVM for Windows) and the CMake Tools not being able to find any suitable generator?

I was unable to set up a full working environment for VS Code + CMake tools + Clang (from VS or from LLVM for Windows).
Scanning for kits works fine, building with VS Clang works fine, but then for the debugging CMake Tools is unable to find lldb (which seems not to be provided with Visual Studio release of Clang compiler). On the other hand when using LLVM for Windows, CMake Tools fails to find a suitable generator.

**Comment by andreeis** [comment]
I'll try those steps. In the meantime, can you try all again but without the first bullet (with loading a different valid project, deleting it, then opening a new folder from there...). Just open VSCode, load an empty folder (Open Folder menu command, avoid anything that says "workspace"), run quick start...

About the generator, until I figure out what's happening for your scenario, can you define "cmake.generator" to what you want? Maybe that will unblock you. More information on cmake generators: https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html.

**Comment by Kaszanas** [comment]
@andreeis 
At this point I am purely experimenting with C++ and this is not related to any particular project apart from me introducing myself to the language and its ecosystem.

I have managed to set everything up with g++ compiler, so I am good. I will try to experiment with setting up a proper generator for the Clang configuration and see if it will work.

**Comment by Kaszanas** [comment]
@andreeis
It seems that I am unable to reproduce the problem here on my part.
I would say that this issue has been resolved as it was probably some kind of one off bug, due to multiple different things being misconfigured.

I am closing this but if You feel that this is something worth investigating on Your part then feel free to re-open this.

**Comment by andreeis** [comment]
I am glad that you are unblocked. I don't think we need to reopen for the moment. We'll see first if others in the community encounter something like this (hopefully not).
