### ISSUE TITLE
Change the order of available kits such that folder kits come first

### ISSUE THREAD

**Issue by slietzau** [microsoft/vscode-cmake-tools#1736]
### Brief Issue Summary
Hey,
first of all, thanks for this awesome extension!

I'm developing on a Windows computer with several Visual Studio installations. `Scan for kits` finds a huge number of kits for all installations multiplied by the available target architectures. On top of that, I have LLVM installed because I use the clangd language server. In total there are almost 40 kits available.

We use project specific kits but they appear at the end of the list which is only reachable by scrolling down twi pages. It would be awesome if the order could be changed.

### Expected:
I would rank folder level kits 'more important' than user level kits because they are closer to the source. Therefore they should come before the user kits in the selection.

If backward compatibility is a concern, this behavior could be hidden behind a configuration setting.

### Other Notes/Information

This is the code in question:
https://github.com/microsoft/vscode-cmake-tools/blob/6f407d91cc08e8ac498b56c70e0169dfe1858a1e/src/kitsController.ts#L115

**Comment by bobbrow** [comment]
Great suggestion.  I don't see any issue with changing the order.

**Comment by bobbrow** [comment]
The fix for this was merged in.  If you want to preview the feature, you can download the VSIX from [here](https://github.com/microsoft/vscode-cmake-tools/actions/runs/709294313) and install it using the "Install from VSIX" command in VS COde.

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.
