### ISSUE TITLE
Initially select a target that is different from "all"

### ISSUE THREAD

**Issue by maddouri** [microsoft/vscode-cmake-tools#174]
Currently, after configuring the project for the first time or when opening an already-configured project, CMake Tools selects the "all" build target by default.

I would like to suggest that the extension selects the first target that is declared using `add_executable()` or `add_library()` instead of "all".

**Comment by ytimenkov** [comment]
But this is consistent with the default behavior of CMake and make: if you just run `make` it will build `all` target.
On the other hand CMake Tools select an executable as a launch target and build only it as prelaunch step.

**Comment by maddouri** [comment]
Sorry for the delay.

The cirrent behavior of the extension is indeed the same as make's.

In the case of make, (or any "build" tool) this makes perfect sense. After all, we use make to "build" a (potentially multi-sub-project) project and it's convenient if it builds all its sub-projects by default.

I would like to argue that, in the case of an "IDE" (or a code editor with IDE-like features, which VSCode is) it makes more sense to select a single target at any given time:
1. More often than not, when "editing" a multi-target project, I edit files that are specific to one suboroject (i.e. target) which I build immediately after saving my edits
2. For extensions (like CMake Tools Helper) that use this extension to set includes/defines in Microsoft's cpptools, (or other intellisense providers) it is not clear what to use as the current includes/defines if a "non-target" (e.g. "all") is selected. In the case of CMake Tools Helper, whent a non-target is selected, a "null" (i.e. empty, invalid...) configuration is passed to cpptools. This can be surprising to users when they load a CMake project for the first time.

Alternatively, it might be useful (at least to other extensions) if this extension provided an API for selectong the current target.

**Comment by dcourtois** [comment]
Hi, maybe this could be selected with a simple option, something like `"cmake.defaultTarget": "whatever"` ? This way the default option could still be `"all"` to follow the default CMake behavior, and it would still be easy for users to change their default target to what they want, right ?

**Comment by ytimenkov** [comment]
I would just remember last selected target and preserve across runs. Initially selected target doesn't really matter - it most likely will be wrong.

**Comment by maddouri** [comment]
@dcourtois sure! I would suggest somerhing like "cmake.defaultTarget": "all|first_parsed_target|whatever"

@ytimenkov yes, it would be great if the selected target were preserved across runs

How about combining both ideas?
* an option for configuring the default target during the first run
* preserving the currently selected target across runs
