### ISSUE TITLE
Unable to quick debug using mingw toolchain

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/vscode-cmake-tools#1745]
### Brief Issue Summary
Unable to quick debug using mingw toolchain.

### Expected:

Debug launched as expected.

### Apparent Behavior:

1. Quick start a hello world excutable.
2. Use GCC 10.2 toolchain to configure.
3. Launch the debugger
4. `Unable to open file`
![image](https://user-images.githubusercontent.com/42881734/113643278-93b6b080-9647-11eb-8d40-48c1a8151c4f.png)

It seems like the file path parsing error. If I click `Create`, it will create the file under `C:\c\User\...`, which is nonsense.

This issue only happens on MingW toolchain. Using visual studio toolchain is fine.
![image](https://user-images.githubusercontent.com/42881734/113643367-c791d600-9647-11eb-86b7-bc2dc40c7d8a.png)

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.20
- **VSCode Version**: 1.56
- **CMake Tools Extension Version**: 1.6.0
- **Compiler/Toolchain**: GCC 10.2 MSYS2 MingW

**Comment by HO-COOH** [comment]
Seems I messed up with the wrong `gdb` and `ld`. I remove all packages in `usr/bin` and reinstall those in `mingw64_x86_64...` packages, and it seems solved it.

**Comment by bobbrow** [comment]
We're glad to hear you were able to resolve your issue.  Let us know if you run into anything else.
