### ISSUE TITLE
MS JScript complains about cmake.js

### ISSUE THREAD

**Issue by tondach01** [microsoft/vscode-cmake-tools#1748]
### Brief Issue Summary

While trying to make a build .c file, the Microsoft JScript raises an error as it tries to compile the cmake.js file.

### Expected:

1. build directory made
2. cd build
3. cmake ..
4. make
5. build done

### Apparent Behavior:

1. build directory made
2. cd build
3. cmake ..
4. error (Windows Script Host):
    script: <user>\.vscode\extensions\twxs.cmake-0.0.17\out\src\cmake.js
    line: 5, column: 57, error: identifier expected
    code: 800A03F2, source: Microsoft JScript - compilation error
(please excuse me if it's not accurate, translating from Czech)

### Platform and Versions

- **Operating System**: Windows 8.1
- **CMake Version**: 3.20.0
- **VSCode Version**:  1.55.0
- **CMake Tools Extension Version**: 1.6.0
- **Compiler/Toolchain**: GCC 6.3.0

**Comment by andreeis** [comment]
Thank you for opening this report. We are not able to reproduce this problem. Also, we've never seen cmake being invoked via twxs. Where is your cmake.exe invoked from? Let us know the output of "where cmake" when run from the terminal in which you reproduce those steps. For example, in my case is C:\Program Files\CMake\bin\cmake.exe.

**Comment by tondach01** [comment]
Thank you for answer. Weird thing is that "where cmake" returns nothing (using PowerShell). Also, my files success to build when I hit the Build button in VSCode (also in cases where manual build fails) - here the called address is "C:\Program Files\CMake\bin\cmake" like yours

**Comment by tondach01** [comment]
So, this seems more likely to be problem in my environment variables than in the program. Sorry for bothering you :)
