### ISSUE TITLE
Multiple tasks stops on return result

### ISSUE THREAD

**Issue by cvoogt** [microsoft/vscode-cmake-tools#1766]
I created 2 tasks ("CMakeBuild" and "Upload") and want to run them is sequence ("BuildUpload").

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "BuildUpload",
            "dependsOn": [
                "CMakeBuild",
                "Upload"
            ],
            "dependsOrder": "sequence",
            "problemMatcher": [],
            "group": "build",
        },
        {
            "label": "CMakeBuild",
            "type": "shell",
            "command": "${command:cmake.build}",
            "group": "build",
            "problemMatcher": [],
        },
        {
            "label": "Upload",
            "type": "process",
            "command": "Upload.bat",
            "problemMatcher": [],
            "group": "build",
        }
    ]
} 
```

When running the task "CMakeBuild" I get the error:

> _Cannot substitute command variable 'cmake.build' because command did not return a result of type string._
When running "BuildUpload" this prevents the task "Upload" from starting.

Wat can I do to solve this issue.

**Comment by bobbrow** [comment]
`cmake.build` is a command that performs a build and doesn't return a string back with the actual command used.
You probably want to use `${command:cmake.tasksBuildCommand}` which should return the actual command string.  [Documentation here](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md#command-substitution).

**Comment by cvoogt** [comment]
Thanks for the suggestion. I replace the command with: "command": "${command:cmake.tasksBuildCommand}". Now cmake is not complying any more. I'm getting this result. 

'''
> Executing task: & '"C:\Program Files\CMake\bin\cmake.EXE" --build c:/Prive/Onedrive/Modelbouw/CVT_Modules/CVT_BST01/CVT_BST01_SW_PICO/build --config Debug --target all --' <

& : The term 'C:\Program Files\CMake\bin\cmake.EXE --build c:/Prive/Onedrive/Modelbouw/CVT_Modules/CVT_BST01/CVT_BST01_SW_PICO/build --config Debug --target all --' is not recognized as the name of a cmdlet, function, script
 file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ & 'C:\Program Files\CMake\bin\cmake.EXE --build c:/Prive/Onedrive/Mod ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...--target all --:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command & '"C:\Program Files\CMake\bin\cmake.EXE" --build c:/Prive/Onedrive/Modelbouw/CVT_Modules/CVT_BST01/CVT_BST01_SW_PICO/build --config Debug --target all --'" terminated with exit code: 1.
'''

I can not find additional information on cmake.tasksBuildCommand than that of your link. Is there more information available on this command?

**Comment by bobbrow** [comment]
Hmm... The `&` shouldn't be part of the command string.  Is VS Code adding that?  What happens if you use CMD as your terminal instead of PowerShell?

**Comment by cvoogt** [comment]
I executed the command "C:\Program Files\CMake\bin\cmake.EXE --build c:/Prive/Onedrive/Modelbouw/CVT_Modules/CVT_BST01/CVT_BST01_SW_PICO/build --config Debug --target all --" in the teminial: 

**powershell**
![PS](https://user-images.githubusercontent.com/21263986/114823396-c7ba7000-9dc3-11eb-957c-acf6b57f68ed.JPG)

**CMD**
![cmd](https://user-images.githubusercontent.com/21263986/114823412-cbe68d80-9dc3-11eb-8646-206b3de62f54.JPG)

When I press the build button in the side bar the program is build normally.
![Build_button](https://user-images.githubusercontent.com/21263986/114824086-a6a64f00-9dc4-11eb-9888-480d10fae910.JPG)

When I run the task CMakeBuild, then the compiler does his job correctly. Only the tasks job ends with the error about the variable.
The only problem that I have with this error is that it prevents starting the 2e task. When changing the order of the 2 tasks, than both are executed (in the wrong order). Parallel executing them works, but that can result in the wrong file being upload to the Pico.

**Comment by bobbrow** [comment]
It looks like you accidentally removed the quotes around the full path to CMake.  If you add them back does it work?

The command is this:
`"C:\Program Files\CMake\bin\cmake.EXE" --build c:/Prive/Onedrive/Modelbouw/CVT_Modules/CVT_BST01/CVT_BST01_SW_PICO/build --config Debug --target all --`

**Comment by cvoogt** [comment]
In deed I had the quotes in the wrong place. The corrected command failes PS. In cmd it runs succesfully. 
![CMD](https://user-images.githubusercontent.com/21263986/114979344-fd765c00-9e8a-11eb-885c-3419c2494902.JPG)

How can I use the CMD way in the tasks?

**Comment by bobbrow** [comment]
I was thinking you just add `options.shell.executable` to the task JSON, but it turns out you need to add a `/c` arg to it too.  Something like this:
```
{
    "tasks": [
        {
            "type": "shell",
            "label": "build my code",
            "command": "echo building...",
            "options": {
                "shell": {
                    "executable": "cmd.exe",
                    "args": ["/c"]
                }
            }
        }
    ],
    "version": "2.0.0"
}
```

**Comment by cvoogt** [comment]
Using cmd make that I could place all in one batch file.
```
            "label": "CMakeBuildUpload",
            "type": "shell",
            "command": "echo building...",
            "options": { 
                "shell": {
                    "executable": "cmd.exe",
                    "args": ["/c CMakeBuildUpload.bat"]
                }
            }
```
My problem has been solved. Thanks for the support.

**Comment by bobbrow** [comment]
What is the batch file for?  I thought you would use the `${command:cmake.tasksBuildCommand}` so that the command line would be dynamic and match your current configuration.
```
{
    "tasks": [
        {
            "type": "shell",
            "label": "build",
            "command": "${command:cmake.tasksBuildCommand}",
            "options": {
                "shell": {
                    "executable": "cmd.exe",
                    "args": ["/c"]
                }
            }
        }
    ],
    "version": "2.0.0"
}
```

**Comment by cvoogt** [comment]
My indention was the automate building the .uf2 + copy the .uf2 to the RPi Pico. With you cmd suggestions I created the batch-file below and I only need a single task. 

```
@echo off
set num1=0
set num2=1 
set loopno=10
set timeoutsec=4
set CurFolder=%cd%
for /f "usebackq delims=" %%i in (
  `powershell -noprofile -c "\"%CurFolder%\" -replace '\\', '/'"`
) do set "CurFolderFwSlash=%%i"

echo ==== Building ====
"C:/Program Files/CMake/bin/cmake.EXE" --build %CurFolderFwSlash%/build --config Debug --target all --
echo ==== Copy uf2 file to Pico ====
timeout /t %timeoutsec% /nobreak
:loop
set /a num1= %num1% + %num2%
if %num1%==%loopno% goto close
if EXIST "d:\INFO_UF2.TXT" goto CopyFile
timeout /t %timeoutsec% /nobreak
goto loop

:CopyFile
echo %CurFolder%
copy %CurFolder%\build\*.uf2 d:\*.uf2

:close
echo %num1%
```

The next step is to assign a shortcut to the task. I have defined a short cut in keybindings.json, but due to that I start code.exe from "Developer Command Prompt" these are not loaded. I spend a couple of hours on internet to find a solution without success. Is this something your can help with.

**Comment by bobbrow** [comment]
Unfortunately, this is outside of our area of expertise.  The VS Code team should be able to help you troubleshoot key bindings.  I recommend you open an issue here: https://github.com/microsoft/vscode/issues/new/choose.

To avoid confusing them, test this after disabling the CMake Tools extension so that they don't think it was caused by us.  It doesn't look like you depend on our command anymore.
