### ISSUE TITLE
Allow building with external tools with CMakePresets.json 

### ISSUE THREAD

**Issue by esweet431** [microsoft/vscode-cmake-tools#1784]
### Brief Issue Summary

cmake-tools can make it easier to build with external tools when CMakePresets.json is enabled. This includes:
1. Adding an option to select an "Unspecified" Configure Preset. This option should not create a CMakePresets.json in the root of the open folder.
2.  Read from CMake settings in settings.json (e.g. cmake.generator, cmake.buildDirectory) when CMake Presets integration is enabled *if* no CMakePresets.json exists.

This will allow users to invoke CMake from the CLI, and then run a trivial configure and build command from inside the extension for better IntelliSense/debugging support.

**Comment by KyleFromKitware** [comment]
>     1. Adding an option to select an "Unspecified" Configure Preset. This option should not create a CMakePresets.json in the root of the open folder.

+1
