### ISSUE TITLE
Version restriction of CMakePresets

### ISSUE THREAD

**Issue by bluec0re** [microsoft/vscode-cmake-tools#1790]
### Brief Issue Summary

1.7.0 [restricts](https://github.com/microsoft/vscode-cmake-tools/blob/develop/src/presetsController.ts#L785) CMakePresets.json to version 2 and above. As this version was only introduced recently (with CMake 3.20; End of March 2021), what is the reason to disallow version 1 (3.19) files?

### Expected:

(Reintroduce) Support for 

```
{
  "version": 1,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 19,
    "patch": 0
  },
 [...]
}
```

### Apparent Behavior:

Error is shown:
```CMakePresets version 1 is not supported. How would you like to proceed?```

**Comment by xisui-MSFT** [comment]
This is by design. Version 2 supports build and test presets. However, we do support all versions of cmake so you can use version 2 + cmake 3.19. @esweet431

**Comment by bluec0re** [comment]
Except that cmake 3.19 does not support version 2:

```
$ cmake --version
cmake version 3.19.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).
$ head -6 CMakePresets.json 
{
  "version": 2,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 19,
    "patch": 0
$ cmake --preset=dev_unix
CMake Error: Could not read presets from /src/: Unrecognized "version" field
```
vs
```
$ head -6 CMakePresets.json 
{
  "version": 1,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 19,
    "patch": 0
$ cmake --preset=dev_unix
Preset CMake variables:

  ASAN="OFF"
  CMAKE_BUILD_TYPE="Debug"
[...]
```

**Comment by esweet431** [comment]
You're right that you need CMake 3.20 to build with CMakePresets.json version 2 from the CLI, but you do not need CMake 3.20 to build with CMakePresets.json version 2 from VS Code.

cmake-tools does not support version 1 files because version 1 does not support Build Presets and Test Presets. Build Presets and Test Presets are required for cmake-tools to provide its existing feature set.

**Comment by bluec0re** [comment]
While this is true (that you can build version 2 presets with cmake 3.19 through vscode), it feels a bit like a pseudo argument: 

You could still provide the configuration feature set (and therefore correct syntax highlighting, autocomplete etc) and disable `Build` and `Test` when using a version 1 presets file.

Sometimes it's easier to run the build step in a terminal or via a script than through fancy UI buttons. So the configuration step is the only one really needed to be fully able to use VS code as an editor (not an build environment!), no?

**Comment by bluec0re** [comment]
Or to be more clear:

What's the difference for the extension between

```
{
  "version": 1,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 19,
    "patch": 0
  },
  "configurePresets": [
    {
      "name": "default",
      "displayName": "Default Config",
      "description": "Default build using Ninja generator",
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/build/default",
      "cacheVariables": {
        "FIRST_CACHE_VARIABLE": {
          "type": "BOOL",
          "value": "OFF"
        },
        "SECOND_CACHE_VARIABLE": "ON"
      },
      "environment": {
        "MY_ENVIRONMENT_VARIABLE": "Test",
        "PATH": "$env{HOME}/ninja/bin:$penv{PATH}"
      },
      "vendor": {
        "example.com/ExampleIDE/1.0": {
          "autoFormat": true
        }
      }
    },
    {
      "name": "ninja-multi",
      "inherits": "default",
      "displayName": "Ninja Multi-Config",
      "description": "Default build using Ninja Multi-Config generator",
      "generator": "Ninja Multi-Config"
    }
  ],
  "vendor": {
    "example.com/ExampleIDE/1.0": {
      "autoFormat": false
    }
  }
}
```
and 
```
{
  "version": 2,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 20,
    "patch": 0
  },
  "configurePresets": [
    {
      "name": "default",
      "displayName": "Default Config",
      "description": "Default build using Ninja generator",
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/build/default",
      "cacheVariables": {
        "FIRST_CACHE_VARIABLE": {
          "type": "BOOL",
          "value": "OFF"
        },
        "SECOND_CACHE_VARIABLE": "ON"
      },
      "environment": {
        "MY_ENVIRONMENT_VARIABLE": "Test",
        "PATH": "$env{HOME}/ninja/bin:$penv{PATH}"
      },
      "vendor": {
        "example.com/ExampleIDE/1.0": {
          "autoFormat": true
        }
      }
    },
    {
      "name": "ninja-multi",
      "inherits": "default",
      "displayName": "Ninja Multi-Config",
      "description": "Default build using Ninja Multi-Config generator",
      "generator": "Ninja Multi-Config"
    }
  ],
  "vendor": {
    "example.com/ExampleIDE/1.0": {
      "autoFormat": false
    }
  }
}
```

both taken from [cmake-presets (7) - 3.19](https://cmake.org/cmake/help/v3.19/manual/cmake-presets.7.html#build-preset) and [cmake-presets (7) - 3.20](https://cmake.org/cmake/help/v3.20/manual/cmake-presets.7.html#build-preset), the second without the build and test presets from the example as they are optional

**Comment by bobbrow** [comment]
@xisui-MSFT can provide more detail, but I believe this support would require an additional hybrid implementation between the Kits+Variants path and the Presets path since there would be no information for the UI about build/debug/test targets if the Presets driver was selected.

**Comment by andreeis** [comment]
Closing this as it is not on our roadmap and we also don't have resources to implement and then maintain this scenario.
