### ISSUE TITLE
CMake tools is persisting an old removed version of ninja

### ISSUE THREAD

**Issue by robotdad** [microsoft/vscode-cmake-tools#1792]
### Brief Issue Summary

I am getting a build failure with CMake tools because it can't find ninja. I have ninja on my path. CMake tools is showing ninja at a non-existent location that used to be on my path. I cannot find where this value is persisted. I have reset the extension and cleaned my cmake cache.

**Comment by andreeis** [comment]
Not sure, just a hunch, do you have presets enabled? Is your project multi-root? Disable presets temporarily ("cmake.useCMakePresets": "never") just to see if the correct ninja is found. I've been hunting a bug regarding incomplete reset of extension state for multi-root presets. There is some cache associated with configure presets that maybe is not cleared when CMakeCache.txt is deleted.
@xisui-MSFT , any ideas?

**Comment by robotdad** [comment]
I had used presets but not for this project. I tried setting useCMakePresets to false, and I rolled back to 1.6 and back up to 1.7 and it still recalls the old ninja location.

**Comment by xisui-MSFT** [comment]
VS Code may not  be able to refresh env vars correctly sometimes. Can you try something like 'ninja --version' in the terminal in VS Code?

**Comment by robotdad** [comment]
It works in the terminal. 

ninja --version
1.10.1

**Comment by andreeis** [comment]
@robotdad, just know that useCMakePresets needs to be "never" not false (it's an enum of 3 string values). Once you set it to never, delete all the build folder and run the reset state command again.
Also, is this single root or multi root?
If this still reproduces after trying my latest suggestion, send us logs (with "cmake.loggingLevel": "Debug") after a VSCode reset of state (the "troubleshooting" comamnd) + "delete cache and reconfigure" command. Then try to make a new project from scratch (with quickStart command) and let's see what happens then.

**Comment by robotdad** [comment]
@xisui-MSFT and I took a look at this together, we can't figure out where this value is persisting from. As a troubleshooting step I'm going to see if I can build cleanly from the cli to rule out issues from my system configuration.
