### ISSUE TITLE
vscode cmake-tools cannot run targets inside subfolders even the targets are correctly detected

### ISSUE THREAD

**Issue by vili22** [microsoft/vscode-cmake-tools#1801]
### Problem description

I have a cmake project which have subfolders, for example unit-test folder having own CMakeList and a target. The CMakeTools
extension correctly identifies this target, i.e, it can be selected as target for build and run options. However, when the build is launched for the selected target it throws and error

> MSBUILD : error MSB1009: Project file does not exist.

 The reason is that it tries to launch the target from root folder i.e., the build argument is

> --build path/to/build --Target UnitTest

even it should be

> --build path/to/build/src/test --Target UnitTest

### Expected:
 The CMake --build argument should point to correct location of the target, i.e., 

> --build path/to/build/src/test --Target UnitTest

### Apparent Behavior:
The CMake --build argument points to root of the project which does not contain the target, i.e.,

> --build path/to/build --Target UnitTest

**Comment by andreeis** [comment]
In general all the identified targets are meant to be built from the build folder. We've never encountered this requirement before and we don't support it. Also, tests are seen as a different entity associated with the main project. They are meant to be built and run while having the main project loaded.

You can do an "Open Folder" to the test location to get the build behavior that you want, but you will lose the main project.
As a workaround you can also "Add folder to workspace" (right click on the free area in the file explorer tab on the left of VSCode) pointing to the test subfolder. Whenever you want to build the test, make sure that the test is the active folder of the workspace. When you need the main project switch the active folder to what you have now.

**Comment by andreeis** [comment]
My comment may not be completely correct (I may have assumed some wrong things about your project). Can you share the project with us or at least the structure and the CMakeLists.txt files?

**Comment by vili22** [comment]
Hi, thank you for looking into this issue. A minimal project illustrating the problem can be found here [example-project](https://github.com/vili22/example_project) . Targets main2 and main3 inside sub_project and sub_sub_project are correctly listed as targets, but cannot be build/run because the project files are not found. The problem is actually caused by the EXCLUDE_FROM_ALL parameter in

> add_subdirectory(sub_directory EXCLUDE_FROM_ALL)

call and affects only Windows environment with visual-studio  compiler. If the EXCLUDE_FROM_ALL parameter is removed the targets can be run normally and in the sense this is not a real problem. However, it is a bit confusing that the targets are listed and cannot be run and furthermore at least Clion can run the targets normally.
