### ISSUE TITLE
Where is MACHINE set?

### ISSUE THREAD

**Issue by JoeABrown58** [microsoft/vscode-cmake-tools#1805]
### Brief Issue Summary

We are building an entire embedded Linux operating system. A component supplier has provided a Yocto environment including a custom layer for their part. We are adding a couple of modules to their layer. It all works for our embedded OS. In order to develop our new code we are trying to get it to build inside VS-Code.

### CMake Tools Log

The CMake/Build output panel shows:
[cmake] CMake Error at tools-public/packaging/packaging.cmake:7 (message):
[cmake]   MACHINE is not defined!
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:505 (include)

### Platform and Versions

- **Operating System**: Ubuntu 16.04
- **CMake Version**: 3.18.6
- **VSCode Version**: 1.55.2
- **CMake Tools Extension Version**: 1.7.0
- **Compiler/Toolchain**: Clang 9.0.0

### Other Notes/Information

I expected to be able to set MACHINE in one of the .vscode/*.json configuration files but have not had any success yet.

**Comment by bobbrow** [comment]
This looks like something that needs to be defined in your CMakeLists.txt, or by adding a command line arg to the cmake invocation.  How do you normally run cmake for this project when you just use a terminal?  If there are additional args you need to pass in, we have two settings `cmake.configureSettings` and `cmake.configureArgs` that can help you out.

https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md

**Comment by JoeABrown58** [comment]
A full build for an embedded machine would look like:
./run_configure.py <machine>
cd build
source setup-yocto
MACHINE=<machine> nice bitbake yocto-nsdk-ip-image-swu

I deleted the **.build-pc** directory and ran
./run_configure.py pc
The error did not appear. Up to 60% of the files compiled until other errors occurred.

I will try the cmake.configureXX settings if it fails again.

**Comment by bobbrow** [comment]
Does that script just define a bunch of variables, or does it also call into CMake?  If it sets up the environment for you and you only need to run it once, you could run it in your terminal before launching vscode, and then when you do launch vscode from that terminal, the environment will be inherited for configuration and build.

Another option is to create a "[Kit](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/kits.md)" in your workspace and set the `environmentSetupScript` property to your python script.

If neither of those options work for you, then your scenario should be covered by #477 which we plan to get to soon.

**Comment by JoeABrown58** [comment]
run_configure.py configures the environment. setup-yocto fetches code from public repositories. bitbake calls code that uses cmake. My issue was when I was trying to work three levels below the root.

**Comment by JoeABrown58** [comment]
Mixing command line and vs-code builds caused problems. The project will not build using CLang so we have abandoned it.
