### ISSUE TITLE
Custom launch / debug control

### ISSUE THREAD

**Issue by RussSchultz** [microsoft/vscode-cmake-tools#1810]
Feature request:    some sort of way of configuring/overriding the default debug and launch mechanisms in CMake tools

I'm using Cmake + VSCode as an "integrated" environment for cross compiling to embedded tools and targets.

One irritating thing is when I'm targeting our ARM board, I'd like to be able to launch or debug using the 'debug' or 'launch' buttons down in the bottom status bar.

These require a different command line than what's built in.  

Right now, for example, it looks like 'launch' just tries to pass the command line the target filename (which on windows is an EXE and it functions.

To run the embedded targeted executables, however, the output is a .ELF file which needs to be loaded by the instruction set simulator or debugger for execution.

For example, we target Xtensa cores, and we have to launch it like so:

xt-run.exe --xtensa-core=<TARGET_PROCESSOR> --exit_with_target_code \<ELFFILE>

or to launch the debugger (rather than the integrated one)

xplorer --debug \<ELFFILE> 

Running ARM ELFs are similar, but different syntax.

I don't know the cleanest way to integrate because the launch and debug string would be different for each toolchain used and would somehow need to overridden by the things in the toolchain file or the variants.yaml file.   

Any suggestions on where to start with this, or ...?

**Comment by bobbrow** [comment]
This documentation goes over how to set up a more advanced scenario like yours: [Debug using launch.json](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md#debug-using-a-launchjson-file).  Let us know if this has the information you need.  The Quick Debugging button wasn't designed to support this.

One thing to note (that we should add to this section) is that when you invoke the `${command:cmake.launchTargetPath}`, it can be configured to build your project so you don't need to add any "preLaunchTasks" to your configuration.  [More information here](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md#command-substitution)
