### ISSUE TITLE
nable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable.

### ISSUE THREAD

**Issue by jariy** [microsoft/vscode-cmake-tools#1812]
### Expected:

1. Push button
2. Thing happens

### Apparent Behavior:

1. Push button
2. Nothing happens

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: 
- **CMake Version**: 
- **VSCode Version**: 
- **CMake Tools Extension Version**: 
- **Compiler/Toolchain**:

**Comment by bobbrow** [comment]
Hi @jariy,

If you could please provide the information requested we would be happy to reopen and investigate your issue.  Currently there is not enough information for us to proceed.
