### ISSUE TITLE
The headers search only work when editing settings.json

### ISSUE THREAD

**Issue by alanlivio** [microsoft/vscode-cmake-tools#1813]
### Brief Issue Summary
The headers search only work when editing settings:
`"C_Cpp.default.compileCommands": "${workspaceFolder}/_build/compile_commands.json"`
or 
`"cmake.copyCompileCommands": "${workspaceFolder}/compile_commands.json"
`

Why the compile_commands.json cannot be automatically load from the default cmake build folder?

### Expected:

Do not edit settings.json.

### Platform and Versions

- **Operating System**: 
- **CMake Version**:  3.20.0-rc5
- **VSCode Version**: 1.52.1
- **CMake Tools Extension Version**: v1.7.1
- **Compiler/Toolchain**: gcc.exe (Rev9, Built by MSYS2 project) 10.2.0

**Comment by bobbrow** [comment]
The C++ extension is blissfully unaware of the outputs of any build system extension like this one.  There are other extensions out there that provide similar functionality so it doesn't play favorites with CMake Tools.

Yet another option is to use `"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"` and not need compile_commands.json at all.

**Comment by alanlivio** [comment]
> `"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"`

Thank you. It worked for me.  
May be is interesting have it in documentation: https://code.visualstudio.com/docs/cpp/cmake-linux
