### ISSUE TITLE
Showing Chinese Mojibake in new version 1.7.1

### ISSUE THREAD

**Issue by LoSealL** [microsoft/vscode-cmake-tools#1820]
### Brief Issue Summary

Can't display Chinese properly in the terminal window in the new version 1.70+

### Expected:

Showing Chinese like "生成“

### Apparent Behavior:

Showing Mojibake like “????”

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: Windows 10 20H2
- **CMake Version**: 3.20.0
- **VSCode Version**: 1.55.2
- **CMake Tools Extension Version**: 1.7.1
- **Compiler/Toolchain**: VS 2019

### Other Notes/Information

Downgrade to 1.6.0 can resolve this issue

**Comment by bobbrow** [comment]
Can you tell us how to set up a project that uses Mojibake?  Maybe create a small project on GitHub that we can clone?  That would help us investigate immensely.

**Comment by LoSealL** [comment]
> Can you tell us how to set up a project that uses Mojibake? Maybe create a small project on GitHub that we can clone? That would help us investigate immensely.

@bobbrow Sorry, maybe the issue isn't clearly stated.

What I mean is that when both Windows and the VS Code are set to use Chinese (Simplified) and the code page is GBK (936) [*perhaps the code page is not the root cause, it's just what my setting is*],
this extension shows "?" and other random characters in the VS Code terminal window.

**Comment by LoSealL** [comment]
Any project can reproduce this issue, once you build the project using this extension.

**Comment by andreeis** [comment]
Very likely fixed by PR https://github.com/microsoft/vscode-cmake-tools/pull/1808. We'll test more to confirm this.

**Comment by andreeis** [comment]
@LoSealL, can you test the vsix here (https://github.com/microsoft/vscode-cmake-tools/actions/runs/811030625) and let us know if it fixes the problem? This fix will be included in 1.7.2 which will be released later this week but we are not sure if it addresses your scenario or not.

**Comment by LoSealL** [comment]
@andreeis Yes, this vsix fixes the issue! Thank you.

**Comment by andreeis** [comment]
Excellent, thank you for confirming.
