### ISSUE TITLE
the procedures of compiling a C project using Cmake/Cmake tools and Vscode

### ISSUE THREAD

**Issue by wenouyang** [microsoft/vscode-cmake-tools#1825]
Are there any tutorials/procedures explaining compiling a C project (including multiple C file and header file) using CMake and VScode. This [tutorial ](https://code.visualstudio.com/docs/cpp/cmake-linux#_build-hello-world)posted only covers compiling a single file. Thanks.

**Comment by andreeis** [comment]
You can also explore these documents from our GitHub repository:
https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/configure.md
https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/build.md

Let us know if there is anything that you can't find and we will work on improving our general documentation.
