### ISSUE TITLE
launch.json selects the incorrect debugger executable.

### ISSUE THREAD

**Issue by seppeon** [microsoft/vscode-cmake-tools#1827]
### Brief Issue Summary

On my computer I have many different GCC installations, I have many LLVM installations etc...

When using the `launch.json` example [here](https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html#debugging-launch-json), the incorrect dbgExe is selected.

### Expected:

Expected behaviour, Cmake Tools select the correct debugger, the same one used if launched using the CMake Tools dedicated debug button.

### Apparent Behavior:
The resulting error is this:
![image](https://user-images.githubusercontent.com/68693576/116852704-24c57b00-ac38-11eb-9a59-1990f43480a5.png)

However the compiler is this:
```
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/utils/bin/mingw64/bin/clang.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: C:/utils/bin/mingw64/bin/clang++.exe - skipped
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: cmake version 3.19.0-rc3
- **VSCode Version**: 1.55.2
- **CMake Tools Extension Version**: 1.7.7
- **Compiler/Toolchain**: Clang 11.1.0

### Other Notes/Information

I use clang from winlibs:
http://www.winlibs.com/

My exact configuration in launch.json:
```JSON
        {
            "name": "Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${command:cmake.launchTargetPath}",
            "args": [],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [
                {
                    "name": "PATH",
                    "value": "$PATH:${command:cmake.getLaunchTargetDirectory}"
                }
            ],
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
```

**Comment by andreeis** [comment]
Thank you for opening this report. If you run debug from the CMake Tools debug button, you're saying that the debugging works (no error), but does it pick the same executable as I see in the error screenshot? Do you have any setting under "cmake.debugConfig"?

Also, the path syntax you are using in your launch.json environment block is wrong for windows. Use ${env.PATH} (and also see if the error occurs still).

**Comment by seppeon** [comment]
Nope, it does the same thing with:
1. Nothing in settings.json, cmake.debugConfig (I had "externalConsole":false)
2. The path "environment" section of the launch file removed entirely.

**Comment by andreeis** [comment]
@WardenGnaw, do you have any ideas what could happen here?

**Comment by WardenGnaw** [comment]
MIEngine determines which debugger to choose based off of the PATH environment variable if `miDebuggerPath` is not specified.

If you open a cmd prompt and run `echo %PATH%`, is `C:/utils/bin/mingw32/bin/` before `C:\Strawberry\c\bin\`? 

The cmake debug button is different from the regular launch and may be adding `C:/utils/bin/mingw32/bin/` for the compilers. 

But if you have a specific debugger to use, please specify `miDebuggerPath` in the `launch.json`.

**Comment by seppeon** [comment]
Yes, its likely the path ordering is wrong, but that seems like a behavioural difference that doesn't need to be there, especially since CMake tools knows the actual debugger path and since the cmake debug button functions differently.

I don't much like the idea of hardcoding paths in the launch.json.
