### ISSUE TITLE
CMake Tools Not Available as C++ Configuration Provider

### ISSUE THREAD

**Issue by KyleFromKitware** [microsoft/vscode-cmake-tools#1832]
### Brief Issue Summary

I'm trying to use CMake Tools as the C++ configuration provider, but it is not available when I go to "C/C++: Change Configuration Provider..."

### Expected:

1. Open command palette
2. Select "C/C++: Change Configuration Provider..."
3. "CMake Tools" should be an option

### Apparent Behavior:

1. Open command palette
2. Select "C/C++: Change Configuration Provider..."
3. "CMake Tools" is not an option

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.20.2
- **VSCode Version**: 1.55.2
- **CMake Tools Extension Version**: 1.7.1
- **Compiler/Toolchain**: GCC 9.3.0

### Other Notes/Information

I am using `CMakeUserPresets.json`, not sure if this is relevant or not.

**Comment by bobbrow** [comment]
CMake Tools does not currently register itself until a successful "configure" has happened.  We recommend setting `cmake.configureOnOpen` to `true` until we make this the default value.  Otherwise, you can run the `CMake: Configure` command and that will start the provider.  We're also looking at #1149 and #477 which will help for the "unconfigured" or "configured outside of VS Code" situations.

**Comment by KyleFromKitware** [comment]
Thanks. I tried running "CMake: Configure" and then changing the provider, but CMake Tools was still not available.

**Comment by bobbrow** [comment]
Did the configure fail?  I don't know of any other reason why this shouldn't work.  Is this on the CMake repo, or some other one?

**Comment by KyleFromKitware** [comment]
The configure succeeded. I just tried it a second time and was still not able to change the configuration provider.

I am working on the CMake repository, but I'm using `/usr/bin/cmake` for the configure.

**Comment by bobbrow** [comment]
Hmm... A fresh clone of Kitware/CMake configured fine for me.  

![image](https://user-images.githubusercontent.com/12818240/117078308-7b8d8c00-acee-11eb-9070-777b54039623.png)

Would you be able to set the `cmake.loggingLevel` to `debug`, reload the window, run the "configure" command and then share the CMake Tools logs with me?  I think you have my email address if you don't want to share them publicly.

**Comment by KyleFromKitware** [comment]
Thanks. I emailed you the debug log in private.

**Comment by andreeis** [comment]
@KyleFromKitware, we have a fix for this problem. Until we release 1.7.3 (soon today or tomorrow) you can try the vsix here: https://github.com/microsoft/vscode-cmake-tools/actions/runs/833201528.
Uninstall CMake Tools 1.7.2 and run the command "Extensions: Install from VSIX" from the palette.
Let us know if IntelliSense works again.

**Comment by bobbrow** [comment]
This fixes it for me.  I updated the version in package.json to 1.7.3.  We just need to update the changelog and we can release it.
