### ISSUE TITLE
CMake/Build OUTPUT view does NOT have hyperlinks 

### ISSUE THREAD

**Issue by messedup-loser** [microsoft/vscode-cmake-tools#1858]
### Brief Issue Summary

the CMake/Build Output view will show compiler output. it is black/white text WITHOUT any hyperlinks to the file/line# that is a error/warning

### Expected:
1. hit the build button
2. the CMake/Build Output view would have hyperlinks of file/line# where there are errors/warnings. so if those are clicked then a file would load in the editor window at the associated line#

### Apparent Behavior:

1. hit the build button
2. the Output view is filled with compiler output. (see the attached screenshot). there is NO link (file/line#) recognition. so it's NOT possible to click in the CMake/Build Output view to load the file that has the associated error/warning

### Platform and Versions

- **Operating System**: windows 10 (Windows_NT x64 10.0.19042)
- **CMake Version**: 3.18.20081302-MSVC_2
- **VSCode Version**: 5.6.0
- **CMake Tools Extension Version**: 1.7.2
- **Compiler/Toolchain**: NOT working on both compilers - clang 11 / gcc 10.3.0

### Other Notes/Information
**[issue #1237](https://github.com/microsoft/vscode-cmake-tools/issues/1237)  advises to open a new issue if experiencing similar problems. there are NO other extensions being used except for the microsoft C/C++ plugin here**

in the attached screen shot, the files shown are relative - does that matter?

ONE other consideration is that i'm using my own custom Cmake build setup for _cross platform but also for different compilers_ where there are also a number of other defines (or Cmake setting variables) that could be changed. so that's all done through my own CMakeLists.txt file - NOT through the ### **_BUGGY_** GUI of the - Cmake Tools extension. 

i have got both ECLIPSE IDE & clion ide  (cmake output) to work using my custom cmake configuration. maybe my custom cmake configuration is the problem? i DON'T know but the Cmake Tools extension GUI kinda seems to be getting in the way (because i control everything through my CMakeLists.txt file NOT ### **_BUGGY_** GUI)

![Capture](https://user-images.githubusercontent.com/64900651/117559429-05648e80-b03a-11eb-8426-8446f008ff02.PNG)

**Comment by ceztko** [comment]
You closed the issue right after opening it, probably meaning that you sorted out. It would be nice if you pointed out what was the problem and how you dealt with it.

**Comment by messedup-loser** [comment]
i have some living situation issues. i DON'T know if this is also the 
regular ide developers (or only the vscode-cmake-tools). but, i'm hoping 
it's also just the vscode ide developers & NOT the cmake_tools ONES.

so i dumped the cmake plugin because all wizards are completely inadequate

okay anyways. my code base is now wired up to just the regular vscode 
ide (with NO plugins that i remember right now except for NON microsoft 
stuff to get stuff working - but i'd have to look)

so i just use CMAKE variables dude & it controls compiling (an automated 
build system) ... tested over linux, windows & mac machines [but only 
controlled through the windows ONE].

it also switches between using whatever compilers are installed on those 
operating systems. like on windows i can compile using the visual studio 
compiler or gcc or clang or intel compiler on windows

so yeah your cmake plugin totally sucks I.M.O..

**Comment by messedup-loser** [comment]
& here's my fucking resume assholes

**Comment by bobbrow** [comment]
Moderating some comments above.  We intend for this repo to be a safe place for developers to collaborate.  Please keep it kind in here.

[Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/)

**Comment by bobbrow** [comment]
For what it's worth, the CMake extension is not responsible for hyperlinks in the Output panel. VS Code has an algorithm to intercept the output and present hyperlinks in that panel.  Any issues with the hyperlinks should be opened in the VS Code repo though I suspect the challenge here is that relative paths are going to be assumed to be rooted by the `${workspaceFolder}`, not the build directory.

https://github.com/microsoft/vscode/issues/new/choose

**Comment by messedup-loser** [comment]
i'm looking forward to your scum being discontinued like ECLIPSE IDE 
BUGGY PIECE OF SHIT & I FUCKING DO THE SHIT YOUR SAYIN WITH FUCKIN SED & 
THE FUCKIN WHATEVER ON WINDOWS I  KNOW WHAT YOU'RE TALKIN ABOUT

**Comment by bobbrow** [comment]
Sorry @messedup-loser, but if you can't play nice here, you will be blocked.

**Comment by messedup-loser** [comment]
FUCK YOU FAG

**Comment by bobbrow** [comment]
I'm sorry that there is so much pain and hurt in your life, but the way you express it here will not be tolerated.  I hope that you can find good resources to help you deal with it.  You have officially been blocked.
