### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by AJGuerin** [microsoft/vscode-cmake-tools#1867]
- Issue Type: `Bug`
- Extension Name: `cmake-tools`
- Extension Version: `1.7.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by andreeis** [comment]
@AJGuerin, please reopen with more details about what the symptoms of the problem are.
