### ISSUE TITLE
On windows, clang are not detected properly

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#1870]
On Windows, the installed clang can works with both mingw and msvc different version
We can generate the matrix for that

**Comment by andreeis** [comment]
@lygstate, can you provide more details for this suggestion? There are many GitHub reports related to clang kits. Please explain how this one fits into the whole story.

**Comment by lygstate** [comment]
> @lygstate, can you provide more details for this suggestion? There are many GitHub reports related to clang kits. Please explain how this one fits into the whole story.

Hi, just for mark, I'll create pr fixes this,

**Comment by lygstate** [comment]
This is the command to using clang-cl to compiling things
```
cmake -Bssl-build-i686 -Hopenssl-cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release "-GNinja" ^
	"-DCMAKE_C_FLAGS_INIT=--target=i686-pc-windows-msvc" ^
	"-DCMAKE_CXX_FLAGS_INIT=--target=i686-pc-windows-msvc -Zc:threadSafeInit-" ^
	-DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl ^
	-DCMAKE_INSTALL_PREFIX=%WD%\install-i686
```
