### ISSUE TITLE
 How can I disable the action of automatic configuration

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/vscode-cmake-tools#1876]
### Brief Issue Summary

Whenever I modify CMakeLists.txt, CMake Tools will help me automatically configure the project. How can I disable the action of automatic configuration?

### Platform and Versions

- **Operating System**:  Win10 21H2
- **CMake Version**: 3.20.2
- **VSCode Version**: 1.56.2
- **CMake Tools Extension Version**: v1.7.3
- **Compiler/Toolchain**: GCC 8.1.0

**Comment by andreeis** [comment]
You can set "cmake.configureOnEdit" to "false" in your .vscode/settings.json. This will prevent automatic configure when editing the CMakeLists.txt and also when changing the value of "cmake.sourceDirectory".
Additionally, if you want to prevent the configure that is done automatically when loading the project, you can set to "false" a similar "cmake.configureOnOpen".
