### ISSUE TITLE
Intellisense configuration for proprietary ARM compiler

### ISSUE THREAD

**Issue by aelray** [microsoft/vscode-cmake-tools#1877]
### Brief Issue Summary

We are using the proprietary ARM compiler 6.14 with a special license and therefore need a special flag to query the compiler, see:

https://github.com/microsoft/vscode-cpptools/issues/5492

However, when we use CMake as configuration provider, this flag seems not to be passed on

![image](https://user-images.githubusercontent.com/2736151/118462182-b33d0080-b6fe-11eb-8017-bff31f7a510d.png)

from: [here](https://github.com/ARM-software/CMSIS_5/blob/def6f800f95661eb3451d317f7d0dde504f6020d/CMSIS/Core/Include/cmsis_compiler.h#L46)

Is there a way to pass the custom flag `-mcpu=cortex-m4` via cmake-tools to the Cpp extension?

### Platform and Versions

- **Operating System**: Windows/WSL2/Ubuntu container
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.56.2
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: ARM Compiler 6.14

**Comment by andreeis** [comment]
@aelray, can you run the command "C/C++ Log Diagnostics" from the palette (while having the header with the squiggle opened in the VSCode editor) and share with us the content of the "C/C++ Diagnostics" output channel?

**Comment by aelray** [comment]
Here is the output:
```
-------- Diagnostics - 9/27/2021, 11:03:16 AM
Version: 1.6.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "compilerPath": "/usr/lib/ccache/clang-10",
    "cStandard": "c11",
    "cppStandard": "c++14",
    "intelliSenseMode": "linux-clang-x64",
    "defines": [
        "ARMCC_VERSION=6100100"
    ],
    "compilerArgs": [],
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": []
}
Translation Unit Mappings:
[ /**/cmsis_compiler.h ]:
    /**/cmsis_compiler.h
Translation Unit Configurations:
[ /**/cmsis_compiler.h ]:
    Process ID: 7893
    Memory Usage: 16 MB
    Compiler Path: /usr/lib/ccache/clang-10
    Includes:
        /usr/include/c++/9
        /usr/include/x86_64-linux-gnu/c++/9
        /usr/include/c++/9/backward
        /usr/local/include
        /usr/lib/llvm-10/lib/clang/10.0.1/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Defines:
        ARMCC_VERSION=6100100
    Standard Version: c++14
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=100001
        --header_only_fallback
Total Memory Usage: 16 MB
```
seems like a lot is not correctly propagated 
We're using two toolchains in this workspace:

-  clang (compiling for x64)
- armclang (compiling for a cortex-m4)

But CMake was set to armclang before creating the log
