### ISSUE TITLE
Unable to resolve resource cmake-tools-schema:/schemas/CMakePresets-schema.json.

### ISSUE THREAD

**Issue by DmitrySokolov** [microsoft/vscode-cmake-tools#1878]
Issue Type: <b>Bug</b>

1. Create the new file `CMakePresets.json`
2. Enter `{}`

Actual result:

Unable to load schema from 'cmake-tools-schema:///schemas/CMakePresets-schema.json': cannot open cmake-tools-schema:/schemas/CMakePresets-schema.json. Detail: Unable to resolve resource cmake-tools-schema:/schemas/CMakePresets-schema.json.

Extension version: 1.7.3
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (56.89GB free)|
|Process Argv|--crash-reporter-id ee5daf53-921f-4db9-9a5d-ec3244a157c7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehovct:30302760
bridgeflightcf:30302070
vscod805cf:30301675

```

</details>

**Comment by bobbrow** [comment]
I am unable to reproduce this by following the steps you shared. If you are still experiencing this issue and can provide more information about how you hit the issue (e.g. settings, folder layout), we can take another look.

**Comment by DmitrySokolov** [comment]
![изображение](https://user-images.githubusercontent.com/1764472/124359861-6cb05080-dc2f-11eb-95f3-53642fb9fbe3.png)

**Comment by DmitrySokolov** [comment]
Changed CMake Tools settings:
```
    "cmake.cmakePath": "C:/Dev/Tools/CMake/bin/cmake.exe",
    "cmake.clearOutputBeforeBuild": false,
    "cmake.skipConfigureIfCachePresent": true,
```

**Comment by andreeis** [comment]
I am not able to reproduce either. I am getting 'Missing property "version"' instead, which is correct.
I also tried with the 1.7.3 exact release, since I suspected that maybe we fixed this since then.

**Comment by jrobeson** [comment]
I just got this as well. It's likely that my file is invalid somehow.  I was playing with this cmake generator https://github.com/friendlyanon/cmake-init and i hadn't had previous experience with the presets file before.

I opened up the generated project and it told me that vscode doesn't support version 1, so i changed it to version 2, and then I got this message.
