### ISSUE TITLE
Environment variables from cmake presets do not seem to carry over to debugger 

### ISSUE THREAD

**Issue by moyo1997** [microsoft/vscode-cmake-tools#1884]
I specified LD_LIBRARY_PATH as an environment variable in my cmake presets. However, when I tried to debug with the “CMake: Debug” command and also right clicking the target and selecting debug, both didn’t work as I got this error : “error while loading shared libraries: libPocoCrypto.so.62: cannot open shared object file: No such file or directory”.
Once I created the launch.json and specified the LD_LIBRARY_PATH and then selected that launch.json configuration at the bottom to debug, then debugging worked.

**Comment by xisui-MSFT** [comment]
Best place to add this:

For debugging: https://github.com/microsoft/vscode-cmake-tools/blob/951ec68872e6f8a08fba9be378e19034b274071b/src/cmake-tools.ts#L1769

For launching: https://github.com/microsoft/vscode-cmake-tools/blob/951ec68872e6f8a08fba9be378e19034b274071b/src/cmake-tools.ts#L1812

**Comment by elahehrashedi** [comment]
we can carry over the `build` preset environment variables to the `debug`.

**Comment by xisui-MSFT** [comment]
> we can carry over the `build` preset environment variables to the `debug`.

Not sure if build preset is the best candidate for this... Maybe test preset is better?

**Comment by bobbrow** [comment]
I think build preset is the preferred choice.  Test presets (or even tests configured by CMake) may not exist.
