### ISSUE TITLE
Can't work with vcpkg

### ISSUE THREAD

**Issue by yoavmil** [microsoft/vscode-cmake-tools#1888]
### Brief Issue Summary

CMake cant find my VCPKG installed libraries. The internet and `vcpkg integrate install` says to use `-DCMAKE_TOOLCHAIN_FILE=path/to/vcpkg/scripts/buildsystems/vcpkg.cmake` but I cant figure out how to do it with CMake tools.

### Expected:

Work out of the box, just as in Visual Studio. There are all Microsoft tools.

### Apparent Behavior:

`find_package` fails to find a library I have installed there, and works in other projects.

### Platform and Versions

- **Operating System**: Win10
- **CMake Version**: 3.20.1
- **VSCode Version**: 1.56
- **CMake Tools Extension Version**:  1.7.3
- **Compiler/Toolchain**: vs pro, 16.9.5
- **vcpkg**: 2021-01-13

**Comment by andreeis** [comment]
You can use either of these settings in your .vscode/settings.json:
"cmake.configureSettings" (which can set pairs of defines and their values, it will translate into adding as many -D as you define)
"cmake.configureArgs" (where you can define in an array of string any argument to be passed to cmake when configuring, including -D but with the complex syntax: -DYouSetting=YourVal).

**Comment by yoavmil** [comment]
could you give a full json example?

**Comment by andreeis** [comment]
Sure, either "configureArgs":
    "cmake.configureArgs": ["-DCMAKE_TOOLCHAIN_FILE=path/to/vcpkg/scripts/buildsystems/vcpkg.cmake"],

or "configureSettings":
    "cmake.configureSettings": {
        "CMAKE_TOOLCHAIN_FILE": "path/to/vcpkg/scripts/buildsystems/vcpkg.cmake"
    },

**Comment by yoavmil** [comment]
Yep, it workws. Is it in the docs? I couldn't find it.
