### ISSUE TITLE
cmake.parallelJobs doesn't effect building parallel

### ISSUE THREAD

**Issue by yoavmil** [microsoft/vscode-cmake-tools#1891]
This is my `.vscode\settings.json`
```json
{
    "cmake.configureArgs": ["-DCMAKE_TOOLCHAIN_FILE=path/tp/vcpkg/scripts/buildsystems/vcpkg.cmake"],
    "cmake.parallelJobs": 8
}
```
I build with msvc19

Builds are not parallel although I think I'm settings them. What am I missing?

### Platform and Versions

- **Operating System**: Win10
- **CMake Version**: 3.20.1
- **VSCode Version**: 1.56
- **CMake Tools Extension Version**:  1.7.3
- **Compiler/Toolchain**: vs pro, 16.9.5
- **vcpkg**: 2021-05-05

**Comment by andreeis** [comment]
Do you have presets on? If yes, define parallelJobs as a cache variable in your configure preset.
If not, then this is a bug and we'll have a look, but we'll wait for your answer first.

**Comment by yoavmil** [comment]
> Do you have presets on? If yes, define parallelJobs as a cache variable in your configure preset.

Where and how? I'm not familiar with cmake tools, I'm still just evaluating it (against VS).

**Comment by andreeis** [comment]
My mistake, not a cache var. It looks that the documentation (https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) allows for the keyword "jobs" in a build or test preset.

**Comment by yoavmil** [comment]
From what I see, `cmake.parallelJobs` effects the `-j N' flag sent to CMake. When not settings anything, on my macine it is set to 18.
But, on MSVC it doesn't propegate to a parrallel command, with the /MP flag. I have to set the /MP flag inside the CMakeLists.txt myself like this:
```cmake
if (MSVC) 
    add_compile_options(/MP16) # set compile parallel
endif()
```

**Comment by andreeis** [comment]
What version of cmake do you have? Is it older than 3.14? Do you confirm the same problem with presets off?
I have [this PR](https://github.com/microsoft/vscode-cmake-tools/pull/1521) on my mind, maybe something is not working right with presets on.
If you have at least cmake 3.14, the extension prefers to use the CMake parallelism so it will invoke -j and not -maxcpucount which is specific to msvc.

**Comment by yoavmil** [comment]
> CMake Version: 3.20.1

> Do you confirm the same problem with presets off?

Remind how to set presets on/off?

**Comment by andreeis** [comment]
Define "cmake.useCMakePresets": "never" in your .vscode/settings.json.

**Comment by yoavmil** [comment]
I confirm, when not using presets, the build isn't parralallel.

maybe this will help, It's the build command
```cmd
cl /c /I... /W3 /WX- /diagnostics:column /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D HAS_BOOST /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /openmp /std:c++17 /Fo"..." /Fd"..." /Gd /TP /errorReport:queue
```
