### ISSUE TITLE
Where to set intelliSenseMode

### ISSUE THREAD

**Issue by thunderstorm010** [microsoft/vscode-cmake-tools#1894]
With the C/C++ integration, what I get in the C/C++ output is always this:
`MSVC intelliSenseMode specified.  Configuring for compiler cl.exe.`
The compiler is set to clang++.
My settings.json:
```
{
    "files.associations": {
        "iostream": "cpp"
    },
    "cmake.exportCompileCommandsFile": true,
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
    "C_Cpp.default.intelliSenseMode": "linux-clang-arm64"
}
```
I did set the intelliSenseMode in both my user and workspace settings but C-cpptools extension insists on MSVC intelliSenseMode

**Comment by andreeis** [comment]
Do you have a kit set?
Share with us the content of the "CMake/Build", "C/C++ Diagnostics" and "C/C++" output channels, after you set "cmake.loggingLevel" AND "C_Cpp.loggingLevel" to "Debug" in your .vscode/settings.json, open the source file with the problem and run the command "C/C++: Log Diagnostics" from the palette.
