### ISSUE TITLE
Unable to find Ninja when using CMakePresets.json and clang-cl.exe

### ISSUE THREAD

**Issue by BLaZeKiLL** [microsoft/vscode-cmake-tools#1897]
### Brief Issue Summary

When configuring without CMakePresets.json everything works fine but when I use the CMakePresets.json for vcpkg integration configuration fails with the error Ninja not found. 

Ninja ,Cmake and Clang are installed on my system as part of Visual Studio 2019

### Expected:

1. Create CMakePresets.json 
2. Press F7 for configure
3. Configuration should be generated

### Apparent Behavior:

1. Create CMakePresets.json 
2. Press F7 for configure
3. Error is logged stating ninja is not found

### CMake Tools Log

```
[main] Building folder: Sandbox 
[main] Configuring folder: Sandbox 
[proc] Executing command: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_C_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/x64/bin/clang-cl.exe" "-DCMAKE_CXX_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/x64/bin/clang-cl.exe" -DCMAKE_INSTALL_PREFIX=d:/C++/Sandbox/out/install/amd64-windows-clang -DCMAKE_TOOLCHAIN_FILE:FILEPATH=C:/Sdk/vcpkg/scripts/buildsystems/vcpkg.cmake -Hd:/C++/Sandbox -Bd:/C++/Sandbox/out/build/amd64-windows-clang -G Ninja
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/C++/Sandbox/out/build/amd64-windows-clang/CMakeFiles/CMakeOutput.log".
```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.19.20122902-MSVC_2
- **VSCode Version**: 1.56.2
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: Clang 11.0.0 (MSVC CLI) - amd64

### Other Notes/Information

My CMakePreset.json, created by following the box2d-lite example

```
{
  "version": 2,
  "configurePresets": [
    {
      "name": "base-config",
      "description": "Sets generator, build and install directory, vcpkg",
      "hidden": true,
      "generator": "Ninja",
      "binaryDir": "${sourceDir}/out/build/${presetName}",
      "cacheVariables": {
        "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}",
        "CMAKE_TOOLCHAIN_FILE": {
          "type": "FILEPATH",
          "value": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
        }
      },
      "environment": {
        "VCPKG_FEATURE_FLAGS": "manifests,versions,binarycaching,registries"
      }
    },
    {
      "name": "amd64-windows-clang",
      "displayName": "Clang 11.0.0 (MSVC CLI) (Visual Studio Professional 2019 Release - amd64)",
      "inherits": [
        "base-config"
      ],
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Debug",
        "CMAKE_C_COMPILER": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/x64/bin/clang-cl.exe",
        "CMAKE_CXX_COMPILER": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/x64/bin/clang-cl.exe"
      },
      "toolset": {
        "value": "amd64",
        "strategy": "external"
      },
      "architecture": {
        "value": "amd64",
        "strategy": "external"
      },
      "vendor": {
        "microsoft.com/VisualStudioSettings/CMake/1.0": {
          "hostOS": [ "Windows" ]
        }
      }
    }
  ],
  "buildPresets": [
    {
      "name": "base-build",
      "description": "Inherits environment from base-config configurePreset",
      "configurePreset": "base-config",
      "hidden": true,
      "inheritConfigureEnvironment": true
    },
    {
      "name": "build",
      "description": "Clean before build (--clean-first)",
      "configurePreset": "amd64-windows-clang",
      "inherits": "base-build",
      "cleanFirst": true
    }
  ]
}
```

**Comment by andreeis** [comment]
@BLaZeKiLL, thank you for opening this report. This looks like a bug and we will investigate and fix it.
In the meantime, try to add in your preset environment variables the path to your ninja installation. It is very probably that this will unblock you. Please let us know if this idea works or not.

**Comment by BLaZeKiLL** [comment]
I added ninja to the preset path and got another error that rc command was not found (part of windows sdk) So I assumes that in case of CMakepresets.json the path variable from vs-dev-shell are not being loaded so I copied my PATH variable from vs-dev-shell 
and this time I got this error

```
[proc] Executing command: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_C_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/bin/clang-cl.exe" "-DCMAKE_CXX_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/bin/clang-cl.exe" -DCMAKE_INSTALL_PREFIX=d:/C++/Sandbox/out/install/amd64-windows-clang -DCMAKE_TOOLCHAIN_FILE:FILEPATH=C:/Sdk/vcpkg/scripts/buildsystems/vcpkg.cmake -Hd:/C++/Sandbox -Bd:/C++/Sandbox/out/build/amd64-windows-clang -G Ninja
[cmake] -- The C compiler identification is Clang 11.0.0 with MSVC-like command-line
[cmake] -- The CXX compiler identification is Clang 11.0.0 with MSVC-like command-line
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - failed
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/bin/clang-cl.exe
[cmake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/bin/clang-cl.exe - broken
[cmake] CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:66 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/Llvm/bin/clang-cl.exe"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: D:/C++/Sandbox/out/build/amd64-windows-clang/CMakeFiles/CMakeTmp
[cmake]     
[cmake]     Run Build Command(s):C:/PROGRA~2/MICROS~1/2019/PROFES~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe cmTC_0294e && [1/2] Building C object CMakeFiles\cmTC_0294e.dir\testCCompiler.c.obj
[cmake]     [2/2] Linking C executable cmTC_0294e.exe
[cmake]     FAILED: cmTC_0294e.exe 
[cmake]     cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_0294e.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\Llvm\bin\lld-link.exe /nologo CMakeFiles\cmTC_0294e.dir\testCCompiler.c.obj  /out:cmTC_0294e.exe /implib:cmTC_0294e.lib /pdb:cmTC_0294e.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cmd.exe /C "cd /D D:\C++\Sandbox\out\build\amd64-windows-clang\CMakeFiles\CMakeTmp && "C:\Program Files\PowerShell\7\pwsh.exe" -noprofile -executionpolicy Bypass -file C:/Sdk/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/C++/Sandbox/out/build/amd64-windows-clang/CMakeFiles/CMakeTmp/cmTC_0294e.exe -installedDir C:/Sdk/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
[cmake]     LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\Llvm\bin\lld-link.exe /nologo CMakeFiles\cmTC_0294e.dir\testCCompiler.c.obj /out:cmTC_0294e.exe /implib:cmTC_0294e.lib /pdb:cmTC_0294e.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_0294e.dir/intermediate.manifest CMakeFiles\cmTC_0294e.dir/manifest.res" failed (exit code 1) with the following output:
[cmake]     lld-link: error: could not open 'kernel32.lib': no such file or directory
[cmake]     lld-link: error: could not open 'user32.lib': no such file or directory
[cmake]     lld-link: error: could not open 'gdi32.lib': no such file or directory
[cmake]     lld-link: error: could not open 'winspool.lib': no such file or directory
[cmake]     lld-link: error: could not open 'shell32.lib': no such file or directory
[cmake]     lld-link: error: could not open 'ole32.lib': no such file or directory
[cmake]     lld-link: error: could not open 'oleaut32.lib': no such file or directory
[cmake]     lld-link: error: could not open 'uuid.lib': no such file or directory
[cmake]     lld-link: error: could not open 'comdlg32.lib': no such file or directory
[cmake]     lld-link: error: could not open 'advapi32.lib': no such file or directory
[cmake]     lld-link: error: could not open 'msvcrtd.lib': no such file or directory
[cmake]     lld-link: error: could not open 'oldnames.lib': no such file or directory
[cmake]     ninja: build stopped: subcommand failed.
[cmake]     
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:2 (project)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/C++/Sandbox/out/build/amd64-windows-clang/CMakeFiles/CMakeOutput.log".
[cmake] See also "D:/C++/Sandbox/out/build/amd64-windows-clang/CMakeFiles/CMakeError.log".
```

After searching I found this is something related to Clang not using the correct ABI tough couldn't find a fix for my case

Anyway I started digging through the vscode-cmake-tools src code and found this in the `driver.ts`

```typescript
/**
 * Get the environment variables that should be set at CMake-configure time.
 */
async getConfigureEnvironment(): Promise<proc.EnvironmentVariables> {
  if (this.useCMakePresets) {
    return this._configurePreset?.environment as proc.EnvironmentVariables;
  } else {
    let envs = getKitEnvironmentVariablesObject(this._kitEnvironmentVariables);
    /* NOTE: By mergeEnvironment one by one to enable expanding self containd variable such as PATH properly */
    /* If configureEnvironment and environment both configured different PATH, doing this will preserve them all */
    envs = util.mergeEnvironment(envs, await this.computeExpandedEnvironment(this.config.environment, envs));
    envs = util.mergeEnvironment(envs, await this.computeExpandedEnvironment(this.config.configureEnvironment, envs));
      envs = util.mergeEnvironment(envs, await this.computeExpandedEnvironment(this._variantEnv, envs));
      return envs;
    }
  }
```

In case of CMakePresets.json env var from the kit is not being loaded now I assume this is by design since the goal of CMakePresets.json is to give complete control and everything needs to be configured manually.

In any case my original goal was to just get vcpkg integration working and upon searching the docs of vscode-cmake-tools the only mention of vcpkg integration was under CMakePresets,json

I'll try by passing the vcpkg toolchain file through extensions settings and see what happens..

**Comment by andreeis** [comment]
Ok, thank you for trying these workarounds. I am sorry that nothing helped to unblock you. We will investigate and fix the issue.

**Comment by maltevesper** [comment]
To add to @BLaZeKiLL 's point: we have a setup where we do not want to explicitly set the cmake generator, as far as we are concerned we would like cmake to use the default generator it finds on the system so we can easily use the same preset for windows with Visual Studio and Linux with make.
However it seems that adding a minimal preset file autogenerates several unwanted options, i.e. a preset file which only sets the toolchain file results in a cmake call which specifies the generator as Ninja and specifies output directories.

i.e. using this toolchain file:
```
{
    "version": 4,
    "configurePresets": [
        {
            "name": "default",
            "cacheVariables": {
                "CMAKE_TOOLCHAIN_FILE": "${sourceDir}/vcpkg/scripts/buildsystems/vcpkg.cmake"
            }
        }
    ]
}
```

showing the configure command outputs this:
```
/usr/bin/cmake -DCMAKE_TOOLCHAIN_FILE=<projectdir>/vcpkg/scripts/buildsystems/vcpkg.cmake -S<projectdir> -B<projectdir>/out/build/default -G Ninja
```

I think **if the build dir and the generator is unspecified in the preset, the extension should NOT touch those** ! ⚡

**Comment by maltevesper** [comment]
Or am I seeing an incarnation of this and am confused here: https://github.com/microsoft/vscode-cmake-tools/issues/1792#issuecomment-823664675?

**Comment by invy** [comment]
Is there some progress on this issue? Today, while investigating this issue (I've completely forgotten I've seen this one already)I found my own workaround here in this issue.
It would be nice if VSCode CMake Tools would be able to find all it needs for configuring project. Somehow "Scan for Kits' didn't work and the only viable workaround was running vscode from developer command prompt.

**Comment by gcampbell-msft** [comment]
This seems very likely to be related to #3497

**Comment by qarni** [comment]
Hi, @BLaZeKiLL, and @invy if still interested, could you please test this version of cmaketools:
[cmake-tools-1.13.0.zip](https://github.com/user-attachments/files/16076385/cmake-tools-1.13.0.zip) and let us know if it fixes your issue? Please make sure to change the extension from `zip` to `vsix` and install it from the Extensions menu.

**Comment by gcampbell-msft** [comment]
@BLaZeKiLL @invy I wanted to follow up here and clarify some things. 

When using CMakePresets, **nothing from the Kits experience is used**. 

@invy Is mostly right about the goal of using CMakePresets, however, one caveat is the use of CMakePresets by itself doesn't do anything for finding what it needs. 
The CMake Tools extension, based on what you have in your preset, will conditionally attempt to add the VS Developer Environment to your environment. However, this is conditional on us confirming that your compiler (cl, clang-cl, or clang++) can't be found on the system. 

@BLaZeKiLL For the repro mentioned originally, in [this comment](https://github.com/microsoft/vscode-cmake-tools/issues/1897#issue-898773016), the reason that we aren't adding any VS developer environment is because your `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` paths are absolute paths, so we assume that you already have the tools necessary installed and we don't need to interrogate whether they exist. 

Some improvements I'm investigating are
1. Ensuring that we correctly apply the VS DevEnv and don't override any modifications to the environment from a preset. 
2. Adding support for, even if we find that cl, clang-cl, clang++, if relatively referenced (e.g. `"CMAKE_C_COMPILER": "cl.exe"`), exists on the system, if ninja isn't found on the system (when ninja is your generator) we will also apply the VS DevEnv to ensure you can use Ninja. 

@invy @BLaZeKiLL  
I have a test installation of the extension here: [cmake-tools.zip](https://github.com/user-attachments/files/16163882/cmake-tools.zip)
You'll need to download it, change the extension of the file to `.vsix` and then manually install it using the Extension pane in VS Code. Please let me know what you think and if it works for you!
