### ISSUE TITLE
Add support for CMake 3.21 and CMakePresets.json v3 files

### ISSUE THREAD

**Issue by esweet431** [microsoft/vscode-cmake-tools#1904]
Kitware is incrementing the version of CMakePresets.json files in CMake 3.21. We need to support CMakePresets.json v3 files and CMake 3.21 in cmake-tools.

**Comment by esweet431** [comment]
In addition to supporting v3 files, there are also some features we can light up in the extension. 

- Respect any specified condition(s) when surfacing presets for selection. If the preset is not enabled then it should not be available for selection. I think this also makes our "hostOS" object obsolete - we can continue to support it (for at least a few releases), but we should change our templates to add a condition where ${hostSystemName} == Windows/Linux /Darwin
- Modify IntelliSense to use installDir and toolchainFile instead of the cacheVariables in cases where the user is using a file with version >= 3

**Comment by KUGA2** [comment]
[CMake 3.21](https://discourse.cmake.org/t/cmake-3-21-0-available-for-download/3756) is now released. Do you have a plan when this will be availible in cmake-tools?
Or at least make the [parser less picky](https://github.com/microsoft/vscode-cmake-tools/issues/1963#issuecomment-874915188).

**Comment by anb0s** [comment]
We have also switched to CMakePresets.json v3 and wanted to use `toolchainFile` instead of `cacheVariables.CMAKE_TOOLCHAIN_FILE` because CMake shows warning during build step. Is there a timeline for release of next plugin version or a beta release? Thanks!

**Comment by bobbrow** [comment]
@anb0s thanks for asking.  You can try a preview of this feature by following these steps:
1. Download the build artifact from here: https://github.com/microsoft/vscode-cmake-tools/suites/3758389143/artifacts/92322935
2. Unzip the VSIX file
3. Run the `Install from VSIX...` command and select the VSIX file.
Let us know if you have any issues with it.
