### ISSUE TITLE
Modifying the Build tools always breaks CMake tools

### ISSUE THREAD

**Issue by FelixBenning** [microsoft/vscode-cmake-tools#1913]
### Brief Issue Summary

So I tried to change the build tools because I had trouble with a python package (probably because of the compiler version) anyway afterwards cmake tools stopped working, first it did not recognize ninja at all, so I manually put the location of it into the path but now it complains about the compiler (which it does not do if I remove the ninja path) The fact that I can select the Build Kit makes this even more ridiculous.

This is the second time this happened. Previously I wanted to swap my harddrive anyway so I just reinstalled windows and everything worked out of the box again. But you just touch the visual studio build tools lightly and everything falls apart. It is sooo frustrating.

```shell
[main] Building folder: grazer 
[main] Configuring folder: grazer 
[proc] Executing command: "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -Hd:/code/grazer -Bd:/code/grazer/Debug -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is unknown
[cmake] -- The CXX compiler identification is unknown
[cmake] CMake Error at CMakeLists.txt:6 (project):
[cmake]   No CMAKE_C_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
[cmake]   the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:6 (project):
[cmake]   No CMAKE_CXX_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
[cmake]   to the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/code/grazer/Debug/CMakeFiles/CMakeOutput.log".
[cmake] See also "D:/code/grazer/Debug/CMakeFiles/CMakeError.log".
```

### Expected:

It should be possible to reinstall CMakeTools and the Build Tools and get the same result as after the first installation

### Apparent Behavior:

Only the first installation works

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.20.21032501-MSVC_2
- **VSCode Version**: 1.56.2
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**:  Visual C++ 2019

**Comment by bobbrow** [comment]
Does the `CMake: Delete Cache and Reconfigure` command work for you?  It is supposed to clean up these kinds of things.  It shouldn't require a reinstall of the extension.

If that doesn't work, can you share the contents of your Kits file?  Run the `CMake: Edit User-Local CMake Kits` command to see them.  If you are using the new CMakePresets instead of Kits, can you please share the contents of your `CMakePresets.json` file?

**Comment by FelixBenning** [comment]
@bobbrow Sorry for my tone, I was really frustrated that time - thank you for helping :)


Output from `Delete Cache and Reconfigure`

<details>

<summary>Same as when pressing configure</summary>

```shell
[main] Configuring folder: grazer 
[driver] Removing d:/code/grazer/Debug/CMakeCache.txt
[driver] Removing d:\code\grazer\Debug\CMakeFiles
[proc] Executing command: "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -Hd:/code/grazer -Bd:/code/grazer/Debug -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is unknown
[cmake] -- The CXX compiler identification is unknown
[cmake] CMake Error at CMakeLists.txt:7 (project):
[cmake]   No CMAKE_C_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
[cmake]   the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:7 (project):
[cmake]   No CMAKE_CXX_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
[cmake]   to the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/code/grazer/Debug/CMakeFiles/CMakeOutput.log".
[cmake] See also "D:/code/grazer/Debug/CMakeFiles/CMakeError.log".
```

</details>


Kits file: 
```json
[
  {
    "name": "Visual Studio Build Tools 2019 Release - amd64",
    "visualStudio": "889672fb",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "host=x64"
    }
  },
  {
    "name": "Visual Studio Build Tools 2019 Release - amd64_x86",
    "visualStudio": "889672fb",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "win32",
      "toolset": "host=x64"
    }
  },
  {
    "name": "Visual Studio Build Tools 2019 Release - x86",
    "visualStudio": "889672fb",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "win32",
      "toolset": "host=x86"
    }
  },
  {
    "name": "Visual Studio Build Tools 2019 Release - x86_amd64",
    "visualStudio": "889672fb",
    "visualStudioArchitecture": "x86",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "host=x86"
    }
  }
]
```

**Comment by bobbrow** [comment]
I'm not sure what's going on because I don't have a repro yet, but could you check one more thing for me?

Run the `Developer: Toggle Developer Tools` command, then in the `Console` tab, search for `varsForVS` and see if there is a log line for that.
![image](https://user-images.githubusercontent.com/12818240/121068135-bddc3a00-c780-11eb-8dbb-91c35a5882b9.png)

If it is there and you don't see a corresponding
```
[kit] OK running C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Auxiliary\Build\vcvarsall.bat x86, env vars:
```
In your log Output, then something failed along the way.  (Note that `cmake.loggingLevel` needs to be set to `"debug"` for this message to appear in the Output)

**Comment by bobbrow** [comment]
And these messages should only print when you set the Kit for the first time, so you might need to reload the window and try again if you don't see them.
