### ISSUE TITLE
minor issues in documentation

### ISSUE THREAD

**Issue by icegood** [microsoft/vscode-cmake-tools#1918]
documentation from vscode links to the wrong location e.g.

https://github.com/microsoft/vscode-cmake-tools/blob/master/docs/cmake-presets.md

Similar doc could be found in develop branch

**Comment by bobbrow** [comment]
Could you tell us the URL of the document needs to be updated?  I see that it is correct here: https://code.visualstudio.com/docs/cpp/cmake-linux
