### ISSUE TITLE
Add support for Fortran

### ISSUE THREAD

**Issue by bscollin** [microsoft/vscode-cmake-tools#1920]
### Brief Issue Summary

When building Fortran projects, vscode-cmake-tools is logging "Unknown language" warnings for Fortran language and f2008 control flags:
```
[cpptools] Unknown language: Fortran
[cpptools] Unknown standard control flag: -std=f2008
```

### Expected:

Fortran code bases produce no warnings when built using cmake-tools.

### CMake Tools Log

```
[cpptools] Unknown language: Fortran
[cpptools] Unknown standard control flag: -std=f2008
```

### Platform and Versions

- **Operating System**: Windows with Ubuntu subsystem (WSL2)
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.56.0
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: GFORTRAN 9.3.0

### Other Notes/Information

I've found similar issues #1108 that seems to have similar issues.  I'm assuming support of Fortran will be more difficult to add.  Even the ability to disable these warnings would be very useful without disabling all build/compiler warnings.

**Comment by bobbrow** [comment]
The issue covering Fortran support is #1506.  It is not on our roadmap, but we will accept PR's from the community if someone is willing to implement it, or even just to suppress certain logging messages.
