### ISSUE TITLE
Separate options for toolchain and kit

### ISSUE THREAD

**Issue by armandas** [microsoft/vscode-cmake-tools#1925]
### Brief Issue Summary

I am working on several embedded projects, each of which have a toolchain file. As this toolchain file is project specific, I would like to define it in the .vscode/cmake-kits.json file of the project.

On the other hand, the compiler (kit) is a system specific option. Each developer may have the compiler installed in a different location, or may want to use a different version for some reason.

### Expected:

1. The project configuration provides a fixed toolchain file.
2. The developer selects a kit that is available on their machine.
3. The project is build using a user-selected kit and the project defined toolchain file.

### Apparent Behavior:

The toolchain file and kit are tied to each other, so the compiler path must be fixed.

**Comment by andreeis** [comment]
Thank you for the feature idea. We may not be able to get to this immediately and we will continue to monitor the reactions from the community to find how this best fits in our backlog.
In the meantime, maybe you can achieve the same goal by using [presets](https://cmake.org/cmake/help/git-stage/manual/cmake-presets.7.html).

**Comment by bobbrow** [comment]
Does adding this setting address the problem for you?
```
 "cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE": "/path/to/toochain/file"
  }
```

**Comment by armandas** [comment]
> Does adding this setting address the problem for you?
> 
> ```
>  "cmake.configureSettings": {
>     "CMAKE_TOOLCHAIN_FILE": "/path/to/toochain/file"
>   }
> ```

That does the job! Thank you!
