### ISSUE TITLE
`cmake` task provider is not available until a build preset is selected

### ISSUE THREAD

**Issue by benmcmorran** [microsoft/vscode-cmake-tools#1926]
### Brief Issue Summary

For projects using CMakePresets.json, there is no `cmake` task provider available until after a build preset is selected.

### Expected:

Create a project with these files:

`.vscode/tasks.json`

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "cmake",
            "command": "build"
        }
    ]
}
```

`CMakeLists.txt`

```cmake
cmake_minimum_required(VERSION 3.20)
project(example)
add_executable(example main.cpp)
```

`CMakePresets.json`

```json
{
    "version": 2,
    "configurePresets": [
        {
            "name": "example",
            "binaryDir": "build",
            "generator": "Visual Studio 16 2019"
        }
    ]
}
```

`main.cpp`

```cpp
int main() {}
```

1. Open the folder, select the "example" configure preset, and configure the project.
2. Press F1, select Tasks: Run Task, and select Build.
3. Expected behavior: the extension asks the user to select a build preset.

### Apparent Behavior

There is an error message saying "There is no task provider registered for tasks of type "cmake"." This message does not appear if a build preset is selected.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.20
- **VSCode Version**: 1.56.2
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: N/A

**Comment by esweet431** [comment]
We should default to the “Default” Build Preset once a Configure Preset is selected if no build presets exist.

**Comment by andreeis** [comment]
It was also proposed to have the extension prompt for a build preset when invoking a build task and no build preset is defined.

**Comment by esweet431** [comment]
Ideally, we will:
- Automatically select the "Default" Build Preset once a Configure Preset is selected if no Build Presets exist, and
- Have the extension prompt for a Build Preset when invoking a build task if no Build Preset is selected and Build Preset(s) exist
