### ISSUE TITLE
Status bar behavior of passing tests does not update when Test Preset changes 

### ISSUE THREAD

**Issue by esweet431** [microsoft/vscode-cmake-tools#1928]
I'm opening this bug on behalf of a customer. 

### Steps to reproduce:

1. Select a config-preset, build-preset and test-preset 
2. Run the tests - note that the status bar says "n/n tests passing"
3. Change to a different config-preset, build-preset and test-preset

### Expected behaviour:
Status bar indicates that tests have not been run

### Actual behaviour:
status bar still says "n/n tests passing"....

### Environment:

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0

**Comment by andreeis** [comment]
Thank you for creating this report. We will fix this.

**Comment by claremacrae** [comment]
> Thank you for creating this report. We will fix this.

Thank you - much appreciated!
