### ISSUE TITLE
How to specify Visual Studio Developer Environment when using CMakePresets.json?

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#1929]
I have been working successfully with CMakePresets.json in VS 2019 and am now trying with VS Code.  I am working on a Windows build, using the Ninja Generator.

In VS Code I opened the same folder as in VS 2019 and selected a Configure Preset that has an existing CMake cache (built in VS 2019).  I see:

```
[cmake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.29.30129/bin/Hostx64/x64/cl.exe - broken
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeTestCXXCompiler.cmake:59 (message):
[cmake]   The C++ compiler
[cmake] 
[cmake]     "C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.29.30129/bin/Hostx64/x64/cl.exe"
[cmake] 
[cmake]   is not able to compile a simple test program.
```
I guess this means that the environment normally provided by the Visual Studio Developer Prompt isn't active.  How can I fix this please?

**Comment by bobbrow** [comment]
This is supposed to work.  Can you share your presets?  Are you using the Visual Studio generator or Ninja?

**Comment by DavidA2014** [comment]
@bobbrow I am using Ninja. Here are the presets I am using:

`{
    "version": 2,
    "configurePresets": [
      {
        "name": "windows-base",
        "description": "Base configuration to target Windows with the Visual Studio development environment, using Ninja generator.",
        "hidden": true,
        "generator": "Ninja",
        "binaryDir": "${sourceDir}/builds/${presetName}",
        "architecture": {
          "value": "x64",
          "strategy": "external"
        },
        "cacheVariables": {
          "CMAKE_BUILD_TYPE": "Debug",
          "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}"
        },
        "vendor": { "microsoft.com/VisualStudioSettings/CMake/1.0": { "hostOS": [ "Windows" ] } }
      },
      {
        "name": "windows-athena",
        "displayName": "Windows x64 Athena Release",
        "description": "Target Windows with the Visual Studio development environment.",
        "hidden": false,
        "inherits": "windows-base",
        "cacheVariables": {
          "CMAKE_BUILD_TYPE": "Release",
          "PROJECT_VARIANT": "Athena"
        },
        "vendor": {}
      }
    ],
    "buildPresets": [
      {
        "name": "windows-core-build",
        "description": "Inherits environment from base Windows configurePreset",
        "configurePreset": "windows-base",
        "hidden": true,
        "inheritConfigureEnvironment": true
      },          
      {
        "name": "windows-athena-quiet",
        "displayName": "quiet build",
        "description": "Run Ninja in non-verbose mode",
        "configurePreset": "windows-athena",
        "inherits": "windows-core-build"
      }
    ]
  }`

**Comment by bobbrow** [comment]
You need to add:
```
            "CMAKE_C_COMPILER": "cl.exe",
            "CMAKE_CXX_COMPILER": "cl.exe",
```
to your `cacheVariables` and then we will know to pick up the Visual Studio environment.

**Comment by DavidA2014** [comment]
@bobbrow Thanks for your solution. It's working now.  However, I do see:

    [preset] Configure preset windows-base: No toolset architecture specified for cl.exe, using x86 by default
    [preset] Configure preset windows-athena: No toolset architecture specified for cl.exe, using x86 by default

I do have:

        "configurePresets": [
        {
            "name": "windows-base",
            "description": "Base configuration to target Windows with the Visual Studio development environment, using Ninja generator.",
            "hidden": true,
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/builds/${presetName}",
            "architecture": {
            **"value": "x64",**
            "strategy": "external"
            },

I want to build for x64.  Is architecture::value not enough?

**Comment by bobbrow** [comment]
You are setting architecture, but not toolset.  Can you add:
```
            "toolset":{
                "value": "x64",
                "strategy": "external"
            },
```

**Comment by DavidA2014** [comment]
@bobbrow Thanks, it's working well with that change.

**Comment by bobbrow** [comment]
I'm not sure how I got that to work before, but CMake expects the toolset value to be of the form 'host=x64' if you want to pick the 64-bit version of the compiler.  I updated the json snippet above.
