### ISSUE TITLE
How to pass --trace(-expand) if using CMakePresets.json

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vscode-cmake-tools#1930]
Simple question:
How to pass `--trace(-expand)` if I am using `CMakePresets.json`? 
I tried a wrapper like:
`"cmakeExecutable": "cmake-trace.bat"`
but it seems like the extension is seeing through that and just calling cmake

**Comment by andreeis** [comment]
According to [CMake presets documentation](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html), cmakeExecutable is 

> An optional string representing the path to the CMake executable to use for this preset. This is reserved for use by IDEs, and is not used by CMake itself. IDEs that use this field should expand any macros in it.

As to how to pass --trace-expand switch to cmake when using presets, I wasn't able to find a way. Adding @esweet431.
Probably you know that without presets (when using kits) you can define "cmake.configureArgs".

**Comment by esweet431** [comment]
Hmm, I'm not sure either. I recommend opening an issue with Kitware to see if they have a recommendation on how to encode --trace or --trace-expand in a presets file.

**Comment by bobbrow** [comment]
Closing upstream issue
