### ISSUE TITLE
Broken links on visualstudio marketplace

### ISSUE THREAD

**Issue by stobor827** [microsoft/vscode-cmake-tools#1931]
The description for this extension on VS marketplace has broken links
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools

(Try visiting 'Debug a Project' Under 'Important Doc links')
Unsure on how all these pages get generated, perhaps related to 'master' no longer being the default branch?

**Comment by bobbrow** [comment]
It looks like a bug with the Marketplace.  We don't specify a branch in our repository where the docs live and they assume it's master (which doesn't exist).  They are rendering our README.md which works when you view it from github.com.

**Comment by andreeis** [comment]
@stobor827, I just checked the links and they seem to work now. I am closing this report but if you notice anything different feel free to reactivate.
