### ISSUE TITLE
Still getting build diagnostics with cmake.parseBuildDiagnostics = false

### ISSUE THREAD

**Issue by alexdesaint** [microsoft/vscode-cmake-tools#1932]
I have `"cmake.parseBuildDiagnostics": false` but still get error reported in the code as `GCC`.

![image](https://user-images.githubusercontent.com/33799602/122021992-7aa84980-cdc6-11eb-8422-3e00bbc0443e.png)

or in the error section:
![image](https://user-images.githubusercontent.com/33799602/122022678-1b970480-cdc7-11eb-80c4-b163225c9625.png)

- **Operating System**: Windows
- **CMake Version**: 3.20
- **VSCode Version**: 1.57
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: clang12

**Comment by bobbrow** [comment]
Thanks for opening this issue.  This was mentioned in my comment in #1266, but a separate issue was never opened, so we lost track of it.

**Comment by bobbrow** [comment]
Workaround: use `"cmake.enabledOutputParsers"` setting to hide the diagnostics you don't want to see.
