### ISSUE TITLE
Missing cmake.debugConfig documentation?

### ISSUE THREAD

**Issue by pearson** [microsoft/vscode-cmake-tools#1936]
### Brief Issue Summary

There does not seem to be any documentation on the `cmake.debugConfig` settings option. Specifically, the documentation page [Configure CMake Tools settings](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md#cmake-settings) does not list this setting, and searches turn up little information.

**Comment by andreeis** [comment]
@pearson, thank you for reminding us of this. I added a bullet in the workitem https://github.com/microsoft/vscode-cmake-tools/issues/1246 which will track several similar documentation updates. And I am closing this.
