### ISSUE TITLE
additional 'configure' arguments are applied to 'build'

### ISSUE THREAD

**Issue by jjacobsohn** [microsoft/vscode-cmake-tools#1939]
### Brief Issue Summary

The project I'm building requires an additional argument (-DBUILD_DEPS=ON) at the configure stage. I set this using the extension's settings. Configure succeeds, but now builds fails because that argument appears on the cmake command line and is not recognized 

### Expected:

build command line should be:
 /usr/local/bin/cmake --build /home/jeremy/Development/or-tools --config Release --target all  -j 8 --

but it is:
 /usr/local/bin/cmake --build /home/jeremy/Development/or-tools --config Release --target all -DBUILD_DEPS=ON -j 8 --

### Apparent Behavior:

the value of 'Configure Args' shows up in an unwanted place

### Platform and Versions

- **Operating System**: Debian remote from MacOS host
- **CMake Version**: 3.21
- **VSCode Version**: 1.57.0
- **CMake Tools Extension Version**: 1.73
- **Compiler/Toolchain**: clang 11.1.0

**Comment by andreeis** [comment]
Thank you for opening this issue. We will look at this. In the meantime, does it happen the same if you use "cmake.configureSettings" instead of "cmake.configureArgs"? I am hoping that maybe this would unblock you until we fix the problem with configureArgs.

 "cmake.configureSettings": {
        "BUILD_DEPS" : "ON"
  },

**Comment by jjacobsohn** [comment]
I tried the experiment - but not sure I did it correctly. I get a different error on CMake configure:
cmake] CMake Error at /usr/local/share/cmake-3.21/Modules/FindPkgConfig.cmake:554 (message):
[cmake]   A required package was not found
[cmake] Call Stack (most recent call first):
[cmake]   /usr/local/share/cmake-3.21/Modules/FindPkgConfig.cmake:776 (_pkg_check_modules_internal)
[cmake]   cmake/FindProtobuf.cmake:25 (pkg_check_modules)
[cmake]   cmake/deps.cmake:45 (find_package)
[cmake]   CMakeLists.txt:246 (include)

I appreciate the suggestion, but I am unblocked by returning to the good old fashioned command line!  
  cmake . -DBUILD_DEPS=ON; cmake --build .
