### ISSUE TITLE
The example on "Get started with CMake Tools on Linux" doesn't work

### ISSUE THREAD

**Issue by parsley72** [microsoft/vscode-cmake-tools#1940]
### Brief Issue Summary

The example on "Get started with CMake Tools on Linux" doesn't work:
https://code.visualstudio.com/docs/cpp/cmake-linux

### Expected:

Described in the web page example.

### Apparent Behavior:

1. Ensure that CMake is installed
```
$ cmake --version
cmake version 3.16.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
2. Check if GCC is installed
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
```
3. Create a CMake project
3.1 Create a CMake hello world project
3.1.1 Open the Command Palette (Ctrl+Shift+P) and run the CMake: Quick Start command
- I get "Select a kit for cmakeQuickStart".
- Selecting [Scan for kits] exits the quick start.
- I have to select a kit, e.g. GCC 9.3.0

3.1.2 Enter a project name
3.1.3 select **Executable**
3.2 Select a kit
- Should this be before 3.1?
4. Configure Hello World
4.1 Select a variant
4.2 Run the **CMake: Configure** command
5. Build hello world
- Shows "No build task to run found. Configure build task..." at the top.
```
[main] Building folder: cmakeQuickStart 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/tom/Documents/cmakeQuickStart/build --config Debug --target all -j 14 --
[build] Build finished with exit code 0
```
- No cmakeQuickStart executable is created.
6. Debug hello world
6.1 Open the Command Palette (Ctrl+Shift+P) and run **CMake: Debug**
```
[main] Building folder: cmakeQuickStart cmakeQuickStart
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/tom/Documents/Bitbucket/cmakeQuickStart/build --config Debug --target cmakeQuickStart -j 14 --
[build] Build finished with exit code 0
[proc] Executing command: /usr/bin/gdb --version
```
- A popup dialog appears with "launch: program '/home/tom/Documents/cmakeQuickStart/-build/cmakeQuickStart' does not exist"

### Platform and Versions

- **Operating System**: Ubuntu 20.04
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.57.1
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: GCC 9.3.0

### Other Notes/Information

If I copy the build command to the terminal it works fine and the executable is created:
```
$ cmake --build build --config Debug --target all -j 14 --
Scanning dependencies of target cmakeQuickStart
[ 50%] Building CXX object CMakeFiles/cmakeQuickStart.dir/main.cpp.o
[100%] Linking CXX executable cmakeQuickStart
[100%] Built target cmakeQuickStart
```

**Comment by andreeis** [comment]
Thank you for opening this report. I will go through the steps you described and try to reproduce. In the meantime, can you confirm if the folder that was opened in VSCode before running the "Quick Start" command was empty? I am thinking that maybe it already had some files that confused the extension, like some json tasks or....
If you have a windows system available, do you see the same repro steps leading to the same result as on linux?

**Comment by parsley72** [comment]
I followed the instructions and created a completely new folder.

**Comment by parsley72** [comment]
Windows works fine, although I'm not sure how relevant that is.

**Comment by andreeis** [comment]
@esweet431, can you have a look at what happens here on linux and eventually update the documentation, or let us know if there is a bug we missed?

**Comment by parsley72** [comment]
Was anything fixed here?
