### ISSUE TITLE
cmake.cmakePath changes not used until VSCode restart

### ISSUE THREAD

**Issue by pearson** [microsoft/vscode-cmake-tools#1943]
### Brief Issue Summary

Any changes made to `cmake.cmakePath` are not used by cmake-tools until VSCode is restarted. (Tested on Windows 10.)

### Expected:

If the `cmake.cmakePath` is changed, cmake-tools should use the new path for a "CMake: Build".

### Apparent Behavior:

A change to `cmake.cmakePath` is not reflected in the behavior of cmake-tools.

1. Open the `settings.json` file (or the normal "Settings" dialog and edit `cmake.cmakePath` to point to an alternate valid install with `cmake.exe`.
2. Press the "Build" button or use "CMake: Build".
3. In the output window, notice that the command executed was for the original `cmake.exe` path .
4. Examining the `cmake.tasksBuildCommand` variable will show that the original `cmake.exe` path is still in use.

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.20.3
- **VSCode Version**: 1.57.0 (system setup)
- **CMake Tools Extension Version**: v1.7.3
- **Compiler/Toolchain**: GCC 10.2.1 arm-none-eabi

### Other Notes/Information

An interesting note here is that if an invalid `cmake.exe` name and path is entered, and the "CMake: Build" command is run, an error will pop up. However, if the name and path is corrected back to the alternate `cmake.exe` install path and the "CMake: Build" command is run, it will use the original `cmake.exe` install path, not the alternate one.

It appears that "CMake: Build" checks if the current `cmake.cmakePath` is valid, but it then uses whatever `cmake.cmakePath` was set to when VSCode started for the actual build.

**Comment by andreeis** [comment]
Thank you for opening this issue. We will fix this.
