### ISSUE TITLE
CMakePresets.json schema is too restrictive

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-cmake-tools#1963]
### Brief Issue Summary

I cannot add the new CMake 3.21 feature "conditions" to the CMakePresets.json without breaking cmake-tools. Or any other feature that might come.

The plugin validates the CMakePresets.json and does not load it.
The same issue was seen here https://github.com/microsoft/vscode-cmake-tools/issues/1934, but this Issue is for a more general issue.

### Apparent Behaviour

Tooltip:
![image](https://user-images.githubusercontent.com/10581931/123763173-cfb68600-d8c3-11eb-9bad-5586e30cf3e1.png)

And no preset found:
![image](https://user-images.githubusercontent.com/10581931/123763309-ec52be00-d8c3-11eb-9177-1d9e5caa605f.png)

#### Code:

```
        {
            "name": "x86_64-windows-user-vs2019-Release",
            ...
            "condition": {
                "type": "equals",
                "lhs": "$env{VSCMD_ARG_TGT_ARCH}",
                "rhs": "x64"
            }
        },
```

### Expected:

It should leave the validation to cmake.exe. e.g. you could run cmake --list-presets and then offer those shown (this will also implicitly enable the condition feature).

```
$ set | grep VSCMD_ARG_TGT_ARCH
VSCMD_ARG_TGT_ARCH=x86

$ cmake --list-presets
Available configure presets:

  "x86-windows-user-vs2019-Release"
```

### CMake Tools Log

```
[presetController] Invalid kit contents CMakePresets.json (d:\git\xx\CMakePresets.json):
[presetController]  >> /configurePresets/1: should NOT have additional properties
[presetController]  >> /configurePresets/2: should NOT have additional properties
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.21.0-rc1
- **VSCode Version**: 1.57.1
- **CMake Tools Extension Version**: private build. see https://github.com/microsoft/vscode-cmake-tools/issues/1934
- **Compiler/Toolchain**: VS2019

**Comment by bobbrow** [comment]
It looks like we are going to need to make the schema check optional when the presets file version is higher than what we support.  Thanks for reporting this!

**Comment by KUGA2** [comment]
Hi @bobbrow, why validate it at all? Just run `cmake --list-presets` and display those presets. Leave the verfication to cmake executable.

**Comment by bobbrow** [comment]
Kitware's recommendation to IDEs is to get the information out of the presets file and invoke the CLI with those parameters instead of using `--preset`.  That's perhaps a discussion we need to revisit.  The other benefit of schema validation is that we can provide IntelliSense help when making changes to the file.  But if the schema is unstable because Kitware is adding stuff to it every release, we are going to have problems with that.

**Comment by bobbrow** [comment]
Tagging: @esweet431

**Comment by KUGA2** [comment]
> 
> 
> Kitware's recommendation to IDEs is to get the information out of the presets file and invoke the CLI with those parameters instead of using `--preset`.

I have also seen this recommendation but cannot find it anymore. Maybe they removed it? Can you link it?

**Comment by esweet431** [comment]
The recommendation is part of the IDE integration guide: https://cmake.org/cmake/help/latest/guide/ide-integration/index.html#presets
