### ISSUE TITLE
Preserve focus after Compile/Build/Run commands

### ISSUE THREAD

**Issue by OleksandrKvl** [microsoft/vscode-cmake-tools#1974]
### Brief Issue Summary
When I use keyboard shortcuts like "Compile active file", "Run without debugging", my focus switched to the terminal which is pretty uncomfortable. My common sequence is "compile active file" -> "run" but after I press Ctrl+F7(compile) focus jumps to the terminal and following Shift+F5(run) leads to printing symbols in terminal instead of actual command execution.

### Expected:
Keyboard shortcuts should not affect window focus if that is not their direct responsibility.

1. Use "Compile active file" shortcut
2. Use "Run without debugging" shortcut
3. Project built and run.

### Apparent Behavior:
1. Use "Compile active file" shortcut
2. Use "Run without debugging" shortcut
3. Weird symbol is printed on the terminal

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.20.1
- **VSCode Version**: 1.57.1
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: GCC 11.1

**Comment by andreeis** [comment]
@OleksandrKvl, thank you for opening this report. This would normally be a quick fix but I tried it (send a parameter when we invoke the terminal telling it to not take focus) and for some reason it doesn't work. I want to follow up with the VSCode team.
Also, shortcuts like "F5" simply work even if the focus is in the terminal and I want to follow up with the same team about why user defined key shortcuts impact the terminal instead of being recognized as a key binding and invoking the associated command.

In the mean time, maybe you invoke only "launch in terminal" command which also triggers a build automatically? Do you need compile active file specifically?

**Comment by OleksandrKvl** [comment]
Thank for reply @andreeis, so it looks like if the source of shortcut is "Default" then it works in terminal, otherwise it doesn't? In my setup "Run in terminal" is empty(default value). F5(Debug: start debugging) works from terminal. I like to use "compile active file" because I don't want to trigger the whole project build because it might be much slower while I only need to verify a single file. It's not a showstopper, I can live with it and wait for a fix, good to know that some actions are taken, thanks.

**Comment by zeroxia** [comment]
I found this focus lost issue kind of annoying.

Usually I hit F5 to start debugging, in the building stage, "Output" of CMake/Build is activated, and focus is kept at the editor, which is good.

When build is done, program is launched, I use the integrated terminal, and in the lower panel, the integrated terminal is switched to. But the focus is just lost, not on the VS Code application at all, any key press has no response, e.g., Ctrl-1 to switch editor, Ctrl-J to turn on /off lower panel. In this stage, I can press Windows logo key to activate the start menu, and press Windows logo key again, the focus is back to VS Code, in the integrated terminal, then I can press `Ctrl-BackTick` to switch to editor.

Here is a screen recording:

![Screencast of focus issue](https://i.imgur.com/PhPbk0a.gif)

**Comment by bobbrow** [comment]
Does the `cmake.revealLog` setting help with this scenario for you?  The default behavior should now be to show the log but not change the focus.  Also, VS Code should have fixed their terminal issues earlier this year.

If not, setting the setting to "never" should also fix it.  Please let us know if you continue to have issues with this scenario.
