### ISSUE TITLE
Unable to quick debug after the vscode updated to 1.58

### ISSUE THREAD

**Issue by ActivePeter** [microsoft/vscode-cmake-tools#1986]
### Brief Issue Summary

After I ran this command,
![image](https://user-images.githubusercontent.com/8100696/125021103-942e6f80-e0ac-11eb-8167-da3115aa8eb0.png)
it didn't start debugging and showed the following thing
![image](https://user-images.githubusercontent.com/8100696/125021024-706b2980-e0ac-11eb-8c9b-5f8868675a6f.png)
It is able to debug before the vscode updated.

**Comment by Mempler** [comment]
Bug inside `vscode-cpptools` https://github.com/microsoft/vscode-cpptools/issues/7808

**Comment by ActivePeter** [comment]
> Bug inside `vscode-cpptools` [microsoft/vscode-cpptools#7808](https://github.com/microsoft/vscode-cpptools/issues/7808)

Thanks. I've turned to 1.4.1 and it‘s ok now.

**Comment by sean-mcmanus** [comment]
Fixed with 1.5.1 (https://github.com/microsoft/vscode-cpptools/releases/tag/1.5.1)
