### ISSUE TITLE
Override for inheriting configure environment when debugging/launching

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode-cmake-tools#1987]
There is some internal debate as to which preset should supply the environment by default and how we might provide an override for people who don't like that decision.  Right now, Visual Studio uses the configurePreset environment instead of the build or test preset environment.

_Originally posted by @bobbrow in https://github.com/microsoft/vscode-cmake-tools/issues/1774#issuecomment-873302811_

**Comment by andreeis** [comment]
Using this report for implementing additional cmake commands for getting the environment variables from more precise sources (configure, build, test presets) and controlled by the user.

**Comment by lygstate** [comment]
I think should use test environment  for debug/launch, and build environment for compile source file
