### ISSUE TITLE
CMake Cache Editor UI fails if boolean property names contain "ON"

### ISSUE THREAD

**Issue by Lindurion** [microsoft/vscode-cmake-tools#1992]
### Brief Issue Summary

If a CMake cache boolean property name has the substring "ON" (in my example "ARGHOTUN_ENABLE_EXCEPTIONS"), unchecking it and hitting the SAVE button from the CMake Cache Editor UI makes invalid updates to the CMake cache (instead creating a new cache variable "ARGHOTUN_ENABLE_EXCEPTIFALSES" with value "ON").

### Expected:

1. Uncheck a previously checked boolean property name containing ON (e.g. ARGHOTUN_ENABLE_EXCEPTIONS)
2. Push SAVE button
3. Close and reopen CMake Cache Editor
4. See the new value of boolean property now unchecked and no unwanted properties added

### Apparent Behavior:

1. Uncheck a previously checked boolean property name containing ON (e.g. ARGHOTUN_ENABLE_EXCEPTIONS)
2. Push SAVE button
3. Close and reopen CMake Cache Editor
4. Value of boolean property is still checked
5. A new unwanted CMake cache variable (ARGHOTUN_ENABLE_EXCEPTIFALSES) is now present.

<img width="297" alt="cmake_tools_bug_screenshot" src="https://user-images.githubusercontent.com/1811213/125206621-2aea6000-e256-11eb-8f4b-ec710024f46c.PNG">

### CMake Tools Log

Note that the CMake/Build output console doesn't seem to have any output about the CMake Cache Editor change; here is the next output that appears as part of the automatic reconfigure that runs:

[main] Configuring folder: arghotun-proto-cpp 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -Hc:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp -Bc:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp/build -G "Visual Studio 16 2019" -T host=x64 -A x64
[cmake] Not searching for unused variables given on the command line.
[cmake] -- 
[cmake] -- 3.17.3.0
[cmake] -- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: C:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp/build

### Developer Tools Log

[Extension Host] [CMakeTools] 2021-07-11T18:48:19.751Z [debug] [extension] [3978] cmake.editCacheUI started
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:19.866Z [debug] [cache] Reading CMake cache file c:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:19.867Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:19.887Z [debug] [extension] [3978] cmake.editCacheUI finished (returned 0)
main.js:701 Blocked autofocusing on a <input> element in a cross-origin subframe.
(anonymous) @ main.js:701
setTimeout (async)
L @ main.js:699
(anonymous) @ main.js:730
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.060Z [debug] [cache] Reading CMake cache file c:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.061Z [debug] [cache] Parsing CMake cache string
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.099Z [info] [main] Configuring folder: arghotun-proto-cpp 
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.099Z [debug] [main] Saving open files before configure/build
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.360Z [debug] [driver] Run _refreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.360Z [debug] [driver] Run _refreshExpansions cb
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.365Z [debug] [driver] Start configure 
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.365Z [debug] [driver] Runnnig pre-configure checks and steps
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.372Z [debug] [driver] Run _refreshExpansions
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.372Z [debug] [driver] Run _refreshExpansions cb
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.378Z [debug] [cmakefileapi-driver] Configuring using kit
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.378Z [debug] [cmakefileapi-driver] Invoking CMake C:\Program Files\CMake\bin\cmake.EXE with arguments ["--no-warn-unused-cli","-Hc:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp","-Bc:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp/build","-G","Visual Studio 16 2019","-T","host=x64","-A","x64"]
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.385Z [info] [proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -Hc:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp -Bc:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp/build -G "Visual Studio 16 2019" -T host=x64 -A x64
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:27.426Z [info] [cmake] Not searching for unused variables given on the command line.
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:29.724Z [info] [cmake] -- 
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:29.724Z [info] [cmake] -- 3.17.3.0
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:30.944Z [info] [cmake] -- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:42.480Z [info] [cmake] -- Configuring done
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:44.466Z [info] [cmake] -- Generating done
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:45.008Z [info] [cmake] -- Build files have been written to: C:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp/build
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:45.027Z [debug] [cmakefileapi-parser] Read reply folder: c:\Users\eric\GitHub\arghotuning\arghotun-proto-cpp\build\.cmake\api\v1\reply
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:45.028Z [debug] [cmakefileapi-parser] Found index files: ["cache-v2-db75c7dd50e8d041f43f.json","codemodel-v2-5efcc6c323d49b73be2e.json","index-2021-07-11T18-48-45-0001.json","target-ALL_BUILD-Debug-07bc5bf199bf200d9be0.json","target-ALL_BUILD-Debug-481cae9387489caaae17.json","target-ALL_BUILD-Debug-9fa54896336bcf9a26dc.json","target-ALL_BUILD-Debug-a79cc6fc2af231e0d489.json","target-ALL_BUILD-Debug-b4742cf98b38c1e500bd.json","target-ALL_BUILD-Debug-f2d053cbac7157c669b0.json","target-ALL_BUILD-Debug-f58ffed3fb42eaefcc8c.json","target-ALL_BUILD-Debug-fa6da59c50887fa02791.json","target-ALL_BUILD-MinSizeRel-07bc5bf199bf200d9be0.json","target-ALL_BUILD-MinSizeRel-481cae9387489caaae17.json","target-ALL_BUILD-MinSizeRel-9fa54896336bcf9a26dc.json","target-ALL_BUILD-MinSizeRel-a79cc6fc2af231e0d489.json","target-ALL_BUILD-MinSizeRel-b4742cf98b38c1e500bd.json","target-ALL_BUILD-MinSizeRel-f2d053cbac7157c669b0.json","target-ALL_BUILD-MinSizeRel-f58ffed3fb42eaefcc8c.json","target-ALL_BUILD-MinSizeRel-fa6da59c50887fa02791.json","target-ALL_BUILD-Release-07bc5bf199bf200d9be0.json","target-ALL_BUILD-Release-481cae9387489caaae17.json","target-ALL_BUILD-Release-9fa54896336bcf9a26dc.json","target-ALL_BUILD-Release-a79cc6fc2af231e0d489.json","target-ALL_BUILD-Release-b4742cf98b38c1e500bd.json","target-ALL_BUILD-Release-f2d053cbac7157c669b0.json","target-ALL_BUILD-Release-f58ffed3fb42eaefcc8c.json","target-ALL_BUILD-Release-fa6da59c50887fa02791.json","target-ALL_BUILD-RelWithDebInfo-07bc5bf199bf200d9be0.json","target-ALL_BUILD-RelWithDebInfo-481cae9387489caaae17.json","target-ALL_BUILD-RelWithDebInfo-9fa54896336bcf9a26dc.json","target-ALL_BUILD-RelWithDebInfo-a79cc6fc2af231e0d489.json","target-ALL_BUILD-RelWithDebInfo-b4742cf98b38c1e500bd.json","target-ALL_BUILD-RelWithDebInfo-f2d053cbac7157c669b0.json","target-ALL_BUILD-RelWithDebInfo-f58ffed3fb42eaefcc8c.json","target-ALL_BUILD-RelWithDebInfo-fa6da59c50887fa02791.json","target-ArghoTunProto_ConverterTest-Debug-f7c5c01cf5aed9b2a806.json","target-ArghoTunProto_ConverterTest-MinSizeRel-e0f25521c75d6cbb2680.json","target-ArghoTunProto_ConverterTest-Release-488acd08ff9165d65af0.json","target-ArghoTunProto_ConverterTest-RelWithDebInfo-c209c9a271347bea0a5c.json","target-ArghoTunProto_TuningProto-Debug-766a3a703f2408b1f366.json","target-ArghoTunProto_TuningProto-MinSizeRel-46c2248946ac702776e6.json","target-ArghoTunProto_TuningProto-Release-06d91104703be6542d6f.json","target-ArghoTunProto_TuningProto-RelWithDebInfo-c0601f9f6a2b648bc268.json","target-ArghoTun_Base-Debug-241ed82a117fc15aa800.json","target-ArghoTun_Base-MinSizeRel-661f69c7aa33c45d0753.json","target-ArghoTun_Base-Release-8c1379a930f865689247.json","target-ArghoTun_Base-RelWithDebInfo-7eda9eaf85f4f0f9c609.json","target-ArghoTun_Entities-Debug-5770906fccb03e470499.json","target-ArghoTun_Entities-MinSizeRel-a2b4dd34af95117ffec2.json","target-ArghoTun_Entities-Release-d4119f894b07e02056b9.json","target-ArghoTun_Entities-RelWithDebInfo-9494823f04d2f3245102.json","target-ArghoTun_JsonEngine-Debug-7e67a45006c793d350fc.json","target-ArghoTun_JsonEngine-MinSizeRel-929d8c93311997dbc6ea.json","target-ArghoTun_JsonEngine-Release-7ed72fcd91fb2dc218fb.json","target-ArghoTun_JsonEngine-RelWithDebInfo-74ed7647aca985323f5a.json","target-ArghoTun_Parser-Debug-3558db95ffdccf4ae669.json","target-ArghoTun_Parser-MinSizeRel-d53fcd53b7098110b246.json","target-ArghoTun_Parser-Release-bdffda662ae97f082055.json","target-ArghoTun_Parser-RelWithDebInfo-d70c63824f087523f935.json","target-ArghoTun_TranslationsDefault-Debug-45ce616f805f9d97ded0.json","target-ArghoTun_TranslationsDefault-MinSizeRel-4dd4957e8679fa158bc5.json","target-ArghoTun_TranslationsDefault-Release-0d2adb675db07e93f209.json","target-ArghoTun_TranslationsDefault-RelWithDebInfo-3c9a64c58ba4b41437c2.json","target-gmock-Debug-8584a0876e99ed326a04.json","target-gmock-MinSizeRel-917449e97b7c71325cbb.json","target-gmock-Release-1263fe65b4bc908331cb.json","target-gmock-RelWithDebInfo-bcf41bbe44e62e9cd917.json","target-gmock_main-Debug-ac1a438a42c84c536098.json","target-gmock_main-MinSizeRel-69d0dc9c4f0a0b1a7f81.json","target-gmock_main-Release-11c13835a5f135550acc.json","target-gmock_main-RelWithDebInfo-7a8cd67c10f2a60f0366.json","target-gtest-Debug-8a65512756bc83d1b3af.json","target-gtest-MinSizeRel-faba7a99846832d129c2.json","target-gtest-Release-a59bc76d71f5badd4fa2.json","target-gtest-RelWithDebInfo-ecbbb809cf1ca1696e99.json","target-gtest_main-Debug-18fc6da6fba48c26f08e.json","target-gtest_main-MinSizeRel-81e58511fcca44c2a84b.json","target-gtest_main-Release-27a0a3ba5304224126a8.json","target-gtest_main-RelWithDebInfo-3fa82899628dff902e7b.json","target-libprotobuf-Debug-dbf070e30d55dc342210.json","target-libprotobuf-lite-Debug-372a5a824418328011d2.json","target-libprotobuf-lite-MinSizeRel-6e52a8c9c2b8ea40f28c.json","target-libprotobuf-lite-Release-957cfd12c23a0ab2d558.json","target-libprotobuf-lite-RelWithDebInfo-0efb365e09ab5104c79d.json","target-libprotobuf-MinSizeRel-4bdedcf9ac1439c97e25.json","target-libprotobuf-Release-b16bc1a18e36779435de.json","target-libprotobuf-RelWithDebInfo-60dedcbeebccf66c0b6d.json","target-libprotoc-Debug-79f233ca47161336586a.json","target-libprotoc-MinSizeRel-2052acb429b22d4481a2.json","target-libprotoc-Release-74e3b238100bae1d959e.json","target-libprotoc-RelWithDebInfo-f7c3153b9bce03d1a3de.json","target-protoc-Debug-39ed8731f64b4565f153.json","target-protoc-MinSizeRel-465efd3db5c218b05850.json","target-protoc-Release-a1e6ecf795efa00c4cb6.json","target-protoc-RelWithDebInfo-f003a49dbb7442f4ea3d.json","target-RapidJsonExternal-Debug-fbb3db02b42a2c7fe198.json","target-RapidJsonExternal-MinSizeRel-fbb3db02b42a2c7fe198.json","target-RapidJsonExternal-Release-fbb3db02b42a2c7fe198.json","target-RapidJsonExternal-RelWithDebInfo-fbb3db02b42a2c7fe198.json","target-ZERO_CHECK-Debug-eee110a47eb036aa8849.json","target-ZERO_CHECK-MinSizeRel-eee110a47eb036aa8849.json","target-ZERO_CHECK-Release-eee110a47eb036aa8849.json","target-ZERO_CHECK-RelWithDebInfo-eee110a47eb036aa8849.json","toolchains-v1-9aec6d1d3d5713ac70f1.json"]
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:45.255Z [debug] [cache] Reading CMake cache file c:/Users/eric/GitHub/arghotuning/arghotun-proto-cpp/build/CMakeCache.txt
console.ts:137 [Extension Host] [CMakeTools] 2021-07-11T18:48:45.257Z [debug] [cache] Parsing CMake cache string
4console.ts:137 [Extension Host] provideCustomConfiguration

### Platform and Versions

- **Operating System**: Windows 10 Pro version 10.0.19041
- **CMake Version**: 3.20.5
- **VSCode Version**: 1.58.0
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: Visual Studio Community 2019 (MSVC 19.29.30038.1)

**Comment by andreeis** [comment]
@Lindurion, thank you for creating this report. Coincidentally, this is addressed by [this PR](https://github.com/microsoft/vscode-cmake-tools/pull/1826) that came from the community and we are reviewing and testing it for CMake Tools 1.8 right now.
