### ISSUE TITLE
Kits and variants leak between windows when using Remote Containers extension

### ISSUE THREAD

**Issue by i-ky** [microsoft/vscode-cmake-tools#1993]
### Brief Issue Summary

I have two projects using CMake Tools and Remote Containers extensions for VS Code. When I have them opened simultaneously in two separate VS Code windows, I see that they "interact".

### Expected:

Extension instances in different VS Code windows must be isolated from each other.

### Apparent Behavior:

I see the following message:
```
[variant] >> Missing setting "foo" in variant definition.
```
in the window of the project that does not have "foo" in `variants.json`.

I have also noticed that changing kit in one window affects saved kit in another window, i.e. if I reload another window, it will change kit too.

### Platform and Versions

- **Operating System**: Windows 10, Ubuntu 18.04 in WSL 2, Docker Compose
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.58.0
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: GCC, Clang

### Other Notes/Information

I have to note that both projects mount source at `/code` directory within container. Maybe it is related (I can imagine that CMake Tools can be using workspace directory to identify cached sessions).

I will be glad to provide more information if needed. These are closed source projects, so I will keep details with me for now.

**Comment by andreeis** [comment]
@i-ky, thank you for opening this report. I think this is by design and the extension cannot differentiate between 2 different projects if they mount towards the same path. The kit selection is saved at project level and path is the key information.

If there would be a bug to save the kit selection at some other level (global versus project) then it would manifest the same but we would have caught this already and it would impact all the users, not only developers that work with remote containers.

Also, does this happen only when you open both projects at the same time? How about when you open one after another, a kit selection done in the previous project is seen in the second project if you open it after you close the first?

**Comment by i-ky** [comment]
@andreeis, thank you for such a prompt response! I will be able to provide answers to your questions tomorrow. But I guess I don't need to open both projects simultaneously. It is just the way I noticed this behaviour. Usually I focus on one project or another, but today I was multi-tasking and both happened to be in front of my eyes at the same time. I should also say that remote development in containers is a new thing for us. There were no issues when developing locally.

> I think this is by design and the extension cannot differentiate between 2 different projects if they mount towards the same path. The kit selection is saved at project level and path is the key information.

What do you really mean by "project level"? If I open the same folder locally and in container, is it the same "project level" or different? As I understand, VS Code will treat them as two independent workspaces. And if two projects are opened in their respective development containers, these are two independent workspaces too, even if workspace folder happens to be the same in both containers. And according to [documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions#persisting-extension-data-or-state), VS Code provides extensions with a workspace specific [`ExtensionContext.storageUri`](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.storageUri) to store data. It seems that using workspace folder as key is unnecessary.

**Comment by andreeis** [comment]
Makes sense, I will investigate. I only need a repro. I will search for a get started or if you have anything else handy let me know. This is new for me as well and to be able to answer precisely I will have to debug what the extension is doing and explore what better information is available to fix this (if it's a bug and not by design as I thought initially).

**Comment by bobbrow** [comment]
Using a workspace folder as the key for some data is necessary to support multi-root workspaces.  If the same folder is opened in several workspaces we can reuse the state saved to that folder if the state is keyed off of the folder URI.  The `storageUri`, if I'm not mistaken will be different for every "workspace" where that folder is used so the state will appear to have been "lost."

**Comment by i-ky** [comment]
> Also, does this happen only when you open both projects at the same time? How about when you open one after another, a kit selection done in the previous project is seen in the second project if you open it after you close the first?

@andreeis, I've done some testing. Settings leak when I open projects one after another as well. Kit selection seems to leak in both directions. Variants leak only one way. This is probably related to project configurations.

Both my projects have same set of kits available for selection, but one of them has more variants. Variant selection leaks from a project with less variants to a project with more variants, but not vice versa.

> I only need a repro. I will search for a get started or if you have anything else handy let me know.

Sure. These two projects are closed source, but I guess I will be able to provide you with a minimal example later today.

**Comment by i-ky** [comment]
@bobbrow,

> If the same folder is opened in several workspaces we can reuse the state saved to that folder if the state is keyed off of the folder URI.

Shouldn't workspaces be isolated?

> If the same folder is opened in several workspaces we can reuse the state saved to that folder if the state is keyed off of the folder URI.

This works well while you are confined within a local filesystem. But if user opens same path/URI from different remote machines or from different containers, the folder should not be "same".

> The `storageUri`, if I'm not mistaken, will be different for every "workspace" where that folder is used so the state will appear to have been "lost."

Yes, I guess so. But there is not much to "loose". Kit and variant can be selected in a few clicks. I may be biased here, but I would really prefer this behaviour. VS Code itself [stores UI state (e.g. opened files) per workspace](https://code.visualstudio.com/docs/editor/workspaces) and everyone seems to be happy with that.
