### ISSUE TITLE
Doc links broken in the VS Code extension page

### ISSUE THREAD

**Issue by sidcha** [microsoft/vscode-cmake-tools#2001]
The following links are broken:
> ## Important doc links
> CMake Tools quick start
> Configure and build a project with CMake Presets
> Configure a project with kits and variants
> Build a project with kits and variants
> Debug a project
> Configure CMake Tools settings
> How to
> FAQ
> Read the online documentation
> Contribute

**Comment by andreeis** [comment]
@sidcha, give us more details about where these links are given and don't work. For example, I found exactly this list in the extension repository, readme.md. When clicking all the links from there, they open.

**Comment by sidcha** [comment]
@andreeis, I mentioned it in the title of the issue. This extension has a landing page in vs-code (hit Cmd-X, search for "cmake tooks") where these links are broken (even as of now).

**Comment by sidcha** [comment]
I know what the issue is. Add those links were pointing to anchors into how-to.md. Now I think that file was split into individual files which is causing the issue. Does this sound familiar?
