### ISSUE TITLE
cmake.cmakePath invalid when reset via the settings UI

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cmake-tools#2006]
If the `cmake.cmakePath` is set to `"cmake"` (which is the default), in both `user` and `workspace` settings, then things work fine.
But if one of them is removed, this error will show up:

![image](https://user-images.githubusercontent.com/16143955/126562546-c9f8ee43-1e0d-4f35-8755-9512ea6fcc10.png)

The expected behavior is to use the `workspace` setting, if not available, use the `user` setting, and if that one is not available, then show this error.

Also, if the default (i.e. `cmake`) is removed from the user or from the workspace in the UI, the JSON file will be modified by this value: 

> `"cmake.cmakePath": ""`

that might be the cause of the error.

**Comment by bobbrow** [comment]
Similar to, but not addressed by https://github.com/microsoft/vscode-cmake-tools/pull/1978.  The problem is that the setting is string with a "null" default which is invalid.
