### ISSUE TITLE
start time cmake configure doesn't respect cmake.buildDirectory settings.

### ISSUE THREAD

**Issue by chezgi** [microsoft/vscode-cmake-tools#2014]
when starting vscode in project dir it uses default `build/` directory and creates some files in build/ directory i don't want. 
when configuring manually in `CMAKE: PROJCT OUTILE` it works correctly.

my settings for build directory:
```
    "cmake.buildDirectory": "${workspaceFolder}/build/${buildKitTargetArch}",    
```

**Comment by bobbrow** [comment]
Sorry if this question seems obvious, but are you using CMakePresets.json to configure your workspace, or CMake Tools Kits?  I didn't reproduce this problem on my first few attempts, so there could be a race condition or something else different about your configuration that is triggering this problem.

**Comment by chezgi** [comment]
thanks @bobbrow,
i am using CMake Tools Kits.

**Comment by bobbrow** [comment]
Are you able to share some more information about your environment and/or your repository?
* VS Code version
* CMake Tools version
* OS
* Enable the `"cmake.loggingLevel": "debug"` setting and reload your window - then share the logs in the OUTPUT window
