### ISSUE TITLE
How to set environment varibles when running executable for specific kit ?

### ISSUE THREAD

**Issue by forallsunday** [microsoft/vscode-cmake-tools#2015]
When I  running vscode-cmake-tool "running without debugging",  I want to set the qt5 mingw environment, because I didn't set the path in the system environment varible.
This is the kit in "cmake-tool-kit.json": 
```   
{
    "name": "GCC 7.3.0 x86_64-w64-mingw32",   
    "compilers": {
      "C": "D:\\IDE\\Qt\\Qt5.13.1\\Tools\\mingw730_64\\bin\\x86_64-w64-mingw32-gcc.exe",
      "CXX": "D:\\IDE\\Qt\\Qt5.13.1\\Tools\\mingw730_64\\bin\\x86_64-w64-mingw32-g++.exe"
    },
    "preferredGenerator": {
      "name": "MinGW Makefiles"
    },
    "environmentVariables": {
      "CMT_MINGW_PATH": "D:\\IDE\\Qt\\Qt5.13.1\\Tools\\mingw730_64\\bin",
      "QT_MINGW_PATH": "D:\\IDE\\Qt\\Qt5.13.1\\5.13.1\\mingw73_64\\bin",
      "PATH": "D:/IDE/Qt/Qt5.13.1/5.13.1/mingw73_64/bin",
    }
},  
```

But this doesn't work.
What is the right way?
P.S. I only want to set this path in this kit, because I often build project using msvc kit  as well.

**Comment by bobbrow** [comment]
Can you try setting `"CMT_MINGW_PATH": "D:/IDE/Qt/Qt5.13.1/5.13.1/mingw73_64/bin"` instead of setting `PATH` directly?  That replaces the system PATH which may have unexpected consequences.

If that doesn't work, can you share the errors you're seeing?

**Comment by forallsunday** [comment]
> Can you try setting `"CMT_MINGW_PATH": "D:/IDE/Qt/Qt5.13.1/5.13.1/mingw73_64/bin"` instead of setting `PATH` directly? That replaces the system PATH which may have unexpected consequences.
> 
> If that doesn't work, can you share the errors you're seeing?

I tried and it doesn't work.
Well, there is no error at building, just want to set the PATH when running.
The names of Dll files in Qt5_mingw dir  and Qt5_msvc dir are the same, so if I change kit to run the executable file, that would cause dll load error. And nothing happens in the Cmake Launch terminal.
Simply copy dll files to the EXECUTABLE_OUTPUT_PATH could run, but what I wish is change the environment varible for differrent kit, is that possible?

**Comment by bobbrow** [comment]
Sorry, I misunderstood your issue and thought you were reporting a build issue.  If you are using the debug/launch buttons in the status bar or the CMake Tools commands to do the same, you need to add the paths to the environment in the `cmake.debugConfig` setting.  For example:
```
  "cmake.debugConfig": {
    "environment": [
      "D:/IDE/Qt/Qt5.13.1/5.13.1/mingw73_64/bin"
    ]
  }
```
