### ISSUE TITLE
cannot config "-T v141"

### ISSUE THREAD

**Issue by xinglinsky** [microsoft/vscode-cmake-tools#2024]
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -T v141 -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Hf:/git_src/hysdk_wrapper -Bf:/xx/build -G "Visual Studio 16 2019" -T host=x86 -A win32
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error: Multiple -T options not allowed
[cmake] CMake Error: Run 'cmake --help' for all supported options.

**Comment by bobbrow** [comment]
Can you share your settings and the Kit you've chosen.  I suspect it is set twice somewhere.
