### ISSUE TITLE
Cmake can not start at right directory

### ISSUE THREAD

**Issue by sparkertim** [microsoft/vscode-cmake-tools#2027]
when I deleted the build directory, and regenerate the new binary file,  the cmake tool start the wrong directory like
" /home/xxx/.local/share/Trash/files/build.13/Linux_Debug_x64/xxx/bin" which is the trash dir.

**Comment by sparkertim** [comment]
I used ubuntu 20.4 , this maybe caused by the system. If I open a termianl at the build directory,  delete the build directory and regenerate the build files, at this time, if I start the exec at the odl terminal, the terminal will target to the trash  directory.  this issue may be caused by the same operation

**Comment by elahehrashedi** [comment]
Would you please explain more on how did you determine that "cmake tool start the wrong directory"?

**Comment by sparkertim** [comment]
> Would you please explain more on how did you determine that "cmake tool start the wrong directory"?
> I am trying to figure out your issue is related to cmaketools extension.

This issue caused by Ubuntu Terminal. cmake-tool will reuse the same terminal when click the launch or debug button on the footer.  the termianl start the execuate at right path such as "/my_project_dir/Linux_Debug_x64/bin". When I delete the build directory manually, the old terminal will point to the binary path which had been deleted. such as **/home/xxx/.local/share/Trash/files/build.11/Linux_Debug_x64/bin.** If I run configure and build to generate these directory and files again, the old terminal still point to the Trash, at this time click the launch  or debug button will run the execaute in the trash.
so, I suggest that cmake-tool should delete the old terminal and use new terminal to start the execuate binary file every time.
