### ISSUE TITLE
Build task broken in PowerShell terminal

### ISSUE THREAD

**Issue by bmcdonnell-fb** [microsoft/vscode-cmake-tools#2034]
### Brief Issue Summary

Cannot launch CMake build as a task using PowerShell, apparently since double quotes don't nest.

Project `.vscode/tasks.json`:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "CMake Build",
            "type": "cmake",
            "command": "build",
            "group": "build",
            "problemMatcher": []
        }
    ]
}
```

We added `"preLaunchTask": "CMake Build"` in our project `.vscode/launch.json`.

![image](https://user-images.githubusercontent.com/81983488/128258753-b6e50d5b-cc92-42d0-9b64-629ff75717b5.png)

### Expected:

1. Click the Debug button
2. The currently-selected CMake variant is built if it is out of date, before debugging begins

### Apparent Behavior:

1. Click the Debug button
2. The build fails

### Platform and Versions

- **Operating System**: Windows_NT x64 10.0.19043
- **CMake Version**: 3.20.4
- **VSCode Version**: 1.58.2 (user setup)
- **CMake Tools Extension Version**: 1.7.3
  - **Compiler/Toolchain**: GNU Arm Embedded (arm-none-eabi) 10_2020-q4-major

### Other Notes/Information

#1680 appears to be related. Now the CMake path is escaped, and it's broken in a different way?

This build task works if we force the terminal to Git bash, such as using the (deprecated) `terminal.integrated.shell.windows` option in `settings.json`.

![image](https://user-images.githubusercontent.com/81983488/128260028-0ccbb4e8-b7bf-4f26-90e9-ea166367186a.png)

**Comment by elahehrashedi** [comment]
With the current version of build task, you should see this message:
`> Executing task: CMake Build <`
in which `CMake Build` is the name of your task. 

I am suspicious that you are using an older version as the message you are seeing is the complete build command which was an older behavior. i.e. `"C:\Program Files\CMake\bin\cmake.exe" --build ..../build --config Debug --target all -j 11--` . I know you mentioned you are using version 1.7.3, I was wondering if you can double-check that.

I am not able to repro your error in powershell, if you have updated your version of the extension and you still see the error, please send me your `launch.json` as well.

**Comment by bobbrow** [comment]
@elahehrashedi The problem happens when you set `"terminal.integrated.shell.windows": "powershell.exe"` in your settings.  It works in the CMD.exe terminal, but not with PowerShell.  Something is incorrect about how the command ends up being quoted.  I'm not sure whether this is our issue or VS Code's.

**Comment by bmcdonnell-fb** [comment]
@elahehrashedi, my CMake Tools version is v1.7.3.

![image](https://user-images.githubusercontent.com/81983488/128537888-fa544a0f-3dc3-421e-9746-ce18b9546075.png)

Following @bobbrow's input above, LMK if you still additional info from me.

@bobbrow

> The problem happens when you set `"terminal.integrated.shell.windows": "powershell.exe"` in your settings.

I didn't have that set, but apparently it is the default behavior.

**Comment by bobbrow** [comment]
@bmcdonnell-fb There are other ways to set the default terminal, but I assumed that was how you were doing it because of your screenshot.

**Comment by elahehrashedi** [comment]
I just realized the new version of `build task` is still not released. This issue has been fixed and it is release-pending (version1.8).

**Comment by bobbrow** [comment]
This is fixed then?  @bmcdonnell-fb do you want to try with our pre-release extension?

Steps:
1. Download from here: https://github.com/microsoft/vscode-cmake-tools/suites/3400423450/artifacts/80311689
2. Unzip
3. Install with the "Install from VSIX..." command in VS Code

**Comment by bmcdonnell-fb** [comment]
CMake Tools `v1.8.0-2781314` (from @bobbrow's link) seems to fix the issue.

(I say "seems to" since I'm no longer getting the error noted in the OP, but I'm still troubleshooting some apparently unrelated debugging issues.)

Thanks @elahehrashedi and @bobbrow. 😃

**Comment by bobbrow** [comment]
Glad to hear it's working now.  Let us know if there's anything we can do to help with the debugging issue.  It could be an issue with this extension or cpptools.
