### ISSUE TITLE
The extension erroneously accepts trailing commas and comments for CMakePresets.json

### ISSUE THREAD

**Issue by TheJCAB** [microsoft/vscode-cmake-tools#2035]
### Brief Issue Summary

Trailing commas and comments are not valid JSON elements, and CMake rejects both when processing CMakePresets.json and CMakeUserPresets.json, but the CMake tools extension seems to instead ignore them.

### Expected:

They should be rejected, preferably with a good message of what the issue was and where it was in the file.

Otherwise, it's easy to introduce breaks when a build pipeline launches the preset directly via CMake. I just did it twice in the last couple of days, one of each kind.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.20.5
- **CMake Tools Extension Version**: 1.7.3

### Other Notes/Information

Frankly, I don't know what possessed CMake to disallow such things, but it clearly is done on purpose. See the [release notes for 3.19.6](https://cmake.org/cmake/help/latest/release/3.19.html#id6), which explicitly disabled comments.

But since the source of truth disallows such things, anything built on top if it should too.

**Comment by elahehrashedi** [comment]
in the default JSON mode, you will see the warnings in your json file: https://code.visualstudio.com/docs/languages/json
unless you change the language mode from JSON to JSONC.
![image](https://user-images.githubusercontent.com/16143955/128463434-680ee8c9-2e43-4314-8115-c9a4e69c30e4.png)

![image](https://user-images.githubusercontent.com/16143955/128462947-3b959470-1b6f-4ca0-b032-8ed176baf69a.png)

we have to discuss with the team whether our extension should also show these warnings or leave it to the user to fix the warnings in their file.

**Comment by bobbrow** [comment]
We use the json5 parser for the presets file.  @xisui-MSFT since CMake doesn't seem to support the extra features yet (trailing commas and comments), can we switch this back to using the standard `JSON.parse` instead?  Perhaps as a warning to folks, we could parse with both and give them instructions as to what to do to resolve the errors (open the file and set the language mode to JSON)

**Comment by xisui-MSFT** [comment]
@bobbrow Might be better to parse it using JSON.parse. And always automatically set the language mode of the file by onDidOpenTextDocument + setTextDocumentLanguage, so we don't need to parse it twice.

**Comment by bobbrow** [comment]
Do we already show an error if it fails to parse so that the developer will open the file?

**Comment by xisui-MSFT** [comment]
There will be errors like this: 
![image](https://user-images.githubusercontent.com/44103947/128560156-b6dbe044-faaa-45e1-8081-48a58cc99a66.png)

**Comment by TheJCAB** [comment]
I wonder whether it'd be best to lobby hard for CMake.exe to be enhanced to provide complete information about presets. At a minimum, provide a fully parsed/normalized version of the preset file(s). Forcing N different GUIs/tools to parse and process the file(s) themselves, inheritance and all, doesn't really seem like a great idea.

**Comment by andreeis** [comment]
This was fixed in 1.8.
