### ISSUE TITLE
Handle CMAKE_BUILD_TYPE string

### ISSUE THREAD

**Issue by jphz** [microsoft/vscode-cmake-tools#2037]
Different settings can cause errors
CMAKE FILE

ERROR
set(CMAKE_BUILD_TYPE "DEBUG")

OK
set(CMAKE_BUILD_TYPE "Debug")

**Comment by elahehrashedi** [comment]
The acceptable CMAKE_BUILD_TYPE in the `_target_map` are empty, `Debug`, `Release`, `RelWithDebInfo`, `MinSizeRel` (https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html)

We can possibly modify this function to modify the name in line 163.
https://github.com/microsoft/vscode-cmake-tools/blob/2781314504c8ad764a9b3b47588e8cd81f303dbf/src/drivers/cmakefileapi/api_helpers.ts#L147-L163

**Comment by elahehrashedi** [comment]
Added an issue to change the log message: https://github.com/microsoft/vscode-cmake-tools/issues/2039

**Comment by jphz** [comment]
Thank you.
