### ISSUE TITLE
Launch the Debugger when CMAKE_BUILD_TYPE is not "Debug"

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cmake-tools#2039]
in this CMakeLists.txt example, the build type is defined as something other than default which is "Debug":
```
cmake_minimum_required(VERSION 3.5)
project(intro3)
add_executable(intro3 ./hello.cpp)
set(CMAKE_BUILD_TYPE "Release")
```
After building the project, When trying to debug, we will get two different error messages. The message doesn't show that there is no Debug target available.

----------
When Debugging from here:
![image](https://user-images.githubusercontent.com/16143955/128780365-ee846a29-9299-4fe3-b551-c78b45fad3cf.png)
the error message is:
```
[main] Failed to prepare executable target with name 'undefined'
[extension] [3899] cmake.debugTarget finished (returned null)
```
----------
When Debugging from here:
![image](https://user-images.githubusercontent.com/16143955/128780549-8b1a1d77-cb29-4a6a-8d78-3a2824f62c27.png)
the error message is:
```
[main] Failed to prepare executable target with name 'intro3'
[extension] [7484] cmake.debugTarget finished (returned null)
```

**Comment by andreeis** [comment]
This will be addressed by https://github.com/microsoft/vscode-cmake-tools/issues/2096.
