### ISSUE TITLE
Offline installation fails with "XHR failed" error

### ISSUE THREAD

**Issue by Schwefelsaeure** [microsoft/vscode-cmake-tools#2049]
### Brief Issue Summary

The installation of the CMake Tools in an offline environment fails with "XHR failed" error which is shown in the bottom right corner of VS Code after clicking **Extensions -> ... -> Install from VSIX...**:

![VSCode-CMakeTools-Installation-XHR-Error](https://i.imgur.com/lI7UTgL.png)

I tried several CMake Tool versions: 1.7.0 to 1.7.3:

![VSCode-Offline-Extensions](https://i.imgur.com/dUtGMaA.png)

Other VSIX (offline) packages like cpptools-linux.vsix work like a charm.

### Developer Tools Log

I start VS Code from a terminal and I get following output after clicking "Install from VSIX...":

```
...
[3644128:0812/075502.770841:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3644128:0812/075502.772301:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

### Platform and Versions

- **Operating System**: Red Hat Enterprise Linux 7
- **VSCode Version**: 1.59.0

### Other Notes/Information

An offline installation is necessary because no internet is available on this development copmuter.

**Comment by bobbrow** [comment]
Does it actually fail to install though?  This extension declares itself as an "extension pack" which means we ask VS Code to also install the "CMake" extension by twxs so I suspect that is where it is failing.  If you install that VSIX first, does it make the error go away?  I don't see the latest version of their extension on their GitHub page so I'm not sure where you would get it besides maybe packaging it yourself, but the second oldest release is there, I believe: https://github.com/twxs/vs.language.cmake/releases/download/v0.0.16-beta1/cmake-0.0.16.vsix

**Comment by Schwefelsaeure** [comment]
Yes, indeed, the problem is gone if I install the "CMake" extension by twxs first followed by "CMake Tools". 👍 

I did not realize that "CMake Tools" is declared as "extension pack". Thank you very, very much for your quick reply and help. :) But, for users a more descriptive error message would be useful in the future like "Dependency xyz could not be fetched".

**Comment by bobbrow** [comment]
Awesome!  I'm glad that worked for you.  Unfortunately we don't own that error message.  Would you be able to open an issue in the VS Code repo for this?

**Comment by Schwefelsaeure** [comment]
Thanks for the tip, that you do not own the error message. Therefore, I filed an issue in the [VS Code repo](https://github.com/microsoft/vscode/issues/130962). 👍
