### ISSUE TITLE
Can't set the tools,  command "cmake.xxxxx" not found

### ISSUE THREAD

**Issue by Rain-Main** [microsoft/vscode-cmake-tools#2052]
### Expected:

1. in my vscode , I can't set my cmake on my task tool bar, It shows me below:
    
![image](https://user-images.githubusercontent.com/58506571/129306969-10b9d7a3-a13a-457d-b9c5-01c13187478a.png)
2. If I click on the setting option, It shows me: `command 'cmake.selectBuildPreset' not found`
3. The command workless either

### Apparent Behavior:

always

### Platform and Versions

- **Operating System**: Win10 19042
- **CMake Version**: 3.20.5
- **VSCode Version**: 1.59.0
- **CMake Tools Extension Version**: The lastest one
- **Compiler/Toolchain**:

**Comment by elahehrashedi** [comment]
Can you please share more information related to the project?  From what I can see, you have a "CMakePresets.json" that activated the presets bar? is that right, or are you using a  cmake-kits.json? 

Enable the `"cmake.loggingLevel": "debug"` setting and reload your window - then share the logs in the OUTPUT window

**Comment by Rain-Main** [comment]
Thanks for your replay. I solved the problem by remove the folder .vscode and install my extension again. ^_^
