### ISSUE TITLE
Custom  `CMAKE_C_COMPILER` and  `CMAKE_CXX_COMPILER`  override by tools

### ISSUE THREAD

**Issue by ckitterl** [microsoft/vscode-cmake-tools#2057]
### Brief Issue Summary

Custom  `CMAKE_C_COMPILER` and  `CMAKE_CXX_COMPILER`  override by tools
### Expected:

I use cmake-tools to develop android ndk project; so I use the andorid ndk's  clang/clang++ ;  The first build seem OK, but  when I reopen the project and the tools will rebuild failed as the CMAKE_C_COMPILER and CMAKE_CXX_COMPILER be overrided by tools.

My setting snippet 
```
    "cmake.configureArgs": [
        "-DANDROID_NDK=${env:ANDROID_NDK_HOME}",
        "-DCMAKE_TOOLCHAIN_FILE=${env:ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake",
        "-DCMAKE_C_COMPILER:FILEPATH=${env:ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang",
        "-DCMAKE_CXX_COMPILER:FILEPATH=${env:ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++",
        "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=output"
   ],
```

The build command 
```
[proc] Executing command: /Users/......./bin/cmake --no-warn-unused-cli -DANDROID_NDK=/Users/mk/Library/Android/sdk/ndk/21.3.6528147 -DCMAKE_TOOLCHAIN_FILE=/Users/mk/Library/Android/sdk/ndk/21.3.6528147/build/cmake/android.toolchain.cmake -DCMAKE_C_COMPILER:FILEPATH=/Users/mk/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/Users/mk/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=output -DANDROID_NATIVE_API_LEVEL:STRING=23 -DANDROID_ABI:STRING=armeabi-v7a -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ -H/Users/mk/myproject -B/Users/mk/myproject/build/debug/armeabi-v7a -G Ninja
```

I seem like a bug of cmake; but if the tools do not add `/usr/bin/clang` and `/usr/bin/clang++` to the tail of command, everything seem be all right.

### Platform and Versions

- **Operating System**: macOs
- **CMake Version**: 3.19.2
- **VSCode Version**: 1.59.0
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: android ndk, 21.3.6528147

**Comment by ckitterl** [comment]
I think I missed  `Cmake kits` and add the compiler setting here;

**Comment by bobbrow** [comment]
Yes, there are several ways that should work for you:
1. Use the settings the way you have it now and select the [Unspecified] Kit so that we don't try to override your values
2. Scan for kits or add one manually if the scan doesn't find it and remove the *_COMPILER settings
3. Add a CMakePresets.json file and move the settings there.
