### ISSUE TITLE
Allow cmake build tasks to select a Kit or preset for the build

### ISSUE THREAD

**Issue by itavero** [microsoft/vscode-cmake-tools#2058]
### Brief Issue Summary

We use CMake Tools in combination with [Cortex-Debug](https://github.com/Marus/cortex-debug).
Our codebase is cross-compiled for different embedded targets with different compilers.

For each of these targets we basically have a CMake Kit defined, as well as a dedicated launch configuration in `launch.json`.
I wish to only enable a specific launch configuration if the correct CMake Kit is selected.

### Platform and Versions

- **Operating System**:  Windows 10
- **CMake Version**: 3.20.1
- **VSCode Version**: 1.59.0
- **CMake Tools Extension Version**: 1.7.3
- **Compiler/Toolchain**: GCC ARM 7, TI armclang, ...

### Other Notes/Information

On a related note:
* We are currently using `${command:cmake.launchTargetPath}` to pass the executable to _Cortex-Debug_, this works well. It would however be awesome if the _Run_ button in the toolbar could also trigger _Cortex-Debug_ (i.e. do what happens if I hit _F5_ on my Windows machine).

**Comment by elahehrashedi** [comment]
This seems like an issue for the Cortex-Debug extension, as your launch.json will be generated by your debugger, not by cmake-tool extension. The F5 and "Run and Debug" buttons both will trigger the debugger. 
Would you please explain more on "only enable a specific launch configuration if the correct CMake Kit is selected" as well?

**Comment by elahehrashedi** [comment]
could you please explain more on "enable a specific launch configuration if the correct CMake Kit is selected" ? Would you please also share a launch.json sample?

**Comment by itavero** [comment]
Given the following `launch.json`:

```json
{
   // Use IntelliSense to learn about possible attributes.
   // Hover to view descriptions of existing attributes.
   // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
   "version": "0.2.0",
   "configurations": [
      {
         "name": "LPC5526 board",
         "cwd": "${workspaceRoot}",
         "executable": "${command:cmake.launchTargetPath}",
         "request": "launch",
         "type": "cortex-debug",
         "servertype": "jlink",
         "device": "LPC5526JBD64",
         "interface": "swd",
         "runToMain": true,
         "presentation": {
            "group": "Boards"
         }
      },
      {
         "name": "LAUNCHXL-CC1352",
         "cwd": "${workspaceRoot}",
         "executable": "${command:cmake.launchTargetPath}",
         "request": "launch",
         "type": "cortex-debug",
         "servertype": "jlink",
         "device": "CC1352R1F3",
         "interface": "jtag",
         "runToMain": true,
         "presentation": {
            "group": "Boards"
         }
      }
   ]
}
```

It has the launch configuration for two physical hardware boards. To run the software on the _LPC5526 board_, we need to compile with a different compiler than when we want to run the software on the _LAUNCHXL-CC1352_.
For that we have different CMake toolchain files, which we provide as `toolchainFile` via different kits in `cmake-kits.json`.

In other words, we know that the _LPC5526 board_ launch config can only be used if the kit is set to _Kit A_ and the _LAUNCHXL-CC1352_ launch config can only be used if _Kit B_ is selected.

I would like to be able to "hide" the launch configurations that do not match the selected kit.

**Comment by bobbrow** [comment]
We can't really "hide" launch configurations because we don't own the `launch.json` experience.  The Run/Debug buttons in the status bar are not connected to any of your tasks/launch configurations.

That said, the `launch.json` configurations could be linked to pre-launch tasks that do the correct build.  In this way you wouldn't actually need to change the active Kit before debugging.  Unfortunately we don't have a way to select a Kit or build preset as part of a build through our build task right now, but it should be possible.  I think it would be better to track this as a feature request for supporting pre-launch tasks that can preselect the Kit or preset.

**Comment by itavero** [comment]
That would also be a way to approach it.

I was thinking about "dynamically" setting the `presentation.hidden` property (which is mentioned in the [general launch.json docs](https://code.visualstudio.com/docs/editor/debugging)).

In other words, I was hoping something like this could be done within a launch configuration:
```json
{
  "presentation": {
    "hidden": "${command:cmake.currentKitIsNot(name-of-required-kit)}"
  }
}
```
