### ISSUE TITLE
Documentation: list of ${command:cmake.*} options

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-cmake-tools#2063]
There exist some command that can be used in launch.json and task.json

For example, `${command:cmake.launchTargetPath}` is described [here](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md).

What other command are availible? Where can I find a list?

**Comment by hwhsu1231** [comment]
I think this [link](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md#command-substitution) of documentation is what you are looking for.

**Comment by bobbrow** [comment]
Yep, that's it.  Thanks @hwhsu1231!

**Comment by KUGA2** [comment]
Link was down (branch was deleted): new link: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#command-substitution
