### ISSUE TITLE
"Open" telemetry is broken

### ISSUE THREAD

**Issue by esweet431** [microsoft/vscode-cmake-tools#2065]
Version: v1.8.0-163e532

1. Open a folder that contains a CMakeLists.txt file in VS Code 
2. The cmake-tools extension fully activates 

Expected behavior: 
3. The EventName "open" fires with property.isFullyActivated == true

Actual behavior: 
3. The EventName "open" fires with property.isFullyActivated == false

Through my manual testing, I haven't found any instances where property.isFullyActivated returns true

**Comment by bobbrow** [comment]
Fix for this is in PR now.
