### ISSUE TITLE
"Locating" a CMakeLists.txt file does not fully activate cmake-tools

### ISSUE THREAD

**Issue by esweet431** [microsoft/vscode-cmake-tools#2066]
Version: v1.8.0-163e532

1. Open a folder with no CMakeLists.txt file at the root and at least one CMakeLists.txt in a subdirectory 
2. You are prompted with a pop-up in the right-hand corner of the editor. Select "Locate"
3. Locate a CMakeLists.txt file 
4. The source directory successfully changes in the project's workspace settings 
5. You are automatically prompted to select a kit/configure preset (or create one if no CMakePresets.json exists.) Select a kit/configure preset

Expected behavior:
6. cmake-tools automatically attempts to configure
7. cmake-tools fully activates 

Actual behavior when kits are active:
6. cmake-tools automatically attempts to configure
7. cmake-tools remains in a partially active state (limited commands, no status bar)

Actual behavior when presets are active:
6. cmake-tools does not automatically attempt to configure 
7. cmake-tools remains in a partially active state (limited commands, no status bar)

Note that if I close the folder and re-open it, cmake-tools behaves as expected and fully activates.

**Comment by bobbrow** [comment]
PR is available for this.
