### ISSUE TITLE
Rename functions that contain underscore prefix

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cmake-tools#2069]
There are functions, for example, setKit, has their corresponding private functions with names like _setKit. While being error prone, this pattern is widely used in this code base. We may want to rename all of them.

**Comment by elahehrashedi** [comment]
We have changed our [coding guidelines](https://github.com/microsoft/vscode-cmake-tools/wiki/Coding-guidelines) and we are planning to enforce the new guidelines in the new PRs that are coming in.

Feel free to do renaming whenever you encounter them in your PRs.

**Comment by bobbrow** [comment]
This was a pre-existing issue and bigger than what made sense for the PR that @xisui-MSFT was working on so I asked him to create this issue.  It's best to do refactoring PR's separate from code change ones if the refactoring is significant.

**Comment by elahehrashedi** [comment]
Sure, we can make a plan for some refactoring.
