### ISSUE TITLE
Unable to debug my test

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#2074]
I am facing a similar issue with one of my cmake projects. I am trying to run this on a remote machine. The host machine is OSX 11.4 (Big Sur). The remote is a Ubuntu 20.04.3. The project configures and builds okay. But I am not able to debug any of my unit tests. This is the error I get when I right-click on the test and press 'Debug'

`
[extension] [1484] cmake.debugTarget started
[main] Failed to prepare executable target with name 'core-01_hello_test.cpp'
[extension] [1484] cmake.debugTarget finished (returned null)
`

Does not give me any other information.

This is what my cmake command looks like:

`                "cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja"`

I have tried Debug, 'Debug', and also 'DEBUG'. Doesn't seem to make a difference.

_Originally posted by @CatsNipYummy in https://github.com/microsoft/vscode-cmake-tools/issues/1692#issuecomment-905059538_

**Comment by bobbrow** [comment]
@CatsNipYummy, can you set the `cmake.loggingLevel` setting to "Debug" and retry the scenario?  Then paste the log output here.  There's more information we can get from the extension between `cmake.debugTarget started` and `cmake.debugTarget finished`.  I'm most interested in what the extension says on this line:
```
[main] Starting debugger with following configuration. {...}
```

**Comment by CatsNipYummy** [comment]
Here are the logs you requested. I've used the snap worked around as well (that's right. removed the .cpp as well)

[VS_Code2.log](https://github.com/microsoft/vscode-cmake-tools/files/7071689/VS_Code2.log)

**Comment by CatsNipYummy** [comment]
@bobbrow do you need any other logs from my end?

**Comment by bobbrow** [comment]
![image](https://user-images.githubusercontent.com/12818240/131536366-4205956b-cd36-4e3e-8f5f-241f4f09d686.png)

**Comment by CatsNipYummy** [comment]
![image](https://user-images.githubusercontent.com/524266/131570988-0d988a7c-2444-4663-9721-faf466364129.png)
Should I have the same hash as well? I don't see an official 1.8.1 release yet.

**Comment by bobbrow** [comment]
Yes, the hash number should be the same as mine.  You might need to uninstall the first VSIX I gave you to get the new one to install properly.  You can also "uninstall" it by deleting the matching folder under `~/.vscode/extensions`.

**Comment by CatsNipYummy** [comment]
my bad. here are the logs from the right version
![image](https://user-images.githubusercontent.com/524266/131574297-c9a12e92-84e0-4a81-bcce-49dd32eceefd.png)

[VS_Code3.log](https://github.com/microsoft/vscode-cmake-tools/files/7086765/VS_Code3.log)
As usual, I've renamed some of the logs after they were generated. So do take the naming with a pinch of salt. Thanks again

**Comment by bobbrow** [comment]
It appears that the CMAKE_BUILD_TYPE for the targets we discovered (Release) does not match the currently active build type for debugging.  Unfortunately, I failed to log what that was, but it should be on the status bar.  Can you tell me what is selected there?  Is it Release, or something else?

![image](https://user-images.githubusercontent.com/12818240/131575986-cfd6527c-3a76-4948-93c7-67f9d439f4cf.png)

**Comment by bobbrow** [comment]
Another option is for me to give you a line of code for you to insert into your copy of the extension and that will add the logging.

**Comment by CatsNipYummy** [comment]
![image](https://user-images.githubusercontent.com/524266/131576998-b54f5985-1e90-4a53-94b6-2547da04736b.png)
This is what I have by default

**Comment by CatsNipYummy** [comment]
Sure. I can add that line of code and see what's happening

**Comment by bobbrow** [comment]
The screenshot is sufficient. You are trying to select "Debug", but the information the extension has indicates that the "Release" configuration is being generated.  Is there anything in your CMakeLists.txt that changes the CMAKE_BUILD_TYPE?  I see that the generator command is correctly setting the CMAKE_BUILD_TYPE to Debug, but all of the files written here: `/home/workspace/proj/build/.cmake/api/v1/reply` have 'Release' in the name.  You can try deleting the `/home/workspace/proj/build/.cmake` folder and regenerating, but it looks like the build type is changing out from under us.  If you set the status bar to "CMake: [Release]: Ready", I think the debugger would start (though you'd be debugging optimized binaries)

**Comment by CatsNipYummy** [comment]
That's true. To your point, when I tried "CMake: [Release]: Ready", it did try to compile the project but then all my paths are missing. So I get 'cannot open *.h' errors.

Let me try deleting the build folder and try again. I've been doing that for all my tests each time. But let me see if something's explicitly changing the CMAKE_BUILD_TYPE to Release at some point.

**Comment by CatsNipYummy** [comment]
So I did delete the .cmake file you mentioned and I was able to get the debugger to start and I see my unit test output which is great!

The only issue is that the breakpoints are not getting activated. Even if this is in release, shouldn't the breakpoints inside int main() get called?

**Comment by bobbrow** [comment]
By default, I don't believe CMake's 'Release' config sets up the binary to have any debug information in it so that's why your breakpoints don't bind.  There is a 'RelWithDebInfo' config that does that.  Sorry, I should have thought of that earlier.

**Comment by CatsNipYummy** [comment]
'RelWithDebInfo' is still not doing anything for me

```
[extension] [7083] cmake.setVariant finished (returned 0)
[extension] [6319] cmake.debugTarget started
[cmakefileapi-driver] [FileApi] Unique targets []
[main] [prepareLaunchTargetExecutable] Looking for 'core-01_hello_proj'
[main] [prepareLaunchTargetExecutable] executableTargets []
[main] Failed to prepare executable target with name 'core-01_hello_proj'
[extension] [6319] cmake.debugTarget finished (returned null)
```
This does sound like a shortcut to the problem. The fact its getting switched to Release is probably why this is not working either.

**Comment by bobbrow** [comment]
Correct.  This is the exact same problem as the 'Debug' config.  If you can figure out where in the project the CMAKE_BUILD_TYPE is getting overwritten, I think everything should start working as expected.

**Comment by CatsNipYummy** [comment]
Dug around the project a bit and found the source of the issue. We're forcing the CMAKE_BUILD_TYPE cause of some cross-platform support like you mentioned. That's something on our end that needs to be changed. But removing that fixed this issue. Thanks a lot for your help @bobbrow . Feel free to close this issue if you like.

**Comment by bobbrow** [comment]
I'm glad you were able to resolve this.  I'll close this issue, but create a new one for us to investigate whether we can throw in a warning about this type of situation.
