### ISSUE TITLE
Intellisense of CMake-Tools is not working with MSYS2.

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-cmake-tools#2086]
## Problem Description

Recently, I've done the research on how to build the environment of **MSYS** in VSCode. First to say, it actually worked. I wrote a simple program with `fork()`, and it could run successfully. However, the intellisence of CMake-Tools shows that it could not locate the headers with the squiggles underneath.

> \#include errors detected based on information provided by the configurationProvider setting. Squiggles are disabled for this translation unit

Usually, I don't use `c_cpp_properties.json` because CMake-Tools will help me to to intellisense whether I work in Windows or Linux, thanks to the `ms-vscode.cmake-tools`. That is awesome, by the way, because I don't have to worry about intellisense of C/C++. But it looks like it cannot work well on **MSYS** environment.

## Steps of Building Environment for MSYS

- Download the MSYS2 installer from its [website](https://www.msys2.org/), and follow the instructions listed on the home page to synchronize databases.

- Use `pacman` to install the toolchain of MSYS, `msys2-devel`.

  ```bash
  pacman -S msys2-devel
  ```

- After installing `msys2-devel`, I add the directory of compiler, `C:\msys64\usr\bin`, to the environment variable, `PATH`, so that CMake-Tools can scan for this kit.

- Open VSCode and input `CMake: Scan for Kits` in Command Palette, and then choose the `GCC 10.2.0 x86_64-pc-msys`.

- Input `CMake: Edit User-Local CMake Kits` in Command Palette to open `cmake-tools-kits.json`. Then, add `MSYS Makefiles` as the `preferredGenerator` for the kit `GCC 10.2.0 x86_64-pc-msys`, like this:

  ```
  "name": "GCC 10.2.0 x86_64-pc-msys",
  "compilers": {
      "C": "C:\\msys64\\usr\\bin\\x86_64-pc-msys-gcc.exe",
      "CXX": "C:\\msys64\\usr\\bin\\x86_64-pc-msys-g++.exe"
  },
  "preferredGenerator": {
      "name": "MSYS Makefiles"
  }
  ```

- In order to simulate the POSIX shell, I copy the `msys-2.0.dll` to the output bin directory. But first, I need to locate where `msys-2.0.dll` is, so I use the following code to do it:

  ```cmake
  if(MSYS)
      get_filename_component(msys_bindir "${CMAKE_C_COMPILER}" PATH)
      set(msys_dll_file "${msys_bindir}/msys-2.0.dll")
      file(COPY "${msys_dll_file}" DESTINATION "${output_bindir}")
  endif(MSYS)
  ```

## Here is my code

[vscode-cmake-tools-msys.zip](https://github.com/microsoft/vscode-cmake-tools/files/7068327/vscode-cmake-tools-msys.zip)

## Screenshots of Result

![pic_02](https://user-images.githubusercontent.com/71438617/131155511-d0250483-ba6f-4d7b-8957-43b91240a0a5.png)
![pic_03](https://user-images.githubusercontent.com/71438617/131154995-9204a63d-f8cc-425b-9bfc-73dea0ffecea.png)
![pic_04](https://user-images.githubusercontent.com/71438617/131155003-c1e7d10d-6ad9-4102-ac60-2ec0cb9ec0e6.png)

## Platform and Versions

- **Operating System:** Windows 11
- **CMake Version:** 3.21.1
- **VSCode Version:** 1.59.1
- **CMake Tools Extension Version:** 1.8.0
- **MSYS Toolchain:** 10.2.0

**Comment by hwhsu1231** [comment]
@bobbrow, I'm sorry for bothering you.

I posted this [issue](https://github.com/microsoft/vscode-cmake-tools/issues/2086) 4 days ago. The content is about an **intellisense bug** of CMake-Tools. It looks like `ms-vscode.cmake-tools` cannot work well on the configuration of **MSYS2**. And I hope CMake-Tools can fix this as soon as possible. However until now, I still don't see any comment or response.

-   If I have anything wrong in this issue, please tell me. Maybe I miss something.
-   If I need to provide more informations about this issue, please tell me, too.

**Comment by bobbrow** [comment]
I'm sorry I didn't have any response for you yet.  I started to take a look at this (thank you for attaching the project), but MSYS2 isn't an area of expertise for us and I didn't have anything helpful to recommend yet.  I should have asked you to send me the logs from running the "C/C++: Log Diagnostics" command.  Please make sure your `fork.c` file is open and active in the editor when you run that command.  Thank you!

**Comment by hwhsu1231** [comment]
Here is the output of running **"C/C++: Log Diagnostics"** command when my `fork.c` is open and active in the editor:
```
-------- Diagnostics - 2021/9/1 上午4:28:34
Version: 1.6.0
Current Configuration:
{
    "name": "MSYS",
    "compilerPath": "C:/msys64/usr/bin/g++.exe",
    "includePath": [
        "${workspaceFolder}/**",
        "C:/msys64/usr/include/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "intelliSenseMode": "windows-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/**",
            "C:/msys64/usr/include/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "d:/vscode-cmake-tools-msys/source"
    ],
    "compilerPath": "c:/msys64/usr/bin/x86_64-pc-msys-g++.exe",
    "compilerArgs": [
        "-g"
    ]
}
Custom configurations:
[ D:\vscode-cmake-tools-msys\source\fork.c ]
{
    "defines": [],
    "includePath": [],
    "compilerPath": "c:/msys64/usr/bin/x86_64-pc-msys-gcc.exe",
    "compilerArgs": [
        "-g"
    ]
}
Translation Unit Mappings:
[ D:\vscode-cmake-tools-msys\source\fork.c ]:
    D:\VSCODE-CMAKE-TOOLS-MSYS\SOURCE\FORK.C
Translation Unit Configurations:
[ D:\vscode-cmake-tools-msys\source\fork.c ]:
    Process ID: 26308
    Memory Usage: 14 MB
    Compiler Path: c:/msys64/usr/bin/x86_64-pc-msys-gcc.exe
    Includes:
        C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE
        C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE-FIXED
        C:\MSYS64\USR\INCLUDE\W32API
    Standard Version: c17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=100200
Total Memory Usage: 14 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2331
```

**Comment by hwhsu1231** [comment]
@bobbrow, I don't know the mechanism in `ms-vscode.cmake-tools`. But MSYS is designed for simulating the POSIX shell. Maybe it could take `linux-gcc-x64` as reference.

If I cancel these things: 
- `"configurationProvider": "ms-vscode.cmake-tools"` in local folder's **c_cpp_properties.json**.
- `"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"` in local and global **settings.json**.

And then, I add `"C:/msys64/usr/include/**"` into includePath, and change intelliSenseMode into `"linux-gcc-x64"`. It looks like it can find the header successfully.

![pic_05](https://user-images.githubusercontent.com/71438617/131643697-7b7da723-ecc4-4d2a-a1f1-485e491de8b6.png)

**Comment by bobbrow** [comment]
Do the headers not exist at:
```
Includes:
        C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE
        C:\MSYS64\USR\LIB\GCC\X86_64-PC-MSYS\10.2.0\INCLUDE-FIXED
        C:\MSYS64\USR\INCLUDE\W32API
```

CMake Tools is telling cpptools that the compiler to emulate is `c:/msys64/usr/bin/x86_64-pc-msys-gcc.exe`, but your `c_cpp_properties.json` is pointing to `C:/msys64/usr/bin/g++.exe` instead.  That is part of where the discrepancy is.  If you update your Kit to point to `C:/msys64/usr/bin/g++.exe` does it work?

Another thing to check is to run this command in your MSYS2 terminal:
```
x86_64-pc-msys-gcc -Wp,-v -E -x c /dev/null
```
If that's the compiler you're using, the paths printed out should match what cpptools is using for the include path. If it doesn't, then that's the reason why it's having issues.

**Comment by hwhsu1231** [comment]
I'm not sure that I get the points which you mentioned above. But I try my best.

### Part1

I include 4 headers in the `fork.c`. Here are the location of each header: (None of them exist in those 3 include directories.)

```
C:\msys64\usr\include\stdio.h
C:\msys64\usr\include\stdlib.h
C:\msys64\usr\include\sys\types.h
C:\msys64\usr\include\unistd.h
```

And I check those 3 include directories in File Explorer. They do exist and have lots of headers inside.

### Part2

About what you mentioned, **"update your Kit pointing to `C:/msys64/usr/bin/g++.exe`"**, what does it mean? Do you mean using `pacman` to upgrade the compiler? If not, can you describe more specifically how to do **"update your Kit pointing to `C:/msys64/usr/bin/g++.exe`"**, please?

### Part3

Here is the output of executing `x86_64-pc-msys-gcc -Wp,-v -E -x c /dev/null` in my MSYS2 terminal:

```bash
$ x86_64-pc-msys-gcc -Wp,-v -E -x c /dev/null
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/include"
ignoring duplicate directory "/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/lib/../lib/../../include/w32api"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-pc-msys/10.2.0/include
 /usr/lib/gcc/x86_64-pc-msys/10.2.0/include-fixed
 /usr/include
 /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../lib/../include/w32api
End of search list.
# 1 "/dev/null"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "/dev/null"
```

**Comment by bobbrow** [comment]
**Part 2**
In your first message, you shared the contents of your Kit:
```
"name": "GCC 10.2.0 x86_64-pc-msys",
"compilers": {
    "C": "C:\\msys64\\usr\\bin\\x86_64-pc-msys-gcc.exe",
    "CXX": "C:\\msys64\\usr\\bin\\x86_64-pc-msys-g++.exe"
},
"preferredGenerator": {
    "name": "MSYS Makefiles"
}
```
I was asking if you could set the C and CXX compilers to `c:/msys64/usr/bin/gcc.exe` and `g++.exe`

**Part 3**
The output is linux-style paths, so there may be a problem with cpptools mapping that back to the `c:/msys64` folder which is why it loses `/usr/include`.  I don't understand how it would get the other paths without that one though.  It's a question for @Colengms who should be back online next week.

**Comment by hwhsu1231** [comment]
About **Part 2**, still not working.

And about **Part 3**, so @Colengms will come to take care of this issue when he comes back, right?

**Comment by bobbrow** [comment]
Thanks for checking on Part 2.  Yes, Colen should be back next week and can look at whether cpptools knows how to deal with this.

**Comment by hwhsu1231** [comment]
@Colengms Thank you for your help. Hope this bug can be fixed as soon as possible. 

1.  I have a question. Does the main reason come from `cpptools`? If `cpptools` fix its problem, `cmake-tools` will solve this bug, therefore?

2.  About your suggestion, the reason I use `msys2-devel` in MSYS2 is because I want to use **POSIX API**, such as `fork`, on Windows. However, MinGW is using **WIN32 API**, which is not allowed to use `fork`. Some softwares on Windows are using `msys2-devel`. For example, Git on Windows. We can find the `msys-2.0.dll` in its `usr/bin` directory.

3.  BTW, I heard **MSYS2(msys2-devel)** is related to **Cygwin**. Both of them simulate the **POSIX API**. So if MSYS2(msys2-devel) has some bugs with intellisense of CMake-Tools, **maybe Cygwin will encounter the similar problem**??

**Comment by Colengms** [comment]
Hi @hwhsu1231 

1. Yes, this is a cpptools bug.
3. Yes, it looks like there is a similar issue when using Cygwin.

**Comment by bobbrow** [comment]
The bug in cpptools should be fixed by now.  Please let us know if you continue to have issues.
