### ISSUE TITLE
1.8.0 release cmake.launchTargetPath no longer work in workspace environment

### ISSUE THREAD

**Issue by fsjack** [microsoft/vscode-cmake-tools#2097]
### Brief Issue Summary

Upgraded to 1.8.0 release, found logging below:
[extension] [8721] cmake.launchTargetPath started
[extension] [8721] cmake.launchTargetPath finished (returned null)

### Background
My workspace contains two cpp project, one has CMakeLists.txt the other is not. Active folder has been set to one has CMakeLists.txt.

### Expected:

1, Run command: Debuging: Start debuging and Stop on entry.
2. Run the program and attach to VSCode debugger.

### Apparent Behavior:

1, Run command: Debuging: Start debuging and Stop on entry.
2. No response.

**Comment by bobbrow** [comment]
This is possibly a duplicate of #2091.  Could you follow the steps in https://github.com/microsoft/vscode-cmake-tools/issues/2091#issuecomment-908779211 and verify if that fixes your problem?  We might also release this patch today. We were waiting to see if any other feedback came in before we did.

**Comment by elahehrashedi** [comment]
this should work in the new patch.

**Comment by fsjack** [comment]
fixed using patch, will close.

**Comment by bobbrow** [comment]
Thank you for confirming.  We plan to release 1.8.1 today.
