### ISSUE TITLE
I have received this message " bad Cmake executable"". is it installed or settings contain correct path " what should I do now ?

### ISSUE THREAD

**Issue by reza149** [microsoft/vscode-cmake-tools#2100]

**Comment by bobbrow** [comment]
That message means that we did not find CMake on your computer.  Please go here to install it: https://cmake.org/download/

**Comment by davidlin409** [comment]
But I have installed cmake 20 on Ubuntu-20, the message still shows up. Does CMake Tool support cmake version 20?

**Comment by bobbrow** [comment]
@davidlin409 we don't officially support snaps yet, but there is some information in this issue that may be of help: #838
