### ISSUE TITLE
CMakePresets.json should allow JSON comments

### ISSUE THREAD

**Issue by tilman22** [microsoft/vscode-cmake-tools#2104]
cmake allows the CMakePresets.json file to contain JSON-comments.
But the cmake-extension complains if there are comments:

[presetController] Failed to parse CMakePresets.json: 
	SyntaxError: Unexpected token / in JSON at position 461
	at JSON.parse (<anonymous>)
	at PresetsController.parsePresetsFile (/home/soti/.vscode-server/extensions/ms-vscode.cmake-tools-1.8.0/dist/main.js:57650:32)
	at PresetsController.resetPresetsFile (/home/soti/.vscode-server/extensions/ms-vscode.cmake-tools-1.8.0/dist/main.js:57036:38)
	at async PresetsController.reapplyPresets (/home/soti/.vscode-server/extensions/ms-vscode.cmake-tools-1.8.0/dist/main.js:57051:9)
	at async FSWatcher.<anonymous> (/home/soti/.vscode-server/extensions/ms-vscode.cmake-tools-1.8.0/dist/main.js:56993:17)
[preset] Could not find configure preset with name

**Comment by bobbrow** [comment]
Is that new?  Because we just addressed an issue where someone said cmake doesn't support JSON 5.  See #2035

**Comment by tilman22** [comment]
I'm using cmake 3.20. By trying out, I observed that cmake supports comments in CMakePrefixs.json (i.e. by using "cmake --prefix ...").
The problem which I reported above seems to be an issue of the cmake extension. 
I haven't observed this error messages before (with older previous of the cmake extensions).

[Remark: The cmake Extension is just great! Thanks a lot for your work on the extension!!!]

**Comment by bobbrow** [comment]
@xisui-MSFT When you fixed #2035, what were your observations?

**Comment by xisui-MSFT** [comment]
The extension should force presets files to use json format (as opposed to jsonc) whenever a presets file is opened or activated, and you even shouldn't be able to set it to jsonc manually... But I'm wondering if this is caused by a conflicts with @tilman22 's settings or another extension.

**Comment by bobbrow** [comment]
I don't think it's settings. He is reporting that passing in a preset on the command line works when the CMakePresets file has comments in it.  Do you see the same or different result?

**Comment by xisui-MSFT** [comment]
Ah sorry I misunderstood. That's a good question. We should ask kitware as it's explicitly disallowed in the doc: https://cmake.org/cmake/help/latest/release/3.19.html#id6.

**Comment by bobbrow** [comment]
I can confirm that comments work with the presets file in 3.20.2.  Seems like a bug on Kitware.

**Comment by bobbrow** [comment]
I opened this bug for them: https://gitlab.kitware.com/cmake/cmake/-/issues/22602
