### ISSUE TITLE
Configuration environment is incorrect when using SSH

### ISSUE THREAD

**Issue by langong347** [microsoft/vscode-cmake-tools#2112]
### Brief Issue Summary

I have kept running into this error even after having `"cmake.generator":  "Ninja",` in my settings.
From the OUTPUT tab I can see the option `-G Ninja`. Regardless, the error didn't go away.
Ninja is installed on my machine:
```
$ which ninja
/bin/ninja
$ ninja --version
1.10.2
```
My `$workspaceFolder/.vscode/settings.json`:
```json
"cmake.configureSettings": {
        "PYTHON_EXECUTABLE": "${env:HOME}/local/miniconda3/envs/$env_name/bin/python",
        "PYTHON_INCLUDE_DIR": "${env:HOME}/local/miniconda3/envs/$env_name/include",
        "PYTHON_LIBRARY": "${env:HOME}/local/miniconda3/envs/$env_name/lib",
        "PYTHONLIBS_VERSION_STRING": "3.9",
}
"cmake.buildDirectory": "${workspaceFolder}/$my_build_dir",
"cmake.generator":  "Ninja",
```

### Expected:

Complete the build without Ninja error.

### Platform and Versions

- **Operating System**: Linux CentOS 8
- **CMake Version**: 3.19.6
- **VSCode Version**: 1.59.1
- **CMake Tools Extension Version**: v1.8.1
- **Compiler/Toolchain**: GNU 8.5.0

### Other Notes/Information
I tried to copy the underlying commands used by CMake/CMakeTools extension tab and run them as command line as follows which showed more details:

1. `/bin/cmake -D[SOME_CACHE_VARIABLES] (including python exe, lib, include dir) -G Ninja  -B$my_build_dir -H$my_source_code_dir`
2. `/bin/cmake --build $my_build_dir --config Debug --target clean -j 58`
3. `/bin/cmake --build $my_build_dir --config Debug --target all -j 58` (swap this line with `ninja` will give the same error, see below)

Error message:
```
fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
[1885/2097] Building CXX object test_api/CMakeFiles/test_api.dir/dataloader.cpp.o
ninja: build stopped: subcommand failed.
```

That gives me two questions:
1) Why in step 3, `/bin/cmake --build` is invoked not `ninja`?
2) Why `Python.h` is considered missing although python related cache variables were specified in the configuration?

**Comment by bobbrow** [comment]
1. `/bin/cmake --build` instructs cmake to run the Ninja build for you. This is expected behavior.
2. It is extremely hard for us to know why the compiler could not find Python.h without having access to the project.  Is this an open source project that we can clone? It is likely there there is an error in your CMakeLists.txt or the variables being used to drive the cmake generator.
    1. A possible way to troubleshoot this is to look at the `compile_commands.json` file that is generated in your `cmake.buildDirectory` and make sure that the include paths for your source files look correct.

**Comment by lg20987** [comment]
>    1. A possible way to troubleshoot this is to look at the `compile_commands.json` file that is generated in your `cmake.buildDirectory` and make sure that the include paths for your source files look correct.

Below is a failed example: I was able to find `-isystem /home/langong/local/miniconda3/envs/pytorch/include/python3.9` among the compiler options:

```bash
$ cat compile_commands.json |grep -F "torch/csrc/api/src/python/init.cpp"|grep "miniconda3\/envs\/pytorch\/include\/python3\.9 "

"command": "/home/langong/local/ccache/lib/c++ -DBUILDING_TESTS -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTHP_BUILD_MAIN_LIB -DUSE_C10D -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_CUDA -DUSE_CUDNN -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_NCCL -DUSE_NUMPY -DUSE_RPC -DUSE_TENSORPIPE -DUSE_VALGRIND -D_FILE_OFFSET_BITS=64 -Dtorch_python_EXPORTS -Iaten/src -I../aten/src -I. -I../ -I../cmake/../third_party/benchmark/include -I../cmake/../third_party/cudnn_frontend/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -I../torch/.. -I../torch/../aten/src -I../torch/../aten/src/TH -Icaffe2/aten/src -Ithird_party -I../torch/../third_party/valgrind-headers -I../torch/../third_party/gloo -I../torch/../third_party/onnx -I../torch/csrc -I../torch/csrc/api/include -I../torch/lib -I../torch/lib/libshm -I../torch/csrc/distributed -I../torch/csrc/api -I../c10/.. -Ithird_party/ideep/mkl-dnn/include -I../third_party/ideep/mkl-dnn/src/../include -I../c10/cuda/../.. -I../torch/lib/libshm/../../../torch/lib -I../third_party/fmt/include -Inccl/include -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/protobuf/src -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party/XNNPACK/include -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /home/langong/local/miniconda3/envs/pytorch/include/python3.9 -isystem /home/langong/local/miniconda3/envs/pytorch/lib/python3.9/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -isystem /usr/local/cuda/include -isystem ../third_party/ideep/mkl-dnn/include -isystem ../third_party/ideep/include  -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -fPIC -DCAFFE2_USE_GLOO -DCUDA_HAS_FP16=1 -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -fno-strict-aliasing -Wno-write-strings -Wno-strict-aliasing -pthread -std=gnu++14 -o caffe2/torch/CMakeFiles/torch_python.dir/csrc/api/src/python/init.cpp.o -c /data/users/langong/pytorch/torch/csrc/api/src/python/init.cpp",
```

If you have the time, you can clone the repository by:
```bash
git clone https://github.com/pytorch/pytorch.git
cd pytorch
git submodule sync --recursive
git submodule update --init --recursive --jobs 0
git config --global submodule.recurse true
```
And create conda environment (assuming you have miniconda3 installed):
```bash
conda create -yn pytorch
conda activate pytorch
conda install -y numpy ninja pyyaml mkl mkl-include setuptools cmake cffi hypothesis protobuf mypy
pip install expecttest
```

[Optional] you can install `ccache` via `conda install -y -c conda-forge ccache`, and prefix your compilation commands with ccache binary.

My steps to build `pytorch` via VSCode CMake Tools are (all done in Command Palette)

1. `CMake: Configure`
2. `CMake: Clean and Rebuild` (if a prior build exists, or simply `rm -rf $buildDirectory`)

**Comment by bobbrow** [comment]
If the project can determine the compiler to use without any interaction on your part (e.g. CMake "just works" in the terminal), then you can set the Kit to "Unspecified" and the CMake Tools extension will ignore Kits.

![image](https://user-images.githubusercontent.com/12818240/132551475-eae87f68-f0e7-4ab3-a7e2-696e02cfe8ad.png)

I just kicked off a build now (thanks for the instructions!) but it may take a while.  I did not install ccache, but I will let you know what I find out.  I only set `cmake.generator` to Ninja and added PYTHON_EXECUTABLE to the `cmake.configureSettings`.

**Comment by langong347** [comment]
Thank you for suggestion on the compiler. Let me experiment around.

If the build is too slow, try set these environment flags in your `.vscode/settings.json` to have just the basics:
```json
"cmake.configureSettings": {
      "PYTHON_EXECUTABLE": "${env:HOME}/local/miniconda3/envs/pytorch/bin/python",
      "DEBUG": true,
      "USE_CUDA": false,
      "BUILD_CAFFE2": false,
      "BUILD_CAFFE2_OPS": false,
      "BUILD_TEST": false,
      "USE_DISTRIBUTED": false,
      "USE_MKLDNN": false,
      "USE_FBGEMM": false,
      "USE_NNPACK": false,
      "USE_QNNPACK": false,
      "USE_XNNPACK": false,
}
```
Verify the build through `python -c "import torch"` will throw an error (something like below):
`OSError: missing shared object torch/lib/libtorch_deps_global.so`

**Comment by bobbrow** [comment]
My build fails to link `lib/libtorch_cpu.so`:  "ld terminated with signal 9 [Killed]".  I didn't see any errors about being unable to include `Python.h`.

I think the key question you were asking is about the compiler, so hopefully that addresses what you need.  But as far as inheriting the conda environment, VS Code should already be doing that if you run `code .` from you terminal.  I also tried removing all my `cmake.` settings and that seems to work ok for me.  If you are able to build in the terminal, but not using our extension, then we can look into that more.

**Comment by langong347** [comment]
Thanks for trying to replicate. I ran `cmake` on the command line with an activated conda environment inside vscode:

```
(pytorch) $ cmake -DCMAKE_INSTALL_PREFIX=/path/to/pytorch/torch -DCMAKE_BUILD_TYPE:STRING=Debug -H/path/to/pytorch -B/path/to/pytorch/build -G Ninja 
(pytorch) $ cmake --build /path/to/pytorch/build --target all -j 58
(pytorch) $ python setup.py develop
Building wheel torch-1.10.0a0+git80a6114
-- Building version 1.10.0a0+git80a6114
cmake3 --build . --target install --config Debug -- -j 56
[0/1] Install the project...
-- Install configuration: "Debug"
-- Set runtime path of "/path/to/pytorch/torch/bin/protoc-3.13.0.0" to "$ORIGIN/../lib64"
....
Using /path/to/miniconda3/envs/pytorch/lib/python3.9/site-packages
Finished processing dependencies for torch==1.10.0a0+git80a6114
```
Verify:
```
>>> import torch
>>> torch
<module 'torch' from '/path/to/pytorch/torch/__init__.py'>
>>> x = torch.randn(1)
>>> print(x)
tensor([-0.9099])
```
I was able to achieve the same end result by switching to `cmake-tools` with the following project settings (with the same activated conda environment, unspecified kit)
<img width="621" alt="Screen Shot 2021-09-08 at 11 23 07 PM" src="https://user-images.githubusercontent.com/23155714/132617229-b433868b-3d68-46fc-a133-74d719f26244.png">


```json
"cmake.configureSettings": {
      "CMAKE_PREFIX_PATH": "${env:HOME}/local/miniconda3/envs/pytorch/lib",
      "CMAKE_INSTALL_PREFIX": "${workspaceFolder}/torch",
      "PYTHON_EXECUTABLE": "${env:HOME}/local/miniconda3/envs/pytorch/bin/python",
      "CCACHE_PROGRAM": "${env:HOME}/local/ccache/bin/ccache",
  },
"cmake.buildDirectory": "${workspaceFolder}/build",
"cmake.generator":  "Ninja",
```
However, I noticed the difference between the two approaches, for example, my g++ compiler is prefixed by ccache:
```
# ~/.bashrc
export PATH=/path/to/ccache/lib:/path/to/ccache/bin:$PATH
```
`CMAKE_CXX_COMPILER` resolved:
- `cmake` on command line: `/path/to/ccache/lib/c++`
- `cmake-tools`: `/usr/lib64/ccache/c++`

Expected: 
- Should `cmake-tools` respect the user's shell environment?
- Would `cmake-tools` auto resolve conda environment without user having to specify `"PYTHON_EXECUTABLE"` in the settings?
- I have a long list of cmake variables (some are native to cmake others are specific to the project, not shown above), is `"cmake.configureSettings"` the right place for them?

**Comment by bobbrow** [comment]
> Should cmake-tools respect the user's shell environment?

Yes, it is supposed to.  But I am seeing that the Terminal does not have the same PATH as my conda activated terminal until I run `conda activate pytorch`.  I'm not sure how this all works, but it sounds like something you might want to open a VS Code issue for.  Our extension doesn't have any special knowledge of environments, so unfortunately, this is not something we would be able to help with.

> Would it be nice that cmake-tools auto resolve conda environment without user having to specify "PYTHON_EXECUTABLE" in the settings?

This was working for me. As I mentioned earlier, I cleared out my settings and deleted my CMake cache and it seemed to resolve.  I'm not sure how this project finds python, but it found it for me. I am unsure whether it was the one installed by conda though.

> I have a long list of cmake variables (some are native to cmake others are specific to the project, not shown above), is "cmake.configureSettings" the right place for them?

`cmake.configureSettings` is the right place for args you would pass to cmake on the command line with `-D`.  Other args can be passed with `cmake.configureArgs`.

**Comment by langong347** [comment]
> EDIT: To clarify, when I run code . in the terminal, I expect the current environment of that terminal instance to be inherited by VS Code. I was not seeing that in the "Terminal" window of VS Code. Most env vars were there, but the conda env did not appear to be set yet
Is it possible to run cmake in the same VSCode "Terminal" that's already open (where I have the correct conda environment and etc.)? Right now cmake just runs in the VSCode "Output" tab. I do not see any configuration of `cmake-tools` that would allow this. When I ran `cmake` in the "Terminal", I didn't need to specify the python executable and other environment variables, I expect the same for `cmake-tools`. 

<img width="2501" alt="Screen Shot 2021-09-10 at 10 29 58 AM" src="https://user-images.githubusercontent.com/23155714/132869929-b219f17c-7f9f-4065-a501-c05e931a7929.png">

**Comment by bobbrow** [comment]
Terminal state is mutable, so we don't rely on it to run the cmake commands.  There's also no VS Code API for us to get the environment from a terminal window.

So do you SSH to the remote host using the VS Code Remote extension?  Or do you remote to a terminal and then launch code from there (is this possible)?  I wonder if configuring your `.bashrc` would result in the environment being set up properly when you connect.  Otherwise, I don't think we have a workaround for this scenario yet besides adding the settings you mentioned earlier.

**Comment by langong347** [comment]
> So do you SSH to the remote host using the VS Code Remote extension? Or do you remote to a terminal and then launch code from there (is this possible)? I wonder if configuring your `.bashrc` would result in the environment being set up properly when you connect. Otherwise, I don't think we have a workaround for this scenario yet besides adding the settings you mentioned earlier.

Yes, I use VSCode remote extension from my laptop. I found the issue was due to our Linux server's default login shell being `zsh` which had failed to activate my `.bashrc`. After changing the login shell to `bash`, I am able to see `cmake-tools` pick up the remote configuration.

The remaining open issue is conda activation -- typically, it's not set in `.bashrc` as a developer may not want it to be the default environment upon login. I can activate conda before `code .` on my laptop's terminal which will give me the correct conda environment upon spinning up VSCode.

Regardless of the above, (just for the record) when `PYTHON_EXECUTABLE` is unset, I always get the error message. Not sure how you were able to configure without setting this variable (perhaps you had a default python installation in your system which got picked up instead?)
```
[cmake]   Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (found version "3.9.6")
[cmake] -- Configuring incomplete, errors occurred!
```

We've probably covered enough ground for this topic. Thank you for the support along. Please feel free to close this issue.

**Comment by bobbrow** [comment]
> Regardless of the above, (just for the record) when `PYTHON_EXECUTABLE` is unset, I always get the error message. Not sure how you were able to configure without setting this variable (perhaps you had a default python installation in your system which got picked up instead?)

I didn't SSH into another machine and I always ran `code` from the activated environment so it probably got it from there. 🤷‍♂️ I'm glad to hear that you are unblocked.  Take care!
