### ISSUE TITLE
Regarding .cmake file does not exist.!!!!!

### ISSUE THREAD

**Issue by RiShu36** [microsoft/vscode-cmake-tools#2113]
### Brief Issue Summary

Hi,
I am using visual studio code for my project. This problem occured at the time of compiling. The visual studio code continuosly giving the error message.

CMake Error: The source directory "C:/Users/e1347354/Desktop/myProject/myProject1/.cmake" does not exist.  
Specify --help for usage, or press the help button on the CMake GUI.
The terminal process "C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake -G "Ninja" -DBOARD=EVT -DNW_PROTOCOL=NW_MODBUS_STM32 -DCMAKE_TOOLCHAIN_FILE=windows-toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -B build" terminated with exit code: 1.

### Expected:

The visual studio code suddenly start giving this error. Which i think might happen after the auto update of visual studio code.

### Platform and Versions

- **Operating System**: 
- **CMake Tools Extension Version**: v 0.0.17
- **Compiler/Toolchain**: <!--  GCC 

Just want to know that is there a problem related to cmake file or visual studio code

**Comment by bobbrow** [comment]
I'm not sure what would cause that, but I don't believe our extension usually runs cmake through powershell.  Are you using `tasks.json` or something?  Can you try running the `CMake: Delete cache and Reconfigure` command and let us know if that works?

**Comment by RiShu36** [comment]
Thanks for the reply. Yes i am using task. json. I will try as you suggested once.
