### ISSUE TITLE
Intellisense is not working properly with header files

### ISSUE THREAD

**Issue by bplx** [microsoft/vscode-cmake-tools#2114]
### Brief Issue Summary
Intellisense shows errors in a header file even though i can hit f12 on where it's included and it goes to it.

### Expected:

1. Create a Cmake project
2. Link a header file into the main file
3. Get nice tab completion and have no error squiggles (when the code is written properly, of course)

### Apparent Behavior:

1. Create a Cmake project
2. Link a header file into the main file
3. Intellisense gets angry at me and spams error squiggles, but it still compiles fine

### CMake Tools Log

```
-------- Diagnostics - 9/7/2021, 3:50:49 PM
Version: 1.6.0
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/include/**"
    ],
    "defines": [],
    "cStandard": "gnu17",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerPath": "/usr/bin/g++",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compileCommands": "g++",
    "compilerArgs": [],
    "browse": {
        "path": [
            "${workspaceFolder}/include/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/....../Projects/ActualProject",
        "/home/....../Projects/ActualProject/build/CMakeFiles"
    ],
    "compilerPath": "/bin/x86_64-linux-gnu-g++-9",
    "compilerArgs": []
}
Custom configurations:
[ /home/....../Projects/ActualProject/main.cpp ]
{
    "defines": [],
    "includePath": [
        "/home/....../Projects/ActualProject/include"
    ],
    "compilerPath": "/bin/x86_64-linux-gnu-g++-9",
    "compilerArgs": [
        "-g"
    ]
}
Translation Unit Mappings:
[ /home/....../Projects/ActualProject/main.cpp ]:
    /home/....../Projects/ActualProject/include/test.h
Translation /home/....../Projects/ActualProject/main.cpp ]:
    Process ID: 1493947
    Memory Usage: 18 MB
    Compiler Path: /bin/x86_64-linux-gnu-g++-9
    Includes:
        /home/....../Projects/ActualProject/include
        /usr/include/c++/9
        /usr/include/x86_64-linux-gnu/c++/9
        /usr/include/c++/9/backward
        /usr/lib/gcc/x86_64-linux-gnu/9/include
        /usr/local/include
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=90300
Total Memory Usage: 18 MB
Browse Paths from compile_commands.json, from workspace folder: /home/....../Projects/ActualProject
    /home/....../Projects/ActualProject
    /home/....../Projects/ActualProject/build/CMakeFiles

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5458
```

### Developer Tools Log

```
Not sure how to obtain this.
```

### Platform and Versions

- **Operating System**: Ubuntu 20.04
- **CMake Version**: 3.16.3
- **VSCode Version**: 1.60
- **CMake Tools Extension Version**: Not sure how to get this, sorry
- **Compiler/Toolchain**: GCC 9.3.0 x86_64-linux-gnu

**Comment by bobbrow** [comment]
Does `main.cpp` include `test.h`?  Nothing in particular stands out in your logs.  Do you have a project you can share?

F12 likely works because that feature doesn't depend on the configurations in the same way.

**Comment by bplx** [comment]
Yeah.

main.cpp
```
#include <iostream>

int main(int, char**) {
    std::cout << "Hello, world!\n";
    #include "include/test.h"
}
```

include/test.h:
```
std::cout << "Hello world from testing!" << std::endl;
```

.vscode/c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/include/*"
            ],
            "defines": [],
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64",
            "compilerPath": "/usr/bin/g++",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

**Comment by bobbrow** [comment]
Can you share the CMakeLists.txt you're using for this too?

**Comment by bplx** [comment]
Ok
```
cmake_minimum_required(VERSION 3.0.0)
project(ActualProject VERSION 0.1.0)

include(CTest)
enable_testing()

include_directories(BEFORE include/)

set(SOURCES main.cpp include/test.h)
add_executable(ActualProject ${SOURCES})

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)

```

**Comment by bobbrow** [comment]
Thank you.  However, I do not reproduce a problem with this example.  Your `#include` is using double quotes to locate the file which means that the current directory will be added to the search path.  Adding `include_directories(BEFORE include/)` would be incorrect if you locate the header with angle brackets like this: `#include <include/test.h>` because you would be including the `include` folder twice in the path and I confirmed that that will cause a squiggle to appear.

**Comment by bplx** [comment]
`#include <test.h>` works fine. What other info should i provide?

**Comment by bobbrow** [comment]
I don't have any information that points to a bug in the extension right now.  If you are expecting `#include <include/test.h>` to work, you need to add the folder above `include` to the `include_directories` (e.g. the bug is in your CMakeLists.txt).  If you are ok with using `#include "include/test.h"`, you don't need to change anything because that include path is automatically added by the compiler because of how double quotes work for `#include`.
