### ISSUE TITLE
Configure buttons in the status bar

### ISSUE THREAD

**Issue by mental13** [microsoft/vscode-cmake-tools#212]
I use other VSCode extensions that add buttons to the status bar and cmake tools makes it really cluttered.
I would appreciate options to edit this and hide buttons that are redundant for a specific project
- Run CTest
- Make build and debug target the same (one selection for both)
- Use icons for build and debug buttons
- Minimize the name of the current project (instead of `Cmake: ProjName: Debug: Ready` a simple `ProjName: Debug` would suffice in most cases)

**Comment by leira** [comment]
Or we can configure to disable these status bar buttons all together.

**Comment by vector-of-bool** [comment]
The buttons will have some clean up in 1.1, but I expect more clean up in 1.2, so I'm going to leave this open and move the milestone to 1.2

**Comment by bobbrow** [comment]
VS Code recently added the capability to hide status bar icons from an extension. It's an all-or-nothing toggle, but it should address @leira's comment.

**Comment by tanveerbadar** [comment]
Can I upvote this 1000x? Kit selection and build mode (debug/release) are the biggest offenders here, eating into already limited available space.

**Comment by michaelkollmann** [comment]
It'd be very interesting for me as well to customize which buttons are being displayed in the status bar.

I'm using CMake Tools for embedded development and I have to use a different debugger (marus25.cortex-debug) then the native VSCode one. This makes the "Debug" button in the status bare useless for me as I can't use quick debug. So now there is this button down there in the menu bar and I have to tell all my colleagues that they must not click this button. Quiet annoying...

**Comment by bobbrow** [comment]
@michaelkollmann, if you are using launch.json to configure debugging because the quick debug button doesn't work, you can actually move the launch.json config into the `cmake.debugConfig` setting.  This allows you to override any of the defaults (e.g. `"miDebuggerPath"`) that you may be needing to change.

**Comment by bobbrow** [comment]
This issue was addressed in version 1.4 but was never closed.  New settings `cmake.statusbar.visibility` and `cmake.statusbar.advanced` were added to give you full control over the icons.
