### ISSUE TITLE
build error because binaryDir removed after configure (with preset) step

### ISSUE THREAD

**Issue by anb0s** [microsoft/vscode-cmake-tools#2128]
### Brief Issue Summary

The `binaryDir` configured in the preset (CMakePresets.json) was deleted by `git clean -dfx` or similar task and push button `Build` shows error message:
```
[main] Building folder: repo
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/andre/git/repo/build/default-x86_64
[build] Error: /home/andre/git/repo/build/default-x86_64 is not a directory
[build] Build finished with exit code 1
```

### Expected:

1. Push `Build` 
2. Configure is running automatically if `binaryDir` folder is not found
3. Build is started

OR 

1. Push `Build` 
2. Message `[build] Error: /home/andre/git/repo/build/default-x86_64 is not a directory` appears
3. Push `Configure` and select same preset
4. Configure is running with preset
5. Push `Build` 
6. Build is started

### Apparent Behavior:

1. Push `Build` 
2. Error is shown, see above, `[build] Error: /home/andre/git/repo/build/default-x86_64 is not a directory`
3. Select the configure preset again
4. Configure is not executed (no output)
5. Select the build preset again
6. Push `Build`
7. Error is shown, see above, `[build] Error: /home/andre/git/repo/build/default-x86_64 is not a directory`

### Platform and Versions

- **Operating System**: WSL2 with Debian 11 Bullseye (VSCode running @ Windows 10 1909)
- **CMake Version**: 3.21.2
- **VSCode Version**: 1.60.0
- **CMake Tools Extension Version**: 1.8.1
- **Compiler/Toolchain**: gcc version 10.2.1 20210110 (Debian 10.2.1-6)

**Comment by bobbrow** [comment]
Thank you for reporting this issue. I can reproduce it on Windows, even without WSL2.

**Comment by bobbrow** [comment]
A fix for this issue is out for review.
