### ISSUE TITLE
Incorporate CMake extension functionality into CMake-Tools extension

### ISSUE THREAD

**Issue by me21** [microsoft/vscode-cmake-tools#2144]
When CMake-Tools extension is installed, it installs another extension (CMake, https://github.com/twxs/vs.language.cmake) which provides Intellisense for CMakeLists.txt files.
The problem is, it's not actively maintained (https://github.com/twxs/vs.language.cmake/issues/78). And it does not work for me (no Intellisense hints), so it would be great if you could adopt that extension into yours since it is installed alongside anyway.

**Comment by bobbrow** [comment]
Thank you for your idea.  I believe #93 covers this.  It is on our radar, but has not been queued up for development yet.  Please go click on the 👍 in the first comment to indicate that you want this feature.
