### ISSUE TITLE
CMake Tools exported API is undefined

### ISSUE THREAD

**Issue by enbyted** [microsoft/vscode-cmake-tools#2153]
### Brief Issue Summary

I'm trying to revive an old extension that I wrote for one of my projects and I came upon this roadblock.
When trying to access the cmake tools API from another extension the `exports` variable (or result of `activate()` I tried both) is undefined.

Looking through the code I found
```js
// TODO: Return the extension API
```
at https://github.com/microsoft/vscode-cmake-tools/blob/develop/src/extension.ts#L1755

Which I guess means that this is not currently implemented.
Quick blame shows that it was broken in f6c49d3855bcdd38fc7fc3c3e6a9abd1b73fc4f8 ~3 years ago, so I imagine that's not a very popular feature. Still it would be nice if it got fixed, since the actual API implementation seems to be in place. 

Thank you for delivering this amazing extension and have a wonderful day!

**Comment by bobbrow** [comment]
Hi @enbyted, yes, the API was removed before we assumed ownership of the extension.  It needs some major work before we can re-enable it.  We are tracking the request in #494, so I will close this as a duplicate.  If you click on the 👍 in that issue that will help us track the demand for this feature.

**Comment by enbyted** [comment]
Ah, I'm sorry for creating a duplicate, I tried to search for existing issue, but got way too many results to sift through.

Thanks for the pointer, vote added!
