### ISSUE TITLE
Solution doesn't work!

### ISSUE THREAD

**Issue by driesvanheeswijk** [microsoft/vscode-cmake-tools#2164]
Hey guys, I was also having trouble with VSCode not finding the CMake generator. I'm working on a project for my university. I found that someone had posted some kind of solution and I followed the steps. I copied and pasted the lines of code to the right files, but it doesn't work!

It now shows an error: "Bad CMake executable "C:\msys64\mingw64\bin\cmake.exe". Is it installed or settings contain the correct path (cmake.cmakePath)?".

I am very very very inexperienced with files and this technical kind of stuff.  I added the files that my university gives us for the assignment. Does anybody know what I can do?

[CMakeLists.txt](https://github.com/microsoft/vscode-cmake-tools/files/7315982/CMakeLists.txt)
[secret.txt](https://github.com/microsoft/vscode-cmake-tools/files/7315983/secret.txt)

### CMake Tools Diagnostics

```
<!-- Paste the `CMake: Log Diagnostics` output HERE -->
```

### Debug Log

```
<!-- Paste the debug log contents HERE -->
```

**Comment by andreeis** [comment]
@driesvanheeswijk, do you confirm that there is a cmake.exe at the mentioned path?
If not, find where it is installed on your system and point the extension to that path via the setting "cmake.cmakePath" in your project .vscode/settings.json.
Let us know how it goes.
