### ISSUE TITLE
environment variables in CMakePresets.json not evaluated correctly on Raspberry Pi 

### ISSUE THREAD

**Issue by jureid** [microsoft/vscode-cmake-tools#2184]
Extension version: 1.9.0
OS: Raspberry Pi

When I reference environment variables in CMakePresets.json, CMake Tools does not evaluate them correctly. For example, I get this error with the following CMakePresets.json (it works when I invoke the build from the command line). The environment variables are defined in my .bashrc file.

Executing command: /usr/local/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ **-DCMAKE_TOOLCHAIN_FILE="/scripts/buildsystems/vcpkg.cmake"** -DCMAKE_INSTALL_PREFIX="/home/pi/demos/blink/out/install/raspi-debug" -H/home/pi/demos/blink -B/home/pi/demos/blink/out/build/raspi-debug -G Ninja
[cmake] CMake Error at /usr/local/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:130 (message):
[cmake]   **Could not find toolchain file: "/scripts/buildsystems/vcpkg.cmake"**

CMakePresets.json
```
{
    "version": 3,
    "configurePresets": [
        {
            "name": "base",
            "description": "For more information: http://aka.ms/cmakepresetsvs",
            "hidden": true,
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/out/build/${presetName}",
            "installDir": "${sourceDir}/out/install/${presetName}",
            "toolchainFile": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
            "cacheVariables": {
                "CMAKE_C_COMPILER": "gcc",
                "CMAKE_CXX_COMPILER": "g++"
            },
            "environment": {
                "VCPKG_FEATURE_FLAGS": "manifests,versions,binarycaching,registries"
            },
            "condition": {
                "type": "equals",
                "lhs": "${hostSystemName}",
                "rhs": "Linux"
            }
        },
        {
            "name": "raspi-debug",
            "displayName": "Raspberry Pi Debug",
            "description": "Sets debug build type",
            "inherits": "base",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Debug"
            }
        },
        {
            "name": "raspi-release",
            "displayName": "Raspberry Pi Release",
            "description": "Sets release build type",
            "inherits": "base",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Release"
            }
        }
    ],
    "buildPresets": [
        {
            "name": "default-build-raspi",
            "displayName": "Default",
            "configurePreset": "raspi-debug",
            "description": "Vanilla build"
        },
        {
            "name": "verbose-build-raspi",
            "displayName": "Verbose Build",
            "description": "Passes -v to Ninja",
            "configurePreset": "raspi-debug",
            "nativeToolOptions": [
                "-v"
            ]
        }
    ],
    "testPresets": [
        {
            "name": "core-test-raspi",
            "description": "Enable output on failure",
            "configurePreset": "raspi-debug",
            "output": {
                "outputOnFailure": true
            }
        }
    ]
}
```
output when run from command line:

pi@raspberrypi:~/demos/blink $ cmake --preset raspi-debug
Preset CMake variables:

  CMAKE_BUILD_TYPE="Debug"
  CMAKE_CXX_COMPILER="g++"
  CMAKE_C_COMPILER="gcc"
  CMAKE_INSTALL_PREFIX:PATH="/home/pi/demos/blink/out/install/raspi-debug"
  CMAKE_TOOLCHAIN_FILE:FILEPATH="/home/pi/vcpkg/scripts/buildsystems/vcpkg.cmake"

Preset environment variables:

  VCPKG_FEATURE_FLAGS="manifests,versions,binarycaching,registries"

-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/demos/blink/out/build/raspi-debug

**Comment by lygstate** [comment]
Well, it's a know issue that $env{VCPKG_ROOT} are not expand properly,
as VCPKG_ROOT are comes from penv{VCPKG_ROOT}

**Comment by lygstate** [comment]
refer to https://github.com/microsoft/vscode-cmake-tools/issues/2233
