### ISSUE TITLE
configure cmake.SourceDirectory in cmake-variants.json

### ISSUE THREAD

**Issue by prudhomm** [microsoft/vscode-cmake-tools#2201]
### Brief Issue Summary

following #2200 it would be great to be able to configure `cmake-sourceDirectory` in `cmake-variants.json`

For example, something like this

```
"components": {
        "default": "all",
        "description": "Enable/Disable components",
        "choices": {
            "all": {
                "short": "all",
                "long": "Enable all components."
            },
            "mor": {
                "short": "mor",
                "long": "Enable mor.",
                "settings": {
                    "ENABLE_MOR": "ON"
                },
                "env":  {
                    "cmake.sourceDirectory": "${workspaceFolder}/mor"
                }
            }
        }
    }
```

Currently vscode says it is invalid to do so

**Comment by andreeis** [comment]
@prudhomm, thank you for this feature idea. We don't think we will support this scenario so I am closing for the moment. We intend to address https://github.com/microsoft/vscode-cmake-tools/issues/2200 at some point and hopefully that will give you all the support that you need in your project.
