### ISSUE TITLE
Switching a Configure Preset requires a manual reconfigure to display the valid new Targets in Preset

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cmake-tools#2219]
If I change to a preset which contains different targets in "Targets in Preset" I see a list of the targets of the previous configuration. Wouldn't it be better to display a empty list and warn/ask us to reconfigure?

It is a bit confusing as it is.

**Comment by andreeis** [comment]
@H-G-Hristov, I do not reproduce this. Maybe there is something special in the structure that you define. Can you share how all the involved presets are written?

**Comment by H-G-Hristov** [comment]
These are my presets:
[Archive.zip](https://github.com/microsoft/vscode-cmake-tools/files/7460424/Archive.zip)

**Comment by andreeis** [comment]
@H-G-Hristov, I see no build preset and no "targets" in the archived json files. What presets are you specifically toggling between and what are the two sets of custom targets?
