### ISSUE TITLE
Select specific CMake Files (-P)

### ISSUE THREAD

**Issue by StStME** [microsoft/vscode-cmake-tools#2223]
### Brief Issue Summary

I cannot find an Setting to specify a custom cmake script like it can be done from the command line with the "-P" option. 

It allows defining a custom root folder but is always searching that folder for a CMakeLists.txt.

I have many different "root" CMakeLists.txt files in one folder with custom names and would like to use them depending on the selected build Kit like:
```
# settings.json
...
    "cmake.sourceDirectory": "${workspaceFolder}/cmake/cmake-${buildKit}.cmake",
...
```
and of course then specify a custom build folder the same way (which is already possible) but it would be nice to be able to define multiple build folders as well (but CMakes "external_project" does the trick here for now).

**Comment by andreeis** [comment]
@StStME, thank you for this feature idea. Indeed, currently we only support searching and reading from "CMakeLists.txt". I was not familiar with the -P switch. We can look at this at some point (we may not be able to implement such support immediately but we would gladly accept a PR from the community if anyone gets to try this before us).

**Comment by linquize** [comment]
`cmake -P` is called **script mode**.
It runs a cmake script `*.cmake` but not `CMakeLists.txt`.
It only takes `-D` options. Extra options are passed to `${CMAKE_ARGV}` of the script.
