### ISSUE TITLE
No Way to Configure CTest Command

### ISSUE THREAD

**Issue by LeonineKing1199** [microsoft/vscode-cmake-tools#2228]
There doesn't seem to be any way for a user to specify the command line options passed to ctest when using the extension.

For example, the following command is always runs:
```console
[proc] Executing command: /home/exbigboss/cpp/cmakes/cmake-3.21.4-linux-x86_64/bin/ctest -j6 -C Debug -T test --output-on-failure
```

Using the Settings UI to edit CTest Args will pass them to `ctest` but wrapped in double-quotes so there's no way, for example, to specify `-T memcheck`.

There should be a UI setting to let  a user override how `ctest` is invoked.

**Comment by andreeis** [comment]
@LeonineKing1199, thank you for this feature idea. It will be useful to implement. We may not get to it immediately and we will also monitor the upvotes from the community to evaluate where this would best fit in our backlog.

**Comment by bobbrow** [comment]
Sorry if I am misunderstanding something, but can't you use `"cmake.ctestArgs": ["-T", "memcheck"]`?  If you are passing in a single string for all of the args, that would be why the extension wraps it in quotes.

**Comment by LeonineKing1199** [comment]
Ah, that was the secret. I didn't realize that was valid syntax.

I had tried via the UI to just add a single string for all the args and was surprised it didn't work.

So via the UI, I would just have to add `-T` and `memcheck` as separate arguments?

**Comment by bobbrow** [comment]
Yes, anything that is spaced out needs to be added as separate args.

**Comment by LeonineKing1199** [comment]
Ah, I see.

Alright, well, technically, my issue's been resolved as I'm now able to run my test suite through valgrind.

This issue can go ahead and be marked closed unless there's any UI refactoring y'all wanna tackle.

**Comment by bobbrow** [comment]
Thanks for confirming. We don't own the UI, the VS Code team does, so I'll go ahead and close this issue.

**Comment by linquize** [comment]
If you have `CMakePresets.json`, you can put `"testPresets"`. 
`vscode-cmake-tools` can work with Test Presets.
