### ISSUE TITLE
Presets in CMakePresets.json should not inherit from presets in CMakeUserPresets.json.

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#2232]
### Brief Issue Summary
Shold warning or erroring when 
Presets in CMakePresets.json inherit from presets in CMakeUserPresets.json.

**Comment by bobbrow** [comment]
Does the extension allow you to use invalid presets like this, or are you just saying you want us to add a warning for it?

**Comment by lygstate** [comment]
> Does the extension allow you to use invalid presets like this, or are you just saying you want us to add a warning for it?

Hi, cmake report error for this, but vscode-cmake-tools didn't report that.

**Comment by bobbrow** [comment]
Interesting. Ok, we'll need to debug it. A few weeks ago I was in the presets code and it looked like the inheritance for CMakePresets shouldn't know about CMakeUsersPresets, but we can look again.
