### ISSUE TITLE
Allow overriding CMake environment variables when using presets

### ISSUE THREAD

**Issue by NicolasIRAGNE** [microsoft/vscode-cmake-tools#2243]
Maybe I am doing something wrong but at the moment I am not using the presets that I have defined because it is very unpractical due to not being able to specify "sticky" variables, because using presets automatically ignores options such as `cmake.configureEnvironment`. 
My project has multiple dependencies that have to be manually specified during configure time (like OpenCV installation directory, etc), and as far as I know, this is currently only possible through editing the cache manually, which is pretty tedious because everytime cache is deleted or preset is changed they are gone. 
Having the option to not ignore environment would solve my problems.

But again, maybe I'm just not doing this properly.
What do you think ?

**Comment by bobbrow** [comment]
Would you be able to add a "hidden" preset that just sets "cacheVariables" and have your other presets inherit from it?  The reason to disable the VS Code-specific settings for presets is because presets are expected to be portable across IDE's and CLI.

**Comment by NicolasIRAGNE** [comment]
Yeah I was thinking about that, but in order to do that I would need to either:
 * Add it to the `CMakePresets.json` file and have everything inherit from it. This would be fine but the file is tracked by git and that would be problematic because my colleagues also need to use presets.
 * Add it to `CMakeUserPresets.json` but then the presets in `CMakePresets.json` will not be able to inherit from it, right ?
 
I'm still having trouble understanding what the proper methodology here is. Isn't it common to have to specify extra, user dependant stuff in the cmake invocation ? 
When building on CLI I just use `cmake --preset=<name> -DVAR=FOO`  and would like to have similar behavior here.

**Comment by bobbrow** [comment]
> * Add it to the `CMakePresets.json` file and have everything inherit from it. This would be fine but the file is tracked by git and that would be problematic because my colleagues also need to use presets.

Is this a problem because you want to set machine-specific variables in it?

> * Add it to `CMakeUserPresets.json` but then the presets in `CMakePresets.json` will not be able to inherit from it, right ?

Correct.

> I'm still having trouble understanding what the proper methodology here is. Isn't it common to have to specify extra, user dependant stuff in the cmake invocation ? When building on CLI I just use `cmake --preset=<name> -DVAR=FOO` and would like to have similar behavior here.

Related discussion: #1829, #1835, #1836
@esweet431 this keeps coming up.

**Comment by NicolasIRAGNE** [comment]
>Is this a problem because you want to set machine-specific variables in it?

Yes, exactly. We have ~3 people working on the project, everyone having different paths. We have 6 presets atm, and we cannot really afford to duplicate them all, especially since the added variables are always the same.

**Comment by stilllman** [comment]
> Would you be able to add a "hidden" preset that just sets "cacheVariables" and have your other presets inherit from it? The reason to disable the VS Code-specific settings for presets is because presets are expected to be portable across IDE's and CLI.

I stumbled upon this issue while trying to set environment variables _specific_ to VS Code, on purpose. I wanted a different behavior when using my preset from the command line and from VS Code, but couldn't achieve it because `cmake.environment` was silently ignored. Sure if I want an env var to be set consistently everywhere I will put it in my presets, but this is not necessarily the case for all variables.

**Comment by Ghabry** [comment]
I noticed the same now for the generator setting. In my VsCode settings the generator is ``ninja`` but the preset does not define any because that is up to the developer to decide with ``-G`` what to use.

Is there a good workaround by now?

Adding presets that specify ninja as generator is not an option because our presets are already so verbose that we would need to add 30 new preset entries to the json file to cover everything.

**Comment by snehara99** [comment]
Thanks for all of your feedback. We typically look at "thumbs ups" to track interest, so be sure to leave one to best help us.
