### ISSUE TITLE
Visual Studio Not Recognizing "NMake Makerfiles" from CMake

### ISSUE THREAD

**Issue by GitbyGit** [microsoft/vscode-cmake-tools#2250]
### I am extremely new to this world of embedded systems so bear with me. I am following along with the set up from https://www.youtube.com/watch?v=mUF9xjDtFfY channel and I continue to get the same issue. To the best of my knowledge I have followed the guide to a T.

I am using windows 10 64bit and all the same settings as the video.
Visual studio 2019

### Debug Log

[main] Building folder: pico-examples 
[proc] Executing command: "C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gcc.exe" -v
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Build failed: Unable to configure the project {}

**Comment by bobbrow** [comment]
Can you share your settings for the `cmake.generator` and `cmake.preferredGenerators` with us?
Also, can you run the `CMake: Log Diagnostics` command and share that output as well?

Thank you!
