### ISSUE TITLE
Consider recommending CMake Language Support

### ISSUE THREAD

**Issue by josetr** [microsoft/vscode-cmake-tools#2253]
The only recommended extension in the README file is `twxs.cmake` which has a lot of unresolved [issues](https://github.com/twxs/vs.language.cmake/issues) so I would ask you guys to consider trying `CMake Language Support` and recommending it if it's good enough.

Download link: https://marketplace.visualstudio.com/items?itemName=josetr.cmake-language-support-vscode
Repository: https://github.com/josetr/cmake-language-support
Interactive Preview: https://josetr.github.io/cmake-language-support

**Comment by bobbrow** [comment]
Thanks for your work on this @josetr.  We'll take a look, but just to set expectations as we approach the holiday season in the US, that this investigation may be delayed a bit.  To help make sure we keep it on our radar, I would recommend you open a PR to change the extension pack dependency in `package.json` to point to your extension instead.
