### ISSUE TITLE
Unable to start debugging. GDB exited unexpectedly.

### ISSUE THREAD

**Issue by TheLardos** [microsoft/vscode-cmake-tools#2256]
### Brief Issue Summary

Hi everyone,

I just set up cmake with a medium sized c++ project using g++ that came with the msys64 installation. The program runs and compiles as expected. However, when I want to debug (I go into the cmake tools section, right click on my project and click debug), the debugging doesn't start. It crashes with the message: 

```
ERROR: Unable to start debugging. GDB exited unexpectedly.

The program 'C:\Users\rueffe01\Documents\vscode_projects\mm_ionsimulator\build\mm_ionsimulator.exe' has exited with code 0 (0x00000000).

ERROR: During startup program exited with code 0xc0000139.
```

My CMakeList.txt looks as follows:

```
cmake_minimum_required(VERSION 3.0.0)
project(mm_ionsimulator VERSION 0.1.0)

include(CTest)
enable_testing()

add_library(
    mm_ionsimulatorlib
    dicer.h
    dicer.cpp
    dp45.h
    dp45.cpp
    fft.h
    fft.cpp
    parser.h
    parser.cpp
    potentials.h
    potentials.cpp
    rk4_fixed.h
    rk4_fixed.cpp
    rk4_adaptive.cpp
    temperature.h
    temperature.cpp
)

add_executable(mm_ionsimulator main.cpp)

target_link_libraries(mm_ionsimulator PRIVATE mm_ionsimulatorlib)

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)
```

This is my CMake: Log Diagnistics output:

```
{
  "os": "win32",
  "vscodeVersion": "1.62.3",
  "cmtVersion": "1.9.1",
  "configurations": [
    {
      "folder": "c:\\Users\\rueffe01\\Documents\\vscode_projects\\mm_ionsimulator",
      "cmakeVersion": "3.21.4",
      "configured": true,
      "generator": "MinGW Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "C:/msys64/mingw64/bin/x86_64-w64-mingw32-gcc.exe",
        "CXX": "C:/msys64/mingw64/bin/x86_64-w64-mingw32-g++.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 30,
    "executablesCount": 1,
    "librariesCount": 1,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}

```

I'm thankfull for any help I can get on this.

Cheers,
Luca

**Comment by bobbrow** [comment]
We've had a lot of trouble with the msys64 environment in the past, and I'll be honest, we're not experts in that system. I would venture a guess that the target being debugged is not launched in the correct environment and immediately exits.  Is your executable capable of running correctly outside of that environment?

**Comment by TheLardos** [comment]
Hey, sorry for my late reply.
Yes, I can run my executable outside the environment.

**Comment by TheLardos** [comment]
Hey,

so just a quick update:
So apparently it works now. The problem I was having originally was that I was unable to compile a program that was able to compile before without changing any code of that program. I'm assuming that this was caused by some internal software update that my company is doing regulary. It might also be this update that caused the problem with the debugger.

Now everything works fine again without me doing anything... Good I hate these random updates...

Thank you for your time!

**Comment by bobbrow** [comment]
Ok. Glad to hear you're unblocked!
