### ISSUE TITLE
Caf

### ISSUE THREAD

**Issue by CwanyJest95** [microsoft/vscode-cmake-tools#2269]
https://github.com/microsoft/TypeScript/commit/daa99cef537cafb28de42e72a529e4ed7cb8aa58

**Comment by CwanyJest95** [comment]
![05-23-24-kit_selector.png](https://user-images.githubusercontent.com/92183675/143810084-d30c6169-3a27-4f3b-a207-c2941eb2cd31.png)

**Comment by bobbrow** [comment]
If you are looking to discuss something, please try https://github.com/microsoft/vscode-cmake-tools/discussions
If you are reporting an issue with the extension, please provide more detail.

I'm closing this issue as it is currently not actionable.
