### ISSUE TITLE
Support for precompiled headers with vscode-cpptools

### ISSUE THREAD

**Issue by sam20908** [microsoft/vscode-cmake-tools#2272]
### Brief Issue Summary

From https://github.com/microsoft/vscode-cpptools/issues/8355#issuecomment-962278716.
This is not directly related to cmake-tools, but given the comment from the cpptools repository, I wanted to bring this here to see what you guys think about it.

### CMake Tools Diagnostics

```
<!-- Paste the `CMake: Log Diagnostics` output HERE -->
```

### Debug Log

```
<!-- Paste the debug log contents HERE -->
```

**Comment by bobbrow** [comment]
We'll need to coordinate this with cpptools.  It doesn't support PCH for IntelliSense configuration yet so it is not ready for us to send this information.
