### ISSUE TITLE
Visual Studio 2008 devenv do not recognize options /m, /property:GenerateFullPaths=true

### ISSUE THREAD

**Issue by mateka** [microsoft/vscode-cmake-tools#228]
When building project in vscode with cmake tools, devenv.exe fails with error stating about unknown options. If I return empty array from lambda creating generator_args in function public async build(target_: Maybe<string> = null): Promise<Number> (at line 1088 in src/common.ts), then everything works. Maybe there should be check for generator version?

**Comment by FoxDevilsWild** [comment]
Same here with Visual Studio 2010. Tried to set an empty generator but without success.

**Comment by vector-of-bool** [comment]
Sorry for the lengthy delay. Been busy IRL.

The VS generators cause me much sadness. They're hard to get right, really. I'll see what I can do about this.

**Comment by ytimenkov** [comment]
VS 2008 doesn't have msbuild, so it needs to use other parameters.
Unfortunately I don't know cross-platform way to specify multiprocess builds.

**Comment by ftrier** [comment]
Would it be possible to manually modify the parameters attached to cmake with "--" in the settings?
As unfortunately I am using VS 2008 and this bug is very annoying.
If I can contribute somehow, please tell me.
