### ISSUE TITLE
Multiple include folders with the same name - missing include files error

### ISSUE THREAD

**Issue by Leopard20** [microsoft/vscode-cmake-tools#2284]
In my CMake project I have two include folders that have the same name, but intellisense shows missing file error for files that are in one of those folders, while the other folder works fine. 

I don't have this problem in Visual Studio 2019.

I'm not sure if this problem is related to this extension or [cpptools](https://github.com/Microsoft/vscode-cpptools), but since I use this extension as the configuration provider for cpptools, I thought it might be related to this one.

**Comment by bobbrow** [comment]
It's probably an issue with this extension, but to make sure, can you:
1. Open both the file that shows the IntelliSense errors and the one that doesn't but uses the same named include folder
2. Then run the `CMake: Log Diagnostics` command and share the output here?

We can then review what the extension is reporting that it expects the configuration should be.

**Comment by Leopard20** [comment]
@bobbrow 
It appears that the problem is something else.
As you can see in the output, one of my include folders has an incorrect name: (stuff that are wrapped in `<>` are just personal info that I removed)
* `"<repo_root>/external/assimp/out/build/x64-/include"`

This is how I've set it up in my CMakeLists:
```cmake
if (${BUILD_X64})
    include_directories(${INCLUDE_DIR}/Assimp/out/build/x64-${CMAKE_BUILD_TYPE}/include)
else()
    include_directories(${INCLUDE_DIR}/Assimp/out/build/x86-${CMAKE_BUILD_TYPE}/include)
endif()
```
So it appears that `CMAKE_BUILD_TYPE` is not set. I also tested it like this and I get an empty output:
```cmake
message("Build Configuration: ${CMAKE_BUILD_TYPE}")
```
However I have selected the build configuration:
![image](https://user-images.githubusercontent.com/16115820/145900897-7c360d26-e131-4548-a99b-3376bc5534fe.png)

```json
{
  "os": "win32",
  "vscodeVersion": "1.63.0",
  "cmtVersion": "1.9.2",
  "configurations": [
    {
      "folder": "",
      "cmakeVersion": "3.21.1",
      "configured": true,
      "generator": "Visual Studio 16 2019",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Release",
    "buildTypesSeen": [
      "Release",
      "Debug",
      "Release_Tracy"
    ],
    "requests": [
      "<repo_root>/src/engine/model/anim.cpp"
    ],
    "responses": [
      {
        "uri": "<repo_root>/src/engine/model/anim.cpp",
        "configuration": {
          "defines": [
            "WIN32",
            "_WINDOWS",
            "NDEBUG"
          ],
          "standard": "c++20",
          "includePath": [
            "<repo_root>/src",
            "<repo_root>/external",
            "<repo_root>/external/imgui",
            "<repo_root>/external/glm/glm",
            "<repo_root>/external/assimp/include",
            "<repo_root>/external/glew/include",
            "<repo_root>/external/glfw/include",
            "<repo_root>/external/robin",
            "<repo_root>/external/cereal/include",
            "<repo_root>/external/zstd/include",
            "<repo_root>/external/freetype/include",
            "<repo_root>/external/assimp/out/build/x64-/include"
          ],
          "compilerPath": "c:/program files (x86)/microsoft visual studio/2019/community/vc/tools/msvc/14.29.30133/bin/hostx64/x64/cl.exe",
          "compilerArgs": [
            "/DWIN32",
            "/D_WINDOWS",
            "/EHsc",
            "/O2",
            "/Ob2",
            "/DNDEBUG",
            "-MD",
            "-std:c++20"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 3,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "ALL_BUILD",
        "type": "UTILITY"
      },
      {
        "name": "<repo_name>",
        "type": "EXECUTABLE"
      },
      {
        "name": "ZERO_CHECK",
        "type": "UTILITY"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

**Comment by bobbrow** [comment]
The Visual Studio generators generate multiple `CMAKE_BUILD_TYPE`s in a single pass, so that variable won't have a value when CMakeLists.txt is processed.  Instead, you tell CMake which build type to use at build time.

The way to make this work without changing your CMakeLists.txt is to use a "single config" generator like "Ninja" instead of Visual Studio.

**Comment by bobbrow** [comment]
And a little more context... The Kit you've selected uses the VS 2019 generator by default.  So you need to set the `cmake.generator` setting to "Ninja"

**Comment by Leopard20** [comment]
@bobbrow Yes, that appears to have fixed my problem. Thank you.
