### ISSUE TITLE
Using specified build target for launch.json debugging

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode-cmake-tools#2285]
### Brief Issue Summary

When I debug using a launch.json configuration, I'm wondering if there's a way to specify the cmake target that gets built first. It seems to use the selected cmake debug target, rather than the selected cmake build target.

I have a project with several cmake targets, but only one can be debugged using cmake (MyProject_Standalone below). I'd like to add a launch.json configuration that builds one of the other targets (MyProject_AU below), then launches my own command for debugging it (which loads the target as a plugin). I can currently only do this if I manually build the target I want, then run the debug configuration.

(I'm a cmake newbie, so forgive me if I'm missing something obvious.)

### CMake Tools Diagnostics

```
{
  "os": "darwin",
  "vscodeVersion": "1.63.0",
  "cmtVersion": "1.9.2",
  "configurations": [
    {
      "folder": "/path/to/my/project",
      "cmakeVersion": "3.22.0",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/clang",
        "CXX": "/usr/bin/clang++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 5,
    "executablesCount": 1,
    "librariesCount": 3,
    "targets": [
      {
        "name": "MyProject",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "MyProject_AU",
        "type": "MODULE_LIBRARY"
      },
      {
        "name": "MyProject_All",
        "type": "UTILITY"
      },
      {
        "name": "MyProject_Standalone",
        "type": "EXECUTABLE"
      },
      {
        "name": "MyProject_VST3",
        "type": "MODULE_LIBRARY"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}

```

### Debug Log

N/A

**Comment by bobbrow** [comment]
Can you share your `launch.json` configuration?  If you are using the [Command Substitution](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#command-substitution) we don't have a variable that represents the currently selected debug target since we assume that you want to debug what you just built.

**Comment by jacobweber** [comment]
I just had something like this:

```
    {
      "name": "Reaper Debug",
      "type": "cppdbg",
      "request": "launch",
      "program": "/Applications/REAPER.app/Contents/MacOS/REAPER",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [
        {
          "name": "PATH",
          "value": "$PATH:${command:cmake.launchTargetDirectory}"
        },
      ],
      "externalConsole": false,
      "MIMode": "lldb"
    }
```

It seems like maybe I need command:cmake.launchTargetDirectory somewhere in there, or it won't build any target before debugging?

But in any case, it builds the only "executable" target, whereas I'd like to build one of the library targets.
