### ISSUE TITLE
Cannot use semicolons in variant settings

### ISSUE THREAD

**Issue by fhriley** [microsoft/vscode-cmake-tools#2287]
### Brief Issue Summary

Semicolons in the variant settings are escaped with backslashes, which changes the meaning of the setting.

I have a cppcheck variant with the settings as follows:

```json
"settings": {
    "CMAKE_CXX_CPPCHECK": "/usr/bin/cppcheck;--std=c++17;--inline-suppr"
}
```

This ends up on the cmake command line like this:

```
"-DCMAKE_CXX_CPPCHECK:STRING=/usr/bin/cppcheck\;--std=c++17\;--inline-suppr"
```

This fails to run cppcheck.

**Comment by MarioGini** [comment]
Probably same issue that https://github.com/microsoft/vscode-cmake-tools/issues/2238 also reports

**Comment by bobbrow** [comment]
Yes, you are correct. This is a duplicate.
