### ISSUE TITLE
CMakePresets.json when use MSVC 2022 "generator" and set "configuration" in "buildPresets", the Launch button doesn't work

### ISSUE THREAD

**Issue by traversebitree** [microsoft/vscode-cmake-tools#2293]
### Brief Issue Summary

I'm using the following CMakePresets.json file in VS Code

```json
{
    "version": 3,
    "configurePresets": [
        {
            "name": "MSVC 2022",
            "displayName": "Visual Studio Professional 2022 - amd64",
            "description": "Using compilers for Visual Studio 17 2022 (x64 architecture)",
            "generator": "Visual Studio 17 2022",
            "toolset": "host=x64",
            "architecture": "x64",
            "binaryDir": "${sourceDir}/out/build/${presetName}",
            "cacheVariables": {
                "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}"
            }
        }
    ],
    "buildPresets": [
        {
            "name": "Debug",
            "configurePreset": "MSVC 2022",
            "configuration": "debug"            
        },
        {
            "name": "Release",
            "configurePreset": "MSVC 2022",
            "configuration": "release"
        }
    ]
}
```

I use **Visual Studio Professional 2022** as **generator**, and use "**debug**"  and "**release**" configuration in "**buildPresets**". Then, I build the target is no problem, but when I clicked the **Launch button**, it doesn't work. But when I changed my generator to MinGW, it works.
![image](https://user-images.githubusercontent.com/30373236/146634591-5f8d0179-fc5e-4b6a-aff0-3cc58011f0d3.png)

**Comment by traversebitree** [comment]
And what's more, using **Visual Studio Professional 2022** as **generator**, **set default build target** button doesn't work either. This button can't find targets anymore.

![image](https://user-images.githubusercontent.com/30373236/146634811-a2b6586c-86ee-482f-871f-9aafd3aa3d3f.png)

**Comment by bobbrow** [comment]
Sorry I can't test this right now as I'm on vacation, but can you try the CMake spelling of the `configuration`s and see if that fixes it? I believe it is case-sensitive.

debug -> Debug
release -> Release

**Comment by traversebitree** [comment]
> Sorry I can't test this right now as I'm on vacation, but can you try the CMake spelling of the `configuration`s and see if that fixes it? I believe it is case-sensitive.
> 
> debug -> Debug release -> Release

Thank you very much, you helped me!
