### ISSUE TITLE
[Question] Where are the CMake preset options?

### ISSUE THREAD

**Issue by Leopard20** [microsoft/vscode-cmake-tools#2294]
When I type `> CMake p` into the command palette I don't see any of the preset options. Could someone please explain to me why? Is it a bug? I've set `cmake.useCMakePresets` to `auto`. 
![image](https://user-images.githubusercontent.com/16115820/146717244-08aa1962-6cfe-4d51-8adb-9cbdf2c550e6.png)

The option was there a few days ago. Not sure what I've changed that made it disappear.

VSCode info (latest):
```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```
CMake Tools version (latest): `1.9.2`

**Comment by bobbrow** [comment]
If you are using `auto` and there is not a `CMakePresets.json` file next to your root `CMakeLists.txt`, then the commands will not be there because it is determined that you are not using presets.  You either need to create a `CMakePresets.json` file or change the setting to `always`.
