### ISSUE TITLE
How to use `mold` linker?

### ISSUE THREAD

**Issue by vadi2** [microsoft/vscode-cmake-tools#2300]
How can I use the [mold](https://github.com/rui314/mold) linker with cmake tools? There's a few ways one can use it: https://github.com/rui314/mold/issues/131 but I didn't see any options that fit the patterns in cmake tools settings.

**Comment by bobbrow** [comment]
Thank you for your feedback.

I don't anticipate us ever adding support to override our configure commands using something like `mold -run ...`.  However, the readme of that project appears to provide information about how to configure clang/gcc to use that linker instead using standard command switches here under "a classic way to use mold": https://github.com/rui314/mold#how-to-use

Then it's just a matter of adding those switches in your CMake scripts.  An example can be found here: https://stackoverflow.com/questions/1867745/cmake-use-a-custom-linker

If you're still blocked, we might be able to help out in some other way, but I don't think you need a feature from our extension to make this work.

**Comment by vadi2** [comment]
I was able to embed the use of alternative linkers in my CMake scripts with https://github.com/omnisci/omniscidb/blob/master/CMakeLists.txt#L100-L114 :+1:

**Comment by bobbrow** [comment]
That's great news. Glad to hear you have it working!
