### ISSUE TITLE
Cannot configure cmake-tools to stop updating the date in my headers

### ISSUE THREAD

**Issue by karlmortensen** [microsoft/vscode-cmake-tools#2313]
CMake-tools is updating the year from 2021 to 2022 in some files within the project and I can't make it stop.

When CMake-tools is enabled, about 20 files get the datestamp of 2021 updated to 2022  in the project. I'm new to VS Code, so this is all a bit new for me. When I try to open the cmake-tools settings, I get "No Settings Found". Not sure if that's a bug or if there are truly no settings for the extension. I don't want it to auto-update my code for any reason. 

How can I make this stop and still have the extension enabled? Thanks!

**Comment by karlmortensen** [comment]
Okay, so it looks like it's actually the cmake extension that's doing this, and having cmake-tools enabled just forced cmake to run. So nevermind. Not your issue.

**Comment by bobbrow** [comment]
Yes, you beat me to it. I was going to say that we just invoke cmake on your behalf, so if your CMakeLists.txt has some logic in it that touches the files and changes the timestamps, the fix would need to be made in your project instead.  If you have any other questions, please let us know.
