### ISSUE TITLE
Show source files tree

### ISSUE THREAD

**Issue by MaJerle** [microsoft/vscode-cmake-tools#2315]
### Brief Issue Summary

When CMakeLists.txt uses source files outside workspace (from let's say library repository somewhere on disk), it would be good to automatically show files in browser in VSCode.

Similar well-done job is integration of this plugin with Cpp-Tools where include paths and symbols are well provided directly from CMake.

### Debug Log

```
<!-- Paste the debug log contents HERE -->
```

**Comment by bobbrow** [comment]
Are you asking to show files in the File Explorer?  Unfortunately, we are unable to do that.  But if you open the CMake Project Outline, you should be able to see all files references by your targets.  Click on this icon in the sidebar: 
![image](https://user-images.githubusercontent.com/12818240/148569607-d138c9fd-adf4-41d4-aff4-9d2a57aea739.png)

**Comment by MaJerle** [comment]
How cool, that's exactly I have been looking for! Thank you for your fast help

Cheers
Tilen
