### ISSUE TITLE
Feature request: `USE_FOLDERS` and `FOLDER`

### ISSUE THREAD

**Issue by friendlyanon** [microsoft/vscode-cmake-tools#2321]
### Brief Issue Summary

I have not seen any other issue requesting this feature.

Please support the folder feature of CMake. Including `CTest` alone will create a lot of targets, which are automatically grouped in a folder when `USE_FOLDERS` is enabled. This feature is already supported by VS:

![image](https://user-images.githubusercontent.com/1736896/149241874-66adcdd6-45c7-4c21-bfae-8a0f223d2c38.png)

The value of the `FOLDER` property is accessible in the File API via the root level `folder` field. I'm not sure about server mode.

**Comment by vdilecce** [comment]
I remember there has been an issue regarding this for a while (https://github.com/microsoft/vscode-cmake-tools/issues/491) though I don't know when this will be planned.

**Comment by friendlyanon** [comment]
You are right. I tried searching for a similar issue, but somehow I didn't find that.
