### ISSUE TITLE
cmake.ctestArgs command expansion

### ISSUE THREAD

**Issue by khlebnikov** [microsoft/vscode-cmake-tools#2323]
I am trying to set up my environment to make extensive use of the build target name for convenience.  In particular, I have the `launch.json` configured to launch the current build target using 

```
"program": "some-stuff-here/${command:cmake.buildTargetName}"
```

This works perfectly.

However, when I try to set up the CTest runner to use the same trick to only run tests associated with the current build target, it does not work.  In particular when I try to use the following configuration in `settings.json` to try and set up the label:

```
    "cmake.ctestArgs": ["-L", "${command:cmake.buildTargetName}"],
```

I get the following output:

> [proc] Executing command: ctest -j7 -C Debug -T test --output-on-failure -L ${command:cmake.buildTargetName}

which is clearly not what I was aiming to get.

Am I doing something wrong or are command expansions not supported in this context and thus require some changes in the plugin?

Thanks!

**Comment by bobbrow** [comment]
Sorry, the expansion isn't supported in this context yet.  The change shouldn't be difficult, it's just a matter of routing the information to the location where it's used in `ctest.ts`

**Comment by khlebnikov** [comment]
I'm not familiar with VSCode extension development, but if you point me to where similar expansion is done (and where it's tested if you have unit tests for that), I can try fixing it and making a PR.
