### ISSUE TITLE
cmake tools' variants vs cmake's cmakepresets

### ISSUE THREAD

**Issue by vadi2** [microsoft/vscode-cmake-tools#2325]
What is the difference between this extensions' [variants](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/variants.md) versus cmake's own cmakepresets? The variants page does not seem to address this.

**Comment by bobbrow** [comment]
Variants is a concept that pre-dates CMake presets.  The biggest difference is that the extension uses variants to generate a cartesian product of the options for you to be able to select any of the combinations of settings for your configuration.

CMake presets currently requires you to author the combinations you care about, though Kitware is considering ways to make this better.

**Comment by vadi2** [comment]
Thanks, that helps!
