### ISSUE TITLE
Sidebar treeview behavior doesn't respect workbench option

### ISSUE THREAD

**Issue by OkazakiNagisa** [microsoft/vscode-cmake-tools#2328]
### Brief Issue Summary

Nodes in project outline expand or collapse with a single click, ignoring setting "workbench.tree.expandMode".

**Comment by bobbrow** [comment]
Thank you for reporting this.  Unfortunately, I don't see anything on the vscode APIs that give our extension any control of this behavior.  If you would like this feature, I think you will need to ask the VS Code team.  You can open a new issue here: https://github.com/microsoft/vscode/issues/new/choose
