### ISSUE TITLE
Gcc 11.2 Latest Vscode: only one cc1plus with parallel enabled

### ISSUE THREAD

**Issue by LeHibou2** [microsoft/vscode-cmake-tools#2331]
Linux - gcc 11.2 - 

Hi,
My builds are slow because not done in parallel.
I use Cmake from snap. Cmake version is 3.22.1.
Cmake-tool 1.9.2

Cmake file:
```
cmake_minimum_required(VERSION 3.5)

set(APP_NAME blah)

project(${APP_NAME} LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set( CMAKE_CXX_EXTENSIONS ON )
set(ENV{CMAKE_BUILD_PARALLEL_LEVEL} 4)

set(HEADER_FILES_colors path)
set(HEADER_FILES_common path)
set(HEADER_FILES_boost path)

file(GLOB HEADERS path)
file(GLOB HEADERS_HTML path)

set(CMAKE_BUILD_RPATH  path)

add_executable(${APP_NAME} main.cpp ${HEADERS} ${HEADERS_HTML})
set_target_properties(${APP_NAME} PROPERTIES LINKER_LANGUAGE CXX)
target_include_directories(${APP_NAME} PUBLIC ${HEADER_FILES_boost} ${HEADER_FILES_common} )
target_compile_options(${APP_NAME} PUBLIC -g -O0 -Wall -Wextra -pedantic )

target_link_options(${APP_NAME} PUBLIC -llib)
```

Here are the modified lines in settings.json:

```
    "cmake.generator": "Ninja",
    "cmake.debugConfig": {
      "name": "_(gdb) Launcher",
      "type": "cppdbg",
      "request": "launch",
      "program": "${command:cmake.launchTargetPath}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}/build",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "setupCommands": [
          {
              "description": "Test",
              "text": "python import sys;sys.path.insert(0, '/path/share/gcc-11.2.0/python');from libstdcxx.v6.printers import register_libstdcxx_printers;register_libstdcxx_printers(None)",
              "ignoreFailures": false
          },
          {
              "description": "Enable pretty-printing for gdb",
              "text": "-enable-pretty-printing",
              "ignoreFailures": true
          }
      ]
  },
    "typescript.disableAutomaticTypeAcquisition": true,

    "search.exclude": {
        "**/node_modules": true
      },
      "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/**": true,
        "env-*": true
      },
      "files.exclude": {
        "**/.git": true,
        "**/.DS_Store": true,
        "**/node_modules": true,
        "env*": true
      }
```

I use Ninja as a generator. The given executed command is:

Executing command: /snap/cmake/current/bin/cmake --build /path/to/app/build --config Debug --target blah -j 4 --

I don't know what I did wrong but the net result is a single core build with my system not used fully and me wasting a lot of time.

Any pointer?

Thanks :)

**Comment by jmigual** [comment]
Hi @LeHibou2 are you specifying the number of cores for a specific reason? The `ninja` generator already detects the number of cores in the system and parallelises the tasks without the need to define any specific parameter.

You could try removing `set(ENV{CMAKE_BUILD_PARALLEL_LEVEL} 4)` and `-j 4`.

**Comment by LeHibou2** [comment]
Hi,
Yes I tried that to check if forcing the parameter could change something.

After investigation, it may be because I have one common header with common definitions included in many files.. but I am not sure and cannot change the structure..

**Comment by jmigual** [comment]
That sounds very strange indeed. I guess you've also tried running the cmake build command directly from the command line? If so were your cores being used?

If you have a very large header file that's causing the bottleneck, you may want to check your disc usage with something like iotop to see whether your disk reading speed is bottlenecking the build. If that's not the case you may want to create another test project and start adding files from your original project to see at which point everything goes wrong.

Without seeing your project I'm afraid I cannot give you any more info 😕

**Comment by LeHibou2** [comment]
You are right, I will check that tomorrow morning and report here ;)-- 22:02, 20 January 2022, "Joan Marcè i Igual" ***@***.***>:
That sounds very strange indeed. I guess you've also tried running the cmake build command directly from the command line? If so were your cores being used?
If you have a very large header file that's causing the bottleneck, you may want to check your disc usage with something like iotop to see whether your disk reading speed is bottlenecking the build. If that's not the case you may want to create another test project and start adding files from your original project to see at which point everything goes wrong.
Without seeing your project I'm afraid I cannot give you any more info 😕

**Comment by bobbrow** [comment]
I agree with @jmigual.  If you see this behavior when you build with cmake directly on the command line (outside of VS Code), then the issue is likely with your project and not due to any settings that VS Code has set for you.  If you could let us know, that will help us determine what the next steps should be.

**Comment by LeHibou2** [comment]
So I tried and it appears the problem is outside of vscode. Even in the command line. So my project is rhe issue. I will close this issue and I apologize for the time wasted for you guys 😅

**Comment by bobbrow** [comment]
You don't need to apologize. We just wish we could help further.  I think @jmigual had some good ideas of ways to find the bottlenecks in your project.

**Comment by LeHibou2** [comment]
Thank you :) the project is header only with boost and templates.. I am out of luck here. Even tried to separate .h and .cpp but same issue..

**Comment by LeHibou2** [comment]
BTW, I literally ditched the former computer for a more recent one (yes, this kind of guy) and everything is back to normal.

Thanks!
