### ISSUE TITLE
No usable generator found

### ISSUE THREAD

**Issue by FuXiii** [microsoft/vscode-cmake-tools#2332]
###I was used llvm-mingw-20211002-msvcrt-x86_64,and follow this https://code.visualstudio.com/docs/cpp/CMake-linux to learn how to config cmake in VSCcode, all the bin I have add in system path (this cmake bin and llvm-mingw-20211002-msvcrt-x86_64 bin)

when I follow into the [CMake: Configure] step,VSCode return this error,.

I try to fix the cmake-tools-kits.json and setting.json ,but it didn't work.

the cmake-tools-kits.json part I use is (I don't change anything just native json text): 

  {
    "name": "Clang 13.0.0 x86_64-w64-windows-gnu",
    "compilers": {
      "C": "F:\\llvm-mingw-20211002-msvcrt-x86_64\\bin\\clang.exe",
      "CXX": "F:\\llvm-mingw-20211002-msvcrt-x86_64\\bin\\clang++.exe"
    }

and the setting.json is:

{
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Default Dark+",
    "[cpp]": {
        "editor.defaultFormatter": "ms-vscode.cpptools"
    }
}

What should I do?

**Comment by FuXiii** [comment]
I try to change the json like this:
the cmake-tools-kits,json:
  {
    "name": "Clang 13.0.0 x86_64-w64-windows-gnu",
    "compilers": {
      "C": "F:\\llvm-mingw-20211002-msvcrt-x86_64\\bin\\clang.exe",
      "CXX": "F:\\llvm-mingw-20211002-msvcrt-x86_64\\bin\\clang++.exe"
    },
    "preferredGenerator": {
      "name": "MinGW Makefiles",
      "platform": "x64"
    },
    "environmentVariables": {
      "PATH": "F:\\llvm-mingw-20211002-msvcrt-x86_64\\bin"
    }
  }


the setting.json:
{
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Default Dark+",
    "[cpp]": {
        "editor.defaultFormatter": "ms-vscode.cpptools"
    },
    "cmake.cmakePath": "F:\\CMake\\bin\\cmake.exe",
    "cmake.mingwSearchDirs": [
      "F:\\llvm-mingw-20211002-msvcrt-x86_64\\bin"
   ],
   "cmake.generator": "MinGW Makefiles"
}


but it still didn't work

**Comment by FuXiii** [comment]
While maybe I have find out the reason why, before I run cmake:quick start command ,In my project dir I have created a main.cpp
file,then after I run the quick start command the VSCode didn't auto create build dir .I have create a new empty dir and run quick cmake,this time I get the correct result


but whem I run cmake: configure the OUTPUT window output this:
[main] Configuring folder: testste 
[proc] Executing command: F:\CMake\bin\cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=F:\llvm-mingw-20211002-msvcrt-x86_64\bin\clang.exe -DCMAKE_CXX_COMPILER:FILEPATH=F:\llvm-mingw-20211002-msvcrt-x86_64\bin\clang++.exe -He:/VSCodeProject/testste -Be:/VSCodeProject/testste/build -G "MinGW Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: E:/VSCodeProject/testste/build
[ctest] There was an error running ctest to determine available test executables

It say "There was an error" ,What is the Error?

**Comment by FuXiii** [comment]
Today I change other computer and run Cmake: Quick Start command in a empty dir,it just create two files, one is CMakeLists.txt another is main.cpp ,the [build] dir no auto create and then the Error show up: [Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable.]

**Comment by FuXiii** [comment]
I think I fixed this problem, before I fixed ,the native json is:

- setting.json

```
{
   "workbench.colorTheme": "Default Dark+",
    "explorer.confirmDelete": false,
    "cmake.cmakePath": "E:\\CMake\\bin\\cmake.exe"
}
```

- cmake-tools-kit.json

```
...
{
    "name": "Clang 13.0.0 x86_64-w64-windows-gnu",
    "compilers": {
      "C": "E:\\llvm-mingw-20211002-msvcrt-x86_64\\bin\\clang.exe",
      "CXX": "E:\\llvm-mingw-20211002-msvcrt-x86_64\\bin\\clang++.exe"
    }
  }
...
```

after fixed, add some items in it:

- setting.json
```
{
    "workbench.colorTheme": "Default Dark+",
    "explorer.confirmDelete": false,
    "cmake.cmakePath": "E:\\CMake\\bin\\cmake.exe",

    "cmake.generator": "MinGW Makefiles"
}
```
- cmake-tools-kit.json

```
...
{
    "name": "Clang 13.0.0 x86_64-w64-windows-gnu",
    "compilers": {
      "C": "E:\\llvm-mingw-20211002-msvcrt-x86_64\\bin\\clang.exe",
      "CXX": "E:\\llvm-mingw-20211002-msvcrt-x86_64\\bin\\clang++.exe"
    },
    "preferredGenerator": {
      "name": "MinGW Makefiles",
      "platform": "x64"
    }
  }
...
```

**Comment by bobbrow** [comment]
Hi @FuXiii sorry we weren't able to get to this issue sooner to help.  What you shared looks correct for MinGW compilers.  Do you need any help with anything else, or shall we close this issue?

**Comment by FuXiii** [comment]
Fine，close it, thanks
