### ISSUE TITLE
How to configure 2 projects?

### ISSUE THREAD

**Issue by xFGhoul** [microsoft/vscode-cmake-tools#2351]
I'm pretty new to cmake and cmake tools and I want to figure out how I can configure 2 projects at the same time:

example:

`Root/Sub/CMakeLists.txt`
`Root/Sub2/CMakeLists.txt`

how do I configure both `Sub` and `Sub2`'s CMakeLists

**Comment by bobbrow** [comment]
You can open multiple folders in a workspace in VS Code.  Two possible ways to do this:
1. Open `Root\Sub` in VS Code, then open the `File` menu > `Add folder to workspace...` and select `Root\Sub2`
2. If you want `Root` open, then you can open `Root` and set the `cmake.sourceDirectory` setting to `"${workspaceFolder}/Sub"`, then open the `File` menu > `Add folder to workspace...` and select `Root\Sub2`

**Comment by xFGhoul** [comment]
Option 1 worked and now everything is working as intended, thank you so much!
