### ISSUE TITLE
Do we need reload windows after making modify for "cmake.cmakePath"?

### ISSUE THREAD

**Issue by alan-wr** [microsoft/vscode-cmake-tools#2361]
### Brief Issue Summary

Do we need reload windows after making modify for "cmake.cmakePath".

I update cmake via the setting "cmake.cmakePath" in your project .vscode/settings.json, but it does not works.

After I 'ctrl+R', it will works.

### CMake Tools Diagnostics

```
<!-- Paste the `CMake: Log Diagnostics` output HERE -->
```

### Debug Log

```
<!-- Paste the debug log contents HERE -->
```

**Comment by elahehrashedi** [comment]
We can not reproduce this problem. the changes in settings will be effective when you run `Cmake: Configure` without the need to reload the window. 
Would you please send us more info? for example, send the project info and log diagnosis info?
