### ISSUE TITLE
Bad CMake executable message appears erroneously

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#2368]
While investigating #2361, it appears that the "Bad CMake executable" message appears one more time after fixing the `cmake.cmakePath` setting and saving the settings.json file.  Despite the message, the save works and the new `cmake.cmakePath` setting is used in the next Configure operation.

**Comment by H-G-Hristov** [comment]
I just found out (I think) that Workspace setting always overwrites User even if it is empty. So basically I am unable to use CMake from a shared directory between macOS host/Linux on a VM.

**Comment by bobbrow** [comment]
Yes, Workspace and Folder settings always override User.  I'm not 100% clear on what you're trying to do though.  Are you setting `"cmake.cmakePath": ""` in the Workspace setting?  That will never work.

**Comment by H-G-Hristov** [comment]
Yes, I tried that. So we can't have a global setting for cmake.cmakePath or am I doing something wrong?

**Comment by bobbrow** [comment]
If you don't set anything for `cmake.cmakePath` in Workspace or Folder settings, then User settings will be used.  So if the User setting would work for both workspaces, then delete whatever you set for `cmake.cmakePath` in Workspace and Folder settings.

**Comment by H-G-Hristov** [comment]
> If you don't set anything for `cmake.cmakePath` in Workspace or Folder settings, then User settings will be used. So if the User setting would work for both workspaces, then delete whatever you set for `cmake.cmakePath` in Workspace and Folder settings.

If I clear:

![Screen Shot 2022-02-10 at 6 31 59 PM](https://user-images.githubusercontent.com/47526411/153452470-2f38beb5-05ac-49e6-9369-3b645b8e812a.png)

I get: Bad CMake executable "". Is it installed or settings contain the correct path (cmake.cmakePath)?

**Comment by H-G-Hristov** [comment]
This setting sets it to "cmake".

**Comment by bobbrow** [comment]
Yes, that's the default value, but that value is not used because you didn't explicitly set it.  You should see something like this that indicates it is set in the User settings.

![image](https://user-images.githubusercontent.com/12818240/153453354-da8b8386-5834-4626-83c8-11c18c5b7cc4.png)

**Comment by bobbrow** [comment]
I just cleared my Workspace setting, set something bogus in User so I could get the message (I'm on Windows currently), and it does pick up the User setting:

![image](https://user-images.githubusercontent.com/12818240/153453813-e5d1985c-8fe8-4e0e-be85-d879c63dd165.png)

**Comment by H-G-Hristov** [comment]
Just for the record. Another workaround: https://github.com/microsoft/vscode-cmake-tools/issues/838#issuecomment-1035123514

**Comment by Juanc179** [comment]
Hi, im running into the same problem. I checked my cmake path and it's like it should be. anyways, it doesn't detect it or it is missing something. 
![image](https://user-images.githubusercontent.com/85572320/219115869-e9c2c0f4-443e-4e8f-9e7b-e4397882fbe2.png)

**Comment by Sinetian** [comment]
bad. Hopes it will be fixed.

**Comment by andreeis** [comment]
Fix is merged in and should be included in the 1.15 release.
