### ISSUE TITLE
launch test is disabled

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#2378]
#2373 disabled the last test in [extension-tests/successful-build/test/debugger.test.ts](https://github.com/microsoft/vscode-cmake-tools/pull/2373/files#diff-bdfd2946bf5034c52bc3134f461733294833f49549a9a489317388c2e8bc2ec7)

We need to continue to investigate and then re-enable that test.

**Comment by lygstate** [comment]
This can be closed
