### ISSUE TITLE
Incorrect "cmake.additionalKits" setting breaks CMake extension: "command 'cmake.*' not found"

### ISSUE THREAD

**Issue by rustyx** [microsoft/vscode-cmake-tools#2382]
### Brief Issue Summary

After adding any folder<sup>1</sup> to `"cmake.additionalKits"` (e.g. `"cmake.additionalKits": [ "C:\\TEMP" ]`) and restarting VSCode:

`command 'cmake.build' not found`
`command 'cmake.selectConfigurePreset' not found`
`command 'cmake.selectActiveFolder' not found`
Or in other words:
`command 'cmake.*' not found`

### CMake Tools Diagnostics

`command 'cmake.logDiagnostics' not found` 🙂

### Debug Log

```
[main] Safe constructing new CMakeTools instance
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[variant] Loaded new set of variants
[main] CMakeTools instance initialization complete.
[kit] Reading kits file C:\Users\me\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 16 kits from C:\Users\me\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Not reading non-existent kits file: c:\Projects\proj1\ctest\.vscode\cmake-kits.json
[kit] Reading kits file C:\TEMP
```

Ext host log:

```
[exthost] [error] Activating extension ms-vscode.cmake-tools failed due to an error:
[exthost] [error] Error: EISDIR: illegal operation on a directory, read
```

---

<sup>1</sup> I know it's wrong to specify a folder in `cmake.additionalKits`, the point of this bug report is that it would be nice if this was reported accordingly instead of silently crashing.

**Comment by bobbrow** [comment]
Thanks for the bug report. I'm testing a fix for this.
