### ISSUE TITLE
How to specify build variant name in Cmake:Build Directory setting

### ISSUE THREAD

**Issue by jerryc05** [microsoft/vscode-cmake-tools#2383]
# Question
In vscode's `Cmake:Build Directory` setting, (how) can I use something like 
```
${workspaceFolder}/cmake-build-${buildVariant}
```
So that when I am build for Debug, the build directory will be `cmake-build-Debug`, and when for Release, that will be `cmake-build-Release`.

**Comment by bobbrow** [comment]
I believe the variable you are looking for is `${buildType}`.

https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#variable-substitution

**Comment by jerryc05** [comment]
> I believe the variable you are looking for is `${buildType}`.
> 
> https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#variable-substitution

Exactly! ty!
