### ISSUE TITLE
environmentSetupScript option does not execute the defined script

### ISSUE THREAD

**Issue by DerJFK** [microsoft/vscode-cmake-tools#2391]
I tried to use the `environmentSetupScript` option in the `.vscode/cmake-kits.json` to init my conda environment. However, if I define the script it seems not to run. In the following I describe my minimal example which does not work. Do I miss something? 

The output window just shows:
```
[proc] Executing command: cmake --build build --config Debug --target all -j 18 --
```

```shell
├── .vscode
│   ├── cmake-kits.json
├── main.cpp
├── CMakeLists.txt
└── script.sh
```

`.vscode/cmake-kits.json`
```json
[
    {
      "name": "Clang 12.0.0 MY",
      "compilers": {
        "C": "/bin/clang-12",
        "CXX": "/bin/clang++-12"
      },
      "environmentSetupScript" : " ${workspaceFolder}/script.sh"
    }
  ]
```

 `CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.23)
project(mytest CXX)
add_executable(main main.cpp)
```

 `script.sh`
```shell
#!/bin/bash

source activate mytest
echo test >> file.txt
```

**Comment by bobbrow** [comment]
Can you remove the space before `${workspaceFolder}` in `" ${workspaceFolder}/script.sh"` and try again?  We currently quote this value when running it and it looks like we didn't trim it first.

**Comment by DerJFK** [comment]
Thanks for your answer. Now it works!
