### ISSUE TITLE
How can I get my kits to choose which subdirectory has CMakeLists.txt?

### ISSUE THREAD

**Issue by cjdb** [microsoft/vscode-cmake-tools#2394]
### Brief Issue Summary

As someone who works in a monorepo, it'd be great to be able to have my kits determine which directory contains the root `CMakeLists.txt`, and which directory I'm going to be building in. For example, sometimes I'm building all of LLVM and need `-S ${workspaceFolder}/llvm -B build`, while other times I want to directly build a subproject (e.g. `-S ${workspaceFolder}/subproject -B build-subproject`).

Being able to set these in `cmake-kits.json` as opposed to my workspace settings would be fantastic. Is there a way to do this?

**Comment by bobbrow** [comment]
Unfortunately, the only way to specify multiple root CMakeLists.txt right now is to open multiple folders in the same workspace.  The feature we would do to support this is tracked by #1374.
