### ISSUE TITLE
Change the action of the "run" button

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cmake-tools#2406]
### Brief Issue Summary
CMake launch target button doesn't let you choose different options than executing the output file by default.

Sometimes it is more useful, especially when cross-compiling, to run custom scripts on post build when the compilation is finished instaed of running the compiled program.  
I'm cross-compiling for an 8bit MCU and every time I press the run button cmake tries to run `my_executable.elf` wich obviously cannot run on my host machine.  
I cannot find it documented anywhere, but I can't seem to be able to modify the action of the run button to execute a custom script.

![cmake](https://user-images.githubusercontent.com/33261286/156051929-2c467237-d25e-46eb-9fb7-e365345419d1.jpg)

**Comment by bobbrow** [comment]
The buttons in the status bar are not currently configurable.  The goal for them was to provide a quick debugging/running experience.  To accomplish more advanced tasks, VS Code provides the `tasks.json` and `launch.json` files. ([launch.json](https://code.visualstudio.com/docs/editor/debugging), [tasks.json](https://code.visualstudio.com/docs/editor/tasks))

**Comment by geots9** [comment]
@bobbrow Thank you for your feedback. That would be a great feature as many embedded software developers use cmake.

**Comment by starball5** [comment]
Would the motivating use-case here be solved with #554?

**Comment by gcampbell-msft** [comment]
@starball5 Yes I think you're right, I do think that this duplicates #1937. I'm going to close this one in favor of the other, since it's a duplicate. 

To help us prioritize this though, could you @starball5 @ghost "like" #1937? We often use the amount of likes as a way to help us prioritize issues and understand what people care about most, so this would help. Thanks!
