### ISSUE TITLE
select varient/Kit/build at once for multiple projects

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-cmake-tools#2409]
Is it possible to select varient at once for multiple projects? If not, it' s a feature request.

 My use case is I have a moduler project that I open tens of vscode windows and I need to switch the build varient Debug/Release frequently to test and benchmark different builds. Having a config stating several projects switch varient/switch Kit/ run build at once would help a lot.
 
I' m willing to implement this function if it' s possible and you give me some hints on which code to look at.

**Comment by bobbrow** [comment]
This is possible via the `CMake: Select Variant for All Projects` command:

![image](https://user-images.githubusercontent.com/12818240/156431251-33500ebc-1961-4805-8586-75a036e0ed76.png)

**Comment by xgdgsc** [comment]
Thanks. I don' t have that command when search. Under which folder structure  would that show?

**Comment by xgdgsc** [comment]
Thanks.
