### ISSUE TITLE
C/C++ Extentsion complains `The key 'externalConsole' is deprecated. Please use 'console' instead.`

### ISSUE THREAD

**Issue by isudfv** [microsoft/vscode-cmake-tools#2428]
when "externalConsole" is set to true, C/C++ Extentsion complains `The key 'externalConsole' is deprecated. Please use 'console' instead.`
```
"cmake.debugConfig": {
    "externalConsole": true
},
```
But `console` is not found in `"cmake.debugConfig"`

**Comment by hwhsu1231** [comment]
Agree. This IntelliSence should be updated.

**Comment by bobbrow** [comment]
Yes, the IntelliSense should be updated, but it should be ok for you to use `console` even without the IntelliSense.  CMake Tools passes the values directly to cpptools and doesn't look at them.
