### ISSUE TITLE
Can't stop configuration step.

### ISSUE THREAD

**Issue by stayprivate** [microsoft/vscode-cmake-tools#2436]
Hi,

Seems the configuration step of cmake-tools cannot be stopped. 

We are using conan and are experimenting with a lots of packages ,all build from sources.  Takes about 30 minutes to build these packages.

I selected a wrong variant, we have 6 of them, so cmake-tool ended up launching conan which decided that a new set of packages was need. That's all good. So I wanted to switch back to the proper variant, but when I did vscode told me a configuration was already running. I could not find a way to stop the configuration step.

When you start a build, a stop options shows up. But for config step I could not find anything equivalent. 

Only work around was to switch the variant and restart vscode.  Important to switch the variant before restarting it, because on restart it will resume the configuration step where it left of.

Or did I miss something ?

- Regards

**Comment by bobbrow** [comment]
Thank you for opening this issue. You are correct that configure is not currently cancellable via the UI. We may not get to this immediately, but we would accept a PR from the community if someone wants to help contribute a fix.

**Comment by Danielmelody** [comment]
Just noticed that closing vscode does not kill the configuration process as well, leaving no workaround here if using output window.

**Comment by Danielmelody** [comment]
My mistake, closing vscode can kill configuration.

**Comment by Danielmelody** [comment]
@bobbrow I 'd like to implement this feature, please tell me anything you think that is necessary to help me start.

**Comment by bobbrow** [comment]
If you trace the usage of this variable, you'll see an example of how the build implements its cancellation logic.  I would expect the configuration cancellation logic to work more or less the same way (keep a handle to the running process and add a command to cancel it).  You could probably use the existing `cmake.stop` command to stop either the configure process or the build process, whichever is currently running.  Consider also updating the status bar UI to show the 'x' icon in place of the configure and/or build icons which a configure/build is active.

https://github.com/microsoft/vscode-cmake-tools/blob/c7557c833ee042ba2d1a101143b32f632681b3ec/src/drivers/cmakeDriver.ts#L1606

**Comment by Danielmelody** [comment]
Rather than maintaining 2 separate status for building and configuring, I bundle them into one. The reason is obvious: one cannot do configuration or building at the same time.
