### ISSUE TITLE
Question: Using a task to select a kit

### ISSUE THREAD

**Issue by UnlimitedKaos** [microsoft/vscode-cmake-tools#2441]
Hello, Im kinda a noob with cmake, so I might not be trying to do this right.

basically I have a project that I want to compile 2 builds for, one using my computer's gcc and one using the arm-none-eabi gcc. To do this Ive set up a kit and toolchain for the arm build and configured settings.json so that each kit builds into their own folder (eg the arm build is in ./build/arm-none-eabi)

I would like to setup a build task to make both of these automatically, so I went into tasks.json and added this task:
```
{
    "label": "Select ARM Kit",
    "command": "${command:cmake.selectKit}",
    "args": [
        "arm-none-eabi"
    ],
    "problemMatcher": [],
},
```

the arg is the same as what you could type into the command 'Cmake: Select Kit' available in the command pallete. However, this arg is seemingly ignored as the same stringselect as the 'Cmake: Select Kit' command pops up.

Is there a better way to do this? 
Id like to avoid having to select the kit manually to avoid accidentally selecting the wrong one.

Additionally, I get an error box saying ` Cannot substitute command variable 'cmake.selectKit' because command did not return a result of type string. ` but this doesnt seem to prevent the task from selecting a kit.

**Comment by UnlimitedKaos** [comment]
Sorry for the late reply, I havnt had the chance to get back to this.

I cant seem to get `setKitByName` working. When I run the task I get 2 dialogue boxes that pop up for a second that say "Unsetting Kit", and the kit I specified isnt selected (The last one I manually selected seems to always remain selected, or If I use the task after opening the workspace, no kit is selected). I feel like I dont have the syntax correct, but Im not sure where to find that info.

This is my task:
```
{
    "label": "Select Build Kit",
    "command": "${command:cmake.setKitByName}",
    "args": [
        "ARMKit"
    ],
    "problemMatcher": [],
}
```

And this is my cmake-kits.json:
```
[
    {
        "name": "ARMKit",
        "toolchainFile": "${workspaceFolder}/arm-none-mirco.cmake"
    }
]
```

I can select the kit using the toolbar at the bottom and the `selectKit` command, and generating/building works fine.

**Comment by bobbrow** [comment]
I should have also linked the syntax documentation.  https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

Try something more like this:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Select Build Kit",
      "command": "echo ${input:selectKit}",
      "type": "shell",
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "selectKit",
      "type": "command",
      "command": "command:cmake.setKitByName",
      "args": "ARMKit"
    }
  ]
}
```
VS Code might still yell at you because I don't think the command returns a value.  That's why I put it in an "echo" command.  I don't think it would be too hard for us to just return the name of the selected kit.  Let me know if you're able to get this to work.

**Comment by UnlimitedKaos** [comment]
Ah yes, lol Ive seen that page a few times but didnt know the bit I was looking for.

Thank you, I was able to get this to work. 

FWIW (and for when I inevitably forget how to do this in a few months) this is how I currently have the task setup, and this changes kits without any error/warning messages:  (the `echo` doesnt seem to be necessary)

```
"tasks": [
        {
            "label": "Select Build Kit",
            "type": "shell",
            "command": "${input:select_n0110}",
            "problemMatcher": [],
        }
    ],
"inputs": [
    {
        "id": "selectArm",
        "type": "command",
        "command": "cmake.setKitByName",
        "args": "ARMKit",
    },
]
```

Its a bit unintuitive to me, but thats more a VSCode problem and not a cmake-tools one.

Thanks again.
