### ISSUE TITLE
Custom command for compile_commands.json / after configuration is done

### ISSUE THREAD

**Issue by Maetveis** [microsoft/vscode-cmake-tools#2448]
It would be nice to have an option to execute a user defined command instead of copying the `compile_commands.json`.

My usecase is that for header files [compdb](https://github.com/Sarcasm/compdb) makes intellisense work for clangd, but currently I have to run it manually after I change the cmake configuration. 

With the suggested option I could automate this. A general hook to run a task after configuration is finished would also work for this usecase.

I can attempt to implement this, if someone can point me in the right direction.

**Comment by bobbrow** [comment]
Thanks for the feature idea.  Before we move forward with it though, I think we should consider the other possible events that would benefit from a hook such as this.  Do you manually run the `CMake: Configure` command after changing the configuration?  If that aligns with your workflow, we may already be planning a feature that would assist you and you could chain your follow up task to that. #2452

**Comment by Maetveis** [comment]
> Do you manually run the `CMake: Configure` command after changing the configuration?

Yes, most of the time. It would be nice if the command would be run if configuration changed because cmake has rerun as part of the build process tough. Does #2452 also support that?

**Comment by Maetveis** [comment]
> Would getting the API from https://github.com/microsoft/vscode-cmake-tools/issues/494 address this issue?

Yes, I'll close this.
