### ISSUE TITLE
Build preset not working

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#2465]
Hi, I have a CMakePresets.json file configured to build an embedded project using the ARM armclang cross-compiler. I am trying to use the CMakePresets.json with VS Code on Windows. The configure preset works fine when activated from VS Code, but the build preset does nothing.

Here's the CMakePresets.json file:

```{
  "version": 2,

  "configurePresets": [
    {
      "name": "windows-base",
      "description": "Base configuration to target Windows with armclang, using Ninja generator.",
      "hidden": true,
      "generator": "Unix Makefiles",
      "binaryDir": "${sourceDir}/builds/${presetName}",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Debug",
        "CMAKE_TOOLCHAIN_FILE": "armclang_toolchain.cmake"
      },
      "environment": {
       <snip>
      }
    },
    {
      "name": "windows-elysion",
      "displayName": "Windows Elysion",
      "description": "Build Elysion using armclang",
      "hidden": false,
      "inherits": "windows-base",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release"
      }
    }
  ],

  "buildPresets": [
    {
      "name": "windows-core-build",
      "description": "Inherits environment from base Windows configurePreset",
      "configurePreset": "windows-base",
      "hidden": true,
      "inheritConfigureEnvironment": true
    },
    {
      "name": "windows-elysion-build",
      "displayName": "quiet build",
      "description": "Run Ninja in non-verbose mode",
      "configurePreset": "windows-elysion",
      "inherits": "windows-core-build",
      "nativeToolOptions": [ "-v" ]
    }
  ]
}
```

When I invoke build preset **windows-elysion-build** this command is invoked:

`"C:\Program Files\CMake\bin\cmake.EXE" --build c:/<snip>/builds/windows-elysion -- -v`

Executing that same command from the command line still does nothing, but executing:

`"C:\Program Files\CMake\bin\cmake.EXE" --build c:/<snip>/builds/windows-elysion -v`

(without the double-dash) successfully invokes a build.

So my question is: what in my CMakePresets.json is causing the '--' or is something else going on?

**Comment by bobbrow** [comment]
[The documentation](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#build-preset) for `nativeToolOptions` in buildPresets states:

`nativeToolOptions`

> An optional array of strings. Equivalent to passing options after -- on the command line. The array values support macro expansion.

If you would like to pass a verbosity option to cmake, I believe the property you want to add to your build preset is: `"verbose": true`

**Comment by DavidA2014** [comment]
@bobbrow Thanks very much for your help - that fixed my problem. My project now builds nicely.

CMake Presets, with VS Code, is great. I'm glad I don't have to worry about the old way of working with kits and variants.
