### ISSUE TITLE
Documentation: json.config   environment path set to "$PATH...."

### ISSUE THREAD

**Issue by rerdavies** [microsoft/vscode-cmake-tools#2466]
### Brief Issue Summary

A documentation error on the page https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html

In the sample launch.json file, the line which reads

              "value": "$PATH:${command:cmake.launchTargetDirectory}"

should read 

              "value": "${env:PATH}:${command:cmake.launchTargetDirectory}"

VSCode does not expand $PATH on launch; the environment in the target executable contains the literal text "$PATH", unexpanded; but ${env:PATH} does the job nicely.

Tested with

Visual Studio Code 1.65.0 
Raspberry Pi OS (64-bit)
Linux raspberrypi 5.10.103-v8+ # 1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux

### CMake Tools Diagnostics

n/a

### Debug Log

n/a

**Comment by bobbrow** [comment]
Thank you for reporting this.  Unfortunately, we do not own that website, but we did update our own documentation for this a while back.  https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md
