### ISSUE TITLE
[cpptools] Unknown C++ standard control flag: -std=c++23

### ISSUE THREAD

**Issue by sweemer** [microsoft/vscode-cmake-tools#2475]
### Brief Issue Summary

When compiling a CMake project with `CMAKE_CXX_STANDARD=23` I see `[cpptools] Unknown C++ standard control flag: -std=c++23` in the CMake/Build output.

### CMake Tools Diagnostics

{
  "os": "linux",
  "vscodeVersion": "1.66.0",
  "cmtVersion": "1.10.5",
  "configurations": [
    {
      "folder": "/home/sweemer/QuantLib",
      "cmakeVersion": "3.22.3",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": true,
      "compilers": {
        "CXX": "g++-11"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 51,
    "executablesCount": 21,
    "librariesCount": 2,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}

**Comment by sweemer** [comment]
Thanks, this isn't blocking anything major for me at the moment.

But I'm curious - as I asked on the merge request, how does the cpptools or cmake extension know which version of Visual Studio is installed on the user's machine? As far as I understand, the value of `/std:c++latest` is different depending on which version is installed, so is it desirable to hardcode the mapping in `src/cpptools.ts`? Is there a way to dynamically resolve the standard number from `/std:c++latest` based on the version of Visual Studio installed?

**Comment by bobbrow** [comment]
From CMake Tools' perspective, we just tell cpptools what CMake told us.  If a specific standard is requested, we send it, but otherwise we don't have to send it.  cpptools owns the mappings, so we shouldn't do anything in `cpptools.ts` for this.  Currently cpptools maps `c++latest` to `c++20`, but will be updated to use `c++23` when they pick up the changes in the API.  There is currently no mapping based on the version of the compiler sent.  If that's something you'd like to see, I recommend opening a bug report for cpptools.

**Comment by Zingam** [comment]
I plan to switch to C++ 23 soon. Is this just an annoyance or a blocker?

**Comment by bobbrow** [comment]
I believe you will need 1.10.0 of cpptools (pre-release) which came out late last week.  I think we already addressed the warnings in the CMake Tools pre-release (community contribution: #2476) but it requires the matching changes in cpptools.

**Comment by bobbrow** [comment]
It looks like our bookkeeping didn't mark this issue as fixed yet.
