### ISSUE TITLE
Vendor map appears to be hiding Configure Presets

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#2480]
I'm developing an ARM application, built using the armclang compiler on Windows. I'm using CMakePresets.json to specify Configure Presets.  My Configure Presets hierarchy was:

``` "configurePresets": [
    {
      "name": "windows-base",
      "description": "Base configuration to target Windows with armclang",
      "hidden": true,
      "generator": "Unix Makefiles",
      "binaryDir": "${sourceDir}/builds/${presetName}",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Debug",
        "CMAKE_TOOLCHAIN_FILE": "armclang_toolchain.cmake"
      },
      <snip>
    },
    {
      "name": "windows-myproj-release",
      "displayName": "Windows MyProj release",
      "description": "Build MyProj using armclang (Release)",
      "hidden": false,
      "inherits": "windows-base",
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Release"
      }
    }
  ],
```

but I changed the names 'windows-xxx' to 'arm-xxx' because the target is not actually Windows but Arm.

However, that causes VS Code to no longer offer the Configure Presets.  I guess this has to do with hostOS and the vendor map?

Is it inadvisable to use the rename to 'arm-xxx' or can I fix it by specifying hostOS?

The documentation:

[https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets.md#cmake-select-configure-preset](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets.md#cmake-select-configure-preset)

has a broken link:

[https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets-json-reference.md#visual-studio-settings-vendor-map](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets-json-reference.md#visual-studio-settings-vendor-map)

**Comment by bobbrow** [comment]
What exactly are you renaming?  Just the `name` property?  That should not have any effect on which presets appear.  If it's something to do with the vendor map, can you share what you set those values to be?

Also, I just fixed the link in the docs.  Thanks for reporting that.

**Comment by DavidA2014** [comment]
@bobbrow Thanks for replying and for fixing the link.

Yes, I am renaming just the name property. I have done nothing to the vendor map. TBH I don't understand the vendor map or know where it lives.  Could you explain that briefly please and perhaps comment on what else may be causing the presets not to appear in VS Code?

Thanks again for your help.

**Comment by DavidA2014** [comment]
@bobbrow Sorry, actually I do understand the vendor maps but, as I'm not using them (and not using hostOS), I don't understand why the presets aren't showing.

**Comment by DavidA2014** [comment]
Sorry this is a non-problem, just my misunderstanding. Thanks for your help.
