### ISSUE TITLE
Support version 4 of presets

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cmake-tools#2492]
### Brief Issue Summary

We need to support new features added in version 4 of presets.
* `include` elements
* `${fileDir}` macro
* `resolvePackageReferences`

**Comment by chausner** [comment]
@elahehrashedi I can try to contribute this. Feel free to assign me to this issue.

**Comment by mpusz** [comment]
Recent versions of [Conan now generate `CMakeUserPresets.json`](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake_layout.html#multi-setting-option-cmake-layout) with schema version 4 (they include other files in it). It would be great to be able to open those files with VSCode.

**Comment by chausner** [comment]
> Recent versions of [Conan now generate `CMakeUserPresets.json`](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmake_layout.html#multi-setting-option-cmake-layout) with schema version 4 (they include other files in it). It would be great to be able to open those files with VSCode.

Yes, that's exactly why I contributed an implementation in #2544, still pending in review though. :) It works well for me with the files generated by Conan.

**Comment by bobbrow** [comment]
We plan to review the v4 PR next week.  We were trying to finish up the last planned PR for 1.11, but had to switch over to cpptools to fix a few things for that release which set us back a little on CMake Tools.  @chausner's PR will be reviewed shortly after and will be available in 1.12 pre-release.  We're sorry for the delay on it.

**Comment by bobbrow** [comment]
This feature is available in version 1.12.3 (pre-release). Thank you @chausner for submitting the PR!
