### ISSUE TITLE
Cannot debug a executable linked by ld.lld with lldb debugger when using a pure LLVM MinGW toolchain.

### ISSUE THREAD

**Issue by securasu** [microsoft/vscode-cmake-tools#2509]
### Brief Issue Summary

Cannot debug a executable linked by ld.lld with lldb debugger when using a pure LLVM MinGW toolchain on Windows.
I found that all executable linked by ld.lld must be debug with MSVC debugger.
There is the related code. [https://github.com/microsoft/vscode-cmake-tools/blob/v1.10.5/src/debugger.ts#L162](https://github.com/microsoft/vscode-cmake-tools/blob/v1.10.5/src/debugger.ts#L162)

**Comment by bobbrow** [comment]
I don't really have all the context behind that decision so I'd be wary about breaking a bunch of people by changing it. That said, I added support to skip over that logic in the linked pull request.  When this goes in, you can use the following setting to skip this check:
```
cmake.debugConfig: {
  "MIMode": "lldb"
}
```
