### ISSUE TITLE
add option to reveal output panel only when an error occurs

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-cmake-tools#2521]
### Brief Issue Summary

- when editing `CMakeLists.txt`, the extension automatically reconfigures cmake
- it also forcibly switches panel into output 
- it would be great to have an option to disable such behavior

### Additional Information

![image](https://user-images.githubusercontent.com/54838975/165031213-59846622-bb8b-4aa7-80e1-6fb2b7152d38.png)
before editing `CMakeLists.txt`, right panel on `terminal`
![image](https://user-images.githubusercontent.com/54838975/165031232-31310cb9-f53b-404e-afcb-6188ddef07cf.png)
after editing `CMakeLists.txt`, right panel on `output`

**Comment by bobbrow** [comment]
Related: #1675

**Comment by scarf005** [comment]
> "cmake.revealLog": "never"

Thank you, this option worked. However this option lacks a description, would be great to have one.
![image](https://user-images.githubusercontent.com/54838975/165399195-c813e06f-6a06-40b4-9fee-66d630ba703d.png)

**Comment by ngagesmu** [comment]
It would be nice if the log was only revealed if exit code != 0

**Comment by tuanpt-0634** [comment]
>It would be nice if the log was only revealed if exit code != 0
This is great if we have option "reveal on error". Or at least we can show build status (success/failed) on status bar or notification

**Comment by wngtk** [comment]
How about use `"cmake.configureOnEdit": false`.

**Comment by mhrstmnn** [comment]
> How about use `"cmake.configureOnEdit": false`.

Does not solve the problem, because CMake should still be configured. We just don't want to have to watch the configuration every time.

**Comment by mhrstmnn** [comment]
> How about use `"cmake.configureOnEdit": false`.

Does not solve the problem, because CMake should still be configured. We just don't want to have to watch the configuration every time (unless an error occurs).

**Comment by sr-tream** [comment]
Implemented this feature here: [cmake-build](https://marketplace.visualstudio.com/items?itemName=SR-team.cmake-tools-build-wrapper). This extension is a wrapper for CMake Tools, what can open output panel on errors.

NOTE: Required to call CMake commands via this extension!
