### ISSUE TITLE
Update test results in CMake Test Explorer

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-cmake-tools#2522]
Issue Type: <b>Feature Request</b>

I use the CMake Tools status bar to run all tests with one click, and I use the CMake Test Explorer extension to run and see results from individual tests. It woud be great if running the tests via one of the methods would update the test results in the other as well.

I don't know exactly how this works, but I think the CMake Test Explorer uses some kind of standard VSCode api to manage and display tests, so I am guessing this extension would need to use the same api for updating the test results.

Extension version: 1.10.5
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-109-generic

**Comment by bobbrow** [comment]
We have an issue tracking doing a test explorer #1682, but it hasn't made it on the roadmap yet.  Does the Test Explorer extension not have a way to run tests in a single click or command?  If it does have a way to run tests easily, I would recommend hiding our status bar button using the following setting:

```
"cmake.statusbar.advanced": {
  "ctest": {
    "visibility": "hidden"
  }
}
```

**Comment by BMBurstein** [comment]
@bobbrow That doesn't rebuild or refresh the list of tests automatically. Using the button in the status bar also rebuilds and always runs all tests, including any new ones.

**Comment by BMBurstein** [comment]
Thank you. I understand that this is a low priority, but maybe if it is on the list someone will look into it. Maybe the two extensions can even be merged in some way if it makes sense.
I am sorry that I am asking for this and not offering to do it myself, but I am a C++ programmer and know nothing of JS or Typescript or whatever else is needed for this.
