### ISSUE TITLE
changes to included files not triggering reconfigure

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-cmake-tools#2526]
### Brief Issue Summary

whenever I make a change to a `CMakeLists.txt` file, it triggers a reconfigure. But if I have e.g. `include(file.cmake)` in the `CMakeLists.txt` file and I change `file.cmake`, it doesn't trigger an automatic reconfigure. Is it possible to do this?

**Comment by elahehrashedi** [comment]
This feature is not currently available, but we can add it in the future. We may not reach to implement this feature soon, but we appreciate any help from the community.

**Comment by bobbrow** [comment]
This was fixed with PR #2548 and is available starting in version 1.12.8 (pre-release).
