### ISSUE TITLE
Get path to Build dir / compile_commands.json for configuring other extensions

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-cmake-tools#2528]
### Brief Issue Summary

I got another vscode extension (sonarlint) that needs the path to compile_commands.json as a [configuration setting](https://github.com/SonarSource/sonarlint-vscode/wiki/C-and-CPP-Analysis).

Therefor, I need the path to the build directory. It changes when I change presets, so I cannot hard code it.

In launch config there is `${command:cmake.buildDirectory}`. But what should I use in configuration files?

### Additional Information

Relevant documentation:
https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md

**Comment by bobbrow** [comment]
Does it work to use `${command:cmake.buildDirectory}/compile_commands.json`?  That's where I would expect it to go, but you may need to ask for a feature from the other extension to be able to be able to execute commands as part of resolving settings.

**Comment by KUGA2** [comment]
Hi @bobbrow,

I did not test this. I thought "command" things can only be used in launch/task.json. Now I tested it and it does not work:

```
[Error - 11:16:54.248] Analysis failed
java.nio.file.InvalidPathException: Illegal char <:> at index 9: ${command:cmake.buildDirectory}/compile_commands.json
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
...
```

This means it is not interpreted.
Can you confirm that this can be used in config files? Then I will open an issue there.

**Comment by KUGA2** [comment]
Thanks. I will close this issue. I reported this at [sonarlint ](https://community.sonarsource.com/t/how-to-set-a-relative-path-in-vscode/61518/5)and they will hopefully create a Ticket.
