### ISSUE TITLE
Includes for CMake presets not supported

### ISSUE THREAD

**Issue by arludwig** [microsoft/vscode-cmake-tools#2531]
### Brief Issue Summary

Since version 4 of the CMake presets JSON schema, presets support including other JSON files. This allows for more modular approaches to defining presets and for less daunting CMakePresets.json files. (At least for projects with many different important configurations and variations thereof.)

Although cmake-tools states to support version 2 and above of the JSON schema
> The CMake Tools extension supports version 2 or later for the CMakePresets.json and CMakeUserPresets.json files.

the extension seems unable to process CMakePresets.json files using this feature.

```
{
    "version": 4,
    "include": "other.json",
    "configurePresets": [
        {
            "name": "MyPreset"
        }
    ]
}
```
![grafik](https://user-images.githubusercontent.com/60502779/166672615-e2e8a6b1-54c2-4eef-80fb-b2d70ec2ff51.png)
![grafik](https://user-images.githubusercontent.com/60502779/166673798-0f1b3aea-5eb7-4f1d-9d40-6344e24ad573.png)

I am using version 1.10.5 of cmake-tools with vscode 1.66.2 and CMake 3.23.1.

Is this a bug, or are there plans to support this feature in the future?

**Comment by bobbrow** [comment]
We have plans to support this but have not done the work yet.  It's being tracked by #2492.
