### ISSUE TITLE
Could we add an option to disable "CMakeLists.txt was not found in the root of the folder..."?

### ISSUE THREAD

**Issue by ilg-ul** [microsoft/vscode-cmake-tools#2532]
### Brief Issue Summary

Would it be possible to add a configuration option (per user/workspace/project) to disable these annoying messages I get whenever I open a project that might have a `CMakeLists.txt` somewhere down in the folder hierarchy?

### Additional Information

Here is an example, when opening a workspace with some VS Code sources, including your extension:

![Screenshot 2022-05-05 at 10 23 30](https://user-images.githubusercontent.com/362732/166878750-159a8915-38e2-4206-aa70-b3b375d6ade6.png)

The reason why the extension is activated is the presence of many `CMakeLists.txt` in the `test` folder:

```console
ilg@wksi vscode-cmake-tools.git % find . -name CMakeLists.txt
./test/smoke/goodProject/CMakeLists.txt
./test/smoke/badProject/CMakeLists.txt
./test/smoke/noCtest/CMakeLists.txt
./test/unit-tests/driver/workspace/source_outside_of_workspace/workspace/CMakeLists.txt
./test/unit-tests/driver/workspace/source_outside_of_workspace/workspace/subdir/CMakeLists.txt
./test/unit-tests/driver/workspace/bad_command/CMakeLists.txt
./test/unit-tests/driver/workspace/test_project/shared_lib_dummy/CMakeLists.txt
./test/unit-tests/driver/workspace/test_project/CMakeLists.txt
./test/unit-tests/driver/workspace/test_project/static_lib_dummy/CMakeLists.txt
./test/extension-tests/successful-build/project-folder/CMakeLists.txt
./test/extension-tests/single-root-UI/project-folder/CMakeLists.txt
./test/extension-tests/multi-root-UI/project-folder2/CMakeLists.txt
./test/extension-tests/multi-root-UI/project-folder/CMakeLists.txt
./test/fakeOutputGenerator/CMakeLists.txt
ilg@wksi vscode-cmake-tools.git % 
```
 
Please note that I do not want to affect in any way the functionality for those who need it, I just want to be able to explicitly disable this with a configuration option for those who find it annoying.

**Comment by bobbrow** [comment]
Thanks for the suggestion. Seems easy enough to do.  We could check on line 573 of cmakeTools.ts for the new setting and skip this suggestion workflow.  Our extension would still activate, but it wouldn't do much after that.

**Comment by ilg-ul** [comment]
I'm not familiar with the workflow, should I submit a PR or are you working on it?

**Comment by bobbrow** [comment]
You are welcome to work on it.  In general, if an issue is unassigned, we will gladly accept a PR from the community.  I didn't put the "help wanted" tag on it, because I thought we would have time to do it in the next release, but if you want to work on it now, it can make it in sooner.  Let me know if you're signing up and I'll assign you so that no one else duplicates your work.

I think we should update the [contributing doc](https://github.com/microsoft/vscode-cmake-tools/blob/main/CONTRIBUTING.md) to talk about PR logistics, but basically, you fork the repo, make the changes and then submit a PR back to us so we can evaluate it and test it.

**Comment by ilg-ul** [comment]
I submitted a first proposal as #2537.

I tested it on my machine, and it seemed functional, but I confess that I'm not fully aware of all details, and there might be other changes required.

**Comment by ilg-ul** [comment]
I guess this can be closed now.

When do you plan to release 1.11?

**Comment by bobbrow** [comment]
We do a pre-release when the main branch changes, so you can pick up this change now by switching to the pre-release version of CMake Tools (use the Extensions panel and select CMake Tools to find the button to switch to pre-release).  It is in version 1.11.18.
