### ISSUE TITLE
Passing environment variable to "cmake" tasks

### ISSUE THREAD

**Issue by TheophileBlard** [microsoft/vscode-cmake-tools#2553]
### Brief Issue Summary

Is it possible to pass environment variable to cmake tasks ?

I'm currently using the pre-release version of the extension, and want to use cmake tasks to install the binaries to predefined directories using [DESTDIR](https://cmake.org/cmake/help/latest/envvar/DESTDIR.html). For example, "shell" tasks provide the "env" keyword in "options", but for "cmake" tasks, only the "cwd" is available.

Thanks!

### Additional Information

CMakeTools version : `1.11.19`
VSCode verson: `1.67.0`
OS: Ubuntu 21.04 TLS

**Comment by elahehrashedi** [comment]
You can define `configurePresets` in `CMakePresets.json`, and set the `CMAKE_INSTALL_PREFIX` there. 
Here is an example:
```
{
    "version": 2,
    "configurePresets": [
        {
            "name": "dev17-ninja-143",
            "displayName": "Ninja - v143,x64",
            "generator": "Ninja",
            "architecture": {
                "strategy": "external",
                "value": "x64"
            },
            "toolset": {
                "strategy": "external",
                "value": "host=x64,version=14.30"
            },
            "binaryDir": "${sourceDir}/out/build/${presetName}",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Debug",
                "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}"
            },
            "inherits": "base",
            "environment": {
                "PATH":  "$penv{PATH};D:\\ninja"
              }
        }
    ],
```
Will this approach solve your issue?
We can also look into adding more customizable features to cmake tasks in future.

**Comment by elahehrashedi** [comment]
One option that can be added to the `configure` or `build` task can be the name of the preset (instead of always picking the default).
for example:
```json
        {
            "type": "cmake",
            "label": "CMake: build",
            "command": "build",
            "targets": [
                "all"
            ],
            **"preset": "presetName",**
            "group": "build",
            "problemMatcher": [],
            "detail": "CMake template build task"
        }
```

**Comment by TheophileBlard** [comment]
Hi!

The `DESTDIR` variable is not interpreted at configure time but at install time, and it's not a CMake variable, but an environment variable that CMake uses to relocate the installation.
A typical use of this variable is: 
```sh
DESTDIR=/package/stage cmake --install .
```

With the `environment` keyword of presets it seems that I can set `DESTDIR` to a custom directory. However, when I use the `preset` keyword in my `tasks.json` I get the following error: `Property preset is not allowed.`. Is this an unreleased feature ? I'm using v1.11.19 of CMake Tools.

Do you plan to add a way to set environment variables directly in CMake tasks ?

**Comment by TheophileBlard** [comment]
Thank you !

**Comment by elahehrashedi** [comment]
There is an upcoming fix for this issue in PR https://github.com/microsoft/vscode-cmake-tools/pull/2636
