### ISSUE TITLE
condition in CMakeUserPresets.json

### ISSUE THREAD

**Issue by dvirtz** [microsoft/vscode-cmake-tools#2564]
### Brief Issue Summary

a condition on `${hostSystemName}` in `CMakeUserPresets.json` is not evaluated correctly. I have the following `CMakeUserPresets.json`:
```json
{
  "version": 3,
  "configurePresets": [
    {
      "name": "linux",
      "condition": {
        "type": "equals",
        "lhs": "${hostSystemName}",
        "rhs": "Linux"
      }
    },
    {
      "name": "darwin",
      "condition": {
        "type": "equals",
        "lhs": "${hostSystemName}",
        "rhs": "Darwin"
      }
    }
  ]
}
```
The extension reports
```
[presetController] Successfully validated presets in /Users/dyitzchaki/github/bugs/CMakePresets.json
```
but no configuration is available to choose, neither on linux nor on MacOs.
If I rename the file to `CMakePresets.json` the conditions are evaluated correctly and only the relevant configuration is displayed.

This may be related to https://github.com/microsoft/vscode-cmake-tools/issues/2362

### CMake Tools Diagnostics

```shell
{
  "os": "darwin",
  "vscodeVersion": "1.67.2",
  "cmtVersion": "1.11.19",
  "configurations": [
    {
      "folder": "/Users/dyitzchaki/github/bugs",
      "cmakeVersion": "3.22.1",
      "configured": false,
      "generator": "",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Debug Log

```shell
[presetController] Start selection of configure presets. Found 2 presets.
[presetController] Opening configure preset selection QuickPick
[presetController] User cancelled configure preset selection
[extension] [8795] cmake.configure finished (returned -1)
```

### Additional Information

A reproducing project can be found at https://github.com/dvirtz/bugs/tree/cmake-hostSystemName.

**Comment by elahehrashedi** [comment]
Thank you for reporting this bug. We thought it has been fixed in https://github.com/microsoft/vscode-cmake-tools/issues/2362. We will have to investigate this more.

**Comment by vhorvath-gs** [comment]
I came across this issue as well. I need this, so I might look into it this week.

**Comment by dvirtz** [comment]
Thanks @gcampbell-msft. I can confirm it's working provided I'm reloading the window after changing the presets. 
Maybe that reload was what I missed when I opened the issue.
