### ISSUE TITLE
Don't reconfigure when changing build types using multi-config generators

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vscode-cmake-tools#2577]
### Brief Issue Summary

When changing build types (Debug, Release, etc.) CMake Tools reconfigures the project, however when using multi-config generators, this may be omitted. Currently when changing configs, we can't issue a build right after, because "Another CMake operation/configuration is in progress" (or something similar) message appears. Depending on the project, a `nop` reconfiguration and subsequent generation can take 1-5 seconds.

Please remove the superfluous reconfigurations blocking builds when using multi-config generators.

_(I'm aware how this is still required to light up IntelliSense changes for extensions relying on `compile_commands.json`, but it should not block builds.)_

**Comment by bobbrow** [comment]
Thanks for reporting this.  Yes, we agree that there doesn't need to be a reconfiguration for multi-config generators.

**Comment by gcampbell-msft** [comment]
This was fixed in #3763, closing.
