### ISSUE TITLE
Add "description" properties to the cmake.revealLog setting and enums

### ISSUE THREAD

**Issue by MURPHYENGINEERING** [microsoft/vscode-cmake-tools#2578]
### Brief Issue Summary

Existing behavior: the panel switches to the output tab on build
Desired behavior: the panel is only optionally hijacked

`docs/build.md` reads

> When the build starts, the CMake Tools output panel opens to display build tool output. 

I'm trying to monitor console output during build; the extension stealing focus makes my workflow impossible <s>possible only by popping the terminal out of the window</s>.

Edit: cmake-tools can no longer run without debugging after popping the terminal out, so yes this is impossible.

Since this is a low priority suggestion, I'd appreciate just knowing where the functionality is implemented so I can take it out for myself.

**Comment by bobbrow** [comment]
We have a setting available that you can use to control the behavior: `cmake.revealLog`.  It has 3 values: "always", "never", and "focus".  "always" should ensure that the log appears, but does not focus it.  "never" will never try to make the log appear or focus it.  "focus" should ensure that the log appears and takes the cursor focus.  I just tested it and it appears to be working the way I expect.  Could you share what the value of this setting is for you?

You also mention "popping the terminal out", but the regular output panel isn't involved here.  Can you help us understand if you are talking about something else instead?

**Comment by MURPHYENGINEERING** [comment]
Hi @bobbrow, that does solve the issue, thank you! I wonder if it would be worth putting the word _output_ in the option label.

Re: "popping out," I just mean moving the terminal tab to a new window. I don't think we should expect that to work.

**Comment by bobbrow** [comment]
It looks like this setting does not have associated documentation.  We should fix that.  Renaming the setting to include the word "output" would break users who have already made changes to it, but if we include "output" in the documentation, it should turn up in the search.
