### ISSUE TITLE
activeBuildPresetName command is not found

### ISSUE THREAD

**Issue by JuriGagarin** [microsoft/vscode-cmake-tools#2579]
### Brief Issue Summary

I try to add a shell build task where I invoke cmake using the currently selected build preset but I get the following error in VSCode:

`command 'cmake.activeBuildPresetName' not found`

I'm using this task definition.

```json
{
    "label": "CMake demo task",
    "type": "shell",
    "command": "cmake",
    "args": [
        "--build",
        "--preset=${command:cmake.activeBuildPresetName}",
        "--target",
        "demo_target"
    ],
    "problemMatcher": []
}
```

Looking at the documentation of [command substitutions](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#command-substitution) I would expect that the `cmake.activeBuildPresetName` is supported. 

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.67.2",
  "cmtVersion": "1.10.5",
  "configurations": [
    {
      "folder": "d:\\ws\\",
      "cmakeVersion": "3.21.6",
      "configured": true,
      "generator": "MinGW Makefiles",
      "usesPresets": true,
      "compilers": {
        "C": "C:/gcc/bin/gcc.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Release",
    "buildTypesSeen": [
      "Release"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 44,
    "executablesCount": 1,
    "librariesCount": 31,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by elahehrashedi** [comment]
"args": [
        "--build",
        "{command:cmake.activeBuildPresetName}",
        "--target",
        "demo_target"
    ],

**Comment by bobbrow** [comment]
We do have this substitution command and it seems to work for me in this simple test:
```
        {
            "type": "shell",
            "label": "print test preset",
            "command": "echo",
            "args": [
                "${command:cmake.activeTestPresetName}"
            ],
            "problemMatcher": []
        }
```

**Comment by bobbrow** [comment]
Is it possible that you do not have presets enabled when you ran the task?  Check the value of the `cmake.useCMakePresets` setting and whether the CMakePresets.json file is located in the same folder as the CMakeLists.txt that is pointed to by the `cmake.sourceDirectory` setting.

**Comment by JuriGagarin** [comment]
Sorry, I've updated my initial post - iniatally I was mixing up `activeTestPresetName` and `activeBuildPresetName`.
The issue is about `activeBuildPresetName`.

![image](https://user-images.githubusercontent.com/5842884/171352085-ca8a02a1-0ca2-4338-9f12-6bbf2190b7fc.png)

(as the project doesn't use tests as of now, I think the warning that no `activeTestPresetName` is present is OK.

My settings are like this:

`cmake.useCMakePresets`: `auto`
`cmake.sourceDirectory`: `${workspaceFolder}`

The `CMakePresets.json` as well as the toplevel `CMakeLists.txt` is located in the `${workspaceFolder}`.
Also, this CMake project works as expected for builduing etc... I just have trouble creating a task running specific targets for the active build preset.
