### ISSUE TITLE
VERBOSE CMake logging level missing

### ISSUE THREAD

**Issue by craigscott-crascit** [microsoft/vscode-cmake-tools#2583]
Issue Type: <b>Bug</b>

In the CMake Tools extension settings, the "Cmake: Logging Level" setting lists the logging level. There is no "verbose" option in the combo box provided, but the CMake message() command does have a VERBOSE message mode (it sits between STATUS and DEBUG, with STATUS presumably mapping to what VS Code calls "info").

Extension version: 1.11.23
VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

**Comment by elahehrashedi** [comment]
This setting is for logging the CMake extension information, not the CMake. CMake has a different way to define "verbos" options, for example, you can look into this page: https://cmake.org/cmake/help/latest/command/message.html
