### ISSUE TITLE
Stuck When Readinf Large compile_command.json

### ISSUE THREAD

**Issue by xiaoyun94** [microsoft/vscode-cmake-tools#2586]
### Brief Issue Summary

if compile_command.json is too large (~100M), the cmake tools will be stucked, and vscode cannot work well

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.67.2",
  "cmtVersion": "1.10.5",
  "configurations": [
    {
      "folder": "/root/c_test",
      "cmakeVersion": "3.17.0",
      "configured": false,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/gcc",
        "CXX": "/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by xiaoyun94** [comment]
- Generate Test Files
```
rm -rf sub_*
for num in {1..3000}  
do
mkdir -p sub_${num}
echo "" > "./sub_${num}/test_${num}.c"
done  

```

- CMAKE FILE DEMO
```cmake

file(GLOB_RECURSE SOURCE_FILES *.c)
file(GLOB DIRS sub_*)
#message("6666 ${SOURCE_FILES}")
include_directories(${DIRS})
add_library(test1 ${SOURCE_FILES})
···

**Comment by bobbrow** [comment]
Hi @xiaoyun94, could you please provide more information about what appears to be stuck for you?  We tried to reproduce this using the scripts you provided (on Ubuntu 20.04 and WSL), but we're not seeing any obvious problems.  Generating the project and loading the project outline seemed to respond in a reasonable amount of time.

**Comment by Worrador** [comment]
It must be the same as in https://github.com/microsoft/vscode-cmake-tools/issues/970.
Basically, it takes too long or too much resources to parse the compile_commands.json file and (for me, the cmaketool crashes).

**Comment by xiaoyun94** [comment]
i have solved the problem by modifying env `NODE_OPTIONS=--max-old-space-size=8192`.
and the log records the memory problem actually
@bobbrow @Worrador
