### ISSUE TITLE
extension v1.11.23 post-update quirk with visual studio platform and toolset cmake flags

### ISSUE THREAD

**Issue by david-fong** [microsoft/vscode-cmake-tools#2589]
### Brief Issue Summary

Today I switched to the pre-release channel of this extension on my Windows 10 machine. This got me from v1.10.5 to v1.11.23. I have the visual studio 17 2022 build tools installed on this machine, and only have the four default-detected user-local kits configured. I have CMake 3.23.2. I updated bunch of other stuff too: visual studio 17.2.0 to 17.2.3, the vscode cpptools extension to v1.10.5, my vscode to 1.68, and some minor windows updates. I think I updated them in that order, but my memory is a little foggy.

After those updates, I ran the configure command from this extension with the "Visual Studio Build Tools 2022 Release - amd64" kit selected. It ran the comfigure command, which included these flags: `-T host=x64 -A x64`. This caused CMake to issue an error saying that "Generator platform: x64 Does not match the platform used previously: " (the one used previously was printed as an empty string). I was really confused and wasn't sure if I had done something wrong.

Finally, I tried switching back to the 1.10.5 release of this vscode extension, which configured without issue. It was at this point that I noticed that after switching back to the 1.10.5 version, the extension didn't add the `-T host=x64 -A x64`. Now what _really_ surprised me was that after switching back to the prerelease version (1.11.23), the flags were now _not_ added either.

I have no idea if this is actually caused by the update-related activities, or if it was caused by something else. I can no longer reproduce the issue by switching between the release and prerelease channels of the extension. I realize that it must be annoying for me to not have a repro (sorry!).

Is this a known issue? Does this sound like a problem with CMake? I don't know what's happening, but if it sounds like a CMake issue I'll post a question on their discourse site.

**Comment by elahehrashedi** [comment]
If you run the command "CMake: Delete Cach and Reconfigure", the previous platform information will be cleaned from the cache.

**Comment by bobbrow** [comment]
It is common to see mismatched caches when you update Visual Studio and running the command @elahehrashedi suggests is usually the correct remedy.

**Comment by bobbrow** [comment]
Regarding the `-A` and `-T` discrepancies, it's hard for us to know without a repro, but the conditions for us adding those flags or not depend on whether `CMAKE_GENERATOR` is previously defined or not, and whether the `toolset` and `platform` are set in the Kit (or settings)

**Comment by david-fong** [comment]
Thank you both for that info! That's good to know. I'm good to close this issue now.
