### ISSUE TITLE
Project Outline missing file icons

### ISSUE THREAD

**Issue by clibequilibrium** [microsoft/vscode-cmake-tools#2595]
### Brief Issue Summary

Since yesterday for some reason I got missing file icons in CMake project outline. It used to display an Icon (C, C++) but now it's all gone.  I have no idea why, I am updated to the latest cpp tools, and cmake tools 

### Additional Information

How it looks in Project Outline (notice not icons) 
![image](https://user-images.githubusercontent.com/105135724/173234075-ad8aa7de-3d1b-4f49-9bbb-10058766866f.png)

How it looks in file explorer: 
![image](https://user-images.githubusercontent.com/105135724/173234100-d5abd36b-e24f-4e98-b243-9fbcf7a84cfb.png)

**Comment by elahehrashedi** [comment]
This doesn't seem to be the CMake Tools extension's issue. Vs Code set the icons, not the extension. 
We could repro this in the Vs Code insiders version. We need to follow up on this issue with the Vs Code.

**Comment by clibequilibrium** [comment]
Thank you @elahehrashedi  for now I am rolling back to 1.67.0, the issue happens on 1.68 version of VSCode

**Comment by bobbrow** [comment]
Upstream issue fixed. Closing this one.
