### ISSUE TITLE
Support cmakeExecutable in CMakePresets.json 

### ISSUE THREAD

**Issue by skallweitNV** [microsoft/vscode-cmake-tools#2611]
### Brief Issue Summary

Currenty, the CMake executable can only be specified using the CMake Tools settings variable `cmake.cmakePath`.

It would be a nice addition if CMake Tools would support the `cmakeExecutable` field in the `CMakePresets.json`:

> An optional string representing the path to the CMake executable to use for this preset. This is reserved for use by IDEs, and is not used by CMake itself. IDEs that use this field should expand any macros in it.

**Comment by skallweitNV** [comment]
I've just tested it again on our project and you are absolutely correct, it is actually working. I must have been doing something wrong before, really sorry for wasting your time! Closing this.

**Comment by bobbrow** [comment]
No worries.  Glad you got it sorted out!
