### ISSUE TITLE
want to display the name of the programs when launch multiple target by launch button of the status bar

### ISSUE THREAD

**Issue by SAquarius** [microsoft/vscode-cmake-tools#2613]
### Brief Issue Summary

I use the launch button of the status bar to launch multiple C++ executable programs, but the names in the terminal are all CMake/Launch, and I want to display the name of the executable program in the terminal. How can I do this?

![](https://pic.songjiahao.com/img/NF}CS3$WIYLWYBT3FQU~R39.png)

**Comment by bobbrow** [comment]
Would you like it to be something more like 'CMake/Launch - targetName'?  I submitted a PR to enable that.

**Comment by SAquarius** [comment]
That's exactly what I was hoping for, thank you.

**Comment by bobbrow** [comment]
It is available in 1.12.5 (pre-release) as of this morning.  Feel free to install it and let us know what you think.
