### ISSUE TITLE
error starting up cmake-server vscoode

### ISSUE THREAD

**Issue by lylth** [microsoft/vscode-cmake-tools#2617]
### Brief Issue Summary

error starting up cmake-server vscoode

### Additional Information

https://github.com/twxs/vs.language.cmake/issues/97#issue-1283377645

**Comment by bobbrow** [comment]
Can you please run the `CMake: Log Diagnostics` command and share the output?

**Comment by lylth** [comment]
{
  "os": "linux",
  "vscodeVersion": "1.68.1",
  "cmtVersion": "1.12.4",
  "configurations": [
    {
      "folder": "stonedb57",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}

**Comment by lylth** [comment]
The cmake version displayed in the terminal is as follows
![image](https://user-images.githubusercontent.com/79444526/175756547-f51c1da4-8cd6-4297-bb39-3f7975ab4f92.png)

**Comment by lylth** [comment]
The plugins I installed also show installed.Why does 'CMake: Log Diagnostics' show unknown
![image](https://user-images.githubusercontent.com/79444526/175756616-72979786-430e-45f8-bbf5-eaea4873bc19.png)

**Comment by lylth** [comment]
Thank you very much, I have been working on it for several days without solving the problem. After listening to your suggestion and changing to a new version of cmake, the problem is solved. you are top notch
