### ISSUE TITLE
Problems with long path names in Linux

### ISSUE THREAD

**Issue by ItachiSan** [microsoft/vscode-cmake-tools#262]
As in title.

## Description
In case the absolute real path of the CMake build folder is longer more than a certan number of characters (have to detect how many), the server doesn't start properly and reports that another server is already running.

## Workaround
From what I've understood, the communication is done through a named pipe (is it?); removing it and restarting VSCode fixes the issue for one time (-> has to be done at every restart)

### TODO
Add missing stuff to make this issue great again.

Issue created as decided in #197.

**Comment by bobbrow** [comment]
In issue #197 you mention that you are not having this problem anymore.  If that is the case, can we close this issue?

**Comment by ItachiSan** [comment]
Hi @bobbrow, has been quite some time since last time I used it, can check probably tonight and let you know.
