### ISSUE TITLE
[bug] Unable to detect `clang-cl.exe` as compilers installed in `C:\Program Files\LLVM\bin\`.

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-cmake-tools#2622]
There are two types of clang compilers on Windows: `clang.exe` and `clang-cl.exe`.

It seems that it can successfully detect both `clang.exe` and `clang-cl.exe` installed in **Visual Studio**. 

However, it can **ONLY** detect `clang.exe` installed in **LLVM**.

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/175800453-d54c1d57-9026-445c-93cd-e235804c32c6.png)
![image](https://user-images.githubusercontent.com/71438617/175800422-1042a8ea-71c1-4c1a-9620-059aa8dfb50c.png)
![image](https://user-images.githubusercontent.com/71438617/175800425-a6960296-96d2-41ac-a742-357a61552a1e.png)

**Comment by elahehrashedi** [comment]
We are working on a fix for this in this PR #2627
