### ISSUE TITLE
MSVC_VERSION is incorrect when cmake configure project with tool kit clang-cl

### ISSUE THREAD

**Issue by ivan-sialiuk** [microsoft/vscode-cmake-tools#2624]
### Brief Issue Summary

The issue described here https://github.com/microsoft/vscode-cmake-tools/issues/1053 still exists.

### CMake Tools Diagnostics

```shell
"os": "win32",
  "vscodeVersion": "1.68.1",
  "cmtVersion": "1.11.26",
  "configurations": [
    {
      "folder": "c:\\prj",
      "cmakeVersion": "3.23.0",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false
      }
    }
  ],

{
    "name": "Clang 12.0.0 (MSVC CLI) for MSVC 16.11.32602.291 (Visual Studio Professional 2019 Release - amd64)",
    "visualStudio": "4d9d25e6",
    "visualStudioArchitecture": "amd64",
    "compilers": {
      "C": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe"
    }
  }, 
```

**Comment by bobbrow** [comment]
What is the version number that you are getting?  Do you have any other versions of Visual Studio installed, or just VS 2019?

**Comment by elahehrashedi** [comment]
@sfreed141

It seems like `VCToolsInstallDir` was added in this PR  https://github.com/microsoft/vscode-cmake-tools/pull/2089 to solve the current issue, which was then removed in PR https://github.com/microsoft/vscode-cmake-tools/pull/2366:

`//'VCToolsInstallDir', - disabled temporarily as it breaks downlevel toolset selection`

Would you please take a look and remind me what was the problem with downlevel toolset selection?

**Comment by sfreed141** [comment]
I don't know what the issue is with downlevel toolset selection. In my PR I was just refactoring and made no changes to the list ([here's where it ended up](https://github.com/microsoft/vscode-cmake-tools/pull/2366/files#diff-933b0edf01d7e849f64032531c3e4b60a887a06ce9bff7a2f4be5337f3ef57efR251)). `VCToolsInstallDir` was already commented out before my PR.

**Comment by ivan-sialiuk** [comment]
> What is the version number that you are getting? Do you have any other versions of Visual Studio installed, or just VS 2019?

I get compiler version 15 instead of 16 (compiler.version=16). I have only visual studio 19 installed with all the latest updates.
