### ISSUE TITLE
cmake.debugConfig": "args" ignores Redirect input/output to/from the debug target

### ISSUE THREAD

**Issue by jx2014** [microsoft/vscode-cmake-tools#2634]
### Brief Issue Summary

I noticed just today that cmake will ignore the IO redirection symbol "<" while parsing arguments.

I have the following arguments setup in `settings.json`. 

```    
"cmake.debugConfig": {
        "args": ["abc", "<", "test.txt"],
        "externalConsole": false,
        "MIMode": "gdb",
    }
```

Here is an example code to test the argument redirection: 
```
int main(int argc, char *argv[])
{
  // testing the ability to pass argument
  // to cmake debugger 
  printf("argument used: %d\n", argc);
  for(int i = 0; i < argc; i++) {
      printf("argv[%d]: %s\n", i, argv[i]);
    }
 }
```

The test program will only print out up to 'abc', while ignoring '<' and what is after. 
```
argument used: 2
argv[0]: test.exe
argv[1]: abc
```

### Additional Information

Platform and Versions
Operating System: Windows 10
CMake Version: 3.21.3
VSCode Version: 1.68.1
CMake Tools Extension Version: 1.11.2
Compiler/Toolchain: GCC 10.3.0 x86-w65-mingw32

**Comment by jx2014** [comment]
I take that back.
the redirection works as intended. It's just that "<" and what's after are not counted as arguments.

**Comment by elahehrashedi** [comment]
This is a debugger error, not the CMakeTools extension. if `"cmake.debugConfig"` contains "<" or ">"  with Visual Studio debugger, you will get this error: 

`Error processing 'configurationDone' request. Input or output cannot be redirected because the specified file is invalid.`

But for example, if you use the GCC kit, there will be no error using "<" or ">" in `"cmake.debugConfig"`.

**Comment by elahehrashedi** [comment]
It is the expected behavior that  "<" and what's after are not counted as arguments. Is there anything else you would like for us to investigate?

**Comment by jx2014** [comment]
I don't have anything else to add. Like you said, the behavior for "<" is expected. It is not a bug.

**Comment by bobbrow** [comment]
Thanks for confirming.
