### ISSUE TITLE
CMake errors persist in "Problems" output

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cmake-tools#2644]
### Brief Issue Summary

CMake errors persist in "Problems" output even after they have been eliminated.

I'm not quite sure how to report this properly yet. I'll add additional info as I can.

I build my project via a Python make.py file and Via CmakePresets. The python make.py file generates some CMake modules.

Sometimes I get CMake errors like the generated CMake.modules.cmake are not found on "include(CMake.cmake). Even after I fix the issue I still can see the red squiggly lines and a entry in the Problems Output section. It persists until I restart VSCode.

**Comment by H-G-Hristov** [comment]
I'm also seeing a similar issue related to Python and Pyling errors. I have several Microsoft Python extensions installed.

**Comment by elahehrashedi** [comment]
1. Persistent Pylint errors in the "Problem" section are not related to CMake tools extension.
2. After fixing CMake errors related to include (as you mentioned), have you tried "CMake: Delete Cache and reconfigure"? Please try this and see if the errors still persist. Every time we re-configure, the "Problems" should be cleared.
