### ISSUE TITLE
I can not launch cpp target in my console using cmake-tools with version 1.12.13

### ISSUE THREAD

**Issue by CSQ223** [microsoft/vscode-cmake-tools#2650]
### Brief Issue Summary

When I launched my cpp target using the triangular button, the powershell only echoes the name of cpp target as follows, but Nothing runs.

```
PS D:\dev\cpp_template\build> "D:/dev/cpp_template/build/cpp_template.exe"
D:/dev/cpp_template/build/cpp_template.exe
PS D:\dev\cpp_template\build>
```

**Comment by elahehrashedi** [comment]
Can you run "CMake: log diagnostics" and share the result here with us?

**Comment by bobbrow** [comment]
The `.` is missing before the quoted path for some reason. We should be adding the dot before the quote when "PowerShell" is in the path of your shell program.  Is your PowerShell installed in some other folder?  Normally it's in one of these two places:
* C:/Windows/System32/WindowsPowerShell
* C:/Program Files/PowerShell/7

**Comment by LucasOe** [comment]
I'm using PowerShell 7 installed via Scoop and the dot before the quoted path is also missing for me.

**Comment by bobbrow** [comment]
@LucasOe what path is your version installed to? Sorry, I'm not familiar with Scoop.  We could potentially fix this by checking the name of the terminal process `pwsh.exe` in addition to looking at the path.

**Comment by LucasOe** [comment]
@bobbrow By default scoop installs to `C:\Users\<Username>\scoop\apps\pwsh\current\pwsh.exe`. According to the [docs](https://scoop-docs.vercel.app/docs/misc/Global-Installs.html) system-wide installations install to `%SYSTEMDRIVE%\ProgramData\scoop`, but I haven't tried that.

**Comment by bobbrow** [comment]
Thanks for confirming.  That explains why our fix for other PowerShell installations is not working in your case.
