### ISSUE TITLE
Unable to determine what CMake generator to use

### ISSUE THREAD

**Issue by gwg605** [microsoft/vscode-cmake-tools#2656]
### Brief Issue Summary

Cannot configure simple(helloworld) CMake project. Report error: "Unable to determine what CMake generator to use"

What I did:
1. Create helloworld folder
2. Go to helloworld folder
3. run VS Code: code .
4. Ctrl+Shift+P: cmake: quick start
5. Project: HelloWorld, type: Executable
Get error: Unable to determine what CMake generator to use

What I expected:
The extension will let CMake select which generator to use, and no extra steps to configure project.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.69.2",
  "cmtVersion": "1.11.26",
  "configurations": [
    {
      "folder": "HelloWorld",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [
      "file:///d%3A/projects/valerygordeev/HelloWorld/main.cpp"
    ],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using kit
[driver] CMakeDriver Kit set to __unspec__
[kit] The environment for kit '__unspec__': {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\user\\AppData\\Roaming",
  "APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL": "1",
  "asl.log": "Destination=file",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_9184_CQGERFMKMDGCZUFK",
  "CMAKE_TOOLCHAIN_FILE": "D:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "PC-WIN10",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "ELECTRON_NO_ATTACH_CONSOLE": "1",
  "ELECTRON_RUN_AS_NODE": "1",
  "ERLANG_HOME": "C:\\Program Files\\erl-24.1",
  "FARADMINMODE": "1",
  "FARHOME": "C:\\Program Files\\Far Manager",
  "FARLANG": "English",
  "FARLOCALPROFILE": "C:\\Users\\user\\AppData\\Local\\Far Manager\\Profile",
  "FARPROFILE": "C:\\Users\\user\\AppData\\Roaming\\Far Manager\\Profile",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\user",
  "LOCALAPPDATA": "C:\\Users\\user\\AppData\\Local",
  "LOGONSERVER": "\\\\PC-WIN10",
  "MOZ_PLUGIN_PATH": "C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
  "NUMBER_OF_PROCESSORS": "4",
  "OneDrive": "C:\\Users\\user\\OneDrive",
  "OPENSSL_CONF": "C:\\Program Files\\PostgreSQL\\psqlODBC\\etc\\openssl.cnf",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\Program Files\\Far Manager\\;C:\\Program Files\\Python310\\Scripts\\;C:\\Program Files\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Python39\\Scripts\\;C:\\Program Files\\Python39\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\CMake\\bin;C:\\Program Files\\nodejs\\;C:\\Program Files\\dotnet\\;C:\\VulkanSDK\\1.2.170.0\\Bin;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\user\\.dotnet\\tools;C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\SysGCC\\mingw64\\bin;C:\\Users\\user\\AppData\\Roaming\\npm",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "3c03",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "QtMsBuild": "C:\\Users\\user\\AppData\\Local\\QtMsBuild",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\user\\AppData\\Local\\Temp",
  "TMP": "C:\\Users\\user\\AppData\\Local\\Temp",
  "USERDOMAIN": "PC-WIN10",
  "USERDOMAIN_ROAMINGPROFILE": "PC-WIN10",
  "USERNAME": "user",
  "USERPROFILE": "C:\\Users\\user",
  "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox\\",
  "VK_SDK_PATH": "C:\\VulkanSDK\\1.2.170.0",
  "VSCODE_AMD_ENTRYPOINT": "vs/workbench/api/node/extensionHostProcess",
  "VSCODE_CLI": "1",
  "VSCODE_CODE_CACHE_PATH": "C:\\Users\\user\\AppData\\Roaming\\Code\\CachedData\\3b889b090b5ad5793f524b5d1d39fda662b96a2a",
  "VSCODE_CWD": "D:\\projects\\valerygordeev\\HelloWorld",
  "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
  "VSCODE_IPC_HOOK": "\\\\.\\pipe\\8e7a4f669414df32e14e14c554b1bc7c-1.69.2-main-sock",
  "VSCODE_NLS_CONFIG": "{\"locale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}",
  "VSCODE_PID": "9184",
  "VULKAN_SDK": "C:\\VulkanSDK\\1.2.170.0",
  "windir": "C:\\Windows"
}
[driver] Trying to detect generator supported by system
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
```

### Additional Information

I. CMake works with this project without any problems:
1. Configure:
D:\projects\valerygordeev\HelloWorld\build>cmake -A x64 ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Configuring done
-- Generating done
-- Build files have been written to: D:/projects/valerygordeev/HelloWorld/build

2. Build:
D:\projects\valerygordeev\HelloWorld\build>cmake --build .
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
Checking Build System
Building Custom Rule D:/projects/valerygordeev/HelloWorld/CMakeLists.txt
main.cpp
HelloWorld.vcxproj -> D:\projects\valerygordeev\HelloWorld\build\Debug\HelloWorld.exe
Building Custom Rule D:/projects/valerygordeev/HelloWorld/CMakeLists.txt

II. I tried to specify preferred generator (.vscode/settings.json): "cmake.preferredGenerators": ["Visual Studio 16 2019"] - the problem is still present.

**Comment by elahehrashedi** [comment]
I am not able to repro your issue. However, I can see in your log that your cmake version is unknown. `"cmakeVersion": "unknown",`
Can you specify the `cmakePath` and `generator` to your settings in `./vscode/settings.json` file and check if that solves your issue:

example:
```json 
{
    "cmake.cmakePath": "C:/Program Files/CMake/v3.18.3/bin/cmake.exe",
    "cmake.generator": "Visual Studio 16 2019",
}
```

**Comment by gwg605** [comment]
1. Adding "cmake.cmakePath": "C:/Program Files/CMake/bin/cmake.exe" - nothing is changed, still: "Unable to determine what CMake generator to use"
NOTES:
   - cmake.exe on the path, you can see it in the environment dump
   - cmake.exe --version => "cmake version 3.23.2"
2. Adding "cmake.generator": "Visual Studio 16 2019" - there are two cases:
   - without VS Code restart - the problem is still present
   - with restart VS Code - the project is configured successfully on startup
3. Regarding '"cmakeVersion": "unknown"': the version is displayed only if project is configured successfully
4. My main complain is that the extension requires the generator specification, but cmake works well without this info
