### ISSUE TITLE
feedback: extension clutters the vscode ui

### ISSUE THREAD

**Issue by mpictor** [microsoft/vscode-cmake-tools#2657]
### Brief Issue Summary

I only occasionally deal with cmake (and C++) projects.

If I have this extension installed, it fills up vscode's status bar with cmake-specific things, even in non-cmake projects. The amount of clutter it adds to the status bar would be annoying _in_ a cmake project, and it's so much worse when it's not a cmake project.

So... make the status bar stuff configurable if it isn't (if it's in the prefs I didn't see it), and make it possible to have the extension minimize itself **_except_** when in a project which already contains cmake files.

![image](https://user-images.githubusercontent.com/671579/180702800-59583825-2ef8-4755-869f-7f533fb898eb.png)
These items, as well as one for switching projects, seem to come from the cmake extension. All show up in non-cmake projects in spite of being **useless in that context**.

### Additional Information

extension version `CMake Tools v1.11.26`

Compare this extension's behavior with, say, the PlatformIO extension. That one does a huge amount, and yet when I'm not actively using it I forget it's there. Not possible with cmake :(

**Comment by bobbrow** [comment]
Have you tried using the `cmake.statusbar.visibility` and/or `cmake.statusbar.advanced` settings to configure the items in the status bar?

We've also considered moving the items out of the status bar completely and into the sidebar with our project outline.  We're tracking that feature with this item: #1582.

The extension should not activate in your non-CMake projects unless there is a CMakeLists.txt file somewhere in your folder.  And even in that case, we won't fully activate and put icons in the status bar unless you tell us you want us to operate on a CMakeLists.txt file that is not in the root folder.  If the extension is activating for some other reason, you can run the `Developer: Startup Performance` command and share the output with us. It will tell us why VS Code activated our extension.
