### ISSUE TITLE
[question] Is it possible to integrate with the VSCode-ROS plugin?

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-cmake-tools#2658]
It is related to the comment of this issue: https://github.com/ms-iot/vscode-ros/issues/694#issuecomment-1087220473

Because ROS uses CMake to manage its C/C++ part and there exist the [vscode-ros](https://github.com/ms-iot/vscode-ros) plugin, I wondered that **"Is it possible to integrate this plugin with it?"**

**Comment by bobbrow** [comment]
What exactly do you mean by "integrate"?  Are you asking to merge your extension into ours?  Your ROS extension can programmatically call our commands.  So you don't necessarily need to have your functionality embedded into our codebase.  And that's probably not something we'd want to do anyway.
