### ISSUE TITLE
Unable to determine what CMake generator to use.

### ISSUE THREAD

**Issue by gi-jimbo** [microsoft/vscode-cmake-tools#2664]
### Brief Issue Summary

I've seen a number of reports of this issue but am having difficulty finding the right solution.

Windows 10 version 21H2
VS Code version 1.69.2
VS Code extension CMake v0.0.17
VS Code extension CMake Tools v1.11.26

I have mingw64

I was having issues with it not finding the cmake path so I installed cmake directly (v 3.23.3) and added it to the path.  Now I'm getting the CMake generator error.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.69.2",
  "cmtVersion": "1.11.26",
  "configurations": [
    {
      "folder": "DesignControl",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
[proc] Executing command: C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe -v
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[main] Configuring folder: DesignControl 
```

**Comment by elahehrashedi** [comment]
This seems to be a duplicate of https://github.com/microsoft/vscode-cmake-tools/issues/2656,
if not, would you please provide more info about your project?

**Comment by elahehrashedi** [comment]
I can see in your log that your cmake version is unknown. `"cmakeVersion": "unknown",`
Can you specify the `cmakePath` and `generator` to your settings in `./vscode/settings.json` file and check if that solves your issue:

example:
```json 
{
    "cmake.cmakePath": "C:/Program Files/CMake/v3.18.3/bin/cmake.exe",
    "cmake.generator": "Ninja",
}
```

**Comment by gi-jimbo** [comment]
"cmake.cmakePath": "C:/CMake/bin/cmake.exe"

I was hoping cmake would determine the generator itself like it does when it's run in a terminal from the cmake command.

**Comment by elahehrashedi** [comment]
Thank you for your response. Would you please do these 3 steps so that we can get a better insight into what is causing this issue?

1. I suggest running this command on the terminal to see if querying the compiler is successful. Please share the results:  `"C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe" -v`

2. try using MSYS Makefiles as your generator:
```json 
{
    "cmake.cmakePath": "C:/CMake/bin/cmake.exe",
    "cmake.generator": "MSYS Makefiles",
}
```

3. You can also generate using the terminal and share the results: 
```
"C:/CMake/bin/cmake.exe" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -Sc:/path/to/your/project -Bc:/path/to/your/project/build -G "MSYS Makefiles"
```

**Comment by bobbrow** [comment]
I made some edits to the request for information above.

**Comment by gi-jimbo** [comment]
Hmm... Interesting.  The setup I used was directly from here:
https://code.visualstudio.com/docs/cpp/config-mingw
Thanks for the tip.  I'll search around and see what I can find related to MSYS2 and CMake.

**Comment by gi-jimbo** [comment]
I uninstalled MSYS2 and got MinGW-64 from here instead:
https://winlibs.com/
Now everything is running as intended.
