### ISSUE TITLE
Can't find CMakeLists.txt file in the root of the folder on Ubuntu

### ISSUE THREAD

**Issue by bub1ick** [microsoft/vscode-cmake-tools#2669]
I have my project, which I have just cloned from my GitHub. In the root dir I have a `CMakeLists.txt `file. Here's the screenshot confirming it.
![image](https://user-images.githubusercontent.com/51718131/182507911-7ccd1120-ac13-4258-9a83-5e9325f09d95.png)
I rely on `CMake: Build` command of the extension to build my project (running ninja build system under the hood). As it can't detect it, I've tried to add this file manually as the extension suggested. That done, it still doesn't allow me to use the aforementioned command - it just doesn't show up in the command pallete, nor does it provide IntelliSense with enough information to properly highlight the code. It could though detect the kit installed on my system (LLVM-clang toolchain).

All of the dependencies and prerequisites have been installed. I also tried rebooting the system a couple of times.

Note: This project setup works flawlessly on Windows, but for some reason on my Ubuntu machine it doesn't.

**Comment by bobbrow** [comment]
Can you try running the `CMake: Configure` command first?  For whatever reason the extension isn't currently aware of the CMakeLists.txt file so it has disabled the build command.  One situation where this happens is when the CMakeLists.txt file is added after the workspace folder is opened in VS Code.  It's also possible that the setting for `cmake.sourceDirectory` is incorrect.  Running the Configure command should either wake up the extension or let us know what the problem is.

**Comment by bub1ick** [comment]
I forgot to mention that I've already tried that, but for the sake of certainty I've tried to run both `CMake: Configure` and `CMake: Delete Cache and Reconfigure` commands again, and it appears that extension cannot configure CMake (configuring takes infinite amount of time) because it still can't locate the `CMakeLists.txt` file.

**Comment by bobbrow** [comment]
Oh, I see the problem now.  It looks like the file is incorrectly named on a case-sensitive file system.  Replace the capital `I` with a lowercase `i` in the file name.  
![image](https://user-images.githubusercontent.com/12818240/182715626-34085bb5-3608-4b18-b228-db50904c4c13.png)

**Comment by bub1ick** [comment]
Thanks! That actually solved my problem. I've completely forgotten that capitalization in Linux is crucial!
