### ISSUE TITLE
respect vscode setting insertSpaces when updating preset files via gui

### ISSUE THREAD

**Issue by david-fong** [microsoft/vscode-cmake-tools#2677]
### Brief Issue Summary

Currently, when adding a new cmake preset via the gui action, the edits made to the CMakePresets.json file will always use spaces for indentation. It would be a nice quality of life feature if it either detected the indentation style by reading the file contents, or checked the vscode settings for `insertSpaces` to decide whether to use tabs or spaces.

**Comment by elahehrashedi** [comment]
We have a fix ready for this issue. #2678

**Comment by david-fong** [comment]
Awesome. Thank you!
