### ISSUE TITLE
CMake kits chokes when parsing exported functions after running `environmentSetupScript`

### ISSUE THREAD

**Issue by progheal** [microsoft/vscode-cmake-tools#2686]
### Brief Issue Summary

When using `environmentSetupScript` property in a kit definition, the specified execution completes succesfully, but the extension have problem parsing the resulting environment variable definitions. Specifically, it reports many `[kit] Error parsing environment variable: }` or similar when there are bash exported function, which is very possible to contain newline in it.

### Additional Information

This is previously reported in a closed bug https://github.com/microsoft/vscode-cmake-tools/issues/809#issuecomment-703607891; the commenter asked if they should open a new issue for this, but I don't see any other issues for this problem with a quick search of the error message.

The exported functions are, in my case, in the form of `BASH_FUNC_<name>%%=() { <function content> }`; some googling indicates that this form is due to Shellshock. The last `}` is usually preceded by a newline, which makes this `}` looks like it's on a line on its own, and may be the reason the error message contains a single `}`. If the function contains `case` constructs, the catch-all case `*)` and the ending double semicolon will also trigger the error message, indicating it doesn't know how to parse `*)` or `;;`.

In addition to the error message, it is shown (via debug log) that the parsed list of env variables contains fragments of function that looks like variable definition and happens to be on a line on its own (eg. setting a variable in a function). This may have some vulnerability implications.

I'm aware that usually environment variable don't have good supports on special characters like newlines, but these exported "variable" comes from bash exporting function, and is not defined manually. So maybe it can be fixed specifically for these exported function only; fixing this for multiline env variable in general may be an impossible task.

**REPRO STEPS**
As there are some aspect of the condition to trigger this that I don't fully understand, I can't provide a clear repro steps; but from more googling, it seems like, in my case, these exported functions entered my system along with the package `environment-modules`. So a possible repro may be:

1. Install `environment-modules` package in a linux distribution.
2. Use VSCode with this extension to connect to this linux distribution.
3. Add a cmake kit with `environmentSetupScript` properties. (The program to run don't seems to matter; also, in my case it is triggered from `cmake-tools-kits.json`, ie. the user kit.)
4. In VSCode, select this kit.
5. :x: Observe the error message appears in "CMake/Build" output.

**SYSTEM SPECS**
* (Remote) Linux distribution: Rocky Linux 8.5 (which seems like has `environment-modules` pre-installed)
* VSCode: 1.70.1 running on Windows 11 21H2
* CMake Tools extension: v1.11.26

As both of these two machines are in a corporate setting, there are corporate policies that I need to investigate to know whether I'm allowed to provide logs; and these logs also contain a pretty good amount of confidential data, so they cannot be provided verbatim anyway. I will try to repro this bug on other machines without these concern.

**Comment by bobbrow** [comment]
Related: #2442, #2515
