### ISSUE TITLE
Problem with ros dependencies

### ISSUE THREAD

**Issue by BossaMelon** [microsoft/vscode-cmake-tools#2701]
### Brief Issue Summary

Hello, 

I am a developer working on ros, every time I  compile my project, I need to `source /opt/ros/kinetic/setup.bash` to setup environment variables and paths. I also write it on my .bashrc, but when I use the cmake extension to build, seems like `source /opt/ros/kinetic/setup.bash` is not executed and will give out `[cmake] -- Configuring incomplete, errors occurred!` But when I use the integrated terminal to do `cmake ..`, there is no error. 

So is there a way to let the extension do the `source /opt/ros/kinetic/setup.bash` first and then build?

Thanks!

**Comment by elahehrashedi** [comment]
Have you tried using `environmentSetupScript` in the kit?
Here is the document on on how to configure a project using kits: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/configure.md#the-cmake-tools-configure-step
and here is some more info on kits options: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md#kit-options

Short example:
```json
[
    {
        "name": "TestKit",
         ...
        "environmentSetupScript": "${workspaceFolder}/envsetup.sh"
    }
]
```

**Comment by BossaMelon** [comment]
Hey Elaheh,

Much thanks for the info, it works well!

Best

**Comment by BossaMelon** [comment]
> Have you tried using `environmentSetupScript` in the kit? Here is the document on on how to configure a project using kits: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/configure.md#the-cmake-tools-configure-step and here is some more info on kits options: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md#kit-options
> 
> Short example:
> 
> ```json
> [
>     {
>         "name": "TestKit",
>          ...
>         "environmentSetupScript": "${workspaceFolder}/envsetup.sh"
>     }
> ]
> ```
Hey Elaheh,

Much thanks for the info, it works well!

Best
