### ISSUE TITLE
No way to disable error hightlight in editor

### ISSUE THREAD

**Issue by grapland0** [microsoft/vscode-cmake-tools#2707]
I'd like to disable the complier error hightlight provided by "GCC" after each CMake build.

Screenshot:
![ni-gcc-error-hint](https://user-images.githubusercontent.com/11003371/186545823-495cda9d-7010-4c07-a5c9-abb295df8ff3.png)

**Comment by bobbrow** [comment]
Can you trying changing the value of the `cmake.enabledOutputParsers` setting to remove the compilers you would like to ignore (e.g. `gcc`)?  The default setting enables squiggles for all the major compilers.

**Comment by grapland0** [comment]
Thank you! It works.
