### ISSUE TITLE
Deprecation warnings show up as errors in Problems view

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vscode-cmake-tools#2708]
### Brief Issue Summary

`message(DEPRECATION ...)` which print `CMake Deprecation Warning at <file>:<line> (message): <message>` show up as errors, whereas it's a warning, which is even inside the message. Could the extension treat these messages as warnings and not errors? (Yellow vs. red sguiggly, ability to filter out as warning in Problems from real errors, etc.)

### Additional Information

![kép](https://user-images.githubusercontent.com/9763499/186616020-13a60918-fe0f-419f-b997-1225947d4472.png)

**Comment by elahehrashedi** [comment]
It looks like the code is not setting a severity level for deprecation warnings. We have a fix for this in [#PR2710](https://github.com/microsoft/vscode-cmake-tools/pull/2710)
