### ISSUE TITLE
Support multi-root workspaces

### ISSUE THREAD

**Issue by Nathan1852** [microsoft/vscode-cmake-tools#271]
### Brief Issue Summary

Support the new multi-root workspaces

### Other Notes/Information

Right now cmake-tools always builds the first directory.

VSCode now supports multiple workspaces, it would be nice if cmake-tools would use the CMakeLists.txt in the folder the user is currently in/the folder with the file the user currently has opened.

https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

Thanks

**Comment by vector-of-bool** [comment]
This is a big one, and I knew it would come up eventually. I'm in the middle of a refactor and am afraid this will have to wait for a while, but I really want to get to it as soon as possible.

**Comment by go2sh** [comment]
@vector-of-bool Does your refractoring touch the multi-root thing, or can I start working on it based on your work?

**Comment by vector-of-bool** [comment]
@go2sh: I've done no investigation into what it would take to do multi-root. Feel free to investigate, just work on the refactor branch, since that's where the develop will be updated soon.

**Comment by c0nd3v** [comment]
This is something that cmake tools NEEDS.

**Comment by vector-of-bool** [comment]
I've done no work on it, but I'm hoping to onboard some more collaborators and we'll hopefully have time to take a look at this.

**Comment by vector-of-bool** [comment]
Sorry all for the down time on this. I'm finally getting around to it. Expect something in the 1.1.0 update.

**Comment by vector-of-bool** [comment]
Turns out to be more work than anticipated. Lot of stateful stuff has to be moved around. This will be the big one for 1.2, since it's holding back the 1.1 and I have other things I want to get in user's hands for 1.1.0.

**Comment by bootress** [comment]
I've noticed that, in addition to the issue mentioned above, the automatic Intellisense configuration also breaks down when using a multi-root workspace, when an application in one workspace folder includes a library in a different folder.

I'm assuming this falls under the general "support multi-root" scope of this issue, just wanted to add my +1. Thanks!

**Comment by MathiasMagnus** [comment]
This would be a mighty useful addition.

**Comment by go2sh** [comment]
I created a new cmake extension about a year ago, because the pain to add this here was to big for me. It has nearly the same features plus a few extras, like multi-root, tasks support, finer configuration options and cmake file api support. The server api used here will be dropped in future versions of cmake. 
Search for cmake integration in the vscode extensions panel.

**Comment by bobbrow** [comment]
We are planning on adding multi-root support soon, though I don't expect it to be ready for 1.2.0.

**Comment by bobbrow** [comment]
For those following, we just posted a pre-release of multi-root support here: https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.3.0-beta

We would appreciate it if you would install it and provide feedback.

Thank you!

**Comment by astraujums** [comment]
I have a multi-root workspace, where one of the roots is for Python code, one is for CMake, and one is just for a reference to common headers that are not under the CMake root. I use the 1.3.0-beta of CMake Tools and it works fine. It wold be even better if CMake Tools did not complain or otherwise react on roots that don't have CMakeLists.txt file.

**Comment by bobbrow** [comment]
Thanks for the feedback @astraujums. I have moved your comment to a new issue.

**Comment by bobbrow** [comment]
This was addressed in 1.3.0
