### ISSUE TITLE
Cannot access /proc/pid/fd in CMake Wrapper when launched by CMake Tools

### ISSUE THREAD

**Issue by hehaoqian** [microsoft/vscode-cmake-tools#2724]
### Brief Issue Summary

I access `/proc/pid/fd` in CMake wrapper, but it does not work. 
**It works in terminal. It works in CI.** 
but does not work when it is launched by VSCode CMake tools
I don't know why

This is a simple minimum reproduce. The real wrapper script is much more complicated.

```
#!/bin/bash
# cmake.sh

ls /proc/$$/fd/2  # The file /proc/$$/fd/2 exists

echo Hello>/proc/$$/fd/2 # Does not work

# Error msg

/proc/XXXXX/fd/2: No such device or address
```

```
# .vscode/settings.json
{
  "cmake.cmakePath": "PATH TO cmake.sh"
}
```

```
# .vscode/tasks.json

{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "cmake",
      "label": "CMake: build_test",
      "command": "build",
      "group": "build",
    },
   ]
}
```

Run the task `CMake: build_test` will reproduce the issue

# Example error message
```
cmake.sh: line 5: /proc/17775/fd/2: No such device or address
```

Note that `/dev/stdout`, `/dev/fd/1`, `/proc/self/fd/1` does not work either,
but they do work outside VSCode

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.70.2",
  "cmtVersion": "1.11.26",
  "configurations": [
    {
      "folder": "/swwork/hbcc/hehaoqian/hbdk4",
      "cmakeVersion": "3.20.1",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/swwork/hbcc/commontools/clang-llvm/clang-llvm-12.0.0/bin/clang",
        "CXX": "/swwork/hbcc/commontools/clang-llvm/clang-llvm-12.0.0/bin/clang++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Additional Information

CMake Tools version: v1.11.26

```
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042
```

```
# uname -a
Linux ic306.hochip.cc 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```

**Comment by bobbrow** [comment]
Hi @hehaoqian, We're sorry you're having trouble with this.  We're not exactly sure what is wrong.  I tried to repro this on Ubuntu without any luck.  Are you able to repro it with a standard "shell" type task? If so, then this might be an issue that the VS Code team can help with.  Our extension just utilizes npm's `proc.execute` API to run the CMake executable (the script in your case).

It's possible that what could be tripping you up is that your script will need to support being run with `--version` as an argument because we use that to determine whether the value of the cmakePath setting is a valid version of cmake.  In that case we expect the first thing printed out to be `cmake version #.##.#`

**Comment by bobbrow** [comment]
Oh, actually, this may not be supported in node right now.  [The documentation](https://runebook.dev/en/docs/node/child_process) covering the options we pass to `spawn` says:

> 'pipe': Create a pipe between the child process and the parent process. The parent end of the pipe is exposed to the parent as a property on the child_process object as [subprocess.stdio[fd]](https://runebook.dev/en/docs/node/child_process#subprocessstdio). Pipes created for fds 0, 1, and 2 are also available as [subprocess.stdin](https://runebook.dev/en/docs/node/child_process#subprocessstdin), [subprocess.stdout](https://runebook.dev/en/docs/node/child_process#subprocessstdout) and [subprocess.stderr](https://runebook.dev/en/docs/node/child_process#subprocessstderr), respectively. Currently, these are not actual Unix pipes and therefore the child process can not use them by their descriptor files, e.g. /dev/fd/2 or /dev/stdout.
