### ISSUE TITLE
VSCodium-1.71.0.22245, cmake not working, libarchive.so.5 can't find liblzma.so.5

### ISSUE THREAD

**Issue by dacobi** [microsoft/vscode-cmake-tools#2728]
### Brief Issue Summary

when running cmake in terminal in VSCodium I get this error on Pop OS 22.04

./VSCodium-1.71.0.22245.glibc2.17-x86_64.AppImage: /tmp/.mount_VSCodiATrNha/lib/x86_64-linux-gnu/liblzma.so.5: version `XZ_5.2' not found (required by /lib/x86_64-linux-gnu/libarchive.so.13)

### CMake Tools Diagnostics

```shell
Bad CMake Executable
```

### Debug Log

```shell
Bad CMake Executable
```

### Additional Information

cmake version 3.22.1
Pop OS 22.04
VSCodium-1.71.0.22245

**Comment by bobbrow** [comment]
Hi there.  Sorry to hear that you're having trouble. We don't bundle `cmake` with this extension, so it sounds like you might have some issue with your distribution of linux or your installation of `cmake`.  Unfortunately, this is not an issue that we are able to help you with.
