### ISSUE TITLE
Build tasks (tasks.json) stopped working in 1.12.26

### ISSUE THREAD

**Issue by piomis** [microsoft/vscode-cmake-tools#2729]
### Brief Issue Summary

It looks that in newest version (1.12.26) build tasks defined via tasks.json stopped working.

It looks that each when build tasks is first pretends to execute it - but it does not in real cmake.exe call and in second stage is just calls cmake.exe without any arguments (see Debug log)

Interestingly when targets property is added to build task then second (previously 'empty') call to cmake.exe is completed with buildDirectory&target and is executed.
However looks that it is added to every tasks. So e.g. if "clean" task is called than it also has two "stages" - first one with clean target (which is not executed) and second one with executable target (which is executed).

When I downgrade to 1.11.26 exactly same config works perfectly.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.70.2",
  "cmtVersion": "1.12.26",
  "configurations": [
    {
      "folder": "d:\\Projects\\project1",
      "cmakeVersion": "3.23.2",
      "configured": true,
      "generator": "Ninja Multi-Config",
      "usesPresets": false,
      "compilers": {
        "C": "C:/Programs/Compilers/Keil_v537/ARM/ARMCLANG/bin/armclang.exe",
        "CXX": "C:/Programs/Compilers/Keil_v537/ARM/ARMCLANG/bin/armclang.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug",
      "Release"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 9,
    "executablesCount": 1,
    "librariesCount": 2,
    "targets": [
      {
        "name": "project1",
        "type": "EXECUTABLE"
      },
      {
        "name": "project1.check",
        "type": "UTILITY"
      },
      {
        "name": "project1.flash",
        "type": "UTILITY"
      },
      {
        "name": "project1.iwyu",
        "type": "UTILITY"
      },
      {
        "name": "project1.sonarqube",
        "type": "UTILITY"
      },
      {
        "name": "lib1",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "lib2",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "testall",
        "type": "UTILITY"
      },
      {
        "name": "testall_ci",
        "type": "UTILITY"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
[main] Building folder: project1
[main] Saving open files before configure/build
[build] Starting build
[driver] Start build project1
[proc] Executing command: C:\Programs\cmake-3.22.2\bin\cmake.EXE --build D:/Projects/project1/output/CMake --config Debug --target project1 --
[cmakefileapi-parser] Read reply folder: D:\Projects\project1\output\CMake\.cmake\api\v1\reply
[cmakefileapi-parser] Found index files: [...]
[build] Build finished with exit code 0
[cache] Reading CMake cache file D:/Projects/project1/output/CMake/CMakeCache.txt
[cache] Parsing CMake cache string
[extension] [8047] cmake.build finished (returned 0)
[proc] Executing command: C:\Programs\cmake-3.22.2\bin\cmake.EXE
```

### Additional Information

tasks.json:
```
{
    "version":"2.0.0",
    "tasks": [
        {
            "label": "CMake: Build",
            "type": "cmake",
            "command": "build",
            "group": {
                "kind": "build",
            },
            "problemMatcher": {
                "base": "$gcc",
                "source": "ArmClang",
                "fileLocation": "absolute"
            },
            "detail": "user defined"
        }
    ]
}
```

Terminal output for building tasks without targets property defined.

```
*  Executing task: CMake: Build 

build task started....
C:\Programs\cmake-3.22.2\bin\cmake.EXE
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

build finished successfully.
```

**Comment by elahehrashedi** [comment]
We have a PR to fix this issue: https://github.com/microsoft/vscode-cmake-tools/pull/2733. This will provide a default target if the target is not defined.
Meanwhile, as a workaround, you can add `"targets": [ "all"]` to your tasks definition:
```json
        {
            "label": "CMake: Build",
            "type": "cmake",
            "command": "build",
            "group": {
                "kind": "build",
            },
            "targets": [ "all"], **
            "problemMatcher": {
                "base": "$gcc",
                "source": "ArmClang",
                "fileLocation": "absolute"
            },
            "detail": "user defined"
        }

```

**Comment by piomis** [comment]
Thank you.
Just a remark - I tried that workaround and it works only partially.
As I described it looks that after latest refactors build task with targets defined json is called ALWAYS.
Thus none of other task works (e.g. clean).
Like it can be seen in log there are two "[proc] Executing command: " - but first one is only printed and never called.

Log when I updated tasks.json with "targets" property and select "CMake: Clean" command:

`[main] Building folder: project1 clean
[build] Starting build
[proc] Executing command: C:\Programs\cmake-3.22.2\bin\cmake.EXE --build D:/Projects/project1/output/CMake --config Debug --target clean --
[build] Build finished with exit code 0
[proc] Executing command: C:\Programs\cmake-3.22.2\bin\cmake.EXE --build D:/Projects/project1/output/CMake --config Debug --target all --`

**Comment by elahehrashedi** [comment]
I am not able to repro the issue when defining the targets, can you please explain what do you expect the `clean` to do and what is actually being done?

I will provide you with the VSIX after the new change is checked in so that you can test it on your project.

**Comment by piomis** [comment]
I can test - not a problem.

Just to describe full picture:

Normally I have following commands available when CMake Tools are installed:
![image](https://user-images.githubusercontent.com/29480839/189166381-f75a577c-5496-4da2-895d-d3a214b40dfd.png)

I'm expecting that when "CMake: Clean" is selected than:
C:\Programs\cmake-3.22.2\bin\cmake.EXE --build D:/Projects/project1/output/CMake --config Debug --**target clean --**
Should be called.
Unfortunately looks that when tasks.json contains property targets (even though it is property for build task not clean) 
it always overwrites all other tasks.

Thus cmake.exe is called with target taken from property instead of "clean".

This looks to be the same for any other target. If if select option "CMake: Build target", than list of available targets appears. However whatever target I will select - it will not be build because again contents of "targets" property will overwrite the one which is selected.

Is my description clear now?

**Comment by elahehrashedi** [comment]
Can you please share your tasks.json? Also, let me know what targets you have set in the status bar.
Also, in what order you are running the commands and/or tasks?

I will provide you with a link to VSIX after the new change is checked in so that you can test it on your project.

**Comment by piomis** [comment]
Not a problem:
tasks.json:
```
{
    "version":"2.0.0",
    "tasks": [
        {
            "label": "CMake: Build",
            "type": "cmake",
            "command": "build",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "targets": [ "all" ],
            "problemMatcher": {
                "base": "$gcc",
                "source": "ArmClang",
                "fileLocation": "absolute"
            },
            "detail": "user defined"
        }
    ]
}
```

In regards to settings I have following ones (taken from status bar):
Current build variant: CMake: [Debug]
Current kit: [ARMClang]
Current default target: [project1]


Interestingly if I change `"targets": [ "all" ]` into `"targets": [ "xxx" ]` then get following even when trying to build project1 target (CMake: Build target and select project1 from list which appears)

Log:
[build] Starting build
[driver] Start build project1
[proc] Executing command: C:\Programs\cmake-3.22.2\bin\cmake.EXE --build D:/Projects/project1/output/CMake --config Debug --target **project1** --
[build] Build finished with exit code 0
[cache] Reading CMake cache file D:/Projects/project1/output/CMake/CMakeCache.txt
[cache] Parsing CMake cache string
[proc] Executing command: C:\Programs\cmake-3.22.2\bin\cmake.EXE --build D:/Projects/project1/output/CMake --config Debug --target **xxx** --
[extension] [5564] cmake.buildWithTarget finished (returned 0)

Terminal:
Build Started...
C:\Programs\cmake-3.22.2\bin\cmake.EXE --build D:/Projects/project1/output/CMake --config Debug --target **xxx** --
ninja: error: unknown target 'xxx', did you mean 'all'?
Build finished with error(s).

**Comment by elahehrashedi** [comment]
I am still not able to follow what steps you are taking that cause this issue. The command `"CMake: Build Target"` will not pick the target from build tasks. I tested the extension and it works as expected when I try to run "CMake: Build Target" on a target that is different from the build task.

Would you please explain your steps in this way, for example:
step 1: run "CMake: Configure"
step 2: run "Tasks: Run Task" 
step 3: pick "CMake: Build" task
step 4: ....

**Comment by piomis** [comment]
So in my case it looks that targets from tasks.json are always picked up. From unknown reason.

Here is my setup and steps:

I am not calling CMake configure from VSCode - I have it done before VSCode is started.
My Workspace settings defines:
- CMake Source Dir to place where CMakelists.txt is located.
- CMake Build Dir to cmake build directory

As you can see in first post (I pasted diag info) CMake Tools properly see all targets which are defined in cmake project.
Additonally setting `configureOnOpen` is set to true - thus VSCode reconfigures (regenerates) Cmake build directory contents.

Steps which I do:
1) I add "targets" : [ "all" ] to tasks.json
2) Open my project workspace in VSCode
      - Cmake configure is automatically called (due to `configureOnOpen`)
3) From status bar I select default build variant (Debug)
4) From status bar I select active kit
5) I press F1 and start typing `cmake: clean`
6) I click on "CMake: Clean"
   - result is that extension calls target "all" instead of "clean".

When in step 1) I remove "targets": ["all"] from tasks.json then  in step 6, extension properly calls target clean.

Once again this behaviour is present also in previous version of cmake tools! It was not seen before (at least by me) because I haven't used "targets": [xxx] property in tasks.json file.

**Comment by elahehrashedi** [comment]
Thanks for the explanation, Let's make it more clear. In these steps, when do you run any task commands, like `"Task: Run Task"`? also in which step do you run a build command?
Can you add the terminal/log output after each step? so that I can see how `clean `command is ending up with a different target than `--target clean`?

**Comment by piomis** [comment]
[project1.zip](https://github.com/microsoft/vscode-cmake-tools/files/9530419/project1.zip)

Please find attached a small project.

What I do to reproduce:
1) unzip file somewhere (e.g. e:\tmp\project1)
2) update .vscode/settings.json with valid path to ninja,exe
3) open workspace in vscode (you may do it from command line with command: `code e:\tmp\project1`) 
 - in my case in Output (CMake/Build) tab I get following log: [opening_output_log.txt](https://github.com/microsoft/vscode-cmake-tools/files/9530432/opening_output_log.txt)
 - terminal log is empty
4) I press F1 and select Tasks: Run Task (as on screenshot: ![run_task_1](https://user-images.githubusercontent.com/29480839/189221006-9f50e969-32cd-4f8f-825a-bd8d65a1a7be.png)
5) In pop-up I pick CMake: Clean (as on screenshot: ![run_task_2](https://user-images.githubusercontent.com/29480839/189221132-08059519-b4ce-4936-9395-ec32b5ec34ea.png)
- following log appears in Output (CMake/Build): [task_clean_output_log.txt](https://github.com/microsoft/vscode-cmake-tools/files/9530445/task_clean_output_log.txt)
- following log appears in Terminal: [task_clean_terminal_log.txt](https://github.com/microsoft/vscode-cmake-tools/files/9530447/task_clean_terminal_log.txt)


By Output (CMake/Build) I understand following:
![image](https://user-images.githubusercontent.com/29480839/189221755-2f22b6a1-e3d1-42f5-b9ed-916195304887.png)

**Comment by elahehrashedi** [comment]
Can you try this VSIX https://github.com/microsoft/vscode-cmake-tools/suites/8203575642/artifacts/357268476 to check if the new changes have resolved your issue? Please let me know the results.

**Comment by piomis** [comment]
I've just tried - provided VSIX solved initial problem (that target which is selected as default is not detected correctly).
So this issue very likely may be closed.

In regards to running 'clean' from VS Code GUI - I have decided to debug it by myself.
Below few my observations:
- `CMake: clean` which I am referring in my posts is not a direct call of Task but a Command.
- looks that code attached to this command is in fact not a "CMake: Task with Clean command" but "CMake Task with Build command of target clean"
- and that is the reason why addition of "targets" in tasks.json is making CMake.Clean command unusable

**Comment by piomis** [comment]
I was able to track it farther.
As wrote before - Command `CMake: Clean`  is handled by function `clean()` in extension.ts
Starting from here is it processed as typical "build" with target 'clean'.
In long chain of different calls it finally ends in proc.ts `execute()` function.
Inside this function if "useTasks" option is set to true it triggers build task (by calling `void vscode.commands.executeCommand("workbench.action.tasks.build");`)

In pre 1.12 version it works (of course if there is no `"target": []` property set inside tasks.json) because in cmakeTools.ts there is `runBuild()` method which calls `updateDefaultTargetsInTaskProvider()` with currently target clean 
Currently there is nothing like that - so previously mentioned call to `vscode.commands.executeCommand("workbench.action.tasks.build");`)` triggers build task with target not set - thus default one is selected

Two questions from my side then:
- should I open separate issue ?
