### ISSUE TITLE
How to correctly set IntelliSense Mode in cpptools with cmake tools?

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cmake-tools#2743]
### Discussed in https://github.com/microsoft/vscode-cmake-tools/discussions/2740

<div type='discussions-op-text'>

<sup>Originally posted by **nedsociety** September 11, 2022</sup>
- vscode 1.71.0
- cmake tools 1.12.26
- c_cpptools 1.12.4

## Background

I'm using a custom toolchain file to cross-build Windows mingw binary from Linux clang.

Currently the toolchain file sets following:
```cmake
set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER "/usr/bin/clang-10" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/usr/bin/clang++-10" CACHE PATH "")
set(CMAKE_C_COMPILER_TARGET "i686-w64-mingw32")
set(CMAKE_CXX_COMPILER_TARGET "i686-w64-mingw32")
# --snip--
```

settings.json
```json
{
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
}
```

## Symptom

I hoped that it'll tell cpptools that I'm building a Windows binary, but IntelliSense is erroneously working in Linux mode. For example `__linux__` is defined everywhere when it shouldn't.

The C++ Log diagnostics says:
```
(include directories and defines are properly set as the toolchain file specified)

IntelliSense Mode: linux-clang-x64
```
which is not correct. 

How does the cmake-tools pass the triplet info to the cpptools? What should I do to fix it?</div>

**Comment by docbrown** [comment]
Same problem here when trying to use a Microchip XC16 toolchain:

```
set(XC16_PATH "/opt/microchip/xc16/v2.10")

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR "33EV256GM002")

set(CMAKE_C_COMPILER "${XC16_PATH}/bin/xc16-gcc")

set(CMAKE_FIND_ROOT_PATH "${XC16_PATH}")

# search for programs in the build host directories
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
If I use the auto-detected `pic30-elf` kit, Intellisense works fine. But when I use a toolchain file, VSCode searches in host paths for headers.
