### ISSUE TITLE
Debugger and application not starting

### ISSUE THREAD

**Issue by SeanOMik** [microsoft/vscode-cmake-tools#2744]
### Brief Issue Summary

I'm trying to debug a project but when I click the debug button, nothing happens. I took a look at the logs but it doesn't really seem like anything happens. I've tried gcc and clang and gdb and lldb-mi all with the same results.

### CMake Tools Diagnostics

```json
{
  "os": "linux",
  "vscodeVersion": "1.69.1",
  "cmtVersion": "1.12.27",
  "configurations": [
    {
      "folder": "/mnt/data_drive/Development/Cpp/SimpleEngine",
      "cmakeVersion": "3.22.3",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/run/current-system/sw/bin/clang",
        "CXX": "/run/current-system/sw/bin/clang++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log
https://gist.github.com/SeanOMik/a3899fa4f3b815ab89e3a9fac88302c4

### Additional Information

I took a look at the (non-debug) log file and it doesn't seem like it even tries to start and debug the program:
```
[main] Building folder: SimpleEngine dev_testing
[build] Starting build
[proc] Executing command: /nix/store/asp609pmpi09vlzdszhliffr65qppmy6-cmake-3.22.3/bin/cmake --build /mnt/data_drive/Development/Cpp/SimpleEngine/build --config Debug --target dev_testing --
[build] ninja: no work to do.
[build] Build finished with exit code 0
[proc] Executing command: /run/current-system/sw/bin/lldb-mi --version
[proc] Executing command: /run/current-system/sw/bin/lldb-mi --version
```

**Comment by bobbrow** [comment]
We're not sure what's happening here.  The only thing that stands out is some of the environment variables with really long values.  @WardenGnaw, do you know of any issues with running the debugger when there are a lot of environment variables or if they have really long values?

**Comment by WardenGnaw** [comment]
> do you know of any issues with running the debugger when there are a lot of environment variables or if they have really long values?
Yep, this is specific for lldb-mi. There is an open PR to fix it but the maintainers have not accepted it yet.

https://github.com/lldb-tools/lldb-mi/pull/87
