### ISSUE TITLE
[Update docs] Add CmakePresets.json to CMake QuickStart guide

### ISSUE THREAD

**Issue by sinemakinci1** [microsoft/vscode-cmake-tools#2745]
### Brief Issue Summary

Currently, there is no information or reference to CMakePresets.json in the CMake quick start guide in VS Code. This may lead to users unable to figure out how to start a project with Presets from this splash page.
https://code.visualstudio.com/docs/cpp/CMake-linux

This is a request to add this information to this documentation

**Comment by ArslanYM** [comment]
Can I work on this issue?

**Comment by sinemakinci1** [comment]
@ArslanYM Sure! If you want to open a PR with documentation changes our team can review it

**Comment by ArslanYM** [comment]
@sinemakinci1  I have a doubt , where exactly in the ` Get started with cmake tools on linux ` do you want me to add the link to the reference of CmakePresets.json. 
also im thinking about adding only the link to this reference : 
![micro](https://user-images.githubusercontent.com/104521101/226538487-6d32f28f-2fd0-49b8-a81a-03357348afd0.png)

Would that be enough?
