### ISSUE TITLE
Scan for kits erases the kit I entered

### ISSUE THREAD

**Issue by rnikander** [microsoft/vscode-cmake-tools#2762]
### Brief Issue Summary

The docs say you can run "Edit User-local CMake Kits" and edit the .json file and it won't be overwritten. But for me, I add a kit for Clang 15, like this:

```json
[
  {
    "name": "Clang 14.0.0 x86_64-apple-darwin22.1.0",
    "compilers": {
      "C": "/usr/bin/clang",
      "CXX": "/usr/bin/clang++"
    }
  },

  {
    "name": "Clang 15.0.1",
    "compilers": {
      "C": "/Users/rob/Dev/clang+llvm-15.0.1-x86_64-apple-darwin/bin/clang",
      "CXX": "/Users/rob/Dev/clang+llvm-15.0.1-x86_64-apple-darwin/bin/clang++"
    }
  }
]
```

But then it doesn't show up in the list when I click on "No active kit" at the bottom. And if I hit "Scan for Kits" it reverts the file and erases my entry for Clang 15.

**Comment by elahehrashedi** [comment]
In order to avoid the kit to be overwritten, you can add this setting to the kit definition:
`"keep": true`

**Comment by elahehrashedi** [comment]
You can also try using a new name for your kit:

```json
  {
    "name": "Clang 15.0.1 my copy",
    "compilers": {
      "C": "/Users/rob/Dev/clang+llvm-15.0.1-x86_64-apple-darwin/bin/clang",
      "CXX": "/Users/rob/Dev/clang+llvm-15.0.1-x86_64-apple-darwin/bin/clang++"
    }
  }
```

If you are modifying a kit that was already found during the scan process, when you re-scan, the content will be updated *(This is by design).

**Comment by rnikander** [comment]
Weird. I did this about 20 times the other day, trying to get it to work, and it would erase my Clang 15 entry every time, even though it had a new unique name. Now I can't reproduce the bug. I suspect the restart of Visual Studio cleared up something.
