### ISSUE TITLE
Move to vscode l10n

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/vscode-cmake-tools#2767]
The gulpfile still uses vscode-nls. But see if they can change it to use the new npm package.

**Comment by bobbrow** [comment]
What is the name of the package?
![image](https://user-images.githubusercontent.com/12818240/193695897-83929c32-9899-4e1a-849a-8b40dd147ec6.png)

**Comment by ChaseKnowlden** [comment]
![04 10 2022_15 16 24_REC](https://user-images.githubusercontent.com/46290258/193906512-357e6f20-540b-429b-8fc2-8e2fb7c394f2.png)

**Comment by ChaseKnowlden** [comment]
this is on npmjs.com

**Comment by ChaseKnowlden** [comment]
vscode L10n

**Comment by bobbrow** [comment]
Thanks.  It doesn't look like that API is ready for consumption and I don't see what it provides that is better than vscode nls right now.  We'll wait until the VS Code team tells us to move if this is the direction they want us to go.
