### ISSUE TITLE
Calling builds/clean/install/test from command palette always builds default target if useTasks option is set 

### ISSUE THREAD

**Issue by piomis** [microsoft/vscode-cmake-tools#2768]
### Brief Issue Summary

After changes introduced in 1.12 it is not possible to run commands from command palette or start targets from CMake Outline when useTasks option is active.
Using above methods will always just build target which is currently selected.

**Comment by elahehrashedi** [comment]
Thank you for reporting this bug. The setting "cmake.buildTask" is designed to run the build task only when the "Cmake: Build" command is run. For all the other commands such as install, clean, and run tests, the behavior should not change. I will close your PR and will send a PR to fix this issue:  https://github.com/microsoft/vscode-cmake-tools/pull/2770

**Comment by piomis** [comment]
The problem is that these other command implementation  does not work at all when option buildTask is active.
Due to condition inncmakeDriver even if target is clean, install or Test they trigger build task with target which is currently set as default.

**Comment by elahehrashedi** [comment]
`"cmake.buildTask"` is not designed to provide task options for commands other than build. Are you trying to use tasks to run `build`, `clean`, `install`,  etc... commands? I recommend ignoring this setting and using tasks directly: please take a look at this tutorial on how to start using tasks: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/tasks.md, ( you don't need to set this setting to use tasks).

> PS. I reviewed your changes. Behaviour of install, clean and test will change :) But in such way that they wont use tasks at all.

Correct, we want the behavior of the install, clean and test to stay the same.

**Comment by piomis** [comment]
The problem which I described above is mainly cased by fact that setting "useBuildTask" is checked in proc.execute (where complete cmake command is already prepared and target which is requested is not passed (as it has already been  included in command string).
However execute() function internally checks if useBuildTask is true and in case it is it just calls build task without passing any target - and this triggers build of currently selected target and not one which was really requested (see line 145 in proc.ts file)

**Comment by elahehrashedi** [comment]
I investigated this situation.
Let's separate the `command pallet` and `project outline` into two different issues:

We can keep this PR: https://github.com/microsoft/vscode-cmake-tools/pull/2770 to fix the clean, install and test tasks bug in the command palette.

And we can open a separate issue to fix running the task with proper targets when the build is calling from the `project outline`. A part of your PR can be used to fix that issue. However, in your PR, you are creating a new task that is based on the selected target, whilst the user might have a default build task for that target defined in the `tasks.json` (your fix currently ignores any tasks defined in `tasks.json`).

I suggest opening a new issue for `project outline` and when this PR  https://github.com/microsoft/vscode-cmake-tools/pull/2770 is checked in, you can send a new PR based on that fix. You won't need to provide any tasks for clean, test, and install. You just need to consider that when providing the task in your _findTasksForTargets you need to consider the tasks that are already defined in `tasks.json`. 

We highly appreciate your contribution.

**Comment by piomis** [comment]
OK - so please proceed with your PR and I will do changes and create new PR.

**Comment by elahehrashedi** [comment]
Here is a sample code on how to read tasks.json file in case you want to read it directly (This code is from C/C++ extension GitHub repository):

https://github.com/microsoft/vscode-cpptools/blob/f2311d7dba27870a6e57e26b078999d1d3b268e4/Extension/src/LanguageServer/cppBuildTaskProvider.ts#L218

**Comment by HofiOne** [comment]
Are there any builds that solve this issue correctly?

I too badly need to have the current build target that the `tasks.json` task is invoked for.
In my case, I'd like to add custom, different dependencies to each kind of target invocation based on the target kind.

Please confirm this (this is what I experience now and would like to know if I did something wrong or just this is the current  state.)

If `cmake.buildTask` is on and  there's more than one CMake Tools task in the `tasks.json` (e.g. one for build `"type": "cmake", "command": "build",` and one for clean `"type": "cmake", "command": "clean",` etc.)  then invoking CMake: Clean from the `command palette` 

### In the actual v1.12.27 Release version:
will invoke the `tasks.json` clean task version too, just will not pass the correct, actual build target to it (even `cmake.tasksBuildCommand` contains the `default` value)

### In the  latest v1.13.26 Pre-Release version:
will not call the `tasks.json` task at all (I guess now only for the build command it is invoked?!)



If this is the case (the worst scenario for me) could you please consider always calling the matching `tasks.json` CMake Tools task (based on the `"command":` key value) and passing the correct `cmake.buildTargetName` (and all the other parameters too) to the actually invoked task in `tasks.json`
It is not just what most of the users assume by default, but this is what would make `cmake.buildTask` actually useful!
Thank you in advance!

**Comment by piomis** [comment]
There is PR ongoing for this issue but still in progress.

Nevertheless few info based on your command:
- calling command pallete won't use tasks at all
- clean (both task and command) do not expect any target - that is how cmake works - clean in just a clean target nothing else
- if you have tasks in tasks.json (build type not clean) with specific target set you may use Run Task from Command Pallete - this should work

**Comment by HofiOne** [comment]
> There is PR ongoing for this issue but still in progress.

could you please sgare the PR link here?

> Nevertheless few info based on your command:
> 
>     * calling command pallete won't use tasks at all

I guess, excpet the build task case, am I right?

> 
>     * clean (both task and command) do not expect any target - that is how cmake works - clean in just a clean target nothing else
> 
>     * if you have tasks in tasks.json (build type not clean) with a specific target set you may use Run Task from Command Pallete - this should work

Even though that one is working (that's what I do know), but, as others suggested earlier too, it would be much, much more elegant, consistent, and clear if all the cases behaved the same way, so if `cmake.buildTask` is on the corresponding tasks would be called always with the updated, correct, actual `cmake.XXX` parameter values

Thanks for your reply!

**Comment by piomis** [comment]
Sorry looks that auto-correction changed my message during writing.
I meant "clean from command palette won't use tasks at all".

In regards to PR:
- one which disables tasks for clean, install, test #2770
- one related with building: #2780  (lined with issue:  #2778 )

**Comment by HofiOne** [comment]
> In regards to PR:
> 
>     * one which disables tasks for clean, install, test [avoid calling build tasks for "clean", "install" and "run tests" commands  #2770](https://github.com/microsoft/vscode-cmake-tools/pull/2770)

It's really bad news :(, this way it would be meaningless to use CMake Tools (at least for me)
I really loved the autogenerated commands, but I badly need a hook point on each command invocation, tasks did the trick up to now more or less (apart from the not actualized `cmake.XXX `parameter values)

> 
>     * one related with building: [Calling build targets from CMake Project Outline always builds default target if useTasks option is set #2780](https://github.com/microsoft/vscode-cmake-tools/pull/2780)  (linked with issue:  [Calling build targets from CMake Project Outline always builds default target if useTasks option is set bug #2778](https://github.com/microsoft/vscode-cmake-tools/issues/2778) )

But, It is a piece of good news, hope it will be fixed soon.
