### ISSUE TITLE
Debugging not hitting breakpoint

### ISSUE THREAD

**Issue by Riprock** [microsoft/vscode-cmake-tools#2771]
### Brief Issue Summary

I am just getting into C++ development and I am starting to learn about CMake. I am following [Vscode Documentation CMake on linux](https://code.visualstudio.com/docs/cpp/cmake-linux) and I was able to follow through, even though im on windows, and when I reach the debug point I set the breakpoint and run Cmake: Debug but the problem is that it opens up the file again in a weird way and doesnt hit the breakpoint yet the step through functions still work

This is the path of the file that gets open when debug is running. Going into the build folder then to the C drive back to the file
![image](https://user-images.githubusercontent.com/8990377/193939121-44fe370c-ef8b-4707-979a-0e81a063111f.png)
This is what it says about the file even though it does exist but the path is weird
![image](https://user-images.githubusercontent.com/8990377/193939189-57ca996d-b558-427c-88ae-645683b130e5.png)

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.71.2",
  "cmtVersion": "1.12.27",
  "configurations": [
    {
      "folder": "c:\\Users\\Riprock\\Documents\\test",
      "cmakeVersion": "3.24.2",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "C:/msys64/mingw64/bin/gcc.exe",
        "CXX": "C:/msys64/mingw64/bin/g++.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///c%3A/Users/Riprock/Documents/test/main.cpp"
    ],
    "responses": [
      {
        "uri": "file:///c%3A/Users/Riprock/Documents/test/main.cpp",
        "configuration": {
          "includePath": [],
          "defines": [],
          "compilerPath": "c:/msys64/mingw64/bin/g++.exe",
          "compilerArgs": [],
          "compilerFragments": [
            "-g"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 29,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Additional Information

What im finding weird is the path is build/C/Users/Riprock/Documents/test/main.cpp 
Its appending the full path to the end of the build directory

**Comment by bobbrow** [comment]
It sounds like something is wrong with the source mapping.  @WardenGnaw, is there something we can check to see what's going on here?

**Comment by WardenGnaw** [comment]
Is it possible to share the generated launch.json and the engine logs?

**Comment by Riprock** [comment]
There is no launch.json as I am doing ctrl + Shift + P and typing CMake: Debug as described here [Debug with Cmake](https://code.visualstudio.com/docs/cpp/cmake-linux#_debug-hello-world). I can attempt to generate one. 
I think that these are the logs that your looking for. If you need other information or if I got the wrong logs, please direct me to what I need to provide

```
variant] Loaded new set of variants
[kit] Successfully loaded 1 kits from C:\Users\Riprock\AppData\Local\CMakeTools\cmake-tools-kits.json
[proc] Executing command: C:\msys64\mingw64\bin\gcc.exe -v
[main] Configuring folder: test 
[proc] Executing command: C:\msys64\mingw64\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=C:\msys64\mingw64\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=C:\msys64\mingw64\bin\g++.exe -Sc:/Users/Riprock/Documents/test -Bc:/Users/Riprock/Documents/test/build -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: C:/Users/Riprock/Documents/test/build
[main] Building folder: test hello
[build] Starting build
[proc] Executing command: C:\msys64\mingw64\bin\cmake.EXE --build c:/Users/Riprock/Documents/test/build --config Debug --target hello --
[build] ninja: no work to do.
[build] Build finished with exit code 0
[proc] Executing command: C:\msys64\mingw64\bin\gdb.exe --version
[proc] The command: C:\msys64\mingw64\bin\gdb.exe --version exited with code: 1 and signal: null
[proc] Executing command: gdb --version
[main] Building folder: test hello
[build] Starting build
[proc] Executing command: C:\msys64\mingw64\bin\cmake.EXE --build c:/Users/Riprock/Documents/test/build --config Debug --target hello --
[build] ninja: no work to do.
[build] Build finished with exit code 0
[proc] Executing command: C:\msys64\mingw64\bin\gdb.exe --version
[proc] The command: C:\msys64\mingw64\bin\gdb.exe --version exited with code: 1 and signal: null
[proc] Executing command: gdb --version
```

**Comment by bobbrow** [comment]
The extension will log out the generated task if you set `cmake.loggingLevel` to `Debug`.  Look for `"Starting debugger with following configuration"` in the output window.

You can enable the debugger trace logging by adding the following setting:
```
"cmake.debugConfig": { 
  "logging": {
    "engineLogging": true,
    "trace": true
  }
}
```

**Comment by Riprock** [comment]
So Update, I set that value and ran these commands in MINGW64 and now Its running as expected
```
pacman -S --needed base-devel mingw-w64-x86_64-toolchain
pacman -Syu
```
