### ISSUE TITLE
Ninja is not detected in M1 Mac (Monterey)

### ISSUE THREAD

**Issue by KaungZawHtet** [microsoft/vscode-cmake-tools#2774]
### Brief Issue Summary

Ninja is not detected by cmake with this message 

`CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.`

Yes. I have already installed ninja with brew ( `brew install ninja` ).

### Debug Log

```shell
[main] Configuring folder: m1exp 
[proc] Executing command: /opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=/Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ "-S/Users/.../myProj" "-B/Users/.../myProj/build" -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeDetermineSystem.cmake:130 (message):
[cmake]   Could not find toolchain file:
[cmake]   /Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:2 (project)
[cmake] 
[cmake] 
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: /opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=/Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ "-S/Users/.../myProj" "-B/Users/.../myProj/build" -G Ninja exited with code: 1 and signal: null
```

### Additional Information

vcpkg is not installed because vcpkg doesn't work on Mac currently

**Comment by elahehrashedi** [comment]
can you run this command in the terminal and share the results with us? 

`/opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=/Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ "-S/Users/.../myProj" "-B/Users/.../myProj/build" -G Ninja`

**Comment by KaungZawHtet** [comment]
Yes, as u said, I run this cmd:
`/opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=/Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ "-S/Users/.../myProj" "-B/Users/.../myProj/build" -G Ninja`

this is the result :

```
Not searching for unused variables given on the command line.
CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeDetermineSystem.cmake:130 (message):
  Could not find toolchain file:
  /Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)
```

**Comment by bobbrow** [comment]
Our environment should match the VS Code terminal.  Just to double check, is `ninja` in your $PATH?

**Comment by KaungZawHtet** [comment]
`/opt/homebrew/bin/ninja` is the result on `which ninja`
`/opt/homebrew/bin/cmake` is the result on `which cmake`

**Comment by bobbrow** [comment]
I'm not sure why cmake reports that it can't find ninja.  If you set `CMAKE_MAKE_PROGRAM` to `/opt/homebrew/bin/ninja`, does it work for you?

**Comment by KaungZawHtet** [comment]
add ` set(CMAKE_MAKE_PROGRAM /opt/homebrew/bin/ninja)` in `CMakeLists.txt` and this is output

```
[main] Configuring folder: myProj 
[proc] Executing command: /opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=/Users/../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ "-S/Users/.../myProj" "-B/Users/.../myProj/build" -G Ninja
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/CMakeDetermineSystem.cmake:130 (message):
[cmake]   Could not find toolchain file:
[cmake]   /Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:3 (project)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: /opt/homebrew/bin/cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE:STRING=/Users/.../vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ "-S/Users/.../myProj" "-B/Users/.../myProj/build" -G Ninja exited with code: 1 and signal: null
```

this is my CMakeLists.txt. Simplest as ever

```
cmake_minimum_required(VERSION 3.0.0)
set(CMAKE_MAKE_PROGRAM /opt/homebrew/bin/ninja)
project(myProj VERSION 0.1.0)
add_executable(myProj main.cpp)
```

**Comment by bobbrow** [comment]
Ok, so it's not an incompatibility with your version of Ninja. Can you try adding this to your CMakeLists.txt and report on what it prints out?
```
message(STATUS "PATH=$ENV{PATH}")
execute_process(COMMAND which ninja.exe)
```

**Comment by KaungZawHtet** [comment]
It print 2 pieces of info :

`PATH=/Users/...:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/...:~/..../tools:/Library/Apple/usr/bin:/Users/.../.fig/bin:/Users/.../.local/bin`

`/opt/homebrew/bin/ninja`

**Comment by bobbrow** [comment]
Is that what prints out when you configure with the CMake Tools extension, or when you configure in your terminal?

**Comment by KaungZawHtet** [comment]
with CMake extension.

**Comment by KaungZawHtet** [comment]
cmake version : 3.24.2
ninja version : 1.11.1

**Comment by bobbrow** [comment]
Sadly, I'm out of ideas as to why CMake can't find Ninja for you if those commands inside your CMakeLists.txt work as expected.  The best I can give you right now is the workaround to include the `CMAKE_MAKE_PROGRAM` in your `cmake.configureSettings` setting:
```
  "cmake.configureSettings": {
    "CMAKE_MAKE_PROGRAM": "/opt/homebrew/bin/ninja"
  }
```

**Comment by KaungZawHtet** [comment]
It works now after I remove this `"CMAKE_TOOLCHAIN_FILE" : "\/Users\/...\/vcpkg\/scripts\/buildsystems\/vcpkg.cmake"` from `cmake.configureSettings`
The err message tells about Ninja but the problem is actually at vcpkg.
<img width="501" alt="Screen Shot 2022-10-12 at 10 41 27 PM" src="https://user-images.githubusercontent.com/15225530/195394340-806a8391-1ef3-4622-8309-c807166370f5.png">

**Comment by KaungZawHtet** [comment]
Nope, vcpkg works on M1 mac too. I misreading the facts. Thx for your reply. I think this issue can be closed now
