### ISSUE TITLE
[exthost] [error] Activating extension ms-vscode.cmake-tools failed due to an error:TypeError: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by nklacar** [microsoft/vscode-cmake-tools#2776]
### Environment

-OS Version: OSX
- VS Code: 1.71
- C/C++ extension:
- OS and version of remote machine (if applicable): Ubuntu 

### Bug Summary and Steps to Reproduce

Bug Summary:  Running cmake-tools extension in Dev Container fails

Steps to reproduce:
1. Use dev container
2. Install cmake tools in container 
4. Launch the dev container 
5. See error...

**Comment by bobbrow** [comment]
According to this stack trace, the extension is expecting either $HOME or $PROFILE to have a value in order to set a data directory.  Can you check the value of these environment variables in your devcontainer?

**Comment by nklacar** [comment]
The $HOME variable was missing. This fixed the issue. Thanks !
