### ISSUE TITLE
`cmake.cacheInit` does not respect absolute paths in environment variables

### ISSUE THREAD

**Issue by Atry** [microsoft/vscode-cmake-tools#2777]
## Reproducing steps

1. Set environment variable `CMAKE_INIT_CACHE` to an absolute path, e.g. `/tmp/my-init-cache.cmake`
2. Add the following setting in `settings.json`
   ``` json
   "cmake.cacheInit": "${env:CMAKE_INIT_CACHE}"
   ```
3. Click "Configure All Projects" button

I expect the file `/tmp/my-init-cache.cmake` will be used to initialize CMake cache. Unfortunately the following command is invoked:
```
cmake ... -C /home/my-user/my-workspace//tmp/my-init-cache.cmake ...
```

**Comment by elahehrashedi** [comment]
it looks like we are not expanding the path before we test if it is an absolute path.

Can you try using this setting and see if it works:
`"cmake.cacheInit": /tmp/my-init-cache.cmake`

**Comment by Atry** [comment]
The following setting works:
> ```
> "cmake.cacheInit": "/tmp/my-init-cache.cmake"
> ```

**Comment by Atry** [comment]
Workaround:

```
"cmake.cacheInit": "/${env:CMAKE_INIT_CACHE}"
```

then the following command will be executed:

```
cmake ... -C //home/my-user/my-workspace//tmp/my-init-cache.cmake ...
```
