### ISSUE TITLE
[bug] Presets with `$env{}` are not checked for circular references.

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-cmake-tools#2781]
### Brief Issue Summary

This issue is related to the [topic](https://discourse.cmake.org/t/how-to-write-a-proper-configurepreset-using-mingw-compilers-with-mingw-makefiles-generator/6615/5?u=hwhsu1231) I posted in CMake Discourse.

In short, it should **FAIL** to configure the project when using `$env{}` like the following example:

```json
"environment": {
  "PATH": "C:/msys64/mingw64/bin;$env{PATH}"
},
```

And it failed as I expected when operating in Terminal.

```cmd
F:\Git-Repo\cmake-project-template-conan>cmake --preset win32-gcc-x64-mingw-debug
CMake Error: Could not read presets from F:/Git-Repo/cmake-project-template-conan: Invalid macro expansion
```

However, it somehow could work with CMake Tools in Visual Studio Code. According to what [Kyle Edwards](https://discourse.cmake.org/u/kyle.edwards) said:

> The `$env{...`} macro is supposed to reference other environment variables within the environment map, or the environment inherited from the parent process if the corresponding variable doesn’t exist. The problem is that if `PATH` contains `$env{PATH}`, then it’s referencing itself, creating a circular dependency. The purpose of `$penv{...}` is to break this cycle by only using the environment inherited from the parent process. If `"PATH": "$env{PATH}"` works in VSCode then it sounds like they didn’t implement their preset support properly.

### Environments and Versions

- Visual Studio Code: **1.71.2**
- CMake Tools: **1.13.11**

### Screenshots

![2af6809a9d09c181f7bf52a7e48f5f1d1744b57f](https://user-images.githubusercontent.com/71438617/194700266-55eb4e8f-ccc8-4640-a92a-84af9c3c9e6f.gif)

**Comment by bobbrow** [comment]
It looks like we marked it as a warning instead of an error.

**Comment by qarni** [comment]
Related to #2934
