### ISSUE TITLE
Move the location of the "Build" button after "Targets in Preset"

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#2782]
### Brief Issue Summary

I think that placing "Build" after "Targets in Preset" will be a more logical layout:

![image](https://user-images.githubusercontent.com/3337419/194706887-bb1997ab-b2dc-4ad4-bccb-6075bb39e536.png)

What do you think?

**Comment by Zingam** [comment]
I'm thinking of a new order:

1. Active folder
2. Configure preset
3. Build preset
4. Default Build Target
5. Build
6. Launch Target
7. Debug
8. Launch

I'm not sure about the Test Preset location. 

Also in CMake 3.25.0 (Presets V6) we get:

> The [cmake-presets(7)](https://cmake.org/cmake/help/git-stage/manual/cmake-presets.7.html#manual:cmake-presets(7)) schema version has been bumped to 6.
>
>  The [cmake-presets(7)](https://cmake.org/cmake/help/git-stage/manual/cmake-presets.7.html#manual:cmake-presets(7)) format now supports a packagePresets field to specify presets for [cpack --preset](https://cmake.org/cmake/help/git-stage/manual/cpack.1.html#cmdoption-cpack-preset).
>
>  The [cmake-presets(7)](https://cmake.org/cmake/help/git-stage/manual/cmake-presets.7.html#manual:cmake-presets(7)) format now supports a workflowPresets field to specify presets for [cmake --workflow](https://cmake.org/cmake/help/git-stage/manual/cmake.1.html#cmdoption-cmake-workflow).

What about those? I feel that the status bar being used as a toolbar is becoming more and more inadequate.

**Comment by bobbrow** [comment]
The status bar for Kits has the build button on the left of the target.  I don't think we want to change it.

If it helps, we want to move stuff out of the status bar anyway and put it in the side panel with the project outline.  #1582

**Comment by Zingam** [comment]
(I would prefer if the stuff gets moved to the side panel.)

Yet let me suggest my new "order' for the new layout too. It also would make sense to have different layouts for different contexts, which are optimized for the specific workflow.

**Comment by elahehrashedi** [comment]
Can you add your suggestion in https://github.com/microsoft/vscode-cmake-tools/issues/1582 , when we have a design for it, we will share our proposal .
