### ISSUE TITLE
Revive Support for CMakeToolsAPI

### ISSUE THREAD

**Issue by go2sh** [microsoft/vscode-cmake-tools#2787]
Hi all,

there is still the file for the CMakeToolsAPI but the nothing is exported anymore. It would be great go get this feature back. Its really helpful for other extensions to get currently selected Projects/Preset/Target/etc. or to modify these. 

I see the old API is not multi-root capable but parts of it are still implemented. Would that be something, where you would accept a PR?

**Comment by bobbrow** [comment]
I believe @benmcmorran's team is starting to look at this and we'll have an implementation soon-ish?

We will be tracking this via #494, so I will close this as a duplicate.
