### ISSUE TITLE
Define buildfolders in cmake-variants.json

### ISSUE THREAD

**Issue by Wishmaster-de** [microsoft/vscode-cmake-tools#2788]
### Brief Issue Summary

It would be nice if we could specifiy inside the cmake-variants.json file a buildfolder. We are using different buildfolders like build_unittest and build_productive. Currently i think this is not possible in conjunction with cmake tools extension.

**Comment by bobbrow** [comment]
I think you should be able to do this.  See [Variant Substitution](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#variant-substitution).

Try something like:
```
  "cmake.buildDirectory": "${workspaceFolder}/build/${variant:FOO}"
```

**Comment by Wishmaster-de** [comment]
> I think you should be able to do this. See [Variant Substitution](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#variant-substitution).
> 
> Try something like:
> 
> ```
>   "cmake.buildDirectory": "${workspaceFolder}/build/${variant:FOO}"
> ```

Thanks Bob. This done it for me. Sometimes it is so easy. I searched a lot before but i was not able to find a soltuion.
