### ISSUE TITLE
Cache Editor UI  Button SAVE don't save to file    

### ISSUE THREAD

**Issue by mariuszmaximus** [microsoft/vscode-cmake-tools#2795]
### Brief Issue Summary

1) git clone https://github.com/DCMTK/dcmtk.git
2) open dcmtk in vscode 
3) click on bottom bar "CMake: [Debug]"
4) open "CMake Cache Editor" [UI]
5) find "DCMTK_MODULES"  and **clear value** 
6) press Button SAVE 

At this point we can't save any string value in "Cache Editor UI" 

I tested Windows 10/11 and Linux Ubuntu last 22.04 LTS

tested on last Release: v1.12.27
and Pre-Release: v1.13.13

**Comment by elahehrashedi** [comment]
Thank you for submitting this issue. We will investigate it.
