### ISSUE TITLE
clang (MSVC) kits should specify the 'ClangCL' toolset

### ISSUE THREAD

**Issue by fredemmott** [microsoft/vscode-cmake-tools#2810]
### Brief Issue Summary

Currently, the incorrect toolset 'host=amd64' is set (https://github.com/microsoft/vscode-cmake-tools/issues/2790) - as well as correcting 'amd64' to 'x64', `ClangCL` should be specified - e.g. `toolset: "ClangCL,host=x64"`

This makes `CMAKE_CXX_COMPILER_ID` and [`CMAKE_CXX_SIMULATE_ID`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_SIMULATE_ID.html) bepopulated correctly ('Clang' and 'MSVC' respectively, and the `MSVC` variable remains correctly set to 1)

For example:

```
[
  {
    "name": "Custom Clang-CL from MSVC 2022 x64",
    "visualStudio": "ee13335b",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 17 2022",
      "platform": "x64",
      "toolset": "ClangCL,host=x64"
    },
    "compilers": {
      "C": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\Llvm\\x64\\bin\\clang-cl.exe"
    }
  }
]
```

### Additional Information

Setting CMAKE_CXX_COMPILER_ID and CMAKE_CXX_SIMULATE_ID is useful to detect ClangCL within CMake; this is occasionally required when MSVC builds require a flag like `/await:strict` which errors with clang-cl.

**Comment by bobbrow** [comment]
Thank you for opening this issue.  We should fix this in the same PR as the fix for #2790.

**Comment by fredemmott** [comment]
Another related note is the `C` and `CXX` compiler specifications do not appear to do anything when using clang-cl - for example, if I specify:

```
    "compilers": {
      "C": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
    }
```

... or specify CMAKE_CXX_COMPILER by hand in the CMakeCache.txt, when using the visual studio generators, cmake will always use the Visual-Studio-bundled clang-cl instead of the one I tell it to.

**Comment by bobbrow** [comment]
> Another related note is the `C` and `CXX` compiler specifications do not appear to do anything when using clang-cl - for example, if I specify:
> 
> ```
>     "compilers": {
>       "C": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
>       "CXX": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
>     }
> ```
> 
> ... or specify CMAKE_CXX_COMPILER by hand in the CMakeCache.txt, when using the visual studio generators, cmake will always use the Visual-Studio-bundled clang-cl instead of the one I tell it to.

I opened a separate issue for this feedback since I already have a PR open for the original comment.
