### ISSUE TITLE
Cannot append to PATH variable from CMakePresets in a userspace installation on Windows

### ISSUE THREAD

**Issue by ToBoMi** [microsoft/vscode-cmake-tools#2813]
I try to add a directory to the path in `CmakePresets.json` like so:
```
        "environment": {
          "PATH": "wherever/ninja/bin;$penv{PATH}"
        }
```
There is nothing appended to the path when I print it from `CMakeLists.txt`.

vscode is a userspace installation without elevated/administrative rights.

Appending to an environmental variable in general works:
```
        "environment": {
          "HOME": "wherever/ninja/bin;$penv{HOME}"
        }
```
Prints the appended string to the `HOME` variable.

I can change the `PATH` variable from the plain command line (Batch) without elevated user rights for the running session with:
`set PATH=mytest/;%PATH%`
That works, too.

Why is changing the `PATH` variable not possible from `CmakePresets.json` in vscode?

I made a very small example that reproduces the error. (Has to be used inside a userspace installation of vscode)
[setUserPathFromCMakePresets.zip](https://github.com/microsoft/vscode-cmake-tools/files/9837746/setUserPathFromCMakePresets.zip)

**Comment by bobbrow** [comment]
I'm not 100% sure what you mean by "userspace installation" of vscode, but I run non-elevated and this works for me.  It prints the updated PATH when I configure.

Can you try installing the latest pre-release version (1.13.17) and set the `cmake.loggingLevel` setting to `"debug"`.  Then share the output of the configure command - it will print out the environment we used when invoking CMake.

**Comment by ToBoMi** [comment]
> I'm not 100% sure what you mean by "userspace installation" of vscode

Yes I mean I use a non-elevated installation.

I cannot share the exact output of the environment, because it contains sensible information of the company.
I hope it is enough answer questions about the debug output.

I reproduced this issue in the pre-release version.
I can already say that the debug output does not show the updated `PATH` in the `CMake/Build` log. (I searched for the term `wherever` (this term used in the example) in the log and it was **not** found in a `PATH` variable)
It was found for the `HOME` variable, though.

I hope this helps.
What does it tell us, when the `PATH` environment that is used when invoking CMake does not contain the updated `PATH`?

**Comment by ToBoMi** [comment]
In other words:
In the debug log, the environment (From the log I think it is the line `[proc]   with environment: [...]`) with which `vscode-cmake-tools` was called looks "normal". The `PATH`  and `HOME` variables both look normal. Nothing is added to them and both look good. They don't have any additions to them.

**Comment by bobbrow** [comment]
> In other words: In the debug log, the environment (From the log I think it is the line `[proc] with environment: [...]`) with which `vscode-cmake-tools` was called looks "normal". The `PATH` and `HOME` variables both look normal. Nothing is added to them and both look good. They don't have any additions to them.

When you say the `PATH` looks normal do you mean it does not include `wherever/ninja/bin`?  I'm confused because you say it looks good, but if it's missing the path you wanted to add, then to us that would not look good.  It would be a bug.

**Comment by ToBoMi** [comment]
Can you tell me if this is a bug then? I would like to know how I can proceed here.

**Comment by ToBoMi** [comment]
Ah.
I wanted to test this on another machine in the organisation, but that VSCode does not output the environmental variables when I setup `vscode-cmake-tools` to debug logging. It just shows that

`[proc] Executing command: "[...]CMake\bin\cmake.EXE"`

and not 

`[proc]   with environment: [...], "Path"[...]`

It is a portable installation just extracted from an archive.

Should this work? I cannot find an issue for this. Is there something else to setup debug logging?

**Comment by ToBoMi** [comment]
> ... and you have to have version 1.13.17 (pre-release) or higher installed.

Ah - debug logging only works in the pre-release - got it.

On the other machine in my org I see the same behavior as in [my first comment](https://github.com/microsoft/vscode-cmake-tools/issues/2813#issue-1418054371) with the portable installation.

I use vscode
``` 
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

**Comment by bobbrow** [comment]
I also tried the portable installation right now and this still works for me.  I'm not sure what's different between your environment and mine.

Can you run the `CMake: Log Diagnostics` command and share the output?
Can you share the contents of your `.vscode/settings.json` file and also your global settings?

**Comment by ToBoMi** [comment]
I can share the user settings. I have this issue in the minium example I shared and there are no workspace settings defined

<details>
  <summary>User settings</summary>

```json

{
    "workbench.colorTheme": "Default Light+",
    "clangd.path": "c:\\Users\\[...]\\AppData\\Roaming\\Code\\User\\globalStorage\\llvm-vs-code-extensions.vscode-clangd\\install\\15.0.3\\clangd_15.0.3\\bin\\clangd.exe",
    "clangd.checkUpdates": true,
    "editor.inlayHints.enabled": "offUnlessPressed",
    "C_Cpp.intelliSenseEngine": "Disabled",
    "terminal.integrated.scrollback": 5000,
    "python.defaultInterpreterPath": "\"C:\\Anaconda3\\python.exe\"",
    "files.autoGuessEncoding": true,
    "idf.gitPathWin": "C:\\Users\\[...]\\.espressif\\tools\\idf-git\\2.30.1\\cmd\\git.exe",
    "idf.espIdfPathWin": "c:\\Users\\[...]\\swdev\\esp-idf",
    "idf.pythonBinPathWin": "C:\\Users\\[...]\\.espressif\\python_env\\idf4.3_py3.8_env\\Scripts\\python.exe",
    "idf.toolsPathWin": "C:\\Users\\[...]\\.espressif",
    "idf.customExtraPaths": "C:\\Users\\[...]\\.espressif\\tools\\xtensa-esp32-elf\\esp-2020r3-8.4.0\\xtensa-esp32-elf\\bin;C:\\Users\\[...]\\.espressif\\tools\\xtensa-esp32s2-elf\\esp-2020r3-8.4.0\\xtensa-esp32s2-elf\\bin;C:\\Users\\[...]\\.espressif\\tools\\xtensa-esp32s3-elf\\esp-2020r3-8.4.0\\xtensa-esp32s3-elf\\bin;C:\\Users\\[...]\\.espressif\\tools\\riscv32-esp-elf\\1.24.0.123_64eb9ff-8.4.0\\riscv32-esp-elf\\bin;C:\\Users\\[...]\\.espressif\\tools\\esp32ulp-elf\\2.28.51-esp-20191205\\esp32ulp-elf-binutils\\bin;C:\\Users\\[...]\\.espressif\\tools\\esp32s2ulp-elf\\2.28.51-esp-20191205\\esp32s2ulp-elf-binutils\\bin;C:\\Users\\[...]\\.espressif\\tools\\cmake\\3.16.4\\bin;C:\\Users\\[...]\\.espressif\\tools\\openocd-esp32\\v0.10.0-esp32-20210401\\openocd-esp32\\bin;C:\\Users\\[...]\\.espressif\\tools\\ninja\\1.10.2;C:\\Users\\[...]\\.espressif\\tools\\idf-exe\\1.0.1;C:\\Users\\[...]\\.espressif\\tools\\ccache\\3.7;C:\\Users\\[...]\\.espressif\\tools\\dfu-util\\0.9\\dfu-util-0.9-win64;C:\\Users\\[...]\\.espressif\\tools\\idf-python-wheels\\idf4.3_py3.9_2021-01-07",
    "idf.customExtraVars": "{\"OPENOCD_SCRIPTS\":\"C:\\\\Users\\\\[...]\\\\.espressif\\\\tools\\\\openocd-esp32\\\\v0.10.0-esp32-20210401/openocd-esp32/share/openocd/scripts\",\"IDF_CCACHE_ENABLE\":\"1\"}",
    "cmake.loggingLevel": "debug"
}

```

</details>

Here is the output of


<details>
  <summary>CMake: Log Diagnostics</summary>

```

{
  "os": "win32",
  "vscodeVersion": "1.73.0",
  "cmtVersion": "1.13.21",
  "configurations": [
    {
      "folder": "c:\\Users\\[...]\\Downloads\\cmake-3.25.0-rc2-tutorial-source\\setUserPathFromCMakePresets",
      "cmakeVersion": "3.20.21032501",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "C:/DevApps/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x86/cl.exe",
        "CXX": "C:/DevApps/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x86/cl.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}


```

</details>

**Comment by Flashs** [comment]
Had the same issue today. Are there any updates on this?

**Comment by gcampbell-msft** [comment]
@ToBoMi @Flashs Could you confirm that this issue is now fixed? We have done some work recently to fix these issues, and this issue should be fixed. Thanks!

**Comment by ToBoMi** [comment]
In the insiders build I set `"cmake.loggingLevel": "debug"` and added

```
message("-------------------------------------------------------")
message("Current PATH is: $ENV{PATH}")
message("-------------------------------------------------------")

message("-------------------------------------------------------")
message("Current HOME is: $ENV{HOME}")
message("-------------------------------------------------------")
```

to the `CMakeLists.txt` and

```
      "environment": {
        "PATH": "bogus/stuff;$penv{PATH}",
        "HOME": "bogus/stuff;$penv{HOME}"
      }
```
to the `CMakePresets.json`.

When I use the configure function from CMakeTools to start the cmake configuration I cannot find the text `bogus/stuff` in the whole output of CMake configure.
