### ISSUE TITLE
Clang Kits always use the Visual Studio bundled version

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#2814]
Another related note is the `C` and `CXX` compiler specifications do not appear to do anything when using clang-cl - for example, if I specify:

```
    "compilers": {
      "C": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
    }
```

... or specify CMAKE_CXX_COMPILER by hand in the CMakeCache.txt, when using the visual studio generators, cmake will always use the Visual-Studio-bundled clang-cl instead of the one I tell it to.

_Originally posted by @fredemmott in https://github.com/microsoft/vscode-cmake-tools/issues/2810#issuecomment-1287437440_

**Comment by fredemmott** [comment]
For context, the reason I care about this is that the Xaml compiler is currently only supported via msbuild, so I need to use an msbuild-based generator - but I'd like to use clang for the better error messages, especially for templates and C++20 `concept`s

**Comment by gcampbell-msft** [comment]
@fredemmott Does this issue still reproduce for you? Our apologies for how long this issue has been open, but we'd like confirmation about whether this issue is still blocking you before we add it to our backlog for the next milestone. Thanks!

**Comment by gcampbell-msft** [comment]
Closing this issue as stale, please open a new issue if you still are facing issues. Thanks!
