### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fowlertADSK** [microsoft/vscode-cmake-tools#2816]
- Issue Type: `Performance`
- Extension Name: `cmake-tools`
- Extension Version: `1.12.27`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.72.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/timfo/AppData/Local/Temp/ms-vscode.cmake-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
[ms-vscode.cmake-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-cmake-tools/files/9852002/ms-vscode.cmake-tools-unresponsive.cpuprofile.txt)

**Comment by elahehrashedi** [comment]
Meanwhile, Is it possible for you to share the project if it is open source? We can use your project to reproduce the issue.

**Comment by bobbrow** [comment]
If you can also let us know what you were doing when this happened, that might help us understand why the extension is spending so much time in the code model update.  It looks like the code model was updated several times in a short period of time which is why the CPU was used so much.  It's not immediately obvious from looking at the code why this would happen.  If you can set the `cmake.loggingLevel` setting to `"debug"` and share the log if this happens again, that would give us more information that could possibly point to a solution to this problem.

**Comment by fowlertADSK** [comment]
I let VS Code log this issue and included the file it generated after it hung while I was searching for a file.  i.e. Ctrl-P...type in a name...a few minutes later I got a message saying that something took too long.

In general, I've been having problems with cpptools taking way too long to do things.  e.g. my application seems to be taking forever to start up, I check the Task Manager and I see something like 100 separate processes parsing files, which I assume is contributing to how slow things are running.    My project is not open source and I can't share it.

**Comment by bobbrow** [comment]
This particular problem doesn't appear to be with cpptools.  It appears to be with CMake Tools.  Can you share a screenshot of task manager or tell us which process has so many copies of itself running?  We shouldn't ever have that many processes running unless they're left over from a previous session that didn't shut down properly.

If you can also run and share the output from the `CMake: Log Diagnostics` command, it might give us a sense of how big a project we're working with too.

**Comment by fowlertADSK** [comment]
I deleted a bunch of file names from my cmake log and here's what is left.
[cmake_log.txt](https://github.com/microsoft/vscode-cmake-tools/files/9854383/cmake_log.txt)
