### ISSUE TITLE
cmake --version spam in output logs

### ISSUE THREAD

**Issue by bachittle** [microsoft/vscode-cmake-tools#2818]
### Brief Issue Summary

when using cmake tools, I get lots of spam which all it does is execute cmake --version. It clutters the actual useful commands of the cmake build process.

![image](https://user-images.githubusercontent.com/39804642/197804602-f9346a2e-4181-434f-be88-909eb87aee73.png)

**Comment by bobbrow** [comment]
Thanks for reporting this. We have a PR out to reduce the spam.
