### ISSUE TITLE
Improve Project Outline in Multi Project 

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cmake-tools#2823]
The project outline needs to be improved when having multiple projects and multiple workspaces.

**Comment by Zingam** [comment]
What about creating a main issue which lists all the sub-issues related to the project outline?

I think there are a bunch of posted issues related to the project outline.

**Comment by elahehrashedi** [comment]
1. Update `setActiveProject` function in `src\projectOutlineProvider.ts`
