### ISSUE TITLE
Linking problem if there is a space in the path name of the source files.

### ISSUE THREAD

**Issue by AJM-DSC** [microsoft/vscode-cmake-tools#2838]
Type: <b>Bug</b>

I am using VS to compile code for STM32 microcontrollers. My environment is VS, CMAKE, ninja and ARM tools. I noticed that in case the path to the source files directory contains a space in the name (Windows), CMake badly builds the task for the linker, does not put the path in quotation marks. 
Eg. for CMake task description:
e:/SEGGER Embedded Studio for ARM Projects/AJM_test/firmware/src/CMakeLists.txt
The job description for the linker looks like this:
...-Xlinker --gc-sections -LE:/SEGGER Embedded Studio for ARM Projects/AJM_test/firmware/src/../ldscripts/ --specs=nano.specs ...
As a result, the linker does not find its parameters description and the job ends with an error. The workaround is to replace all spaces in the path name with, for example, "_" or map the path as a drive (in my case, Z: \ == E: \ SEGGER Embedded Studio for ARM Projects \).

Extension version: 1.12.27
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.88GB (5.30GB free)|
|Process Argv|Z:\\AJM_test\\firmware\\src\\CMakeLists.txt --crash-reporter-id 5d768ecb-b580-4fdc-b89c-9d400fca1231|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by elahehrashedi** [comment]
Are you able to reproduce this issue on the command line as well? or do you reproduce this issue only when using VS Code and CMake Tools extension?

**Comment by AJM-DSC** [comment]
Hi,

 

I didn't use (even try) the command line. I noticed a problem trying to build the program from VS Code, 

CMake was installed as a Tool extension.

 

Andrzej
