### ISSUE TITLE
Possibly related: argc=1 even after specifying args in launch.json in VS code

### ISSUE THREAD

**Issue by AurusHuang** [microsoft/vscode-cmake-tools#2839]
### Brief Issue Summary

The issue appears when I'm using RelWithDebInfo as building variant. Details are here: 
https://github.com/microsoft/vscode-cpptools/issues/10086
It doesn't seem to appear when I choose Debug or Release.

**Comment by bobbrow** [comment]
If only 1 arg is passed, I would suspect that means that your `launch.json` was not used (e.g. you're using the CMake Tools run/debug buttons which don't look at launch.json).  We can test this theory by having you set the `cmake.debugConfig` setting as follows:
```json
  "cmake.debugConfig": {
            "args": [
                "/abs/path/to/file1",
                "/abs/path/to/file2",
                "/abs/path/to/file3"
            ]
  }
```
This will add args to the process launch command generated by the CMake Tools run/debug buttons.

**Comment by AurusHuang** [comment]
Where should I insert them? I tried several locations but no luck.

**Comment by AurusHuang** [comment]
Solved. Looks like the ladybug button on the bottom status bar is not the right option to start a debug with arguments. I should press F5 instead.

**Comment by bobbrow** [comment]
Correct. The debug button in the status bar runs through our extension. It does not look at your `launch.json` file.

**Comment by AurusHuang** [comment]
I suggest that your team work on having it run with launch.json, because the buttons on status bar seems too natural to be a workflow.

发自我的iPhone

在 2022年11月4日，23:47，Bob Brown ***@***.***> 写道：

﻿

Correct. The debug button in the status bar runs through our extension. It does not look at your launch.json file.

**Comment by bobbrow** [comment]
The buttons on the status bar will be removed in a future update. #1582
