### ISSUE TITLE
Pass command line arguments for "Run Without Debugging"

### ISSUE THREAD

**Issue by SineStriker** [microsoft/vscode-cmake-tools#2846]
### Brief Issue Summary

When I tried to use "cmake.debugConfig" and pass argument to the target, I found the CMake Tool cannot parse the escape variables such as `${workspaceFolder}`, it's a trouble when I need to pass a relative path of a file to a target.

**Comment by bobbrow** [comment]
Can you share your settings?  This works for me.
```
  "cmake.debugConfig": {
    "args": [ "${workspaceFolder}" ]
  }
```

**Comment by SineStriker** [comment]
> Can you share your settings? This works for me.
> 
> ```
>   "cmake.debugConfig": {
>     "args": [ "${workspaceFolder}" ]
>   }
> ```

Similar to yours, when I apply such configuration but the escape variable won't expand.

**Comment by bobbrow** [comment]
Unfortunately, we don't have enough information to investigate this and it works for us.  If your repo is open source, can you share a link?  If you have a small project that reproduces this, can you zip it up and attach it to this issue?

**Comment by bobbrow** [comment]
Ah ok.  I see the problem.  Thanks.
