### ISSUE TITLE
Disable or Remove the [scan for tools] function

### ISSUE THREAD

**Issue by ZZH-Finzlize** [microsoft/vscode-cmake-tools#2859]
Type: <b>Bug</b>

I have a lot of toolchains in my cmake-tools-kits.json file, all of them are configured by my self, but, I don`t know why the cmake tools just scan tools automaticly today, that action destroy all my tools configurations. now I have nothing in my cmake-tools-kits.json

Extension version: 1.12.27
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|39.68GB (23.89GB free)|
|Process Argv|D:\\proj\\signal-test-box\\tiny-signal-box.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bobbrow** [comment]
I'm sorry if you lost your kits.  We tried to document it here: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md.  I think it would be better to warn if kits will be deleted.

It is intended that you create a local kits file in your .vscode folder for the workspace. Those are safe from scans.

**Comment by ZZH-Finzlize** [comment]
Another problem is that dose the cmake tools support define RC compiler manually? I know it can define C and CXX compiler, if I need to using RC files to add an icon for my binary file,so I need to tell cmake where to find the correct version of RC compiler. Because every kit will contains a RC compiler, but cmake will use the first one it find in the PATH variable, that one may not match the C/CXX compiler, so i have to define CMAKE_RC_COMPILER variable in my CMakeLists.txt file, this will cause a problem when I switching to another kit.

**Comment by bobbrow** [comment]
You can set everything you want if you use `CMakePresets.json` instead of Kits.  ([Official Documentation](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html))

**Comment by ZZH-Finzlize** [comment]
Thanks, it is helpful to me
