### ISSUE TITLE
can't add custom configure args when using presets

### ISSUE THREAD

**Issue by dvirtz** [microsoft/vscode-cmake-tools#2860]
### Brief Issue Summary

I'd like to add a `--trace` argument to CMake configure but the code at https://github.com/microsoft/vscode-cmake-tools/blob/e7ed1b7dcd0f371cb84855d18417978b54500b9e/src/drivers/cmakeDriver.ts#L1295-L1305 only reads the `cmake.configureArgs` setting when not using presets.
I don't see a reason why not let the user add command line arguments even when using presets.

**Comment by elahehrashedi** [comment]
We are considering re-enabling this feature, alongside this feature request: https://github.com/microsoft/vscode-cmake-tools/issues/1836

**Comment by seppeon** [comment]
I would like to second this feature, for a similar reason, with the addition of `--debug-output`, another related issue is that `Cmake: Enable Trace Logging` is also ignored.

**Comment by gcampbell-msft** [comment]
This should be resolved by #3537. Marking this as `fixed-pending-release`, could you confirm that this fixes your issue? 

Additionally, we plan to add support for CMake Presets v7 and v8 in 1.18, which has `trace` support.

**Comment by dvirtz** [comment]
Thanks for the fix. I'm not working with CMake presets currently, so I won't be able to verify.
