### ISSUE TITLE
Add support for CMake Presets v6

### ISSUE THREAD

**Issue by mathisloge** [microsoft/vscode-cmake-tools#2871]
### Brief Issue Summary

With CMake 3.25 there are now package and workflow presets. 
It would be good as a first step to just accept them. 

https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

**Comment by Kuxe** [comment]
Just having

```
"workflowPresets": [
  {
    [...]
  }
}
```

breaks `vscode-cmake-tools` - it can't find configure and build presets anymore.

The [most current documentation](https://github.com/microsoft/vscode-cmake-tools/blob/903aad3/docs/cmake-presets.md#supported-cmake-and-cmakepresetsjson-versions) is misleading
> The CMake Tools extension supports version 2 or later for the CMakePresets.json and CMakeUserPresets.json files.

since version 6 is not supported.

**Comment by nolange** [comment]
> breaks `vscode-cmake-tools` - it can't find configure and build presets anymore.

This annoys me too, can we get a quick fix ignoring unknown properties please?
Kinda like a less strict mode if the presets `version` is higher than the last one supported.

**Comment by vdilecce** [comment]
> > breaks `vscode-cmake-tools` - it can't find configure and build presets anymore.
> 
> This annoys me too, can we get a quick fix ignoring unknown properties please? Kinda like a less strict mode if the presets `version` is higher than the last one supported.

Having a CMakePresets.json file with unknown properties (e.g. higher version) breaking the extension behavior is indeed annoying. Currently it's either presets v6 new features or a proper VS Code developing experience.

If the support for presets version 6 cannot be included in 1.13 (the release of which I assume is not too distant in the future), I also would be happy with a (quick?) fix to ignore what's unknown in CMakePresets.json.

**Comment by bobbrow** [comment]
> If the support for presets version 6 cannot be included in 1.13 (the release of which I assume is not too distant in the future), I also would be happy with a (quick?) fix to ignore what's unknown in CMakePresets.json.

Unfortunately, presets version 6 will not be in 1.13.  But thanks for the reminder on ignoring unknown properties.  I added a new setting to ignore unknown properties/macros for unsupported versions in this PR which we will take for 1.13 #2945.  `cmake.allowUnsupportedPresetsVersions`

**Comment by vdilecce** [comment]
> I added a new setting to ignore unknown properties/macros for unsupported versions in this PR which we will take for 1.13 #2945. `cmake.allowUnsupportedPresetsVersions`

Thank you for your quick feedback, much appreciated!

**Comment by sinemakinci1** [comment]
Also add support for v7 and v8
