### ISSUE TITLE
Any reference to ${command:cmake.getLaunchTargetPath} will reconfigure after a cmake configure task

### ISSUE THREAD

**Issue by trondhe** [microsoft/vscode-cmake-tools#2878]
### Brief Issue Summary

Running a configure task such as
``` json
{
    "label": "cmake configure",
    "type": "cmake",
    "command": "configure",
    "preset": "${command:cmake.activeConfigurePresetName}",
},
```
to completion, build with
``` json
{
  "label": "cmake build",
  "type": "cmake",
  "command": "build",
  "preset": "${command:cmake.activeConfigurePresetName}",
  "targets": [
      "${command:cmake.buildTargetName}"
  ],
}
```
a follow up with
``` json
{
    "label": "cmake run target",
    "type": "shell",
    "command": "${command:cmake.getLaunchTargetPath}",
    "dependsOn": "cmake build",
},
```
will always reconfigure.

It seems that the `command:cmake.<vars>` state are not saved/fetched when using a cmake configure task. Such that the extension itself need to load it by doing a configure for itself.  
Deleting the build folder, configuring, building and running the `cmake run target` task directly after this does _not_ make it reconfigure a second time, which I guess perhaps is also wrong?
If one does `Ctrl+shift+p` -> `Developer: Reload window` after the project is fully configured and built, the `cmake run target` task will make the cmake tools extension reconfigure again.

**Comment by elahehrashedi** [comment]
Thank you for reporting this issue. We will take a look into it.

**Comment by gcampbell-msft** [comment]
@trondhe Following up on this. Are you still able to reproduce this issue? If so, could you please help us repro by providing an example/repro project? 

Looking forward to investigating this.

**Comment by trondhe** [comment]
I am not sure if something changed since last time, not sure it behaves quite the same as before. However there is still a common (to me) flow that often happens.
It seems to be problematic to me as vcpkg often forces reconfigures (a problem on its own outside of this of course). But it seems to be triggered via something this extension might be able to avoid I hope.

This order of sequence will always end up re-configuring twice for me:
- Ensure an existing project configure step has been run
- (Re)open vscode (or `Developer: Reload Window` from command palette)
- Do any change that will trigger a reconfigure (edit cmake, vcpkg needs (aka in some cases even the path variable changed etc)
- Run a "run binary shell command" using `${command:cmake.getLaunchTargetPath}` that depends on a task of type `cmake` with `build`as command
- Now it reconfigures first on the terminal, and then another time in the extension before the build command is run and executed.

This simple project gives a reproducible setup running the `_cmake run target` task after the reload and a change that requires reconfigure has been applied

```json
// .vscode/tasks.json
{
	"version": "2.0.0",
	"windows": {
		"options": {
			"shell": {
				"executable": "powershell.exe"
			}
		}
	},
	"tasks": [
		{
			"label": "_cmake configure",
			"type": "cmake",
			"command": "configure",
			"preset": "${command:cmake.activeConfigurePresetName}",
		},
		{
			"label": "_cmake build",
			"type": "cmake",
			"command": "build",
			"preset": "${command:cmake.activeConfigurePresetName}",
			"targets": [
				"${command:cmake.buildTargetName}"
			],
		},
		{
			"label": "_cmake run target",
			"type": "shell",
			"command": "${command:cmake.getLaunchTargetPath}",
			"dependsOn": "cmake build",
		},
	]
}
```


```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.20)

project(test)

add_executable(mybin main.cpp)

set(seconds 3)
message("Intentionally sleeping for ${seconds} seconds to slow down configure step")
foreach(i RANGE 1 ${seconds})
    message("${i} sec")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 1)
endforeach()
```
```json
// CMakePresets.json
{
    "version": 6,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 23,
        "patch": 0
    },
    "configurePresets": [
        {
            "name": "default",
            "displayName": "Default Config",
            "description": "Default build using Ninja generator",
            "generator": "Ninja",
            "binaryDir": "${sourceDir}/build/default"
        }
    ],
    "buildPresets": [
        {
            "name": "default",
            "configurePreset": "default"
        }
    ]
}
```

```cpp
// main.cpp
#include <iostream>

int main() {
  std::cout << "Hello, World!\n";
  return 0;
}
```

**Comment by trondhe** [comment]
More direct breakage which I think was my original problem:

Same initial steps to the problem
- Have a configured build setup
- Reopen or reload vscode
- Edit a cmakelist file
- run the task `_cmake configure`, it will now configure
- run the task `_cmake run target`, it will not configure again

**Comment by gcampbell-msft** [comment]
@trondhe Do you have any automatic configuring settings turned on? For example: `cmake.automaticReconfigure`, `cmake.configureOnEdit`, `cmake.configureOnOpen`. I'm not able to reproduce your issue right now. I'm finding that it behaves as expected where it simply runs the most recent build and runs the target. 

Thanks for any information that could help. Running `CMake: Log Diagnostics` may provide helpful information

**Comment by gcampbell-msft** [comment]
Here is a video of me attempting your repro and everything behaving as expected. 

Thanks for all of your information!

![Repro](https://github.com/microsoft/vscode-cmake-tools/assets/86264750/c1d55b3e-0e57-4c46-b1de-55b536248075)

**Comment by trondhe** [comment]
Its because it automatically has already configured it for you via the extension.
I dont have automatically reconfigure on and when I invoke a task that is specifically `cmake` and `configure` as shown as my tasks, this should instruct the extension as I would understand to do the configure, so it should know about it, but it still reconfigures.

Here is a video (btw snipping tool is awesome, just wish it could set a output export size) that shows how it reconfigures twice.

https://github.com/microsoft/vscode-cmake-tools/assets/7525911/478a3407-bc07-4a80-a204-fe325567a2f0

**Comment by gcampbell-msft** [comment]
I successfully am able to reproduce now. I will investigate the issue. Thanks for helping me get the repro!
