### ISSUE TITLE
Allow setting environment variables via shell/cmd script

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vscode-cmake-tools#288]
It would be great to have support for setting environment variables via a script in addition to the current name-value lists (i.e. `cmake.environment`). This would help building against third-party libraries relying on shell/batch scripts to prepare the build environment (e.g., _Intel Performance Libraries_ - each library exposes a .sh/.bat script which sets relevant environment variables).

**Comment by vector-of-bool** [comment]
Sounds useful.

What sort of design/UX would you like to see?

**Comment by emptyVoid** [comment]
I'm not really sure how it's usually done, though I was thinking about something like this:
```js
    "cmake.environmentScript": "source ${workspaceRoot}/path/to/script.sh"
```
and on Windows:
```js
    "cmake.environmentScript": "${workspaceRoot}\\path\\to\\script.bat"
```

**Comment by KoeMai** [comment]
Do you need the script only in the build step or in the configure step of Cmake?

I would prefer a preConfigure and preBuild Script step. 
Is this script step multiproject specific, project specific, variant specific or kit specific?

**Comment by vector-of-bool** [comment]
I almost feel like this is getting close to the idea of another Kit type. The VS kits are generated in a similar manner (by invoking the vcvars batch files and collecting environment variables). Perhaps it belongs there?

**Comment by emptyVoid** [comment]
> Do you need the script only in the build step or in the configure step of Cmake?

Actually all of them:
- in the configure step: to detect the presence of a third-party library (e.g., _Intel Performance Libraries_ set `<LIB>ROOT` environment variables)
- in the build step: to pick up correct paths and/or compiler flags (e.g., _Intel Performance Libraries_ set `CPATH`/`INCLUDE` and `LIBRARY_PATH`/`LIB` environment variables)
- in the test step and debug: to launch an application built against a third-party library  (e.g., _Intel Performance Libraries_ set `LD_LIBRARY_PATH`/`PATH` environment variables)

**Comment by KoeMai** [comment]
I think the ```environmentPreparationScript``` belongs to the kits.  It is a additional preparation step before cmake is running. May be it needs to be added to each kit,  because it is not a separate compiler more a extended compiler configuration.

**Comment by mika-fischer** [comment]
I would also be interested in something like this. We already have a batch file that sets all necessary variables for our version of VS2017 build tools as well as some others we need internally. It would be great if we could just make cmake-tools use that as a kit.

Has there been any progress in that direction? What would be the direction forward?

**Comment by MBetters** [comment]
I made a [workaround script](https://gist.github.com/MBetters/ba1e8c65c3d9a65e27ebe72b5d99a36b)

**Comment by danieroux** [comment]
This will also be useful for Yocto SDKs: https://www.yoctoproject.org/docs/current/mega-manual/mega-manual.html#sdk-running-the-sdk-environment-setup-script

The work-around script doesn't work as-is for it, since the setup script sources other files in as well.

**Comment by bobbrow** [comment]
This request was addressed by the addition of `environmentSetupScript` in the Kit schema in version 1.4.0.
