### ISSUE TITLE
Scan for kits on windows

### ISSUE THREAD

**Issue by PeterFromSweden** [microsoft/vscode-cmake-tools#2880]
### Brief Issue Summary

1) msys2 ucrt64 gcc is not found.
2) If manually entered in user local cmake kits it is deleted when scanning again.

_UPDATE_
gcc is not in path (by intention). I guess that thats why it is not found at scan?!? "Scan" is more of a "get" then...

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.73.1",
  "cmtVersion": "1.12.27",
  "configurations": [
    {
      "folder": "log4cplus",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
No build. Just scan for kits.
```

### Additional Information

I know that project specific kits can be added, but this is logically wrong since I want to make the installed kit available for all projects.

**Comment by bobbrow** [comment]
Correct.  We don't scan your entire hard drive for compilers.  There is a setting called `cmake.mingwSearchDirs` that allows you to add paths to search for compilers.

**Comment by PeterFromSweden** [comment]
But msvc is found so some scanning is made outside path, so some standard
paths for mingw gcc would be expected to be searched as per my opinion.
These would be for instance (alternatives)
https://www.msys2.org/
choco install msys2
choco install mingw

and for clang...
choco install llvm

Den fre 2 dec. 2022 kl 17:46 skrev Bob Brown ***@***.***>:

**Comment by bobbrow** [comment]
Visual Studio has a detection tool called `vswhere.exe`.  We run that tool to find Visual Studio installations.

We could add additional default installation paths to scan by default.  We'd accept a pull request with such an addition.
