### ISSUE TITLE
Erorr at startup: No cache object found

### ISSUE THREAD

**Issue by tommeschberlin** [microsoft/vscode-cmake-tools#2882]
### Brief Issue Summary

Hi, I get the error `[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: No cache object found` at startup configuration of vscode.

### Steps to reproduce:
Before starting vscode:
- Create a` [buildDir]/.cmake/api/v1/query` directory and put two queries into (via touch):
  cmakeFiles-v1 and  codemodel-v2
- run `cmake -S[srcDir] -B[buildDir] -G Ninja`

Then start vscode and the error appears!

### Some research results:
- if no queries are given and no .cmake directory exists everything is fine
- if you add additional cache-v2 query also everything is fine

It looks like the cmake-tool trust by mistake at a cache entry in the cmake-file-api if .cmake directory exists!!
 

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.73.1",
  "cmtVersion": "1.10.4",
  "configurations": [
    {
      "folder": "82952",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
[rollbar] Unhandled exception: Unhandled Promise rejection: buildDirectory Error: No cache object found {}
```

**Comment by bobbrow** [comment]
Is this normal operation for your project? If the entries are missing then we can't update the code model to provide IntelliSense configurations to the C++ extension.  We can remove the Promise rejection, but you may end up in a state where the extension doesn't provide a service and you won't know that something is wrong.

**Comment by tommeschberlin** [comment]
There seems to be code to write a client-vscode query: https://github.com/microsoft/vscode-cmake-tools/blob/a00c339cef191fb9bae64922713189bf64d994b0/src/drivers/cmakeFileApi.ts#L221
But apparently this is not executed on my end. The reply is for a different query that does not need all the same object types. However, it looks like this reply is still picked up even though the query was not written.

**Comment by bobbrow** [comment]
I'm sorry, I don't fully understand.  Do you have a query file from another IDE in there?  The function `createQueryFileForApi` always executes - I don't see how it could be skipped.  Is it failing?  Can you set the `cmake.loggingLevel` to `"debug"` and look for "Failed writing to file" in the Output Window?

**Comment by tommeschberlin** [comment]
Yes that maybe the problem, we have a pre-build environment setting process, which creates queries for `cmakeFiles-v1` and `codemodel-v2`, but no query for `cache-v2`, this process also calls cmake. After that I start vscode which results in the described error.
