### ISSUE TITLE
CMake was unable to find Ninja then using CMakePresets.json

### ISSUE THREAD

**Issue by x-santiaga-x** [microsoft/vscode-cmake-tools#2888]
### Brief Issue Summary

I have a test project using CMake. It builds fine if there is no CMakePresets.json file in the directory. But if the file is added, an error appears: _CMake was unable to find a build program corresponding to "Ninja"_.
It can be seen from the log that in the first case, _vcvarsall.bat x64_ is launched, while in the second it does not. If the path to Ninja is explicitly added to the environment variables, later on there are search errors for the C and CXX compilers.

Test project [cmake_test.zip](https://github.com/microsoft/vscode-cmake-tools/files/10164889/cmake_test.zip).
The log directory contains logs for cases where the test directory contains (presets.log) or does not contain (no_presets.log) the CMakePresets.json file.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.74.0-insider",
  "cmtVersion": "1.13.27",
  "configurations": [
    {
      "folder": "c:\\work\\temp_proj\\cmake_test",
      "cmakeVersion": "3.24.202208181",
      "configured": true,
      "generator": "",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
[presetController] Start selection of configure presets. Found 3 presets.
[presetController] Opening configure preset selection QuickPick
[presetController] User selected configure preset "win-test"
[main] Resolving the selected configure preset
[main] Using generator from user configuration: Ninja
[main] Loading new configure preset into CMake driver
[main] Resolving the selected build preset
[main] Using generator from user configuration: Ninja
[main] Loading new build preset into CMake driver
[main] Building folder: cmake_test 
[main] Starting new CMake driver
[main] Starting CMake driver
[main] Using generator from user configuration: Ninja
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using preset
[driver] CMakeDriver configure preset set to win-test
[driver] CMakeDriver build preset set to win-test
[driver] Setting new variant Debug
[cache] Reading CMake cache file c:/work/temp_proj/build/win-test/CMakeCache.txt
[cache] Cache file does not exist: Returning empty cache data
[main] Saving open files before configure/build
[cache] Reading CMake cache file c:/work/temp_proj/build/win-test/CMakeCache.txt
[cache] Cache file does not exist: Returning empty cache data
[cpptools] The build configurations generated do not contain the active build configuration. Using "Debug" for CMAKE_BUILD_TYPE instead of "null" to ensure that IntelliSense configurations can be found
[cpptools] The build configurations generated do not contain the active build configuration. Using "Debug" for CMAKE_BUILD_TYPE instead of "null" to ensure that IntelliSense configurations can be found
[main] Configuring folder: cmake_test 
[main] Saving open files before configure/build
[driver] Start configure 
[driver] Running pre-configure checks and steps
[cmakefileapi-driver] Configuring using preset
[cmakefileapi-driver] Invoking CMake c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe with arguments ["-DCMAKE_BUILD=1","-DCMAKE_BUILD_TYPE=Debug","-DCMAKE_INSTALL_PREFIX=c:/work/temp_proj/run/win-test","--debug-output","-Sc:/work/temp_proj/cmake_test","-Bc:/work/temp_proj/build/win-test","-G","Ninja"]
[proc] Executing command: "c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_BUILD=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=c:/work/temp_proj/run/win-test --debug-output -Sc:/work/temp_proj/cmake_test -Bc:/work/temp_proj/build/win-test -G Ninja
[cmake] Running with debug output on.
[cmake] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[cmake]    Called from: [1]	C:/work/temp_proj/cmake_test/CMakeLists.txt
[cmake] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[cmake]    Called from: [1]	C:/work/temp_proj/cmake_test/CMakeLists.txt
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/work/temp_proj/build/win-test/CMakeFiles/CMakeOutput.log".
[proc] The command: "c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_BUILD=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=c:/work/temp_proj/run/win-test --debug-output -Sc:/work/temp_proj/cmake_test -Bc:/work/temp_proj/build/win-test -G Ninja exited with code: 1 and signal: null
[extension] [5039] cmake.build finished (returned 1)
```

### Additional Information

VSCode info

Version: 1.74.0-insider (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T10:17:57.998Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

Microsoft Visual Studio Community 2022
Version 17.4.2
VisualStudio.17.Release/17.4.2+33122.133
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Community

CMake from Microsoft Visual Studio Community 2022 with Ninja bundled.
c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja

**Comment by x-santiaga-x** [comment]
Log results after adding path to Ninja, as expected: 
<details><summary>No CMAKE_CXX_COMPILER could be found.</summary>

[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[main] CMakeProject instance initialization complete.
[kit] Reading kits file C:\Users\user\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 22 kits from C:\Users\user\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Not reading non-existent kits file: c:\work\temp_proj\cmake_test\.vscode\cmake-kits.json
[presetController] Reading presets file C:\work\temp_proj\cmake_test\CMakePresets.json
[presetController] Successfully validated presets in C:\work\temp_proj\cmake_test\CMakePresets.json
[main] Resolving the selected configure preset
[main] Loading new configure preset into CMake driver
[main] Resolving the selected build preset
[main] Using generator from user configuration: Ninja
[main] Loading new build preset into CMake driver
[extension] Configuring workspace on open file:///c%3A/work/temp_proj/cmake_test
[proc] Executing command: "c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --version
[extension] [9859] cmake.buildDirectory started
[main] Starting new CMake driver
[main] Starting CMake driver
[main] Using generator from user configuration: Ninja
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using preset
[driver] CMakeDriver configure preset set to win-test
[driver] CMakeDriver build preset set to win-test
[driver] Setting new variant Debug
[main] Configuring folder: cmake_test 
[main] Saving open files before configure/build
[extension] [9859] cmake.buildDirectory finished (returned "C:/work/temp_proj/cmake_test/build/win-test")
[driver] Start configure 
[driver] Running pre-configure checks and steps
[cache] Reading CMake cache file C:/work/temp_proj/cmake_test/build/win-test/CMakeCache.txt
[cache] Cache file does not exist: Returning empty cache data
[cmakefileapi-driver] Configuring using preset
[cmakefileapi-driver] Invoking CMake c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe with arguments ["-DCMAKE_BUILD=1","-DCMAKE_BUILD_TYPE=Debug","-DCMAKE_INSTALL_PREFIX=C:/work/temp_proj/cmake_test/run/win-test","--debug-output","-SC:/work/temp_proj/cmake_test","-BC:/work/temp_proj/cmake_test/build/win-test","-G","Ninja"]
[proc] Executing command: "c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_BUILD=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/work/temp_proj/cmake_test/run/win-test --debug-output -SC:/work/temp_proj/cmake_test -BC:/work/temp_proj/cmake_test/build/win-test -G Ninja
[proc]   with environment: {"ALLUSERSPROFILE":"C:\\ProgramData","APPDATA":"C:\\Users\\user\\AppData\\Roaming","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true","COMPUTERNAME":"user-pc","ComSpec":"C:\\Windows\\system32\\cmd.exe","CommonProgramFiles":"C:\\Program Files\\Common Files","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","CommonProgramW6432":"C:\\Program Files\\Common Files","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","ELECTRON_RUN_AS_NODE":"1","HOME":"C:\\Users\\user","HOMEDRIVE":"C:","HOMEPATH":"\\Users\\user","LOCALAPPDATA":"C:\\Users\\user\\AppData\\Local","LOGONSERVER":"\\\\user-pc","MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Reader\\plugins\\","NUMBER_OF_PROCESSORS":"24","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","OS":"Windows_NT","OneDrive":"C:\\Users\\user\\OneDrive","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","PROCESSOR_ARCHITECTURE":"AMD64","PROCESSOR_IDENTIFIER":"AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD","PROCESSOR_LEVEL":"25","PROCESSOR_REVISION":"2102","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules","PUBLIC":"C:\\Users\\Public","Path":"C:/Program Files/Common Files/Oracle/Java/javapath;C:\\Windows\\system32;C:/Windows;C:\\Windows\\System32\\Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/;C:\\Windows\\System32\\OpenSSH\\;C:/Program Files/dotnet/;C:\\Program Files\\TortoiseGit\\bin;C:/Program Files/Git/cmd;C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps;C:/Users/user/.dotnet/tools;C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;c:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja","ProgramData":"C:\\ProgramData","ProgramFiles":"C:\\Program Files","ProgramFiles(x86)":"C:\\Program Files (x86)","ProgramW6432":"C:\\Program Files","QTDIR":"c:\\work\\xcad\\libs\\qt5\\qt5.x64\\Release","SESSIONNAME":"Console","SystemDrive":"C:","SystemRoot":"C:\\Windows","TEMP":"C:\\Users\\user\\AppData\\Local\\Temp","TMP":"C:\\Users\\user\\AppData\\Local\\Temp","TRACEDESIGNTIME":"false","USERDOMAIN":"user-pc","USERDOMAIN_ROAMINGPROFILE":"user-pc","USERNAME":"user","USERPROFILE":"C:\\Users\\user","VSCODE_AMD_ENTRYPOINT":"vs/workbench/api/node/extensionHostProcess","VSCODE_CODE_CACHE_PATH":"C:\\Users\\user\\AppData\\Roaming\\Code - Insiders\\CachedData\\5235c6bb189b60b01b1f49062f4ffa42384f8c91","VSCODE_CWD":"C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code Insiders","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_IPC_HOOK":"\\\\.\\pipe\\072dd7ba48040d039523d946722e2806-1.74.0-insider-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"ru\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_PID":"33836","WIX":"C:\\Program Files (x86)\\WiX Toolset v3.11\\","windir":"C:\\Windows"}
[extension] [9039] cmake.buildDirectory started
[extension] [9039] cmake.buildDirectory finished (returned "C:/work/temp_proj/cmake_test/build/win-test")
[cmake] Running with debug output on.
[cmake] -- The CXX compiler identification is unknown
[cmake]    Called from: [3]	C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/CMakeDetermineCompilerId.cmake
[cmake]                 [2]	C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/CMakeDetermineCXXCompiler.cmake
[cmake]                 [1]	C:/work/temp_proj/cmake_test/CMakeLists.txt
[cmake] CMake Error at CMakeLists.txt:3 (project):
[cmake]   No CMAKE_CXX_COMPILER could be found.
[cmake] 
[cmake]   Tell CMake where to find the compiler by setting either the environment
[cmake]   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
[cmake]   to the compiler, or to the compiler name if it is in the PATH.
[cmake] 
[cmake] 
[cmake]    Called from: [1]	C:/work/temp_proj/cmake_test/CMakeLists.txt
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/work/temp_proj/cmake_test/build/win-test/CMakeFiles/CMakeOutput.log".
[cmake] See also "C:/work/temp_proj/cmake_test/build/win-test/CMakeFiles/CMakeError.log".
[proc] The command: "c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_BUILD=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/work/temp_proj/cmake_test/run/win-test --debug-output -SC:/work/temp_proj/cmake_test -BC:/work/temp_proj/cmake_test/build/win-test -G Ninja exited with code: 1
[cache] Reading CMake cache file C:/work/temp_proj/cmake_test/build/win-test/CMakeCache.txt
[cache] Parsing CMake cache string
</details>

And if I explicitly specify the path to the compiler, further, I think, other paths from vcvars.bat will be missing, since it was not run, according to the reports.

**Comment by bobbrow** [comment]
I made some fixes to the presets file I found in your test project.

```json
    {
      "name": "win-default",
      "hidden": true,
      "displayName": "Windows Default Config",
      "description": "Default Win build using Ninja generator",
      "inherits": "default",
      "architecture": {
        "value": "x64",
        "strategy": "external"
      },
      "toolset": {
        "value": "host=x64",
        "strategy": "external"
      },
      "cacheVariables": {
        "CMAKE_CXX_COMPILER": "cl.exe",
        "CMAKE_C_COMPILER": "cl.exe"
      },
      "vendor": {
        "microsoft.com/VisualStudioSettings/CMake/1.0": {
          "hostOS": [ "Windows" ]
        }
      }
    },
```

When you use Ninja, CMake expects the build environment to be pre-configured.  Our extension can do that for you, but it needs to know first that you want to use `cl.exe` as the compiler.  So if you set those cache variables in your preset, then we can auto-inject the correct build environment for you.  Otherwise, you need to launch VS Code from a Visual Studio Developer Command Prompt.

Also, the toolset property looked incorrect.  I don't know what `msvc_x64` maps to, but if you put `host=x64` in there, it should do what you want.

**Comment by x-santiaga-x** [comment]
Thanks a lot for your fixes, everything works now.

I didn't read the compiler selection section of the documentation carefully enough ([Select your compiler](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-presets.md#select-your-compilers) if anyone else runs into this problem).
