### ISSUE TITLE
CMake build tasks don't respect `debug.onTaskErrors`

### ISSUE THREAD

**Issue by mihe** [microsoft/vscode-cmake-tools#2891]
### Brief Issue Summary

When launching a program from Visual Studio Code, with a task of `"type": "cmake"` set as the `preLaunchTask` for that launch configuration, the program will launch after the `preLaunchTask` results in an error, despite the user having set the user setting `debug.onTaskErrors` to something like `abort`.

**Steps to reproduce:**

1. Create a `task.json` similar to what's shown below
2. Create a `launch.json` similar to what's shown below
3. Ensure that "My Build Task" results in an error when run
4. Set the user setting `debug.onTaskErrors` to `abort`
5. Launch the "My Launch Task" configuration
6. Note how it runs "My Build Task" first
7. Note how "My Build Task" results in an error
8. Note how it still launches the application set in "My Launch Configuration"
9. Note how the `CMake/Build` output log says `[proc] The command: [redacted] exited with code: 1 and signal: null`

**`.vscode/tasks.json`:**

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "cmake",
      "label": "My Build Task",
      "command": "build",
      "preset": "${command:cmake.activeBuildPresetName}",
      "targets": ["${command:cmake.buildTargetName}"],
      "group": { "kind": "build", "isDefault": true }
    }
  ]
}
```

**`.vscode/launch.json`:**

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "cppvsdbg",
      "request": "launch",
      "name": "My Launch Configuration",
      "program": "C:/Path/To/Executable.exe",
      "preLaunchTask": "My Build Task"
    }
  ]
}
```

### CMake Tools Diagnostics

```shell
N/A
```

### Debug Log

```shell
N/A
```

**Comment by elahehrashedi** [comment]
We have a fix for this here: https://github.com/microsoft/vscode-cmake-tools/pull/2803/files, we haven't released this fix yet, it is still in pre-release. If you install the pre-release version this should work for you. If it didn't work, let us know and we will investigate more.
