### ISSUE TITLE
How to use make instead of ninja

### ISSUE THREAD

**Issue by JeffR1992** [microsoft/vscode-cmake-tools#2899]
### Brief Issue Summary

I'm using the CMake Tools extension in VS Code to build my project. However, it seems that `ninja` is used to build by default. Is there a way I can change this to use `make` instead?

As a simple example, what I currently do to build my project is the following:
```
cd build
ninja
```

What I want to do instead is:
```
cd build
make
```

**Comment by elahehrashedi** [comment]
you can set your preferred generator using `"cmake.generator"` setting.

**Comment by Zingam** [comment]
Alternative: CMake presets. Set the generator via CMake presets.
