### ISSUE TITLE
Running CTest rebuilds other build configuration in CMake multi generator configuration

### ISSUE THREAD

**Issue by jorisvanderpol** [microsoft/vscode-cmake-tools#2904]
### Brief Issue Summary

CMake Tools 1.12.27
Visual Studio Code 1.72.2

I have created a project with the following `CMakePresets.json`:

```
{
    "version": 6,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 25,
        "patch": 1
    },
    "configurePresets": [
        {
            "name": "v140_x64",
            "displayName": "Visual Studio 2015",
            "generator": "Visual Studio 14 2015",
            "architecture": "x64",
            "environment": {
                "CMAKE_CONFIGURATION_TYPES": "Debug;Release"
            }
        }
    ],
    "buildPresets": [
        {
            "name": "v140_x64_debug",
            "displayName": "Build Debug",
            "configurePreset": "v140_x64",
            "configuration": "Debug"
            },
        {
            "name": "v140_x64_release",
            "displayName": "Build Release",
            "configurePreset": "v140_x64",
            "configuration": "Release"
        }
    ],
    "testPresets": [
        {
            "name": "v140_x64_debug",
            "displayName": "Test Debug",
            "configurePreset": "v140_x64",
            "configuration": "Debug"
        },
        {
            "name": "v140_x64_release",
            "displayName": "Test Release",
            "configurePreset": "v140_x64",
            "configuration": "Release"
        }
    ]
}
```

If I now select the `Build Debug` as the active build preset and the `Test Release` as the active test preset, it will build the `Debug` configuration and run the CTest tests with the `Release` configuration. This is confusing behavior. Removing the configuration from the test preset will not work (assuming it takes over the configuration of the build preset), as it produces an error (`Test not available without configuration`).

**Comment by bobbrow** [comment]
I believe that this is a deficiency with the spec for test presets.  test presets are dependent on a configurePreset, not a buildPreset, so it wasn't considered when we implemented this.  Visual Studio appears to have the same problem.

It seems reasonable to me that we could filter out the test presets that don't apply to the active build preset when offering the list of presets to select since the build type is known.  We could probably also make the case where the build type is unknown work as well (assuming that it works on the command line... need to check).

**Comment by MartinsSmirnovs** [comment]
@bobbrow 
Could it be possible to not to build at all when running CTests? There are cases when existing binary is not necessary for test case, only CMake configure.

**Comment by bobbrow** [comment]
@MartinsSmirnovs can you open a new issue to request that?  There may not be a way for us to know beforehand that this is possible which means this might need to be controlled by a setting or by adding a new command.

**Comment by MartinsSmirnovs** [comment]
Created feature request #2933

**Comment by bobbrow** [comment]
> Created feature request #2933

Thank you.
