### ISSUE TITLE
Windows + Ninja + MSVC + CMakePresets.json - does this combination work?

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#2912]
### Brief Issue Summary

I created the simplest HelloWorld project using CMakePresets.json, using the standard Ninja generator and CMake couldn't find MSVC. I couldn't work out a solution using the docs.
I switched to Ninja Multi-Config it just worked. The Visual Studio 2022 generator also works.

Is there anything special that needs to be done to use the Ninja generator on Windows with Visual Studio 2022 or there is an issue?

**Comment by bobbrow** [comment]
Hi @Zingam, we're going to need more information/logs.  I've been doing quite a bit of testing this week with Windows + Ninja + MSVC + CMakePresets and it works fine for me.

Please share your CMakePresets.json and the output from the `CMakeL Log Diagnostics` command.  It would also be helpful to have the debug logs too if you're able to share them (set `cmake.loggingLevel` to "debug" and reload the window)

**Comment by Zingam** [comment]
I probably did something wrong with the Ninja preset as I seemingly got it working now. So I apologize for the trouble.

Yet this made me wonder why isn't the extension using the same mechanism already implemented by the "compiler kits" to select from a list of available compilers.
The above instead of:

```json
"architecture": {
   "value": "x64",
   "strategy": "set"
},
"cacheVariables": {
   "CMAKE_BUILD_TYPE": "Debug",
   "CMAKE_C_COMPILER": "cl",
   "CMAKE_CXX_COMPILER": "cl",
   "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}"
 },
```

I use the extension on macOS and Linux primarily where it just picks up the default compiler and everything is smooth.
I dislike the idea to have to hardcode the COMPILER variables or to make even more User preset combinations.

**Comment by bobbrow** [comment]
> Yet this made me wonder why isn't the extension using the same mechanism already implemented by the "compiler kits" to select from a list of available compilers.

If you configure with presets outside of VS Code, the "kits" aren't used.  Presets is intended to be portable across environments.  You can get away with not setting the C and CXX compiler variables in some cases, but it will depend on your environment how CMake will pick the compiler and we don't guarantee the same results in CMake Tools.

> If cmake is run on the command line it should be run in a vsvars.bat shell anyway.

Yes, Ninja + MSVC requires the VS build environment to be pre-configured.  But we don't know to do that for you automatically unless you specify "cl" as the compiler.  What if the developer wanted clang/gcc on Windows instead?  It's less of an issue on mac/linux because the default compilers there (gcc/clang) don't require a bunch of environment variables to be set.

**Comment by hwhsu1231** [comment]
@Zingam 

The following are my examples of `CMakePresets.json` using **MSVC** compilers with **Ninja/Ninja Multi-Config** generators. You can take them for reference.

According to my experience and research, you need to specify 3 settings in Configure Presets:

* `"toolset"` field with `"external"` strategy.
* `"architecture"` field with `"external"` strategy.
* Environemnt Variables or Cache Variables for MSVC compiler.


```json
{
  "version": 3,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 21,
    "patch": 0
  },
  "configurePresets": [
    {
      "name": "win32-msvc16-x64-ninja-debug",
      "displayName": "Windows MSVC16 x64 (Ninja) Debug",
      "description": "Using MSVC16 x64 compiler with \"Ninja\" generator on Windows - Debug",
      "generator": "Ninja",
      "toolset": {
        "value": "v142,host=x64",
        "strategy": "external"
      },
      "architecture": {
        "value": "x64",
        "strategy": "external"
      },
      "cacheVariables": {
        "CMAKE_C_COMPILER": "cl.exe",
        "CMAKE_CXX_COMPILER": "cl.exe",
        "CMAKE_BUILD_TYPE": "Debug"
      }
    },
    {
      "name": "win32-msvc17-x64_x86-ninja-multi",
      "displayName": "Windows MSVC17 x64_x86 (Ninja Multi-Config)",
      "description": "Using MSVC17 x64_x86 compiler with \"Ninja Multi-Config\" generator on Windows",
      "generator": "Ninja Multi-Config",
      "toolset": {
        "value": "v143,host=x64",
        "strategy": "external"
      },
      "architecture": {
        "value": "x86",
        "strategy": "external"
      },
      "cacheVariables": {
        "CMAKE_C_COMPILER": "cl.exe",
        "CMAKE_CXX_COMPILER": "cl.exe"
      }
    }
  ]
}
```

**Comment by Zingam** [comment]
> @Zingam
> 
> The following are my examples of `CMakePresets.json` using **MSVC** compilers with **Ninja/Ninja Multi-Config** generators. You can take them for reference.
> 
> According to my experience and research, you need to specify 3 settings in Configure Presets:
> 
> * `"toolset"` field with `"external"` strategy.
> * `"architecture"` field with `"external"` strategy.
> * Environemnt Variables or Cache Variables for MSVC compiler.
> 
> ```json
> {
>   "version": 3,
>   "cmakeMinimumRequired": {
>     "major": 3,
>     "minor": 21,
>     "patch": 0
>   },
>   "configurePresets": [
>     {
>       "name": "windows-only",
>       "displayName": "Windows-only configuration",
>       "description": "This build is only available on Windows",
>       "cmakeExecutable": "C:/Program Files/CMake/bin/cmake.exe",
>       "binaryDir": "${sourceDir}/build/${presetName}",
>       "installDir": "${sourceDir}/install/${presetName}",
>       "hidden": true,
>       "condition": {
>         "type": "equals",
>         "lhs": "${hostSystemName}",
>         "rhs": "Windows"
>       }
>     },
>     {
>       "inherits": "windows-only",
>       "name": "win32-msvc16-x64-ninja-debug",
>       "displayName": "Windows MSVC16 x64 (Ninja) Debug",
>       "description": "Using MSVC16 x64 compiler with \"Ninja\" generator on Windows - Debug",
>       "generator": "Ninja",
>       "toolset": {
>         "value": "v142,host=x64",
>         "strategy": "external"
>       },
>       "architecture": {
>         "value": "x64",
>         "strategy": "external"
>       },
>       "cacheVariables": {
>         "CMAKE_C_COMPILER": "cl.exe",
>         "CMAKE_CXX_COMPILER": "cl.exe",
>         "CMAKE_BUILD_TYPE": "Debug"
>       }
>     },
>     {
>       "inherits": "windows-only",
>       "name": "win32-msvc17-x64_x86-ninja-multi",
>       "displayName": "Windows MSVC17 x64_x86 (Ninja Multi-Config)",
>       "description": "Using MSVC17 x64_x86 compiler with \"Ninja Multi-Config\" generator on Windows",
>       "generator": "Ninja Multi-Config",
>       "toolset": {
>         "value": "v143,host=x64",
>         "strategy": "external"
>       },
>       "architecture": {
>         "value": "x86",
>         "strategy": "external"
>       },
>       "cacheVariables": {
>         "CMAKE_C_COMPILER": "cl.exe",
>         "CMAKE_CXX_COMPILER": "cl.exe"
>       }
>     }
>   ]
> }
> ```

@hwhsu1231 Thank you! I'll try your solution. I also got it to work. I did something wrong intimacy later I managed to get it working and I am quick to complain.

**Comment by Zingam** [comment]
> > Yet this made me wonder why isn't the extension using the same mechanism already implemented by the "compiler kits" to select from a list of available compilers.
> 
> If you configure with presets outside of VS Code, the "kits" aren't used. Presets is intended to be portable across environments. You can get away with not setting the C and CXX compiler variables in some cases, but it will depend on your environment how CMake will pick the compiler and we don't guarantee the same results in CMake Tools.
> 
> > If cmake is run on the command line it should be run in a vsvars.bat shell anyway.
> 
> Yes, Ninja + MSVC requires the VS build environment to be pre-configured. But we don't know to do that for you automatically unless you specify "cl" as the compiler. What if the developer wanted clang/gcc on Windows instead? It's less of an issue on mac/linux because the default compilers there (gcc/clang) don't require a bunch of environment variables to be set.

My idea is: to also have the option with a single CMake preset to automatically selecting the compiler via the kits option. Would that be theoretically possible and practically feasible?

Technically this workflow can be done with User presets but then I still have to figure out where my compilers are located manually.
This would be convenient for a quick, lazy project setup.

I hope I have explained my case clearly.

**Comment by bobbrow** [comment]
> My idea is: to also have the option with a single CMake preset to automatically selecting the compiler via the kits option. Would that be theoretically possible and practically feasible?

It's theoretically possible.  In CMakePresets.json, it is possible to add additional data in the 'vendor' field and CMake will ignore that.  I don't think we'll do it though, because the purpose of presets is to be able to create a portable configuration that both CMake and the IDE's can understand.  Such a configuration would suffer from working only in VS Code with our extension.

To aid you in creating presets that are tied to Kits, though, we added a "Add Configure Preset" command that lets you use one of the Kits as a starting point.  (Though I see there's a problem with those commands appearing that I am fixing with #2977)

**Comment by MathiasMagnus** [comment]
@bobbrow I've written a short [CMake script](https://gist.github.com/MathiasMagnus/791c82dc1db4c50bc1c125937da4c0bd), that extracts the environment from any of the MSBuild PlatformToolset's `BuiltTask`. What it it does is that it runs the `set` command of `cmd.exe` both from the env of the caller and inside a dummy MSBuild project inside an `add_custom_command`, then it computes a delta of the two environments and saves it in a file of the user's choice in CMakePresets format. I include this file in my `CMakeUserPresets.json` so that I need no equivalent to `environmentSetupScript` in presets. My issue is that CMake Tools seems to completely disregard the environment I setup this way. MSVC happens to work from VS Code (because the compiler is set as `cl.exe`, but `clang-cl.exe` doesn't, even though from the command-line this approach works flawlessly. Using the script I do something like:
```
{
	"version": 4,
	"cmakeMinimumRequired": {
		"major": 3,
		"minor": 22,
		"patch": 0
	},
	"include": [
		"C:\\Users\\mate\\OneDrive\\Develop\\Visual Studio\\Toolchain-MSVC-MakefileGenerators.json",
		"C:\\Users\\mate\\OneDrive\\Develop\\Visual Studio\\Toolchain-ClangCL-MakefileGenerators.json"
	],
	"configurePresets": [
		{
			"name": "generator-ninja-multi-config",
			"hidden": true,
			"generator": "Ninja Multi-Config",
			"cacheVariables": {
				"CMAKE_MAKE_PROGRAM": "C:\\Kellekek\\Ninja\\bin\\ninja.exe"
			},
			"architecture": {
				"value": "x64",
				"strategy": "external"
			}
		},
		{
			"name": "toolchain-makefiles-c/c++-msvc-v143",
			"hidden": true,
			"cacheVariables": {
				"CMAKE_C_COMPILER": "cl.exe",
				"CMAKE_C_LINK_EXECUTABLE": "link.exe",
				"CMAKE_CXX_COMPILER": "cl.exe",
				"CMAKE_CXX_LINK_EXECUTABLE": "link.exe",
				"CMAKE_RC_COMPILER": "rc.exe",
				"CMAKE_MT": "mt.exe"
			},
			"toolset": {
				"value": "v143,version=14.34,host=x64",
				"strategy": "external"
			}
		},
		{
			"name": "toolchain-makefiles-c/c++-clangcl",
			"hidden": true,
			"cacheVariables": {
				"CMAKE_C_COMPILER": "clang-cl.exe",
				"CMAKE_C_LINK_EXECUTABLE": "llvm-link.exe",
				"CMAKE_CXX_COMPILER": "clang-cl.exe",
				"CMAKE_CXX_LINK_EXECUTABLE": "llvm-link.exe",
				"CMAKE_RC_COMPILER": "rc.exe",
				"CMAKE_MT": "mt.exe"
			},
			"toolset": {
				"value": "ClangCL,version=14.34,host=x64",
				"strategy": "external"
			}
		},
		{
			"name": "msvc-arch-native-strict-iso-high-warn",
			"hidden": true,
			"cacheVariables": {
				"CMAKE_C_FLAGS": "/arch:AVX2 /W4",
				"CMAKE_CXX_FLAGS": "/arch:AVX2 /EHsc /permissive- /W4"
			}
		},
		{
			"name": "clangcl-arch-native-strict-iso-high-warn",
			"hidden": true,
			"cacheVariables": {
				"CMAKE_C_FLAGS": "/arch:AVX2 /W4 -fuse-ld=llvm-link",
				"CMAKE_CXX_FLAGS": "/arch:AVX2 /EHsc /permissive- /W4 -fuse-ld=llvm-link"
			}
		},
		{
			"name": "ninja-msvc-v143",
			"displayName": "Ninja MSVC v143",
			"inherits": [
				"layout",
				"generator-ninja-multi-config",
				"toolchain-makefiles-c/c++-msvc-v143",
				"developer-command-prompt-msvc-v143-x64",
				"msvc-arch-native-strict-iso-high-warn"
			]
		},
		{
			"name": "ninja-clangcl",
			"displayName": "Ninja ClangCL",
			"inherits": [
				"layout",
				"generator-ninja-multi-config",
				"toolchain-makefiles-c/c++-clangcl",
				"developer-command-prompt-clangcl-x64",
				"clangcl-arch-native-strict-iso-high-warn"
			]
		}
	],
	"buildPresets": [
		{
			"name": "ninja-parallel",
			"hidden": true,
			"nativeToolOptions": [
				"-j$env{NUMBER_OF_PROCESSORS}"
			]
		},
		{
			"name": "ninja-verbose",
			"hidden": true,
			"verbose": true
		},
		{
			"name": "ninja-msvc-v143-debug",
			"displayName": "Debug",
			"configuration": "Debug",
			"configurePreset": "ninja-msvc-v143",
			"inherits": [
				"ninja-parallel"
			]
		},
		{
			"name": "ninja-msvc-v143-release",
			"displayName": "Release",
			"configuration": "Release",
			"configurePreset": "ninja-msvc-v143",
			"inherits": [
				"ninja-parallel"
			]
		},
		{
			"name": "ninja-clangcl-debug",
			"displayName": "Debug",
			"configuration": "Debug",
			"configurePreset": "ninja-clangcl",
			"inherits": [
				"ninja-parallel"
			]
		},
		{
			"name": "ninja-clangcl-release",
			"displayName": "Release",
			"configuration": "Release",
			"configurePreset": "ninja-clangcl",
			"inherits": [
				"ninja-parallel"
			]
		}
	]
}
```
If it works outside the IDE, I would like CMake Tools to play along with this setup. This is the closest I could get to telling CMake via a preset how to use a toolchain without setting up the environment otherwise.

**Comment by MathiasMagnus** [comment]
@bobbrow Any update on this? CMake Tools and Presets which set their own environment still don't mix well.

**Comment by tomasiser** [comment]
For anyone encountering this issue and spending hours on figuring it out, I can confirm that what @hwhsu1231 wrote above indeed seems to work.

The trick for using `"generator": "Ninja"` together with Visual Studio 2022 Build Tools is adding the following to your preset:

```json
"toolset": {
    "value": "v143,host=x64",
    "strategy": "external"
},
"architecture": {
    "value": "x64",
    "strategy": "external"
},
```

and

```json
"cacheVariables": {
    "CMAKE_C_COMPILER": "cl.exe",
    "CMAKE_CXX_COMPILER": "cl.exe",
    ... anything else you want ...
}
```

Without these, it does not work and it will complain that it cannot find Ninja and the compilers.

**Comment by Zitrax** [comment]
Even if I set:

```json
"toolset": {
    "value": "v143,host=x64",
    "strategy": "external"
},
"architecture": {
    "value": "x64",
    "strategy": "external"
},
"cacheVariables": {
    "CMAKE_C_COMPILER": "cl.exe",
    "CMAKE_CXX_COMPILER": "cl.exe"
}
```

it complains for me that it cannot find Ninja with:

`CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.`

Even if I set `CMAKE_MAKE_PROGRAM` to point to the ninja executable, it still complains with the same error.

However if I launch VS Code from the "Developer Command prompt for VS 2022" all works fine. I would like to avoid launching from that or messing with the environment variables.

This used to work for me, but stopped working on two independent computers for me in the recent weeks. Has anything changed regarding how this should be setup?

I am using vcpkg and thus also setting `CMAKE_TOOLCHAIN_FILE` if that is of importance.

**Comment by gcampbell-msft** [comment]
@Zitrax To my knowledge nothing has been changed regarding how this is setup, but hopefully we can chat and see what might be going on. 

How were you defining `CMAKE_MAKE_PROGRAM`?

**Comment by Zitrax** [comment]
I tried:

```json
"CMAKE_MAKE_PROGRAM": "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe"
```
this path has been verified to exist.

This time it moves on (not sure why it did not last time), but stops at:

```
[cmake] CMake Error at CMakeLists.txt:2 (project):
[cmake]   The CMAKE_CXX_COMPILER:
[cmake] 
[cmake]     cl.exe
[cmake] 
[cmake]   is not a full path and was not found in the PATH.
```

So next I try to provide the full path to cl.exe, but it leads to new errors:

```
[cmake]     RC Pass 1: command "rc /fo CMakeFiles\cmTC_6c10a.dir/manifest.res CMakeFiles\cmTC_6c10a.dir/manifest.rc" failed (exit code 0) with the following output:
[cmake]     The system cannot find the file specified
```

when it's testing the compiler. But specifying full paths to everything feels wrong anyway so I assume something else is wrong.

I also tried to repair the VS 2022 install and toggling some of the options there on and off without further luck. I also tried to download "Build Tools for Visual Studio 2022". 

One possible oddity is that I do not have VS installed on the C drive but another drive letter.

Unsure how I should debug it further.
