### ISSUE TITLE
1.13.32/1.13.33 regression: Numerous Include Errors in Project

### ISSUE THREAD

**Issue by scottfurry** [microsoft/vscode-cmake-tools#2915]
### Brief Issue Summary

Version 1.13.31 works as expected.

Version 1.13.32 and 1.13.33 both show the same problem with ms-vscode.cpptools extension integration resulting in tremendous number of include errors on any open file in the editor. This is in spite of paths being set properly and working previously. Clearing cache files and/or reloading CMake settings for project does not resolve the issue.

CMake execution is normal. Project builds without error and can be executed as normal.
Issue appears to be disconnect between CMake discovered paths not being shared with ms-vscode.cpptools.

Reverting to version 1.13.31 of extension as a workaround.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.74.2",
  "cmtVersion": "1.13.33",
  "configurations": [
    {
      "folder": "[PROJECT_HOME]",
      "cmakeVersion": "3.25.1",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/lib/llvm/15/bin/clang",
        "CXX": "/usr/lib/llvm/15/bin/clang++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Reading kits file [HOME]/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Successfully loaded 3 kits from [HOME]/.local/share/CMakeTools/cmake-tools-kits.json
[kit] Not reading non-existent kits file: [PROJECT_HOME]/.vscode/cmake-kits.json
[main] Injecting new Kit into CMake driver
[main] CMakeProject instance initialization complete.
```

### Additional Information

NOTE - for log outputs above - paths edited
[HOME] refers to user home directory: "/home/user/"
[PROJECT_HOME] refers to path in [HOME]: "/home/user/.../project/"

**Comment by sean-mcmanus** [comment]
Yeah, I'm reproing this too, i.e. our team is able to reproduce it.

**Comment by sean-mcmanus** [comment]
@elahehrashedi This appears to be a regression from https://github.com/microsoft/vscode-cmake-tools/pull/2835 -- it repros with our internal vc workspace (single or multi-root).

**Comment by sean-mcmanus** [comment]
@bobbrow I'm seeing this as not fixed yet.

**Comment by sean-mcmanus** [comment]
I'm still seeing this as not fixed with 1.13.36 -- is anyone else seeing it as fixed or not fixed? I'm not sure if my case is unusual or not.

**Comment by scottfurry** [comment]
1.13.35 w/ 1.74.2 VSC is working for me after clearing out previous CMakeCache et al.
I haven't tried 1.13.36 and now I'm scared to.

**Comment by sean-mcmanus** [comment]
@scottfurry That's fine -- the fix was in 1.13.35, i.e. it sounds like the issue got fixed for you.

**Comment by scottfurry** [comment]
@sean-mcmanus - It did. You just beat me to letting people know of the change of circumstances.
Thanks for the efforts moving bug along.

**Comment by sean-mcmanus** [comment]
@scottfurry Yeah, 2 members of our team are still reproing the bug and 2 members are not, so it seems like there's some special case where it still repros that we haven't figured out. Not sure if I should open a new issue or not yet...

**Comment by scottfurry** [comment]
@sean-mcmanus - I can't help but think there's a point release and/or some setting differentiating each set of cases. My instinct would be to hunt that down. Sorry I can't help more than that.
