### ISSUE TITLE
configure on deleting or adding files

### ISSUE THREAD

**Issue by cjwijtmans** [microsoft/vscode-cmake-tools#2921]
### Brief Issue Summary

`cmake.configureOnEdit` says 
> Automatically configure CMake project directories when cmake.sourceDirectory or CMakeLists.txt content are saved.

What exactly does "when cmake.sourceDirectory are saved" mean? Does it mean when cmake files are edited? Adding or removing files does not trigger a configure job for me. If this feature is not added I would like it to be added, although i think it can get kinda complicated if you dont want to trigger a configure when editing certain files.

**Comment by elahehrashedi** [comment]
We will update the docs to clarify the purpose of `"cmake.configureOnEdit"` setting: https://github.com/microsoft/vscode-cmake-tools/pull/2928

It seems like you requesting a feature to trigger a configure when certain files are being added or removed. Right? Would you please explain more?

**Comment by cjwijtmans** [comment]
Yes i thought the description might be saying it would reconfigure on removing or adding files but it was not the case. Usually they recommend to edit the files in cmake file to trigger configure. Ading in a feature to  configure on adding or removing files would be possible but difficult to implement i think.

**Comment by bobbrow** [comment]
> Usually they recommend to edit the files in cmake file to trigger configure. Ading in a feature to configure on adding or removing files would be possible but difficult to implement i think.

Yes, this is what we recommend.  It would only make sense to configure on adding files if you had a `GLOB` in your CMakeLists.txt, but we don't parse through your CMakeLists.txt to discover that.  We ask CMake to tell us which files are relevant and if they aren't there on the first configure, we won't know that new files are meant to be a part of the configuration.  I don't think that it is a feature that we will implement in the extension.

**Comment by gcampbell-msft** [comment]
Now that we've updated the docs to clarify this, we are closing this issue. Thanks!
