### ISSUE TITLE
Building a configure preset for MSVC without specifying targets fails 

### ISSUE THREAD

**Issue by badlogic** [microsoft/vscode-cmake-tools#2929]
### Brief Issue Summary

The first time a folder with a `CMakePresets.json` file is opened, the CMake tools build target is undefined and defaults to `[[Target for preset]]`. Consider this configure preset using a Visual Studio generator.

Consider this configure preset:
```
        {
            "name": "windows-debug",
            "displayName": "Desktop debug",
            "description": "",
            "generator": "Visual Studio 15 2017 Win64",
            "binaryDir": "${sourceDir}/build/${presetName}",
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Debug"
            },
            "condition": {
                "type": "equals",
                "lhs": "${hostSystemName}",
                "rhs": "Windows"
            }
        },
```

When seleting this preset via configure preset CMake tools status bar entry without having specified a build target and hitting `Build`, CMake tools will issue a command like this:

```
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build c:/workspaces/r96/build/windows-debug --target all
```

This does not work with the Visual Studio generator, as no target with name `all` is generated. Instead, `ALL_BUILD` is what's needed for the Visual Studio generator.

In terms of UX, the user is never prompted to select a build target. It would make sense to set this to `ALL_BUILD` in case a Visual Studio generator is used, so builds do not fail out of the box.

**Comment by bobbrow** [comment]
Can you share the active build preset as well?  Since VS is a multi-config generator, I don't have the full picture.  We should be pulling the targets from the build preset, and it nothing is defined, we don't select a target at all.

Also, what version of the extension are you using?  1.12.27, or one of the 1.13 pre-releases?  I don't reproduce this problem in the pre-releases.
