### ISSUE TITLE
"build" task improvements

### ISSUE THREAD

**Issue by piomis** [microsoft/vscode-cmake-tools#2935]
### Brief Issue Summary

This issue is continuation of issue #2778 and pull-request #2780 
Newly merged implementation is not able to properly find tasks from tasks.json if their definitions include "isDefault" option..

### Additional Information

See https://github.com/microsoft/vscode-cmake-tools/pull/2780#discussion_r1038154473 and https://github.com/microsoft/vscode-cmake-tools/pull/2780#discussion_r1066050839

**Comment by elahehrashedi** [comment]
@piomis I suggest combining the 3 PR and 3 issues into one. I will close the other 2 issues and we will follow the issue on this thread.

**Comment by piomis** [comment]
@elahehrashedi  as you wish.
I created 3 because I had idea how to fix two problems. In  regards to "template" tasks like I write in comment in previous PR I am not sure what was final intention as `isTemplate` property looks as unfinished.
