### ISSUE TITLE
Build task searching mechanism does not eliminate template tasks in search process and adds duplicate of original build template task to quick pick list 

### ISSUE THREAD

**Issue by piomis** [microsoft/vscode-cmake-tools#2936]
### Brief Issue Summary

This issue is continuation of issue https://github.com/microsoft/vscode-cmake-tools/issues/2778 and pull-request https://github.com/microsoft/vscode-cmake-tools/pull/2780
Newly merged implementation intention was to search among all tasks defined in tasks.json and at initial stage eliminate ones which are "template" tasks.

However currently these tasks are still included in search mechanism.
Additionally at the end all build tasks (ones from tasks.json + template tasks) should be displayed in QuickPick - it is working fine but additional "template" task is added to list. 

For details see https://github.com/microsoft/vscode-cmake-tools/pull/2780#discussion_r1066052934

**Comment by elahehrashedi** [comment]
I will close this issue and we will follow the improvements from here: https://github.com/microsoft/vscode-cmake-tools/issues/2935

**Comment by piomis** [comment]
@elahehrashedi 
Would it be sensible to re-open this issue? #2935 was closed with other two fixes (default task and cancellation) but not this particular one.
