### ISSUE TITLE
The arguments compile_commands did not include c++ standard.

### ISSUE THREAD

**Issue by Michaelzhouisnotwhite** [microsoft/vscode-cmake-tools#2947]
### Brief Issue Summary

The following pic shows the problems.

## Environment

my g++ version is: 12.2.0

cmake version is: 3.25.1

# Error Detail

I set cxx version in CMakeLists.txt: `set(CMAKE_CXX_STANDARD 17)` 

However, the compile_commands.json it generated did not include -std=gnu++17:

![image](https://user-images.githubusercontent.com/52443370/212897119-c2258a77-f353-48a1-aef3-806d0d9b59ea.png)

This problem cause my clangd extension can't diagnosis the code.

![image](https://user-images.githubusercontent.com/52443370/212897890-555d3a2a-42ec-49b1-96b4-1d9aaf46ce2f.png)

string_view is in c++17. the langrauge server did not know.

**Comment by elahehrashedi** [comment]
Did the CMake Tools extension generate this command file? if not, can you please share the fileApi file with us? the path to the file looks something like this: 
"`${workspaceFolder}\build\.cmake\api\v1\reply\target-envTest-Debug-62117f3e8a65ca9b8d89.json`", the file name starts with "`target`"

**Comment by Michaelzhouisnotwhite** [comment]
```json
{
	"artifacts" : 
	[
		{
			"path" : "LeetCoding.exe"
		},
		{
			"path" : "LeetCoding.pdb"
		}
	],
	"backtrace" : 1,
	"backtraceGraph" : 
	{
		"commands" : 
		[
			"add_executable",
			"target_include_directories"
		],
		"files" : 
		[
			"CMakeLists.txt"
		],
		"nodes" : 
		[
			{
				"file" : 0
			},
			{
				"command" : 0,
				"file" : 0,
				"line" : 7,
				"parent" : 0
			},
			{
				"command" : 1,
				"file" : 0,
				"line" : 8,
				"parent" : 0
			}
		]
	},
	"compileGroups" : 
	[
		{
			"compileCommandFragments" : 
			[
				{
					"fragment" : "-g"
				}
			],
			"includes" : 
			[
				{
					"backtrace" : 2,
					"path" : "D:/Repository/LeetCoding/src"
				}
			],
			"language" : "CXX",
			"languageStandard" : 
			{
				"backtraces" : 
				[
					1
				],
				"standard" : "17"
			},
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"id" : "LeetCoding::@6890427a1f51a3e7e1df",
	"link" : 
	{
		"commandFragments" : 
		[
			{
				"fragment" : "-g",
				"role" : "flags"
			},
			{
				"fragment" : "",
				"role" : "flags"
			},
			{
				"fragment" : "-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32",
				"role" : "libraries"
			}
		],
		"language" : "CXX"
	},
	"name" : "LeetCoding",
	"nameOnDisk" : "LeetCoding.exe",
	"paths" : 
	{
		"build" : ".",
		"source" : "."
	},
	"sourceGroups" : 
	[
		{
			"name" : "Source Files",
			"sourceIndexes" : 
			[
				0
			]
		}
	],
	"sources" : 
	[
		{
			"backtrace" : 1,
			"compileGroupIndex" : 0,
			"path" : "main.cpp",
			"sourceGroupIndex" : 0
		}
	],
	"type" : "EXECUTABLE"
}

```

**Comment by Michaelzhouisnotwhite** [comment]
Besides, as I set cxx standard to 20. The compile_commands.json is generated with -std=gnu++20. 

![image](https://user-images.githubusercontent.com/52443370/213102041-66129165-d3d8-4417-a845-70a8ef112fca.png)

**Comment by bobbrow** [comment]
Can you clarify what you are doing?  In the first message, you said `-std=gnu++17` was not being added to the `compile_commands.json` and now you show `-std=gnu++20` is added to `compile_commands.json`.  It appears that the CMake file api is being inconsistent in when it includes the flag in the compiler flags and when it doesn't.

**Comment by Michaelzhouisnotwhite** [comment]
That means it only happened when the cxx standard is set to 17. And c++11 20 doesn't have this issue. It's very strange.

> Can you clarify what you are doing? In the first message, you said `-std=gnu++17` was not being added to the `compile_commands.json` and now you show `-std=gnu++20` is added to `compile_commands.json`. It appears that the CMake file api is being inconsistent in when it includes the flag in the compiler flags and when it doesn't.

**Comment by Mo-way** [comment]
As this issue shows up on top of google: It's not a bug, it's a feature to leave out `-std` when the default is already correct. Starting with cmake 3.23 you can use `set(CMAKE_CXX_STANDARD 17)` to force it.
Source: https://discourse.cmake.org/t/cmake-does-not-set-the-compiler-option-std-to-gnu17-or-c-17-although-i-set-the-target-compile-features-to-cxx-std-17/3299/15
