### ISSUE TITLE
CMake Tools 1.13.40 fails to pick up CMakeUserPresets.json (only on first start after updating?)

### ISSUE THREAD

**Issue by floooh** [microsoft/vscode-cmake-tools#2952]
### Brief Issue Summary

After updating to 1.13.40, CMake Tools fails to pick up my CMakeUserPresets.json file, ```CMake: Build``` does nothing no build or debug target is selected, and selecting one is not possible, in short: nothing works :)

This happened to me both on macOS and Windows (so now the second time on Windows I'm writing this ticket).

...ok, weird: after setting the logging output to debug as requested below, and restarting, it suddenly worked.

AHA: starting another time it doesn't work again, really weird.

Then starting again, it picks up the configuration and now it seems like it's consistently working. Very confusing.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.74.3",
  "cmtVersion": "1.13.40",
  "configurations": [
    {
      "folder": "e:\\projects\\sokol-samples",
      "cmakeVersion": "3.25.1",
      "configured": false,
      "generator": "Visual Studio 17",
      "usesPresets": true,
      "compilers": {}
    },
    {
      "folder": "e:\\projects\\fips-imgui-dock",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "e:\\projects\\sokol",
      "cmakeVersion": "3.25.1",
      "configured": false,
      "generator": "",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [
      "file:///e%3A/projects/sokol/tests/compile/sokol_gfx.c",
      "file:///e%3A/projects/sokol/tests/compile/sokol_gfx.cc",
      "file:///e%3A/projects/sokol/sokol_gfx.h"
    ],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Debug Log

```shell
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Reading kits file C:\Users\floh\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 12 kits from C:\Users\floh\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Not reading non-existent kits file: e:\projects\sokol-samples\.vscode\cmake-kits.json
[presetController] Reading presets file E:\projects\sokol-samples\CMakeUserPresets.json
[presetController] Successfully validated presets in E:\projects\sokol-samples\CMakeUserPresets.json
[main] Resolving the selected configure preset
[main] Loading new configure preset into CMake driver
[main] Resolving the selected build preset
[main] Using generator from user configuration: Ninja
[main] Loading new build preset into CMake driver
[main] CMakeProject instance initialization complete.
[proc] Executing command: C:\Users\floh\scoop\shims\cmake.EXE --version
[main] Starting new CMake driver
[main] Starting CMake driver
[main] Using generator from user configuration: Ninja
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using preset
[driver] CMakeDriver configure preset set to default
[driver] CMakeDriver build preset set to default
[cache] Reading CMake cache file E:/projects/fips-build/sokol-samples/sapp-d3d11-win64-vscode-debug/CMakeCache.txt
[cache] Parsing CMake cache string
[driver] Setting new variant Debug
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: e:\projects\fips-imgui-dock\.vscode\cmake-kits.json
[main] CMakeProject instance initialization complete.
[main] Not starting CMake driver: no kit selected
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: e:\projects\sokol\.vscode\cmake-kits.json
[presetController] Reading presets file E:\projects\sokol\tests\CMakePresets.json
[presetController] Successfully validated presets in E:\projects\sokol\tests\CMakePresets.json
[main] CMakeProject instance initialization complete.
[main] Starting new CMake driver
[main] Starting CMake driver
[main] Using generator from user configuration: Ninja
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using preset
[driver] Setting new variant Debug
[extension] Attempting to use cache to configure workspace file:///e%3A/projects/fips-imgui-dock
[main] Not starting CMake driver: no kit selected
[main] Unable to configure with existing cache
[extension] Attempting to use cache to configure workspace file:///e%3A/projects/sokol
[extension] Attempting to use cache to configure workspace file:///e%3A/projects/sokol-samples
[main] Unable to configure with existing cache
[main] Unable to configure with existing cache
[cache] Reading CMake cache file E:/projects/fips-build/sokol-samples/sapp-d3d11-win64-vscode-debug/CMakeCache.txt
[cache] Parsing CMake cache string
[extension] [4033] cmake.selectBuildPreset started
[extension] [4033] cmake.selectBuildPreset finished (returned false)
[extension] [5561] cmake.selectBuildPreset started
[extension] [5561] cmake.selectBuildPreset finished (returned false)
[extension] [2661] cmake.launchTarget started
[rollbar] Invalid folder. {}
[rollbar] No active CMake project. {}
[extension] [2661] cmake.launchTarget finished (returned -2)
```

After pressing F7 for build:

```
[rollbar] Invalid folder. {}
[rollbar] No active CMake project. {}
[extension] [1164] cmake.build finished (returned -2)
```

### Additional Information

This is the CMakeUserPresets.json file:

```
{
  "version": 3,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 21,
    "patch": 0
  },
  "configurePresets": [
    {
      "name": "default",
      "displayName": "sapp-d3d11-win64-vscode-debug",
      "binaryDir": "E:/projects/fips-build/sokol-samples/sapp-d3d11-win64-vscode-debug",
      "generator": "Visual Studio 17",
      "architecture": "x64",
      "cacheVariables": {
        "CMAKE_EXPORT_COMPILE_COMMANDS": "ON",
        "CMAKE_BUILD_TYPE": "Debug",
        "FIPS_CONFIG": "sapp-d3d11-win64-vscode-debug",
        "FIPS_LOCAL_BUILD": "OFF",
        "USE_SOKOL_APP": {
          "type": "BOOL",
          "value": "ON"
        },
        "SOKOL_USE_D3D12": {
          "type": "BOOL",
          "value": "ON"
        },
        "FIPS_AUTO_IMPORT": "OFF"
      }
    }
  ],
  "buildPresets": [
    {
      "name": "default",
      "configurePreset": "default",
      "configuration": "Debug"
    },
    {
      "name": "debug",
      "configurePreset": "default",
      "configuration": "Debug"
    },
    {
      "name": "release",
      "configurePreset": "default",
      "configuration": "Release"
    }
  ]
}
```

**Comment by dbenson2000** [comment]
I hit the same issue and after struggling to get things working googled to find out how to install a previous version.
I had "cmake.useCMakePresets": "never" set but it still failed to find CMake settings.

**Comment by elahehrashedi** [comment]
@dbenson2000 we are investigating this issue, meanwhile, can you try reloading the window or running "CMake: Delete cache and reconfigure" to see if it works or not?

**Comment by vdilecce** [comment]
I experienced more or less the same problems with 1.13.40.

I tried running command `CMake: Reset CMake Tools Extension State`: it seemed to restore some sensible behavior, though since then the `CMake Project Outline` in the Activity Bar has gone completely empty (!?)

**Comment by elahehrashedi** [comment]
@vdilecce Can you please provide some more explanation on 1) the error message you see, 2) and the steps you took before seeing the error, 3) and also share the "Cmake: log diagnostics"? That will help us repro the issue.
I am not able to repro the issue with the steps mentioned by @floooh.

**Comment by bobbrow** [comment]
I tried to repro with the CMakeUserPresets.json you shared and a multi-root folder like the Log above showed, but was unable to hit the problem.  Based on the settings, it looked like 2 folders had cmake projects in them and one didn't.  The logs indicate that no project is active.  I'm not sure how the extension is getting into this state yet.

Possible workaround:
Click the little folder icon in the status bar 
![image](https://user-images.githubusercontent.com/12818240/213824096-b96a8291-2adb-4cf9-b2f2-9ddd189cc9d5.png)
or run the "CMake: Select Active Folder" command to pick a folder/project to be the active one.

If this successfully works around it, let us know.  And also let us know if there is text already in the statusbar that indicates one of the folders should have already been "active".

**Comment by bobbrow** [comment]
Actually, I think I have a repro.  It involves reloading the window when a file which is not in any of the workspace folders is focused.  Focusing any file from one of the workspace folders or using the other workarounds from my previous comment does address this problem.

**Comment by floooh** [comment]
@bobbrow I'm not 100% sure (since I couldn't reliably reproduce the issue anyway once it worked), but explicitely selecting the subproject might work. I had actually hidden this button in the status bar (because it was getting a bit too busy), otherwise I would probably had figured out that this was the issue hmm...

...maybe that's also a sign that CMake Tools shouldn't clutter the status bar like that ;) For instance maybe it makes sense to unify the build and debug target? It's kinda awkward that those are selected separately. Different topic though ;)

**Comment by kelteseth** [comment]
Can confirm selecting my presets is gone since the last update...

**Comment by bobbrow** [comment]
> @bobbrow I'm not 100% sure (since I couldn't reliably reproduce the issue anyway once it worked), but explicitely selecting the subproject might work. I had actually hidden this button in the status bar (because it was getting a bit too busy), otherwise I would probably had figured out that this was the issue hmm...
> 
> ...maybe that's also a sign that CMake Tools shouldn't clutter the status bar like that ;) For instance maybe it makes sense to unify the build and debug target? It's kinda awkward that those are selected separately. Different topic though ;)

We are working on #1582 for 1.14 which will remove the buttons from the status bar
