### ISSUE TITLE
cmake.debugConfig args console redirection broken

### ISSUE THREAD

**Issue by BobSmun** [microsoft/vscode-cmake-tools#2955]
### Brief Issue Summary

With the last update (1.13.40) when using `>` (and likely `<` too), it now gets passed to the console in quotes, which breaks the console redirection

`.vscode/settings.json` file:

```json
{
    "cmake.debugConfig": {
        "args": [
            ">", "log.txt"
        ]
    },
}
```

output: `test.exe ">" log.txt`

expected `test.exe > log.txt`

Seems like it would be related to `Quote launch arguments sent to the terminal if they have special characters. https://github.com/microsoft/vscode-cmake-tools/issues/2898`

**Comment by elahehrashedi** [comment]
We probably need to make a change in this function: https://github.com/microsoft/vscode-cmake-tools/blob/3236cc864b140c27651c5cf79caf0f34185b7370/src/shlex.ts#L80
