### ISSUE TITLE
Project using kits and variants doesn't work in 1.13.40

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cmake-tools#2963]
### Brief Issue Summary

Project using kits and variants doesn't work in 1.13.40

1. Create a CMake project without presets, in which case it should fall back to kits and variants.
2. Open project in VS Code and notice that the tool bar doesn't switch to kits and variants view, and none of the configure / build related commands work.
3. Multi-root with kits and variants doesn't work as well, not sure if that's also caused by this though.

**Comment by elahehrashedi** [comment]
This is the project that repro the issue:
azure-sphere-samples/Samples/HelloWorld/HelloWorld_HighLevelApp at main · Azure/azure-sphere-samples (github.com)

**Comment by elahehrashedi** [comment]
We are going to add a rename or delete event listener for CMakeLists.txt . We can add the presets files to the event listener as well (for the cases where `"cmake.useCMakePresets"` is set to `"auto"`.

Look at `onDidRenameFiles `events from here : https://github.com/microsoft/vscode-cmake-tools/pull/2946/files

**Comment by xisui-MSFT** [comment]
Ah yeah I was using an old version of that sample... So the actual steps:
1. Remove presets file from the project so it uses kits/variants.
2. Install Azure Sphere SDK: https://aka.ms/AzureSphereSDKDownload/Windows
3. Install Azure Sphere extension in VS Code
4. Open the project

I believe the reason this issue repros is that the Azure Sphere extension calls the following commands on activation, and causes a deadlock:
- cmake.setKitByName
- cmake.launchTargetPath
- cmake.hideLaunchCommand
- cmake.hideDebugCommand

> We can add the presets files to the event listener as well (for the cases where "cmake.useCMakePresets" is set to "auto".

I remember I wrote this? I'm probably wrong though since that's a long time ago.

**Comment by elahehrashedi** [comment]
By following the steps, I am able to see the kit menu in the status bar (in both situations where Azure Sphere extension is installed or not).

however, after installing your extension, I see this and I am not able to configure correctly:
![image](https://user-images.githubusercontent.com/16143955/214390304-cfda62b8-6756-465a-a77d-b5b10abd78ea.png)

**Comment by elahehrashedi** [comment]
I used another project with a CMakeLists.txt as below and I am able to configure without setting the kits:
```txt
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)
PROJECT(CMakeSample C)

azsphere_configure_tools(TOOLS_REVISION "22.11")
azsphere_configure_api(TARGET_API_SET "15")
```

![image](https://user-images.githubusercontent.com/16143955/214391464-49098b95-5228-46fd-aae5-419babfd9ecf.png)

**Comment by elahehrashedi** [comment]
@bobbrow The issue repro when I disable the Azure Sphere extension and enable it again, then the status bar starts showing presets options. 
A sample `settings.json` including Azure commands: 
```json
{
    "cmake.buildToolArgs": ["-v"],
    "cmake.buildDirectory": "${workspaceRoot}/out/${buildType}-${command:azuresphere.AzureSphereTargetApiSet}",
    "cmake.configureSettings": {
        "CMAKE_TOOLCHAIN_FILE": "${command:azuresphere.AzureSphereSdkDir}/CMakeFiles/AzureSphereToolchain.cmake",
        "AZURE_SPHERE_TARGET_API_SET": "latest-lts"
    },
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"
}
```
and a sample `CMakeLists.txt` : 
```txt
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)
PROJECT(CMakeSample C)

azsphere_configure_tools(TOOLS_REVISION "22.11")
azsphere_configure_api(TARGET_API_SET "15")

# Create executable
ADD_EXECUTABLE(${PROJECT_NAME} main.c)
```

**Comment by xisui-MSFT** [comment]
Call stack:
```
expandStringHelper (d:\CMakeTools\src\expand.ts:237)
expandString (d:\CMakeTools\src\expand.ts:113)
<anonymous> (d:\CMakeTools\src\drivers\cmakeDriver.ts:674)
await (Unknown Source:0)
doRefreshExpansions (d:\CMakeTools\src\drivers\cmakeDriver.ts:662)
_refreshExpansions (d:\CMakeTools\src\drivers\cmakeDriver.ts:666)
_baseInit (d:\CMakeTools\src\drivers\cmakeDriver.ts:1833)
processTicksAndRejections (internal/process/task_queues:96)
await (Unknown Source:0)
createDerived (d:\CMakeTools\src\drivers\cmakeDriver.ts:1849)
create (d:\CMakeTools\src\drivers\cmakeFileApiDriver.ts:67)
startNewCMakeDriver (d:\CMakeTools\src\cmakeProject.ts:778)
<anonymous> (d:\CMakeTools\src\cmakeProject.ts:1085)
await (Unknown Source:0)
<anonymous> (d:\CMakeTools\src\strand.ts:41)
Promise.then (Unknown Source:0)
_enqueue (d:\CMakeTools\src\strand.ts:18)
<anonymous> (d:\CMakeTools\src\strand.ts:39)
execute (d:\CMakeTools\src\strand.ts:38)
getCMakeDriverInstance (d:\CMakeTools\src\cmakeProject.ts:1070)
get binaryDir (d:\CMakeTools\src\cmakeProject.ts:2498)
checkBuildDirectories (d:\CMakeTools\src\projectController.ts:223)
createCMakeProjectsForWorkspaceFolder (d:\CMakeTools\src\projectController.ts:215)
await (Unknown Source:0)
addFolder (d:\CMakeTools\src\projectController.ts:272)
loadAllProjects (d:\CMakeTools\src\projectController.ts:199)
init (d:\CMakeTools\src\extension.ts:168)
create (d:\CMakeTools\src\extension.ts:212)
setup (d:\CMakeTools\src\extension.ts:1603)
activate (d:\CMakeTools\src\extension.ts:1793)
```

Need to check what's changed from 1.12

**Comment by xisui-MSFT** [comment]
I think the difference is in projectController.ts, line 215. Can we move checkBuildDirectories to after activation, or don't wait for it?
