### ISSUE TITLE
Support CMake Presets version 5

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#2979]
### Brief Issue Summary

requires cmake version 3.24.  It adds the following features:

https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html
`testOutputTruncation`

An optional string specifying the test output truncation mode. Equivalent to passing --test-output-truncation on the command line." This is allowed in preset files specifying version 5 or above.

`${pathListSep}`

Native character for separating lists of paths, such as : or ;.

For example, by setting PATH to /path/to/ninja/bin${pathListSep}$env{PATH}, ${pathListSep} will expand to the underlying operating system's character used for concatenation in PATH.

This is allowed in preset files specifying version 5 or above.

**Comment by nasinlock** [comment]
I've created a pull request for the functionality changes. I will be creating a second pull request to update the tests to account for the new functionality.
