### ISSUE TITLE
Not check targets and includes after configuration. (Since plugin version v1.13.40)

### ISSUE THREAD

**Issue by traversebitree** [microsoft/vscode-cmake-tools#2980]
### Brief Issue Summary

Since update to `v1.13.40`, "vscode-cpptools" not check whether target links and includes path exists.
For example
**Step 1 (Prepare)**:
![image](https://user-images.githubusercontent.com/30373236/215115983-7fdea988-24b0-486a-9aae-d7ec00b922d8.png)
![image](https://user-images.githubusercontent.com/30373236/215116316-2ae2f919-8757-4d33-8ea4-10ccef101d18.png)

**Step 2 (Bug appear)**:
![image](https://user-images.githubusercontent.com/30373236/215117055-5486f14c-f0a7-4481-9149-580ef2f550eb.png)
![image](https://user-images.githubusercontent.com/30373236/215117573-e802ef8c-cbef-4683-9ce7-f7a9bc5935aa.png)

**Step 3 (After build, it becomes normal)**:
![image](https://user-images.githubusercontent.com/30373236/215118000-78f34f72-fb59-44c1-8c4d-c4ce137271ff.png)
![image](https://user-images.githubusercontent.com/30373236/215118156-54bdbaee-475c-4693-a825-1d2049be610c.png)

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.74.3",
  "cmtVersion": "1.13.43",
  "configurations": [
    {
      "folder": "d:\\Workspace\\CPP\\CPPT001",
      "cmakeVersion": "3.25.2",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "gcc",
        "CXX": "g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Release",
    "buildTypesSeen": [
      "Release"
    ],
    "requests": [
      "file:///d%3A/Workspace/CPP/CPPT001/main.cpp"
    ],
    "responses": [
      {
        "uri": "file:///d%3A/Workspace/CPP/CPPT001/main.cpp",
        "configuration": {
          "includePath": [
            "d:/workspace/cpp/cppt001/extern/fmt_x64-mingw-static/include"
          ],
          "defines": [],
          "compilerPath": "c:/dev/tdm-gcc-64/bin/g++.exe",
          "compilerArgs": [],
          "compilerFragments": [
            "-O3 -DNDEBUG",
            "-std=gnu++2a"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 1,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "main",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Additional Information

Version `v1.12.x` and before, no this bug. The header check is done after **configuration**, not after build.

**Comment by elahehrashedi** [comment]
Thank you for reporting this issue. I can repro this in 1.13.xx versions. 
If the file is already open, after re-configure, the config provider is not updating the include paths.
If we reload the window, or build, or open a file that hasn't been already opened, the config provider will send the updated information.
