### ISSUE TITLE
Enable "Task" options in "Pinned" view.

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cmake-tools#2984]
### Brief Issue Summary

After transferring the extension's setting from the status bar to the sidebar, we need to add the "Task" options to the sidebar as well, and design a UI that makes it clear when we are using the "task" options for build or the "preset" options, or "kit".

And, currently, the configure that is running through the status bar is separate from the configure that is running using a task. Ideally, the user should be able to pick a config task (similar to when they pick a config preset setting) and the extension should use that task as a default for the next build (currently, only the "build" task that is followed by that "config" task will use that config task's setting).

related to: https://github.com/microsoft/vscode-cmake-tools/issues/1582

**Comment by sinemakinci1** [comment]
Spec done, this may need to be scoped to a v2 side bar
