### ISSUE TITLE
Update cmake.mingwSearchDirs documentation

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#2996]
@bobbrow Without the default value, the description isn't sufficient to understand the format of the setting, e.g. setting
```
"cmake.mingwSearchDirs": [
        "C:\\msys64\\mingw64\\bin"
    ]
```
doesn't work. The "\\bin" has to be removed. It may be helpful to others if the description included an example or something.

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cmake-tools/issues/2942#issuecomment-1414719064_

**Comment by bobbrow** [comment]
Sure, we could do that or fix it so that it works with `bin` in the path.

**Comment by sean-mcmanus** [comment]
@bobbrow Either seems fine to me.
