### ISSUE TITLE
CMake tools not fully loaded on workspace open

### ISSUE THREAD

**Issue by pm-ur** [microsoft/vscode-cmake-tools#3000]
### Brief Issue Summary

Since a recent update (1.13.43->1.13.45), opening a multi-folder workspace with a C++ project fails to load CMake Tools extension properly. I see the following output:
```
[kit] Successfully loaded 3 kits from /home/pm/.local/share/CMakeTools/cmake-tools-kits.json
[variant] Loaded new set of variants
[proc] Executing command: /usr/bin/cmake --version
[proc] Executing command: /usr/bin/gcc -v
[extension] We don't have an extension manager created yet. Feature set including CMake Tools commands palette is disabled.
```
All the CMake Tools buttons and infos in the status bar appear momentarily and then disappear on window load while extensions are being activated. Pressing `F7` doesn't build the project either. After I run CMake configure using command palette, I can see the status bar buttons etc and `F7` to build also works.
After loading workspace and before CMake Configure:
![image](https://user-images.githubusercontent.com/14093541/216687091-72be6ba5-67aa-418e-96af-ff53f4626b44.png)

After CMake Configure:
![image](https://user-images.githubusercontent.com/14093541/216686730-15c64136-5604-453a-b7c0-12ea7bb4e31b.png)

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.75.0",
  "cmtVersion": "1.13.45",
  "configurations": [
    {
      "folder": "/home/pm/d/ws/mino/controller",
      "cmakeVersion": "3.25.1",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/gcc",
        "CXX": "/usr/bin/g++"
      }
    },
    {
      "folder": "/home/pm/d/b/mino/controller/build",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Release",
    "buildTypesSeen": [
      "Release"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 79,
    "executablesCount": 15,
    "librariesCount": 46,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by pm-ur** [comment]
Tried pre-release version (1.14.6) too and it seems to be affected as well.

**Comment by elahehrashedi** [comment]
We will fix the initialization of the extension manager to make sure it is always available from the beginning.
