### ISSUE TITLE
Missing items in statusbar with icon visibility

### ISSUE THREAD

**Issue by orgonth** [microsoft/vscode-cmake-tools#3006]
### Brief Issue Summary

When the visibility is set to `icon`:
```json
"cmake.statusbar.visibility": "icon"
```

A couple of items are not visible in the status bar, namely:
- set the default build target
- select the target to launch

Of course, it's still possible to access these through the command palette.
Still, it would be great IMHO to make these items available in the status bar, e.g. with two new icons.

**Comment by elahehrashedi** [comment]
This is by design. We don't have icons for those.
you can use these settings as a workaround to keep those two visible:
```
"cmake.statusbar.advanced": 
{
        "buildTarget": {
            "visibility": "default"
        },
        "launchTarget": {
            "visibility": "default"
        }
}
"cmake.statusbar.visibility": "icon",
```
We are planning to remove the status bar in the future and move everything to the side panel for a better UI experience.
