### ISSUE TITLE
Bad cmake executable "". with last vscode update

### ISSUE THREAD

**Issue by PierreMarchand20** [microsoft/vscode-cmake-tools#3007]
### Brief Issue Summary

With the last update (1.75.0), cmake executable is not found. Reloading the windows does not seem to work, and cmake is in my path :
```
❯ which cmake
/opt/homebrew/bin/cmake
```

I could set it in my settings, but since it is in my path and it worked before, I guess it should work out of the box.

### CMake Tools Diagnostics

```shell
{
  "os": "darwin",
  "vscodeVersion": "1.75.0",
  "cmtVersion": "1.13.45",
  "configurations": [
    {
      "folder": "/***/htool_dev",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [
      "file:///***/block_tree.hpp",
      "file:///***/hmatrix.hpp"
    ],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by bobbrow** [comment]
I think we're missing some information.  If you have not set the `cmake.cmakePath` setting and you are not using a `configurePreset` that sets `cmakeExecutable`, then we do `which cmake` exactly as you would have done.  Can you confirm that you have not overwritten the setting (User or Workspace settings) or the property in your CMake presets file?

**Comment by PierreMarchand20** [comment]
I had no cmake preset and I had not set `cmake.cmakePath`, but after a few reload of my computer, it now works as before. I would not know how to reproduce so I will close the issue.
