### ISSUE TITLE
New problem can't be solved by the previous solution: syntax highlighted isn't supported in CMakeLists.txt

### ISSUE THREAD

**Issue by youfang11523868** [microsoft/vscode-cmake-tools#3011]
**Brief Issue Summary**
The CMake extension give me a message which is "Cannot register 'cmake.cmakePath'. This property is already registered.", and the extension couldn't provide the functionality called "syntax highlight". I take great pains to find the solution to this problem, but I didn't find it till now. If you know about it, please share with me.

**Expected**
When I open CMakeLists.txt, expected syntax highlight.

**CMake Tools Log**
![image](https://user-images.githubusercontent.com/71740544/217609658-91b46ded-2d2a-4855-88b7-979186334e85.png)
![image](https://user-images.githubusercontent.com/71740544/217609730-12460b1d-7bd1-49ef-b315-13a60324bdfb.png)

**Platform and Versions**
Operating System: Ubuntu 22.04
CMake Version: 3.22.1
VSCode Version: 1.75
CMake Tools Extension Version: 1.13.45
Compiler/Toolchain: Gcc 11.3.0 x86_64-linux-gnu

**Comment by bobbrow** [comment]
We are aware of the setting name conflict.  We see an actual popup message when we debug the extension, but the warning wasn't supposed to be visible to users.  Is it actually disabling the language services though?  I still get syntax highlighting and IntelliSense in my CMakeLists.txt.

I guess this is on Windows though.  I'll check and see if Ubuntu is any different for me.
![image](https://user-images.githubusercontent.com/12818240/217612576-0489afcd-bf38-41d7-9da2-cf7b7ebbb792.png)

**Comment by youfang11523868** [comment]
Thank you, and look forward your response again.

**Comment by bobbrow** [comment]
It works for me on Ubuntu too.  What theme are you using?

**Comment by youfang11523868** [comment]
material theme? I don't understand what you said.
![image](https://user-images.githubusercontent.com/71740544/217616939-b7d10b62-dd80-4d10-bead-9e3d02fc759d.png)

**Comment by youfang11523868** [comment]
Thank your help. 
How surprising and imperceptible the problem is !!!
It actually is because of the color theme. But if I persist on this theme as above, is there any way to provide syntax highlight?

**Comment by bobbrow** [comment]
Yes. That is it.  If you change to Dark+ or a built in theme, the keyword colors appear as expected.  If you want to report an issue to the theme extension, you can send them this information about the keyword colors:

![image](https://user-images.githubusercontent.com/12818240/217618174-402e3ff4-0274-4dad-9525-9033c7a29d5d.png)

If you want to override it for now, you can add something like this to your settings.json file:
```json
    "editor.tokenColorCustomizations": {
        "[Deepdark Material Theme | Default Version]": {
            "textMateRules": [
                {
                    "scope": [ "keyword.cmake" ],
                    "settings": {
                        "foreground": "#3333ba",
                        "fontStyle": "bold"
                    }
                }
            ]
        }
    }

```
