### ISSUE TITLE
Extension is not properly activated in multi project configuration

### ISSUE THREAD

**Issue by helo9** [microsoft/vscode-cmake-tools#3024]
### Brief Issue Summary

We have a codebase with two projects in the same workspace.
Both _CMakeLists.txt_ are listed in `cmake.sourceDirectory` within _settings.json_.
During creation of this setup, everything works fine.
After restart, the extension does not show up anymore in the _ActivityBar_. 
The _StatusBar_ is still displaying the extensions control elements for some of us. Clicking only triggers ExtensionActivation again.
A minimal setup showing that behavior can be found [here](https://github.com/helo9/minimal_cmake-tools_MultiList_example).
Is there something wrong with our setup, or is this a bug?

A known workaround is to remove one project list from the settings.json, restart and add it again to the list. When settings.json is saved, the extension updates and the multi root option works again.

### CMake Tools Diagnostics

```shell
Not possible - only triggers Extension Activation
```

### Debug Log

```shell
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Reading kits file C:\Users\%USER%\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 5 kits from C:\Users\%USER%\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Not reading non-existent kits file: c:\Users\Public\Software\vscode_cmake-tools_minimal_example\.vscode\cmake-kits.json
[main] Injecting new Kit into CMake driver
[main] CMakeProject instance initialization complete.
[main] Safe constructing new CMakeProject instance
[variant] Constructing VariantManager
[main] Constructing new CMakeProject instance
[main] Starting CMake Tools second-phase init
[variant] Loaded new set of variants
[kit] Not reading non-existent kits file: c:\Users\Public\Software\vscode_cmake-tools_minimal_example\.vscode\cmake-kits.json
[main] Injecting new Kit into CMake driver
[main] CMakeProject instance initialization complete.
[proc] Executing command: "C:\Program Files\CMake\cmake-3.22.2-windows-x86_64\bin\cmake.EXE" --version
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] Initializating base driver using kit
[kit] Testing GCC binary: C:\mingw-w64\x86_64-w64-mingw32\bin\x86_64-w64-mingw32-gcc.exe
[proc] Executing command: C:\mingw-w64\x86_64-w64-mingw32\bin\x86_64-w64-mingw32-gcc.exe -v
[kit] Detected GCC compiler: C:\mingw-w64\x86_64-w64-mingw32\bin\x86_64-w64-mingw32-gcc.exe
[driver] CMakeDriver Kit set to GCC 8.4.0 x86_64-w64-mingw32
[kit] The environment for kit 'GCC 8.4.0 x86_64-w64-mingw32': {
  %KITCONTENT%
}
[driver] Trying to detect generator supported by system
```

**Comment by elahehrashedi** [comment]
Thank you for reporting this issue. 
We are implementing a new sideBar feature that will replace the staus bar. https://github.com/microsoft/vscode-cmake-tools/pull/2993 This PR will probably solve this issue. When the feature is ready I will provide a VSIX for you to verify on your project.

**Comment by helo9** [comment]
Awesome, thank you ;)

**Comment by snehara99** [comment]
Hi @helo9, I believe this issue is fixed so I'm going to go ahead and close this. Please open a new issue if you encounter this issue again after upgrading to the latest pre-release, thanks!

**Comment by helo9** [comment]
sorry missed this conversation, but the issue is solved for me :)
