### ISSUE TITLE
CMake Tools status bar buttons are visible when non-cmake projects are open

### ISSUE THREAD

**Issue by bizzehdee** [microsoft/vscode-cmake-tools#3025]
### Brief Issue Summary

When i open up a python project, or a C++ project that has no cmakelists.txt file, or any other non-cmake based project, the cmake tools buttons still appear in the status bar. Can we have it so that the buttons appear selectively, based on whether or not there is a cmakelists.txt file in the root of a workspace/directory?

**Comment by bobbrow** [comment]
That is supposed to be the default behavior.  Can you run the "Developer: Startup Performance" command and share what you see in the "Extension Activation Stats" table for `vscode-cmake-tools`?  It will tell us why the extension is being activated.

**Comment by bizzehdee** [comment]
`| ms-vscode.cmake-tools                   | true  | 21        | 0             | 2166            | workspaceContains:*/CMakeLists.txt,*/*/CMakeLists.txt,*/*/*/CMakeLists.txt | ms-vscode.cmake-tools                   |`

1 of the projects, i have found to have a dummy cmakelists.txt deep down in its directory structure, but the others, i cannot find anything for at all.

**Comment by bobbrow** [comment]
What does the table say for the other projects?  Or are you opening a multi-folder workspace?

**Comment by bobbrow** [comment]
What should be happening for your project with the CMakeLists.txt in it is that the extension will activate and ask you to select a CMakeLists.txt that contains your project.  If you select one of the ones we found, then we update the `cmake.sourceDirectory` setting for you and the status bar should light up.  If you dismiss the prompt, the extension should disable most of its functionality, including the status bar.  I just tried this out on a new folder and it works the way I expect.  If the status bar is visible, then check to see if the `cmake.sourceDirectory` setting is set by accident and clear it.

**Comment by Longhanks** [comment]
> `| ms-vscode.cmake-tools | true | 21 | 0 | 2166 | workspaceContains:*/CMakeLists.txt,*/*/CMakeLists.txt,*/*/*/CMakeLists.txt | ms-vscode.cmake-tools |`
> 
> 1 of the projects, i have found to have a dummy cmakelists.txt deep down in its directory structure, but the others, i cannot find anything for at all.

This is happening for me as well, my project is not CMake based, but a library that is within the source directory as a submodule has a nested CMakeLists.txt somewhere in its directory tree, and this activates the `ms-vscode.cmake-tools` extension (`*/*/*/CMakeLists.txt` matches).

It would be great if there were a setting to only load the extension if CMakeLists.txt was chosen, or a setting in e. g. `C_cpp_properties.json` to disable it - setting `"configurationProvider": "none"` or `"configurationProvider": ""` does *not* disable loading of `ms-vscode.cmake-tools`.
