### ISSUE TITLE
Unable to find GDB in default search path and

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cmake-tools#3034]
Type: <b>Bug</b>

I am not sure if this is a real issue or I have a bad configuration. Whenever I click on the {bug} icon in the status bar I get:

> Unable to find GDB in default search path and /opt/homebrew/opt/ccache/libexec/lldb.

It is working for me if I start debugging form the side bar.

It was supposed to be fixed: 

- https://github.com/microsoft/vscode-cmake-tools/pull/1102
- https://github.com/microsoft/vscode-cmake-tools/issues/1060

My `launch.json`:

```json5
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(lldb) Launch",
      "type": "cppdbg",
      "request": "launch",
      // "program": "${workspaceFolder}/../build/default.debug.libcxx/LLVM-Testing",
      // Resolved by CMake Tools:
      "program": "${command:cmake.launchTargetPath}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${fileDirname}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "lldb"
    },
    {
      "name": "(lldb) Attach",
      "type": "cppdbg",
      "request": "attach",
      // "program": "${workspaceFolder}/../build/default.debug.libcxx/LLVM-Testing",
      // Resolved by CMake Tools:
      "program": "${command:cmake.launchTargetPath}",
      "MIMode": "lldb"
    },
    {
      "type": "lldb",
      "request": "launch",
      "name": "Launch",
      // "program": "${workspaceFolder}/../build/default.debug.libcxx/LLVM-Testing",
      // Resolved by CMake Tools:
      "program": "${command:cmake.launchTargetPath}",
      "args": [],
      "cwd": "${workspaceFolder}"
    },
  ]
}
```

Extension version: 1.13.45
VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|16.00GB (0.59GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30669238
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsccsb:30677849
pythonb192:30669360
funwalk2cf:30676044

```

</details>

**Comment by bobbrow** [comment]
Clicking the bug icon in the status bar ("quick debug") doesn't use your configurations from `launch.json`.  There is a setting `cmake.debugConfig` where you can override our heuristics if the quick debug feature is unable to determine the correct debugger.  The available properties should match what is supported by the `cppdbg` and `cppvsdbg` debug types.

Example:
```json
  "cmake.debugConfig": {
    "MIMode": "lldb"
  }
```
