### ISSUE TITLE
Is there any way to unset an env variable in cmake.buildEnvironment?

### ISSUE THREAD

**Issue by midhunpg** [microsoft/vscode-cmake-tools#3037]
I am trying to set up a CMake remote project. I am able to do it till the CMake configure step. But for performing the CMake build, I need to do "unset PYTHONHOME" and then initiate the CMake build command. I can't seem to find a way to do this currently. I can set PYTHONHOME as an empty string, but that is not working on the remote system. I need to explicitly unset the variable. Is there any way I can unset an env variable through settings.json?

**Comment by benmcmorran** [comment]
If you can use [CMakePresets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#build-preset) to configure your project, it should be possible to use the `environment` options to do what you want. From the docs (emphasis added):

> Environment variables are inherited through the `inherits` field, and the preset's environment will be the union of its own `environment` and the `environment` from all its parents. If multiple presets in this union define the same variable, the standard rules of `inherits` are applied. **Setting a variable to `null` causes it to not be set, even if a value was inherited from another preset.**

**Comment by midhunpg** [comment]
Thank you, that works.
