### ISSUE TITLE
Scanning for kits occurs too frequently

### ISSUE THREAD

**Issue by robotdad** [microsoft/vscode-cmake-tools#3046]
### Brief Issue Summary

The CMakeTools extension is scanning for kits on startup of any CMake project I open in VS Code. This scanning is interfering with proper configuration of the project I opened. I have to wait for the scan to complete and then clean reconfigure. It is unreasonable to think that I have installed a compiler in the time I closed one project and opened another.

Please place some limit on how often kits are scanned for, daily or weekly seems more appropriate. It also does not seem like something that needs to be done on startup if I already have kits configured. This would be far better as a background task.

**Comment by bobbrow** [comment]
Hmm... It should only scan once.  I believe we made a change to the Kits and forced a rescan, but it should have only happened one time.  We'll need to investigate.

**Comment by bobbrow** [comment]
I talked with Marc. This is a bug in the vscode-embedded-tools extension. It's forcing a kit scan when it initializes.
