### ISSUE TITLE
Requesting build causes extension crash

### ISSUE THREAD

**Issue by adorostkar** [microsoft/vscode-cmake-tools#3065]
Type: <b>Bug</b>

I added this as my settings.json

    {
        "cmake.configureOnOpen": false,
        "cmake.buildDirectory": 
        "${workspaceFolder}/projects/vscodeBuild"
    }

The configurations completes ok and I can build the code from terminal app with

    cmake --build projects/vscodeBuild

However, trying to build the code inside vscode with cmake extension causes the extension to crash.

Extension version: 1.13.45
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:54:09.061Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|20, 25, 24|
|Memory (System)|32.00GB (0.99GB free)|
|Process Argv|--crash-reporter-id c0b3aa38-222f-448e-9c01-635dab535476|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
azdwalk:30687957
pythonms35:30686772

```

</details>

**Comment by gcampbell-msft** [comment]
Thanks for letting us know about this issue. Could you provide us with some additional information and details that might help us repro and attempt to diagnose?

1) Is there a small version of your project that still repros that you're able to share with us? This will help us investigate.
2) Could you send us the CMake Tools Diagnostics information? You can see an example in this issue: #3061.

Thanks!

**Comment by adorostkar** [comment]
Unfortunately I can't provide anything regarding the project. 
Also even when I try to get the cmake log diagnostic I get a crash and extension manager restarts. Is there any other way to get this information out?

**Comment by mortenfc** [comment]
[Extension Host] [CMakeTools] 2024-03-27T13:00:12.472Z [debug] [expand] expanding cmake
log.ts:417  INFO Extension host (Remote) is unresponsive.

And then it crashes for me. So I guess my problem is related to WSL?
