### ISSUE TITLE
error when trying to build with cmake

### ISSUE THREAD

**Issue by dananothername** [microsoft/vscode-cmake-tools#3066]
### Brief Issue Summary

![Screenshot_2](https://user-images.githubusercontent.com/101902085/225979537-7a9b24a6-6afd-46c6-aa08-cf654d0f4954.png)
help 

### CMake Tools Diagnostics

```shell
CMake: : The term 'CMake:' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ CMake: Log Diagnostics
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (CMake::String) [], CommandNotFo  
   undException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Additional Information

cmake is installed well but somehow vsc error

**Comment by gcampbell-msft** [comment]
@dananothername Thanks for posting this issue, we'll look into it!

To help us, could you run the command `CMake: Log Diagnostics` within VSCode by using the command pallete? This should give us some information that may help us diagnose. 

Additionally, are you able to invoke cmake on a fresh command-line? It seems that the extension can't find the cmake executable. 

Thanks!

**Comment by gcampbell-msft** [comment]
Another thing to try is to set the `cmake.cmakePath` to the location of your cmake executable on disk. Let us know if these suggestions and questions help!

**Comment by dananothername** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/101902085/226650120-c3dd1fdd-c80a-47f9-b685-5cef4e5b8b4e.png)
about the vscode can't identify cmake executable yes i think so
while i already download cmake 
also by setting `cmake...` do you mean 
file/open folder /

**Comment by gcampbell-msft** [comment]
@dananothername If I'm understanding you correctly, yes, you should navigate to the VSCode Settings UI, and edit the CMake Tools setting for `cmake.cmakePath` to the location of your cmake exe.

1) Open the Command Pallete by navigating View -> Command Pallete
2) Start typing and then select "Preferences: Open Settings (UI)"
3) Enter "cmake.cmakePath" into the box. 
4) Edit the setting to point at your cmake installation. 

Additionally, could you provide some information about your system? What OS are you using, what version of VSCode, what version of the extension? 

Thanks!

**Comment by dananothername** [comment]
i am on windos 6
vsc 2019 
just downloaded this cmake 3.26.0
https://cmake.org/download/
after i set the cmake path
![Screenshot_2](https://user-images.githubusercontent.com/101902085/227209178-172c07aa-10ba-4909-abeb-baf44f79e6b7.png)
and trying to build it
![Screenshot_1](https://user-images.githubusercontent.com/101902085/227209337-84eac5ec-0bb1-4057-8a97-40dbb6f0224a.png)

this happens

**Comment by benmcmorran** [comment]
In order to use CMake, you need to have a both a compiler (like MSVC, GCC, or Clang) and a build system (like Ninja or MSBuild, known as generators in CMake) installed. What were you planning to use? A simple way to get started is by installing Visual Studio, which includes MSVC and Ninja.

**Comment by dananothername** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/101902085/227717154-9bbb00a4-8701-4765-834e-5a9a3f3fce9a.png)
https://stackoverflow.com/questions/4822400/register-an-exe-so-you-can-run-it-from-any-command-line-in-windows#comment46075436_4822427
ok after installing bunch of things its still not working

**Comment by benmcmorran** [comment]
Are you able to successfully use CMake to build your project on the command line outside of VS Code? If it's not working outside VS Code, then it means there's a configuration issue on your system that will need to be resolved before you can use CMake in VS Code.

Also, `cmake.cmakePath` should be the full path to `cmake.exe`, not just the directory containing the executable.
