### ISSUE TITLE
CMake Tools Crash Extension Host

### ISSUE THREAD

**Issue by edoren** [microsoft/vscode-cmake-tools#3070]
Type: <b>Bug</b>

I just installed the CMake Tools extension and it make fail the extension host.

Extension version: 1.13.45
VS Code version: Code 1.76.2 (Universal) (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:54:09.061Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 9, 11|
|Memory (System)|32.00GB (7.48GB free)|
|Process Argv|--crash-reporter-id 74b3f51c-c621-4596-8932-f1e7ba94051a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsccsb:30677849
pythonb192cf:30669361
functionswalk:30687959
pythonms35cf:30686773

```

</details>

**Comment by edoren** [comment]
I'm getting this on the Developer Tools console
```
workbench.desktop.main.js:90 [Extension Host] [CMakeTools] 2023-03-22T10:15:37.608Z [debug] [cache] Parsing CMake cache string
workbench.desktop.main.js:1670 Extension Host
workbench.desktop.main.js:1670 Debugger attached.
workbench.desktop.main.js:615  INFO UNRESPONSIVE extension host: starting to profile NOW
workbench.desktop.main.js:1670 Extension Host
workbench.desktop.main.js:1670 <--- Last few GCs --->[26514:0x148008000]    31466 ms: Mark-sweep 3960.1 (4092.1) -> 3955.3 (4094.8) MB, 1616.7 / 0.0 ms  (average mu = 0.355, current mu = 0.004) allocation failure; scavenge might not succeed[26514:0x148008000]    34755 ms: Mark-sweep 3963.0 (4094.8) -> 3958.1 (4097.8) MB, 3282.4 / 0.0 ms  (average mu = 0.152, current mu = 0.002) allocation failure; scavenge might not succeed<--- JS stacktrace --->[26514:0322/111608.412201:ERROR:node_bindings.cc(163)] Fatal error in V8: Reached heap limit Allocation failed - JavaScript heap out of memory
workbench.desktop.main.js:2605 Extension host (LocalProcess) terminated unexpectedly. Code: 11, Signal: unknown
```

**Comment by snehara99** [comment]
Hi @edoren , thank you for reaching out with this issue. Could you provide us with some additional information and details that might help us repro and attempt to diagnose?

1. Is there a small version of your project that still repros that you're able to share with us? This will help us investigate.
2. Could you send us the CMake Tools Diagnostics information? You can see an example in this issue: https://github.com/microsoft/vscode-cmake-tools/issues/3061. You can get this info by running the CMake: Log Diagnostics command.

Thanks!
