### ISSUE TITLE
Feature: add commands to obtain a list of targets and projects and compile_commands.json for each of them

### ISSUE THREAD

**Issue by iwannabekoshka** [microsoft/vscode-cmake-tools#3078]
### Brief Issue Summary

I suggest adding commands to obtain a list of available projects and their targets. I also suggest adding commands to obtain the compilation database (*compile_commands.json*) for each of them. 

For example:
-   `cmake.getAllProjects` returns a list of projects;
-   `cmake.getAllTargets` returns a list of targets for the specified project;
-   `cmake.getCompileDatabaseForProject` returns *compile_commands.json* for the specified project;
-   `cmake.getCompileDatabaseForTarget` returns *compile_commands.json* for the specified target.

### Additional Information

I’m developing a PVS-Studio extension for VSCode that will analyze projects. To run the analysis, I need to obtain *compile_commands.json*. Unfortunately, now this file can only be obtained for the entire project folder. 
I’d like to give users a possibility to check separate projects and their targets. To do this, I need *compile_commands.json* to be generated for separate projects/targets.

**Comment by gcampbell-msft** [comment]
@iwannabekoshka Thanks for the request!

Have you tried using the CMake extension API? You can try out using [this API ](https://www.npmjs.com/package/vscode-cmake-tools?activeTab=code) to interface with the extension and get most if not all of the information you've requested!

Feel free to try this out and let us know how it goes. 👍

Here is another link if you want to see it in-browser: https://npm.runkit.com/vscode-cmake-tools/api.ts?t=1679935012779.
