### ISSUE TITLE
Test results are reported incorrectly in some cases

### ISSUE THREAD

**Issue by guntern** [microsoft/vscode-cmake-tools#3082]
### Brief Issue Summary

When running the tests via the Test explorer some tests are marked as failed even though the output clearly states that, that all tests passed.

The tests are created using Catch2 and are made available to ctest via `catch_discover_tests`

### CMake Tools Diagnostics

```shell
{
	"os": "linux",
	"vscodeVersion": "1.77.0-insider",
	"cmtVersion": "1.14.20",
	"configurations": [
	  {
		"folder": "[REDACTED]",
		"cmakeVersion": "3.16.3",
		"configured": true,
		"generator": "Unix Makefiles",
		"usesPresets": false,
		"compilers": {
		  "C": "/usr/bin/gcc",
		  "CXX": "/usr/bin/g++"
		}
	  },
	  {
		"folder": "[REDACTED]",
		"cmakeVersion": "unknown",
		"configured": false,
		"generator": "unknown",
		"usesPresets": false,
		"compilers": {}
	  }
	],
	"cpptoolsIntegration": {
	  "isReady": true,
	  "hasCodeModel": true,
	  "activeBuildType": "Debug",
	  "buildTypesSeen": [
		"Debug"
	  ],
	  "requests": [
		"file:///[REDACTED]",
		"file:///[REDACTED]",
		"file:///[REDACTED]",
		"file:///[REDACTED]",
		"file:///[REDACTED]"
	  ],
	  "responses": [
		{
		  "uri": "file:///[REDACTED]",
		  "configuration": {
			"includePath": [
			  "/usr/include/eigen3",
			  "[REDACTED]",
			  "[REDACTED]",
			  "[REDACTED]",
			  "[REDACTED]"
			],
			"defines": [],
			"compilerPath": "/usr/bin/g++",
			"compilerArgs": [],
			"compilerFragments": [
			  "-g  ",
			  "-std=gnu++11"
			]
		  }
		},
		{
		  "uri": "file:///[REDACTED]",
		  "configuration": {
			"includePath": [
			  "/usr/include/eigen3",
			  "[REDACTED]",
			  "[REDACTED]",
			  "[REDACTED]",
			  "[REDACTED]"
			],
			"defines": [],
			"compilerPath": "/usr/bin/g++",
			"compilerArgs": [],
			"compilerFragments": [
			  "-g  ",
			  "-std=gnu++11"
			]
		  }
		},
		{
		  "uri": "file:///[REDACTED]",
		  "configuration": {
			"includePath": [
			  "/usr/include/eigen3",
			  "[REDACTED]",
			  "[REDACTED]",
			  "[REDACTED]"
			],
			"defines": [],
			"compilerPath": "/usr/bin/g++",
			"compilerArgs": [],
			"compilerFragments": [
			  "-g  ",
			  "-std=gnu++11"
			]
		  }
		},
		{
		  "uri": "file:///[REDACTED]",
		  "configuration": {
			"includePath": [
			  "/usr/include/eigen3",
			  "[REDACTED]",
			  "[REDACTED]",
			  "[REDACTED]",
			  "[REDACTED]"
			],
			"defines": [],
			"compilerPath": "/usr/bin/g++",
			"compilerArgs": [],
			"compilerFragments": [
			  "-g  ",
			  "-std=gnu++14"
			]
		  }
		}
	  ],
	  "partialMatches": [],
	  "targetCount": 42,
	  "executablesCount": 7,
	  "librariesCount": 6,
	  "targets": []
	},
	"settings": [
	  {
		"communicationMode": "automatic",
		"useCMakePresets": "auto",
		"configureOnOpen": true
	  },
	  {
		"communicationMode": "automatic",
		"useCMakePresets": "auto",
		"configureOnOpen": null
	  }
	]
  }
```

### Additional Information

I suspect the issue is realted to similar namings of two tests. One test is named `getPosition` and the other is named `Spline: getPosition`.

The one falsly reported as failed it the `getPosition`. This is also the only test, which actually runs two tests (the both mentioned aboth), when run. All other tests run on their own.

When changing the name to `getTestPosition` all tests are reported with the correct result.

**Comment by gcampbell-msft** [comment]
@xisui-MSFT

**Comment by xisui-MSFT** [comment]
CTest -R is a regex match, and I kind of forgot this after writing the command arguments. I'll add line start and end to the regex.

**Comment by guntern** [comment]
@benmcmorran : I now have cmtVersion 1.14.21. Would this be the version matching #3084? (I do not see where the version numbers change). I am asking, because the behavior is still the same and the test is reported as failed.

**Comment by benmcmorran** [comment]
The fix should be in version `1.14.22`. We publish pre-release builds nightly, so you probably just missed getting the new build last night.

**Comment by guntern** [comment]
Tested today with 1.14.22. I do see the new regex-Expressions in the test calls. And now its indeed always only one test, which runs in an individual call. However, the tests are still reported as failed, even though, the output states that they ran successfully.

I will try to find some time to set up a test repo to reproduce this behavior.

**Comment by guntern** [comment]
I am puzzled. I built a test repo this morning. And it worked fine. So I checked with the original workspace, which also worked fine. Switching back and forth between Version 1.14.21, .22 and .23 it always worked with 1.14.22 and .23 - both with WSL and under Windows. I have no idea why it was not working yesterday.
My apologies.
