### ISSUE TITLE
Cannot run cmake behind a proxy.

### ISSUE THREAD

**Issue by dev-techmoe** [microsoft/vscode-cmake-tools#3086]
### Brief Issue Summary

I'm new for cpp programming and I'm living in Mainland China, it's a magic country where can't connect to Github and many other online infrastructure directly, unlucky my project is using FetchContent module to fetch some dependencies from Github. If I running `build` manually, I can set proxy by running `export HTTPS_PROXY="..."` to make cmake connect with proxy, but I cant set this env in our CMake Tools extension （`ms-vscode.cmake-tools`）, anyway to do this? Or perhaps we need a option to set env for cmake process? (I tried set `cmake.buildEnvironment` but does not work), thank you.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.76.2",
  "cmtVersion": "1.13.45",
  "configurations": [
    {
      "folder": "/mnt/dev/cpp-journey",
      "cmakeVersion": "3.26.1",
      "configured": false,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/gcc",
        "CXX": "/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///mnt/dev/cpp-journey/headers/myheader.h",
      "file:///mnt/dev/cpp-journey/src/main.cc"
    ],
    "responses": [
      {
        "uri": "file:///mnt/dev/cpp-journey/src/main.cc",
        "configuration": {
          "includePath": [
            "/mnt/dev/cpp-journey/headers",
            "/mnt/dev/ext",
            "/mnt/dev/cpp-journey/ext",
            "/mnt/dev/cpp-journey/ext/fmtlib/include"
          ],
          "defines": [
            "FMT_SHARED"
          ],
          "compilerPath": "/usr/bin/g++",
          "compilerArgs": [],
          "compilerFragments": [
            "-g"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 37,
    "executablesCount": 3,
    "librariesCount": 4,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}

```

### Debug Log

```shell
N/A
```

**Comment by benmcmorran** [comment]
Thanks for the report! Does it work for you to use the [`environment` option in a `CMakePresets.json` file](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#configure-preset)? That should work for both configure presets and build presets, and will set environment variables for the CMake process.
