### ISSUE TITLE
[zh-TW] Suggest that "Configure" be translated into "組態".

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode-cmake-tools#3101]
### Suggestion

* **English String:** Configure
* **Current Translation:** 設定
* **Suggested Translation:** 組態

There's a corresponding issue that I posted in vscode-loc: https://github.com/microsoft/vscode-loc/issues/1309

### Version

* **CMake Tools Version:** `v1.14.24`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/230438844-855d5397-fc87-4794-94c8-6d4dd57d7f98.png)

**Comment by gcampbell-msft** [comment]
@csigs Could you take a look at this?

**Comment by gcampbell-msft** [comment]
@hwhsu1231 After an internal review and discussing with our localization team, the decision has been made that the current translation is appropriate. 

Thank you for your suggestion, but we are closing this issue as "won't fix", based on our internal review results. 

Thanks again!
