### ISSUE TITLE
CMake Tools Cannot Debug - Access Denied

### ISSUE THREAD

**Issue by atom0s** [microsoft/vscode-cmake-tools#3116]
### Brief Issue Summary

I recently purchased a new laptop and installed VSCode Insiders. I have several other systems I also use for development work thus I make use of the built-in Sync features to ensure all systems have the same extensions and settings installed.

This new laptop is running Windows 11 Pro 22H2 (Windows_NT x64 10.0.22621) and has issues with the CMake Tools extension not being able to debug any project unless VSCode is ran as an administrator. This issue does not happen on any of my other machines. (Windows 8.1 and Windows 10 on various versions.)

To reproduce the issue on this machine:

1. Install Windows 11. (Again, my laptop is Windows 11 Pro 22H2 installed within the last month.)
2. Install VSCode Insiders using the 'System Installer'.
3. Install CMake Tools extension and C++ developer tools/extension.
4. Create any basic kind of project that will produce an executable file.
5. Build the project.
6. Click the 'Bug' icon on the CMake Tools bottom toolbar to attempt to debug the project.

At this point, VSCode will attempt to begin the debug session but fail with the following popup error in the bottom right:
```
Unable to start program '<Path to your project>\<projname>.exe'. Access is denied.
```

However, if I run VSCode as an Administrator (right-click > Run as Administrator on the VSCode - Insiders.exe) then this issue does not happen and it works as normal. This is not the case on any other machine I have, I can debug any project without having to run as admin.

It does not matter what folder the project resides in, meaning it is not a permissions issue that I am aware of. I have tested placing the project folder in all kinds of locations with different access levels, I have also ensured that I have ownership of said folders and parent folders to ensure that it is not a permissions issue. 

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.78.0-insider",
  "cmtVersion": "1.13.45",
  "configurations": [
    {
      "folder": "c:\\SourceCode\\GitHub\\atom0s\\project_name_here",
      "cmakeVersion": "3.25.1",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "cl.exe",
        "CXX": "cl.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 1,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "project_name_here",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by benmcmorran** [comment]
Thanks for the report! To help us investigate if this is an issue with the CMake Tools or C/C++ extension, can you try adding a [simple `launch.json` file to your project](https://code.visualstudio.com/docs/cpp/launch-json-reference) that debugs the executable you just built? If that doesn't work, then the issue is likely with C/C++ extension. The example below assumes you are using MSVC as your compiler, but check the docs for how to set this up for other compilers.

```json
{
  "name": "C++ Launch (Windows)",
  "type": "cppvsdbg",
  "request": "launch",
  "program": "<path to exe>",
  "externalConsole": true,
  "logging": {
    "trace": true
  }
}
```

**Comment by atom0s** [comment]
Running VSCode Insiders with a launch.json has the same issue. The console will open/popup and just say:
```
Press any key to continue . . .
```

VSCode will also say the same 'Unable start program' with 'Access Denied.' error popup. Also, if I run VSCode Insiders as admin, then the launch.json configuration works as expected.
