### ISSUE TITLE
Cant quick debug with clang from winlibs

### ISSUE THREAD

**Issue by Hyderman** [microsoft/vscode-cmake-tools#3119]
### Brief Issue Summary

I can build and run the project with clang bug I can't debug with it.
I saw some post talking about lldb-mi but winlibs has it built in.

A comparison between gcc and clang debug console :

clang++:

Loaded 'C:\Users\logan\Desktop\New folder\build\myProject.exe'. 
Loaded 'C:\Windows\System32\ntdll.dll'. 
Loaded 'C:\Windows\System32\kernel32.dll'. 
Loaded 'C:\Windows\System32\KernelBase.dll'. 
Loaded 'C:\Windows\System32\ucrtbase.dll'. 
Loaded 'C:\Users\logan\scoop\apps\mingw-winlibs-llvm-ucrt\12.2.0-16.0.0-10.0.0-r5\bin\libstdc++-6.dll'. Module was built without symbols.
Loaded 'C:\Users\logan\scoop\apps\mingw-winlibs-llvm-ucrt\12.2.0-16.0.0-10.0.0-r5\bin\libgcc_s_seh-1.dll'. 
Loaded 'C:\Users\logan\scoop\apps\mingw-winlibs-llvm-ucrt\12.2.0-16.0.0-10.0.0-r5\bin\libwinpthread-1.dll'. Module was built without symbols.
Hello, world!
Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
Loaded 'C:\Windows\System32\msvcrt.dll'. 
The program '[6444] myProject.exe' has exited with code 0 (0x0).

g++:

Thread 1 hit Breakpoint 2.2, _GLOBAL__sub_I_main () at C:\Users\logan\Desktop\New folder\src\main.cpp:5
5	}
Loaded 'C:\WINDOWS\SYSTEM32\ntdll.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\System32\kernel32.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\System32\KernelBase.dll'. Symbols loaded.
Loaded 'C:\WINDOWS\System32\ucrtbase.dll'. Symbols loaded.
Loaded 'C:\Users\logan\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\libstdc++-6.dll'. Symbols loaded.
Loaded 'C:\Users\logan\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\libgcc_s_seh-1.dll'. Symbols loaded.
Loaded 'C:\Users\logan\scoop\apps\mingw-winlibs-llvm-ucrt\current\bin\libwinpthread-1.dll'. Symbols loaded.
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.77.3",
  "cmtVersion": "1.14.29",
  "configurations": [
    {
      "folder": "c:\\Users\\logan\\Desktop\\New folder",
      "cmakeVersion": "3.26.3",
      "configured": true,
      "generator": "MinGW Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "C:/Users/logan/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/clang.exe",
        "CXX": "C:/Users/logan/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/clang++.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

**Comment by benmcmorran** [comment]
Thanks for the report. To help us diagnose this issue, can you provide the contents of your `launch.json` configuration, and can you add this snippet to the configuration to enable verbose MIEngine logging? After trying to run the debugger, please provide the content of the debug console which will include this verbose logging.

```json
"logging": {
  "engineLogging": true
},
```

**Comment by Hyderman** [comment]
I don't use any launch.json. I don't know where I can find the default launch.json used by quick debug to test logging.
If you give it to me, I could try the logging setting.

**Comment by benmcmorran** [comment]
Can you create a [launch.json](https://code.visualstudio.com/docs/cpp/launch-json-reference) or tell us which commands you run to start your debugging session?

**Comment by Hyderman** [comment]
![image](https://github.com/microsoft/vscode-cmake-tools/assets/81628944/7f5c449e-1514-4a6a-a9d2-b9a63e4c0c3c)

**Comment by bobbrow** [comment]
I don't have the full context, but to override the defaults for quick debugging, you can use the `cmake.debugConfig` setting in `settings.json`.  If lldb-mi is built in to your debugger or you know where it exists on the machine, then you might want to try setting something like this in your settings:

```json
{
  "cmake.debugConfig": {
    "MIMode": "lldb",
    "miDebuggerPath": "C:/path/to/lldb-mi"
  }
}
```

**Comment by gcampbell-msft** [comment]
@Hyderman Have you been able to attempt the above suggestion? Please let us know if there is anything else we can help with. 

Thanks.
