### ISSUE TITLE
CMAKE_MODULE_PATH in VSCode user settings

### ISSUE THREAD

**Issue by wenglorfranz** [microsoft/vscode-cmake-tools#313]
### Current Behaviour

In settings.json I set
```
"cmake.configureSettings": {
        "CMAKE_MODULE_PATH":"/opt/toolchain/cmake",
        "CMAKE_TOOLCHAIN_FILE":"/opt/toolchain/cmake/Toolchains/x86_64-Linux.cmake",
        "CMAKE_PREFIX_PATH":"${workspaceRoot}/_install",
        },
```

When I start cmake from VSCode, I get this inside InitializeCache.cmake

```
# This file is generated by CMake Tools! DO NOT EDIT!
cmake_policy(PUSH)
if(POLICY CMP0053)
   cmake_policy(SET CMP0053 NEW)
endif()
set(CMAKE_MODULE_PATH "/;o;p;t;/;t;o;o;l;c;h;a;i;n;/;c;m;a;k;e;/home/user/workspace/hilscher/_build/CMakeTools" CACHE STRING "Variable supplied by CMakeTools. Value is forced." FORCE)
set(CMAKE_TOOLCHAIN_FILE "/opt/toolchain/cmake/Toolchains/x86_64-Linux.cmake" CACHE STRING "Variable supplied by CMakeTools. Value is forced." FORCE)
set(CMAKE_PREFIX_PATH "/home/user/workspace/hilscher/_install" CACHE STRING "Variable supplied by CMakeTools. Value is forced." FORCE)
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Variable supplied by CMakeTools. Value is forced." FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS "TRUE" CACHE BOOL "Variable supplied by CMakeTools. Value is forced." FORCE)
cmake_policy(POP)
```

### Expected Behaviour

What I would expect:
`set(CMAKE_MODULE_PATH "/opt/toolchain/cmake;/home/user/workspace/hilscher/_build`

### VSCode Log

> [vscode] Setting up new CMake configuration
> [vscode] Configuring using the "Eclipse CDT4 - Unix Makefiles" CMake generator
> Execute cmake with arguments: -GEclipse CDT4 - Unix Makefiles,-DCMAKE_INSTALL_PREFIX=/home/user/workspace/hilscher/_install,-C/home/user/workspace/hilscher/_build/CMakeTools/InitializeCache.cmake,-DBUILD_SHARED_LIBS=ON,-H/home/user/workspace/hilscher,-B/home/user/workspace/hilscher/_build
> [vscode] Executing command: cmake "-GEclipse CDT4 - Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/home/user/workspace/hilscher/_install -C/home/user/workspace/hilscher/_build/CMakeTools/InitializeCache.cmake -DBUILD_SHARED_LIBS=ON -H/home/user/workspace/hilscher -B/home/user/workspace/hilscher/_build
> loading initial cache file /home/user/workspace/hilscher/_build/CMakeTools/InitializeCache.cmake

### Platform and Versions

- **Operating System**: OpenSuseLeap 42.1
- **CMake Version**: 3.3.2
- **VSCode Version**: 1.20.0
- **CMake Tools Extension Version**: 0.10.4
- **Compiler/Toolchain**: gcc 4.8.5

May also be relevant to #304

**Comment by Randshot** [comment]
Is this still a problem in the latest **0.11.-beta4**? My project that uses `CMAKE_MODULE_PATH` works without any problems.

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been addressed. If you require further assistance, please let us know and we can reopen it.
