### ISSUE TITLE
Extension unusable, enters error loop

### ISSUE THREAD

**Issue by maciekgajewski** [microsoft/vscode-cmake-tools#3131]
Type: <b>Bug</b>

It looks like the extension is trying to do some RPC call, and fails perpetually. Configuring or building code is impossible.

It prints these lines in output forever:

```
[rollbar] Unhandled exception: Failed to open CMake cache file on code model update SyntaxError: Unexpected token l in JSON at position 0 {}
[proc] Executing command: /opt/rh/gcc-toolset-10/root/usr/bin/gcc -v
[cmakefileapi-driver] This version of CMake does not support the "toolchains" object kind. Compiler paths will be determined by reading CMakeCache.txt.
[rollbar] Unhandled exception: Failed to open CMake cache file on code model update SyntaxError: Unexpected token l in JSON at position 0 {}
```

Extension version: 1.15.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:52.732Z)
OS version: Linux x64 5.15.0-70-generic snap
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (12 x 3792)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 3, 6|
|Memory (System)|23.42GB (18.54GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 81e4a98f-281a-4f6b-ab11-e2499817e43a|
|Screen Reader|no|
|VM|33%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container|
|OS|Linux x64 5.15.0-70-generic|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (12 x 3792)|
|Memory (System)|23.42GB (18.54GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
6233i204:30672705
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by gcampbell-msft** [comment]
@maciekgajewski Thanks for the issue! Could you provide us with some more information to help us try and investigate this? 

Are files being populated in the CMake File API response? This can be found in `.cmake/api/v1/reply/.....`. This will typically be found in your build location. 

Additionally, can you run the `CMake: Log DIagnostics` command and send the output?

**Comment by maciekgajewski** [comment]
Yes, the reply files are generated; looks like roughly one per target.

The diagnostic:
```
{
  "os": "linux",
  "vscodeVersion": "1.77.3",
  "cmtVersion": "1.15.0",
  "configurations": [
    {
      "folder": "/workspace/project/project",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by maciekgajewski** [comment]
After executing `CMake: Reset CMake Tools Extensions State (for troubleshooting)`, the extension does noting when trying to configure the project. Even after restarting VSCode.

I checked the validity of json files in `.cmake/api/v1/reply/`, and they all seem fine (according to `jq`).

**Comment by MrTroble** [comment]
Same issue here, out of the sudden it got stuck in this error loop.

**Comment by MrTroble** [comment]
> Downgrading the extension to 1.13.45 solves the problem.

Confirmed that this helps (thank you saved my day)

**Comment by snehara99** [comment]
Hi @maciekgajewski, would you be able to provide a sample project that produces this error? I am unable to reproduce the issue on my end.

**Comment by maciekgajewski** [comment]
I'm sorry, I'm unable to share the code.
