### ISSUE TITLE
Latest Cuda/Optix file changes not been copied for new build, but cmake works fine alone

### ISSUE THREAD

**Issue by iaomw** [microsoft/vscode-cmake-tools#3134]
### Brief Issue Summary

It's a C++ project with many *cu file, new changes are not been copied for new build. It's always building the old *.cu files.

However, this problem never happen when using CMake directly. So I assume, the cmake config is correct. 

I guess it's possible to solve this by some parameter. If that's the case, Please let me know.

**Comment by gcampbell-msft** [comment]
@iaomw Could you provide some more information that would help us start to investigate?

Some information that would help us:
1. A repro project that we could unzip and repro with.
2. The output from the result of the `CMake: Log Diagnostics` command
3. More information regarding your system configuration and versions. 

When we have more information to investigate with we'll be happy to look into this!
