### ISSUE TITLE
Side panel: add configure and build buttons for each folder

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cmake-tools#3137]
### Brief Issue Summary

Got this feedback from a customer. Currently the only way building another folder is to select a folder as active folder, and then run configure/build commands. But since the side panel shows all the folders, it would be better to add configure and build buttons for each folder, so avoiding switching active folders.

**Comment by benmcmorran** [comment]
Thanks for the feature request. @snehara99 I'm assigning you for now since you were doing sidebar work earlier and marking this for 1.15.
