### ISSUE TITLE
Debug a Googletest testcase from the Testing interface gives error

### ISSUE THREAD

**Issue by NoMore201** [microsoft/vscode-cmake-tools#3141]
If I try to debug a single test case through the Testing panel by clicking the "Debug Test" icon, test starts but nothing happens. Output of the test result windows stays empty, an error message is shown and it will be stuck like this forever:

![image](https://user-images.githubusercontent.com/3220188/234579692-e761dca0-1626-487e-833d-8f16b83288a7.png)

I tried to configure a debug launch configuration as explained [here](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md#debug-using-a-launchjson-file), but it doesn't work. If I understood that page correctly, it works only with the test executable currently selected as "launch target".

It happens on any CMake project using googletest I have on my machine. Running and debugging test executables separately works perfectly fine.

Information:
OS: Windows 10
Visual Studio Code 1.77.3
CMake Tools extension 1.14.30

**Comment by gcampbell-msft** [comment]
@NoMore201 Could you test this again in the most recent CMake Tools version? I believe it should be fixed.

**Comment by gcampbell-msft** [comment]
Based on last comments, this should be fixed. If not, @NoMore201 Could you please create a new issue with more context and a repro project? Thanks.
