### ISSUE TITLE
Run tests as a single CTest invocation

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vscode-cmake-tools#3149]
### Brief Issue Summary

I wasn't too excited to hear that CMake Tools started biting into Test Explorer integration, because Frederic Bonnet's [CMake Test Explorer](https://github.com/fredericbonnet/cmake-test-explorer) is an otherwise stellar extension doing the same thing and he has already fixed a lot of the issues CMake Tools is just about to encounter.

One of these issues is CMake Tools (like Frederic's extension initially) wanted to outsmart CTest and launch tests using various CTest invocations. The problem with this is that it breaks a lot of CTest functionality around Resource Awarness, Resource Locks and Fixtures. [This](https://github.com/fredericbonnet/cmake-test-explorer/issues/23) issue of mine on his repo details what the problem is, but the gist of it is that it is virtually impossible to run tests in any other way than a single ctest CLI invocation without breaking test execution.

I am aware that CMake Tools advertized that initially tests can't run in parallel, however I wanted to note that however CMake Tools wishes to move forward, it should probably be formulating a single CLI invocation based on user input. CTest does a whole bunch of test provisioning that is extremely hard (if not impossible) to re-implement from outside. @xisui-MSFT

**Comment by gcampbell-msft** [comment]
@MathiasMagnus FYI, I have a PR out now that allows users to disable the Test Explorer integration. So, I'd love for you to, once this change is released, test this out again!

**Comment by hippo91** [comment]
@gcampbell-msft i think this issue is solved by #3577. Am I wrong?

**Comment by gcampbell-msft** [comment]
@hippo91 You are correct. I'll mark this as `fixed-pending-release`. Thanks!
