### ISSUE TITLE
Add a way to run a test preset

### ISSUE THREAD

**Issue by quyykk** [microsoft/vscode-cmake-tools#3151]
### Brief Issue Summary

After the test explorer feature, it looks like I can't run a test preset anymore. Clicking on "Run CTest" just opens the test explorer with a list of tests, instead of running the selected test preset like it was before. 

I also couldn't find a way to run the selected test preset in any other way.

**Comment by xisui-MSFT** [comment]
I think clicking the run all tests button (or run test button for a certain folder) after the test explorer opens runs the tests under the currently selected test preset?

**Comment by quyykk** [comment]
>after the test explorer opens

So I have to click the button twice? That seems not great (Sorry I can't test it right now)

**Comment by xisui-MSFT** [comment]
No, there's a run all button in the test explorer.

**Comment by gcampbell-msft** [comment]
@snehara99 I have moved this to the 1.16 release and milestone. It seems that this may be more of a request on the status bar button action to do a direct action rather than open the Test Explorer.

We will triage and assess our course of action in 1.16.

**Comment by snehara99** [comment]
We are working on a fix for this issue, but in the meantime you should be able to run your test presets using the Project Status View

**Comment by snehara99** [comment]
Hello @quyykk, if you install the newest version of the pre-release channel, you should now be able to use the `Run CTests` button like before, bypassing the test explorer. Please try it out and let me know if this solves your issue, thanks!

**Comment by snehara99** [comment]
Hello this feature should now be available on the main channel, so I'm going to close this issue as complete. Please create a new issue if you encounter any new problems or if you have other requests. Thanks!
