### ISSUE TITLE
Per-folder browse configurations incorrectly contain paths from other workspace folders

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cmake-tools#3155]
The [C/C++ extension API](https://github.com/microsoft/vscode-cmake-api) provides an way (`canProvideBrowseConfigurationsPerFolder` field) for a configuration provider to indicate that it can provide a separate 'browse configuration' per workspace folder in multi-root scenarios.  CMake Tools is providing a value of true for this, and is returning results from calls to `provideFolderBrowseConfiguration`.

We're seeing that CMake Tools incorrectly includes paths from workspace folder A in the browse paths for workspace folder B. 

This causes a problem with exclusions.  It's possible that workspace folder A may have excluded some subdirectories of its browse paths.  When those same paths get associated with another folder, those exclusions are bypassed (not defined by the other workspace folder), resulting in files being parsed into the browse database that should have been excluded.

**Comment by gcampbell-msft** [comment]
@Colengms Do you possibly have an example project for a repro of this issue?
