### ISSUE TITLE
Option to split test names for tree-like view

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode-cmake-tools#3156]
### Brief Issue Summary

The new test explorer integration (#3032) is great, but it puts all the tests in one long list. It would be great to have an option (similar to https://github.com/fredericbonnet/cmake-test-explorer#:~:text=cmakeExplorer.suiteDelimiter) to split test names into a tree-like list. Even better would be to allow for multiple such delimiters (for example, googletest uses both '.' and '/' for different levels of test names)

**Comment by jhuels** [comment]
This would be awesome.  Can't seem to get CMake Test Explorer to work anymore since the CMake Tools test explorer integration landed, so I've been using C++ TestMate (https://marketplace.visualstudio.com/items?itemName=matepek.vscode-catch2-test-adapter) in the meantime just for this grouping feature

**Comment by tristanlabelle** [comment]
Hi @gcampbell-msft (we meet again!). We're interested in this feature at The Browser Company. Is this already in the works, or would you accept a community contribution PR? If so, would the release cadence mean that the feature would be published within a month of the PR merging? Thanks!

**Comment by vinocher-bc** [comment]
@Evelyn-001 FYI, a PR has been submitted. Thanks!

**Comment by Evelyn-001** [comment]
@gcampbell-msft, the customer has been submitting a PR to try to fix this issue, could you please help check it? Thanks in advance.

**Comment by hippo91** [comment]
@gcampbell-msft AFAIK it is now possible to have test delimiter. Should this issue be closed?

**Comment by gcampbell-msft** [comment]
@hippo91 Yes, this is a good callout, thank you! 

Closing.
