### ISSUE TITLE
Windows - build tool doesn't see system path

### ISSUE THREAD

**Issue by Nicklesworth** [microsoft/vscode-cmake-tools#3159]
Setup: Win11 + VSCode + CMakeTools + Ninja + MSys

I have a fairly simple CMakeLists.txt file that has a post-build custom command as follows:
`
add_custom_command(TARGET application.elf
POST_BUILD
COMMAND ${CMAKE_OBJCOPY} -O ihex application.elf ${RELEASE_DIR}/application.hex
COMMAND bash ${CMAKE_SOURCE_DIR}/scripts/make_release_files.sh
)
`

I'm on a Windows system, so bash is provided by MSys, whose bin directory I have properly setup in environment variables.

When I build within VSCode (F7), my application links, the first subcommand executes, but the second subcommand fails with the following error: `[build] 'bash' is not recognized as an internal or external command`

However, if I head to the VSCode Terminal, or Windows command line, and run `cmake --build build`, the post-build subcommand runs just fine.

Up until last week, this was all working just fine. But recently the problematic behavior started and I cannot trace it to a direct event.

It's as if Ninja, running as a result of the CMake build tools, don't see/respect the system path.

**Comment by benmcmorran** [comment]
What version of the extension are you using? We fixed an issue with MinGW paths in 1.14.31 that was released on Tuesday.

**Comment by Nicklesworth** [comment]
This issue appears fixed by v1.14.31. Thank You!
