### ISSUE TITLE
CI tests do not respect the CMake version from the env matrix

### ISSUE THREAD

**Issue by vector-of-bool** [microsoft/vscode-cmake-tools#316]
This means we run the same build four times.

**Comment by KoeMai** [comment]
No I did not check it. At the moment I do not see any tests which use cmake. Is this right?
I would finish the refactoring of the tests (#323) and then I like to add some test like configure and build to the extension_tests. After this works with one cmake version, it is useful to get the different versions running.

**Comment by vector-of-bool** [comment]
We have a few tests that already do run the configure/build process (even if poorly).

**Comment by vector-of-bool** [comment]
Moving this to the backlog as supporting multiple cmake version in the tests isn't a very high priority ATM
