### ISSUE TITLE
The logic of the feature —— "select CMakeLists.txt"

### ISSUE THREAD

**Issue by SAquarius** [microsoft/vscode-cmake-tools#3170]
### Brief Issue Summary

CMake extension has a program logic that confuses me. When I open a folder that contains a project folder organized by CMake and many other folders, I don't want to use the CMake extension to initialize or process the directory. I just want to browse or modify other files. However, the CMake extension always automatically pops up a prompt window to select the CMakeLists.txt file. As shown in the following figure:
![GLHCVWSZFOWN270GDTBBG$X](https://github.com/microsoft/vscode-cmake-tools/assets/51738302/d39c6b72-df33-4632-aef1-6870a22fa3c2)
As shown in the above figure: I opened the "code" folder, which contains multiple subfolders. The CMake directory is a project I created to learn CMake syntax, and there are also several other independent folders included. However, as I was browsing and editing Python files, the CMake plugin popped up a prompt window, which obviously does not conform to the user's logical use.

**Comment by gcampbell-msft** [comment]
@SAquarius Thanks for the issue!

Please enable the `cmake.ignoreCMakeListsMissing` setting, at the user level, and this should fix your issue!

We will also take an action to update the docs to document this setting.
