### ISSUE TITLE
`Bad CMake Executable` when opening 2 CMake projects

### ISSUE THREAD

**Issue by juan-lunarg** [microsoft/vscode-cmake-tools#3174]
### Brief Issue Summary

I'm currently getting this CMake error `Bad CMake executable: "". Check to make sure it is installed or the value of the "cmake.cmakePath" setting contains the correct path`

I'm able to reproduce this issue very reliably.

Open up 2 separate projects with vscode that use CMake and the error appears on the 2nd instance.

```
# psuedo instructions
cd cmake_project_1
code .  # Leave this vscode instance running

cd ../

cd cmake_project_2
code . # This vscode instance will have the aforementioned error message
```

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.78.2",
  "cmtVersion": "1.14.31",
  "configurations": [
    {
      "folder": "/home/juan/projects/profiles",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Additional Information

![image](https://github.com/microsoft/vscode-cmake-tools/assets/114601453/e5c0a488-9428-493b-97f9-63b770939165)

In this example I have 2 instances of vscode up.

As you can see I get the `Bad Executable` error message.

I can also trigger this error message via commands like `CMake: Log Diagnostics` reliably when I have 2 instances of vscode up.

Aside from having 2 instances of vscode open I never receive this error message.

**Comment by gcampbell-msft** [comment]
@juan-lunarg Do you still notice this issue? I wasn't able to reproduce, though I did notice that possibly your `cmake.cmakePath` setting had gotten corrupted? When I press the gear icon for the CMake path setting and click `Reset Setting` it gets reset to "cmake" rather than an empty string. 

Please let me know if this issue is still present, thanks!

**Comment by juan-lunarg** [comment]
I can no longer reproduce this issue. Feel free to close the issue since I can't give a repro anymore.

**Comment by gcampbell-msft** [comment]
@juan-lunarg Great! I'm glad that the issue has been resolved for you. Closing this issue.
