### ISSUE TITLE
Add language selection support to Quick Start.

### ISSUE THREAD

**Issue by REDl3east** [microsoft/vscode-cmake-tools#3182]
### Brief Issue Summary

I love using this tool for C++ and I always use the Quick Start command to quickly create a new project. I also enjoy writing programs in C, which becomes a problem with the Quick Start command. Whenever I start a new C project I will run the Quick Start as normal and then go in and change the filenames to .c files and update the files to represent the C language, e.q. use printf instead of cout. I would love for there to be an option to select either C or C++ language, similarly as selecting Executable or Library.

**Comment by benmcmorran** [comment]
Thanks for the feedback! I'm marking this as a feature request and will take a look at the PR you've opened.

**Comment by benmcmorran** [comment]
Shipped in 1.15.31.
