### ISSUE TITLE
CMake Tools ignores environment variables in an inherited configurate preset when it is in an included CMakePreset file

### ISSUE THREAD

**Issue by brycehutchings** [microsoft/vscode-cmake-tools#3185]
Type: <b>Bug</b>

If I have a configurationPreset inherit from another configurationPreset defined in another file which is "included", then this extension will not set the environment correctly when invoking CMake. If I move the inherited configurationPreset into CMakePresets.json so that everything is in one file then it works correctly.

Note this problem would not exist if this extension instead invoked CMake using --preset rather than trying to replicate its behavior. It would be preferable to leverage CMake's preset support directly instead of trying to mimic it.

Minimal repo: Create the following three files in a folder and open this folder in VSCode with the CMake Tools extension enabled. Try to configure the "Test" preset and see that it fails because the MY_TEST_ENV_VAR environment variable is not set.

CMakePreset.json:
```
{
  "version": 4,
  "include": [
    "CMakePresets-Base.json"
  ],
  "configurePresets": [
    {
      "name": "Test",
      "inherits": ["Test-base"],
      "cacheVariables": {
        "CMAKE_BUILD_TYPE": "Debug"
      }
    }
  ]
}
```

CMakePresets-Base.json:
```
{
  "configurePresets": [
    {
      "name": "Test-base",
      "hidden": true,
      "environment": {
        "MY_TEST_ENV_VAR": "Hello World!"
      }
    }
  ]
}
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.25)
project(EnvVarTestProject)

# Should show "Hello World!"
if (NOT DEFINED ENV{MY_TEST_ENV_VAR})
    message(FATAL_ERROR "MY_TEST_ENV_VAR is not defined!")
else()
    message(STATUS "MY_TEST_ENV_VAR is defined: $ENV{MY_TEST_ENV_VAR}")
endif()
```

Extension version: 1.14.31
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.80GB (31.23GB free)|
|Process Argv|. --crash-reporter-id 35565c2c-7c25-4087-b760-217e4df20021|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
pythongtdpath:30739704

```

</details>

**Comment by benmcmorran** [comment]
Hi @brycehutchings, I've started investigating this issue, but I'm having trouble reproducing it. Given the files you provided, both command line CMake and CMake Tools complain about the lack of a version number in the `CMakePresets-Base.json` file.

Command line:

```powershell
C:\dev\issue-3185> cmake --list-presets
CMake Error: Could not read presets from C:/dev/demos/issue-3185: No "version" field
```

CMake Tools log:

```
[presetController] Successfully validated presets in C:\dev\issue-3185\CMakePresets.json
[presetController] Unsupported presets detected in C:\dev\issue-3185\CMakePresets-Base.json. Support is limited to features defined by version 4.
[presetController]  >> : should have required property 'version'
[presetController] Unknown properties and macros can be ignored by using the 'cmake.allowUnsupportedPresetsVersions' setting.
[preset] Could not find configure preset with name Test-base
```

If I add `"cmake.allowUnsupportedPresetsVersions": true` to settings.json, then it appears that the configure preset is partially used, but the entire `Test-base` preset is still dropped, and the configure step fails with the error you described.

CMake Tools log:

```
[presetController] Successfully validated presets in C:\dev\demos\issue-3185\CMakePresets.json
[presetController] Unsupported presets detected in C:\dev\demos\issue-3185\CMakePresets-Base.json. Support is limited to features defined by version 4.
[presetController]  >> : should have required property 'version'
[presetController] Unknown properties and macros can be ignored by using the 'cmake.allowUnsupportedPresetsVersions' setting.
[preset] Could not find configure preset with name Test-base
[driver] Switching to configure preset: Test
[driver] Switching to build preset: __defaultBuildPreset__
[driver] Unsetting test preset
```

However, if I instead add `"version": 4` to `CMakePresets-Base.json`, then everything appears to work correctly. Does this match the behavior you are seeing?
