### ISSUE TITLE
CMake extension buttons gone with 1.14.32

### ISSUE THREAD

**Issue by TaeZStkyoht** [microsoft/vscode-cmake-tools#3198]
### Brief Issue Summary

CMake buttons are now gone in version 1.14.32 on Ubuntu. If I downgrade to 1.14.31, everything works fine.

**Comment by AntonSamojlow** [comment]
Same for me, both Windows and Ubuntu:
The extension is no longer shown in the **status bar**.
(Commands and side bar options still work)

**Comment by knehez** [comment]
same for me

**Comment by joe-lindlbauer** [comment]
The project status was disabled 1.14.32 for whatever reason... It can be enabled by going to Settings->Cmake: Use Project Status View and uncheck the box.

**Comment by snehara99** [comment]
Yes, as @joe-lindlbauer has found, you can opt-out of using the Project Status View by unchecking `Cmake: Use Project Status View`.

**Comment by itodirel** [comment]
Hey folks, @TaeZStkyoht, @AntonSamojlow, @knehez, @joe-lindlbauer, sorry about that. This is a feature slated for the upcoming 1.15 release, and we accidentally activated it in 1.14.32, we will fix this in a 1.14 release very shortly. Thank you for the report. 

We are planning A/B experimentation on this feature, so if you see this again, just use the setting mentioned by @snehara99, to stop using the Sidebar.

**Comment by snehara99** [comment]
In 1.14.33 (now released), the buttons in the status bar are back by default. Sorry for the confusion!

**Comment by TaeZStkyoht** [comment]
> Hi @TaeZStkyoht, @knehez, @AntonSamojlow, and @joe-lindlbauer, the buttons in the status bar are back by default in 1.14.33 (now released). Sorry for the confusion!

Thanks, 1.14.33 solved the problem.
