### ISSUE TITLE
Bug related to the inability to select the compiler (xx.cmake) correctly

### ISSUE THREAD

**Issue by xiaoapeng** [microsoft/vscode-cmake-tools#3201]
### Strange commands observed after clicking "build":
![image](https://github.com/microsoft/vscode-cmake-tools/assets/40020246/4bfe09ea-4bb8-458f-9b55-d99df7a04fce)
### The error command is as follows:
[proc] Executing command: /usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_toolchainFile_COMPILER:FILEPATH=/xxxxx.cmake /xxxxx/src -G Ninja
### On the other machine (SSH), the correct command looks like this:
[proc] Executing command: /usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/xxxxx.cmake -S/xxxxx/src -B/xxxxx/build -G Ninja

So I believe that CMAKE_toolchainFile_COMPILER should be incorrect.

### Environment causing the bug：
Local environment：  Windows 10  19044.2965  Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz   3.41 GHz
Remote environment：Linux ubuntu 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Plugin version ： v1.14.33
vs code version:   v1.78.2
cmake version :    v3.5.1

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.78.2",
  "cmtVersion": "1.14.33",
  "configurations": [
    {
      "folder": "/xxxx/xxx",
      "cmakeVersion": "3.5.1",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/cc",
        "CXX": "/usr/local/bin/c++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

**Comment by benmcmorran** [comment]
Thanks for the report! We'll try to reproduce this issue and let you know if we have any additional questions.

**Comment by snehara99** [comment]
Hi @xiaoapeng, in the `.vscode/settings.json` file can you see how `cmake.configureArgs` is set? You can also find it at `Settings -> CMake Tools configuration`

**Comment by xiaoapeng** [comment]
> Hi @xiaoapeng, in the `.vscode/settings.json` file can you see how `cmake.configureArgs` is set? You can also find it at `Settings -> CMake Tools configuration`. If there is nothing there, can you show me where you set the toolchain file please?

Thank you for your response. I haven't configured this setting in both my local workspace and remote workspace, as well as in my user environment.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/40020246/50a3e6f1-2ba5-4aa7-8924-5657200de6b2)

I have checked my JSON configuration, and this configuration is not set.

I'm not very good at English, please forgive me.   ^_^

**Comment by snehara99** [comment]
Hi @xiaoapeng, I don't believe the toolchain file should be set under compilers. Can you try to set it like in this [example](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md#specify-a-toolchain)

**Comment by snehara99** [comment]
As an update, I tried setting up `cmake-tools-kits.json` how you had it with the `"toolchainFile"` being under `"compilers"` and I ran into the same issue. The issue was resolved when I moved the `"toolchainFile"` out of `"compilers"`. Please let me know if this change works for you!

(for clarity)
instead of this:
`[ {"name": "some name", "compilers": {"toolchainFile": "path-to-file"} ]`
try this:
`[ {"name": "some name", "toolchainFile": "path-to-file"} ]`

**Comment by xiaoapeng** [comment]
> As an update, I tried setting up `cmake-tools-kits.json` how you had it with the `"toolchainFile"` being under `"compilers"` and I ran into the same issue. The issue was resolved when I moved the `"toolchainFile"` out of `"compilers"`. Please let me know if this change works for you!
> 
> (for clarity) instead of this: `[ {"name": "some name", "compilers": {"toolchainFile": "path-to-file"} ]` try this: `[ {"name": "some name", "toolchainFile": "path-to-file"} ]`

Thank you for your reply, the method is indeed effective, and my problem has been resolved.

**Comment by snehara99** [comment]
Great! I'm going to close this issue now, but feel free to open more issues in the future if you're facing problems. Thanks!
