### ISSUE TITLE
Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable

### ISSUE THREAD

**Issue by Bodden007** [microsoft/vscode-cmake-tools#3205]
### Brief Issue Summary

Hello. I'm new to programming, the first time I installed VS Code, a Microsoft C++ plugin and CMake Tools. Unfortunately I can't use it properly. Help please. Perhaps there is a more subtle instruction on how to configure it?

### Debug Log

```shell
[variant] Loaded new set of variants
[kit] Successfully loaded 5 kits from C:\Users\h253747\AppData\Local\CMakeTools\cmake-tools-kits.json
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --version
[proc] Executing command: C:\msys64\ucrt64\bin\gcc.exe -v
[proc] The command: ninja --version failed with error: Error: spawn ninja ENOENT
[proc] The command: ninja-build --version failed with error: Error: spawn ninja-build ENOENT
[proc] The command: make --version failed with error: Error: spawn make ENOENT
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[main] Configuring project: cmFuk
```

**Comment by Bodden007** [comment]
Changing the compiler to Visual Studio Community 2022 Release - amd64 17.6.2 solved the problem.

**Comment by benmcmorran** [comment]
Glad you got it working. It's important to note that the CMake Tools extension does not come with CMake itself, and the C++ extension does not come with a compiler. If you're just getting started, installing Visual Studio is an easy way to get both, and the CMake Tools extension should automatically find them as you discovered.
