### ISSUE TITLE
how to select libc++ when scan kits?

### ISSUE THREAD

**Issue by walkthetalk** [microsoft/vscode-cmake-tools#3208]
### Brief Issue Summary

scan kits can find clang/lld, but can't select libstdc++ or libc++

**Comment by benmcmorran** [comment]
Please add more detailed repro steps. What system are you running on, how did you install your kits, what actions are you taking in the extension, what output are you seeing, and what did you expect to see?

**Comment by bobbrow** [comment]
Selecting libc++ vs. libstdc++ is something you would configure in your CMakeLists.txt or a Toolchain file.  It's controlled with a linker flag.  Something like one of these:

`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lc++")`
or
`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++")`
or
`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libstdc++")`

The purpose of Kits is to select a compiler and it doesn't do any configuration beyond that.

**Comment by walkthetalk** [comment]
Oh, thanks!

Does cmake will check stdlib settings in exe_linker_flags and drop default one?
or how is the default setting work? and how the cmake_exe_linker_flags work against default setting?

> Selecting libc++ vs. libstdc++ is something you would configure in your CMakeLists.txt or a Toolchain file. It's controlled with a linker flag. Something like one of these:
> 
> `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lc++")` or `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++")` or `set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libstdc++")`
> 
> The purpose of Kits is to select a compiler and it doesn't do any configuration beyond that.

**Comment by walkthetalk** [comment]
the default means which lib is linked without custom 'CMAKE_EXE_LINKER_FLAGS'.

**Comment by gcampbell-msft** [comment]
I believe that by default CMake invokes the linker through the compiler exe. Either way, I believe that when you set CMAKE_EXE_LINKER_FLAGS, it will override the default. 

Thanks! Closing this issue since it seems that Bob's suggestion fixed your issue.
