### ISSUE TITLE
copyCompileCommands to the original path makes the file empty

### ISSUE THREAD

**Issue by tocic** [microsoft/vscode-cmake-tools#3214]
### Brief Issue Summary

I'm using `cmake.copyCompileCommands` as a workaround to support _clangd_ (see https://github.com/microsoft/vscode-cmake-tools/issues/654):

```json
"cmake.copyCompileCommands": "${workspaceFolder}/build/compile_commands.json"
```

But if the `${workspaceFolder}/build` directory is the original `compile_commands.json`'s directory then the extension makes the file empty. I expect it to either not copy the file or overwrite the file with its original contents.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.79.2",
  "cmtVersion": "1.14.33",
  "configurations": [
    {
      "folder": "/home/tocic/test",
      "cmakeVersion": "3.26.4",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/gcc",
        "CXX": "/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Debug Log

```shell
[main] Copying compile_commands.json from /home/tocic/test/build/compile_commands.json to /home/tocic/test/build/compile_commands.json
[compdb] Error parsing compilation database "/home/tocic/test/build/compile_commands.json": 
	SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at CompilationDatabase.fromFilePaths (/home/tocic/.vscode-oss/extensions/ms-vscode.cmake-tools-1.14.33-universal/dist/main.js:37178:38)
	at async CMakeProject.refreshCompileDatabase (/home/tocic/.vscode-oss/extensions/ms-vscode.cmake-tools-1.14.33-universal/dist/main.js:34944:27)
	at async /home/tocic/.vscode-oss/extensions/ms-vscode.cmake-tools-1.14.33-universal/dist/main.js:35056:33
	at async CMakeProject.doConfigure (/home/tocic/.vscode-oss/extensions/ms-vscode.cmake-tools-1.14.33-universal/dist/main.js:35145:24)
```

**Comment by gcampbell-msft** [comment]
@tocic Thanks for the bug report! We will put this on the backlog and assess when we can get to it. In the meantime, we are happy to take open source contributions!

**Comment by parniere** [comment]
Hi, I just hit the same bug, I think the pull request just posted above fix it

**Comment by recursivenomad** [comment]
I'd like to re-open this issue, as the current solution does not account for differences in path separators on Windows.  Example:

```json
"cmake.buildDirectory": "${workspaceFolder}/firmware/build"
```

on Windows gets sanitized to `your/path/to/firmware/build/compile_commands.json`.  But:

```json
"cmake.copyCompileCommands": "${workspaceFolder}/firmware/build/compile_commands.json"
```

does not get sanitized on Windows, and results in `your\path\to/firmware/build/compile_commands.json`.  I can confirm this is the problem by manually entering the absolute path with identical path separators as the sanitized input, and the feature will work as intended.  The result is there is still CDB corruption on Windows when using `${workspaceFolder}`.
