### ISSUE TITLE
No CMake in Status bar

### ISSUE THREAD

**Issue by rokostrup** [microsoft/vscode-cmake-tools#3229]
### Brief Issue Summary

When updating to v1.14.34 the CMake Tools Extension disappear from the status bar.

Rolling back to 1.14.33 it reappears.

I'm running inside a dev container.

It looks like it quickly appears when I do a "Reload Window" (I can see the presets in the status bar), but they disappear immediately.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.79.2",
  "cmtVersion": "1.14.34",
  "configurations": [
    {
      "folder": "/workspaces/myprj",
      "cmakeVersion": "3.22.1",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "/usr/bin/cc",
        "CXX": "/usr/bin/c++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

**Comment by Sknp1006** [comment]
my vscode version:1.79.2
my cmake tools version:1.14.33

disable this setting may help you.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/41496773/5c344dbd-a795-405a-85af-9ad01277f414)

**Comment by Sknp1006** [comment]
I think that this is caused by CMake Tools updating to a newer version and having this setting enabled by default. I just encountered the same problem too and I found this issue. Have a nice day :-)
