### ISSUE TITLE
All the cmake icons in the bottom status bar have disappeared

### ISSUE THREAD

**Issue by lichjian** [microsoft/vscode-cmake-tools#3231]
### Brief Issue Summary

During my use, I suddenly realized that the cmake extension was no longer displayed in the status bar at the bottom of vscode

### Additional Information

![微信截图_20230704205555](https://github.com/microsoft/vscode-cmake-tools/assets/37821198/48810a88-f9d6-4ad2-a096-b19d84d6d601)

**Comment by snehara99** [comment]
Hi @lichjian, we are currently running an A/B experiment where we are migrating some users' options that were previously located in the status bar to the side panel. As @pJunger pointed out, the details and opt-out instructions are in #3202. Please feel free to leave feedback as well, thanks!

**Comment by snehara99** [comment]
I'm going to go ahead and close this issue, but if you have any other issues, feel free to create a new one.
