### ISSUE TITLE
Make the CMake Debugger work in script mode and without access to output

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vscode-cmake-tools#3248]
### Brief Issue Summary

Currently the CMake debugger requires a CMake project to run the debugger but I would also like to debug cmake scripts run with the `-P` option. My use case is actually to debug vcpkg portfiles. (There is a hacky way to currently achieve that but I would rather have it correctly supported)

Furthermore I would like to attach the debugger to cmake projects which don't directly write to stdout. Currently the debugger is waiting for `Waiting for debugger client to connect...` in the console output to trigger the state change in the debugger however I have a use case where the output is already redirected to a file and I cannot redirect the output to stdout. Wouldn't it be better to test if the named pipe is available and then start the debugger? Use case here is to debug CMake projects currently being configured inside vcpkg.

**Comment by benmcmorran** [comment]
Thanks for the suggestion! We're planning to add the ability to debug in script mode in our `1.16` release.

**Comment by Neumann-A** [comment]
> We're planning to add the ability to debug in script mode in our 1.16 release.

After thinking about it there should be three modes:

a) normal configure (already implemented)
b) script mode
c) attach mode (basically attach the debugger to the given pipe/socket without starting cmake yourself.)

**Comment by gcampbell-msft** [comment]
@Neumann-A Thanks for your suggestions and thoughts! 

One quick question regarding this comment:

>  "Furthermore I would like to attach the debugger to cmake projects which don't directly write to stdout. Currently the debugger is waiting for Waiting for debugger client to connect... in the console output to trigger the state change in the debugger however I have a use case where the output is already redirected to a file and I cannot redirect the output to stdout. Wouldn't it be better to test if the named pipe is available and then start the debugger? Use case here is to debug CMake projects currently being configured inside vcpkg."

Have you hit this error where we can't connect to the configure process? Our implementation should be parsing the output of cmake before it actually gets sent to the output (which you have redirected to a file), so this should still be supported. If you have a case where it's not, I'd love to hear about it and get reproduction steps, because this would be a bug. Thanks!

**Comment by Neumann-A** [comment]
> Have you hit this error where we can't connect to the configure process? 

Yes. It also stalls the debugger completely if it cannot connect. No way to stop it if that happens (which is actually a bug in my eyes since you should be able to press stop and force a reset of the debugger instance). You probably assume you have actual control over the cmake run but I put a batch script between VS Code and CMake via `"cmake.cmakePath": "${workspaceFolder}/vcpkg-debug.bat"` to achieve the thing shown off in https://github.com/microsoft/vcpkg/discussions/32643 . 

> cmake before it actually gets sent to the output (which you have redirected to a file), so this should still be supported.

The redirection is outside VS Code so I doubt you can listen in / support that currently. VS Code -> Runs Batch script -> Runs vcpkg -> Runs CMake script mode -> Runs CMake configure mode via `execute_process` from inside CMake script mode (`execute_process` doesn't print to stdout).

**Comment by gcampbell-msft** [comment]
@Neumann-A Thanks for all of your information. We are working on this and will be enabling script mode support as well as connecting the debugger to an externally launched cmake process in the 1.16 release. 

Thank you!

**Comment by gcampbell-msft** [comment]
@Neumann-A I have a PR up right now: #3277 that enables debugging with script mode using a launch.json!

It'd be great if you could take a quick look and see if the launch.json schema and overall PR implementation seems like it meets your needs!

**Comment by Neumann-A** [comment]
@gcampbell-msft Is there a quick and simple way to make VS Code use that PR? (Like e.g. copying some files to somewhere)

**Comment by benmcmorran** [comment]
I just kicked off a [VSIX build](https://github.com/microsoft/vscode-cmake-tools/actions/runs/5758878124) which you should be able to [download here](https://github.com/microsoft/vscode-cmake-tools/suites/14814614658/artifacts/843293863).
