### ISSUE TITLE
CMake Tools does not recognize "packagePresets" or "workflowPresets" from CMakePresets.json

### ISSUE THREAD

**Issue by chockey** [microsoft/vscode-cmake-tools#3262]
### Brief Issue Summary

Hello,

CMake tools does not recognize CMakePresets.json version 6 entries for "packagePresets" and "workflowPresets", giving a JSON validation error. This also seems to prevent me from selecting a configure preset at all, I'm simply presented with the option to create a new preset.

If I remove the "packagePresets" and "workflowPresets" entries from CMakePresets.json, I'm able to select one of my presets as expected.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.80.1",
  "cmtVersion": "1.14.34",
  "configurations": [
    {
      "folder": "/workspaces/XXX",
      "cmakeVersion": "3.27.0",
      "configured": false,
      "generator": "",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Additional Information

![image](https://github.com/microsoft/vscode-cmake-tools/assets/442120/f69d3c9f-76b8-4da3-b45e-2e99067884f2)

**Comment by bobbrow** [comment]
I'm not sure when presets v6 support will be implemented, but you should be able to use the `cmake.allowUnsupportedPresetsVersions` setting to get past this validation error and use your configurePresets.

**Comment by chockey** [comment]
Thank you, @bobbrow - that solution works perfectly, as long as I can still build and run while those are there, I'm happy :)

**Comment by benmcmorran** [comment]
Glad it's working for you now! I'm closing this issue, but you can track the progress of CMakePresets v6 support at #2871.
