### ISSUE TITLE
Cmake tools test task with multiple jobs?

### ISSUE THREAD

**Issue by trondhe** [microsoft/vscode-cmake-tools#3289]
### Brief Issue Summary

Isnt it possible for a task with properties
``` json
"type": "cmake",
"command": "test",
```
to be run with multiple jobs?
At least I can't find any documentation on it.

**Comment by trondhe** [comment]
It was less apparent on what I ment when I re-read my own post, sorry.

I literally just want the cmake executable to run ctest with `ctest --paralell <jobcount>`. Right now it seems to only run a single job, and I cannot figure out any way to change that into paralell.

**Comment by gcampbell-msft** [comment]
@trondhe Thanks for the clarification! 

This was previously unavailable after adding our Text Explorer. However, @snehara99 recently merged changes that allowed users to override this setting. If you navigate to VSCode settings and set `cmake.ctest.allowParallelJobs` to true, this should be enabled. 

Please let us know if this fixes your issue by commenting if it doesn't work, or if it does, feel free to close this issue. Thanks!

**Comment by trondhe** [comment]
Ah right. That should be sufficient I think.
