### ISSUE TITLE
No prompt pop up when adding the same key and value fail

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-cmake-tools#3302]
### Brief Issue Summary

**Repro steps:**
1. Launch VScode and open "Preferences: Open Settings(UI)"
2. Navigate to "CMake: Build Environment"
3. Click "Add item", input "Key" with "CMakeTest" and "Value" with "1"
4. Repeat step3

**Expected:**
Prompt pop up when adding the same key and value

**Actual:**
Adding the same key and value actually fails, while without any prompt pop up
![CMakeTools_AddSameItem](https://github.com/microsoft/vscode-cmake-tools/assets/37648162/219c3a7d-041d-41a4-8e40-4645421da05f)

Environment:
VS2022+ VSCode 1.80.2 + C/C++ Extension Pack 1.3.0+CMake 0.0.17+CMake tools 1.16.1

**Comment by bobbrow** [comment]
I believe this is by design but the VS Code team owns this UI, not the extension.
