### ISSUE TITLE
NDEBUG Definition always enabled using Ninja Multi-Config

### ISSUE THREAD

**Issue by AlessandroScrem** [microsoft/vscode-cmake-tools#3305]
### Brief Issue Summary

Bug NDEBUG Definition is not grayed in release mode

- step to reproduce:
set  cmake generator = Ninja Multi-Config

```
#ifndef NDEBUG
#define PRINTHELLO() std::cout << "Hello, debug!\n";
#else
#define PRINTHELLO() std::cout << "Hello, release!\n";
#endif

man() {
PRINTHELLO();
}

```

- expected : 
- following line grayed in  release mode

#define PRINTHELLO() std::cout << "Hello, debug!\n"; 

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.81.1",
  "cmtVersion": "1.15.31",
  "configurations": [
    {
      "folder": "c:\\Users\\ascre_p1ijxgd\\test\\prova",
      "cmakeVersion": "3.27.1",
      "configured": true,
      "generator": "Ninja Multi-Config",
      "usesPresets": false,
      "compilers": {
        "C": "C:/msys64/clang64/bin/clang.exe",
        "CXX": "C:/msys64/clang64/bin/clang++.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Additional Information

- Configuration is Release

![image](https://github.com/microsoft/vscode-cmake-tools/assets/48774358/cceed407-d723-48f5-b583-7b766ea14d17)

![image](https://github.com/microsoft/vscode-cmake-tools/assets/48774358/fe4dc74c-76c3-4e50-acea-170dad393c96)

![image](https://github.com/microsoft/vscode-cmake-tools/assets/48774358/a5f85ef0-16af-4e93-8ede-86f47365a870)

**Comment by gcampbell-msft** [comment]
@AlessandroScrem Thanks for posting the issue! Is there any way that you could provide a repro project for us to reproduce this issue and investigate? 

Is this using kits?

**Comment by AlessandroScrem** [comment]
This is the repo I used to reproduce the issue:
It's very basic file.
https://github.com/AlessandroScrem/prova

I using following kit:
CMAKE_C_COMPILER:FILEPATH=C:\msys64\clang64\bin\clang.exe -CMAKE_CXX_COMPILER:FILEPATH=C:\msys64\clang64\bin\clang++.exe 
Cmake Generator =  "Ninja Multi-Config"

Im also using clangd extension:
https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd

I hope this info could be userful.

Thank so much.
Alessandro

**Comment by deribaucourt** [comment]
> It's possible that #3363 fixes this issue. Once merged, could you please confirm? We also will try to check if this is fixed. Thanks.

Yup, this issue could be related since the CMakeLists.txt does not provide a CMAKE_BUILD_TYPE.
