### ISSUE TITLE
Is there a way to override/remove the arguments passed to CTest?

### ISSUE THREAD

**Issue by lucas-yotsui** [microsoft/vscode-cmake-tools#3307]
### Brief Issue Summary

I'm starting to use CTest in my projects just now, so I don't have much experience in it and therefore could be making something wrong in my scripts or whatever.

My issue is this: whenever I run my tests via terminal with ___cd build && ctest___ it works just fine, but when I try to use the extension's button on the status bar it doesn't and outputs the following:
```
^google_test_first_attempt_test_NOT_BUILT$
[ctest] Cannot find file: /home/lucas-yotsui/iase/g_test_first_attempt/build/DartConfiguration.tcl
[ctest]    Site: 
[ctest]    Build name: (empty)
[ctest] Test project /home/lucas-yotsui/iase/g_test_first_attempt/build
[ctest] Cannot find file: /home/lucas-yotsui/iase/g_test_first_attempt/build/DartConfiguration.tcl
[ctest] No tests were found!!!
[ctest] CTest finished with return code 0
[ctest] [object Object]
```

By inspecting the output I've noticed that the extension is passing some arguments that I'm not:
```
/snap/bin/ctest -j18 -C Debug -T test --output-on-failure "-T " -R
```

After trying different combinations of those arguments I've found that the one that causes this error is ___-T test___.

I created a .vscode folder with a settings.json to try and customize this behavior but I couldn't find any configuration that allowed me to remove these arguments, the closest I've got was this option:
```json
"cmake.ctestArgs": []
```
But it only appends more arguments to the ctest call.

Is there any way to remove these arguments altogether?

**Comment by gcampbell-msft** [comment]
@lucas-yotsui Could you test the most recent version of the pre-release channel? I believe there is a chance this has been either modified or fixed.
