### ISSUE TITLE
Support for $penv{} in include in CMake(User)Presets.json

### ISSUE THREAD

**Issue by jogerh** [microsoft/vscode-cmake-tools#3310]
### Brief Issue Summary

https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#includes describes that $penv{} can be used in include statements. This can be quite useful, particularly for centralizing user settings. One useful way of using this can be:

`{
  "version": 7,
  "include": [
    "$penv{USERPROFILE}\MyPresets.json",
  ]
}
`

This works with CMake, but it seems like it does not play well when configuring from VSCode with CMake Tools.

**Comment by gcampbell-msft** [comment]
@jogerh Could you provide some information about how it doesn't seem to play well? 

A couple of things that could be helpful for us to have are the following:
1) CMake Tools Diagnostics
2) Repro project that shows the issue. Detail what you are expecting versus what happens. 

Thanks!

**Comment by benmcmorran** [comment]
Relabeling as an enhancement because this is asking for a part of CMakePresets v7 support, which we don't yet formally support.
