### ISSUE TITLE
Presets not found after generating CMakeUserPresets.json

### ISSUE THREAD

**Issue by tim-hilt** [microsoft/vscode-cmake-tools#3313]
### Brief Issue Summary

When I open a project right after cloning, the `CMakeUserPresets.json` is not generated yet. After generating, I need to run `Developer: Reload Window` in order for the cmake-tools extension to suggest the presets.

### CMake Tools Diagnostics

``` json
{
  "os": "win32",
  "vscodeVersion": "1.81.1",
  "cmtVersion": "1.15.31",
  "configurations": [
    {
      "folder": "confidential",
      "cmakeVersion": "3.25.2",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Additional Information

We're using the conan package-manager to generate the CMake-Cache and CMakeUserPresets.json

**Comment by gcampbell-msft** [comment]
@tim-hilt What are you expecting the behavior to be? 

Could you try to delete cache and regenerate after the CMakeUserPresets is generated? Or even just resetting the CMake extension with the "Reset CMake Tools Extension State" command?
