### ISSUE TITLE
project quick luanch failed

### ISSUE THREAD

**Issue by jiuxiaxixi** [microsoft/vscode-cmake-tools#3316]
### Brief Issue Summary

lanuch.json  

debug is ok  ,means env isok . but quick launch is failed, Nothing happend.

my project is QT6 qml demo project. I can open it by clicked the exe file. I got the qt env set.

![image](https://github.com/microsoft/vscode-cmake-tools/assets/13214300/50470d89-5013-493b-afbf-c66bcc7d9eef)

```bash
PS D:\qtprojects\external_monitor\build> ."D:/qtprojects/external_monitor/build/appexternal_monitor.exe"
````
`.\appexternal_monitor.exe` also nothing happend. Maybe there is something wrong in the powsershell config  ?
 but running in powershell outside the vscode is ok, the program can launched.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            // Resolved by CMake Tools:
            "program": "${command:cmake.launchTargetPath}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [
                {
                    // add the directory where our target was built to the PATHs
                    // it gets resolved by CMake Tools:
                    "name": "PATH",
                    "value": "${env:PATH}:${command:cmake.getLaunchTargetDirectory}"
                }
            ],
            "externalConsole": true,
            "miDebuggerPath": "D:/Qt/Tools/mingw1120_64/bin/gdb.exe",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

![image](https://github.com/microsoft/vscode-cmake-tools/assets/13214300/8551cac6-e615-46ca-9588-5219b94706b9)

maybe that issue cause the problem?

### CMake Tools Diagnostics

```shell
l
```

**Comment by jiuxiaxixi** [comment]
![image](https://github.com/microsoft/vscode-cmake-tools/assets/13214300/275bcefc-99bf-4754-8986-1a373ee37d50)

I changed a computer, The same thing changed

**Comment by gcampbell-msft** [comment]
Could you provide us with a repro project so that we can best investigate this? 

A couple of additional questions, what is the program expected to do? It seems like it's getting invoked, just not outputting what you expected?

Thanks!
