### ISSUE TITLE
${buildType} doesnt work in launch.json

### ISSUE THREAD

**Issue by zbendefy** [microsoft/vscode-cmake-tools#334]
I'm trying to set up a launch.json in VSCode, where upon launching, the currently selected built type is selected. So if I set cmake to debug, the Build/Debug/MyApp will launch, but if I select release, then Build/Release/MyApp will launch.

I tried to accomplish this according to the documentation here (I'm not sure if I followed it correctly): https://vector-of-bool.github.io/docs/vscode-cmake-tools/configuring.html?highlight=

In my launch.json I have something like this:

> 
>       {
> 		"name": "MyApp",
> 		"type": "cppdbg",
> 		"request": "launch",
> 		"program": "${workspaceFolder}/../Build/${buildType}/MyApp",  // <----- Here is where I tried to select the buildtype
> 		"stopAtEntry": false,
> 		"cwd": "${workspaceFolder}/Binary",
> 		"externalConsole": true,
> 		"MIMode": "gdb",
> 		"setupCommands": [
> 				{
> 						"description": "Enable pretty-printing for gdb",
> 						"text": "-enable-pretty-printing",
> 						"ignoreFailures": true
> 				}
> 		] 
> 	}

### Platform and Versions

- **Operating System**: Linux Mint 18.3 64bit cinnamon
- **CMake Version**: 3.5.1
- **VSCode Version**: 1.20.1
- **CMake Tools Extension Version**: 0.10.4
- **Compiler/Toolchain**: GCC 6.3.0

**Comment by Randshot** [comment]
That's not how this works. The variable substitution, at least to my knowledge, only works in the settings.json and maybe in the variant and kit json files (I can't remember right now).

**Comment by vector-of-bool** [comment]
CMake Tools has no access to do those substitutions. You may want to look at `${command:cmake.launchTargetProgramPath}`, which will substitute the path to the selected launch target.

**Comment by zbendefy** [comment]
@vector-of-bool Thanks, I actually found that, however I still need the buildType, because there are some other folders I need to set as Link directories. Is there a way to get that with a ${command:cmake.<something>}?

**Comment by vector-of-bool** [comment]
Not at the moment, but it's a valid feature request. I'll log it

**Comment by vincent-breysse** [comment]
Is there any progress on this feature ? I actually have pretty close needs.
I'd like to write something like this in my settings.json :
```
{

"catch2TestExplorer.executables": [
        {
            "name": "${filename}",
            "description": "${relDirpath}/",
            "pattern": "bin/${buildKit}/${buildType}/*"
        }
    ]

}
```
Maybe any workaround to advice ?

**Comment by notskm** [comment]
I found myself wanting this feature, too, but in tasks.json.

A task to use [conan](https://conan.io/) to install dependencies might look like this:

```json
"tasks": [
  {
    "label": "conan install",
    "type": "shell",
    "options": {
      "cwd": "${command:cmake.buildDirectory}"
    },
    "command": "conan install ${workspaceRoot} -s build_type=${command:cmake.buildType}",
    "problemMatcher": []
  }
]
```

This would also make use of #564/#695

**Comment by xgdgsc** [comment]
Hoping `buildKit` would work in launch.json. Since this is maintained by microsoft now.

**Comment by bobbrow** [comment]
I forgot to close this issue since it was fixed in 1.2.2.  @xgdgsc the referenced Pull Request shows what needs to be done to add a new command.  If you want to follow that pattern to add support for `buildKit`, we would accept a PR.  I believe the data you are looking for is in `this.activeKit.name` (when `this.activeKit` is non-null).

**Comment by xgdgsc** [comment]
Great. I will send a PR in a month.

**Comment by mfdeveloper** [comment]
Hello @xgdgsc and @bobbrow !!

How can I get the current `buildKit.compiler` of `C` or `CXX` properties in `tasks.json` or `launch.json` ? 
Using `${command:cmake.buildKit}` I've got just the **name**, right ?

**Comment by bobbrow** [comment]
@mfdeveloper I'm going to move your request to a new issue. This issue should have been closed.  The solution for the original request is to use `${command:cmake.buildType}` instead of `${buildType}` in launch.json and tasks.json
