### ISSUE TITLE
i18n - French issue

### ISSUE THREAD

**Issue by jano42** [microsoft/vscode-cmake-tools#3341]
Hi

There is an issue in fr-18n on status bar button.

https://github.com/microsoft/vscode-cmake-tools/blob/addd2393ce3ccd95f29a13edecd132e2f4d0fe65/i18n/fra/src/status.i18n.json#L21

But should be

````json
     "build": "Générer",
````

**Comment by gcampbell-msft** [comment]
@jano42 Thanks for notifying us of this! We will work on getting a fix out for this, hopefully in our next release.

**Comment by gcampbell-msft** [comment]
2 options here: 
1. Create a loc bug
2. Just before release, update the string in place

**Comment by gcampbell-msft** [comment]
@jano42 I'm curious, before I move my investigation forward, why are you suggesting that Version should be translated to Générer? 

While this is naive, I tested in Google Translate and Générer translates to "Generate". English "Version" translates to "Version" in french on google translate. 

Thanks!

**Comment by bobbrow** [comment]
I agree with @jano42.  I have seen this come up before in French translations and the correct verb usually settles on Générer which means "to generate, build, or produce". And you usually don't want to pick a verb for "build" that has more of a construction context.  I don't think "Version" is the right choice.

**Comment by bobbrow** [comment]
You can also look at other translations done where more context is available and the translators pick Générer for "build"

"build.tooltip": "Générer la cible sélectionnée",

**Comment by jano42** [comment]
@gcampbell-msft : @bobbrow is right and provide a very good explanation . Then translation of "build" in French is "Générer" (in computer science), while the reverse is not completely true. "Générer" as more possible meanings, (sorry I'm French).

**Comment by gcampbell-msft** [comment]
@jano42 @bobbrow Ah, I misunderstood in my initial investigation. I'll make it a priority to submit a bug fix request to the loc team.
