### ISSUE TITLE
Please add a setting option to set runtime PATH variable

### ISSUE THREAD

**Issue by quanzhuo** [microsoft/vscode-cmake-tools#3346]
### Brief Issue Summary

I use vscode and this plugin on qt projects, everything works ok , except that I can not launch the built exeutable when click the Launch button in status bar. because the executable can not find qt library needed.

I have to set PATH variable manually in the failed termimal, and run again to launch the program.

```
$env:PATH="$env:PATH;C:\Qt\5.15.2\msvc2019_64\bin"
```
Is there a way/setting to set PATH environment when run the built executable ?

**Comment by gcampbell-msft** [comment]
@quanzhuo Could you provide some additional information about how you're trying to launch your executable? Are you defining a launch.json? If so, depending on your launch configuration type, there should be available fields to adjust the Path variable. 

Thanks.

**Comment by quanzhuo** [comment]
I run the executable by clicking the triangle in status bar, @gcampbell-msft 
![image](https://github.com/microsoft/vscode-cmake-tools/assets/8767119/e81920e3-0514-4343-aefe-5387536efab9)
