### ISSUE TITLE
IntelliSense configuration incorrect with default/empty CMAKE_BUILD_TYPE using CMakePresets

### ISSUE THREAD

**Issue by deribaucourt** [microsoft/vscode-cmake-tools#3355]
### Brief Issue Summary

Hello, 

I'm using the cmake-tools extension with a custom toolchain.cmake file. This file uses a cross-compilation toolchain making use of a target sysroot containing the headers that CMake compiles with. The build configuration correctly uses them. However, the "includePath" and "browse.path" properties of the cpptools extension is still using my host sysroot when using cmake-tools as configurationProvider. For instance, if I right-click on a `#include` statement then "Go to definition", I'm directed to the header in `/usr/include` instead of `<sysroot>/usr/include`.

I'm configuring the workspace using a CMakePresets.json with a CMakeCache.txt as attached. In my configuration, no `CMAKE_BUILD_TYPE` or `CMAKE_CONFIGURATION_TYPES` are defined. It is specified in the [CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html) that this is a valid (albeit not recommended) CMake configuration which should use the default toolchain's parameters. Indeed, I can successfully build the project through the extension. However, the intelliSense configuration is not passed to the cpptools extension, which produces an incorrect linting. See bellow screenshots.

[CMakeCache.txt](https://github.com/microsoft/vscode-cmake-tools/files/12792290/CMakeCache.txt)
`CMAKE_BUILD_TYPE:STRING=`

Problematic IntelliSense configuration:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/19970889/1f3a0c1e-afeb-4e7e-92cb-cafbd6aa9750)

### On fixing this

I tracked this behaviour down to the `src/cpptools.ts:updateConfigurationData(opts: CodeModelParams)` function. The test `config.name === opts.activeBuildTypeVariant` expands to `"" === null`. The first is defined through the target preset in the UI, the latter in `.src/cmakeProject.ts:currentBuildType()` which parses `CMakeCache.txt`. This resulted in no configuration being passed to IntelliSense at any point, resulting in the erroneous linting. I think it should be allowed to fallback to `""` when a `null` build type variant is specified to handle this case. I'm going to submit a PR with these modifications.

Fixed IntelliSense configuration:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/19970889/e90c2a9e-4b45-4036-8fab-8ea0654e690c)

**Comment by deribaucourt** [comment]
See related discussions on the cpptools extension : https://github.com/microsoft/vscode-cpptools/issues/6798

**Comment by benmcmorran** [comment]
Thanks for the detailed report and opening a PR with a fix!
