### ISSUE TITLE
Bad executable

### ISSUE THREAD

**Issue by yudi-azvd** [microsoft/vscode-cmake-tools#3359]
### Brief Issue Summary

I use [asdf](https://github.com/asdf-vm/asdf) and [asdf-cmake](https://github.com/srivathsanmurali/asdf-cmake) for my CMake installation. Until some weeks ago, **I could use the VSCode CMake extension with no problems**. But today I get the following error:

```
Bad CMake executable: "<path>". Check to make sure it 
is installed or the value of the "cmake.cmakePath" setting 
contains the correct path
```

I've already tried setting `cmakePath` to the following values:

- leaving blank
- `cmake`
- `/home/yudi/.asdf/installs/cmake/3.25.2/bin/cmake`
- `/home/yudi/.asdf/shims/cmake`

But all result in the same error: Bad CMake executable.

### CMake Tools Diagnostics

<details>
<summary>Diagnostics</summary>

```
{
  "os": "linux",
  "vscodeVersion": "1.82.2",
  "cmtVersion": "1.15.31",
  "configurations": [
    {
      "folder": "/home/yudi/Documents/1-projetos/programming/hassembler",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```
</details>

### Additional Information

Some logs from the Output tab:

```
[proc] Executing command: ~/.asdf/installs/cmake/3.25.2/bin/cmake --version
[proc] The command: ~/.asdf/installs/cmake/3.25.2/bin/cmake --version failed with error: Error: spawn ~/.asdf/installs/cmake/3.25.2/bin/cmake ENOENT
[proc] Executing command: ~/.asdf/installs/cmake/3.25.2/bin/cmake -E capabilities
[proc] The command: ~/.asdf/installs/cmake/3.25.2/bin/cmake -E capabilities failed with error: Error: spawn ~/.asdf/installs/cmake/3.25.2/bin/cmake ENOENT
[proc] Executing command: /home/yudi/.asdf/shims/cmake --version
[proc] The command: /home/yudi/.asdf/shims/cmake --version exited with code: 1
[proc] Executing command: /home/yudi/.asdf/shims/cmake -E capabilities
```

Running the following commands from my terminal or VSCode terminal result in the expected behavior.

```sh
cmake --version
/home/yudi/.asdf/shims/cmake --version
~/.asdf/installs/cmake/3.25.2/bin/cmake --version

# output
cmake version 3.25.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```

**Comment by gcampbell-msft** [comment]
@yudi-azvd Since this is happening on older versions as well, this doesn't seem to be a regression. Could you attempt to run the command `CMake: Reset CMake Tools Extension State (for troubleshooting)`, and then ensure that you configure your cmake path to your cmake installation, and see if this issue still persists?

**Comment by gcampbell-msft** [comment]
I'm glad that it got resolved, thanks!

**Comment by rwarren** [comment]
I've been having this exact same problem, and am also using asdf for my cmake version.

I figured out what the issues is: it is that the cwd that the cmake extension is running in is not the project cwd, and the `tool-versions` file is not found in the parent dir tree.  When this happens, the asdf shim cannot work properly, and returns exit code 126.

For example:
```
~/asdf_demo$ ls -al | grep tool
-rw-r--r--  1 russ russ   84 Mar 12 12:45 .tool-versions
~/asdf_demo$ cat .tool-versions
# This file specifies the tool versions to use with asdf
cmake 3.28.3
python 3.11.8
~/asdf_demo$ /home/russ/.asdf/shims/cmake --version
cmake version 3.28.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
~/asdf_demo$ cd ..
~$ /home/russ/.asdf/shims/cmake --version
No version is set for command cmake
Consider adding one of the following versions in your config file at
cmake 3.28.3
~$ echo $?
126
```

Here is an example cmake extension output that runs into this issue (when `cmakePath` is set directly to the shim script):
```
[proc] Executing command: /home/russ/.asdf/shims/cmake --version
[proc] The command: /home/russ/.asdf/shims/cmake --version exited with code: 126
[proc] Executing command: /home/russ/.asdf/shims/cmake -E capabilities
[proc] The command: /home/russ/.asdf/shims/cmake -E capabilities exited with code: 126
```

Definitely a working directory issue.  Is there some way to force the working dir that the extension script is using?  I woudl have thought it would be `${workspaceFolder}`, but it does not seem to be.  Maybe the working dir is just not set early enough in the init process?

In my case, setting `cmakePath` to the direct executable works fine, like `/home/russ/.asdf/installs/cmake/3.28.3/bin/cmake`, bit having to set a direct path to a specific version is obviously non-ideal here when using `asdf`.

On that note, setting a direct user path is also not ideal.  How do you access env vars for the `cmakePath`? I have a cross-platform and cross-user project where I'm trying to use a `CMAKE_HOME` env var to abstract away the differences in cmake location, but the cmake extension doesn't seem to expand env vars, showing this in the vscode output log:

```
[proc] Executing command: ${env:CMAKE_HOME}/cmake --version
[proc] The command: ${env:CMAKE_HOME}/cmake --version failed with error: Error: spawn ${env:CMAKE_HOME}/cmake ENOENT
[proc] Executing command: ${env:CMAKE_HOME}/cmake -E capabilities
[proc] The command: ${env:CMAKE_HOME}/cmake -E capabilities failed with error: Error: spawn ${env:CMAKE_HOME}/cmake ENOENT
```

**Comment by Yingzi1234** [comment]
@rwarren Thank you for your contribution to the developer community. Since this issue has been closed for a long time, could you recreate a new issue with **detailed steps and more information** on reproducing it? Thanks.
