### ISSUE TITLE
/docs/debug-launch.md seems out of date with respect to non-launch-config debugging

### ISSUE THREAD

**Issue by starball5** [microsoft/vscode-cmake-tools#3360]
### Brief Issue Summary

https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md

- There is no longer any command named `CMake: Debug Target` (in the "quick debugging" section). Instead, there is `CMake: Debug`.
- What even is this "quick debugging" feature? The docs for it state: "_Quick-debugging does not let you specify program arguments or other debugging options. See the next section for more options._". If that's the case, then what's the `cmake.debugConfig` setting?
- There is no longer any command name `CMake: Execute the current target without a debugger` (in the "Run without debugging" section). Instead, there is `CMake: Run Without Debugging`.

The doc makes no mention of the `cmake.debugConfig` setting, which I discovered from reading https://github.com/microsoft/vscode-cmake-tools/issues/924#issuecomment-845539774.

Am I just looking at the wrong doc?

Also, I don't see the `cmake.debugConfig` setting listed in https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#cmake-settings. Why is that?

Note to self: Once I get more info, update https://stackoverflow.com/a/77204339/11107541.

**Comment by benmcmorran** [comment]
Thanks for bringing this to our attention! I'm marking this as documentation bug that we'll work on in our upcoming 1.16 release.

@sinemakinci1 FYI for a documentation gap

**Comment by sinemakinci1** [comment]
Hi @starball5 , the documentation has been updated for the latest experience for debugging without a launch.json. Please let us know if you see any other issues!

**Comment by starball5** [comment]
Thanks! I think it would be nice to mention the `cmake.debugConfig` setting in https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md#run-without-debugging and to say what schema it uses (the same on as the `cppdbg` launch configuration type?) in https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-settings.md#cmake-settings

**Comment by sinemakinci1** [comment]
@starball5 Run without debugging doesn't really use a debug config, it just invokes the built executable without debugging attached in a terminal, so the default debugConfig is null, which is what I put in the documentation. Is there anything else I should add to clear that up, like explicitly calling that out in the run without debugging section?

**Comment by starball5** [comment]
> like explicitly calling that out in the run without debugging section

Yes, that would be great! It would also be nice to specify in the `cmake.debug` setting's doc what schema it uses. Is it mostly just the same schema as the `cppdbg` launch config?

This does bring up a thought for me, which is that (and this was actually what I'd expect to happen) it would be nice for the non-debugger-specific parts of the `cmake.debugConfig` property to be used when running without debugging: `additionalSOLibSearchPath`, `args`, `cwd`, `environment`, `externalConsole`, and `symbolSearchPath`, but I guess that would be the subject of a separate issue ticket. **To confirm**- the current behaviour is that `cmake.debugConfig` has _no effect_ on running without debugging, right?
