### ISSUE TITLE
Investigate Language Services for CMake

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode-cmake-tools#3375]
### Brief Issue Summary

We'd like to investigate the level of language service support we currently have for CMake and if there are ways that we can improve it.

**Comment by benmcmorran** [comment]
@gcampbell-msft What differentiates this issue from #534 and #93 (rank 1 and 3, respectively, by 👍 reacts).

**Comment by gcampbell-msft** [comment]
I'm going to close this in favor of #534 and #93
