### ISSUE TITLE
"cmake.ctestArgs" setting ignored (possible because using presets?)

### ISSUE THREAD

**Issue by RealLitb** [microsoft/vscode-cmake-tools#3390]
I defined the following in my settings.json

    "cmake.ctestArgs": [
       "--output-on-failure"
    ],

In the default, it included  "-T test" in this list. However, The CMake tools extension still executes the tests as follows:

    [proc] Executing command: /usr/bin/ctest -T test ...

Why does it not apply the setting? I can't change that with CMakePresets.json.. so there seems no place I can inhibit those flags.

_Originally posted by @RealLitb in https://github.com/microsoft/vscode-cmake-tools/discussions/3385_

**Comment by owenstranathan** [comment]
I am having a similar issue when using custom presets.
I had the setting:
```
    "cmake.configureSettings": {
        "ADDONS_DIR": "${workspaceFolder}/addons",
    }
```
in my workspace `.vscode/settings.json` file
it worked fine when using the default presets from the cmake tools.
I made some custom presets and started using those and now the configure set does not seem to be respecting the workspace args at all.
Seems like using workspace presets causes the tool to ignore workspace settings

**Comment by gcampbell-msft** [comment]
@owenstranathan @RealLitb Thanks for your feedback. In general, yes, the CMake Tools extension, as well as the overall design for CMake Presets, is to ignore the specific settings from the CMake Tools extension when using presets. 

However, our most recent versions of the extension should allow for these arguments to override temporarily, so this issue should be resolved. 

Additionally, @RealLitb you could set up a test preset with `output.outputOnFailure` enabled: `{ "output": "outputOnFailure": true}`. Closing. Thanks! Please open a new issue if you are still hitting issues.
