### ISSUE TITLE
Repost: Support arguments for environment setup script

### ISSUE THREAD

**Issue by Korki-Fork** [microsoft/vscode-cmake-tools#3418]
### Brief Issue Summary

Hello,

I'm referring to the request here: [Support arguments for environment setup script #1732](https://github.com/microsoft/vscode-cmake-tools/issues/1732)

It would be great if we could finally get the option to provide arguments to the "environmenSetupScript" (in kit definition).

That's all.
Thank you and kind regards.

**Comment by snehara99** [comment]
Hi @Korki-Fork having duplicate issues can get confusing for our backlog so I need to close this, but please go upvote/comment on the other issue and we'll take note of your interest! Thanks!
