### ISSUE TITLE
Updates to the CMake Tools Status Bar and Side Bar

### ISSUE THREAD

**Issue by sinemakinci1** [microsoft/vscode-cmake-tools#3423]
Available now in the official 1.16.29 release, the CMake Tools extension UI has been updated to incorporate the feedback we have received from our users in our first experimental implementation, while taking into consideration customer requests to de-clutter the status bar.  In that, we have provided a customizable UI, and more notification and docs to support the user through this change.

You should see this notification once you are updated to the new experience:
<img width="335" alt="cmake notification" src="https://github.com/microsoft/vscode-cmake-tools/assets/99284450/c658b3ea-a757-4c4e-a62f-c6cdd3f2de5c">

The status bar will now only contain commonly used CMake actions by default- Build, Debug, and Run.
<img width="376" alt="cmake-new-status-bar" src="https://github.com/microsoft/vscode-cmake-tools/assets/99284450/221f20c3-5768-435c-b451-abed18d11f1f">

We have added options to the CMake Tools side bar for users to select their active Configure, Build, and Test Presets, kits and variants, and active targets. There are new options up at the top of the Project Status View for Deleting Cache and Reconfiguring and access CMake settings.
Both the new status bar and side bar are customizable, so you can configure your view across the status bar and side bar to add other options you may want to the status bar or exclude ones you don't need from the side bar. 

To learn more about how you can customize this view, please see: [our view configuration docs](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-options-configuration.md).

If you would like to opt-back to the previous side bar with all the available CMake options, please set the **CMake Status Bar Visibility** setting in the VS Code Settings to `visible`

<img width="749" alt="cmake-visibility-v2" src="https://github.com/microsoft/vscode-cmake-tools/assets/99284450/2835d5fe-41a3-48c7-ac0d-ab7f0cca57bb">

Please comment any feedback you have on this experience on this issue. Our goals are to add CMake tasks to the side bar in the near future.

**Comment by Zingam** [comment]
It looks a bit ugly and confusing. I hope you continue improving on the new UI.

**Comment by snehara99** [comment]
thanks for your feedback @Zingam, if you have any specific suggestions, we'd love to hear them as well. The UI is a work in progress, but something to note though is that our implementation of the VSCode Extension [Tree View API](https://code.visualstudio.com/api/extension-guides/tree-view) for the sidebar limits us a bit in customizing its appearance. We may switch to a more flexible view in the future once the team has more bandwidth though.

**Comment by findNextStep** [comment]
how to disable this part 
![image](https://github.com/microsoft/vscode-cmake-tools/assets/26270464/679a32e3-42ef-4201-ab94-44be741937ba)
I try every option in json and cannt hidden it

**Comment by gcampbell-msft** [comment]
> how to disable this part ![image](https://user-images.githubusercontent.com/26270464/281252614-679a32e3-42ef-4201-ab94-44be741937ba.png) I try every option in json and cannt hidden it

@snehara99 FYI

**Comment by snehara99** [comment]
@findNextStep I apologize the "cmake.options.advanced" setting had a bug with the "variant" option. This should now be fixed in the 1.16.25 pre-release version of CMake Tools!

How to set that status bar option to be hidden:
`"cmake.options.advanced": {
     "variant": {
          "statusBarVisibility": "hidden"
     }
}`

**Comment by quyykk** [comment]
I would like to see a bit more in the default status bar:

- Switching build presets. It is common to switch between Debug/Release, so I think having that in the status bar makes sense.
- The "Run CTest" button. Running tests is a pretty common thing to want to do I would say.
- Switching test presets. Switching test presets is also a pretty common thing to do, at least in my workflow.
- 
Thoughts?

**Comment by sinemakinci1** [comment]
> I would like to see a bit more in the default status bar:
> 
> * Switching build presets. It is common to switch between Debug/Release, so I think having that in the status bar makes sense.
> * The "Run CTest" button. Running tests is a pretty common thing to want to do I would say. (you could probably just add the icon and drop the text though)
> * Switching test presets. Switching test presets is also a pretty common thing to do, at least in my workflow.
> 
> Thoughts?

Thank you for your feedback -  we chose our historically most commonly performed actions to put in the status bar by default which were Build, Debug, and Launch to keep the integrity of a simplified status bar but appreciate the verbal feedback on your workflows. You can configure the status bar to have all of these by default via your settings.json for now and we can take these thoughts into consideration in future designs.

**Comment by findNextStep** [comment]
> @findNextStep I apologize the "cmake.options.advanced" setting had a bug with the "variant" option. This should now be fixed in the 1.16.25 pre-release version of CMake Tools!
> 
> How to set that status bar option to be hidden: `"cmake.options.advanced": { "variant": { "statusBarVisibility": "hidden" } }`

update to 1.16.26 and it work fine ! thx

**Comment by Zingam** [comment]
> Thank you for keeping the status bar. This update was a much better experience than when the status bar suddenly disappeared last time :)
> 
> The new configurability of the status bar is really nice! I want to see some more things in it, but I can see how the new default configuration is cleaner for many people and the notification works well for the transition.

Thank you for the work. It is definitely a step in the right direction and an a improvement but as I said before the UI is confusing because of that tree view and it wasn't clear to me what I saw before I saw the message warning about the new side bar implementation. Instead of a tree view something like a standard toolbar would be preferable or a widget panel similar to Visual Studio.

**Comment by tonygould** [comment]
For me, seeing the configure preset in full is essential as I often switch compilers and need to see which one I'm in. However I'd welcome the ability to have everything else as an icon; in particular the build and test presets aren't important. I can't see a way to do this via advanced options, or am I missing something?

**Comment by sinemakinci1** [comment]
@tonygould You can set any setting you want to be an icon via the "statusBarVisibility" variable for that respective setting. i.e.
```
        "buildPreset": { 
            "statusBarVisibility": "icon", 
        }
```
That being said, some of these features don't have icons (Configure, Build Target, Launch Target).

**Comment by tonygould** [comment]
> @tonygould You can set any setting you want to be an icon via the "statusBarVisibility" variable for that respective setting. i.e.
> 
> ```
>         "buildPreset": { 
>             "statusBarVisibility": "icon", 
>         }
> ```
> 
> That being said, some of these features don't have icons (Configure, Build Target, Launch Target).

Perfect, thanks for the help.

**Comment by jhuels** [comment]
> You can configure the status bar to have all of these by default via your settings.json

Can you point to the documentation for these settings?  Not seeing anything in `docs/cmake-settings.md`.

**Comment by sinemakinci1** [comment]
@Zingam You can hide any unnecessary elements from the side bar per the [view configuration docs](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-options-configuration.md) through their parent node setting and setting "projectStatusVisibility" to "hidden".
i.e. what I believe you are asking for is:
```
        "folder": { 
            "projectStatusVisibility": "hidden" 
        },
        "ctest": { 
            "projectStatusVisibility": "hidden" 
        }
```
Launch will launch the build target in a terminal, so it doesn't need a launch.json setting file.

**Comment by misner5** [comment]
As a daily user of VSCode with Cmake Tools I think this is a bad change and has caused confusion and problems. for our team.  The fact that out of box when we install on a new machine it doesn't switch between Debug & Release easily is a major UI error from our perspective.

I recommend you set "Status Bar Visibility" to visible by default... it is a confusing hassle to have it hidden.

**Comment by xgdgsc** [comment]
I also think `visible` should be the default.  You said you want to "de-clutter". But searching for `clutter` only finds one issue https://github.com/microsoft/vscode-cmake-tools/issues/2657 with no votes. So I guess there isn' t actually any "clutter" for most people with sane dev machine / reasonable sized monitor. Or maybe you' ve seen other complaint sources that view these basic functionality as "clutter"?  I personally have hundreds of extensions installed and uses multiple languages inside projects on a daily basis and don' t find it any `clutter`.

**Comment by troberti** [comment]
I also find the `hidden` status bar  to be less usable, and switched back to `compact`. I never use the "Run and Debug" sidebar, because that requires a `launch.json` file, which is cumbersome. The status bar is much more convenient and requires no additional configuration. The only thing that I found strange in the status bar is that the build and run target are specified independently. This does add extra 'clutter' as a target shows up twice.

**Comment by sinemakinci1** [comment]
@xgdgsc Thank you for your feedback, there has been other feedback we've received that isn't using the exact wording of "clutter", but commenting on how much of the status bar was taken up by CMake Tools. Additionally, it can be argued that it is a good practice to put commonly used actions on the status bar and put anything else in an extension-specific side bar as some other extensions do, especially since the status bar is a shared space. This implementation was our best attempt at consolidating all levels of customer feedback and providing user flexibility. However, we really appreciate your feedback on your workflow and will take into consideration with the team!

**Comment by sinemakinci1** [comment]
@misner5 That definitely makes sense, thank you for bringing this up! I opened an issue to track this request: https://github.com/microsoft/vscode-cmake-tools/issues/3555. The main concern with bringing out one level of presets is users may not know to go to the side bar for their other presets or it may create a disjointed workflow, but this seems like a valid request.

**Comment by sinemakinci1** [comment]
@troberti Thank you for your feedback! Actually, better integrating with the "Run and Debug" sidebar is one of our open work items (https://github.com/microsoft/vscode-cmake-tools/issues/3380), but I do understand the need for the status bar specific run and debugs, which were left there to avoid need to go to the CMake side bar. But, again, appreciate the feedback on preferring the compact workflow and will take into consideration with the team with future implementations!

**Comment by H-G-Hristov** [comment]
If I change the build target in the side bar how do I re-select [Targets in Preset] again?

**Comment by sinemakinci1** [comment]
@H-G-Hristov I don't think this functionality exists right now without resetting the entire extension, I opened a bug to look into this! https://github.com/microsoft/vscode-cmake-tools/issues/3587

**Comment by mrexodia** [comment]
I am trying to set up a workshop using GitHub Codespaces (dev containers) and it is majorly confusing that this 'Configure CMake Options Visibility' dialog pops up. I tried adding the following to my `settings.json`, but it complains that this is a user setting:

```
"cmake.showOptionsMovedNotification": false,
```

Is there a way to prevent this popup in dev containers or settings.json? I already had the `cmake.options.statusBarVisibility` option set to `hidden`, but it still pops up this warning...
