### ISSUE TITLE
`cmake.options.advanced` Will Not Show Variant

### ISSUE THREAD

**Issue by cvanbeek13** [microsoft/vscode-cmake-tools#3426]
### Brief Issue Summary

With the new Status Bar updates (#3423), the `variant` is not displayed on the status bar if `cmake.options.statusBarVisibility` is set to `hidden`.

Here is my `settings.json` file:

```json
    "cmake.options.statusBarVisibility": "hidden",
    "cmake.options.advanced": {
        "folder": {
            "statusBarVisibility": "visible"
        },
        "build": {
            "statusBarVisibility": "icon"
        },
        "debug": {
            "statusBarVisibility": "icon"
        },
        "launch": {
            "statusBarVisibility": "icon"
        },
        "variant": {
            "statusBarVisibility": "visible"
        },
        "ctest": {
            "statusBarVisibility": "icon"
        },
        "kit": {
            "statusBarVisibility": "hidden"
        }
    },
```

And here's the resulting status bar:

![image](https://github.com/microsoft/vscode-cmake-tools/assets/20888380/153c0b87-0c73-4421-a4e3-cf871424bb51)

If I change `cmake.options.statusBarVisibility` to `visible`, then it shows up.  However, it also expands a few of the icons that I want to keep compact and shows more than I want:

![image](https://github.com/microsoft/vscode-cmake-tools/assets/20888380/1d70a511-61e8-41df-a594-98999c5f13b8)

I'm running CMake Tools `v1.16.23` on VSCode `1.84.1`.

**Comment by gcampbell-msft** [comment]
@cvanbeek13 Thanks for notifying us of this!

@snehara99 FYI.

**Comment by snehara99** [comment]
Hi @cvanbeek13 this issue should now be fixed in the latest pre-release version of CMake Tools (1.16.25). Could you try it out and let me know if your issue is resolved? Thanks!

**Comment by cvanbeek13** [comment]
Yes, this looks like it's working now.  Here are my new settings

```json
    "cmake.options.statusBarVisibility": "icon",
    "cmake.options.advanced": {
        "folder": {
            "statusBarVisibility": "compact"
        },
        "build": {
            "statusBarVisibility": "icon"
        },
        "variant": {
            "statusBarVisibility": "compact"
        },
        "kit": {
            "statusBarVisibility": "hidden"
        },
    },
```

And here's the new status bar:

![image](https://github.com/microsoft/vscode-cmake-tools/assets/20888380/9b3edd85-7435-4dea-aace-787163adb4ef)

One thing that's still a little weird is if I don't specify `icon` for the `build` item, it shows the `compact` version.  I would have expected that since `cmake.options.statusBarVisibility` was set to `icon`, all the items with an `icon` option would show the `icon`.  Maybe that isn't the intention though.  Here's what the status bar looks like without specifying `build`:

![image](https://github.com/microsoft/vscode-cmake-tools/assets/20888380/d7f3b2a6-77e9-4c33-9995-5a04ffe26e33)

**Comment by snehara99** [comment]
@cvanbeek13 your logic makes sense to me, I will update this to the spec that you expect and let you know once it is in pre-release. I'll create a new issue to track this

**Comment by cvanbeek13** [comment]
I think it's probably okay how it is.  I can get it to do what I want by just specifying the `statusBarVisibility`.  I'll close this out.
