### ISSUE TITLE
CMake Tools identifies each project as C or C++

### ISSUE THREAD

**Issue by fssrepository** [microsoft/vscode-cmake-tools#3430]
### Brief Issue Summary

CMake Tools have only menus for all projects inside the VSCode workspace, however i had java and other projects also, what CMake wanted to build, naturally failed before the C project has been built.

1) CMake identifies java project or docker project as C, and generate stuff in it.
2) On git tab i have seen buttons on the menu item. Pls. add on every menu:
    a) we can build/clean projects separately.
    b) we can clean/build internal shared libraries separately.
3) if the settings.json "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools" is missing, then it won't be able to build anything (intellisens plugin fails, even if it's configured correctly in workspace.json), many times i need to restart VsCode to popup the relevant menu again. Can we simplify the config? There is a task.json also, not sure why it's not in the launch.json.
4) I was not able to build the shared library automatically with the main build, however it appeared in the CMake tab.
    Unfortunately, i had to load it, but seems it was in_memory, not sure how i can access that if i don't push the build button on the item in the CMake Tools tab manually.
5) I'm using the Makefile plugin also, maybe that feature set also can go into CMake Tools and make it more standard.

The experience is kind of messy, makes lots of noises around the focus of development.

**Comment by snehara99** [comment]
Hi @fssrepository thanks for bringing these issues/suggestions to our attention. If possible, could you separate them out into separate issues? It would then be easier to track and label appropriately on our end.
