### ISSUE TITLE
Running on Windows without having to run Code from VIsual Studio CLI promp?

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#3436]
### Brief Issue Summary

Is that possible? I use cmake presets and in the latest version I am unable to get the project to properly configure unless I run code from a VS CLI promp.

**Comment by snehara99** [comment]
Hi @Zingam, would you be able to fill out the sections outlined in this issue (CMake Tools Diagnostics and Debug Log) and also provide us with a sample project so that we can investigate this issue? Thanks!

**Comment by H-G-Hristov** [comment]
It looks like that this is a related issue: https://github.com/microsoft/vscode-cmake-tools/issues/3413

**Comment by benmcmorran** [comment]
I suspect this is the same issue as #3440. Can you try installing CMake Tools 1.16.30 (just released) and see if it resolves your issue?

**Comment by H-G-Hristov** [comment]
@H-G-Hristov I was going to ask if https://github.com/microsoft/vscode-cmake-tools/pull/3445 resolves this issue.

**Comment by Zingam** [comment]
My project uses C++23 and C++20 modules and uses Win32. 

With a MSBuild configuration I am able to build the project.

I have installed CMake 3.28-RC3 and I use Ninja-Multiconfig. After the configuring the project the build fails. It seems the Windows SDK headers are not found. The issue seems similar to an issue I also have with Visual Studio 2022, a custom CMake 2.38 + Ninja (same CMake profile).
If I use the built-in CMake 2.37 in VS2022 (the latest preview) the project builds. 
I'll wait for the final release of CMake 2.38, and if the problem persists I'll try to provide a repro.

**Comment by snehara99** [comment]
> @benmcmorran I was going to ask if #3445 resolves this issue.

It should!

**Comment by snehara99** [comment]
> My project uses C++23 and C++20 modules and uses Win32.
> 
> With a MSBuild configuration I am able to build the project.
> 
> I have installed CMake 3.28-RC3 and I use Ninja-Multiconfig. After the configuring the project the build fails. It seems the Windows SDK headers are not found. The issue seems similar to an issue I also have with Visual Studio 2022, a custom CMake 2.38 + Ninja (same CMake profile). If I use the built-in CMake 2.37 in VS2022 (the latest preview) the project builds. I'll wait for the final release of CMake 2.38, and if the problem persists I'll try to provide a repro.

Hi @Zingam did you try updating to the newest release to see if that fixes your issue as well?

**Comment by Zingam** [comment]
Hi @Zingam I upgraded the extension to the latest version. I am seeing a similar if not the same issue with external custom CMake 3.28 in Visual Studio: https://developercommunity.visualstudio.com/t/CMake:-Unable-to-build-project-with-cust/10516211#T-ND10518466
I'll wait for the final version of CMake 3.28 before I do further investigations.

**Comment by Zingam** [comment]
It turns out my issue was related to a new CMake policy related to C++20 modules.
