### ISSUE TITLE
Commands with folder arguments broken

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cmake-tools#3446]
### Brief Issue Summary

Commands with folder arguments, like build, are now broken.

Repro steps:
1. Create an extension (A), that depends on CMakeTools.
2. In extension (A), do something like:
    ```
    async test() {
        if (!vscode.workspace.workspaceFolders) return;
        for (const folder of vscode.workspace.workspaceFolders) {
            await vscode.commands.executeCommand("cmake.build", folder);
        }
    }
    ```
3. Build and install extension (A), open a multiroot workspace containing multiple CMake projects, and run `test`.

Expected:
All folders are built.

Actual:
Only the first folder is built.

Note:
I think this command has been broken for `build` for several versions, but some other commands triggers `build` worked, so we didn't hit this issue. Now none of them work, and this breaks our extension.

**Comment by benmcmorran** [comment]
Are you able to use [the API](https://github.com/microsoft/vscode-cmake-tools-api) instead? I'm not sure if the commands have ever been an officially supported extensibility point.

**Comment by xisui-MSFT** [comment]
@benmcmorran Since we wrote our extension before this API, we didn't have this option. While we can try that API, I do hope this issue can be fixed so our extensions that are already published won't be broken.

**Comment by gcampbell-msft** [comment]
@xisui-MSFT Is this specific to the latest CMake Tools version?

**Comment by gcampbell-msft** [comment]
@xisui-MSFT I just followed your repro steps and wasn't able to reproduce the issue. I'm seeing that all of the folders are built. Is there any way that you could provide a repro project and/or a video of what you're seeing? Thanks.

**Comment by xisui-MSFT** [comment]
Actually this commit https://github.com/vlavati/vscode-cmake-tools/commit/3cfda1ad18cb4cb5a0ba0818c68fc989859c41c2. Why are object parameters required?

**Comment by gcampbell-msft** [comment]
This has been fixed.
