### ISSUE TITLE
toolset ignored, need CMAKE_GENERATOR_TOOLSET

### ISSUE THREAD

**Issue by brccabral** [microsoft/vscode-cmake-tools#3450]
### Brief Issue Summary

The CMakePresets.json has an option "toolset" but the CMake Tools extension ignores it.
If I run from command line `cmake.exe` detects it, but using the extension it doesn't detect `clang-cl`.
I need to add `CMAKE_GENERATOR_TOOLSET` for the extension to detect `clang-cl`, but as said, the command line doesn't need it.
```json
        {
            "name": "clang-x64-debug",
            "displayName": "Win Clang x64 Debug",
            "inherits": "x64-debug",
            "toolset": "ClangCL", // command line only needs this
            "cacheVariables": {
                "CMAKE_GENERATOR_TOOLSET": "ClangCL" // extension needs this
            }
        },
```

**Comment by gcampbell-msft** [comment]
@brccabral We're wondering if this has possibly been fixed with the most recent release, could you test again? Thank you.

**Comment by brccabral** [comment]
Hi @gcampbell-msft , yes, v1.16.31 works with just `"toolset": "ClangCL"`

**Comment by leolcao** [comment]
@gcampbell-msft I find cmake-tools(v1.19.52) doesn't support the format:

```json
{
    "toolset": 
   {
       "value": "ClangCL"
   }
}
```

but cmake command does
