### ISSUE TITLE
Cannot debug with amd64 tool-kit version 

### ISSUE THREAD

**Issue by buzd3v** [microsoft/vscode-cmake-tools#3459]
### Brief Issue Summary

OS: Window

I try to debug with Clang for MSVC - amd64 and Visual Studio Community - amd64 tool-kit but when i using debug utility it show nothing, but it do works with others tool-kit

**Comment by snehara99** [comment]
Hi @buzd3v thank you for creating this issue. To better help us investigate your problem, could you provide the requested CMake Tools Diagnostics and Debug Log? If possible, it would also help if you could provide us a sample project where you encounter this issue, thanks!
