### ISSUE TITLE
Status Bar icon view hides build target selector

### ISSUE THREAD

**Issue by kmbgit** [microsoft/vscode-cmake-tools#3461]
### Brief Issue Summary

The recent changes to the status bar threw me for a while - I had to read the ChangeLog to discover the new Project Status View! - but now I've found it I quite like the change as it removes clutter from the status bar.  HOWEVER ... if I switch to "icon" view then the default build target selector disappears, which is a bit of a nuisance as that's the thing I use most.

Perhaps you could add even more sub-options under cmake.options.advanced.build to control the visibility of each individual element - buildVariant, activeKit and defaultBuildTarget?

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.84.2",
  "cmtVersion": "1.16.31",
}
```

**Comment by sinemakinci1** [comment]
Hi @kmbgit ,
You can fully configure each item you want to add to the view after specifying your statusBarVisibility setting, under the cmake.options.advanced settings, as shown in our docs here: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/cmake-options-configuration.md
 

For example, what I think you would to specify (if you want your build target, variant, and kit): 
```
"cmake.options.advanced": { 
        "kit": { 
            "statusBarVisibility": "visible"
        }, 
        "variant": { 
            "statusBarVisibility": "visible"
        }, 
        "buildTarget": { 
            "statusBarVisibility": "visible"
        }
}
