### ISSUE TITLE
"Not all open documents were saved" popup appears in unhelpful position, prematurely

### ISSUE THREAD

**Issue by kmbgit** [microsoft/vscode-cmake-tools#3462]
### Brief Issue Summary

I'm running VSCode on a Mac mini with the Remote::SSH extension doing its thing on an ARM evaluation board running Debian Bullseye Linux, so CMake Tools v1.16.31 is running on that board.  When I hit the "Build" button in the status bar at the bottom-left of the screen I often get a **"Not all open documents were saved. Would you like to continue anyway?"** popup window appearing in the bottom-right corner, with **"Source: CMake Tools (Extension)"** laying the blame at this module.

My first complaint is with the position of the window, which is right on the other side of the VSCode window to the "Build" button.  I'm using an 86cm Ultrawide Quad HD 3440x1440 screen, so when I'm looking at the button to click on it, the window pops up in the peripheral vision of my right eye and I often don't notice it appear.  Instead all I see is nothing happening in the output window and I have to go looking for the reason.  Ideally the popup window should appear close to where I clicked the mouse, though I'd settle for it being in the centre of the VSCode window.

My second complaint is with the appearance of this window at all, because all the files HAVE been saved.  Maybe it takes a little longer for VSCode to realise this because I'm using Remote:SSH so the save has to complete on the remote ARM evaluation board rather than the local machine that's running VSCode.  I always end up clicking "Yes" to get the build to start, so really this is just wasting time with false warnings.

**Comment by kmbgit** [comment]
Looks like a dupe of https://github.com/microsoft/vscode-cmake-tools/issues/2889.

Also, I see this when the unsaved file has a diff tab open, and closing the diff tab makes the "not all saved" problem go away, as discussed against 2889.

**Comment by snehara99** [comment]
Hi @kmbgit thank you for bringing this up. It seems like we may be externally blocked by this issue ([reference](https://github.com/microsoft/vscode-cmake-tools/issues/2889#issuecomment-1373986955)). Also as this is a duplicate, I'll close it so that the original issue can get more visibility. It will help visibility if you like/comment on #2889 itself.
