### ISSUE TITLE
Build info in output panel uses ANSI escape codes while it doesn't support it.

### ISSUE THREAD

**Issue by nielsmittertreiner** [microsoft/vscode-cmake-tools#3464]
### Brief Issue Summary

As stated, the build info that is presented in the output panel tries to display ANSI escape codes for colors and such, however, VSCode's output panel does not support ANSI formatting.
Because of this, warnings and errors thrown by a compiler are much harder to read.
Here's an example:
![afbeelding](https://github.com/microsoft/vscode-cmake-tools/assets/25991043/b8b823a4-0e14-4db7-8338-3c8d9b6e5510)

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.84.2",
  "cmtVersion": "1.16.31",
  "configurations": [
    {
      "folder": "/home/nielsmittertreiner/agbcpp",
      "cmakeVersion": "3.25.1",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": true,
      "compilers": {
        "C": "/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc",
        "CXX": "/opt/devkitpro/devkitARM/bin/arm-none-eabi-g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 3,
    "executablesCount": 1,
    "librariesCount": 2,
    "targets": [
      {
        "name": "agbcpp",
        "type": "EXECUTABLE"
      },
      {
        "name": "librom",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "libagx",
        "type": "STATIC_LIBRARY"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

**Comment by snehara99** [comment]
Hi @nielsmittertreiner Thanks for your post. As you saw this issue is related to #3203, and the reason this happens is detailed [here](https://github.com/microsoft/vscode-cmake-tools/issues/3203#issuecomment-1589638315). We are tracking votes on #3203 for interest, so I will close this as a duplicate because votes can get diluted if spread between two issues. Please like that issue if you haven't already, thanks again!
