### ISSUE TITLE
Run one test case of a google test 

### ISSUE THREAD

**Issue by infn-ke** [microsoft/vscode-cmake-tools#3467]
### Brief Issue Summary

How can I run just one single test case inside a google test without having a launch.json passing --gtest_filter?

**Comment by H-G-Hristov** [comment]
Select the test in the test explorer and click on the triangle? Doesn't that work for you. You should also see such triangles in the code editor and right clicking should display a context menu related to the tests.

**Comment by infn-ke** [comment]
> Select the test in the test explorer and click on the triangle? Doesn't that work for you. You should also see such triangles in the code editor and right clicking should display a context menu related to the tests.
> 
> Have you installed the extension C++ Test mate which you need for gtest support?

So vscode-cmake-tools is not sufficient to run gtest? I tried c++ test mate, but still cannot run individual test cases (`TEST` and `TEST_F`).

**Comment by H-G-Hristov** [comment]
> > Select the test in the test explorer and click on the triangle? Doesn't that work for you. You should also see such triangles in the code editor and right clicking should display a context menu related to the tests.
> > Have you installed the extension C++ Test mate which you need for gtest support?
> 
> So vscode-cmake-tools is not sufficient to run gtest? I tried c++ test mate, but still cannot run individual test cases (`TEST` and `TEST_F`).

This extension is about CMake. For tests support you need another extension. C++ Test mate is the extension for C++.

If I undestand your problem correctly, here I have run a single test:

![Screenshot 2023-11-27 at 17 49 24](https://github.com/microsoft/vscode-cmake-tools/assets/47526411/96b60905-866f-429b-b9a7-0c6aff1989c1)

**Comment by H-G-Hristov** [comment]
These are my tests: 

![Screenshot 2023-11-27 at 17 51 05](https://github.com/microsoft/vscode-cmake-tools/assets/47526411/b7aafe0a-50df-42b8-83a1-f0662327b438)
![Screenshot 2023-11-27 at 17 50 55](https://github.com/microsoft/vscode-cmake-tools/assets/47526411/34e2cfb2-f6ea-4353-9fe6-8f9625f3822f)

**Comment by snehara99** [comment]
Hi @infn-ke let us know if you still need more guidance. Until then I will mark this as 'more information needed'. Also thank you for your help @H-G-Hristov!

**Comment by infn-ke** [comment]
Thanks for the help on this @H-G-Hristov ! I can get the same results by installing the same extension you said.
