### ISSUE TITLE
Remote extension host unexpectedly ended 3 times in 5 minutes

### ISSUE THREAD

**Issue by borjamunozf** [microsoft/vscode-cmake-tools#3469]
### Brief Issue Summary

I have executed **Extension Bisect** to identify the problematic extension and identified CMake as the cause:
- Open my C++ project (it's a company & production grade).
- Try to configure the project with CMake (we have CMakePresets on place).
- Endless loop of restaring VSCODE, crashes and shows Remote Extension unexpectedly ended 3 times in 5 minutes.

Expected results:
- Able to configure the project, build & so on. Normal developer flow.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.84.2",
  "cmtVersion": "1.16.31",
  "configurations": [
    {
      "folder": "/home/borjamf/workspace/quefacemos",
      "cmakeVersion": "3.27.7",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {}
    },
    {
      "folder": "/home/borjamf/workspace/quefacemos/quefacemos_auto_test",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/home/borjamf/workspace/quefacemos/quefacemos_gui",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
Can't copy the Developer Tools > Console, no option to save as is working. A snippet:
```

![imagen](https://github.com/microsoft/vscode-cmake-tools/assets/25910927/ef3deeac-8413-4b1c-80f4-e7a1d2ea8945)

![imagen](https://github.com/microsoft/vscode-cmake-tools/assets/25910927/5d6fc806-e5c5-41b0-bd4b-127f1b4e7cdc)

### Additional Information

Intel (R) Xeon(R) Gold 6248R CPU @ 3.00GHz (12 x 2993)
RAM: 64GB

Replaced some real names & projects with others.

**Comment by snehara99** [comment]
Thank you @borjamunozf for your detailed issue. For more context, does this happen with any other CMake projects on your machine, or just this one?

**Comment by snehara99** [comment]
Also, it would help if you could answer these questions: 
- Has this project ever worked on your machine/is this a recent regression? 
- Does this issue occur on any other machine, if you have access to one?

**Comment by borjamunozf** [comment]
Only fu

> Thank you @borjamunozf for your detailed issue. For more context, does this happen with any other CMake projects on your machine, or just this one?

Not exactly, but it's true that other project got a really similar behaviour (enter in a configure cmake loop, vscode restarts) time ago. 

> Also, it would help if you could answer these questions:
>   Has this project ever worked on your machine/is this a recent regression?
 >  Does this issue occur on any other machine, if you have access to one?

Other devs in different machines has the same issue, I mean, everyone who opens this project & tries to configure with CMakeTools gets the same behaviour.

It's the first time we try this project in VSCODE. More than 100 developers are transitioning to VSCODE from QTCreator in my company and it's been a really bumpy road with a lot of issues (not strictly your extension only, of course!) with VScode for C++ development in complex projects.

Anything I could help with? more logs, snippets?

**Comment by snehara99** [comment]
Last thing, @borjamunozf could you provide a screenshot of what you found using the Extension Bisect utility? Thanks again!

**Comment by borjamunozf** [comment]
Quick update: I have to do a few more tests, but I think that I have just found the root cause.

- Disable loadCompileCommands in settings.json
```json
    "cmake.loadCompileCommands": false
```

![imagen](https://github.com/microsoft/vscode-cmake-tools/assets/25910927/25dc58e0-d482-4962-8993-b9d219c87c40)

After setting this, I have opened the project 3-4 times and it has not crash. However, reverting this & enabling to true, opening again the project triggers the crash.

**Comment by Agomezvi** [comment]
> Quick update: I have to do a few more tests, but I think that I have just found the root cause.
> 
> * Disable loadCompileCommands in settings.json
> 
> ```json
>     "cmake.loadCompileCommands": false
> ```
> 
> ![imagen](https://private-user-images.githubusercontent.com/25910927/286412221-25dc58e0-d482-4962-8993-b9d219c87c40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDcyOTQsIm5iZiI6MTcwMTI0Njk5NCwicGF0aCI6Ii8yNTkxMDkyNy8yODY0MTIyMjEtMjVkYzU4ZTAtZDQ4Mi00OTYyLTg5OTMtYjlkMjE5Yzg3YzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA4MzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTAyZDFiMTJhNGUyODUxZDQ1MjEyZTAxNmUzY2JjYzg4Y2ZmNzAwZmQ0NjQ0NzE0N2ZhOWE4ZjAxYTVjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eTYIP0hy1x4sw0e7iAJW-scz9bQJpMYLmtXQo73-Khs)
> 
> After setting this, I have opened the project 3-4 times and it has not crashed. However, reverting this & enabling to true, opening again the project triggers the crash.


This works for me too. It would be good if it was set to false by default. Thank you

**Comment by lukka** [comment]
@Agomezvi  @borjamunozf do you have a small project which you can share with us which is reproing the problem?

**Comment by borjamunozf** [comment]
Sadly, we're using complex & production grade projects in my company, it would be really hard to create a repo that triggers the issue with a small one.

However, another news or info regarding this issue:
- Without disabling  "cmake.loadCompileCommands": false loading, if we modify the **NODE_OPTIONS** environment variable and save it in the user .bashrc like this:

export NODE_OPTIONS="--max-old-space-size=8192"

it solves the crash loop.

**Comment by bidjc** [comment]
Good solution,thank you
 "cmake.loadCompileCommands": false
