### ISSUE TITLE
Can you remove this assertion failure in multiroot?

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#3474]
I keep hitting this asserion failure when debugging our C/C++ extension.

            console.assert(this.projectController.numOfWorkspaceFolders === vscode.workspace.workspaceFolders?.length);
            
at https://github.com/microsoft/vscode-cmake-tools/blob/8018ef5d5edfa9a06af6f88c7e5e9ea999b693fe/src/extension.ts#L118 .

Can you remove that?

My repro is with a multiroot workspace in which one or more of the workspace folders doesn't have a CMakeLists (or isn't configured to build with it).

this.projectController.numOfWorkspaceFolders is 1

and vscode.workspace.workspaceFolders?.length is 2+.

**Comment by sean-mcmanus** [comment]
Oh -- I found out the breaking in the debugger was caused by the "Unchecked exceptions" options being checked -- if I uncheck that then it doesn't always break in the debugger from this.

**Comment by sean-mcmanus** [comment]
@gcampbell-msft Yeah, I could also submit a PR too if you want.

**Comment by gcampbell-msft** [comment]
#3485
