### ISSUE TITLE
[debugger] cannot debug vcpkg using cmake tools

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vscode-cmake-tools#3476]
### Brief Issue Summary

Hi guys,
Today I tried to debug the portfile in vcpkg according to [the official doc](https://devblogs.microsoft.com/cppblog/debug-vcpkg-portfiles-in-cmake-script-mode-with-visual-studio-code/).
After adding `tasks.json` and `launch.json` and then clicking the `Debug zlib portfile` button, I got:
<img width="1500" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/47264268/3c291308-c18e-46c5-acf3-3e8ae931eb49">

Also, in TERNIMAL, I got some errors:
```
 *  Executing task: & "/Users/jackyu/Documents/vcpkg/vcpkg" remove zlib; & "/Users/jackyu/Documents/vcpkg/vcpkg" install zlib --no-binarycaching --x-cmake-debug \\.\pipe\portfile_debugging 

zsh:1: parse error near `&'

 *  The terminal process "/bin/zsh '-l', '-c', '& "/Users/jackyu/Documents/vcpkg/vcpkg" remove zlib; & "/Users/jackyu/Documents/vcpkg/vcpkg" install zlib --no-binarycaching --x-cmake-debug \\.\pipe\portfile_debugging'" failed to launch (exit code: 1). 
 *  Terminal will be reused by tasks, press any key to close it. 
 *
```

OS:  macOS 14.1.1.
CMake: 3.27.8
CMake Tools: v1.16.32

Is there any way to fix this?

Thanks.

### Additional Information

After modified the command `& \"${workspaceFolder}/vcpkg\" remove zlib; & \"${workspaceFolder}/vcpkg\" install zlib --no-binarycaching --x-cmake-debug \\\\.\\pipe\\portfile_debugging` to `\"${workspaceFolder}/vcpkg\" install zlib --no-binarycaching --x-cmake-debug \\\\.\\pipe\\portfile_debugging`, the task appears to be executed successfully, but the warning window still appears:
<img width="1131" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/47264268/8779b32a-4003-4afb-9ffc-640332808692">

**Comment by JackBoosY** [comment]
As you can see:
> OS: macOS 14.1.1.
CMake: 3.27.8
CMake Tools: v1.16.32

You can also get launch.json and tasks.json in https://devblogs.microsoft.com/cppblog/debug-vcpkg-portfiles-in-cmake-script-mode-with-visual-studio-code/, they are same except the `.exe` suffix since my OS is macOS.

**Comment by gcampbell-msft** [comment]
@JackBoosY Thanks for reclarifying, sorry I missed that. 

My thought is that the pipe name from that blog post, is a Windows named pipe, following the protocol for naming a pipe in Windows. However, in things like Linux and Mac, I believe it is simply treated as a file, so the format from the blog likely won't work. Could you change the named pipe name to something else? Maybe even a new absolute path, that is in the current directory. 

Let me know if this works for you.

**Comment by JackBoosY** [comment]
> My thought is that the pipe name from that blog post, is a Windows named pipe, following the protocol for naming a pipe in Windows. However, in things like Linux and Mac, I believe it is simply treated as a file, so the format from the blog likely won't work. Could you change the named pipe name to something else? Maybe even a new absolute path, that is in the current directory.

I tried to replace the pipeline with a file path but no luck.
<img width="730" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/47264268/38a5ec42-be65-49d9-bcdf-27c504d8006c">

BTW, I have 2 questions:
1. Is the `&` only support on Windows?
2. Can you please provide the VSCode pipe config related documents?

**Comment by JackBoosY** [comment]
> @JackBoosY To clarify, you also changed the name of the pipe from the task that starts the cmake process, correct?

Yes, in both launch.json and tasks.json.

**Comment by gcampbell-msft** [comment]
What errors are you hitting? 

I was able to follow the blog post with the changes I mentioned and debug the cmake on a spare mac that I have. I made the pipe name /Users/xxx/proj/<folderWithProject/testPipe.

**Comment by JackBoosY** [comment]
<img width="756" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/47264268/03047e7e-6ca9-450b-aa19-541c8ba17a1e">

Is my config correct?

**Comment by gcampbell-msft** [comment]
What do you see in the terminal if you use the command palette to directly run the `Reinstall zlib` task?

**Comment by JackBoosY** [comment]
> What do you see in the terminal if you use the command palette to directly run the `Reinstall zlib` task?
> 
> Based on your output, I wonder if your zlib task is not getting all the way to where it's waiting to connect the cmake debugger, maybe it's failing sometime before then.

```
Error: failed to create debug adapter.
Internal error with /Users/jackyu/Documents/vcpkg/vcpkg_pipe: EADDRINUSE
```

**Comment by gcampbell-msft** [comment]
Ah, okay. Could you `rm` the vcpkg_pipe, it will be a file on your filesystem, and then try to debug again?

**Comment by JackBoosY** [comment]
> Ah, okay. Could you `rm` the vcpkg_pipe, it will be a file on your filesystem, and then try to debug again?

When I manually run the command with `sudo`, terminal shows:
```
<Regluar installation log>
Running with debugger on.
Waiting for debugger clinet to connect...
```
However, I got the error window when using the same command:
```
connect EACCES <pipe_file_Path>
```
And the terminal also shows the same output in terminal.

**Comment by gcampbell-msft** [comment]
Ah, maybe it's a permissions issue, if you're having to run `sudo` to get it to run correctly. Is there a reason why you need to use `sudo`?

**Comment by JackBoosY** [comment]
> Ah, maybe it's a permissions issue, if you're having to run `sudo` to get it to run correctly. Is there a reason why you need to use `sudo`?

Yes it seems like a permission issue. Maybe my account has some limits, I need use `sudo` to run install command.

**Comment by JackBoosY** [comment]
Ping @gcampbell-msft 
Also, I still need to know the related doc link.

**Comment by gcampbell-msft** [comment]
@JackBoosY Ah, in this case, the issue isn't with our extension, it's something with the permissions. However, does it work if you add `sudo` to the command-line in the tasks.json file?

**Comment by JackBoosY** [comment]
> @JackBoosY Ah, in this case, the issue isn't with our extension, it's something with the permissions. However, does it work if you add `sudo` to the command-line in the tasks.json file?

Unfortunately it doesn't work now:
<img width="701" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/47264268/e6725749-6c59-4a26-9c50-45942a0ccd0e">

**Comment by JackBoosY** [comment]
@gcampbell-msft Any feedback?

**Comment by gcampbell-msft** [comment]
@JackBoosY Thanks for the ping. Unfortunately, looking through the issue again to remind myself and what was going on. It seems like this is likely a permissions issue on your machine. 

Is there a way that you can configure your machine to be able to run the command without `sudo`? I believe that if you have to run it with sudo, the CMake Tools debug sessions won't be able to access the pipe, because VS Code isn't, by default, run with `sudo`. 

You could possibly attempt to open VS Code with `sudo`, and then run the steps again, and then maybe since everything is now at `sudo` level, it will run successfully?

**Comment by JackBoosY** [comment]
> @JackBoosY Thanks for the ping. Unfortunately, looking through the issue again to remind myself and what was going on. It seems like this is likely a permissions issue on your machine.
> 
> Is there a way that you can configure your machine to be able to run the command without `sudo`? I believe that if you have to run it with sudo, the CMake Tools debug sessions won't be able to access the pipe, because VS Code isn't, by default, run with `sudo`.
> 
> You could possibly attempt to open VS Code with `sudo`, and then run the steps again, and then maybe since everything is now at `sudo` level, it will run successfully?

Will try that later.

**Comment by JackBoosY** [comment]
I believe this is a permission issue. Close now.
