### ISSUE TITLE
Can't running cmake command, command "cmake.xxxxx" not found

### ISSUE THREAD

**Issue by bidjc** [microsoft/vscode-cmake-tools#3479]
### Brief Issue Summary

After connect to WSL,the cmake command cannot running.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/52255dfb-d53f-4125-8df3-c8916f24cb85)
CMake Tools seem not active(尚未激活)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/88dc5e43-85a9-4c09-aa3b-ff68b31d64f8)

### CMake Tools Diagnostics

```shell
CMake: Log Diagnostics can not running.
```

**Comment by gcampbell-msft** [comment]
@bidjc Could you paste a screenshot of what is populated when you type "CMake" into the command palette? Is it evident that the CMake extension activated? 

There shouldn't be any reason why the CMake Tools extension wouldn't work in WSL, so any logs or screenshots or context would be very helpful to help us investigate.

**Comment by bidjc** [comment]
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/9d521064-2e76-44f2-a633-a0e52f0f48dd)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/31f3c3ac-272f-41cd-b9e3-958d90e7ec28)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/35c79605-a84b-4565-bb07-23d78fe0180c)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/f219cc32-6964-46c9-a219-bed6000d893b)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/0bfd629e-1628-4bf3-8eef-66c51fe3ac58)

**Comment by bidjc** [comment]
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/1d945890-29a4-47da-b89d-ace403b0372d)

**Comment by bidjc** [comment]
@gcampbell-msft  sorry for later responsed,I have make screenshot,if need more info,please @to me.
Thanks

**Comment by bidjc** [comment]
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/fdc0afdc-a7ef-4432-8ad2-4a14df14a113)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/aef69bbf-8843-49c7-a52b-18e62de8c8a9)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/a2015a10-1bef-4591-858b-99a319d42ea9)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/52dc25a5-2a7c-4676-847c-e211e8cfb561)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/17551706/71e76896-f5d3-42da-a0de-378e640d93b0)

**Comment by bidjc** [comment]
when I change vscode display language to English, cmake tools was work well.
And cmake tools can not work after switch display language to Chinese.

**Comment by bidjc** [comment]
Today,I install Chinese (Simplified) (简体中文) Language Pack for Visual Studio Code v1.84 to WSL,and change language to Chinese,cmake tools work well.
It's seem need install Chinese language between local and WSL,then cmake tools can work well in Chineses.
