### ISSUE TITLE
there is no way to set up a find_package _DIR 

### ISSUE THREAD

**Issue by Raffaello** [microsoft/vscode-cmake-tools#3487]
### Brief Issue Summary

if using a dependency there is no way to set where to find the directory.

At the same time I didn't find any documentation to basically configure a cmake project in vscode that has a fidn_package required c

**Comment by gcampbell-msft** [comment]
@Raffaello Thanks for letting us know of this issue. Could you explain in some more detail what is going wrong? One thing that could be helpful is providing a repro project that can help us fully understand what it is that isn't working for you.

Thanks! Looking forward to learning more about your scenario.

**Comment by Raffaello** [comment]
for e.g:

I don't think there is a straight forward example, how to set up a `CMake project with VSCode using "X" lib`
basically what is missing in the first getting started is a snippet of code more or less like this: 
`.vscode/settings.json`
```json
{
  "cmake.enviroment" = {
    "X_DIR" : "./libs/Xlib-1.0.0.0"
  }
}
```
when CMake can't find the X lib by itself.


(i think in the getting started is using zlib maybe or something, but anyway just to get the idea)

**Comment by Raffaello** [comment]
for e.g. having a reference here: https://code.visualstudio.com/docs/cpp/cmake-linux
using a "X" lib and setting up properly with a simple .vscode/settings.json would be quicker to getting started.
