### ISSUE TITLE
CMakeTools extension was unable to initialize: Error: spawn cmake ENOENT [See output window for more details]

### ISSUE THREAD

**Issue by ImKifu** [microsoft/vscode-cmake-tools#350]
somebody help me pls :<
i get trouble with VS Code 
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:30.761Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

and i follow this : 
https://www.codeproject.com/Articles/1184735/Quick-Start-to-Use-Visual-Studio-Code-for-Cplusplu

but at step : 
" Choose CMake:Configure for the first time. A new list bumps up; the list has all available configurations. "

i have error message : 
CMakeTools extension was unable to initialize: Error: spawn cmake ENOENT [See output window for more details]

i use kubuntu 17.10
KDE plasma ver 5.10.5
cmake 0.0.17
cmaketools 0.10.4

im newbie pls guide me slowly :>

**Comment by Randshot** [comment]
@ImKifu I recommend using the beta4 release (look at issue #274). In that issue, there also is a link to an incomplete documentation page.

**Comment by vector-of-bool** [comment]
It's likely that you don't have `cmake` on your `$PATH`. Have you installed CMake?

**Comment by ImKifu** [comment]
i use commend "ext install twxs.cmake"
i have installed it

![screenshot_20180320_132023](https://user-images.githubusercontent.com/37338905/37638860-86399b5c-2c41-11e8-88e7-a9260fa46049.png)

**Comment by Randshot** [comment]
@ImKifu He is talking about [CMake](https://cmake.org/), and not the VSCode extension "CMake".

**Comment by ImKifu** [comment]
tks @Randshot and @vector-of-bool 
i have install Cmake.
i use Code Block with GNU GCC compiler.

and now i dont know how to add GNU GCC compiler in VS Code
![screenshot_20180320_232301](https://user-images.githubusercontent.com/37338905/37668203-7fdb7b72-2c96-11e8-9664-fce3b3ad980b.png)

**Comment by Randshot** [comment]
@ImKifu It seems like your `CMakeLists.txt` file is wrong. This is not an issue with this extension, but rather with your `CMakeLists.txt` file.

**Comment by ImKifu** [comment]
[CMakeLists.txt](https://github.com/vector-of-bool/vscode-cmake-tools/files/1830252/CMakeLists.txt)

but i have not touch CmakeLists.txt :<
how can it is wrong  TT

**Comment by vector-of-bool** [comment]
What output do you see from running `cmake --version` on the command line?

**Comment by ImKifu** [comment]
@vector-of-bool 
here you are:
cmake version 3.11.0-rc4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
![screenshot_20180321_112737](https://user-images.githubusercontent.com/37338905/37694562-eba7f196-2cfa-11e8-91cf-16faa492d806.png)

**Comment by vector-of-bool** [comment]
Have you worked with CMake before? Is the CMakeLists.txt you attached the one you are using in your project?

**Comment by ImKifu** [comment]
no i have not worked with Cmake. i dont know how to check the CMakeLists.txt attached in my project or not.

**Comment by vector-of-bool** [comment]
CMake Tools contains a `CMake: Quickstart` command that you can run to generate a bare-minimum working CMake project. You can take the CMakeLists.txt it generates and adapt it to fit your needs.

If you have knowledge of build systems outside of CMake, you'll want to watch [this video](https://www.youtube.com/watch?v=bsXLMQ6WgIk), which is a good introduction to using CMake for someone who understands a lot about building software already.

If you're just getting started with CMake and C++, don't worry about learning all of CMake yet: A bare minimum will get you started nicely.

**Comment by RPG3D** [comment]
Same issue in windows， v 0.10.4

**Comment by vector-of-bool** [comment]
@RPG3D, do you have CMake on your `$PATH`? If not, you're seeing #296, which will have a fix in the beta5 soon

**Comment by ImKifu** [comment]
![screenshot_20180327_154247](https://user-images.githubusercontent.com/37338905/37956980-fc04bc78-31d6-11e8-9a32-7080e4ed83e1.png)
![screenshot_20180327_154330](https://user-images.githubusercontent.com/37338905/37956982-fd9bd6ca-31d6-11e8-8bac-bccf7e2ee1fa.png)

**Comment by ImKifu** [comment]
i don know how to run code with Cmake :< 
there was no button
first picture i click run code (Ctrl+Alt+N) to build code

**Comment by RPG3D** [comment]
@vector-of-bool , I added to system Path. I can run cmake in CMD

**Comment by vector-of-bool** [comment]
@ImKifu, CMake does not have a facility to simply run arbitrary code. Can I see the contents of your `CMakeLists.txt`? How did you do to create the `test` and `a.out` executables in your project directory?

**Comment by ImKifu** [comment]
tks @vector-of-bool . now i know VS code is text editor and Cmake is not an IDE
cmake is package software.
I just want to run my code from VSCode like codeblocks. 
Sorry i am newbie and i have a litter confusion about Cmake. tks for spending time for me.
can you recommend me some thing to help me to build and run my code in VScode

**Comment by vector-of-bool** [comment]
Based on your screenshot, this should be a good starting `CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.7.2)
project(SomeProject)

add_executable(all-equal "week3_All Equal.cpp")
```

Then you can configure and build. I'd recommend not using spaces in your code filenames: That can cause a lot of confusion.

After building, you will have an executable named `all-equal` in the `build/` folder that you can execute from the command line.

You can also launch a target using `Shift+F5`, and CMake Tools will start the program in the terminal, or `Ctrl+F5` and CMake Tools will start the program in a debugger. [Read more on debugging here](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/target_debugging.md).

**Comment by vector-of-bool** [comment]
@ImKifu, have you made any progress?

**Comment by kernelkin** [comment]
The same "Error: spawn cmake ENOENT" is shown to me. I've changed "terminal.integrated.shell.*" in settings. Does vscode-cmake-tools respect this setting and uses the integrated shell?

**Comment by Randshot** [comment]
@kernelkin You have to either add CMake to your PATH, or provide the path to the cmake executable via `cmake.cmakePath`.

**Comment by kernelkin** [comment]
I am using an MSYS2 installation with cmake version 3.10.2 and cmake-tools version 0.10.4. Setting the path to cmake.exe is working if the build directory is filled by a manual cmake run, cmake-tools doesn't find the build program for "Unix Makefiles" and doesn't even search for MSYS2 Makefiles. So at least one step further but not finished.

I'll try to make cmake.exe available in path (which is not quite clear in an msys environment) and I'll try to install cmake-tools 0.11.0-beta5. I'll report the results here.

**Comment by kernelkin** [comment]
First change on the previous named setup:
```json
	"settings": {
		"terminal.integrated.shell.windows": "D:/msys64/usr/bin/bash.exe",
		"terminal.integrated.shellArgs.windows": [
			"-i"
		],
		"terminal.integrated.env.windows": {
			"PATH": "/mingw64/bin;/usr/local/bin;/usr/bin;/bin;D:/msys64/bin/;D:/msys64/usr/local/bin;D:/msys64/usr/bin;D:/msys64/bin;D:/msys64/mingw64/bin/;%PATH%"
		}
	}
```
- [x] cmake-tools using cmake working
- [ ] `MSYS Makefiles` generator *not* found
- [ ] `Mingw Makefiles` generator *not* found
- [ ] `Unix Makefiles` generator *not* found

Next step for me is the installation of cmake-tools 0.11.0-beta5.

**Comment by kernelkin** [comment]
Okay, cmake-tools 0.11.0-beta5 installed. By the way: I like it, keep up the good work ;) 
But sadly the detected kits in `cmake-kits.json` are my Windows installed clang and Visual Studio installations, nothing about MSYS or the MSYS MinGW part found. Any hints someone?

**Comment by kernelkin** [comment]
Again one step further: I added the path to the MSYS MinGW installation (in my case `D:/msys64/mingw64/bin`) to my system path variable and not only to the Visual Studio Code terminal path as shown above. Now the MSYS MinGW installation is found, Visual Studio Code shows the output `[cms-client] None of preferred generators available on the system.`
`[rollbar] Unhandled exception: Unhandled Promise rejection: Changing build variant Error: Unable to determine CMake Generator to use {}`
`[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant Error: Unable to determine CMake Generator to use {}`

I will now try to set one of the generators `MSYS Makefiles`, `MinGW Makefiles` or `Unix Makefiles` manually.

**Comment by kernelkin** [comment]
Okay, we are close to the destination: setting `"cmake.generator": "MinGW Makefiles"` is working.

**Comment by kernelkin** [comment]
Thanks for this.

Adding `D:\\msys64\\mingw64\\bin` to the windows path, the following to `cmake-kits.json` and using the `MinGW Makefiles` generator works for me 👍 
```json
  {
    "name": "GCC 7.3.0",
    "compilers": {
      "CXX": "D:\\msys64\\mingw64\\bin\\g++.exe",
      "C": "D:\\msys64\\mingw64\\bin\\gcc.exe"
    }
  }
```

**Comment by ReDucTor** [comment]
For anyone else looking at this error, I had a similar issue when trying to build a project which has a file named 'BUILD' in the root directory so it conflicted with the CMake Tools default build folder (changing the option in the workspace settings fixed it)

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
