### ISSUE TITLE
The first build and run (Ctrl+F5) always starts in Debug mode disregarding Release settings.

### ISSUE THREAD

**Issue by pauljurczak** [microsoft/vscode-cmake-tools#3507]
![Screenshot from 2023-12-19 23-14-56](https://github.com/microsoft/vscode-cpptools/assets/4933032/eb1ddc7f-604e-42dc-914e-d5aae361613b)

Type: <b>Bug</b>

Fresh install of VS Code on Ubuntu 22.04.3. Added only C/C++ Extension Pack. Installed CMake and dependencies. Followed your getting started tutorial at https://code.visualstudio.com/docs/cpp/CMake-linux. Set CMake: Select Variant to Release. CMakeLists.txt also contains `set(CMAKE_BUILD_TYPE "Release")`. The first build and run (Ctrl+F5) always starts in Debug mode. The second and the following ones are correctly in Release mode.

Extension version: 1.3.0
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.2.0-39-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) N100 (4 x 2917)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|11.41GB (6.60GB free)|
|Process Argv|--unity-launch --crash-reporter-id aef934d6-fd74-440a-a24f-e74f7a8cfae5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by bobbrow** [comment]
@gcampbell-msft @sinemakinci1 this looks like an issue with CMake Tools, and maybe with the Getting Started documentation.  Can you please take a look?

**Comment by pauljurczak** [comment]
I've been using VSCode with these extensions for several years and this bug was always there.

**Comment by snehara99** [comment]
Hi @pauljurczak Ctrl+F5 is actually meant to run in debug mode according to [these docs](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md#debugging-without-a-launchjson). The docs say this:

> Start a debugging session on the active target by running the CMake: Debug command from the VS Code command palette, by selecting the Debug button in the status bar or CMake Tools sidebar Project Status View, or by pressing the keyboard shortcut (the default is Ctrl+F5).

You should be able to run without debugging by using Shift+F5 according to [these docs](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md#run-without-debugging). The docs say this:

> You can run a target without debugging it, by running the CMake: Run Without Debugging from VS Code's command palette, by selecting the play button in the status bar or the play button to the left of the Launch node, or by pressing the keyboard shortcut (the default Shift+F5).

I looked through the Getting Started documentation and didn't see where it says to use Ctrl+F5. Could you point me more specifically to where you saw that? Thanks!

**Comment by pauljurczak** [comment]
The UI suggests `Ctrl+F5` for `Run without debugging`, see:

![Screenshot from 2024-01-02 15-22-41](https://github.com/microsoft/vscode-cmake-tools/assets/4933032/179438af-a2eb-45a6-b317-0b511b3f2c50)

**Comment by snehara99** [comment]
@pauljurczak thank you for the screenshot. We'll look more into it as soon as we have the capacity.  Can you confirm if Shift + F5 works for you?

**Comment by pauljurczak** [comment]
Yes, `Shift+F5` works.

**Comment by gcampbell-msft** [comment]
@andreeis I think this might could be fixed by modifying the keybindings in the package.json.

**Comment by v-frankwang** [comment]
We verified the issue on CMake tools: v1.19.45 and it has been fixed.

ENV：
CMake Tools:v1.19.45
vscode: 1.92.2

Actual result:
![image](https://github.com/user-attachments/assets/d7795065-b5f6-44bb-b8a3-21e339c0069c)
