### ISSUE TITLE
[warning] [cmake-tools]: Cannot find key cmake-tools.configuration.cmake.options.advanced.statusBarVisibility.variant.description , And git have been waiting.

### ISSUE THREAD

**Issue by cyrus123456** [microsoft/vscode-cmake-tools#3511]
### Brief Issue Summary

![image](https://github.com/microsoft/vscode-cmake-tools/assets/73327722/92a271fb-1628-4e74-bd74-873f5789a57a)

### Additional Information

![image](https://github.com/microsoft/vscode-cmake-tools/assets/73327722/14b1f8bb-035d-4185-8663-4ee65a20a5a6)

**Comment by cyrus123456** [comment]
Just open the project in a new window, don't use the old workspace file.

**Comment by snehara99** [comment]
@cyrus123456 it should be fixed now in the newest pre-release channel update, if you could install it and confirm, thanks!
