### ISSUE TITLE
"Delete Cache and Reconfigure" not working properly

### ISSUE THREAD

**Issue by 424778940z** [microsoft/vscode-cmake-tools#3515]
### Brief Issue Summary

My use case is a bit odd, I'm swaping between few computers for work, and my project folder is synced by usb drive or network drive.

That means the abs path won't be same between computers. So when I try to build after move computer, cmake will complain some config issues caused by path chage, understandable.

However, when I select `CMake: Delete Cache and Reconfigure`, the cache is not fully cleared, cmake is still complaining something in CMakeCache.txt isn't right, unless I manually remove the build folder entirely.

Make things worse, sometime it seems vscode/cmake is holding build folder open so I cannot remove it within vscode, I have to close everything then remove the folder and open everything again.

Could we have an option to force remove build folder or make the ext clear cache properly?

**Comment by snehara99** [comment]
Hi @424778940z, could you please provide us with a sample project that reproduces your issue? It would be much easier to investigate with it, thanks!

**Comment by 424778940z** [comment]
>Hi @424778940z, could you please provide us with a sample project that reproduces your issue? It would be much easier to investigate with it, thanks!

**Comment by snehara99** [comment]
@424778940z Thank you for the detailed repro steps. We'll investigate the issue as soon as we have enough capacity.

**Comment by qarni** [comment]
@424778940z Two members from our team attempted the repro and it didn't reproduce. If there is any other information you could provide that might help us reproduce, that would be great, otherwise, we will close the issue.

**Comment by gcampbell-msft** [comment]
@424778940z Could you confirm whether this is still reproducing? Specifically on the most recent pre-release CMake Tools version? Thank you!

**Comment by 424778940z** [comment]
![image](https://github.com/microsoft/vscode-cmake-tools/assets/2379529/a43d9a64-386a-4474-999c-57e996721607)
Here is an example, which is my tiny C playground for some quick testing, which the cmakelist.txt only few lines, and a single source code
It was built at `C:/_projects/_playgrounds/c_std_pg`, then I copy the whole c_std_pg folder to `d:/c_std_pg`, then cmake will complain about the location change, which is fine, but the "Clean" or "Clean and rebuild" from Cmaketools won't work because cmake refuse to work due to location change
the only way to get it work, is to manually nuke the build cache folder, in this case, is the `.build`

**Comment by 424778940z** [comment]
Confirmed it is working under linux. We could close the issue now

**Comment by 424778940z** [comment]
unfortunately, I have to open this issue again, it seems the `CMake: Delete Cache and Reconfigure` is only removing following two files, but in some cases, this is NOT enough, as there are many things in the build folder.
I can't give you the whole project to repurduce the issue, but could you just give an option to let `CMake: Delete Cache and Reconfigure` nuke the whole build folder instead of removing those two files?

```
[driver] Removing /home/user/Desktop/firmware/.build/CMakeCache.txt
[driver] Removing /home/user/Desktop/firmware/.build/CMakeFiles
```

**Comment by v-ericawu** [comment]
@424778940z @gcampbell-msft Thanks for your feedback, we can reproduce the problem using the following environment and steps and we will continue to follow the issue:

**ENV:**
- OS: Win10 22H2
- VS Code version: 1.88.1
- CMake Tools extension: 1.18.31(pre-release)

**Repro Steps:**
1. Download and unzip [Test](https://microsoft-my.sharepoint.com/:u:/p/v-ericawu/ES_K4hgM_lxIgWEZoXygbeABn94_IKyBM-sCpYEcb_EUgw?e=SWo4CJ) project.
2. Open Test project with VS Code.
3. Press F1 and run command 'CMake: Delete Cache and Reconfigure'.

**Expected Result**: Provide an option to delete the entire **build** folder, not just the two files.

**Actual Result**: Only **CMakeCache.txt/CMakeFiles** have been removed.
**Before running the 'CMake: Delete Cache and Reconfigure' command:**
![image](https://github.com/microsoft/vscode-cmake-tools/assets/78774400/8cced6df-3a68-46ad-928f-e0331e4fd56b)

**After running the 'CMake: Delete Cache and Reconfigure' command:**
[driver] Removing c:/Users/v-ericawu/Desktop/Test/build/CMakeCache.txt
[driver] Removing c:\Users\v-ericawu\Desktop\Test\build\CMakeFiles
![image](https://github.com/microsoft/vscode-cmake-tools/assets/78774400/0369fa6a-a952-48a2-9e54-742a6eb2b93c)

**Comment by Ashley-Li** [comment]
Verified on CMake Tools v1.18.43(pre-release), this issue still repro: only CMakeCache.txt/CMakeFiles have been removed.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/56664234/f5e49cc0-fc36-4865-b6d1-48618b0be406)

**Comment by gcampbell-msft** [comment]
@Ashley-Li Did you turn on the setting that was added?

**Comment by Ashley-Li** [comment]
@gcampbell-msft Thank you for your guidance. After setting cmake.deleteBuildDirOnCleanConfigure is true, this issue has fixed. Now deleted the entire build folder, not just the two files.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/56664234/4b78243e-1711-4310-93d5-a4d1d0d87967)

**Comment by 424778940z** [comment]
could we have a checkbox for this option in settings menu?

**Comment by Ashley-Li** [comment]
> could we have a checkbox for this option in settings menu?

Hi @424778940z Please press "Ctrl+,"  to open setting page, then search keywords and find "Cmake:Delete Build Dir On Clean Configure" and switch to Workspace, then select the checkbox to enable. Please see below:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/56664234/81d07e7f-775e-4d2f-8a20-f2c55f06d1ea)

**Comment by starball5** [comment]
I wonder if this could have been worked around by using the CMake Tools command to do a clean rebuild?

**Comment by 424778940z** [comment]
no cmake only cleans what built directly by it, any by product won't be deleted by clean unless you specifically config it to
