### ISSUE TITLE
0.11.0-beta4: `Edit Cmake Cache` command doesn't work

### ISSUE THREAD

**Issue by isushik94** [microsoft/vscode-cmake-tools#353]
There is a bug related with `Edit Cmake Cache` command. The command doesn't work. It prints: "There are no cache entries to show. Have you configured the project?". But I can build the project, run `Configure` command and etc. A `build` folder also exists.

**Comment by vector-of-bool** [comment]
This won't be any better in beta5, and I'm inclined to leave this for a while. VSCode is preparing a new WebView API that will make the implementation of this cache editor markedly simpler and less error-prone. The current architecture of the cache editor is quite painful.

**Comment by bobbrow** [comment]
This should be addressed in 1.2.0.  See issue #676 for a workaround in 1.1.3.
