### ISSUE TITLE
This may be caused by the extension triggering the 'cmake.projectStatus.selectConfigurePreset' command

### ISSUE THREAD

**Issue by BinaryRyan** [microsoft/vscode-cmake-tools#3544]
### Brief Issue Summary

When attempting to configure a CMake project and choose a preset,an error occurs with the message "Cannot configure: No configuration preset is active for this CMake project. This may be caused by the extension triggering the 'cmake.projectStatus.selectConfigurePreset' command."

### CMake Tools Diagnostics

```shell
{
  "os": "darwin",
  "vscodeVersion": "1.85.2",
  "cmtVersion": "1.16.32",
  "configurations": [
    {
      "folder": "/Users/ryan/Desktop/development/cpp/sectran",
      "cmakeVersion": "3.23.1",
      "configured": false,
      "generator": "",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### cmake version
cmake version 3.23.1

### here is my configure
```json
{
    "version": 3,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 23,
        "patch": 1
    },
    "configurePresets": [
        {
            "name": "macos-base",
            "hidden": false,
            "displayName": "macos base",
            "generator": "Unix Makefiles",
            "binaryDir": "${sourceDir}/cmake-build-${presetName}",
            "cacheVariables": {
                "CMAKE_C_COMPILER": "gcc",
                "CMAKE_CXX_COMPILER": "g++",
                "CMAKE_EXPORT_COMPILE_COMMANDS": "ON"
            },
            "condition": {
                "type": "equals",
                "lhs": "${hostSystemName}",
                "rhs": "macos"
            }
        },
    ]
}
```

```log
Running the command 'cmake.projectStatus.selectConfigurePreset' error: Cannot configure: No configuration preset is active for this CMake project. This may be caused by the extension triggering the 'cmake.projectStatus.selectConfigurePreset' command.
```

**Comment by gcampbell-msft** [comment]
@BinaryRyan Could you run the "CMake: Reset CMake Tools Extension State" (NOTE: It will reset your CMake Tools extension state, so you might want to save your settings somewhere so you can restore them at some point if needed), this will restore everything to get to a base state to help us understand what might be going on. 

Thanks! Also, if you could try to configure with this on the command-line as well, we could narrow down that this isn't an issue with the preset itself. Thanks!

**Comment by BinaryRyan** [comment]
I tried to reset the cmake tool but an error window popped up:"The command "CMake: Reset CMake Tools Extension Status (for troubleshooting)" caused an error,Unable to configure: No configuration presets have been activated for this CMake project"
