### ISSUE TITLE
"CMake: Select A Kit" Is missing in visual studio code

### ISSUE THREAD

**Issue by DanelOfficial** [microsoft/vscode-cmake-tools#3552]
### Brief Issue Summary

i wanted to type CMake: Select A Kit but its missing

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.85.2",
  "cmtVersion": "1.16.32",
  "configurations": [],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": []
}
```

### Additional Information

![bandicam 2024-01-29 19-22-47-503](https://github.com/microsoft/vscode-cmake-tools/assets/81319129/f04d5501-bb1d-416c-b20e-5f4c755baab8)

**Comment by gcampbell-msft** [comment]
@DanelOfficial I don't recognize those two commands "Select CMake Configuration" or "Select CMake Project". 

Do you have a CMakeLists.txt in your folder? One thing you could try is to reset the CMake Tools extension `CMake: Reset CMake Tools Extension State`, though it may reset some of your settings. 

Could you share a zip of your project so that I can see what might be going on?

**Comment by gcampbell-msft** [comment]
I assume one of those is in your workspace root folder? 

Did you attempt to reset the cmake tools extension state?

**Comment by gcampbell-msft** [comment]
What is the value of `cmake.useCMakePresets` in your settings? If it's set to always, that command won't appear. If you aren't using CMakePresets.json, then you could possibly set this to `never` and you should see this command appear.

**Comment by DanelOfficial** [comment]
> What is the value of `cmake.useCMakePresets` in your settings? If it's set to always, that command won't appear. If you aren't using CMakePresets.json, then you could possibly set this to `never` and you should see this command appear.

Its `never`

**Comment by gcampbell-msft** [comment]
@DanelOfficial Interesting, this is definitely an odd bug. 

If you could create a minimal repro that we could investigate with, as well as attempt the repro with the `cmake.loggingLevel` set to `debug`, and then send us the log, that would be most helpful.

**Comment by Septanesium** [comment]
is there any more documentation on this so called bug? i found this post and only this post and that's it, virtually zero other mention

**Comment by gcampbell-msft** [comment]
@Septanesium Are you using CMake Kits or CMake Presets?

**Comment by gcampbell-msft** [comment]
@septanesium Does this issue still work in the most recent CMake Tools extension version?

**Comment by gcampbell-msft** [comment]
@septanesium Please let us know if these issues still repro, for now, I'm going to close this issue because those commands no longer exist in the product.

**Comment by E1iko** [comment]
had to setup minGW in enviroment variables -> path . then before select kit,  scan kit in vs code
