### ISSUE TITLE
environmentSetupScript exit code not checked

### ISSUE THREAD

**Issue by joelfrederico** [microsoft/vscode-cmake-tools#3566]
### Brief Issue Summary

I had an environmentSetupScript that worked. It started failing when IT removed a feature from the machine I needed. But since VSCode doesn't check the script's exit code, I never had a chance to notice that it was failing.

### Additional Information

The result of the script is here: https://github.com/microsoft/vscode-cmake-tools/blob/424005921358095a7a262274e00951af05924707/src/kit.ts#L693

As far as I can tell, its exit code is never checked. If it was checked, and an error raised, I could have noticed that my script wasn't working properly.

**Comment by gcampbell-msft** [comment]
@joelfrederico Thanks for the call-out we should make a failure here more obvious. Adding it to the backlog.
