### ISSUE TITLE
CMake doesn't show up in status bar

### ISSUE THREAD

**Issue by junekhan** [microsoft/vscode-cmake-tools#3568]
### Brief Issue Summary

<img width="937" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/3932094/9cd3304b-0eb9-459d-99a4-05cb7de7d05d">

Even though `Status Bar Visibility` is set to `visible`, I cannot see the button on my status bar. Note that, `CMake` is not even an option on the right-click menu of the status bar.

**Comment by junekhan** [comment]
@gcampbell-msft I'm sure all of the three extensions are activated. Lemme know if you need more information from my end.
<img width="422" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/3932094/1af92fae-cc15-4322-ab7a-9189bb617cd8">

**Comment by gcampbell-msft** [comment]
@junekhan That view doesn't guarantee that the extensions have been activated, only that they have been installed. Could you try running "CMake: Configure" and then letting me know what you see? 

Also, if you could send the output of "CMake: Log Diagnostics", that would be very helpful. Thanks

**Comment by junekhan** [comment]
Hi @gcampbell-msft , after running `CMake: Configure`, everything now works like charm. Thanks very much!
It was a bit weird at the beginning, tho. It voluntarily configures CMake in my other projects, showing that pop-up for choosing a compiler. However, it was not the case in this project, no matter how many times I restarted VS Code. Thanks for letting me know about this manual trick.

**Comment by junekhan** [comment]
@gcampbell-msft I still feel it's counter intuitive to see nothing on the UI side when the CMake extension is installed while not being configured yet. Other extensions from the market usually reveal something noticeable once installed, and it makes more sense to me.
Also, I recommend to retrigger the auto configuration each time users reopen projects if the configuration is incomplete.

**Comment by gcampbell-msft** [comment]
@junekhan This confusion is likely caused by our conversion to using primarily the Project Status view. Since this specific issue is fixed, but there is still very valid feedback, I'd ask that you give your thoughts and feedback here: #3423, since that's the main issue where we are tracking feedback for this change .Thanks!
