### ISSUE TITLE
Changing cmake path to an invalid location force user to restart VS Code to proceed

### ISSUE THREAD

**Issue by vinodappu** [microsoft/vscode-cmake-tools#3570]
### Brief Issue Summary

I've changed cmake.path to a non existing location & saved the changes. I can see Bad cmake executable error coming, which is obvious. 

Now I changed the cmake executable to existing one, still it's not working, giving bad cmake executable error, I had to restart VS Code to get rid of this issue.

![image](https://github.com/microsoft/vscode-cmake-tools/assets/65697683/fff40b19-4bdf-42a4-b3ef-358582208c36)

![image](https://github.com/microsoft/vscode-cmake-tools/assets/65697683/2f95e84a-1208-4c83-8c63-83beb7c4538e)

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.86.0",
  "cmtVersion": "1.16.32",
  "configurations": [
    {
      "folder": "c:\\Users\\test",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 3,
    "executablesCount": 1,
    "librariesCount": 1,
    "targets": [
      {
        "name": "test.elf",
        "type": "EXECUTABLE"
      },
      {
        "name": "create-objdump",
        "type": "UTILITY"
      },
      {
        "name": "test",
        "type": "STATIC_LIBRARY"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by gcampbell-msft** [comment]
@vinodappu Thanks for letting us know. We'll mark this as a bug and place it on our backlog of bugs to fix.

**Comment by oursland** [comment]
Related is when CMake is installed after launching VS Code.  An example that I frequently encounter is when using a `conda`-based project in which the `conda` package manager is responsible for installing `cmake`.

Prior to installation of the `conda`-managed packages, VS Code tests for the `cmake` executable and fails.  After this failure it never tests the executable again, even though the package may have been installed.

A preferable behavior would be to always attempt to run the `cmake` executable and reporting the error if it cannot be run, instead of testing once at startup.

**Comment by Yingzi1234** [comment]
@vinodappu @gcampbell-msft We can reproduce this issue on latest version, you can get the details below.

**Repro steps:**
1. Open a folder
2. Open settings UI and set the Cmake: Cmake Path to a non existing location, e.g., 'cmake1'
3. Click F1 to run 'CMake: configure'
4. Reset the Cmake: Cmake Path to original location, e.g., 'cmake'
5. Click F1 to run “CMake: configure” and check if the configuration is successful

**Expected result:**
It should be configured successfully

**Actual result:**
The configuration did not succeed. And displays the error: “Bad CMake executable ‘cmake1’.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/101234795/48dc90e5-0238-4661-bde5-8a4e1a16a5e6)

**Comment by oursland** [comment]
@gcampbell-msft is there a PR that closed this issue?

**Comment by gcampbell-msft** [comment]
This commit: https://github.com/microsoft/vscode-cmake-tools/commit/6eb0121930d4b2222bb0538d94580e8e40861f69

**Comment by oursland** [comment]
This addresses the situation in which changing a cmake path occurs, but does not address the situation in which a previously invalid path is made valid.  I'll file a new issue for this.
