### ISSUE TITLE
Update docs to use "scan for compilers" instead of "kits"

### ISSUE THREAD

**Issue by dc6c** [microsoft/vscode-cmake-tools#3574]
### Brief Issue Summary

The [documentation page](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md#scan-for-kits) directs the user to run "Scan for Kits" from the command palette, but the actual command (in the current release of VSCode, v1.86.0, at least) is  "Scan for Compilers".

For better consistency, when the rest of the text talks about scanning for kits, it could say "scan for _compiler_ kits", so there is connection between the documentation and the command.

**Comment by gcampbell-msft** [comment]
Likely we should merge this with #3624

**Comment by gcampbell-msft** [comment]
@dc6c Could you confirm whether this is happening when you're using Presets or Kits? 

I want to confirm because while we likely should still update the docs, I think there are two different names for the commands depending on which workflow you are using. Thanks.
