### ISSUE TITLE
Need to select debug target every time I switch configurations

### ISSUE THREAD

**Issue by guusw** [microsoft/vscode-cmake-tools#3583]
### Brief Issue Summary

Using a launch configuration with `"program": "${command:cmake.launchTargetPath}",`
Switching the configuration parameters, the debug target needs to be changed every time, even thought the project status still has the correct target selected.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.86.1",
  "cmtVersion": "1.16.32",
  "configurations": [
    {
      "folder": "a:\\Projects\\shards",
      "cmakeVersion": "3.26.4",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "C:/Program Files/LLVM/bin/clang.exe",
        "CXX": "C:/Program Files/LLVM/bin/clang++.exe"
      }
    },
    {
      "folder": "a:\\Projects\\fbl",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "a:\\Projects\\formabble-docs",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "c:\\Users\\Fragcolor2\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\egui-0.25.0",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Additional Information

I'm using a cmake-variants file.
I'm using the project status window to switch the configuration parameter:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/16842774/ef55cc20-8644-432e-b232-1d340395d048)
After this, pressing launch will just output:
```
[main] =======================================================
[main] No executable target was found to launch. Please check:
[main]  - Have you called add_executable() in your CMake project?
[main]  - Have you executed a successful CMake configure?
[main] No program will be executed
```

Trying to change the target by pressing the button next to the debug target name does nothing until I manually run configure
![image](https://github.com/microsoft/vscode-cmake-tools/assets/16842774/153789d4-d23e-41a1-8bde-81a1965f9b99)

After this I can successfully launch, although I don't want to go through this process every time, the target name stays the same I'm just changing the configuration

It might be worth noting that I have my cmake set to generate into different folders based on the configuration, along with the following settings:
```json
{
"cmake.buildDirectory": "${workspaceFolder}/build/${buildKit}/${variant:buildType}",
"cmake.configureOnEdit": false,
"cmake.configureOnOpen": false,
"cmake.automaticReconfigure": false,
}
```

**Comment by guusw** [comment]
Ok, it seems like turning on `cmake.automaticReconfigure` fixed it, although I feel like this should work without re-running configure, maybe it's harder to fix. feel free to close this.

**Comment by gcampbell-msft** [comment]
@guusw Thank you for letting us know the workaround! We'll make a note on our side, but since there is a workaround, we'll close this issue. Thanks.
