### ISSUE TITLE
Cmake extension does not prompt to select CmakeLists.txt file in 1.17

### ISSUE THREAD

**Issue by sinemakinci1** [microsoft/vscode-cmake-tools#3588]
### Brief Issue Summary

in 1.17, even when there is a CMakeLists.txt file, the Cmake Tools extension does not activate. An example repo I used can be found here: https://github.com/sinemakinci1/basic-cpp-copilot-example/tree/main/my-cmake-project
<img width="1201" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/99284450/d3228fc9-faf6-4f2b-ae1d-3508590127ee">

Since CMakeLists.txt file is embedded not at the top-level, it should prompt me to select a CMakeLists.txt file (this is part of the partial activation experience). Once I downgraded to 1.15, I saw the prompt, selected my CMakeList.txt file and kits, and now 1.16 and 1.17 versions of CMake Tools extension activate with the project.

**Comment by sinemakinci1** [comment]
The hypothesis is that this came from a community PR to disable selecting CMakeList.txt when it is not in your root. We need to bring back that dropdown to some degree

**Comment by YuriL180821** [comment]
@sinemakinci1 could you please provide any workaround to fix the problem locally on user's PC?

**Comment by sinemakinci1** [comment]
@YuriL180821 Can you try the following?

1. Set this setting in your settings.json
`“cmake.sourceDirectory” : “${workspaceFolder}/<insert path to where the CMakeLists.txt lives in this project>”.` 

Then, reload the window and see if VSC will prompt for youto configure? Once prompted, you should press Yes, and see an option to select a CMakeLists.txt file up top (if embedded in a subdirectory).

In general, if you have the CMake Tools extension installed, you should be able to find the CMake: Configure command in the command palette which will fire that option to select a CMakeLists.txt file if detected in a sub-directory.
