### ISSUE TITLE
"Run CTest" no longer works when there is no preset

### ISSUE THREAD

**Issue by ebouteillon** [microsoft/vscode-cmake-tools#3589]
### Brief Issue Summary

Since the upgrade of "CMake Tools" extension to version v1.17.15, when I click "Run CTest" in the status bar, I get the error "[ctest] test.preset.not.set Test preset is not set" and unit tests are not run.

*Additional notes:*

- CMake presets are not used in my environment (no "CMakePresets.json" file).
- When running a single unit test from Test Explorer, test is run successfully.
- Setting useCMakePresets from "auto" -> "never", does not fix the issue
- Downgrading "CMake Tools" extension to previous version v1.16.32, fixes the issue.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.86.1",
  "cmtVersion": "1.17.15",
  "configurations": [
    {
      "folder": "/home/axis/workspace/map-core",
      "cmakeVersion": "3.26.4",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "/opt/rh/devtoolset-12/root/usr/bin/gcc",
        "CXX": "/opt/rh/devtoolset-12/root/usr/bin/g++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 97,
    "executablesCount": 32,
    "librariesCount": 36,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
[main] Building folder: map-core 
[build] Starting build
[proc] Executing command: /opt/cmake/bin/cmake --build /home/axis/workspace/map-core/build --config Debug --target all -j 4 --
[build] [  1%] Built target axmapserializer_object

... snip....

[build] [100%] Built target tpv_gtestu
[driver] Build completed: 00:00:01.068
[build] Build finished with exit code 0
[ctest] test.preset.not.set Test preset is not set
```

**Comment by gcampbell-msft** [comment]
@ebouteillon Thanks for letting us know about this regression. Is there a way that you could share with us a minimal repro project so that we could quickly investigate this?

**Comment by gcampbell-msft** [comment]
@ebouteillon Update, I believe I found the issue, could you manually install this vsix and confirm that this fixes your issue? 
[cmake-tools.zip](https://github.com/microsoft/vscode-cmake-tools/files/14280994/cmake-tools.zip)

To install it, 
1) Download the zip, and rename it to change the extension to .vsix
2) Navigate to the extensions pane and install a manual vsix:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/86264750/0a3faf11-4182-49a5-86a8-69a2960378ce)

I believe this will fix your issue, and I have a PR out here: #3590

**Comment by ebouteillon** [comment]
Hi @gcampbell-msft , thanks for the quick response. I confirm it is working with the .vsix  provided.

**Comment by gcampbell-msft** [comment]
@ebouteillon Perfect, assuming the PR merges today, it will be in the pre-release starting tomorrow, and we plan to path an official release early next week. Thanks!
