### ISSUE TITLE
Build directory not determined correctly

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-cmake-tools#3594]
### Brief Issue Summary

Since today's update (v1.16.32 -> v1.17.15) the build dir is not determined correctly anymore.
The error is reproducible and is avoided by changing the version back to the old one.

It is clearly visible in the log:

```
[proc] Executing command: /usr/local/bin/cmake -DCMAKE_BUILD_TYPE=Debug  -S/workspaces/prj -B/workspaces/prj/Build/x86_64-linux-user-gcc-Release-Ninja -G Ninja
```

Debug != Release

cmake -preset xxx -N shows the correct path.

Problem is probably releated to our preset, it is awfully complicated... I cannot share it completely, so I will give you a reduced version . If needed I will provide a standalone example.

(configuration presets)
```
        {
            "name": "base",
            "hidden": true,
            "displayName": "Base Config",
            "description": "Everything else should inherit from here.",
            "generator": "Ninja",
            "binaryDir": "$env{BINARY_DIR}",
            "environment": {
                "BINARY_DIR": "${sourceDir}/Build/$env{TOOLCHAIN}-$env{BUILD_TYPE}-${generator}",
                "BUILD_TYPE": "Release"
            },
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "$env{BUILD_TYPE}"
            }
        },
        {
            "name": "switch-debug",
            "hidden": true,
            "description": "Settings for a debug build",
            "environment": {
                "BUILD_TYPE": "Debug"
            },
            "cacheVariables": {
                "CMAKE_BUILD_TYPE": "Debug"
            }
        },
        {
            "name": "x86_64-linux-user-gcc-Release",
            "description": "Release build for linux in platform_rts/devenv container.",
            "inherits": "base"
        },
        {
            "name": "x86_64-linux-user-gcc-Debug",
            "description": "Debug build for linux in platform_rts/devenv container.",
            "inherits": [
                "switch-debug",
                "x86_64-linux-user-gcc-Release"
            ]
        },

```

(I can not attach any further log right now. It might share to much private information. If you request the standalone example, then I can do this)

**Comment by gcampbell-msft** [comment]
@KUGA2 I have opened a PR for this here: #3595. I have tested and confirmed that this fix resolves this bug! Assuming that the PR merges today, it should be released in the pre-release channel tomorrow. 

Thanks!

**Comment by KUGA2** [comment]
I can confirm that this works in v1.17.16

**Comment by gcampbell-msft** [comment]
@KUGA2 The fix I merged seems to have regressed other inheriting for things like cacheVariables. 

Could you all download this file:
[cmake-tools.zip](https://github.com/microsoft/vscode-cmake-tools/files/14361639/cmake-tools.zip)
, change the extension to a .vsix. and install it manually in VS Code and confirm that it still fixes your issue?

**Comment by KUGA2** [comment]
Yes, i can confirm this works.
btw: We also had a similar error like #3603. I can confirm this is also fixed with this private build.

PS: please change the version of your local build to something reasonable. like 9.9.9 or 0.0.0. It is 1.13 which is quite confusing.
