### ISSUE TITLE
Command '(Internal) Build a Target by Name' resulted in an error - command 'cmake.buildNamedTarget' not found

### ISSUE THREAD

**Issue by i-ky** [microsoft/vscode-cmake-tools#3596]
### Brief Issue Summary

Attempt to run "(Internal) Build a Target by Name" command which is available from Command Palette:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/25753618/056859a1-d3b0-48b6-87b1-1bc3e4f0ce0c)
...results in an error:
> **Command '(Internal) Build a Target by Name' resulted in an error**
command 'cmake.buildNamedTarget' not found

![image](https://github.com/microsoft/vscode-cmake-tools/assets/25753618/c60da552-8ba0-44e2-96a9-cd9a6fbe6af2)

I understand, that this command is "internal" and is not supposed to be invoked by users, but it is strange that the command is listed in extension's manifest without any implementation under the hood. Looks like implementation was removed, but the manifest and translations were not cleaned up properly.

### CMake Tools Diagnostics

```shell
{
  "os": "linux",
  "vscodeVersion": "1.86.2",
  "cmtVersion": "1.17.15",
  "configurations": [
    {
      "folder": "/home/dev_user/dev_project",
      "cmakeVersion": "3.27.1",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "CXX": "/usr/bin/c++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

**Comment by gcampbell-msft** [comment]
@i-ky Thank you for posting this issue! This is almost certainly simply an error on our part. I've confirmed that this isn't a regression from our most recent release, so we will plan to get this fixed in our 1.18 release. Thanks!
