### ISSUE TITLE
Generating additional presets if no presets file exists

### ISSUE THREAD

**Issue by AlexandraKemperMS** [microsoft/vscode-cmake-tools#3615]
### Brief Issue Summary

Hi team! I was playing around with presets and ran into some strange error messages. Here is how you replicate: 

1. open a project that does not have a CmakePresets.json file
2. Go to your settings and change the Use Cmake Presets setting to "always"
3. go back to your project and use the "Add configure preset", then choose based on your compiler, choose a compiler and add a name
4. A presets file will be generated for you. Now, click on the buttons in the status bar. When you choose "No configure preset selected" it will give you the error "Cannot configure: no configure preset is active for this CMake project"

I showed this to Ben and Sinem who both mentioned that by design, this makes sense, but is super confusing from a user experience. I through by using this method that the extension would just generate the entire presets file for me.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.86.1",
  "cmtVersion": "1.18.3",
  "configurations": [
    {
      "folder": "c:\\Users\\Cmakedemo",
      "cmakeVersion": "3.27.4",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/Llvm/x64/bin/clang.exe",
        "CXX": "C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Tools/Llvm/x64/bin/clang.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///c%3A/Users/Cmakedemo/main.cpp"
    ],
    "responses": [
      {
        "uri": "file:///c%3A/Users//Cmakedemo/main.cpp",
        "configuration": {
          "includePath": [],
          "defines": [],
          "compilerPath": "c:/program files/microsoft visual studio/2022/preview/vc/tools/llvm/x64/bin/clang.exe",
          "compilerArgs": [],
          "compilerFragments": [
            "-O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 29,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "always",
      "configureOnOpen": true
    }
  ]
}
```

### Additional Information

![image](https://github.com/microsoft/vscode-cmake-tools/assets/67650598/3aeaa87e-1a2f-4934-bdb7-b50a83c2247f)

**Comment by gcampbell-msft** [comment]
Just tested this and it has been fixed, when a new preset is added it is by default selected as the active configure preset
