### ISSUE TITLE
Calling of build task doesn't work properly

### ISSUE THREAD

**Issue by Felix-devel** [microsoft/vscode-cmake-tools#3622]
### Brief Issue Summary

I want to use a task to run the cmake build since I want to use some specific problem matcher. If I start the task over Menu->Terminal->Run Build Task every thing works fine. But the buttons of the cmake extension don't call my speciffic build task but calls the default (template) build task. 

After press the build button here:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/138763124/9f389576-aee3-4a82-a85c-6a5a4d099293)
or here:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/138763124/ef299ecd-5ab3-4207-a067-23372a39828c)
VSCode asks for the build task but only suggest the CMake template build task.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/138763124/7eef3d36-26bc-4e2f-a91e-3851ea6a02be)

Even if I name the task "detail": CMake template build task, it doesn't use the one written in tasks.json. 
Also if i modify the template task which is added to the tasks.json if there is no. When I press the build Button it doen't use my modified one. 

If enabled the "Build Task" option for "User, Workspace and the Project"
![image](https://github.com/microsoft/vscode-cmake-tools/assets/138763124/ea5b7e34-acb8-44ea-ace6-2b045a171bfd)

There is a similar if I use the clean button, here it even doen't ask for the clean task, but for the build task.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/138763124/842fba1a-9822-4bb3-ace3-64d833973eeb)
![image](https://github.com/microsoft/vscode-cmake-tools/assets/138763124/4c2d32a7-8b87-4658-a9a9-cb1bb9179fe3)

### Additional Information

[tasks.json](https://github.com/microsoft/vscode-cmake-tools/files/14459936/tasks.json)

**Comment by gcampbell-msft** [comment]
@Felix-devel Thanks for letting us know. We recently have found that we may have some bugs in our tasks integration experience. I'll add this to the backlog of bugs related to that. 

@qarni FYI.

**Comment by moyo1997** [comment]
@Felix-devel  this is now fixed pending release! Also for clean, it says build tasks because clean is considered a part of build.

**Comment by v-frankwang** [comment]
We verified the issue on CMake tools: v1.19.45 and it has been fixed.

ENV：
CMake Tools:v1.19.45
vscode: 1.92.2

Actual result:
![image](https://github.com/user-attachments/assets/48afee0d-37ea-4929-9faa-ba5046aad29b)
