### ISSUE TITLE
Can I set access breakpoints for vcpkg

### ISSUE THREAD

**Issue by cctv130** [microsoft/vscode-cmake-tools#3623]
### Brief Issue Summary

I have a local custom port project, but there is a cmake error in the subdirectory of this project, I want to set breakpoints on find_package(z3 config) through the project after the installation of the patch
When I hit the play button, because the breakpoint condition (find_package(z3 config)) is triggered, I will automatically go to z3config.cmake for debugging, which should be a very useful requirement
Or can I rely on the current environment to debug the cmake file directly in the subdirectory？

**Comment by gcampbell-msft** [comment]
@cctv130 To confirm, you want to be able to debug into the cmake files? You should definitely be able to do this. 

You can either `Configure with CMake Debugger`, or you can create a launch.json with `type: cmake` and use the various settings to set up a debug session. Once you hit a breakpoint in any of those files, you should be able to step through as expected. 

Does this answer your question? Please let me know if not, I'm not 100% confident I fully understand what you're hoping to do.
