### ISSUE TITLE
Scan for compilers command is still available when using CMakePresets

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode-cmake-tools#3624]
### Brief Issue Summary

Since we view Kits and Presets as separate and distinct paths, we shouldn't have the "Scan for compilers" command available when a user is using presets. 

@sinemakinci1 Thoughts?

**Comment by sinemakinci1** [comment]
@gcampbell-msft I agree, these two paths should be as distinct as possible to avoid confusion.

**Comment by gcampbell-msft** [comment]
@bobbrow I noticed that there actually is a `Scan for Kits` and a `Scan for compilers` command. Is there historical context for these two different commands?
