### ISSUE TITLE
 Enhance Support for Configuring Third-Party Toolsets in CMake Projects

### ISSUE THREAD

**Issue by binhpht** [microsoft/vscode-cmake-tools#3628]
### Feature Request

**Issue Description:**

When working with CMake projects in Visual Studio Code, I aim to utilize a third-party Clang-CL compiler rather than the default LLVM Clang-CL that comes bundled with Visual Studio. Despite setting the toolset to use Clang-CL in my CMakePresets.json, CMake automatically defaults to the LLVM Clang-CL provided by Visual Studio.
Current Setup:

My CMakePresets.json is configured to specify the third-party Clang-CL compiler paths and to use Clang-CL as the toolset. However, even with these settings, the build process inadvertently picks up the Clang-CL compiler from Visual Studio's LLVM installation.
```
{
  "version": 3,
  "configurePresets": [
    {
      "name": "UseThirdPartyClangCL",
      "description": "Configuration to use third-party Clang-CL",
      "generator": "Visual Studio 17 2022",
      "toolset": "ClangCL",
      "cacheVariables": {
        "CMAKE_C_COMPILER": "C:\\path\\to\\thirdparty\\clang-cl.exe",
        "CMAKE_CXX_COMPILER": "C:\\path\\to\\thirdparty\\clang-cl.exe"
      }
    }
  ]
}
```
**Requested Feature:**

I would like to request enhanced support or clearer documentation on how to configure CMake projects in Visual Studio Code to prioritize the use of specified third-party toolsets over default installations. Specifically, it would be beneficial to ensure that when a toolset path is explicitly provided in the CMakePresets.json, CMake does not default to similar toolsets found within the Visual Studio installation.
Thanks

**Comment by gcampbell-msft** [comment]
@binhpht Thank you for letting us know about this. 

We are currently in the PR process for this PR #3612, which will allow more user control over when the Visual Studio environment is added to yours. This should allow you to more easily get what you want. 

Additionally, there is a PR out #3606 that we _**may**_ take that might improve this as well. 

If those propositions will solve your issue, please close this issue and follow those. If not, please let me know what other things you're asking about and asking for! Thank you.

**Comment by binhpht** [comment]
Hi, does the PRs support to set a custom LLVM location and toolset. In Visual studio code, According to this [link](https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170). The custom LLVM should be detect based on the file _Directory.build.props_ which has the content `<Project>
  <PropertyGroup>
    <LLVMInstallDir>C:\MyLLVMRootDir</LLVMInstallDir>
    <LLVMToolsVersion>15.0.0</LLVMToolsVersion>
  </PropertyGroup>
</Project>`
 However, I could not find the similar way to config with VS code.  Thanks

**Comment by oreyg** [comment]
This simple program seems to be working fine with #3606 (It grabs a compiler from provided CMAKE_CXX_COMPILER and std library is inferred from visual studio installation)
[test-project.zip](https://github.com/microsoft/vscode-cmake-tools/files/14531110/test-project.zip)

**Comment by oreyg** [comment]
Looking at #3612, it would work aswell, you would have to additionally set 
In preset: `CMAKE_C_COMPILER_WORKS=1`
and
`cmake.enableVSDevEnv` to true for your workspace
and in both cases @binhpht would need to use preset similar to one in the "test-project"

**Comment by gcampbell-msft** [comment]
@oreyg Thank you for confirming! @binhpht Does this answer your questions? Since it seems like we have confirmation, I'll close this issue, but if you have more follow ups, I'll re-open. Thanks!

**Comment by binhpht** [comment]
Thanks for help, I think this can solve my issue.
