### ISSUE TITLE
Add CmakePresets.json to CMake QuickStart

### ISSUE THREAD

**Issue by qarni** [microsoft/vscode-cmake-tools#3649]
### Brief Issue Summary

Dynamically generate a CMakeLists.txt file and CMakePresets.json file to get started with CMake using the QuickStart command.

Related to #2745

**Comment by gcampbell-msft** [comment]
Tagging #2745 in this to make sure that we update the documentation as well. Closing #2745 in order to clean up the backlog, but we need to make sure that we do that as well.

**Comment by gcampbell-msft** [comment]
Actually, leaving #2745 open since there was interest from an OSS contributor, but still, we need to make sure both happen, and then when completed, both are closed.
