### ISSUE TITLE
Always show standard error when executing cmake

### ISSUE THREAD

**Issue by geertj** [microsoft/vscode-cmake-tools#3650]
### Brief Issue Summary

In our setup, `cmake` is provided by our build system rather than the host OS. We have configured the cmake path to point to a wrapper (`cmake-wrapper`) instead. This wrapper asks the build system for the location of the cmake binary for the current package, and then executes it with the provided arguments. Generally this has been working very well. There is one usability improvement that would be nice to have for our users.

Sometimes our build system has to download new artifacts. This can take minutes, and while it does this, it displays progress on standard error. In other cases, it is possible that a developer has incorrectly configured dependencies for a package, and it is not possible to call the build system at all. In this case, an error is displayed on standard error.

In order to better work with these cases, it would be helpful if standard error would always be shown when CMake Tools runs cmake. This is usually the case, except at startup when CMake Tools calls `cmake --version` and `cmake -E capabilities`. We're not requesting any change to how the return code of these two commands is interpreted, just that standard error is displayed when running these commands. In the first case (downloading artifacts), cmake will run normally after our build system has downloaded artifacts, and standard error serves as a progress indicator to our users. In the second case (broken build system), our wrapper will exit with an error, causing the "bad cmake executable" message to be displayed. In this case, standard error helps the user understand what the issue is.

**EDIT**: I have analyzed our requirements a bit more, and I think all that is needed is to show standard error in case the above cmake invocations exit with a non-zero exit status. No output needs to be shown while the program is running. I have a simple patch that does this that I will submit as a PR shortly.

**Comment by gcampbell-msft** [comment]
@geertj THanks for the issue! I've added it to the "On Deck" milestone for us to consider for upcoming releases. Thanks.
