### ISSUE TITLE
cmake tools can't recognize the C/C++ compiler from cygwin

### ISSUE THREAD

**Issue by xusw-cs** [microsoft/vscode-cmake-tools#3656]
### Brief Issue Summary

i have installed cygwin with necessary components for C/C++ ,  and i create a cmake project in vscode, i select a kit GCC 11.4.0 x86_64-pc-cygwin， when i build the project , it report error like this : 
[main] Building folder: codeStudy 
[main] Configuring project: codeStudy 
[proc] Executing command: D:\App\Cygwin\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=D:\App\Cygwin\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=D:\App\Cygwin\bin\g++.exe -SD:/codeStudy -Bd:/codeStudy/build -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is unknown
[cmake] -- The CXX compiler identification is unknown
[cmake] CMake Error at CMakeLists.txt:2 (project):
[cmake]   The CMAKE_C_COMPILER:
[cmake] 
[cmake]     D:/App/Cygwin/bin/gcc.exe
[cmake] 
[cmake]   is not a full path and was not found in the PATH.

it seems that cmake  cant find compiler,  i an sure the compiler works well, because i can use it in powershell and in vscode teminal,  and i have set the PATH enviroment
i am confused because when i open the vscode terminal , and  excute command  " cmake ." ,   it work well, 
but when i click the cmake build button at the bottom of vscode, it report error

**Comment by gcampbell-msft** [comment]
@xusw-cs In order to best investigate this, could you please provide a minimal repro project that we can use to repro and investigate this bug with?
