### ISSUE TITLE
CMake build is failing with versions above v1.17.15

### ISSUE THREAD

**Issue by kerimbavcic** [microsoft/vscode-cmake-tools#3657]
### Brief Issue Summary

When using CMake Tools extention, the build is failing. Our log output indicates that CMake presets are not parsed properly (from CMakePresets.json) and are not "taken into account". When we run our build from terminal, everything works as expected.

Issues started occuring after the update to v1.17.16 and our temporary solution was to roll back to v1.17.15. We expected the problem to be fixed with the next update to v1.17.17, but the problem is still present. 

### Additional Information

Example of our error message is:

"VxWorks compiler sysroot not found. Please set WIND_CCSYSROOT"

and this variable(WIND_CCSYSROOT) is being set in CMake presets.

**Comment by gcampbell-msft** [comment]
@kerimbavcic  In order to best investigate this, could you please provide a minimal repro project that we can use to repro and investigate this bug with?

Without a reproduction project or at least a copy of the CMakeLists.txt and CMakePresets that you are using, it's very difficult to determine what might be the issue. 
Thank you!

**Comment by kerimbavcic** [comment]
Certainly, have a look at our minimized CMakeLists.txt, CMakePresets.json and build_output.txt.

Also one more thing, as I said this is just happening with using your tool (we can build successfully using the terminal where we manually add the wanted preset). We started getting this error with update to v1.17.16 and the build_output.txt indicates that the values from CMakePresets.json are not parsed for some reason.

I hope this will give you a better insight in the problem we are having.

[build_output.txt](https://github.com/microsoft/vscode-cmake-tools/files/14636293/build_output.txt)
[CMakeLists.txt](https://github.com/microsoft/vscode-cmake-tools/files/14636295/CMakeLists.txt)
[CMakePresets.json](https://github.com/microsoft/vscode-cmake-tools/files/14636296/CMakePresets.json)

**Comment by gcampbell-msft** [comment]
Since there is lots of dependencies and items in your CMakeLists.txt, is there a way to zip up your entire project so that I can attempt to reproduce? Thanks!

I'd like to be able to investigate this as soon as I can in case it's a regression. However, the build_output.txt file you sent doesn't currently give me any indication that it is caused by our recent changes. It's possible, but nothing specific jumps out at me yet.

**Comment by kerimbavcic** [comment]
@gcampbell-msft thank you for the support. While I'm preparing the project here are a couple of infos how we prepare our project for CMake, maybe this can help you understand the project better:

1. executing a powershell script, where we set environment variables, e.g. {VSB_PATH} (see CMakePresets.json line 39 where we set "WIND_CCSYSROOT" to this value).
2. at the end of powershell script we start VS Code.
3. project build which fails with specified error.

It seems that the problem is caused with this line (line 39):

`"environment": {
    "WIND_CC_SYSROOT": "$env{VSB_PATH}"
  }
`

**Comment by kerimbavcic** [comment]
@gcampbell-msft here is the minimal repro project, if you need anything else please let me know.

Thank you.
[minimal_repro_project.zip](https://github.com/microsoft/vscode-cmake-tools/files/14694797/minimal_repro_project.zip)

**Comment by gcampbell-msft** [comment]
What error are you seeing in the minimal repro project? I was not able to reproduce, I was able to build successfully when I opened VS Code in an environment that contains ninja and compilers on path. 

Thanks

**Comment by kerimbavcic** [comment]
It will build successfully, because nothing is being done. See the images below:

Here you see we set the env variable in line 7:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/113244867/48e22ec8-8a62-410a-ab8f-dd2683f45e65)

Here you see that PRESET_VAR should have the value of the env variable set in startvsCode.ps1
![image](https://github.com/microsoft/vscode-cmake-tools/assets/113244867/5f33d3e9-cf47-45b7-9278-beba4ea2409b)

In line 5 you see we print out the value of PRESET_VAR;
![image](https://github.com/microsoft/vscode-cmake-tools/assets/113244867/ef7076e9-2850-42b4-8560-d6e9ff2b0ee2)

And in output we don't see the value we set:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/113244867/a7f5986e-e5b5-43f1-a6cf-5ba2223e9550)

This is happening as well in the original project, but since the variable is used somewhere in the code, the build of original project is failing.

I hope it is clear now what the exact problem is.

**Comment by gcampbell-msft** [comment]
@kerimbavcic AH, thank you for the clarification, it's clear that I didn't fully understand the minimal repro. I will investigate. Thanks

**Comment by gcampbell-msft** [comment]
@kerimbavcic Ah, I've found the issue. Thanks for pointing this out! I have a PR opened here: #3664. Once it merges, please update to the pre-release version and it will be available the business day after the PR merges.

**Comment by kerimbavcic** [comment]
@gcampbell-msft No problem, thank you for your quick response and effort :)
