### ISSUE TITLE
${workspaceFolder} is not resolved on VSC start

### ISSUE THREAD

**Issue by ANauzet** [microsoft/vscode-cmake-tools#3658]
### Brief Issue Summary

I have a workspace with a settings.json with:
`"cmake.cmakePath": "${workspaceFolder}\\Tools\\cmake\\bin\\cmake.exe"`

When starting VSC, the following error are displayed:
```
[proc] Executing command: ${workspaceFolder}\Tools\cmake\bin\cmake.exe --version
[proc] The command: ${workspaceFolder}\Tools\cmake\bin\cmake.exe --version failed with error: Error: spawn ${workspaceFolder}\Tools\cmake\bin\cmake.exe ENOENT
[proc] Executing command: ${workspaceFolder}\Tools\cmake\bin\cmake.exe -E capabilities
[proc] The command: ${workspaceFolder}\Tools\cmake\bin\cmake.exe -E capabilities failed with error: Error: spawn ${workspaceFolder}\Tools\cmake\bin\cmake.exe ENOENT
```

If I replace ${workspaceFolder} by the "real" path, there are no error. But I need to use ${workspaceFolder} so that it work for any coworker using the projet in its own directory

After start, it work but having error displayed on start is confusing, especially for coworker not familiar with CMake

**Comment by gcampbell-msft** [comment]
@ANauzet Thanks for posting this issue! We should be supporting this macro, so this is definitely a bug.

**Comment by gcampbell-msft** [comment]
@ANauzet PR opened here #3658
