### ISSUE TITLE
Un-included header file in subdirectory includePath broken

### ISSUE THREAD

**Issue by TomKrcmar** [microsoft/vscode-cmake-tools#3665]
### Brief Issue Summary

When using VSCode to view a header file inside a CMake project, sometimes the header file has #include squiggles saying
```
#include errors detected based on information provided by the configurationProvider setting. Squiggles are disabled for this translation unit (D:\projects\tmp\cmake-tools-bug\src\B\B.h).C/C++(1696)
```

I created a minimum project setup to reproduce the issue. I found that the issue is caused by 2 conditions:
- The broken header file is not included by some translation unit somewhere in the project.
- The broken header file is trying to include something in a relative path from the project root.

With Log Diagnostics it seems CMake-Tools thinks the header file is a translation unit. Not sure if this is relevant or not.

Note the minimum project includes:
- A.h which tries to include subdir/util.h (works)
- B.h which tries to include subdir/util.h (broken)

The only difference between A.h and B.h is that A.h is included by the translation unit main.cpp, whereas B.h is not.

Project setup:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/7291070/c6c3fd7b-2812-4c89-8002-b8dad3fb8b8d)

main.cpp
```cpp
#include "subdir/A.h"
int main() {
	sayHello();
	return 0;
}
```
subdir/A.h
```cpp
#include "subdir/util.h"
void sayHello() {
	std::cout << "Hello";
	util::endl();
}
```
subdir/B.h **<-- THIS ONE IS BROKEN**
```cpp
#include "subdir/util.h" // <-- RED SQUIGGLY HERE
void sayWorld() {
	std::cout << "World";
	util::endl();
}
```
subdir/util.h
```cpp
#ifndef UTIL_H
#define UTIL_H

#include <iostream>

namespace util {
	void endl() {
		std::cout << std::endl;
	}
};

#endif
```
CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.26.4)
project(cmake-tools-bug)
set(CMAKE_BINARY_DIR ${CMAKE_CURRENT_LIST_DIR}/build)
set(CMAKE_CXX_STANDARD 20)
include_directories(src)
add_executable(test src/main.cpp)
```
.vscode/settings.json
```json
{
    "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",
    "C_Cpp.default.intelliSenseMode": "windows-gcc-x64",
    "cmake.buildDirectory": "${workspaceFolder}/.cmake",
    "cmake.loggingLevel": "debug"
}
```

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.87.2",
  "cmtVersion": "1.17.17",
  "configurations": [
    {
      "folder": "d:\\projects\\tmp\\cmake-tools-bug",
      "cmakeVersion": "3.26.4",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "D:/msys64/mingw64/bin/cc.exe",
        "CXX": "D:/msys64/mingw64/bin/c++.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///d%3A/projects/tmp/cmake-tools-bug/src/main.cpp",
      "file:///d%3A/projects/tmp/cmake-tools-bug/src/subdir/B.h"
    ],
    "responses": [
      {
        "uri": "file:///d%3A/projects/tmp/cmake-tools-bug/src/main.cpp",
        "configuration": {
          "includePath": [
            "d:/projects/tmp/cmake-tools-bug/src"
          ],
          "defines": [],
          "compilerPath": "d:/msys64/mingw64/bin/c++.exe",
          "compilerArgs": [],
          "compilerFragments": [
            "-g -std=gnu++20"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 1,
    "executablesCount": 1,
    "librariesCount": 0,
    "targets": [
      {
        "name": "test",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": null
    }
  ]
}
```

### Debug Log

```shell
[expand] expanding cmake
[main] Configuring project: cmake-tools-bug 
[main] Saving open files before configure/build
[expand] expanding D:/projects/tmp/cmake-tools-bug
[expand] expanding ${workspaceFolder}/.cmake
[driver] Start configure 
[driver] Running pre-configure checks and steps
[expand] expanding --no-warn-unused-cli
[expand] expanding -DCMAKE_BUILD_TYPE:STRING=Debug
[expand] expanding -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
[expand] expanding D:/projects/tmp/cmake-tools-bug
[expand] expanding ${workspaceFolder}/.cmake
[cmakefileapi-driver] Configuring using kit
[cmakefileapi-driver] Invoking CMake D:\msys64\mingw64\bin\cmake.EXE with arguments ["--no-warn-unused-cli","-DCMAKE_BUILD_TYPE:STRING=Debug","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-SD:/projects/tmp/cmake-tools-bug","-Bd:/projects/tmp/cmake-tools-bug/.cmake","-G","Ninja"]
[proc] Executing command: D:\msys64\mingw64\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -SD:/projects/tmp/cmake-tools-bug -Bd:/projects/tmp/cmake-tools-bug/.cmake -G Ninja
[proc]   with environment: { REDACTED }
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 13.1.0
[cmake] -- The CXX compiler identification is GNU 13.1.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: D:/msys64/mingw64/bin/cc.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: D:/msys64/mingw64/bin/c++.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- Configuring done (3.0s)
[cmake] -- Generating done (0.0s)
[cmake] -- Build files have been written to: D:/projects/tmp/cmake-tools-bug/.cmake
[cmakefileapi-parser] Read reply folder: d:\projects\tmp\cmake-tools-bug\.cmake\.cmake\api\v1\reply
[cmakefileapi-parser] Found index files: ["cache-v2-70f1464f46b7be553ca7.json","cmakeFiles-v1-24ad5f2b15c2ad18416c.json","codemodel-v2-77cca25d72f55825d07f.json","directory-.-Debug-d0094a50bb2071803777.json","index-2024-03-22T23-21-24-0323.json","target-test-Debug-2a038b1933481c52db08.json","toolchains-v1-4361422600fcf5269637.json"]
[expand] expanding cmake
[expand] expanding cmake
[cache] Reading CMake cache file d:/projects/tmp/cmake-tools-bug/.cmake/CMakeCache.txt
[cache] Parsing CMake cache string
[expand] expanding cmake
```

### Additional Information

The C++ Diagnostics logs are very revealing!

It seems B.h is being treated as a translation unit, and in the B.h TU section, the line:
`D:\projects\tmp\cmake-tools-bug\src`
is missing from the `Includes:` section! Even if B.h must be treated as a TU, why can't it inherit the same include path settings as the other TUs?

~Another observation, the cppStandard (c++17) is not the setting specified in CMakeLists.txt (c++20). CMake Tools seems to pick up the correct version, but maybe it's not communicating it to VSCode?~ Scratch that, I see c++20 is listed closer to the TU sections. gnu++17 at the top may just refer to some default.

```
-------- Diagnostics - 3/22/2024, 7:22:30 PM
Version: 1.19.9
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "d:/projects/tmp/cmake-tools-bug/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "D:\\msys64\\mingw64\\bin\\gcc.exe",
    "cStandard": "c17",
    "cppStandard": "gnu++17",
    "compilerPathInCppPropertiesJson": "D:\\msys64\\mingw64\\bin\\gcc.exe",
    "intelliSenseMode": "windows-gcc-x64",
    "intelliSenseModeIsExplicit": true,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "d:/projects/tmp/cmake-tools-bug/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "d:/projects/tmp/cmake-tools-bug/src"
    ],
    "compilerPath": "d:/msys64/mingw64/bin/c++.exe",
    "compilerArgs": [],
    "compilerFragments": [
        "-g -std=gnu++20"
    ]
}
cpptools version (native): 1.19.9.0
Translation Unit Mappings:
[ D:\projects\tmp\cmake-tools-bug\src\main.cpp - source TU]:
    D:\projects\tmp\cmake-tools-bug\src\subdir\A.h
[ D:\projects\tmp\cmake-tools-bug\src\subdir\B.h - source TU]:
Translation Unit Configurations:
[ D:\projects\tmp\cmake-tools-bug\src\main.cpp ]:
    Process ID: 17056
    Memory Usage: 134 MB
    Compiler Path: D:\msys64\mingw64\bin\c++.exe
    Includes:
        D:\projects\tmp\cmake-tools-bug\src
        D:\msys64\mingw64\include\c++\13.1.0
        D:\msys64\mingw64\include\c++\13.1.0\x86_64-w64-mingw32
        D:\msys64\mingw64\include\c++\13.1.0\backward
        D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\13.1.0\include
        D:\msys64\mingw64\include
        D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\13.1.0\include-fixed
    Standard Version: c++20
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=130100
[ D:\projects\tmp\cmake-tools-bug\src\subdir\B.h ]:
    Process ID: 9524
    Memory Usage: 50 MB
    Compiler Path: D:\msys64\mingw64\bin\c++.exe
    Includes:
        D:\msys64\mingw64\include\c++\13.1.0
        D:\msys64\mingw64\include\c++\13.1.0\x86_64-w64-mingw32
        D:\msys64\mingw64\include\c++\13.1.0\backward
        D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\13.1.0\include
        D:\msys64\mingw64\include
        D:\msys64\mingw64\lib\gcc\x86_64-w64-mingw32\13.1.0\include-fixed
    Standard Version: c++20
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=130100
Total Memory Usage: 184 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3566
```

**Comment by TomKrcmar** [comment]
For future readers, you can workaround it by just force-feeding your include dirs directly to c_cpp_properties and removing cmake-tools from settings.

The drawback is you lose any of the other comforts cmake-tools was giving you, and you have to repeat your includes both in your cmake setup and in here.

c_cpp_properties .json
```json
{
	"configurations": [
		{
			"name": "Win32",
			"includePath": ["${workspaceFolder}/src"]
		}
	],
	"version": 4
}
```
settings.json (showing only the line to comment/remove)
```json
{
    // "C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools"
}
```

**Comment by gcampbell-msft** [comment]
@Colengms Curious if you have any immediate expertise here? 

At first glance, it seems like it's an issue on our side where for some reason the `D:\projects\tmp\cmake-tools-bug\src` is missing from the includes like the user posted, but it could be just a c++ issue, so I'm curious if you have immediate thoughts before I put it on our backlog. Thanks!

**Comment by TomKrcmar** [comment]
Hey thanks for looking into this and clarifying.

I figured it might be something like that, but when I tried to use cmake-tools config provider together with setting a default include dir via settings.json, it doesn't seem to fall back on the defaults for the header file. I also added a c_cpp_properties with the include dir above in my workaround, but as long as cmake-tools config provider is set, none of the other settings seem to take effect, and the header stays broken:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/7291070/1151aaea-a855-41ba-854f-bfd79680f732)

> I believe this can be addressed by associating the header with your project in your CMakeLists.txt.
I'm not a pro with CMakeLists script; is there a way to associate it with the project without adding it as a source to some binary? It isn't meant to be a TU that goes into the compiler CLI, but it would be nice to add a loose header file within the project that still gets my CMake-driven intellisense and c++xx version config. The use case being starting a new header file that you want to implement some before deciding where/how to include it in the greater project yet.

**Comment by Colengms** [comment]
Hi @TomKrcmar .  Actually, I was mistaken about one detail.  Rather than fallback to the base configuration, the C/C++ extension currently falls back to the browse configuration for files the configuration provider was unable to provide a configuration for.  This is actually a bug, and it should fall back to the base configuration.  I've opened an issue to track this here: https://github.com/microsoft/vscode-cpptools/issues/12144

**Comment by TomKrcmar** [comment]
> Hi @TomKrcmar . Actually, I was mistaken about one detail. Rather than fallback to the base configuration, the C/C++ extension currently falls back to the browse configuration (a compiler path and args passed by the config provider that we use to populate the browse database) for files the configuration provider was unable to provide a configuration for. This is actually a bug, and it should fall back to the base configuration. I've opened an issue to track this here: [microsoft/vscode-cpptools#12144](https://github.com/microsoft/vscode-cpptools/issues/12144)

Awesome, I'll keep an eye on that one, and this one can be closed.

Regarding the header association with the CMake project you mentioned, I think that would be ideal so I don't have to repeat my CMake configs in vscode settings or risk the settings being mismatched in non-obvious ways. If I did that, I might be looking at different C++ validation rules applied to header files that I'm not even aware are falling back on non-CMake settings. Additionally, if I'm writing a header-only library, I'm not sure if cmake-tools would apply to any of the files.

Looking into it, I found a couple of avenues, but none of them have worked. They include:

- Adding headers to a custom_target dedicated to fixing IDEs. cmake-tools did not pick these headers up, plus setting target_include_dirs on custom targets is not allowed in CMake.
(see all answers of https://stackoverflow.com/q/27039019)

- Adding the headers as sources to the main target. This was allowed in CMake and apparently CMake correctly adds the files and filters header files when compiling. But cmake-tools did not pick up the headers regardless after being added to the target:
https://stackoverflow.com/a/10973278
![image](https://github.com/microsoft/vscode-cmake-tools/assets/7291070/89890c31-7dae-4d07-b60c-ace84e2d14a9)

**Comment by TomKrcmar** [comment]
> @TomKrcmar This _may_ be a different bug, but if you could create a new issue, that would greatly help us with issue tracking. If you determine/decide it's a new/different bug that is, thanks!

I did some more testing, and getting some strange results. Created several more unused headers, included one of them, then deleted the cpp file that included it so it was orphaned again, that header remained fixed. Clearing CMake cache, deleting CMake generated folder, resetting intellisense database, nothing re-broke the file.

Very mysterious, but after restarting VSCode today not only was that fixed, but the above issue about headers associated with the project not being picked up by cmake-tools was also fixed! For future readers, the following has worked for me after a VSCode restart. This is **without** a c_cpp_properties.json file at all, and cmake-tools set as the config provider. This is exactly the solution I wanted.
![image](https://github.com/microsoft/vscode-cmake-tools/assets/7291070/61a70a92-09fa-4bd9-81b8-2a317f4a631c)

If glob is acceptable for your project, you can use glob patters to grab all header files and add them so it's automated for your project hierarchy.
