### ISSUE TITLE
clang-cl program build issues

### ISSUE THREAD

**Issue by cctv130** [microsoft/vscode-cmake-tools#3666]
### Brief Issue Summary

How to run vcvars64.bat before using clang-cl?
I want to debug cmake right click cmakelists.txt select debug, but I want to run vcvars64.bat before debugging the project.

```[tasklist]
### Tasks
```

**Comment by gcampbell-msft** [comment]
@cctv130 To get more context on this, what is the full scope of your scenario? What are you needed vcvars.bat for? 

We currently have some level of support (and are planning on improving it) for including the Visual Studio development environment with your presets, which may enable this. However, depending on your scenario, this may be a feature request. 

THanks!

**Comment by gcampbell-msft** [comment]
@cctv130 Could you test the workaround that I suggested here: https://github.com/microsoft/vscode-cmake-tools/issues/3502#issuecomment-2026064274

**Comment by gcampbell-msft** [comment]
@cctv130 Are you using kits or presets?

**Comment by gcampbell-msft** [comment]
Closing this in favor of other issues #3497 that are related to the VS environment, we plan to improve our "magic" which will resolve this issue.
