### ISSUE TITLE
CMake Debugger restart issue

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode-cmake-tools#3674]
### Brief Issue Summary

The ability to restart a CMake Debugger debugging process is expected. Right now it just bails when restart is attempted. 

Also, there are times where the CMake configure failure isn't something that the Debugger can actually help with, but the "Configure with CMake Debugger?" popup still appears.

**Comment by qarni** [comment]
Marking as duplicate #3582  wont fix
