### ISSUE TITLE
Setting cmake.loadCompileCommands not documented

### ISSUE THREAD

**Issue by RobbertProost** [microsoft/vscode-cmake-tools#3680]
### Brief Issue Summary

The setting to prevent the extension from loading the compilation database (`cmake.loadCompileCommands`) is present in the source code, but is not documented in `docs/cmake-settings.md`. I think it makes sense to add this to the document.

### CMake Tools Diagnostics

```shell
NA
```

### Debug Log

```shell
NA
```

**Comment by gcampbell-msft** [comment]
@sinemakinci1 FYI.

**Comment by gcampbell-msft** [comment]
Closed, fixed in #3746
