### ISSUE TITLE
Typo: "unknow" instead of "unknown"

### ISSUE THREAD

**Issue by mkucmpro** [microsoft/vscode-cmake-tools#3682]
### Brief Issue Summary

https://github.com/microsoft/vscode-cmake-tools/blob/73ac9596bede222d9a399d54b17f17ca8ce22fa4/src/drivers/cmakeDriver.ts#L429

Typo: `unknow` instead of `unknown` in this file

**Comment by gcampbell-msft** [comment]
This is also the case for the one below it in that file.
