### ISSUE TITLE
[MacOS 14.5]Why the CMake-Tools extension does not display in English?

### ISSUE THREAD

**Issue by nolongerwait** [microsoft/vscode-cmake-tools#3691]
### Brief Issue Summary

<img width="1195" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/22978131/0d4ad260-13f4-4435-84f8-4428fcd29528">
<img width="560" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/22978131/807fbc32-cc94-4b63-b274-1810534bbb86">

why these areas display in Chinese language? and I need it in English.

<img width="1147" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/22978131/f3b47606-9d8f-43bc-a217-93c42646fa30">

I confirm that my "Configurate Display Language" is "English"(see the latest image).

**Comment by nolongerwait** [comment]
Can anyone help me to change the cmake-tools extension display language to English?

**Comment by nolongerwait** [comment]
I find this issue https://github.com/microsoft/vscode/issues/82791 , but I didnot download any language pack.

so, why the cmake-tools extension still display in Chinese? All the other extensions display in English and work normally.

**Comment by nolongerwait** [comment]
in `.vscode/extensions/ms-vscode.cmake-tools-1.17.17/dist/main.js`
```
class SchemaProvider {
    async provideTextDocumentContent(uri) {
        console.assert(uri.path[0] === '/', "A preceeding slash is expected on schema uri path");
        const fileName = uri.path.substr(1);
        const locale = util.getLocaleId();
        let localizedFilePath = path.join(util.thisExtensionPath(), "dist/schema/", locale, fileName);
        const fileExists = await util.checkFileExists(localizedFilePath);
        if (!fileExists) {
            localizedFilePath = path.join(util.thisExtensionPath(), fileName);
        }
        return pr_1.fs.readFile(localizedFilePath, "utf8");
    }
}
```

`util.getLocaleId();` what value will return after call this method, and does it get locale from vscode display language or local device?

**Comment by nolongerwait** [comment]
fine, when I upgrade my vscode to latest version(1.88) in my another macbook pro, the cmake-tools extension display language also change to Chinese.

**Comment by gcampbell-msft** [comment]
@nolongerwait To confirm, this happens only for this extension? 

We use the `vscode-nls` extension for localization, which should handle this appropriately, I wonder if there is a bug with that?

**Comment by gcampbell-msft** [comment]
It seems like there was an issue here as well for a different extension: https://github.com/microsoft/vscode-cpptools/issues/10632, and it seems like it should be fixed based on this: https://github.com/microsoft/vscode-cpptools/issues/10632#issuecomment-1482050757. 

@TylerLeonhardt Is there any known bugs on VS Code with this still?

**Comment by nolongerwait** [comment]
Based on the content of the issue you provided, I have made the following discoveries:
When I download and use other language packs, all displays are correct. For instance, when I download the Japanese language pack and restart vscode, the entire interface, including the notification UI of cmake-tools, is displayed in Japanese. At this point, if I switch back to English through Configure Display Language, everything returns to normal, and cmake-tools also displays UI notifications in English.

<img width="1733" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/22978131/10367422-0705-484e-8808-ae8dab024a9b">
<img width="1683" alt="image" src="https://github.com/microsoft/vscode-cmake-tools/assets/22978131/3c90dba3-0ee6-4b23-ae5e-fc43dbd71534">

So, I suspect that vscode-nls might still have a BUG, which causes the locale to retrieve the local device's regional language instead of the display language set by vscode in an initial environment (where only the default English display is available).

**Comment by gcampbell-msft** [comment]
Closing since this seems external and there is a workaround. Once we get confirmation about where the external issue might be we'll create a bug in the correct location.
