### ISSUE TITLE
CMake Quick Start command asks user to browse a CMakeLists.txt

### ISSUE THREAD

**Issue by suikan4github** [microsoft/vscode-cmake-tools#3710]
### Brief Issue Summary

In the WSL environment, when a user creates a new project in an empty directory, the _CMake Quick Start command_ asks the user to browse an existing CMakeLists.txt. This makes users confused. 

This browse request is not explained in the [document](https://code.visualstudio.com/docs/cpp/cmake-linux#_create-a-cmake-hello-world-project). So, it could be a bug.  

Note: I saw this issue only once in a user account. So, you may need to create a new VM to see. 

## Environment
- Windows 11 WSL 2
- VS Code 1.88.1
- CMake Tools v1.17.17

## Procedure to reproduce

Please see the procedure to reproduce : 

1. From the bash, launch vs code. 
2. Run the _CMake Quick Start_ command from the command pallet. 
3. Select a kit.
4. You will see the message to browse the existing CMakeLists.txt.

## Screenshots
 
Launch the VS Code from an empty directory, and start the _CMake Quick Start_ command. ( procedure 1 and 2 ) 
![](https://github.com/microsoft/vscode-cmake-tools/assets/26223147/018c7e93-e632-4893-a407-f811963668eb)

Select a kit (3).
![](https://github.com/microsoft/vscode-cmake-tools/assets/26223147/9e8f7da0-1297-4d97-b572-575fe47dbedc)

You will see the message to browse the existing CMakeLists.txt(4)
![](https://github.com/microsoft/vscode-cmake-tools/assets/26223147/19a094fb-7ff5-43b6-9138-0aad61f1d875)

**Comment by v-frankwang** [comment]
@gcampbell-msft Following the steps given by the user, this issue we can reproduce on top of the latest VSCode and you can get some information below:

ENV:
VS Code: 1.88.1
CMake tools: 1.18.27
C/C++:1.20.1

Repro steps recording:
![repro](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/2e5296cd-1dc6-46c2-9e59-084216f2c75f)

**Comment by gcampbell-msft** [comment]
@qarni FYI.

**Comment by gcampbell-msft** [comment]
@qarni I believe this is fixed with #3717. Closing. However, please confirm if not fixed.
