### ISSUE TITLE
${workspaceFolder} is not resolved in cmake.debugConfig

### ISSUE THREAD

**Issue by upcliujie** [microsoft/vscode-cmake-tools#3711]
### Brief Issue Summary

settings.json:
``` json
"cmake.debugConfig": {
        "environment": [
            {
                "name": "LD_LIBRARY_PATH",
                "value": "${workspaceFolder}/build/bin"
            },
        ]
    },
```
gdb can't get LD_LIBRARY_PATH environment

**Comment by v-frankwang** [comment]
@upcliujie I am unable to reproduce this issue, can you provide more information on reproducing this issue?

**Comment by upcliujie** [comment]
@v-frankwang The environment variable read on the executable file is incorrect，${workspaceFolder} is not be expanded.

**Comment by v-frankwang** [comment]
@upcliujie Could you please provide your error log and reproduce project?

**Comment by upcliujie** [comment]
@v-frankwang 
![图片](https://github.com/microsoft/vscode-cmake-tools/assets/53069964/c6a8e68c-2027-4d75-a7dd-eb19de91689a)
![图片](https://github.com/microsoft/vscode-cmake-tools/assets/53069964/b62120d5-c3da-4fe0-84fe-936f25ce78d5)
![图片](https://github.com/microsoft/vscode-cmake-tools/assets/53069964/891271bc-8731-4f82-bcc3-fdbe6d0021ad)

**Comment by gcampbell-msft** [comment]
@upcliujie How are you executing the code? Are you executing the code using the CMake debug button? If so, I think you're right that this is a possible bug and we should put it on the backlog to investigate.

**Comment by upcliujie** [comment]
> @upcliujie How are you executing the code? Are you executing the code using the CMake debug button? If so, I think you're right that this is a possible bug and we should put it on the backlog to investigate.

Yes，I execute the code using the CMake debug button.

**Comment by v-frankwang** [comment]
This bug has been fixed. :
![image](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/379ce3dc-e0cc-4f12-8b99-7a7b63758f61)

**Comment by geertj** [comment]
Slightly broadening this feature request, hope that is okay. It would be nice if `${workspaceFolder}` is expanded as in `cmake.debugConfig.miDebuggerPath` as well. Our use case is that we have a gdb wrapper that is local to a package.

**Comment by v-frankwang** [comment]
@geertj This issue has been fixed, and for the issue you raised you can go ahead and create a new issue
