### ISSUE TITLE
cmakeuserpresets.json not read by vscode-cmake-tools?

### ISSUE THREAD

**Issue by aiyolo** [microsoft/vscode-cmake-tools#3725]
### Brief Issue Summary

My CMake project folder has a cmakeuserpresets.json file, but the preset(both configure preset and build preset) is not loaded by vscode-cmake-tools, so I can't use the preset defined in cmakeuserpresets.json.
Is there any option to open this feature? How can use the preset defined in cmakeuserpresets.json?

**Comment by v-ericawu** [comment]
@gcampbell-msft We reproduced the issue using the following steps:

**ENV:**
- OS: Win10 22H2
- VS Code version: 1.88.1
- CMake Tools extension: 1.18.31(pre-release)

**Repro Steps:**
1. Download and unzip [Test ](https://microsoft-my.sharepoint.com/:u:/p/v-ericawu/EYUiBlM8qZpIsIKuTvCzTzUBpBwIba74EwI8yDgbaEPO5A?e=uPTqpq)project.
2. Open Test project with VS Code.
3. Press F1 and run command 'CMake: Add Configure Preset', select 'Inherit from Configure Preset'.

**Expected Result:** Can add preset (both configure preset and build preset) for 'CMakeUserPresets.json' file. 

**Actual Result:** preset (both configure preset and build preset) only adds to the CMakePresets.json file but not to the CMakeUserPresets.json file.

**'CMake: Add Configure Preset'->'Inherit from Configure Preset':**
![image](https://github.com/microsoft/vscode-cmake-tools/assets/78774400/abd06e8e-09d5-416c-830f-0f335eb626ad)

**‘CMake: Add Build Preset’->'Create from Configure Preset':**
![image](https://github.com/microsoft/vscode-cmake-tools/assets/78774400/7279dacf-cc0e-49f6-9ad1-1b4e42241940)

**Comment by gcampbell-msft** [comment]
@aiyolo Does the above reproduction match the issue that you are hitting? Is it only this use case that it is happening in? Or is there more general issues?

**Comment by aiyolo** [comment]
yes, it is the issue I'm hitting, I think it's a general issue.

**Comment by benschreiber** [comment]
Possibly related to #3636

**Comment by v-ericawu** [comment]
@gcampbell-msft @aiyolo @benschreiber Verified on CMake Tools v1.18.37(pre-release), this issue still repro:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/78774400/40dd06c0-a87a-43e5-8cdb-47e5d6aa2b88)

**Comment by Ashley-Li** [comment]
Verified on CMake Tools v1.18.43(pre-release), this issue was fixed:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/56664234/71667d56-f477-47a2-86a0-f38ddba0d6aa)
