### ISSUE TITLE
usepresets context is not set after using quickstart

### ISSUE THREAD

**Issue by qarni** [microsoft/vscode-cmake-tools#3734]
### Brief Issue Summary

When a CMakePreset is added through QuickStart, or if the user escapes out before adding a preset, the usepresets context is not set, and so no preset options pop up in the command pallete.

**Comment by v-frankwang** [comment]
@qarni @gcampbell-msft This issue has been fixed, should I close it?

**Comment by gcampbell-msft** [comment]
@qarni @v-frankwang I don't think that it's been fixed, we'll leave it open pending confirmation from Fatima.

**Comment by qarni** [comment]
> @qarni @v-frankwang I don't think that it's been fixed, we'll leave it open pending confirmation from Fatima.

Yeah, this hasn't been fixed.

**Comment by v-frankwang** [comment]
@qarni @gcampbell-msft Thank you very much for your replies, I'm very sorry I guess I didn't understand the question, here are my steps, can you give me some advice?

Steps：
![repro4](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/53a5bd55-0a37-4558-9086-6972295aaf87)

**Comment by qarni** [comment]
https://github.com/microsoft/vscode-cmake-tools/assets/17552078/00db1d00-8007-4980-ae5a-aad92ea6126b

**Comment by Ashley-Li** [comment]
Verified on CMake Tools v1.18.43(pre-release), this issue was fixed:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/56664234/6ffb7400-ecec-48e6-8f60-a8794381fb80)

https://github.com/microsoft/vscode-cmake-tools/assets/56664234/6a596537-2842-478c-bb97-e9dae1fdbbf9
