### ISSUE TITLE
Investigate passing multiple workspace browse configurations (1 for each target+fileGroup combo) to C/C++ extension

### ISSUE THREAD

**Issue by snehara99** [microsoft/vscode-cmake-tools#3736]
### Brief Issue Summary

Currently only 1 target and file group (the last combo) is used to create the workspace browse configuration for c/c++ extension. Maybe working with the C/C++ extension to pass workspace browse configurations for all combinations is a good move which can potentially fix intellisense issues.

Check updateConfigurationData() in cpptools.ts

**Comment by snehara99** [comment]
@gcampbell-msft as per our convo

**Comment by v-frankwang** [comment]
>Currently only 1 target and file group (the last combo) is used to create the workspace browse configuration for c/c++ extension

@snehara99 Thanks for posting this issue, could you please provide an example? :)

**Comment by snehara99** [comment]
@gcampbell-msft actually told me to open this issue, so I'll add the stale-exempt label so that this issue isn't closed by the stale bot
