### ISSUE TITLE
After clicking Run Tests an error is reported

### ISSUE THREAD

**Issue by v-frankwang** [microsoft/vscode-cmake-tools#3738]
### Brief Issue Summary

**Note: This issue is only reproduced on the pre-release channel.**

Repro steps:

1.	Create a new folder named 'CMakeProject1' and open it with vscode.
2.	Create a file named CMakeLists.txt with the following content:
                 cmake_minimum_required(VERSION 3.8) 
                 project(CMakeProject1)
                 add_executable(CMakeProject1 "CMakeProject1.cpp" "CMakeProject1.h")
                 enable_testing()
                 add_executable(UnitTest "test.cpp")
                 add_test(UnitTest0 UnitTest 0)
                 add_test(UnitTest1 UnitTest 1)
3.	Create a file named test.cpp with the following content:    
                 #include <iostream> 
                  auto main() -> int { std::cout << "hello world" << std::endl; }
4.	Create a file named CMakeProject1.cpp with the following content:  
              #include "CMakeProject1.h"
               using namespace std;
               int main()
              {
                   cout << "Hello CMake." << endl;
                   return 0;
              }
5.	Create a file named “CMakeProject1.h” with the following content:
               #pragma once
               #include <iostream>
6.	Run command: “CMake:configure”
7.	Click on Testing in the left navigation bar
8.	Click'Debug Tests'.

Actual results：
![image](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/1c97cc0f-d60c-497d-913f-9ea40cc16301)

**Comment by gcampbell-msft** [comment]
This PR #3731 fixes this issue. Thanks.

**Comment by v-frankwang** [comment]
We verified this issue on CMake Tools: v1.20.3 (pre-release), and it has been fixed.

Actual result:
![image](https://github.com/user-attachments/assets/e04e12b8-6aec-4fcf-9a6f-80ba1c633aad)
