### ISSUE TITLE
How to set the default ``cmake_minimum_required`` version in QuickStart command

### ISSUE THREAD

**Issue by LiuZengqiang** [microsoft/vscode-cmake-tools#3793]
## How to set the default cmake_minimum_required version in QuickStart command?
When using "QuickStrat", there will be created a default ``CMakeLists.txt`` file, the ``cmake_minimum_required`` is ``3.0.0`` in this file.
It will create a warning of ``"(cmake_minimum_required):Compatibility with CMake < 3.5 will be removed from a future version of
CMake."``, how to set the ``cmake_minimum_requied`` is ``3.20.0`` or other user defined version?

**Comment by Yingzi1234** [comment]
@LiuZengqiang Thank you for your GitHub issue! You can fix this by manually modifying the code “`cmake_minimum_required(VERSION 3.0.0)`” in the CMakeLists.txt file to a version greater than (version 3.5.0).

**Before modify:**
![image](https://github.com/microsoft/vscode-cmake-tools/assets/101234795/6953ee07-5bb2-481d-93ad-6ccd5b2921ce)

**After modify:**
![image](https://github.com/microsoft/vscode-cmake-tools/assets/101234795/4a52661f-9077-4d2a-8c4b-5517a33d0358)

Please feel free if you have any questions and doubt!

**Comment by LiuZengqiang** [comment]
@Yingzi1234  Thanks for your reply. However, I'm too lazy to modify it manually 😂. Specifying the CMake version in the configuration file of cmake-tools once and for all might be a better solution.

**Comment by v-frankwang** [comment]
Verified on CMake Tools v1.18.43(release)，this issue has been fixed：

Actual result：
![image](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/bd6aa910-2946-41b2-bb68-2a572ac66bd5)

**Comment by LiuZengqiang** [comment]
> Verified on CMake Tools v1.18.43(release)，this issue has been fixed：
> 
> Actual result： ![image](https://private-user-images.githubusercontent.com/160998958/346929757-bd6aa910-2946-41b2-bb68-2a572ac66bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzI0ODYsIm5iZiI6MTcyMDU3MjE4NiwicGF0aCI6Ii8xNjA5OTg5NTgvMzQ2OTI5NzU3LWJkNmFhOTEwLTI5NDYtNDFiMi1iYjY4LTJhNTcyYWM2NmJkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwMDQzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTVkNzMwYzczNWFhNzExNzE3ZWRjNTcyYjFlYzAyZmFkMTRhNjliZmEwZDZlMjQ0ZjBiNzU4MjYwMmVjZjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hIasWkEB_INLYyHT86q9kb8MtKxcYIh3Yg_CKjTk-KQ)

Yes, I know, because it is fixed by me ☺️.
