### ISSUE TITLE
Customer request: Add a setting for hierarchy delimiter to Test Explorer

### ISSUE THREAD

**Issue by sinemakinci1** [microsoft/vscode-cmake-tools#3795]
### Brief Issue Summary

From a customer request, 

"Add a setting that is for a hierarchy delimiter that the user can pick.  I’ve seen this in some of the other extensions. This would maintain current behavior, but allow users to customize how things are displayed."

**Comment by tristanlabelle** [comment]
Implemented in https://github.com/microsoft/vscode-cmake-tools/pull/3759
