### ISSUE TITLE
Installing cmake after launching VS Code results in claims of a cmake invalid location, forcing user to restart VS Code to proceed

### ISSUE THREAD

**Issue by oursland** [microsoft/vscode-cmake-tools#3811]
### Brief Issue Summary

In environments where the `cmake` path points to a file that does not yet exist, installing `cmake` does not correct the issue requiring restaring VS Code to proceed.

An example is in projects where build dependencies are maintained through a local package manager such as `conda`.  When the project is loaded, the path to `cmake` for the project is invalid.  After installing the build dependencies, the `vscode-cmake-tools` extension does not attempt to use the newly installed `cmake`.

What is expected is that when attempting to use `cmake` an error due to the absence of the `cmake` executable should present a UI, and when the `cmake` executable is installed it should use this.  The current implementation performs this check once, presumably to prevent multiple UI notifications of the `cmake` path error.

It would be preferable to try to run the `cmake` program each time to account for the possibility of the program being installed, and upon failure only present the error notification UI on the first failure.

**Comment by oursland** [comment]
Related to https://github.com/microsoft/vscode-cmake-tools/issues/3570

**Comment by v-frankwang** [comment]
@oursland I'm very sorry that I can't reproduce the problem you mentioned, I uninstalled cmake installed on my machine and running cmake: configure command gives me an error, when I reinstalled cmake without restarting vscode and ran cmake: configure command directly the cmake project can be configured successfully, can you give me some suggestions?

Repro steps：
![not repor](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/2ea5e00e-5397-4826-8fdb-675352e74481)
