### ISSUE TITLE
[regression] TypeError when running CTests with debugging

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/vscode-cmake-tools#3817]
### Brief Issue Summary

Running tests with debugging from the test explorer has recently regressed to failing with
> TypeError: Cannot read properties of undefined (reading 'fsPath')"

![image](https://github.com/microsoft/vscode-cmake-tools/assets/2314287/86f2fe17-a6c3-4c0b-a71c-cf79d937ad37)

I attached a debugger and found that [this line](https://github.com/microsoft/vscode-cmake-tools/blob/227d9632cf70fcd232e79ab137f0025c1e798897/src/ctest.ts#L1107) assumes that `TestItem.uri` is non-null, whereas it is in our case.

![image](https://github.com/microsoft/vscode-cmake-tools/assets/2314287/4f71b4fd-427b-4d50-909a-80df17575f59)

I'm flagging this as a regression because it just recently started happening and affecting our engineers.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.89.1",
  "cmtVersion": "1.18.41",
  "configurations": [
    {
      "folder": "c:\\Code\\<snip>",
      "cmakeVersion": "3.29.3",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "clang",
        "CXX": "clang"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 303,
    "executablesCount": 8,
    "librariesCount": 265,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "always",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
This is unrelated to the CMake build, but a problem of the CTest integration.
```

**Comment by gcampbell-msft** [comment]
@tristanlabelle Could you try out this PR? #3814 I've updated it to include a catch fix for this.

**Comment by tristanlabelle** [comment]
@gcampbell-msft , yup, that fixes it!
