### ISSUE TITLE
Ninja Output no longer stays on one line

### ISSUE THREAD

**Issue by spinicist** [microsoft/vscode-cmake-tools#382]
### Brief Issue Summary

Hi,

One of the reasons I like Ninja is that, if there are no problems, compilation messages are overwritten on the same line so your terminal/output window does not get spammed. This has stopped working for me in the VS Code output pane this week - I don't know whether it is CMake Tools 0.11, or the March update to VS Code. Ninja continues to work correctly in the Mac OS terminal.

### Expected:

Successful build messages from Ninja are overwritten on a single-line.

### Apparent Behavior:

All Ninja messages are output across multiple lines.

### Platform and Versions

[[For issues, fill out the following. Otherwise delete this section.]]

- **Operating System**: Mac
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.22.2
- **CMake Tools Extension Version**: 0.11
- **Compiler/Toolchain**: Clang

**Comment by Randshot** [comment]
@spinicist CMT parses the output from CMake and then prints that to the VSCode output panel. If you are talking about the VSCode integrated terminal, then that has nothing to do with CMT.

**Comment by Randshot** [comment]
Like I previously mentioned, CMT reads the stdout stream from the CMake instance and then prints it out to the output panel. I don't see a quick/easy fix for this either.

**Comment by spinicist** [comment]
Did something change with that in the latest version? I could have sworn it was working as expected last week when I was still on 0.10. My memory is not great these days though.

**Comment by Randshot** [comment]
We did a major refactor between 0.10 and 0.11, which is why it took so long. I don't know how it worked in the previous versions though.

**Comment by vector-of-bool** [comment]
Could you paste/screenshot the contents of your build log that look wrong? I'm a bit confused.

**Comment by spinicist** [comment]
Sure - sorry, didn't think of cut and pasting the exact output.

Output from hitting `Cmd+B`, i.e. with CMake Tools:
```
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /Users/Tobias/Code/QUIT/cmake_build --config Release --target all -- -j 3
[build] [1/3] Generating version_depend_dummy
[build] -- Found Git: /usr/bin/git (found version "2.13.6 (Apple Git-96)") 
[build] -- Version: v2.0.0-9-ga8038bb-dirty
[build] [2/3] Building CXX object Source/Relaxometry/CMakeFiles/qidespot1.dir/qidespot1.cpp.o
[build] [3/3] Linking CXX executable Source/Relaxometry/qidespot1
[build] Build finished with exit code 0
```

The final result from invoking `/usr/local/bin/cmake --build /Users/Tobias/Code/QUIT/cmake_build --config Release --target all -- -j 3` in the integrated Terminal:

```
[1/3] Generating version_depend_dummy
-- Found Git: /usr/bin/git (found version "2.13.6 (Apple Git-96)")
-- Version: v2.0.0-9-ga8038bb-dirty
[3/3] Linking CXX executable Source/Relaxometry/qidespot1
``` 

Note that in this version you don't see the `[2/3] Building CXX object Source/Relaxometry/CMakeFiles/qidespot1.dir/qidespot1.cpp.o` line - it was printed, then overwritten by `[3/3] Linking CXX executable Source/Relaxometry/qidespot1`. For this trivial example it's not such a big problem, but my full build currently has 121 steps!

**Comment by vector-of-bool** [comment]
Ahh... I see. This isn't a regression from a prior CMake Tools version. The reason this happens is that Ninja doesn't clear the output line and re-write it unless it detects stdout to be a TTY.

I've been thinking about having builds run in the integrated terminal instead of the output channel, but haven't gotten around to implementing it or thinking about the design.

**Comment by vector-of-bool** [comment]
The output channel API from VSCode isn't that good. It needs to get some love, so I'm not sure I'd be able to clear individual lines, but I can look into it.

**Comment by spinicist** [comment]
I'm tidying up my open issues and have learned to live with this one.
