### ISSUE TITLE
Why CMAKE_BUILD_TYPE is always Debug?

### ISSUE THREAD

**Issue by zchrissirhcz** [microsoft/vscode-cmake-tools#3821]
### Brief Issue Summary

`CMake: Configure` always uses `-DCMAKE_BUILD_TYPE:STRING=Debug` even if I delete `CMAKE_BUILD_TYPE` or set `CMAKE_BUILD_TYPE=Release` in setting of CMake Tools extension, and I've already set environment variable: `export CMAKE_BUILD_TYPE=Release`

### CMake Tools Diagnostics

```shell
{
  "os": "darwin",
  "vscodeVersion": "1.90.0",
  "cmtVersion": "1.18.41",
  "configurations": [
    {
      "folder": "/Users/zz/work/cppsober/kcv",
      "cmakeVersion": "3.29.5",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/Library/Developer/CommandLineTools/usr/bin/cc",
        "CXX": "/Library/Developer/CommandLineTools/usr/bin/c++"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 7,
    "executablesCount": 1,
    "librariesCount": 3,
    "targets": [
      {
        "name": "birch-autotimer-update",
        "type": "UTILITY"
      },
      {
        "name": "imgui",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "konacv",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "test",
        "type": "EXECUTABLE"
      },
      {
        "name": "glfw",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "update_mappings",
        "type": "UTILITY"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "never",
      "configureOnOpen": false
    }
  ]
}
```

**Comment by Luvideria** [comment]
I would like to add that I can't find the correct way to simply add more build types. The CMakeFiles I use have for instance ServRel or ToolRel as build types, which I can't access at all.

**Comment by Evelyn-001** [comment]
Thanks for reporting this issue. Today we try to repro using a simple CMake Project, but we didn't repro it. We find that if we set the "CMAKE_BUILD_TYPE": "Release" in related configuration, and the **-DCMAKE_BUILD_TYPE=Release** displays on CMake output when configure the project. For further investigation, could you please share us a demo project with clear repro steps? Wea re looking forward to hearing from you. Thanks.

ENV:
VS code version: 1.90.0
CMake Extension version: 1.18.42

Please see the verified results as below.
![0613VScode](https://github.com/microsoft/vscode-cmake-tools/assets/124944537/a04f3ff8-0fac-44c4-83f4-8fd358a5622e)

**Comment by zchrissirhcz** [comment]
@Evelyn-001 Hi, thanks for the reply. This gif looks okay, and maybe I need a little time to learn to use CMakePresets.json. Actually I begin to use CMake since about CMake 3.12 or before that.

My previous trial was on a Apple M1 machine, which is not available now.
I'm currently using a Windows 11, x86-64 machine, and I can reproduce it.

**I guess Ninja as generator is the key to reproduce**.

Here is the detail:

- C/C++ compiler: Visual Studio 2022 (17.10.1)
- CMake:  3.29.5 (manually installed, instead of the VS2022 installed one)
- Build Tool: Ninja 1.12.1 (manually installed, instead of the VS2022 installed one)

VSCode: Version: 1.90.0
VSCode CMake Tools plugin version: v1.18.42
VSCode User setting.json
```json
{
    "cmake.generator": "Ninja",
    "cmake.pinnedCommands": [
        "workbench.action.tasks.configureTaskRunner",
        "workbench.action.tasks.runTask"
    ],
}
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.29)
project(x)
message(STATUS "[x] CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")
add_executable(x x.c)
```

x.c:
```c
int main() {}
```

CMake Configure output by `CMake: Configure` in VSCode command palette:
![image](https://github.com/microsoft/vscode-cmake-tools/assets/3831847/ef09d998-0416-4dfb-99ea-37ac94690f71)


Do I set `CMAKE_BUILD_TYPE` environment variable? No
![image](https://github.com/microsoft/vscode-cmake-tools/assets/3831847/188f1b81-3ae6-4b05-b6cd-1f1711398243)

**Comment by Evelyn-001** [comment]
[](url)Thanks for your reply. According to your comment, we try to repro it using above demo files, please see the verified results as below. Is it your issue? Thanks.
ENV:
VS code version: 1.90.0
CMake Extension version: 1.18.42
![061404](https://github.com/microsoft/vscode-cmake-tools/assets/124944537/1b80d526-7837-4b98-ab9b-391739f02862)

**Comment by zchrissirhcz** [comment]
> Thanks for your reply. According to your comment, we try to repro it using above demo files, please see the verified results as below. Is it your issue? Thanks. ENV: VS code version: 1.90.0 CMake Extension version: 1.18.42 ![061404](https://private-user-images.githubusercontent.com/124944537/339677189-1b80d526-7837-4b98-ab9b-391739f02862.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzE5MjgsIm5iZiI6MTcxODM3MTYyOCwicGF0aCI6Ii8xMjQ5NDQ1MzcvMzM5Njc3MTg5LTFiODBkNTI2LTc4MzctNGI5OC1hYjliLTM5MTczOWYwMjg2Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzI3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTk2ZmFjNTFlYTU4NGU0MjEyZjVjZjY0ZjUxYTJkYzM1ZWEzOWI3NmM2YTg3MWJkNGZhYmNlZGZkZTUxMGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0cJrOd9ir402VHwQNknnKQfgMKj_OBA1bIGEswDlQnM) [ ![061404](https://private-user-images.githubusercontent.com/124944537/339677189-1b80d526-7837-4b98-ab9b-391739f02862.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzE5MjgsIm5iZiI6MTcxODM3MTYyOCwicGF0aCI6Ii8xMjQ5NDQ1MzcvMzM5Njc3MTg5LTFiODBkNTI2LTc4MzctNGI5OC1hYjliLTM5MTczOWYwMjg2Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzI3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTk2ZmFjNTFlYTU4NGU0MjEyZjVjZjY0ZjUxYTJkYzM1ZWEzOWI3NmM2YTg3MWJkNGZhYmNlZGZkZTUxMGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0cJrOd9ir402VHwQNknnKQfgMKj_OBA1bIGEswDlQnM) ](https://private-user-images.githubusercontent.com/124944537/339677189-1b80d526-7837-4b98-ab9b-391739f02862.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzE5MjgsIm5iZiI6MTcxODM3MTYyOCwicGF0aCI6Ii8xMjQ5NDQ1MzcvMzM5Njc3MTg5LTFiODBkNTI2LTc4MzctNGI5OC1hYjliLTM5MTczOWYwMjg2Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzI3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTk2ZmFjNTFlYTU4NGU0MjEyZjVjZjY0ZjUxYTJkYzM1ZWEzOWI3NmM2YTg3MWJkNGZhYmNlZGZkZTUxMGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0cJrOd9ir402VHwQNknnKQfgMKj_OBA1bIGEswDlQnM) [ ](https://private-user-images.githubusercontent.com/124944537/339677189-1b80d526-7837-4b98-ab9b-391739f02862.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzE5MjgsIm5iZiI6MTcxODM3MTYyOCwicGF0aCI6Ii8xMjQ5NDQ1MzcvMzM5Njc3MTg5LTFiODBkNTI2LTc4MzctNGI5OC1hYjliLTM5MTczOWYwMjg2Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMzI3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTk2ZmFjNTFlYTU4NGU0MjEyZjVjZjY0ZjUxYTJkYzM1ZWEzOWI3NmM2YTg3MWJkNGZhYmNlZGZkZTUxMGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0cJrOd9ir402VHwQNknnKQfgMKj_OBA1bIGEswDlQnM)

Thanks for the reply. The verified result you provided in the gif is nearly what I thing the issue is. And to be precise, I think there are two sub-issues:
1. When the C/C++ compiler is `cl.exe`, if specified Ninja as generator in settings.json, the bug appears
2. When the C/C++ compiler is `Clang`, including `Clang.exe` from Visual Studio (for Windows), and `AppleClang` (for macOS), the bug appears

**Comment by Evelyn-001** [comment]
This issue reproduces with below Conditions:

1. When the C/C++ compiler is cl.exe, if specified Ninja as generator in settings.json, the bug appears
2. When the C/C++ compiler is Clang, the bug appears

**ENV**：
VSCode version: 1.90.1
CMake version: 3.28.3-msvc11
Ninja version: 1.11.0
VSCode CMake Tools extension version: v1.18.42

![image](https://github.com/microsoft/vscode-cmake-tools/assets/124944537/3669ff2d-d2b6-42da-9cbf-9847fceb0e58)
![339677189-1b80d526-7837-4b98-ab9b-391739f02862](https://github.com/microsoft/vscode-cmake-tools/assets/124944537/43684d48-3ce5-47eb-827f-2090965c786d)

**Comment by Evelyn-001** [comment]
@gcampbell-msft, if user do not explicitly specify a value for CMAKE_BUILD_TYPE when executing CMake, or do not explicitly set it before building, will CMake choose a default CMAKE_BUILD_TYPE of Debug? Coud you please help look at this issue? Thanks in advance.

**Comment by gcampbell-msft** [comment]
@Evelyn-001 Yes, if there is no CMAKE_BUILD_TYPE specified, then the default is Debug.

**Comment by gcampbell-msft** [comment]
@zchrissirhcz @Evelyn-001 Let me take some time to investigate, I actually believe I may have been wrong about our default, let me look more closely into it and get you the full understanding and context. Thanks!

**Comment by gcampbell-msft** [comment]
@zchrissirhcz Okay I've investigated closer and we do in fact default to "Debug". What are you expecting the default to be?

**Comment by gcampbell-msft** [comment]
@zchrissirhcz Follow up to help us understand your scenario better, is there a reason that you don't want to explicitly set the build type?

**Comment by zchrissirhcz** [comment]
I think `CMAKE_BUILD_TYPE` should be set by user, and a default value provided by "VSCode CMake Tools" is not required. Consider this case: a cross-platform C/C++ project, in its `CMakeLists.txt`, automatically detect and set value for `CMAKE_BUILD_TYPE`:

```cmake
cmake_minimum_required(VERSION 3.5)
projet(x)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Choose the type of build." FORCE)
endif()
message(STATUS "[x] CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")
```

When invoked in command like:
```bash
cmake -S . -B build
```
it will print `[x] CMAKE_BUILD_TYPE: Release`

But when invoked in VSCode CMake Tools' "cmake configure", it prints `[x] CMAKE_BUILD_TYPE: Debug`.

I see this usage in:
- 1. the ncnn project: https://github.com/Tencent/ncnn/blob/master/CMakeLists.txt#L26-L28
- 2. the 3rd search result in google with keywords "default value for cmake_build_type": https://www.kitware.com/cmake-and-the-default-build-type/

@gcampbell-msft @Evelyn-001

**Comment by gcampbell-msft** [comment]
@zchrissirhcz Thanks for all of this information, we will definitely assess this on the backlog and investigate. Again, thanks!

**Comment by Evelyn-001** [comment]
Verify this issue has been fixed. Thanks.
**ENV:**
VS code: 1.91.1
CMake Tools Extension: v1.19.19 (pre-release)
![071201](https://github.com/user-attachments/assets/467a8106-981d-4881-84ff-9d8404230887)

**Comment by smp73** [comment]
> ### Brief Issue Summary
> `CMake: Configure` always uses `-DCMAKE_BUILD_TYPE:STRING=Debug` even if I delete `CMAKE_BUILD_TYPE` or set `CMAKE_BUILD_TYPE=Release` in setting of CMake Tools extension, and I've already set environment variable: `export CMAKE_BUILD_TYPE=Release`
> 
> ### CMake Tools Diagnostics
> ```shell
> {
>   "os": "darwin",
>   "vscodeVersion": "1.90.0",
>   "cmtVersion": "1.18.41",
>   "configurations": [
>     {
>       "folder": "/Users/zz/work/cppsober/kcv",
>       "cmakeVersion": "3.29.5",
>       "configured": true,
>       "generator": "Ninja",
>       "usesPresets": false,
>       "compilers": {
>         "C": "/Library/Developer/CommandLineTools/usr/bin/cc",
>         "CXX": "/Library/Developer/CommandLineTools/usr/bin/c++"
>       }
>     }
>   ],
>   "cpptoolsIntegration": {
>     "isReady": true,
>     "hasCodeModel": true,
>     "activeBuildType": "Debug",
>     "buildTypesSeen": [
>       "Debug"
>     ],
>     "requests": [],
>     "responses": [],
>     "partialMatches": [],
>     "targetCount": 7,
>     "executablesCount": 1,
>     "librariesCount": 3,
>     "targets": [
>       {
>         "name": "birch-autotimer-update",
>         "type": "UTILITY"
>       },
>       {
>         "name": "imgui",
>         "type": "STATIC_LIBRARY"
>       },
>       {
>         "name": "konacv",
>         "type": "STATIC_LIBRARY"
>       },
>       {
>         "name": "test",
>         "type": "EXECUTABLE"
>       },
>       {
>         "name": "glfw",
>         "type": "STATIC_LIBRARY"
>       },
>       {
>         "name": "update_mappings",
>         "type": "UTILITY"
>       }
>     ]
>   },
>   "settings": [
>     {
>       "communicationMode": "automatic",
>       "useCMakePresets": "never",
>       "configureOnOpen": false
>     }
>   ]
> }
> ```
> 
> ### Debug Log
> _No response_
> 
> ### Additional Information
> _No response_

12bc6cdb375f9688ba2eff535c36b26dbbaff710

**Comment by Evelyn-001** [comment]
@smp73, thanks for your reply. Do you want to use -DCMAKE_BUILD_TYPE:STRING=Release ? you need to add Adding "configuration": "release" in CMakePresets.json file. Please refer to this [comment](https://github.com/microsoft/vscode-cmake-tools/issues/3721#issuecomment-2078883126) in that issue. Thanks.
