### ISSUE TITLE
separate folder for each cmake kit

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-cmake-tools#383]
### Brief Issue Summary

Can you add the ability to set a build folder for each cmake kit

### Expected

1. Switch to kit A
2. Full Build
3. Switch to kit B
4. Full Build
5. Switch to kit A
6. Incremental Build from (2.)

### Apparent Behavior:

1. Switch to kit A
2. Full Build
3. Switch to kit B
4. Full Build
5. Switch to kit A
6. Full Build

**Comment by Randshot** [comment]
@KUGA2 You can use variable substitution when defining your build directory in the settings.json.
E.g.: `"cmake.buildDirectory": "build_${generator}/${buildType}"`

**Comment by KUGA2** [comment]
But this is not the kit (toolchain) nor the target when cross compiling

**Comment by Randshot** [comment]
Well.., you are right. We could certainly make the current kit name available via variable substitution.

**Comment by vector-of-bool** [comment]
This will need a test for validation. I'm curious what will happen when we change directories on a Kit change. It should be possible, especially since we already delete the CMake config on a kit change.

**Comment by mika-fischer** [comment]
This should be fixed, no? https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#variable-substitution

**Comment by KUGA2** [comment]
Yes, this is resolved with the addition of `${buildKit}`.
