### ISSUE TITLE
CMake Tools cause probleme

### ISSUE THREAD

**Issue by nattyrootman** [microsoft/vscode-cmake-tools#3831]
Type: <b>Bug</b>

extension host terminated unexpectedly 3 times within the last 5 minutes.

Extension version: 1.18.42
VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.94GB (1.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Yingzi1234** [comment]
@nattyrootman Thank you for your github issue! To solve your problem can you try to follow the steps below?
1. Update your CMake tools version or re-install it
2. Update your operating system and ensure that both the operating system and VS Code itself are up to date
3. Disable other extensions: Sometimes other running extensions may conflict with the current extension and cause unexpected termination. Try disabling other extensions and re-enabling them one by one to see if there is any improvement

Could you provide us with extended logs if none of the above actions fix it?
Open the extended Output or Log panel in VS Code to see if there are any termination-related error or warning messages. These messages can often provide key clues to help determine the problem

Please feel free if you have any questions!

**Comment by gcampbell-msft** [comment]
@nattyrootman How do we know that it is the CMake Tools extension that is causing this? Is there any stack that you can provide?
