### ISSUE TITLE
I dont now what is this error

### ISSUE THREAD

**Issue by ArashGamer23** [microsoft/vscode-cmake-tools#3834]
### Brief Issue Summary

it sais Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable.

### Debug Log

```shell
[proc] The command: ninja --version failed with error: Error: spawn ninja ENOENT
[proc] The command: ninja-build --version failed with error: Error: spawn ninja-build ENOENT
[proc] The command: make --version failed with error: Error: spawn make ENOENT
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[proc] The command: ninja --version failed with error: Error: spawn ninja ENOENT
[proc] The command: ninja-build --version failed with error: Error: spawn ninja-build ENOENT
[proc] The command: make --version failed with error: Error: spawn make ENOENT
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[main] Configuring project: DDNetPP
```

**Comment by v-frankwang** [comment]
@ArashGamer23 Thank you for reporting this issue. Regarding this issue, we tried to reproduce it using a simple demo project but were not able to reproduce it, in order to investigate further, could you please provide us with a simple project that can reproduce this issue, we look forward to your feedback.

**Comment by gcampbell-msft** [comment]
@ArashGamer23 Also, could you please run the "CMake Tools: Diagnostics" command? @v-frankwang This is a step that is very helpful for any issues where we need more understanding. 👍

**Comment by OrkunTokdemir** [comment]
@gcampbell-msft I have encountered this problem with the below versions.

To reproduce the problem, copy the below kit into your `cmake-tools-kits.json` and try to build it. It generatres the below error. I think the problem is the resolution of `${env:PATH}`.

This problem only happens on `Windows`

It doesn't occur in `v1.18.44`

```
[
  {
    "name": "Visual Studio Build Tools 2019 Release - amd64",
    "visualStudio": "3db5ba35",
    "visualStudioArchitecture": "x64",
    "isTrusted": true,
    "environmentVariables": {
      "PATH": "${env:PATH}"
    },
    "preferredGenerator": {
      "name": "Ninja Multi-Config",
      "platform": "x64",
      "toolset": "host=x64"
    }
  }
]
```

The error
```
[proc] The command: ninja --version failed with error: Error: spawn ninja ENOENT
[proc] The command: ninja-build --version failed with error: Error: spawn ninja-build ENOENT
[proc] The command: ninja --version failed with error: Error: spawn ninja ENOENT
[proc] The command: ninja-build --version failed with error: Error: spawn ninja-build ENOENT
[proc] The command: ninja --version failed with error: Error: spawn ninja ENOENT
[proc] The command: ninja-build --version failed with error: Error: spawn ninja-build ENOENT
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
```
![image](https://github.com/user-attachments/assets/c35bc9e9-b811-4518-a75d-b2c219943cda)


`Log Diagnostic`

```
{
  "os": "win32",
  "vscodeVersion": "1.92.1",
  "cmtVersion": "1.19.39",
  "configurations": [
    {
      "folder": "c:\\Users\\ilhan\\OneDrive\\Desktop\\playground\\cpp_playground",
      "cmakeVersion": "unknown",
      "configured": false,
      "generator": "unknown",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}

```

**Comment by gcampbell-msft** [comment]
A couple of things: 
1. If you're referencing `env` from the `environmentVariables`, then it's going to hit circular reference. I would suggest doing `$penv{PATH}`. 
2. Do you still have that Visual Studio installation installed?

**Comment by OrkunTokdemir** [comment]
> If you're referencing env from the environmentVariables, then it's going to hit circular reference. I would suggest doing $penv{PATH}.

I will try that.

> Do you still have that Visual Studio installation installed?

Yes. It works normally.

**Comment by OrkunTokdemir** [comment]
@gcampbell-msft  
> If you're referencing env from the environmentVariables, then it's going to hit circular reference. I would suggest doing $penv{PATH}

This fixed another problem we encountered but it didn't fix the problem I shared, unfortunately.

**Comment by OrkunTokdemir** [comment]
I didn't bisect but this MR might break it. 

https://github.com/microsoft/vscode-cmake-tools/pull/3887

**Comment by gcampbell-msft** [comment]
@OrkunTokdemir I don't have that specific version of Visual Studio installed, but when I modified the "visualStudio" entry to refer to a valid VS install, I don't see this same issue. Is it possible that the value of your Visual Studio entry has changed? 

@moyo1997 @v-frankwang @Yingzi1234  FYI

**Comment by gcampbell-msft** [comment]
@ArashGamer23 For your specific issue, could you provide a repro like @OrkunTokdemir did? Or is it the same issue?

**Comment by OrkunTokdemir** [comment]
> @OrkunTokdemir I don't have that specific version of Visual Studio installed, but when I modified the "visualStudio" entry to refer to a valid VS install, I don't see this same issue. Is it possible that the value of your Visual Studio entry has changed?
> 
> @moyo1997 @v-frankwang @Yingzi1234 FYI

No need to specify any specific version. It happens with any Visual Studio kit.

**Comment by OrkunTokdemir** [comment]
@gcampbell-msft  I'm further investigating because I try to use `penv` on all platforms. It didn't work on Linux. I guess some other things are broken too. Does `penv` work on Linux? For example I try the below kit on Linux and I get the same error message. Or I'm missing something.

```json
[
  {
    "name": "workspace kit",
    "compilers": {
      "C": "/usr/lib/ccache/clang",
      "CXX": "/usr/lib/ccache/clang++"
    },
    "environmentVariables": {
      "PATH": "${penv:PATH}"
    },
    "isTrusted": true,
    "preferredGenerator": {
      "name": "Ninja Multi-Config"
    }
  }
]
```

**Comment by OrkunTokdemir** [comment]
@gcampbell-msft https://github.com/microsoft/vscode-cmake-tools/pull/3887 breaks expansion of `${env:PATH}` for Visual Studio kits and `cppvsdbg` in both `cmake-kits.json` and `launch.json`

**Comment by gcampbell-msft** [comment]
@OrkunTokdemir Could you provide a repro for the `launch.json`?

**Comment by OrkunTokdemir** [comment]
@gcampbell-msft Here is the launch config I use. 

`${command:qt-official.kitDirectory}` returns the selected Qt kit path. And, I add `bin` to reach the path of `dll` files . You can use any other `dll` folder instead. Also, I use a Visual Studio kit to build the executable.
```json
{
    "configurations": [
    {
        "name": "Debug Qt Application with Visual Studio Debugger",
        "type": "cppvsdbg",
        "request": "launch",
        "program": "${command:cmake.launchTargetPath}",
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "visualizerFile": "${command:qt-official.natvis}",
        "windows": {
            "environment": [
                {
                    "name": "PATH",
                    "value": "${env:PATH};${command:qt-official.kitDirectory}${/}bin"
                }
            ]
        }
    }
    ]
}
```

**Comment by OrkunTokdemir** [comment]
@gcampbell-msft I tried a little bit more. I think the expansion of `${env:PATH}` in `launch.json` might be not broken.
