### ISSUE TITLE
usepresets context is not set after manually creating a cmakepresets.json

### ISSUE THREAD

**Issue by qarni** [microsoft/vscode-cmake-tools#3854]
### Brief Issue Summary

usepresets context is not set after manually creating a cmakepresets.json, so the Select Configure Preset and Add Configure Preset options are not available in the command palette.

Might need to add/update a file watcher to update the active project when changes are made to a cmakepreset.json file. Also maybe for cmakeuesrpresets.json as well.

Related to #3734.

**Comment by Yingzi1234** [comment]
@qarni Thanks for asking the question on Github! **Its not a problem**, you need to re-open the vscode and re-open this file, then search again and the command will be found.
Please feel free if you have any concerns!

**Comment by qarni** [comment]
Thanks @Yingzi1234. The team would actually like to have this functionality without a reload and I’ll be working on a fix later on. :)

**Comment by hypdeb** [comment]
It seems that in general changes to CMakePresets.json files are not taken into account, or at least not as consistently as I would like. Reloading VS Code is fast enough usually, but it can be slow when working in a dev container for example. I think the file watcher @qarni is mentioning could solve that issue.

**Comment by qarni** [comment]
Hi @hypdeb! Could you provide a description/ minimal repro of the other issues you're seeing with presets files?

**Comment by hypdeb** [comment]
I basically have the same issue as you. If the file is created after the window is loaded, presets are not loaded and I cannot select them.

I also mentioned changes are not taken into account in general, but this I cannot reproduce. It could be another quirk of my environment.

**Comment by Yingzi1234** [comment]
@qarni This issue has been fixed on latest CMake tools version v0.19.35(pre-release), you can get the details below. Thank you!
ENV:
VSCode version: v1.91.1(system setup)
CMake tools version: 0.19.35(pre-release)
C/C++ version: v1.21.5
C/C++ Extension pack version: v1.3.0
![3854](https://github.com/user-attachments/assets/cd438734-78fa-4f08-b0db-67b3788b7bad)
