### ISSUE TITLE
[Loc]Setting's description not localized for "cmake.ctest.testSuiteDelimiter"

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-cmake-tools#3863]
### Brief Issue Summary

**Environment**:
VSCode 1.90.1+ CMake Tools v1.19.13(pre-release)

**More info**:
Repro Language: All loc languages
Repro platform: Windows, Linux, Mac

**Repro steps**:
1. Open VScode and change the display language to CHS
2. Open setting page and input “CMakeTools”, check the setting's description localization status for "cmake.ctest.testSuiteDelimiter"

**Expected result**:
Description localized for all settings

**Actual result**:
Description not localized for "cmake.ctest.testSuiteDelimiter"
![setting_notloc](https://github.com/microsoft/vscode-cmake-tools/assets/37648162/02855768-685c-4667-b3e4-bd5e55faaf14)

**Comment by snehara99** [comment]
this has been fixed in a recent loc pr

**Comment by PhoebeTf** [comment]
Verified with CMake Tools v1.19.34 (pre-release), this issue has been fixed.
<img width="605" alt="image" src="https://github.com/user-attachments/assets/ea8fb02c-87f5-44e0-9b67-19bb9b9ea768">
