### ISSUE TITLE
macros for penv/env not expanded when cache variables for cmake(c/cxx)compilers are included in configure preset

### ISSUE THREAD

**Issue by qarni** [microsoft/vscode-cmake-tools#3870]
### Brief Issue Summary

$penv{PATH}/$env{PATH} are not expanded when cache variables for "CMAKE_C_COMPILER": "cl.exe", "CMAKE_CXX_COMPILER": "cl.exe" are included in configure preset. Likely they are overwritten by our vs dev environment magic.

Repro configure preset:

>  {
            "name": "preset",
            "displayName": "Visual Studio Enterprise 2022 IntPreview - amd64",
            "description": "Using compilers for Visual Studio 17 2022 (x64 architecture)",
            "generator": "Visual Studio 17 2022",
            "toolset": "host=x64",
            "architecture": "x64",
            "binaryDir": "${sourceDir}/out/build",
            "environment": {
                "PATH": "HELLOTHISISBAD;$penv{PATH}"
            },
            "cacheVariables": {
                "CMAKE_INSTALL_PREFIX": "${sourceDir}/out/install/${presetName}",
                "CMAKE_C_COMPILER": "cl.exe",
                "CMAKE_CXX_COMPILER": "cl.exe"
            }
        }

**Comment by v-frankwang** [comment]
@qarni I used a simple project to reproduce the problem, using message in the CMakeList.txt file to print the value of the PATH, and it would not show the value of the macro. Does this reproduce your problem?

Actual result：
![image](https://github.com/microsoft/vscode-cmake-tools/assets/160998958/06a32367-8256-41b0-87e5-843a7a6de5c6)
