### ISSUE TITLE
[Loc] Property’s tooltip info in file "CMakePresets.json" is not localized 

### ISSUE THREAD

**Issue by PhoebeTf** [microsoft/vscode-cmake-tools#3872]
### Brief Issue Summary

**Environment**:
VSCode 1.90.1+ CMake Tools v1.19.13(pre-release)

**More info:**
Repro Language: All loc languages

**Repro steps**:
1. Open VScode and change the display language to CHS
2. Download and unzip [Version Validation](https://microsoft.sharepoint.com/teams/DD_VC/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FDD%5FVC%2FShared%20Documents%2FCross%20Platform%2FCMake%2FTest%20CMake%20Projects%2FVersion%20Validation&p=true&ga=1)
3. Open above project with VS Code.
4. Open CMakePresets.json file
5. Focus on the property and check the tooltip info status

**Expected result**:
Tooltip info localized _(Tooltip info localized in VS and screenshot as below)_
![Tooltip_VS](https://github.com/microsoft/vscode-cmake-tools/assets/37648162/323de690-dc45-4a41-9c25-0dfff8d63feb)

**Actual result**:
Tooltip info for all property are not localized
![Tooltip_VSCode](https://github.com/microsoft/vscode-cmake-tools/assets/37648162/e526c0a3-413e-4133-93d6-29cfe8227c38)

**Comment by PhoebeTf** [comment]
Verified with CMake Tools v1.19.35 (pre-release), this issue has been fixed.
![image](https://github.com/user-attachments/assets/3fe31de8-6d71-458b-ab41-af71fd85dfe5)

**Comment by v-frankwang** [comment]
We verified the issue on CMake tools: v1.19.45 and it has been fixed.

ENV：
CMake Tools:v1.19.45
vscode: 1.92.2

Actual result:
![image](https://github.com/user-attachments/assets/cd6b979c-ef9d-4c73-a9a7-5a2a78432fae)
