### ISSUE TITLE
"CMake: build" is repeated twice in the list

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-cmake-tools#3882]
### Brief Issue Summary

**More info:** 
This issue is reproduced on Windows, Linux, and Mac platforms

**Repro steps:**

1. Add a file named main.cpp with the following content: 

```
#include <iostream> 
auto main() -> int { std::cout << "hello world" << std::endl; }
```

 
2. Add a file named CMakeLists.txt with the following content:
```
cmake_minimum_required(VERSION 3.5) 
project(Test)
add_executable(Test main.cpp)
```

3. Click F1 and run "Task: Configure Task" command
4. Choosing the "CMake: build"
5. Re-click "Task: configure task"
6. Check the list

**Expected result:**
All commands appear only once

**Actual result:**
"CMake: build" is repeated twice in the list
![Issue31](https://github.com/microsoft/vscode-cmake-tools/assets/101234795/c4a69b70-c690-4e91-a1a1-3dc309466226)

**Comment by gcampbell-msft** [comment]
This is expected because we provide the cmake build task by default, so when it is redefined in the launch.json, it will appear twice. Closing.
