### ISSUE TITLE
Failure to ask the user to select a kit due to erroneously not finding CMakeLists.txt

### ISSUE THREAD

**Issue by gareth-davies-img** [microsoft/vscode-cmake-tools#3901]
### Brief Issue Summary

I think the problem comes from:
https://github.com/microsoft/vscode-cmake-tools/blob/15ad70769f62b5ce902b6fd1ae27986bb958d3d0/src/extension.ts#L432

which is then used in:
https://github.com/microsoft/vscode-cmake-tools/blob/15ad70769f62b5ce902b6fd1ae27986bb958d3d0/src/extension.ts#L434C1-L441C85

So it won't ask the user to select a kit if it hasn't found `CMakeLists.txt`.

The problem I'm getting in my case is it's not finding `CMakeLists.txt` because it's in the top-level of my workspace folder. This is because the search invoked by `util.globForFileName` starts from one sub-directory down:
https://github.com/microsoft/vscode-cmake-tools/blob/15ad70769f62b5ce902b6fd1ae27986bb958d3d0/src/util.ts#L978C1-L987C2

If I change this as below then it finds my `CMakeLists.txt` fine:
```
export async function globForFileName(fileName: string, depth: number, cwd: string): Promise<boolean> {
    let starString = ".";   // start with the top-level of cwd
    for (let i = 1; i <= depth; i++) {
        if (await globWrapper(`${starString}/${fileName}`, cwd)) {
            return true;
        }
        starString += "/*";
    }
    return false;
}
```

This issue came in from v1.18.41.

Please check if my logic above seems correct. I think CMakeLists.txt being in the top-level is quite common. If the above change were made, should the depth of the search be increased to 4?

**Comment by gcampbell-msft** [comment]
@gareth-davies-img Great catch, I think the extension must have been activating due to other reasons, but I believe you are correct, I will make a PR

**Comment by v-frankwang** [comment]
We verified the issue on CMake tools: v1.19.45 and it has been fixed.

ENV：
CMake Tools:v1.19.45
vscode: 1.92.2

Actual result:
![image](https://github.com/user-attachments/assets/3211e3fd-cee7-481c-8c6b-6a4666bb2cb1)
