### ISSUE TITLE
Independent projects / CMakeLists.txt

### ISSUE THREAD

**Issue by ukoloff** [microsoft/vscode-cmake-tools#391]
Now I should have main CMakeLists.txt in workspace root.

But I have several independent folders each with its own CMakeLists.txt. 

If I open another VSCode having one of my folders as workspace root, everything is ok, but it's not convenient.

I tried to configure CMake Tools:
```json
{
  "cmake.buildDirectory": "${fileDirname}/build",
  "cmake.sourceDirectory": "${fileDirname}"
}
```
But it seems `${fileDirname}` is ignored, unlike `${workspaceFolder}`.

As I see, one can say
```
{
    "cmake.buildDirectory": "${workspaceRoot}/build.${buildType}"
}
```
so `${buildType}` is also available.

Is it possible to add support for `${fileDirname}` into plugin settings?

Or may be another way to use multiple independent projects inside single VSCode workspace?

**Comment by vector-of-bool** [comment]
There is an open ticket for multi-root workspace support. It's on the roadmap, but might be a while since the extension deals tightly with file paths and the like.

**Comment by HunterZ** [comment]
Having a similar problem I think.

I created a workspace and added multiple folders to it, where each folder contains a separate CMake project that I want to build. CMake Tools seems to only recognize the first project, and does not let me configure or build the others.

Is this forcing me to build a super project just for CMake Tools integration? I would prefer not to do this yet, as these projects come from separate git repos.

**Comment by HunterZ** [comment]
Stale bots are extremely user-hostile. Just because this has fallen off the developers' radar doesn't mean it isn't valid. Going to unsubscribe from this issue because I don't want to see this happen again.

**Comment by gcampbell-msft** [comment]
@ukoloff @HunterZ There should be support for selecting the active folder in the CMake Tools project, does this not meet your needs? If not, we should mark consider this as an improvement needed in our multi-root scenarios.

**Comment by gcampbell-msft** [comment]
@HunterZ I'm not sure I understand you r comment about user-hostile bots, but since you said that you don't care about this issue anymore, we will close it in favor of other issues that are better tracking multi-root support. 

See those items here: #1042 #4112 #2338 

Thank you
