### ISSUE TITLE
quick start causes second configure if automaticReconfigure is enabled

### ISSUE THREAD

**Issue by qarni** [microsoft/vscode-cmake-tools#3910]
One thing I noticed while testing is that line 2863 (in the new version), will technically force a second configure if the `automaticReconfigure` setting is enabled. I don't think this needs to block this PR, but it is something we should look into.

_Originally posted by @gcampbell-msft in https://github.com/microsoft/vscode-cmake-tools/pull/3853#discussion_r1662917321_

**Comment by v-frankwang** [comment]
We verified the issue on CMake tools: v1.19.45 and it has been fixed.

ENV：
CMake Tools:v1.19.45
vscode: 1.92.2

Actual result:
![image](https://github.com/user-attachments/assets/00519363-d970-48db-ba03-1bc9658b563e)
