### ISSUE TITLE
Is the cache being cleared on the first configure?

### ISSUE THREAD

**Issue by britalmeida** [microsoft/vscode-cmake-tools#392]
### Brief Issue Summary
When using CMake-Tools  and configuring for the first time, the cmake cache gets deleted.
I already had it previously configured.

Additionally, I don't know of a way to edit the cmake vars within VSCode. I use cmake-gui to do it as before, and all my configuration gets cleared and fails because of that.

### Expected:

I run Configure (for the first or any other time) and it does not delete the cache.

### Platform and Versions

- **Operating System**: Linux
- **CMake Version**: 3.11.1
- **VSCode Version**: OpenSource checkout: 1.23.0
- **CMake Tools Extension Version**: 0.11.0
- **Compiler/Toolchain**: GCC 7.3.0

**Comment by vector-of-bool** [comment]
If you set a kit, then yes: CMake Tools wipes the cache because kit changes require a clean configure. There's no reliable way to ensure that the first configure with a kit works.

The cache editor is in need of some love and fixes, indeed. How are you seeing it behave?

**Comment by britalmeida** [comment]
I already had a configured cmake and it's rather upsetting that some* of the configuration gets lost.

* I am unsure how much it was deleted. Sometimes everything is gone and others I lost some of my variables, but not all.

I did not 'change a kit' I was trying to get vscode to pickup my existing setup (this was before I updated my compiler).
It's not super bad to need to reconfigure again (I think), it's bad that it lost my settings, my paths, flags, booleans, etc).

I suggest:
1. if you need to delete the cache, always prompt the user
2. try to preserve existing settings as much as possible?


The CacheEditor always displayed something as 'you haven't run configure yet' with a button to 'configure' and 'generate'.  It always displays this for me, even now that I managed to compile and run my project again.
It would be useful to show an existing cache even before a successful configure.

For me, I am not entirely sure how I made it work, because I could only edit the variables externally and cmake-tools partially deleted them and kept failing the initial configuration because of that.
It was not super deterministic, though, and eventually it got to work.

**Comment by vector-of-bool** [comment]
Does the issue reproduce with _any_ project, or just with Blender? I'm having an itch in the back of my mind that something is going wrong with VSCode mementos. Does it re-ask you for a kit every time you start? Does it re-ask you for a variant every time you start? Does it forget what target you had selected when you restart VSCode?

All of those attributes are saved in Memento objects, and might be dropped on the floor.

**Comment by janosimas** [comment]
@britalmeida 
I have a workaround for the problem, I created an empty kit:
```
  {
    "name": "dummy",
    "compilers": {
    }
  },
```

This will not override the pre-configured compilers and won't clear you cache.

@vector-of-bool Forcing the user to set a kit is a huge drawback, I have a script to configure some projects for a new dev environment. If the user doesn't create that empty kit, every conf is lost.

**Comment by KoeMai** [comment]
@vector-of-bool Is this still an open issue or does the `__unspec` kit solve this?

**Comment by britalmeida** [comment]
It was a huge problem for me when I was trying to set it up for the very first time. I still don't know how I got past it, but I don't hit it regularly now. I haven't updated the compiler again.

Why would the cache be reset ever? I set many manual things like paths to libraries and manual defines for components to add. I never want to loose this.
If you really, really need to clear the cache, you should require user confirmation, so people can back up their configuration.

In my case, I had not changed compilers, I had a fresh install of cmake-tools and I had my project running for many years using other tools. I expected cmake-tools to just pick up the existing working configuration.


What I am asking is (if possible):
1. if you ever need to delete the cache, for whatever reason, notify the user that the cache will be lost and offer a cancel button.
2. try to pickup an existing configuration instead of keeping a 'is_configure_successful' state internally.
This makes it much nicer when other tools are used for cmake. I still can not edit my cache via your editor and therefore, I use cmake-gui externally to edit the cache, configure and generate, then I compile via command line, open vscode and try to F5 for debug   -> impossible, I need to reconfigure, even though I just did.
3. don't require a successful configuration before editing the cache in your editor, otherwise, it will never be successful :)

**Comment by vector-of-bool** [comment]
Thanks for the suggestions. I'll add a warning before deleting the cache. The trouble with honouring an existing configuration without deleting it on a kit change is that I have to be sure that modifying it won't change CMake's compilers. If I ignore it, it will emit a pertinent warning to users, so I might just not do the clear on the initial configure. That sounds like a good option.

Have you looked into using cache-initializers via the `-C` argument? It's the "official" way to store a set of cache variables permanently and revive them when necessary. Also, I'm looking to change up the cache editor now that VSCode supports webviews. It'll be a post-1.0 feature, though. Maybe a 1.1.
