### ISSUE TITLE
ninja, etc now required on the PATH?

### ISSUE THREAD

**Issue by gareth-davies-img** [microsoft/vscode-cmake-tools#3924]
### Brief Issue Summary

I think the recent https://github.com/microsoft/vscode-cmake-tools/pull/3869 means ninja, etc are now required on the PATH.

This didn't use to be the case and seems a bit contrary to offering the `cmake.cmakePath` setting, allowing cmake to be specifiable and not on the PATH.

Previously I used to have neither cmake nor ninja on the PATH, with a `settings.json` like:
```
{
    "cmake.cmakePath": "/path/to/cmake",
    "cmake.configureArgs": [
        "-DCMAKE_MAKE_PROGRAM=/path/to/ninja"
    ]
}
```
Just wanted to check if this change in behaviour is definite?

**Comment by gcampbell-msft** [comment]
@gareth-davies-img Thanks for the question, we will look into this. 

I took at the code quickly and it doesn't seem to me like the `cmake.cmakePath` is affected by the PR that you linked. It only checks for the generator on PATH, so as it stands, the change does mean that the generator needs to be on PATH. Is this something that you don't want to do? Or was it mainly `cmake.cmakePath` that you want to make sure this isn't the case for?

**Comment by gareth-davies-img** [comment]
Hi @gcampbell-msft Many thanks for looking into this.

The project I work on supplies an SDK that bundles cmake and ninja (for convenience and to guarentee version), and we also have our own VSCode extension that picks up and uses this SDK.

So far we've tried to avoid asking users to put these cmake and ninja on their PATH and have achieved this via a settings.json in each app build like:
```
{
    "cmake.cmakePath": "${command:img.sdkBuildToolsPath}/cmake",
    "cmake.configureArgs": [
        "-DCMAKE_MAKE_PROGRAM=${command:img.sdkBuildToolsPath}/ninja"
    ]
}
```
where those `img.` commands are implemented in our VSCode extension which works out the location of the SDK.

The above worked until recently but now cmake-tools is wanting the generator (ninja) to be on the PATH, which kind of breaks the above.

My mentioning of `cmake.cmakePath` was more by comparision, that cmake-tools permits this not to be on the PATH and for the path to it to be specified. So not following the same for the generator feels to me like going against this approach and breaking the purity of offering `cmake.cmakePath`.

Overall, if you guys decide the generator does now need to be on the PATH, happy to go with this and we can accommodate this in our flow, probably by asking the users to put the generator on their PATH. However, just wanted to check with you on this; I understand https://github.com/microsoft/vscode-cmake-tools/pull/3869 was necessary to satisfy the needs of https://github.com/microsoft/vscode-cmake-tools/issues/2709 but asking now for the generator to be on the PATH does break the kind of usage/assumptions I've got above.

**Comment by jophippe** [comment]
Hi @gareth-davies-img 
We decided that we don't need to check whether Ninja or Make exist on the PATH, and we only need to skip a generator if the system doesn't support it. This should still solve the original issue of the Visual Studio generator being selected on Linux and should solve your issue too. The fix will be available in the next release. Please let us know if you encounter any additional issues. Thanks for your feedback!

**Comment by jophippe** [comment]
Hello again @gareth-davies-img,
after further testing, we ran into a regression with customers that were relying on Ninja not being found on the PATH to default automatically to use Unix Makefiles instead. With this change, it would default to Ninja instead and fail to generate. After some more discussion, we decided to revert this change and require Ninja or Make on PATH to be detected, since the majority of customers will have their preferred generator on their PATH. That reversion PR #3938 has been merged and will be applied to the next release. Apologies for the inconvenience.

**Comment by gareth-davies-img** [comment]
Hi @jophippe,
No worries. Just wondering if adding something like `cmake.generatorPath` to settings might be a possibility. So when you search for generators you could search on PATH and on this. For people with their generator on the PATH, they would just leave this empty (and this would be the default). But in my case, we would fill this in to specify our path to ninja. No worries if this isn't possible, we can tell users to ensure ninja is on the PATH, but just wondering if something like this might be possible. It would be complimentary to `cmake.cmakePath`.

**Comment by jophippe** [comment]
Hi @gareth-davies-img, sorry for the late response,
If you still want this feature, I recommend you create a new issue and put [Feature Request] in the title so we can properly track this request and consider it in the future. Thanks!
