### ISSUE TITLE
Add support for CMake Presets v9

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode-cmake-tools#3946]
### Brief Issue Summary

CMake Presets version 9 is available and allows for more types of expansion in `include` field. In short, v9 supports all expansion in `include` field except for `env` and preset-specific macros like `presetName`

### Additional Information

https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

![image](https://github.com/user-attachments/assets/24ebedc5-3d5f-4625-b07e-939914a30a6a)

**Comment by Zingam** [comment]
CMake 3.31.0 upped introduced version 10, which enable cmake comments. I'd like to have that feature sooner. Please consider adding support for CMake Presets 10 too.

> "$comment": "An example CMakePresets.json file",
