### ISSUE TITLE
cmake.getLaunchTargetFilename returns nothing (again?)

### ISSUE THREAD

**Issue by emece67** [microsoft/vscode-cmake-tools#3957]
### Brief Issue Summary

Same as https://github.com/microsoft/vscode-cmake-tools/issues/1692 and apparently related to https://github.com/microsoft/vscode-cmake-tools/issues/1412 and https://github.com/microsoft/vscode-cmake-tools/issues/461 , but this time (re-)appeared in version 1.18.43. Up to 1.18.42 it worked OK.

Thanks & regards.

**Comment by gcampbell-msft** [comment]
@emece67 Have you selected your launch target? I notice that when running the "echo" task from here: https://github.com/microsoft/vscode-cmake-tools/issues/1692#issue-820225966 and modifying it to also use `${command:cmake.getLaunchTargetFilename}`, it says it can't find any and asks me to pick a launch target. However, once I've selected a launch target in the Project status view: 
![image](https://github.com/user-attachments/assets/68f360d5-afef-4910-8e46-88f4c1950324)


It works as expected: 
![image](https://github.com/user-attachments/assets/89dbea16-c3e6-4806-92aa-90ee3e49ed63)

**Comment by emece67** [comment]
Hope this helps:
![1 18 42](https://github.com/user-attachments/assets/8728c183-1847-4c75-be0f-fb0f1cfce119)
![1 18 43](https://github.com/user-attachments/assets/b86d5ae8-c651-44ca-942f-c3194a095588)

**Comment by gcampbell-msft** [comment]
@emece67 I'm not able to repro this on multiple different large test projects. Also, I've tested the most recent pre-release channel and found that this issue doesn't reproduce. Could you share a repro project?

**Comment by emece67** [comment]
Hi again:

Not in a repo, but I've prepared a minimal example.

Note that I'm working on Windows 11 with MSYS2 using clang. But python, cmake and ninja are not the MSYS2 ones, but "straight" Windows executables. Also, I'm debugging with lldb, so using CodeLLDB.

[hello.zip](https://github.com/user-attachments/files/16515144/hello.zip)

**Comment by gcampbell-msft** [comment]
@Yingzi1234 Could you assist in helping us reproduce this?

**Comment by gcampbell-msft** [comment]
@emece67 Are you able to successfully configure?

**Comment by emece67** [comment]
Yes, it both configures and builds.

**Comment by gcampbell-msft** [comment]
@emece67 Thanks for posting this issue. I've been able to track this down. There was an issue created here: #3541, that was fixed in this way: #3764. 

Could you try to workaround this by using a different build directory? Also, what machine are you working on? My thoughts right now are that the PR that was merged may be a fix for only Linux scenarios.

**Comment by emece67** [comment]
I think you're right. Changing paths from `${sourceDir}/~build/${presetName}` to `${sourceDir}/.build/${presetName}` or `${sourceDir}/build/${presetName}`fixed it.

I'm working in Windows 11, where paths such as `${sourceDir}/~build/${presetName}` are perfectly valid (in my systems, paths starting with `~` are not synced, thus my insistance on using `~`).

**Comment by gcampbell-msft** [comment]
@emece67 I would agree, I think we'll insert a quick fix where we only do that adjustment in linux and/or mac. Thanks for the issue

**Comment by v-frankwang** [comment]
We verified the issue on CMake tools: v1.19.45 and it has been fixed.

ENV：
CMake Tools:v1.19.45
vscode: 1.92.2

Actual result:
![image](https://github.com/user-attachments/assets/0c19a8d3-367f-4a16-9570-a9e30ba4f192)
