### ISSUE TITLE
duplicate launch/debug button

### ISSUE THREAD

**Issue by florenso** [microsoft/vscode-cmake-tools#3990]
### Brief Issue Summary

Its a bit confusing to have multiple launch/debug buttons that have different behaviour.

I see the benefit of a quick launch option but it should be disabled when there is a propper launch.json

#3204 #3989 #2999

**Comment by gcampbell-msft** [comment]
@florenso What items are you saying are duplicate? We have two separate buttons, ones that debug, and ones that simply launch.
