### ISSUE TITLE
scanForKits could look for tollchain kits in CMake cache.

### ISSUE THREAD

**Issue by schultetwin1** [microsoft/vscode-cmake-tools#400]
### Brief Issue Summary

The addition of kits broke my developer experience. I use a toolchain file to configure cmake but didn't have a cmake-kits file which listed that as an option. I've since added it but if I ever git checkout an older commit I'll have to manually recreate the cmake-kits file. Could cmake-tools scan the CMake Cache (if it exists) to see if CMAKE_TOOLCHAIN_FILE is set? If so, add that in the scanForKits call.

**Comment by vector-of-bool** [comment]
Scanning is possible, although it may need to manually be named. Is the toolchain file available at the user-local level? Can you put it in the user-local kits file?

**Comment by schultetwin1** [comment]
Unfortunately no, the toolchain file is repository specific and so probably shouldn't go in the user-local level as it will be different per clone of the repo. The main issue I'm running into is that if I have already setup cmake to build properly (whether that be with a toolchain file or just the default compiler) I also have to pick a kit for cmake-tools to work. It would be awesome if cmake-tools could autodetect your "kit" configuration by looking at the CMake cache. This would make the extension much quicker to get up and using. Only those who build different "kits" will really care about using them.
