### ISSUE TITLE
Cannot start CMake debugger in (Conan-)bootstrapped environments

### ISSUE THREAD

**Issue by rschuurmanbench** [microsoft/vscode-cmake-tools#4022]
### Brief Issue Summary

I am using Conan and CMake, and Conan will start CMake in the `def build()`, as shown here:
```python
class MyProject(ConanFile):
    #... Lots of  stuff

    def build(self):
        # Pre-build actions

        cmake = CMake(self)
        cli_args = []

        if debugging:
            cli_args += ["--debugger", "--debugger-pipe",
                         r'\\.\pipe\MyCmakeDebugger']

        cmake.configure(cli_args=cli_args)
        if self.should_build:
            cmake.build()  # This calls CMake
```

As I understand, this means that if I want to use the CMake debugger for this, I need to set vscode debug type to `external` and provide `--debugger --debugger-pipe \\.\pipe\MyCmakeDebugger` as arguments to CMake.
The conanfile looks like this:

Now I have this launch configuration:

```json
{
	"name": "Create build with CMake",
	"type": "cmake",
	"request": "launch",
	"pipeName": "\\\\.\\pipe\\MyCmakeDebugger",
	"preLaunchTask": "MyTaskThatBootstrapsTheBuild", // <-- Note that this does not work because VSCode will wait for the task to complete
	"cmakeDebugType": "external"
},
```
Now if I run this, the preLaunchTask will block, waiting for a debugger to connect.

It would be much better if VSCode just waits for the preLaunchTask to open the pipeName, and then connect to that.
If I seperate the 2 calls (run the task manually, then start the debugger), then it works perfectly fine.

**Comment by gcampbell-msft** [comment]
What version of the extension is this on?

**Comment by rschuurmanbench** [comment]
It's on v1.19.49, which is the latest available for me now.

**Comment by gcampbell-msft** [comment]
@rschuurmanbench Can you install the 1.18.44 version and let me know if it works there? Our expectation is that it still won't work there. We're trying to understand if this is a regression

**Comment by rschuurmanbench** [comment]
It's still there in 1.18.44. In both versions it's stuck here:
![image](https://github.com/user-attachments/assets/993f11a6-9c14-4602-bf50-d41afbbc7495)
What I think is happening: Conan/Python calls CMake with --debugger -> This makes CMake blocking while waiting for a debugger to attach.
Because the PreLaunchTask probably has to be exited before the debugger even tries to connect, it blocks.

**Comment by v-frankwang** [comment]
@gcampbell-msft Users have verified that this issue is still reproduced on CMake Tools:v1.18.44, can you give some advice?

**Comment by gcampbell-msft** [comment]
@v-frankwang Yes, this is a feature request. 

@rschuurmanbench I actually believe this would be a possible feature request for VS Code. We don't control how the `preLaunchTask` runs, our task only starts to execute once this is finished. Therefore, I don't believe there is anything for us to do here.
