### ISSUE TITLE
Environment variables won't load in presets file

### ISSUE THREAD

**Issue by amir-s2** [microsoft/vscode-cmake-tools#4034]
### Brief Issue Summary

After upgrading to v1.19.49 the `$env{}` won't work in `CMakePresets.json` file. Reverting version to v1.18.44 will fix the problem

**Comment by gcampbell-msft** [comment]
@amir-s2 It is very difficult to fix any issues if there is no information to investigate with. What about your env isn't working? 
 
Please provide a repro project, repro steps, and the output of the CMake Diagnostics Log command. 
Also, we've recently merged some regression fixes into the v1.20.2 pre-release channel.

**Comment by amir-s2** [comment]
I have something like this as my default preset:
```
  "configurePresets": [
    {
      "name": "default",
      "hidden": true,
      "cacheVariables": {
        "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake",
        "VCPKG_MANIFEST_NO_DEFAULT_FEATURES": "ON"
      }
    },
    ...
    ]
```

The variable `"$env{VCPKG_ROOT}` would evaluate to nothing with the latest version. It's would be loaded correctly in the last version

**Comment by amir-s2** [comment]
pre-release seems fine btw I've just checked that :))

**Comment by gcampbell-msft** [comment]
Great! I'll close this issue. We hope to patch the official version of the extension sometime next week. Thanks!

**Comment by v-frankwang** [comment]
@gcampbell-msft We verified this issue on CMake tools:v1.20.2 (pre-release) and it has been fixed.

[CMake Tools Diagnostics.txt](https://github.com/user-attachments/files/16833784/CMake.Tools.Diagnostics.txt)

Actual result：
![image](https://github.com/user-attachments/assets/20e28361-eef3-4939-ae46-906433a7b86d)
