### ISSUE TITLE
$env in cmakeExecutable in Preset not working since 1.19.49

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vscode-cmake-tools#4035]
### Brief Issue Summary

Since the newest version, our Presets do not work any more.

Configuring gives the following error message:

```
[cmakeExecutable] CMake executable not found in cache. Checking again.
[proc] Executing command: /cmake.exe --version
[proc] The command: /cmake.exe --version failed with error: Error: spawn /cmake.exe ENOENT
[proc] Executing command: /cmake.exe -E capabilities
[proc] The command: /cmake.exe -E capabilities failed with error: Error: spawn /cmake.exe ENOENT
[main] Configuring project: ---
```

As you can see, the path is incomplete. It does not resolve out preset correctly anymore. We have this line there:

```
            "cmakeExecutable": "$env{CMAKE3271}/cmake.exe"
```

We only use this setting in Windows, i am not sure if this bug appears in other OSes.

Workaround:
- Roll back to last version
- Use `penv` instead of `env`. Reading the CMake documentation, $env should also work!

(I am not adding logs here, because I would need to manually remove confidential data. If you cannot reproduce, please contact me)

**Comment by gcampbell-msft** [comment]
@KUGA2 Thanks for the issue, @staffanf thanks for testing and confirming that it is fixed in pre-release, we are aware of the issue and plan to patch the official release version this week. We agree it is high priority.
