### ISSUE TITLE
Use upper case drive letter for `cmake.buildDirectory`

### ISSUE THREAD

**Issue by kuch3n** [microsoft/vscode-cmake-tools#4036]
### Brief Issue Summary

CMake compiled unter cygwins environment doesn't handle lower case drive letter correctly. Leading to the creation of a "c" directory inside the actual build directory. 

It seems like path checks are failing (`c:/` vs. `C:/`), too. Which leads to inconsitent absolute paths, e.g.: `[ctest] profiling:/cygdrive/c/Users/.../project/test/c:/Users/.../project/build/test/gcov/out/mock_EAPP.gcda:Skip`

Problem is similar to #2665 and is fixed for `cmake.sourceDirectory`.

Specifiying a relative build direcotry doesn't work, since the process working directory is set to VSCode installation directory: ` Build files have been written to: /cygdrive/c/Users/.../AppData/Local/Programs/Microsoft VS Code/build/build`

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.92.2",
  "cmtVersion": "1.19.49",
  "configurations": [
    {
      "folder": "c:\\Users\\...\\project",
      "cmakeVersion": "3.20.0",
      "configured": true,
      "generator": "Unix Makefiles",
      "usesPresets": false,
      "compilers": {
        "C": "C:/.../cygwin64/bin/gcc.exe",
        "CXX": "CMAKE_CXX_COMPILER-NOTFOUND"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell

```

### Additional Information

see [CMake Issue 16648](https://gitlab.kitware.com/cmake/cmake/-/issues/16648)

**Comment by kuch3n** [comment]
It doesn't matter if you run cmake inside a cygwin environment or somewhere else. The above behaviour get's triggered by using a windows style full path like `[cC]:/path-to-build/`. 

Using `/cygdrive/c/path-to-build/´ doesn't trigger any problems. 

`-S` has similar problems with windows style full paths:
If you call a `return()` before a call to `project()`, you can see some errors regarding absolute paths when including local modules: `[cmake] CMake Error: RelativePath must be passed a full path to remote: C:/project-dir/cmake/Doxygen.cmake`

It would be nice to have options like:

* run cmake.exe in a given working directory
  * allow relative paths in `cmake.sourceDirectory` or `cmake.buildDirectory`
* specify cygpath to transform paths for source or build directory
* option to transform above directories with, e.g., cygpath or as extra options like `cmake.cygwinSourceDirectory` (`cygpath -a C:/windows/system32` --> `/cygdrive/c/windows/system32`)

But those seem like workarounds and it should be fixed within Cygwin's cmake

**Comment by kuch3n** [comment]
I created a topic on CMakes discussion forum: https://discourse.cmake.org/t/call-cmake-cygwin-with-windows-style-path-c/11599/1

Should this issue be closed, since this is not realy a problem of cmake-tools plugin?

**Comment by v-frankwang** [comment]
@kuch3n @gcampbell-msft I've had a similar issue before, where a folder called “c” is created after the project configuration is finished. At the time it was said that the problem was a problem with Kitware CMake.

**Comment by v-frankwang** [comment]
@gcampbell-msft I'm not sure if it's a CMake Tools extension issue, can you give some advice?

**Comment by kuch3n** [comment]
CMake devs state that windows paths aren't supported by Cygwins CMake, thus the User/IDE has to take care of valid paths, by converting those path before invoking cmake, e.g.:
`/usr/bin/cmake -S "//localhost/c$/test/" -B$(cygpath -a -u '\\localhost\c$\test\build')`

See issue on [Kitware CMake](https://gitlab.kitware.com/cmake/cmake/-/issues/26277) regarding handling windows paths with Cygwins CMake.

A user can use a script to hook between CMake Tools and the actual invocation, if #4037 gets fixed. For now only executables as hook can be used.

**Comment by kuch3n** [comment]
If you run accross this problem, don't use Cygwin's CMake within a windows environment. Use a native windows executable, like from MSys. See #4037 if you still need to run withwin a CMake environment
