### ISSUE TITLE
Time to retire the Show Options Moved notification?

### ISSUE THREAD

**Issue by sbhutch** [microsoft/vscode-cmake-tools#4039]
### Brief Issue Summary

The CMake Tools options were moved in the status bar 6+ months ago. Are there any plans to remove the pop-up notification soon? I would like to remove the "cmake.showOptionsMovedNotification" from my settings.json.

**Comment by Amy-Li03** [comment]
Verified this issue on cmake tools v1.20.52(release), Show Options Moved notification has been removed.

![Image](https://github.com/user-attachments/assets/b2dfd4b0-162d-4dc4-805e-fb5fa1b1b4e6)
