### ISSUE TITLE
Test Coverage Integration

### ISSUE THREAD

**Issue by TSonono** [microsoft/vscode-cmake-tools#4040]
### Brief Issue Summary

Should the CMake Tools extension support [Test Coverage](https://code.visualstudio.com/api/extension-guides/testing#test-coverage) which is an extension to the Testing API finalized in vscode v1.88.0?

We have an extension which revolves around a product that utilizes CMake extensively in its build system. Users of our extension are expected to also have the CMake Tools extension installed for a fuller feature set. We have now faced an obstacle when it comes to the test explorer view. The CMake Tools extension provides a "CTest" test controller that is present in the VSCode test explorer. We are trying to decide if we should push our users to rely on the CTest test explorer view or if we should provide our own (we have a test runner that can discover and run tests independently from CTest, but would preferably rely on CTest). I have added coverage support to our own test controller using the new coverage support in the VSCode Testing API, and think it is very useful.

My question is thus if there is any possibility of implementing coverage support to the CMake Tools extension directly? I'm thinking that coverage is handled differently in different build environments, which could make it hard to make something generalized. But one could for instance have configuration parameters in the CMake Tools extension which the user can set that includes say:

```jsonc
{
    cmake.preTestCoverageTask: "<task to run before a "Run Test with Coverage" execution>",
    cmake.postTestCoverageTask: "<task to run after a "Run Test with Coverage" execution>",
    cmake.lcovTraceFiles: [
        "<lcov trace files to parse when adding test coverage to files in the project. Could perhaps we wildcarded>"
    ]
}
```

If you think something like this (or some other approach that could also be thought reasonable for handling coverage), let me know. I could perhaps help out with an implementation if it makes sense to do one.

**Comment by triou-harmonicinc** [comment]
Hi, I have tested the implementation of [#4094](https://github.com/microsoft/vscode-cmake-tools/pull/4094) with v1.20.30 pre-release version.
I was able to make it work but found a few bugs :
1. The new cmake options are not recognized as valid configuration in the settings.json :![Image](https://github.com/user-attachments/assets/eee2e0af-7927-434b-8dfb-af3677a52122).
They are also not showing up in the UI. But they are taken into account when running test with coverage in the test explorer.
2. If a `cmake.preRunCoverageTarget` was specified and then the setting is removed, the value is not reset and keep being taken into account. Workaround is to specify an empty target.
3. If no `cmake.coverageInfoFiles` is specified running test with coverage never ends. I suppose it is because the extension is waiting for a file to parse.

In any case, thanks a lot for adding this feature, it will be very useful  and is more powerful than coverage gutters extension I have been using until then.

**Comment by TSonono** [comment]
Hi @triou-harmonicinc . I tried running `v1.20.30 (pre-release)`

> 1. The new cmake options are not recognized as valid configuration in the settings.json

This is strange, they are recognized for me, and when I hover my mouse cursor over them, I see the description of the option as well.

![Image](https://github.com/user-attachments/assets/83b838e0-f45d-4bc6-b053-104ee57e5f33)


> 2. If a cmake.preRunCoverageTarget was specified and then the setting is removed, the value is not reset and keep being taken into account. Workaround is to specify an empty target.

I was not able to reproduce that, when I removed it, the `preRunCoverageTarget` was not built. Can you see the log `Building the preRunCoverageTarget '<target-name>' for project <project-dir>` in the `OUTPUT` after removing the setting from `settings.json` when running the test with coverage?

> 3. If no cmake.coverageInfoFiles is specified running test with coverage never ends. I suppose it is because the extension is waiting for a file to parse.

This is also something that I'm not able to reproduce, in this case I see `No coverage info files for CMake project <project-folder>. No coverage data will be analyzed for this project.` and the test concludes.

**Comment by triou-harmonicinc** [comment]
I just double checked and after doing `Developer : Reload window` all the issues disappeared.
I guess I should have tried that first (I only installed newest extension and restart extensions until then), sorry for the bother.

**Comment by TSonono** [comment]
Glad to hear that things are working

**Comment by triou-harmonicinc** [comment]
By the way, @gcampbell-msft I suppose this issue can be closed.

**Comment by Amy-Li03** [comment]
Hi @TSonono and @gcampbell-msft 
I want to test manually this new feature on our side, for now I have done the following things:
1. Install Lcov using MSYS2
2. Install Jtest extension
3. Install Coverage Gutters extension
4. Git Clone _https://github.com/microsoft/vscode-cmake-tools_ repo
5. Open _test/end-to-end-tests/single-root-UI/project-folder_ folder in WSL
6. After cmake configure successfully, click "Run Test with Coverage" in TESTING window
7. Following error message occurs in Output window, and **lcov-base.info** and **lcov-test.info** are empty

**Is it possible that I'm missing some steps, or am I doing something wrong, and you can give me some guidance?**

![Image](https://github.com/user-attachments/assets/d2061f52-5c30-4ee2-a50c-2668805813dd)

```
[main] Building folder: /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder/build 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder/build --parallel 18 --
[build] [100%] Built target TestBuildProcess
[driver] Build completed: 00:00:00.070
[build] Build finished with exit code 0
[ctest] Building the preRunCoverageTarget for project /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder before running tests with coverage.
[main] Building folder: /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder/build init-coverage
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder/build --parallel 18 --target init-coverage --
[build] [ 50%] Reset all coverage counters to zero
[build] [ 50%] Built target reset-coverage
[build] [100%] Collecting initial coverage
[build] [100%] Built target init-coverage
[driver] Build completed: 00:00:00.667
[build] Build finished with exit code 0
[proc] Executing command: /usr/bin/ctest -C Debug -T test --output-on-failure -R ^TestBuildProcessAsTest$
[ctest]    Site: CPC-vamyl-KL0D9
[ctest]    Build name: Linux-g++
[ctest] Test project /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder/build
[ctest]     Start 1: TestBuildProcessAsTest
[ctest] 1/1 Test #1: TestBuildProcessAsTest ...........   Passed    0.00 sec
[ctest] 
[ctest] 100% tests passed, 0 tests failed out of 1
[ctest] 
[ctest] Total Test time (real) =   0.00 sec
[ctest] CTest finished with return code 0
[ctest] Building the postRunCoverageTarget 'capture-coverage' for project /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder after the tests have run with coverage.
[main] Building folder: /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder/build capture-coverage
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder/build --parallel 18 --target capture-coverage --
[build] [100%] Capture coverage data
[build] lcov: ERROR: no valid records found in tracefile lcov-base.info
[build] gmake[3]: *** [CMakeFiles/capture-coverage.dir/build.make:72: CMakeFiles/capture-coverage] Error 255
[build] gmake[2]: *** [CMakeFiles/Makefile2:947: CMakeFiles/capture-coverage.dir/all] Error 2
[build] gmake[1]: *** [CMakeFiles/Makefile2:954: CMakeFiles/capture-coverage.dir/rule] Error 2
[build] gmake: *** [Makefile:550: capture-coverage] Error 2
[proc] The command: /usr/bin/cmake --build /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder/build --parallel 18 --target capture-coverage -- exited with code: 2
[driver] Build completed: 00:00:00.395
[build] Build finished with exit code 2
[ctest] Building target postRunCoverageTarget on project in /home/amy/vscode-cmake-tools/test/end-to-end-tests/single-root-UI/project-folder failed. Skipping handling of coverage data.
```

**Comment by TSonono** [comment]
Looking at your screenshot again, it seems like you have done the configuration aspect correctly. Would you be able to share the content of the `lcov.log` and `lcov.err` files?

**Comment by Amy-Li03** [comment]
Hi @TSonono , thank you so much and thanks for explaining it in such detail!
As you said, after selected the `LinuxUser2 `preset, the test coverage worked well. Thank you again!
