### ISSUE TITLE
Merging main for 1.19 patch (#4041) to fix the issue (#4033) is failing

### ISSUE THREAD

**Issue by niimor** [microsoft/vscode-cmake-tools#4045]
### Brief Issue Summary

There is a conflict between #3869 and #4033 in the merge (#4041) . The fixes of cmakeDriver.ts around 750th line at the same time so a merge is unexpected.  Pre-release 1.20.2 is good because two fixes are applied in sequence. But release 1.19.50 is not good　  because of merge conflict.

**Comment by gcampbell-msft** [comment]
@niimor Thank you , we'll investigate. We appreciate you letting us know!

**Comment by gcampbell-msft** [comment]
@niimor Issue has been fixed.

**Comment by niimor** [comment]
thanks a lot for your quick response!!!
