### ISSUE TITLE
Ninja not found

### ISSUE THREAD

**Issue by Lioncky** [microsoft/vscode-cmake-tools#4089]
### Brief Issue Summary

*VSCode cmake/generate unable to find a build program corresponding to "Ninja"*
https://code.visualstudio.com/docs/terminal/profiles

It look like vscode has found cmake.exe by my self-define vs2022dev [command prompt](https://code.visualstudio.com/docs/terminal/profiles), 
but I have to add this
```
    "cmake.configureSettings": {
        "CMAKE_MAKE_PROGRAM": "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe"
    },
```
into `setting.json` otherwise it can't find the ninja, maybe a bug?

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.93.1",
  "cmtVersion": "1.19.52",
  "configurations": [
    {
      "folder": "e:\\@KsaProj\\android\\AndCmd",
      "cmakeVersion": "3.29.5",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

### Debug Log

```shell
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```

**Comment by Amy-Li03** [comment]
Hi @Lioncky, thank you for opening this report. Unfortunately we cannot repro this issue on a simple app, there is no error:
**_CMake was unable to find a build program corresponding to "Ninja"_** even if "CMAKE_MAKE_PROGRAM" is not set in setting.json.

If you could provide some more information about this issue, that would be great. For example, repro steps to reproduce this, or a small example of a script you're using.

**Comment by Amy-Li03** [comment]
From [Garrett Campbell](https://github.com/gcampbell-msft)'s response to a similar issue in https://github.com/microsoft/vscode-cmake-tools/issues/3443#issuecomment-2341166427:

_Please ensure that you're making use of cmake.generator or cmake.preferredGenerator settings. In the most recent extension release it is expected that if you're using the unspecified kit for example, no generator is used unless it's found on the system, so you should be sure to define the cmake.generator setting. Thanks!_

**Comment by gcampbell-msft** [comment]
I can confirm what @Amy-Li03 said above, closing this issue. THanks!
