### ISSUE TITLE
Initial work for multi-root

### ISSUE THREAD

**Issue by vector-of-bool** [microsoft/vscode-cmake-tools#409]
This is a ticket to track some refactors that need to be done to support multi-root workspaces (as well as better testing). Below are some tasks that I need to work out, and I may add more in the future.

- [ ] Don't store workspace-specific data in global variables.
- [x] No more implicit global config: It has to be workspace local, especially for variable expansion to work correctly.
- [ ] Permit multiple instances of the extension's core logic to run simultaneously.
- [ ] Refactor out GUI components from backend stuff so that the GUI components can switch between different backend instances depending on the active workspace.

If done correctly, we can simplify the acceptance testing to run properly in only a single instance of VSCode since we can just spawn a different extension instance for each test sub-project.

**Comment by vector-of-bool** [comment]
@ytimenkov you may be interested in some of this work, especially since I'm pulling apart the UI stuff from the real logic stuff.

**Comment by Zingam** [comment]
Isn't this done now?

**Comment by andreeis** [comment]
Yes, closing the report. Thanks for reminding us.
