### ISSUE TITLE
CTest Test Suite Delimiter prevents running all tests

### ISSUE THREAD

**Issue by Jesseeee** [microsoft/vscode-cmake-tools#4092]
### Brief Issue Summary

When using the test explorer and enabling the test suite delimiter, I see it correctly get split up and I can run the test suites separately, however when I click on the run of the application itself in the explorer, execute "CMake: run tests" or "Test: run all tests" it only runs a single test suite (presumably the first one it finds)

One peculiarity is that when I click on the run button to run them all, it first shows "0/49" which is the correct amount of tests and then only ends up with "15/15" from that first test suite

Example project & gif:

![ezgif-3-3c37dcf0ed](https://github.com/user-attachments/assets/5377d47c-1a32-45b2-8d4e-cae901214714)

[ctest-project.zip](https://github.com/user-attachments/files/17127238/ctest-project.zip)

**Comment by Yingzi1234** [comment]
@Jesseeee  We can't reproduce the problem based on the information you provided, can you provide us with a project that can reproduce the problem? This will go a long way in helping us to investigate this problem, thank you

**Comment by Jesseeee** [comment]
![2024-09-24 11-58-02](https://github.com/user-attachments/assets/fb5abb12-dbdc-4c97-9678-d383c039e62c)

Hello Yingzi, hopefully this gif makes the issue more clear, so when just adding the delimiter nothing is seen as run, I click start and would expect all tests to run, and only one test suite is run

**Comment by Yingzi1234** [comment]
Hi @Jesseeee , we can't reproduce your issue on latest  CMake tools version 1.20.10(pre-release), you can get the details repro steps below, please let us know if it is wrong. Thank you!

**ENV:**
C/C++: V1.21.6
CMake tools: v1.20.10(pre-release)
VSCode: 1.93.1

**Repro steps:**
1. Open this folder with VSCode
2. Click "Run tests" button
3. Open settings page and set the "CTest: Test Suite Delimiter" to "\."
4. Re-click "Run tests" button
5. Check if all the test suites can be run successfully

 **Actual result:**
All test suites can be run successfully
![4092](https://github.com/user-attachments/assets/aa8b7fb1-ec26-434d-adbe-bdf778dd9b50)

**Comment by Jesseeee** [comment]
Hello @Yingzi1234 that's not really what I'm running into, I've made a small example project because I can't share my actual project, but it demonstrates the issue well

![ezgif-3-3c37dcf0ed](https://github.com/user-attachments/assets/5377d47c-1a32-45b2-8d4e-cae901214714)

[ctest-project.zip](https://github.com/user-attachments/files/17127238/ctest-project.zip)

**Comment by Yingzi1234** [comment]
@Jesseeee Thanks for the update on this issue, we **can reproduce** the issue based on the items you provided, you can get the specific information below. 
@gcampbell-msft We were able to reproduce this issue on the latest version, and we have added the bug label to this issue, you can get the exact reproduction steps and reproduction information from below, thanks!

**ENV:**
C/C++: V1.21.6
CMake tools: v1.20.10(pre-release)
VSCode: 1.93.1

**Repro steps:**
1. Open this folder [ctest-project.zip](https://github.com/user-attachments/files/17127238/ctest-project.zip) with VSCode
2. Click "Run tests" button
3. Open settings page and set the "CTest: Test Suite Delimiter" to "\."
4. Re-click "Run tests" button
5. Check if all the test suites can be run successfully

Actual result:
Only one suite can be run successfully after setting the value of “CTest: Test Suite Delimiter”
![Repro_issue4092](https://github.com/user-attachments/assets/de82e513-4535-41fa-be4a-c0194560ca81)

**Comment by Yingzi1234** [comment]
@Jesseeee @gcampbell-msft This issue has been fixed on latest CMake tools version 1.20.24(pre-release), you can get the details below. Thank you!
![Image](https://github.com/user-attachments/assets/483ae53f-44e2-40e8-9cb6-a22621ed37e9)

**Comment by Yingzi1234** [comment]
This issue has been fixed on latest version 1.20.50, you can get the details below. Thanks!

![Image](https://github.com/user-attachments/assets/9cf13645-87f5-4a86-8afa-f1c183c0bc8d)

**Comment by gcampbell-msft** [comment]
The 1.20.50 version will be released hopefully some time next week. Thanks!
