### ISSUE TITLE
Cannot change enablement of CMake extension because of its extension kind

### ISSUE THREAD

**Issue by EeyoreLee** [microsoft/vscode-cmake-tools#4093]
### Brief Issue Summary

When I enable this extension, the vscode notice "Cannot change enablement of CMake extension because of its extension kind". But I can enable it through `enable(workspace)` knob. Is this designed this way on purpose? And what I did is just I install this extension and enable it and disable it and then it turned out like this.

**Comment by v-frankwang** [comment]
@EeyoreLee I'm very sorry, I'm not able to reproduce the problem you mentioned, could you provide the CMake tool diagnostics as well as some more detailed information? A screenshot back of the error would be better, looking forward to hearing from you!
![4093](https://github.com/user-attachments/assets/d6887746-087b-4b25-aa06-7314449fccd4)

**Comment by EeyoreLee** [comment]
@v-frankwang - hi, here seems no a output channel to get debug log. The screenshot just like 
![image](https://github.com/user-attachments/assets/b1c34cfd-a6db-4725-b79b-b4a69d259dee)

I guess the problem will be resloved after reinstall this extension. I just wonder what makes a vscode extension can enable(workspace) but can't enable.

**Comment by v-frankwang** [comment]
@EeyoreLee You can run this command: **CMake:log Diagnostics** to get CMake tool diagnostics.I'm not sure why this problem occurs because I've never encountered it before, according to what you said after reboot can solve the problem, you can observe after that will not come across it again, if come across it, I hope that you can the first! If you do, I hope you'll update your comment as soon as possible.

**Comment by EeyoreLee** [comment]
@v-frankwang - here's the diagnostics
```
{
  "os": "linux",
  "vscodeVersion": "1.91.1",
  "cmtVersion": "1.19.52",
  "configurations": [
    {
      "folder": "/media/E/lichunyu/bert.cpp",
      "cmakeVersion": "3.22.1",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {
        "C": "/usr/bin/gcc",
        "CXX": "/usr/bin/g++"
      }
    },
    {
      "folder": "/media/E/lichunyu/bert.cpp",
      "cmakeVersion": "3.22.1",
      "configured": false,
      "generator": "Ninja",
      "usesPresets": false,
      "compilers": {}
    },
    {
      "folder": "/media/E/lichunyu/bert.cpp",
      "cmakeVersion": "3.22.1",
      "configured": false,
      "generator": "",
      "usesPresets": false,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 12,
    "executablesCount": 5,
    "librariesCount": 7,
    "targets": [
      {
        "name": "bert_shared",
        "type": "SHARED_LIBRARY"
      },
      {
        "name": "ggml",
        "type": "SHARED_LIBRARY"
      },
      {
        "name": "tokenizer_cpp_objs",
        "type": "OBJECT_LIBRARY"
      },
      {
        "name": "tokenizers_c",
        "type": "INTERFACE_LIBRARY"
      },
      {
        "name": "tokenizers_cpp",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "sentencepiece-static",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "sentencepiece_train-static",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "spm_decode",
        "type": "EXECUTABLE"
      },
      {
        "name": "spm_encode",
        "type": "EXECUTABLE"
      },
      {
        "name": "spm_export_vocab",
        "type": "EXECUTABLE"
      },
      {
        "name": "spm_normalize",
        "type": "EXECUTABLE"
      },
      {
        "name": "spm_train",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    },
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```
As I expected, it works fine which can both enable and enable(workspace) after reinstalling this extension. Although we couldn't find the root cause of the issue, it's not affecting things anymore, and I don't think I can reproduce the previous problem on my side. So I close this issue. Thanks for you so fast reply mate.
