### ISSUE TITLE
${cmake.testProgram} is replaced by an empty string

### ISSUE THREAD

**Issue by cmorve-te** [microsoft/vscode-cmake-tools#4108]
As happened in https://github.com/microsoft/vscode-cmake-tools/issues/3280, I find that `${cmake.testProgram}` is replaced by an empty string: https://github.com/microsoft/vscode-cmake-tools/blob/v1.19.52/src/ctest.ts#L1001

#3280 was fixed in https://github.com/microsoft/vscode-cmake-tools/pull/3631, but it would seem only for Google Test.
I'm using Catch2, with catch_discover_tests: https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#automatic-test-registration

In https://github.com/microsoft/vscode-cmake-tools/pull/3631 there is this mention:
> During testing with my projects, I discovered that the root cause of https://github.com/microsoft/vscode-cmake-tools/issues/3280 is how multi-root workspaces are handled.

I was not using a multi-root workspace, but I was using a workspace with two projects. Once I removed the workspace, and just opened the project with the tests directly, the problem has disappeared.

**Comment by v-frankwang** [comment]
@cmorve-te Thanks for posting this issue. Could you please provide your projects files? :)
cc @danniesim @gcampbell-msft

**Comment by cmorve-te** [comment]
Never mind. I am now on VSCode 1.94.2 (still v1.19.52 of the plugin) and it works fine :-?

**Comment by cienporcien** [comment]
> As happened in [#3280](https://github.com/microsoft/vscode-cmake-tools/issues/3280), I find that `${cmake.testProgram}` is replaced by an empty string: https://github.com/microsoft/vscode-cmake-tools/blob/v1.19.52/src/ctest.ts#L1001
> 
> [#3280](https://github.com/microsoft/vscode-cmake-tools/issues/3280) was fixed in [#3631](https://github.com/microsoft/vscode-cmake-tools/pull/3631), but it would seem only for Google Test. I'm using Catch2, with catch_discover_tests: https://github.com/catchorg/Catch2/blob/devel/docs/cmake-integration.md#automatic-test-registration
> 
> In [#3631](https://github.com/microsoft/vscode-cmake-tools/pull/3631) there is this mention:
> 
> > During testing with my projects, I discovered that the root cause of [#3280](https://github.com/microsoft/vscode-cmake-tools/issues/3280) is how multi-root workspaces are handled.
> 
> I was not using a multi-root workspace, but I was using a workspace with two projects. Once I removed the workspace, and just opened the project with the tests directly, the problem has disappeared.

Same thing happened to me, I removed the other project and the problem went away.
