### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by shreyak-05** [microsoft/vscode-cmake-tools#4109]
- Issue Type: `Performance`
- Extension Name: `cmake-tools`
- Extension Version: `1.19.52`
- OS Version: `Linux x64 6.8.0-40-generic`
- VS Code version: `1.94.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/ms-vscode.cmake-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Yingzi1234** [comment]
@shreyak-05 Thank you for your github issue!
We can't reproduce your problem, so in order to better solve your problem, could you provide us with your `<myExtensionId>.cpuprofile.txt` file? Please let us know if you have any concerns!

**Comment by gcampbell-msft** [comment]
Closing due to not getting necessary info.
