### ISSUE TITLE
Test output isn't visible when failed

### ISSUE THREAD

**Issue by redstrate** [microsoft/vscode-cmake-tools#4116]
### Brief Issue Summary

When a test fails, the test output isn't visible... which is where the actual error is located. For example, in the code lens:

![image](https://github.com/user-attachments/assets/9cbf903a-b41e-4da7-a7fa-0e6b28c73e2b)

And when clicking the test in "Test Results":

![image](https://github.com/user-attachments/assets/6560ccec-a442-40aa-96f7-b7014feb35dc)

It's possible to work around this by pressing the "Show Result Output" button to view the actual output, but it isn't immediately obvious why I need to do that :sweat_smile: Is there something I'm missing or is this intentional?

I tracked down the [line to here](https://github.com/microsoft/vscode-cmake-tools/blob/ed37b19f512fb654ba64a6f32b5cf81b55351267/src/ctest.ts#L553) and I can even modify the extension to print the test output, but that seems wrong since it should have that log anyway. But if that would be better, I can make a pull request.

![image](https://github.com/user-attachments/assets/723aa8d4-49e9-4e1b-97a2-52e23c488cd6)

This doesn't have to do anything with my testing setup, even a Google.Test example I pulled from GH exhibits the same issue once I forced one of their tests to fail. Successful tests do print their log correctly.

**Comment by Amy-Li03** [comment]
Hi @redstrate, thanks for your reporting!
@gcampbell-msft when a test fails, the test output does not show detailed error messages on the code line, but we can press the "Show Result Output" button to view the actual output. 
**Maybe this is by design?**

**Comment by gcampbell-msft** [comment]
@redstrate This seems like a reasonable improvement to see the output without having to click a button, we'd be happy to accept a PR from you!
