### ISSUE TITLE
LLDB debug (lldb extension)

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cmake-tools#412]
(this is not a bug , just a question , and can be closed at any time.)

I see cmaketools always call ms cpptools for the debug.
I'm using lldb with an [extension](https://github.com/vadimcn/vscode-lldb), looks more useful than MS one.

when I run the debugger by F5 , I see LLDB as available option for the debug
and launch.json use this then.
![screenshot from 2018-05-03 18-53-43](https://user-images.githubusercontent.com/3259933/39588631-d25162d2-4f04-11e8-8c9b-9ba95ef7642b.png)

but how to configure cmaketools to use this one by default? 

thank you

**Comment by vector-of-bool** [comment]
The quick debugging only supports cpptools at the moment, but adding lldb is possible. You can also use [`launch.json`](https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html#debugging-with-cmake-tools-and-launch-json) with CMake Tools to get a similar effect.

**Comment by amigo421** [comment]
yes, I'm using usual launch.json 
just thou that can be configured in cmake-tools...

okay, can be closed, thank you.
please add lldb support if possible :) 
this plugin supports the debugging better than ms cpptools

**Comment by fifv** [comment]
I found this setting works (in `settings.json`):
```json
    "cmake.debugConfig": {
        "type": "lldb",
    },
```
After setting this, I got lldb debug session when triggering `CMake: Debug`



Previously, I have to write a `launch.json` like this (notice the `${command:cmake.getLaunchTargetPath}` will automatically trigger a CMake build before starting debug and get the executable's path) and replace the shortcut of `CMake: Debug` with the vscode's one:
```json
    {
        "type": "lldb",
        "request": "launch",
        "name": "Debug",
        "program": "${command:cmake.getLaunchTargetPath}",
        "args": [],
        "cwd": "${workspaceFolder}"
    }
```

**Comment by GitSparTV** [comment]
Just wanted to confirm what @fifv said. I even went to make a PR to detect Code LLDB extension and use `"type": "lldb"` instead. Or to add an option in debugConfig, but it actually already works!

Please document it. Auto-generated launch tasks is what makes VSCode feel like an IDE for C++.
