### ISSUE TITLE
Hello, may I ask why I have installed the relevant extension but still do not have the cmake icon?

### ISSUE THREAD

**Issue by aodexiusi1997** [microsoft/vscode-cmake-tools#4122]
### Brief Issue Summary

![Image](https://github.com/user-attachments/assets/4618bb6d-0a7c-4e5e-9447-3cebf8bfdfb8)
Hi, this is the question.

**Comment by Amy-Li03** [comment]
Hi @aodexiusi1997 , thanks for reporting issue here!
After creating a new project, you will see the cmake icon displayed. Following is a video, we use _CMake: Quick Start_ command to create new project, then the cmake icon appears.
![Image](https://github.com/user-attachments/assets/d28eae57-0b22-4f44-8d9c-f3441dcd9a54)
