### ISSUE TITLE
No Kit commands in command palette

### ISSUE THREAD

**Issue by bmcdonnell-fb** [microsoft/vscode-cmake-tools#4138]
### Brief Issue Summary

The "scan for kits" / "select kit" options don't show in my command palette.

![Image](https://github.com/user-attachments/assets/4f108d68-d428-4608-9bc2-8ef014336e0e)

![Image](https://github.com/user-attachments/assets/1d6dd2d6-151a-4ebe-bbc7-b80c1e8647c4)

Unclear whether or how I can update my toolchain without these.

### CMake Tools Diagnostics

```
{
  "os": "win32",
  "vscodeVersion": "1.94.2",
  "cmtVersion": "1.19.52",
  "configurations": [
    {
      "folder": "c:\\Users\\bmcdonnell\\dev\\groupREDACTED\\projREDACTED",
      "cmakeVersion": "3.28.3",
      "configured": true,
      "generator": "Ninja",
      "usesPresets": true,
      "compilers": {
        "C": "C:/Tools/GNU_Arm_Embedded_Toolchain/12.3-rel1/bin/arm-none-eabi-gcc.exe",
        "CXX": "C:/Tools/GNU_Arm_Embedded_Toolchain/12.3-rel1/bin/arm-none-eabi-g++.exe"
      }
    }
  ],
  "cpptoolsIntegration": {
    "isReady": true,
    "hasCodeModel": true,
    "activeBuildType": "Debug",
    "buildTypesSeen": [
      "Debug"
    ],
    "requests": [
      "file:///c%3A/Users/bmcdonnell/dev/groupREDACTED/projREDACTED/src/blah.c"
    ],
    "responses": [
      {
        "uri": "file:///c%3A/Users/bmcdonnell/dev/groupREDACTED/projREDACTED/src/blah.c",
        "configuration": {
          "includePath": [
            "c:/users/bmcdonnell/dev/groupREDACTED/projREDACTED/configs",
            "c:/users/bmcdonnell/dev/groupREDACTED/projREDACTED/src",
            "REDACTED...",
          ],
          "defines": [
            "REDACTED..."
          ],
          "compilerPath": "c:/tools/gnu_arm_embedded_toolchain/12.3-rel1/bin/arm-none-eabi-gcc.exe",
          "compilerArgs": [],
          "compilerFragments": [
            "-g -std=gnu11",
            "-mcpu=cortex-m4",
            "-mthumb",
            "-mfloat-abi=hard",
            "-mfpu=fpv4-sp-d16",
            "-fno-common",
            "-fmerge-constants",
            "-fmessage-length=0",
            "-ffunction-sections",
            "-fdata-sections",
            "-ffreestanding",
            "-fno-builtin",
            "-fstack-usage",
            "-Wall",
            "-Og",
            "-g3"
          ]
        }
      }
    ],
    "partialMatches": [],
    "targetCount": 13,
    "executablesCount": 1,
    "librariesCount": 10,
    "targets": [
      {
        "name": "REDACTED_lib1",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "programmableBin",
        "type": "UTILITY"
      },
      {
        "name": "programmableHex",
        "type": "UTILITY"
      },
      {
        "name": "stm32f4xx",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "stm32f4hal",
        "type": "STATIC_LIBRARY"
      },
      {
        "name": "segger_rtt",
        "type": "STATIC_LIBRARY"
      },
      ## ...
      {
        "name": "smartblock.elf",
        "type": "EXECUTABLE"
      }
    ]
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": true
    }
  ]
}
```

**Comment by Yingzi1234** [comment]
@bmcdonnell-fb Thank you for your GitHub issue! This issue is expected behavior. When you have a preset file among your test files, the Selection Kit should be unavailable.

**Comment by bmcdonnell-fb** [comment]
@Yingzi1234 thanks for the reply.

> When you have a preset file among your test files, the Selection Kit should be unavailable.

I take it this changed sometime within the last year or so? (Since we've had a `CMakePresets.json` in our project, and had been using "kits", for some years now.) When did this change, and why? Are there migration instructions somewhere?

What is the significance of "test files"? (We have no test files in our workspace, other than a do-nothing `tests/CMakeLists.txt`.) Or did you mean to say "source files"?

**Comment by Yingzi1234** [comment]
@bmcdonnell-fb This change happened after version CMake Tools version V1.18.43(release). I apologize if my statement caused any misunderstanding, the "test files" refers to the project you are testing. When using presets, the Selection Kit should be unavailable.

**Comment by bmcdonnell-fb** [comment]
> This change happened after version CMake Tools version V1.18.43(release).

I looked, but cannot find... Where can I find some documentation or PR that explain the change, and/or the reasoning behind it?

> I apologize if my statement caused any misunderstanding, the "test files" refers to the project you are testing.

Sorry, I guess this is kind of an aside, but I still don't follow your meaning on that. I'm building the project, not testing it. (Or, more broadly, I'm developing the firmware.)

> When using presets, the Selection Kit should be unavailable.

Why?

**Comment by gcampbell-msft** [comment]
@bmcdonnell-fb To my knowledge, this behavior has been present for versions much before v1.18.43. 

The reason for this is simply because they are totally separate flows and different designs for how to interact with your CMake project. If you are using Presets, that should be your source of truth, and kits should not be used. Presets is the preferred way as it's fully supported by Kitware.

**Comment by gcampbell-msft** [comment]
@bmcdonnell-fb Technically, this could also have to do with your setting for `cmake.useCMakePresets`. If you set this to `never`, then you may be able to still use kits even with a Presets file. However, this is not the recommended path. Thanks

**Comment by bmcdonnell-fb** [comment]
@gcampbell-msft thanks for chiming in.

Do I understand correctly that kits are a CMake Tools feature, not a CMake feature?

Can everything that can be done w/ kits also be done using `CMakePresets.json` + `toolchain.cmake`? If so, then wouldn't it make sense to deprecate kits?

**Comment by gcampbell-msft** [comment]
@bmcdonnell-fb Correct, kits are only for CMake Tools. 

Yes, I believe that everything that can be done with kits can be done with CMakePresets and toolchains. There is an open request to deprecate kits here #4006. We've gotten some feedback though that in some less common scenarios, CMakePresets doesn't handle it well, so for right now we're only strongly encouraging using of CMakePresets, rather than forcing it by deprecation.
