### ISSUE TITLE
Mystery Error: This instance was not yet configured

### ISSUE THREAD

**Issue by vector-of-bool** [microsoft/vscode-cmake-tools#415]
I'm getting a huge number of Rollbar issue reports for "This instance was not yet configured" from CMake Server. This issue appears when you call `cmakeInputs` before properly configuring the project.

I've been completely unable to reproduce the issue and can't see in the code any obvious reason why it would occur. No user has reported the issue, as it seems that it's occurrence doesn't actually block users.

If anyone reading this is seeing this error message, please comment below! (**Edit:** Please also include information about your platform, CMake version, OS, etc.)

**Comment by DoddzyCodes** [comment]
Had this problem just pop up.

I only noticed it start happening after enabling the C/C++ extension.  I had already configured and built the project.

After installing the C/C++ extension and reloading, the instance not configured error would pop up on almost any cmake-server operation. Disabling the C/C++ extension stopped the error showing up, and weirdly enough, I haven't been able to reproduce the error after re-enabling it.

Will let you know if I can find something a bit more reproducible.

**Comment by vector-of-bool** [comment]
@DoddzyCodes, what CMake version and OS are you running?

**Comment by DoddzyCodes** [comment]
@vector-of-bool Ubuntu 18.04, Cmake 3.10.2

**Comment by KoeMai** [comment]
I think there error is created by switch between kit files.
I test at the moment the new concept for the debugger integration, I get the error often when I switch between MinGw and Visual studio.

**Comment by vector-of-bool** [comment]
@KoeMai could you find a way to reliably reproduce the issue? I want to attach a debugger to CMake at the same time to see what is going on

**Comment by magpier84** [comment]
Moreover, following log line appear in some cases:

[rollbar] Unhandled exception: Unhandled Promise rejection: build [cmake-server] This instance was not yet configured. {}

**Comment by chetferry** [comment]
MacOS 10.13.4
make 3.11.
arm-eabi-none-gcc compiler

Getting the same errors but only intermittently.  About 1 our of 3 times that I build.

**Comment by johnf9896** [comment]
I get the same error after running CMake: Build. The same log line appears.

Windows 10 Home
CMake 3.11.2

**Comment by magpier84** [comment]
Unfortunately this popup + error message about already running cmake during launching app made me switch to another IDE for some time. Now both errors are not reproduced :(

**Comment by vector-of-bool** [comment]
@magpier84 Okay. Does the other error message need another GitHub issue?

**Comment by magpier84** [comment]
I will try to reproduce it.

**Comment by camelator** [comment]
Same error here with Ubuntu 16.04 and stable release
