### ISSUE TITLE
How do I pass parameters to the generator, such as ninja

### ISSUE THREAD

**Issue by Carter-chao** [microsoft/vscode-cmake-tools#4158]
I tried cmake.buildToolArgs and cmake.buildArgs and it didn't work,

**Comment by Carter-chao** [comment]
I hope to receive any helpful assistance.

**Comment by Carter-chao** [comment]
any help?

**Comment by Yingzi1234** [comment]
@Carter-chao 
Could you try adding the following code to the CMakeUserPresets.json file? And then try again if that solves the issue?
```
{
  "version": 3,
  "cmakeMinimumRequired": {
    "major": 3,
    "minor": 22,
    "patch": 0
  },
  "buildPresets": [
    {
      "name": "ninja",
      "generator": "Ninja",
      "binaryDir": "build",
      "buildToolArgs": ["-j4"]  // Add ninja args here
    }
  ]
}
```

**Comment by gcampbell-msft** [comment]
@Carter-chao @Yingzi1234 We don't support `buildToolArgs` from CMakePresets.json. However, if you create a build preset, you can likely make use of the `nativeToolOptions`. See the docs here: https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#build-preset

**Comment by gcampbell-msft** [comment]
@Carter-chao Did the `nativeToolOptions` in `CMakePresets.json` work for you? 

I'm going to close this issue, but please let us know if we can assist further.
