### ISSUE TITLE
[Loc] Field tooltips in CMakeLists.txt file not localized

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-cmake-tools#4165]
**More info:**
	1. This issue is reproduced on both release and pre-release versions, so it's not a regression issue
	2. Repro Language: All loc languages
	3. Repro platform: Windows, Linux, Mac

**Repro steps:**
	1. Download and unzip [CMakeProject1 (2).zip](https://microsoft-my.sharepoint.com/:u:/p/v-cathyzhang/Ebv_eitxyG9DgZPxJlvS10UB9MYAfu4FpOhLtAGRCOMWLw?e=xBhgRq)
	2. Open it with VSCode and change the display language to CHS
	3. Open above project with VS Code.
	4. Open CMakeLists.txt file
	5. Hover the mouse over the field

**Expected result:**
Tooltip messages for all fields are localized (Tooltip info localized in VS and screenshot as below)
![Image](https://github.com/user-attachments/assets/80309074-3cb2-4e12-a522-fcc5ad29ec35)

**Actual result:**
Tooltip messages for all fields are not localized
![Image](https://github.com/user-attachments/assets/17bb9c52-4cd0-4617-a790-f0c0fec93f9a)

**Comment by Yingzi1234** [comment]
Verified on CMake Tools v1.20.25(pre-release), this bug is still reproducing, so reopen it.

**Comment by gcampbell-msft** [comment]
This is expected, as we currently still depend on a 3rd party extension. Closing. This will plan to be fixed as part of #3560
