### ISSUE TITLE
[Loc]String “rerun test” for old results in test panel not localized

### ISSUE THREAD

**Issue by Yingzi1234** [microsoft/vscode-cmake-tools#4182]
### Brief Issue Summary

**Environment:**
VS Code 1.95.1
CMake Tools v1.20.25 (pre-release)

**More info:**
Repro Language: All loc languages
Repro platform: Windows, Linux, Mac

**Repro steps:**
1. Open VS Code and change the display language to CHS
2. Download and unzip [CMakeTestProject.zip](https://github.com/user-attachments/files/17643103/CMakeTestProject.zip)
3. Open the project with VS Code
4. Click Testing in left navigation bar
5. Click “Run Test“ 2 times on the “Test” page
6. After tests run completed, click "Show Output" in Testing page
7. Focus on buttons next to CMake Tools in "Show Output" window
![Image](https://github.com/user-attachments/assets/74924e40-0746-44b5-a08d-155cb6e66f69)

**Actual result:**
“Rerun the test” not localized in older results
![Image](https://github.com/user-attachments/assets/5a730aaa-b31a-4061-aee9-2746a381fcc5)

### CMake Tools Diagnostics

```shell

```

### Debug Log

```shell

```

**Comment by gcampbell-msft** [comment]
We do not own that output pane / window. Closing. Thanks!
