### ISSUE TITLE
Using sourceDir to locate a preset include file does not work

### ISSUE THREAD

**Issue by coder451** [microsoft/vscode-cmake-tools#4196]
### Brief Issue Summary

CMake Tools does not seem to understand the use of ${sourceDir} to locate a file included in a preset. 
I didn't find any existing issue covering this by searching with terms "sourceDir", "preset", "include".
There are at least two issues (https://github.com/microsoft/vscode-cmake-tools/issues/2531, https://github.com/microsoft/vscode-cmake-tools/issues/2492) that mention macro expansion in presets, but it looks like they were not related to finding files for inclusion.

### Background
I noticed this when I was working with a project that supports several compilers and platforms. Its CMakePresets.json contains only a list of includes. The included files are in a directory structure, and all include a common file  for local user settings from the top of that structure. To avoid using relative paths, this file is included using ${sourceDir}, which is one of the allowed macros in presets files. CMake itself works with this arrangement, but I wasn't able to use VS Code to build.  There is a reproduction of the problem with a simpler arrangement in the github repo mentioned below. Unlike the project where I noticed this problem, the included file is in the source directory.

### Reproduction
The problem is shown in the minimal Git repository mentioned below. Open the project in VS Code + CMake Tools, open the CMake view using the icon on the left, and try to set a configure preset . No presets are displayed in the dropdown. 

Or, take a project with an included preset file that works, and modify the path to the included file to use ${sourceDir}. All the existing presets disappear and it is not possible to choose a configuration preset.

### Github repo for repro
There is a [minimal Git repository reproducing the problem](https://github.com/coder451/cmake-preset-include-with-sourceDir-macro).

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.95.3",
  "cmtVersion": "1.19.52",
  "configurations": [
    {
      "folder": "c:\\Users\\perma\\dev\\src\\cmake-tools-issues\\cmake-preset-include-with-sourceDir-macro",
      "cmakeVersion": "3.31.0",
      "configured": false,
      "generator": "",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Debug Log

```shell
First, here is the (working) output for including without the macro:

[presetController] Reading presets file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json
[presetController] Reading and validating the presets "file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json"
[presetController] Successfully validated C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json against presets schema
[presetController] Reading presets file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\user-cache-variables.json
[presetController] Reading and validating the presets "file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\user-cache-variables.json"
[presetController] Successfully validated C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\user-cache-variables.json against presets schema
[presetController] Expanding presets file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json
[preset] Configure preset user-cache-variables: No binaryDir specified, using default value "${sourceDir}/out/build/${presetName}"
[expand] expanded ${sourceDir}/out/build/${presetName}
[presetController] Successfully expanded presets file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json

Next, the error output on changing to use ${sourceDir}:

[presetController] Reading presets file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json
[presetController] Reading and validating the presets "file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json"
[presetController] Successfully validated C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json against presets schema
[presetController] Included presets file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\${sourceDir}\user-cache-variables.json cannot be found
[presetController] Expanding presets file C:\Users\perma\dev\src\cmake-tools-issues\cmake-preset-include-with-sourceDir-macro\CMakePresets.json
[preset] Could not find configure preset with name user-cache-variables
[presetController] Expansion errors found in the presets file.
```

### Additional Information

The output copied above suggests that ${sourceDir} is not being expanded in the context of the "include" list..

This is my presets file:

```
{
  "version": 9,
  "include": [
    "${sourceDir}/user-cache-variables.json"
  ],
  "configurePresets": [
    {
      "inherits": [
        "user-cache-variables"
      ],
      "name": "msvc17-x64",
      "displayName": "msvc17-x64",
      "generator": "Visual Studio 17 2022",
      "architecture": "x64",
      "binaryDir": "builds/msvc17/x64"
    }
  ]
}
```

CMake Tools shows a red squiggly on the opening brace, with the message "Could not find configure preset 'user-cache-variables' in preset 'msvc17-x64'"

This is the included file:
```
{
  "version": 9,
  "configurePresets": [
    {
      "name": "user-cache-variables",
      "hidden": true,
      "cacheVariables": {
        "CMAKE_PREFIX_PATH": {
          "type": "STRING",
          "value": "C:/Users/perma/cget/"
        }
      }
    }
  ]
}
```

**Comment by gcampbell-msft** [comment]
Could you try this again with the most recent pre-release version of the CMake Tools extension? This is only currently supported in the pre-release version until we do an official 1.20 release. Thanks!

**Comment by Amy-Li03** [comment]
@coder451 we can repro this issue on CMake Tools extension release version v1.19.52, however, it **has been fixed** on recent pre-release version v1.20.28.

**Release version v1.19.52**
![Image](https://github.com/user-attachments/assets/61258d45-1d9b-480b-b087-44f3eee34a5f)

**Pre-release version v1.20.28**
![Image](https://github.com/user-attachments/assets/60b39d74-8d69-40ab-a7c2-3a7ad71fdc19)

@gcampbell-msft FYI

**Comment by coder451** [comment]
Awesome, thanks! I guess I should have looked ...

**Comment by coder451** [comment]
Just to confirm, I did try this and it worked
