### ISSUE TITLE
Bug when reopen the project

### ISSUE THREAD

**Issue by sunqi1993** [microsoft/vscode-cmake-tools#440]
It seems that there is a bug in the extension. when successfully build the target and reopen the project,
the extension doesn't work as expected

- The target selected for build, in this case i selected "all"  which is missing
- The F7/F5  doesn't work.
- it works after i delete the "build" dir in the workspace 
Platform :  Debian

![_ _20180529225748](https://user-images.githubusercontent.com/12682690/40667070-d38a913e-6393-11e8-8856-b52d3333e98b.png)

**Comment by vector-of-bool** [comment]
Sorry for the slow response. I've been having some hardware trouble this past week.

Two things to help diagnose the issue:

1. If you run `CMake: Configure` from the command palette, what happens?
2. Do you see any messages if you turn up the CMake Tools logging level in `settings.json`?

**Comment by vector-of-bool** [comment]
@sunqi1993 were you able to discover anything?

**Comment by sunqi1993** [comment]
@vector-of-bool 

After "cmake:Configure" command,there is no response from "cmake/build" panel 

But the output of "cmake: build" command is as following:
```
[extension] [9349] cmake.build started
[main] Run build 
[main] Saving open files before configure/build
[extension] [1947] cmake.build started
[main] Run build 
[main] Saving open files before configure/build
[extension] [6221] cmake.build started
[main] Run build 
[main] Saving open files before configure/build
```
it's interesting,it seems that the build thread has been blocked and the building of the target hasn't finished
