### ISSUE TITLE
Configuration selection returning "Bad Argument"

### ISSUE THREAD

**Issue by jovere** [microsoft/vscode-cmake-tools#446]
### Brief Issue Summary

When trying to select a CMake configuration from the "CMake: Unconfigured Project: Ready" menu, the following message occurs in the output window.

```[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant TypeError: Bad argument {}```

### Expected:

CMake should allow me to select "Release", and it should be updated accordingly in the bottom toolbar

### Apparent Behavior:

When selecting, only the "BadArgument" notification comes up and nothing else works.  Clicking on "Build" also comes up with an unhandled exception as below:

```
[rollbar] Unhandled exception: Unhandled Promise rejection: setVariant TypeError: Bad argument {}
[rollbar] Unhandled exception: Unhandled Promise rejection: build TypeError: Bad argument {}
```

This all worked with the previous version of CMake Tools.  This issue seemed to coincide with the "kits" options.

### Platform and Versions

- **Operating System**: Ubuntu 16.04.4 LTS
- **CMake Version**: 3.4.3
- **VSCode Version**: 1.23.1
- **CMake Tools Extension Version**: 0.11.1
- **Compiler/Toolchain**: GCC 5.4.0, GCC ARM 5.3.0

**Comment by vector-of-bool** [comment]
@KoeMai want to take a look at this one?
