### ISSUE TITLE
Question? How to use kits in     "cmake.buildDirectory"

### ISSUE THREAD

**Issue by lygstate** [microsoft/vscode-cmake-tools#462]
I want to use something like this to building for different compiler & tartget : "${workspaceRoot}/build/${buildType}-$(buildKit}",

such as Visual Studio 2017 amd 64& Visual Studio 2015 x86 & LLVM Cross for Linux and so on.

**Comment by vector-of-bool** [comment]
This is not currently supported, but is a good feature request, and I don't think this is the first time it has come up.

**Comment by mika-fischer** [comment]
This should be fixed, no? https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#variable-substitution

**Comment by lygstate** [comment]
Yeap, this was fixed, but arise a new issue:
The buildKit are very long:)
For example:
"sbe/build/Visual Studio Community 2019 Release - amd64"
May us config a short name for buildKit  without space and special character?
such as Visual Studio Community 2019 Release - amd64 to be vs2019-amd64

**Comment by lygstate** [comment]
Thanks for you wonderfull work
