### ISSUE TITLE
Using a toolchain file "sometimes" broke until cmake-kits.json is not edited.

### ISSUE THREAD

**Issue by andyinno** [microsoft/vscode-cmake-tools#471]
### Brief Issue Summary

I use cmake to cross compile for an embedded arm custom board. I usually specify a toolchain on the command line and then I open eclipse with the generated project.
During test for evaluating the possibility to switch on Code I found out that the toolchain file is not used while trying to compile the test program.

My toolchain file looks contains:
    
    SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

as defined in the documentation and is used during cross compilation in order to avoid linking errors with libraries not present before cmake configuration.

https://cmake.org/cmake/help/v3.10/variable/CMAKE_TRY_COMPILE_TARGET_TYPE.html

From Code I see often an error related to the fact that -rdynamic is not available while compiling a test program. So during cmake initial configuration. If I edit the cmake-kits.json and alter it a while a new cmake running is correct.

> [cmake]     Run Build Command:"/usr/bin/ninja" "cmTC_acd83"
[cmake]     [1/2] Building C object CMakeFiles/cmTC_acd83.dir/testCCompiler.c.obj
[cmake]     [2/2] Linking C executable cmTC_acd83
[cmake]     FAILED: cmTC_acd83 
[cmake]     : && /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc-7.2.1   -rdynamic CMakeFiles/cmTC_acd83.dir/testCCompiler.c.obj  -o cmTC_acd83   && :
[cmake]     arm-none-eabi-gcc-7.2.1: error: unrecognized command line option '-rdynamic'
[cmake]     ninja: build stopped: subcommand failed.

This usually happen switching kit but sometimes it just happen while iterating in the edit code => compile etc.

For fixing it I added twice the toolchain value and my cmake-kits.json looks like this:
>  {
    "name": "GCC for arm-none-eabi 7.2.1",
    "keep": true,
    "cmakeSettings": {
      "CMAKE_TOOLCHAIN_FILE": "/home/andrea/workspace/CanDeckAlpine/arm_gcc.cmake"
    },
    "toolchainFile": "/home/andrea/workspace/CanDeckAlpine/arm_gcc.cmake",
    "compilers": {
      "C": "/home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc-7.2.1"
    }

Commenting and uncommenting the toolchain file let the program to re-parse the kit and it works for a while.
The "keep true" flag is not causing errors or solving them.

### Expected:

That the cmake settings are not altered from execution to execution.

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.24.1
- **CMake Tools Extension Version**: 1.0.1
- **Compiler/Toolchain**: arm-none-eabi-gcc-7.2.1

**Comment by vector-of-bool** [comment]
Sorry for the delay. I just returned from a vacation.

Setting the `toolchainFile` option in the kit should be enough. You can omit `CMAKE_TOOLCHAIN_FILE` in the `cmakeSettings` key. Also, if your toolchain file sets up compilers you should be fine to omit the `compilers` section.

The `keep` option only appears if a compiler path refers to a non-existent file. Does the `C` compiler path refer to an existing file?

If you make these changes or tweaks, does the behavior change at all?

**Comment by andyinno** [comment]
Hi,
thank you for your kind reply.

I am sorry but I am not a English native speaker. Maybe I expressed myself wrong.

I already tried to change the values in the config file without success.

I do not have access until Monday to the documents.
I can post the toolchain file on Monday but I use it from the command line without any problem.

It looks like to me that cmake server mode does not receive the toolchain file after a reconfigure.

Basically the steps I did for hitting the problem are:

1) configure cmake-kits.json using the toolchain file.
2) configure cmake
3) compile the sources
4) add a new file to CMakeLists.txt or edit the file someway
5) compile (so reconfigure cmake).
at point 5 cmake pops the error 
> arm-none-eabi-gcc-7.2.1: error: unrecognized command line option '-rdynamic'

(which means that the toolchain file is not used while reconfiguring cmake.)
This error is avoided using in the toolchain file of the command 

> SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

This command is used for telling cmake while testing the compiler to not try to compile an executable but a static library.

If at this point I edit again cmake-kits.json or I change the active compiler, the build directory is deleted and recreated from zero.
Setting again the compiler that I want to use allow me to compile correctly. Like being at point 1. 
The compiler works correctly until I reach again point 4.

The same behaviour is observed on 2 different computers, both running Ubuntu.
I tried different projects, every project uses the same toolchain file because they target the same processor.

Thank you and sorry for the long post.
best regards
Andrea

**Comment by vector-of-bool** [comment]
Could you provide a minimal test case to reproduce the issue? I'm not sure what might be happening here.

**Comment by andyinno** [comment]
Of course...

1) Download a toolchain from https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
the one currently active in my project is gcc-arm-none-eabi-7-2017-q4-major. 
2) Insert the extracted directory in the PATH variable
3) create a toolchain file. I am using:

> SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR arm-eabi)
SET(CMAKE_C_COMPILER arm-none-eabi-gcc) 
SET(CMAKE_CXX_COMPILER arm-none-eabi-g++)
SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

4) Using a simple hello world 
>#include <stdio.h>
>
>int main(int argc, char **argv){
	printf("Hello world!\r\n");
	return 0;
}

5) Using a simple CMakeLists.txt

>Project(CandeckAlpine C ASM)
>cmake_minimum_required(VERSION 3.8)
>
>add_executable(hello main.c)

6) Add to the cmake-kits.json the correct configuration for the arm compiler.
Mine looks like this one:

>[
  {
    "name": "GCC 7.3.0",
    "compilers": {
      "CXX": "/usr/bin/g++-7",
      "C": "/usr/bin/gcc-7"
    }
  },
  {
    "name": "GCC for arm-none-eabi 7.2.1",
    "toolchainFile": "/home/andrea/workspace/CanDeckAlpine/arm_gcc.cmake",
    "compilers": {
      "C": "/home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc-7.2.1"
    }
  }
]

7) Try to compile for GCC 7.3.0
The compilation is successful.

8) Switch to GCC 7.2.1 ARM and compile the code.
The compilar complains about missing function that is present in custom libraries depending on the vendor. **THIS IS NORMAL. IT IS NOT THE PROBLEM THAT I AM NOTICING.**

9) Edit CMakeLists.txt in some way. The change I made in the example is:
add
>target_link_libraries(hello m)

at the end of the file.
It now looks like:

>Project(CandeckAlpine C ASM)
>cmake_minimum_required(VERSION 3.8)
>
>add_executable(hello main.c)
>target_link_libraries(hello m)

10) Try to compile the code. The output I get is:

>[cmake] Configuring done
[cmake] You have changed variables that require your cache to be deleted.
[cmake] Configure will be re-run and you may have to reset some variables.
[cmake] The following variables have changed:
[cmake] CMAKE_C_COMPILER= /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc-7.2.1
[cmake] 
[cmake] The C compiler identification is GNU 7.2.1
[cmake] The ASM compiler identification is GNU
[cmake] Found assembler: /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc
[cmake] Check for working C compiler: /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc-7.2.1
[cmake] Check for working C compiler: /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc-7.2.1 -- broken
[cmake] CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "/home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc-7.2.1"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: /home/andrea/workspace/HelloWorld/build/CMakeFiles/CMakeTmp
[cmake]     
[cmake]     Run Build Command:"/usr/bin/ninja" "cmTC_a3702"
[cmake]     [1/2] Building C object CMakeFiles/cmTC_a3702.dir/testCCompiler.c.obj
[cmake]     [2/2] Linking C executable cmTC_a3702
[cmake]     FAILED: cmTC_a3702
[cmake]     : && /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc-7.2.1   -rdynamic CMakeFiles/cmTC_a3702.dir/testCCompiler.c.obj  -o cmTC_a3702   && :
[cmake]     arm-none-eabi-gcc-7.2.1: error: unrecognized command line option '-rdynamic'
[cmake]     ninja: build stopped: subcommand failed.
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:1 (Project)
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] See also "/home/andrea/workspace/HelloWorld/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "/home/andrea/workspace/HelloWorld/build/CMakeFiles/CMakeError.log".
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.

As you can see cmake is executing without the use of the toolchain file definition
>SET(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

11) Switch on the host compiler again
>[driver] Switching to kit: GCC 7.3.0
[cms-client] Configuring using the "Ninja" CMake generator

and compile the software that compiles correctly.

12) Switch again on arm compiler

>[cmake] The C compiler identification is GNU 7.2.1
[cmake] The ASM compiler identification is GNU
[cmake] Found assembler: /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc
[cmake] Check for working C compiler: /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc
[cmake] Check for working C compiler: /home/andrea/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc -- works
[cmake] Detecting C compiler ABI info
[cmake] Detecting C compiler ABI info - done
[cmake] Detecting C compile features
[cmake] Detecting C compile features - done
[cmake] Configuring done
[cmake] Generating done
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/andrea/workspace/HelloWorld/build --config Debug --target all -- -j 10
[build] [1/2] Building C object CMakeFiles/hello.dir/main.c.obj
[build] [2/2] Linking C executable hello
[build] FAILED: hello 
...

The compilation starts correctly and the error visible is not related to this bug report.

The problem I am facing is that after cmake is configured, a change to the CMakeLists.txt file breaks the compiler. I need to switch compiler to host and then switch back to arm compiler for passing the cmake configuration step.

I don't think to be able to provide a more detailed step by step of this one.
By the way if you need to ask for some test or changes to be made I am available to try them.

Thank you
Andrea

**Comment by vector-of-bool** [comment]
Thanks for the in-depth test case! I'll evaluate and see if I can get a fix for 1.1
