### ISSUE TITLE
vscode with cmake error

### ISSUE THREAD

**Issue by chenzongxi** [microsoft/vscode-cmake-tools#479]
ubuntu14 install vscode，
cmake
![image](https://user-images.githubusercontent.com/38370307/42732888-f7351db0-885b-11e8-9c52-bcec008b8d6e.png)
cmake tool
![image](https://user-images.githubusercontent.com/38370307/42732899-16489da8-885c-11e8-8326-5a3755b39678.png)
cmake version
![image](https://user-images.githubusercontent.com/38370307/42732905-2c8cebfa-885c-11e8-9cf7-e1e39ff551aa.png)

It can build with cmake。But when i click the "Debug" button，there is a Error message。

![image](https://user-images.githubusercontent.com/38370307/42732926-b2d59dc4-885c-11e8-83cd-6b32ca43e549.png)

the configuration:

What's wrong?
Thanks.

**Comment by Randshot** [comment]
@chenzongxi It looks like you haven't enabled server mode.
The extension works best with CMake server mode enabled and since you seem to have CMake version `3.10.3`, you should be able to enable it.

**Comment by bobbrow** [comment]
Closing stale questions marked "more info needed".  If you are still having trouble, please open a new issue with the information requested.  Thank you for helping us build a better CMake Tools extension.
