### ISSUE TITLE
Organize targets using the FOLDER property in the Project Outline window

### ISSUE THREAD

**Issue by MathiasMagnus** [microsoft/vscode-cmake-tools#491]
First of all: I just **LOVE** the fact that the cpptools integration finally works! Awesome work guys!

### Expected:

It would be nice if the `FOLDER` property of targets and source_groups belonging to targets displayed as if they were in logical folders (Filters in VS terms), just like in Big Brother VS.

### Apparent Behavior:

All targets and source files are displayed in a flat structure.

**Comment by vector-of-bool** [comment]
This is actually what I wanted to do with the outline originally, but I was disappointed to find that CMake Server doesn't give me the value of the `FOLDER` property, so I can't know where to put the targets/sources.

**Comment by vdilecce** [comment]
+1 for a nice feature I would very much appreciate.

Apparently, CMake's [file API](https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html#codemodel-version-2-target-object) is exposing information about the `FOLDER` target property (JSON object member `folder`) and the `source_group` CMake command (`sourceGroupIndex` and `sourceGroups`), so I guess this should be possible now.

**Comment by ompadu** [comment]
I'd like to support as well this feature request, now that it is feasible

**Comment by gcampbell-msft** [comment]
Quick update for everyone:

We are currently working on a design for some improvements to the Project Outline window, which will include support for using the FOLDER property. We hope to have this functionality ready for release in 1.18, but we will keep you updated.
