### ISSUE TITLE
Build stops (like #387)

### ISSUE THREAD

**Issue by mmanyen** [microsoft/vscode-cmake-tools#492]
### Brief Issue Summary

Press build and it starts building but never completes. Cannot cancel or start another build until vscode is restarted.

Build works from terminal using the following from the workspace root:
cmake --build build 
also works:
/usr/bin/cmake --build /home/manyenm/V2-1/build --config Debug --target DesktopCP

The latter is what it looks like the extension is generating.

### Expected:

1. Push build button
2. Build progresses until complete

### Apparent Behavior:

1. Push build button
2. Build starts
3. Some progress
4. Progress stops before complete
5. Build function is locked up, the rest of vscode and the extension continues to work fine.

### Platform and Versions

- **Operating System**: Ubuntu 16.04 LTS
- **CMake Version**: 3.11.3
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.0
- **Compiler/Toolchain**: GCC for x86_64-linux-gnu 5.4.0

### Other Notes/Information

Seems similar to #387, but that is closed.
Sometimes goes a long way (it is a large project), sometimes stops in the first few lines of output.

**Comment by vector-of-bool** [comment]
How many lines of output does a build usually produce? Flooding the channel with output has caused problems in the past, and it may need to be throttled for some cases.

**Comment by vector-of-bool** [comment]
In a successful build from a command line, how many lines does it output?

**Comment by mmanyen** [comment]
725 from a clean build

**Comment by mmanyen** [comment]
More Info:

Much smaller build sometimes gets hung up just like the main build. Sample output below from a successful build:

```
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/manyenm/BP/BaxGUI/build --config Debug --target all -- -j 6
[build] Scanning dependencies of target BaxGUI
[build] [ 12%] Building CXX object CMakeFiles/BaxGUI.dir/Platform/Widget.cpp.o
[build] [ 12%] Building CXX object CMakeFiles/BaxGUI.dir/Platform/Screen.cpp.o
[build] [ 12%] Building CXX object CMakeFiles/BaxGUI.dir/GUI/IVisual.cpp.o
[build] [ 16%] Building CXX object CMakeFiles/BaxGUI.dir/GUI/Visuals/VisualSprite.cpp.o
[build] [ 20%] Building CXX object CMakeFiles/BaxGUI.dir/GUI/Visuals/VisualText.cpp.o
[build] [ 24%] Building CXX object CMakeFiles/BaxGUI.dir/Platform/ScreenDriver.cpp.o
[build] [ 28%] Building CXX object CMakeFiles/BaxGUI.dir/GUI/Visuals/VisualWWText.cpp.o
[build] [ 32%] Building CXX object CMakeFiles/BaxGUI.dir/GUI/Visuals/VisualMarkUpText.cpp.o
[build] [ 36%] Building CXX object CMakeFiles/BaxGUI.dir/GUI/Visuals/MarkUpParser.cpp.o
[build] [ 40%] Linking CXX executable BaxGUI
[build] [100%] Built target BaxGUI
[build] Build finished with exit code 0
```

**Comment by mmanyen** [comment]
Using same project under Windows7 does not seem to have this problem.

**Comment by andreeis** [comment]
We did not have this exact symptom in the repros we worked on while going through our extension GitHub issues but there were several fixes in this area. Please upgrade to latest CMake Tools and reopen if this problem is not solved.
