### ISSUE TITLE
Support for multiple toolchain files

### ISSUE THREAD

**Issue by hriekehof** [microsoft/vscode-cmake-tools#493]
### Brief Issue Summary

I read through some of the issues which i think are similar to my problem like #477 or #190 but i'm not sure what the status is with the cmake-tools or if there is already a way to achieve this. 
I basically have one root folder with a CMakeLists.txt. I can configure and build my project very nicely with the cmake-tools when i provide a kit with a toolchain file. Works like a charm as far as i can tell :)

The problem i have right now is that i want to use different toolchain files for different platforms like, Cortex-M0 or Cortex-M4, without reconfiguring and rebuilding when changing the toolchain.

### Expected:

I would like to define a separate build folder for every configuration. So a complete Rebuild is avoided when changing a toolchain or variant.
I also would like to see the available targets in the cmake-tools Project-Outline when i switch to a different build folder or variant.

### Apparent Behavior:

If i use different kits for this, cmake-tools reconfigure completely and the project structure it not automatically updated. I have to close and reopen VSCode to see the new targets in the project outline. I also have to rebuild everything since the build folder seems to be cleared when changing a kit.

I also tried the variants feature where i used always the same kit and supplied the toolchain file via the settings property of the variants. Passing `CMAKE_TOOLCHAIN_FILE` with the option with the new file name of the tool chain file.
But also when i changed the variant the same build folder is used and the targets are not updated until i restart VSCode.
I also tried to append `"cmake.buildDirectory": "${workspaceRoot}/build"` with the variable `${buildType}` to have separate build folders, but this seems only to work for the CMAKE_BUILD_TYPE variable. So when i want to build RelWithDebInfo with two different toolchain files, again the same build folder is used.

At the moment i use cmake-gui and eclipse+ninja to build my projects and i have a separate build folder for every build configuration.

### Platform and Versions

- **Operating System**: Windows 10 Pro, 1803
- **CMake Version**: 3.12
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.10
- **Compiler/Toolchain**: arm-none-eabi

**Comment by decimad** [comment]
Hello,
you can use the ${buildType} variable inside the cmake tooks build-directory path variable. That way when switching variants you get the desired behaviour.

**Comment by vector-of-bool** [comment]
There's a few things open for the same thing. #383, #462, and the #485 PR all address this. Being able to use the kit name in the build directory path would enable this feature.

**Comment by jhaws1982** [comment]
I'm curious to know if this is slated for an upcoming release or not?  This feature would make my life a whole lot easier!

**Comment by andreeis** [comment]
This is not yet scheduled for any of the upcoming releases. As soon as we are ready to investigate this, we will change the milestone from backlog to something else.
We are willing to accept a PR from the community though, which, if in good shape, it can be included in the upcoming release of that moment.

**Comment by gcampbell-msft** [comment]
@hriekehof I think that the best way for you to accomplish this would be to migrate to and use CMake Presets, this would solve exactly what you're looking for, which I understand to be that you want different configurations with different toolchains for each. 

Closing this as not planned since this is supported with CMake Presets, please feel free to open new issues you might encounter if you migrate to CMake Presets. Thanks!
