### ISSUE TITLE
Extension locks up occasionally when switching between git branches

### ISSUE THREAD

**Issue by ksmith-velo3d** [microsoft/vscode-cmake-tools#498]
### Brief Issue Summary

Occasionally when switching between git branches in the currently open folder (either through the VSCode UI or through the shell, it doesn't seem to make a difference), the extension appears to get stuck doing something with cmake. 

### Expected:

1. Checkout a different git branch
2. The active branch changes.

### Apparent Behavior:
**Intermittent**
1. Checkout a different git branch
2. The UI seems to be waiting for the branch to change.
3. `cmake.exe` and a VSCode subprocess will both be using 2 cores fully. The cmake subprocess memory usage will steadily climb up. After 10-20 minutes it's using over 24 GB of memory and still climbing.
4. During this time no git actions can be taken since there are OS level locks held on seemingly random files preventing them from being opened or modified.

It's unclear whether this process ever completes on its own.

### CMake Tools Log

No log output observed during these events.

### Developer Tools Log

No log output observed during these events.

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.11.0-rc3
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.0
- **Compiler/Toolchain**: Visual C++ 2017

### Other Notes/Information

This seems to happen most frequently if I switch between branches that have a lot of differences.

**Comment by vector-of-bool** [comment]
I've seen issues where CMake's file-watching system will accidentally see thousands of changes all enqueue very quickly. This happens if a large number of files are changed instantly. When you switch branches, how many files do you estimate are being changed by git?

**Comment by ksmith-velo3d** [comment]
The codebase is fairly large so I could imagine the number of changed files is on the order of hundreds. 

There are some other issues with trying to terminate the CMake server and associated CMT subprocess after the fact, but I think that might be a weird interaction with hardware or the security software installed on this machine. I think I'm the only one routinely using VSCode here, so this issue has only been observed on my machine.

In case it's somehow relevant, though: attempting to kill either process doesn't immediately kill it and ends up causing really poor system performance as a whole (and looks like it starts triggering some problems with the video driver since I will lose all displays periodically). At this point I usually have to reboot the machine.

I generally just close VSCode when switching git branches which is slightly annoying, but far from the worst workaround I've ever had to deal with.

**Comment by vector-of-bool** [comment]
I'm marking this as an upstream bug. CMT doesn't use cmake-server's file-watching facilities, so it's not helpful to the ext. It would be good to be able to disable it if possible, but there isn't yet an option to do so. I too have seen cmake-server lock up on systems with a huge number of file changes also while running intrusive security software (Webroot in my case, which causes me no end of grief).

**Comment by TarImre** [comment]
As far as I know, the same problem happened to me when I changed a source branch by the `gitlen` extension.

Here is a possible better workaround than restarting the VSCode instance:
I switched off the "Configure On Open" option of `ms-vscode.cmake-tools` extension and restarted the VSCode instance. For now, it seems to solve the problem. 

![kép](https://user-images.githubusercontent.com/10563321/99069314-67be6400-25ae-11eb-9c30-185096014d3b.png)

I hope that it helps.

**Comment by bobbrow** [comment]
@TarImre that option only has an effect when you open a new VS Code window.  I wouldn't expect it to have any effect on syncing a new branch.

I have also experienced a lock up on a large repository when switching between branches that had diverged by thousands of changes, but that was the only case.  The issue was actually with the C++ extension and we did some work to make the scenario work better.  I haven't seen this problem since.

**Comment by bobbrow** [comment]
Sorry, I went off topic a bit.  For the CMake case which is the subject of the original issue, I suspect that upgrading to 3.15 or newer will resolve this because you have the option of using the CMake file API to get the project information instead of using CMake Server which is now deprecated and unlikely to be fixed.
