### ISSUE TITLE
Add touch bar controls for cmake commands

### ISSUE THREAD

**Issue by rafmudaf** [microsoft/vscode-cmake-tools#499]
The title pretty much covers it, but it would be really helpful to add vscode-cmake-tools commands to the touch bar. I already use the touch bar to run debug commands, so adding configure, build, and maybe ctest buttons would go pretty far for my workflow. I haven't actually seen a VS Code extension make use of this, but extensions can add [custom touch bar buttons](https://code.visualstudio.com/updates/v1_17#_touch-bar-support).

If it is decided that this would be worthwhile, I'm happy to take a stab at implementing it.

**Comment by Randshot** [comment]
I did take a look at the vscode api, and it looks simple enough for that to be added. The only problem will be testing this feature, since I don't think that any of us (@vector-of-bool and the other contributors) have a MacBook with a touchbar. At least I only have an older model.

**Comment by rafmudaf** [comment]
Got ya, let me know if there's any way I can help in testing as I do have a touch bar.

**Comment by vector-of-bool** [comment]
If you are able to do VSCode development you could send PR. Otherwise, the turnaround time for iterating on the creating of touch bar items might be too high. Anyone else reading this who might be able to offer help: Your assistance would be greatly appreciated.

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.5.0 which was published today.
Let us know if you encounter any issues with this release.
