### ISSUE TITLE
CMake Tools does not remember "Unspecified" kit choice

### ISSUE THREAD

**Issue by DexterMagnific** [microsoft/vscode-cmake-tools#502]
### Brief Issue Summary

When you select "Unspecified" as a compiler kit, it is not remembered on VSCode restart

### Expected:

CMake Tools should remember that we chose Unspecified kit

1. Chose Unspecified kit
2. Close VSCode
3. Restart VSCode

-> Should not ask again to chose a compiler kit

### Apparent Behavior:

-> Asks to chose a compiler kit

### Platform and Versions

- **Operating System**: Any
- **CMake Version**: 3.11.2
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.1
- **Compiler/Toolchain**: Custom, based on CLang 3.9.0

**Comment by giantmustache** [comment]
I am having the same issue with the chosen kit, not only with Unspecified.
