### ISSUE TITLE
Execute current target without a debugger is incompatible with Windows Subsystem for Linux

### ISSUE THREAD

**Issue by DorianCzichotzki** [microsoft/vscode-cmake-tools#511]
### Brief Issue Summary

I'm using the WSL bash in vscode. When I try to execute the current target without a debugger (Shift+F5) cmake-tools tries to execute the windows style command ("[Full path to target]").

### Expected:

Execute Unix style command if a WSL bash is the default integrated terminal.

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.11.1
- **VSCode Version**: 1.25.1
- **CMake Tools Extension Version**: 1.1.0

**Comment by vector-of-bool** [comment]
I'll take a look

**Comment by bobbrow** [comment]
I know this issue is old, but have you tried the new [Remote WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) extension for VS Code?  If you open your WSL folder with that extension your workspace will load as if it were running natively on linux.
