### ISSUE TITLE
output window code page 

### ISSUE THREAD

**Issue by longlongwaytogo** [microsoft/vscode-cmake-tools#518]
When i used vscode-cmake-tools to build project, the output text  defualt with utf8 code ; but how i change it to GBK(chinese charset)

![error](https://user-images.githubusercontent.com/16498273/44440127-63868480-a5f9-11e8-94ef-72907cc0371e.png)

**Comment by andreeis** [comment]
Closing this issue. Please reopen if the merge that is referenced did not help with your case.
