### ISSUE TITLE
Is there any chance for your guys to tell me what's going on?

### ISSUE THREAD

**Issue by Tonysmark** [microsoft/vscode-cmake-tools#520]
![image](https://user-images.githubusercontent.com/22767695/44541769-8e79f100-a73d-11e8-9168-c9c9c86de9a8.png)
I 'm positive sure I can use Clion to run my code,and I don;t know why this happend
![image](https://user-images.githubusercontent.com/22767695/44541871-def14e80-a73d-11e8-803e-d924c9ea1651.png)
Is there anything I forget ?

**Comment by vector-of-bool** [comment]
I'm sorry that I let this sit unanswered for so long. I've been busy with a few projects.

It looks to be that the extension is failing to load. Can you show the output from the your CMake Tools log? Check the troubleshooting section from the documentation.

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
