### ISSUE TITLE
Setting up Cmake kits 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/vscode-cmake-tools#527]
How do I add `user-local kits` to the cmake-kits.json file, what is the "CC" & "CXX" paths ?

**Comment by vector-of-bool** [comment]
Sorry for the slow response.

[The documentation should tell you all-you need to know](https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html).

"user-local" kits just refers to the user-wide `cmake-kits.json` file. This file isn't associated with a specific workspace.

`CC` and `CXX` are environment variables which specify the path/name of the C and C++ compilers. CMake will use these to guess what compilers you wish to use.

Does this answer your questions?

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
