### ISSUE TITLE
Run in terminal doesn't work with Powershell

### ISSUE THREAD

**Issue by hasali19** [microsoft/vscode-cmake-tools#535]
### Brief Issue Summary

Right clicking on a target in the cmake project outline and selecting the 'Run in terminal' option doesn't work if the terminal is set to Powershell, since the path is in quotes, so it just prints back the path.

```
PS D:\hasan\Projects\HelloWorld> "D:\hasan\Projects\HelloWorld\build\HelloWorld.exe"
D:\hasan\Projects\HelloWorld\build\HelloWorld.exe
```
To execute the program the path must be prefixed with '& '.

```
PS D:\hasan\Projects\HelloWorld> & "D:\hasan\Projects\HelloWorld\build\HelloWorld.exe"
Hello, world!
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.11.4
- **VSCode Version**: 1.26.1
- **CMake Tools Extension Version**: 1.1.1
- **Compiler/Toolchain**: Visual C++ 2017

**Comment by vector-of-bool** [comment]
Sorry for the lack of responsiveness.

Ouch. This is kind of troublesome. Starting a process with a shell in VSCode consists of starting the shell in a terminal, then feeding the command text into `stdin`, followed by a newline to execute in the shell. There isn't a reliable way to know what shell will actually be executed. I can check the shell value in `settings.json`, but that provides little information on what the shell actually _is_. May require more investigation.

**Comment by KoeMai** [comment]
The first issue part is the same as #601.
The last comment seems to be something different. I think it is a problem with detection of gdb, it does not use the PATH variables from the selected kit.

**Comment by LucasOe** [comment]
This has been an issue for four years now. All that's missing is a dot or an "&" before the path.
