### ISSUE TITLE
Clearing cache

### ISSUE THREAD

**Issue by decimad** [microsoft/vscode-cmake-tools#536]
Hello,

I was wondering if there is a way to purge the cache and configure from scratch. Sometimes I select the incorrect kit by accident on the first configure. But since the cmake-server keeps some files opened in the build directory, I can't delete it from within vscode, so I need to close the instance, delete the cache with os-utilities and then restart vscode. Is there a way to reset the cache that I'm missing?

And thank you for this extension, it has become a great tool that even serves our very special cross-compiling needs!

**Comment by decimad** [comment]
Thinking about it, it might be simpler to trigger a complete cache wipe once you change the kit, right?

**Comment by vector-of-bool** [comment]
Changing the kit _should_ cause a cache-reset. If it isn't, that's a bug. Also, CMake shouldn't be holding those files opened permanently, as far as I know. What platform and CMake version are you using?

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
