### ISSUE TITLE
Suggestion/request: cmake-browser-like functionality ala Stephen Kelly's original ideas for cmake-server

### ISSUE THREAD

**Issue by lanza** [microsoft/vscode-cmake-tools#537]
When Kelly was working on/creating cmake-server he designed a little tool he called "cmake-browser" that used his tools to their full potential. Observe the [variable diffing in this video](https://youtu.be/BPgXuvPAl-8?t=10m39s). I asked him about it and he simple said that "I never published the code" and then never responded as to why.

At any rate, this variable tracking functionality is my dream for cmake. Any idea if the cmake-server functionality is complete enough at this point to provide this?

**Comment by vector-of-bool** [comment]
The current CMake Server design does not yet provide the information necessary to replicate his `cmake-browser`, but I sure wish it did!

There are a few pending tickets regarding an enhanced CMake GUI embedded via a WebView in VSCode. If cmake-server support reaches this level in the future, it may become a reality.
