### ISSUE TITLE
preLaunchTask to build using cmaketools in settings.json

### ISSUE THREAD

**Issue by nico-abram** [microsoft/vscode-cmake-tools#540]
I've tried using a build task but I couldnt get it to work. Is there any way to do this currently? 
```
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"name": "RelWithDebug",
			"type": "cppvsdbg",
			"request": "launch",
			"program": "${workspaceFolder}/Program/Etterna-release-symbols.exe",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"environment": [],
			"externalConsole": true
		},
		{
			"name": "Release",
			"type": "cppvsdbg",
			"request": "launch",
			"program": "${workspaceFolder}/Program/Etterna.exe",
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"environment": [],
			"externalConsole": true
		}
	]
}
```
This is what i currently have for settings.

**Comment by nico-abram** [comment]
That's a shame. This extension is absolutely amazing! Thanks for the great work. It *just* worked. Having an easy way to setup the launch settings with automatic building would be a godsend.

**Comment by HOYS** [comment]
+1 For this option!

**Comment by Voxed** [comment]
+1 This would be great!

**Comment by fyesoft** [comment]
+1 I need it too

**Comment by exomo** [comment]
+1
I came here to see if there is already a suggestion to integrate cmake with the tasks system. And I found it. Unfortunately it looks like we're not getting this feature, at least anytime soon.
Is there any progress or is it still not possible due to technical reasons?

imho setting up tasks in vs code is not really intuitive and my tasks usually ignore everything I set in the cmake extension and just run cmake with default args. While this somehow works in my usual configuration, it fails to chose the right tools when I want to use a different kit.
I would greatly appreciate a "cmake" task type that just works, like the rest of the extension (great work btw).

**Comment by whiitehead** [comment]
Is there a workaround for launching a debug session and a build with a single command?

**Comment by andreeis** [comment]
If you are using the CMake Tools debug feature (via the status bar or the command), a build will be triggered by an out of date state.
If you use a launch.json then no.

**Comment by RolfNoot** [comment]
Found a good solution for this. Please give some thumbs up [over here](https://github.com/microsoft/vscode-cmake-tools/issues/1535) and hope it will be implemented finally.

**Comment by bobbrow** [comment]
@RolfNoot I also posted over there and will copy here for convenience.

#### Without `preLaunchTask`
There is an example `launch.json` in our documentation that shows how to do this without a `preLaunchTask`.  https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md#debug-using-a-launchjson-file

The `cmake.launchTargetPath` and `cmake.getLaunchTargetPath` variable substitutions and their side effects (or lack thereof) are documented here: https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/cmake-settings.md#command-substitution.

#### With `preLaunchTask`
`cmake.tasksBuildCommand` should give you the cmake command required to build your binary, so if you want a `preLaunchTask` you could create a shell task that runs `${command:cmake.tasksBuildCommand}` as the command (I see this is missing from the substitution documentation).

**Comment by qu1ck** [comment]
@bobbrow what should the type of task with `${command:cmake.tasksBuildCommand}` be?
I've tried both "process" and "shell" and neither work because they treat the command as a single string instead of separate arguments:

`The terminal process failed to launch: Path to shell executable "D:\Kicad\source\D:\devtools\CMake\bin\cmake.EXE --build d:\Kicad\source\build\vscode-msvc --config RelWithDebInfo --target install -j 26 --" does not exist.`

`The term 'D:\devtools\CMake\bin\cmake.EXE --build d:/Kicad/source/build/vscode-msvc --config RelWithDebInfo --target install -j 26 --' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.`

**Comment by andreeis** [comment]
@qu1ck, try type "cmake" and command "build" (it will automatically use the same build command that tasksBuildCommand constructs). The "cmake" type of task was implemented more recently in our extension than when this report was discussed.

**Comment by qu1ck** [comment]
@andreeis I tried that before, failed, reported it here https://github.com/microsoft/vscode-cmake-tools/issues/1234#issuecomment-861932288, provided the logs you asked for but there was no follow up.

Please let me know if I can provide any more information.
Just repeated the test with type "cmake" and command "build". On linux machine it works fine, on windows machine I still get errors as described in my earlier report.

**Comment by bobbrow** [comment]
@qu1ck are you using PowerShell as your terminal?  I don't think the command works with PowerShell in VS Code anymore.  I use this setting to ensure that the regular Windows Command prompt is used.

```
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
```
(may require reloading VS Code for the setting to take proper effect)

If you are just trying to ensure that stuff is built before you start debugging, you can use the example launch.json entry mentioned in the following documentation plus the `cmake.buildBeforeRun` setting instead of adding a separate build task for it: https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/debug-launch.md#debug-using-a-launchjson-file

**Comment by qu1ck** [comment]
@bobbrow I had it set to `null` which I think is equivalent to default or "Command Prompt". Anyway, when setting to "Command Prompt" explicitly, same errors still occur. Bunch of "Cannot open include file" errors that are not there if I press F7 or run "command": "${command:cmake.build}","type": "shell".

**Comment by bobbrow** [comment]
Can you paste the output of your latest attempt?  If it says something about a cmdlet, then it's still trying to use PowerShell and you need to restart VS Code with that terminal setting set to `"Command Prompt"`.

I don't know what you mean about the second part.  Where are the "Cannot open include file" errors?  In the terminal (which I didn't think was working), or as red underlines in the editor?

**Comment by qu1ck** [comment]
It's not using powershell.

<details>
  <summary>Full output</summary>

```
> Executing task: CMake-build <

Starting build...
D:\devtools\CMake\bin\cmake.EXE --build d:/Kicad/source/build/vscode-msvc --config RelWithDebInfo --target install -j 26 --
[1/40] Creating image archive D:/Kicad/source/build/vscode-msvc/resources/images.tar.gz
[2/40] Generating version string header
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.23.0.windows.1") 
-- Using Git to determine build version string.
-- Writing D:/Kicad/source/build/vscode-msvc/kicad_build_version.h file with version: (5.99.0-13222-g16a34e6adb-dirty)
[3/40] Building RC object gerbview\CMakeFiles\gerbview.dir\__\resources\msw\gerbview.rc.res
FAILED: gerbview/CMakeFiles/gerbview.dir/__/resources/msw/gerbview.rc.res 
"D:/devtools/CMake/bin/cmcldeps.exe" RC D:\Kicad\source\resources\msw\gerbview.rc gerbview\CMakeFiles\gerbview.dir\__\resources\msw\gerbview.rc.res.d gerbview\CMakeFiles\gerbview.dir\__\resources\msw\gerbview.rc.res "Note: including file: " "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe -DBOOST_ALL_NO_LIB -DBOOST_UUID_FORCE_AUTO_LINK -DGERBVIEW -DGLM_FORCE_CTOR_INIT -DHAVE_STDINT_H -DKICAD_BUILD_ARCH=x64 -DKICAD_BUILD_ARCH_X64 -DKICAD_CONFIG_DIR=kicad -DKICAD_SCRIPTING_WXPYTHON -DKICAD_SPICE -DKICAD_USE_OCC -DNOMINMAX -DUNICODE -DWXUSINGDLL -DWX_COMPATIBILITY -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_USE_MATH_DEFINES -I D:\Kicad\source\include -I D:\Kicad\source\gerbview -I D:\Kicad\source\resources\msw -I D:\Kicad\source\gerbview\dialogs -I D:\Kicad\source\common -I D:\Kicad\source\common\dialogs -I D:\Kicad\source\3d-viewer -I D:\Kicad\source\build\vscode-msvc -I D:\devtools\vcpkg\installed\x64-windows\include\python3.9 -I D:\Kicad\source\scripting -I D:\Kicad\source\thirdparty\nlohmann_json -I D:\Kicad\source\thirdparty\compoundfilereader -I D:\Kicad\source\build\vscode-msvc\common -I D:\Kicad\source\libs\kimath\include -I D:\Kicad\source\thirdparty\clipper -I D:\Kicad\source\thirdparty\other_math -I D:\Kicad\source\thirdparty\rtree -I D:\Kicad\source\libs\kiplatform\include -I D:\Kicad\source\thirdparty\pybind11\include -I D:\devtools\vcpkg\installed\x64-windows\include -I D:\devtools\vcpkg\installed\x64-windows\include\opencascade -I D:\devtools\vcpkg\installed\x64-windows\lib\mswu -I D:\devtools\vcpkg\installed\x64-windows\include -I D:\devtools\vcpkg\installed\x64-windows\tools\python3\include -DWIN32 /fo gerbview\CMakeFiles\gerbview.dir\__\resources\msw\gerbview.rc.res D:\Kicad\source\resources\msw\gerbview.rc
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
D:\devtools\vcpkg\installed\x64-windows\include\wx/msw/wx.rc(12): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
[4/40] Building RC object bitmap2component\CMakeFiles\bitmap2component.dir\__\resources\msw\bitmap2component.rc.res
FAILED: bitmap2component/CMakeFiles/bitmap2component.dir/__/resources/msw/bitmap2component.rc.res 
"D:/devtools/CMake/bin/cmcldeps.exe" RC D:\Kicad\source\resources\msw\bitmap2component.rc bitmap2component\CMakeFiles\bitmap2component.dir\__\resources\msw\bitmap2component.rc.res.d bitmap2component\CMakeFiles\bitmap2component.dir\__\resources\msw\bitmap2component.rc.res "Note: including file: " "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe -DBITMAP_2_CMP -DBOOST_ALL_NO_LIB -DBOOST_UUID_FORCE_AUTO_LINK -DGLM_FORCE_CTOR_INIT -DHAVE_STDINT_H -DKICAD_BUILD_ARCH=x64 -DKICAD_BUILD_ARCH_X64 -DKICAD_CONFIG_DIR=kicad -DKICAD_SCRIPTING_WXPYTHON -DKICAD_SPICE -DKICAD_USE_OCC -DNOMINMAX -DUNICODE -DWXUSINGDLL -DWX_COMPATIBILITY -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_USE_MATH_DEFINES -I D:\Kicad\source\include -I D:\Kicad\source\bitmap2component -I D:\Kicad\source\resources\msw -I D:\Kicad\source\build\vscode-msvc -I D:\devtools\vcpkg\installed\x64-windows\include\python3.9 -I D:\Kicad\source\scripting -I D:\Kicad\source\thirdparty\nlohmann_json -I D:\Kicad\source\thirdparty\compoundfilereader -I D:\Kicad\source\build\vscode-msvc\common -I D:\Kicad\source\libs\kimath\include -I D:\Kicad\source\thirdparty\clipper -I D:\Kicad\source\thirdparty\other_math -I D:\Kicad\source\thirdparty\rtree -I D:\Kicad\source\libs\kiplatform\include -I D:\Kicad\source\thirdparty\potrace\include -I D:\Kicad\source\thirdparty\pybind11\include -I D:\devtools\vcpkg\installed\x64-windows\include -I D:\devtools\vcpkg\installed\x64-windows\include\opencascade -I D:\devtools\vcpkg\installed\x64-windows\lib\mswu -I D:\devtools\vcpkg\installed\x64-windows\include -I D:\devtools\vcpkg\installed\x64-windows\tools\python3\include -DWIN32 /fo bitmap2component\CMakeFiles\bitmap2component.dir\__\resources\msw\bitmap2component.rc.res D:\Kicad\source\resources\msw\bitmap2component.rc
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
D:\devtools\vcpkg\installed\x64-windows\include\wx/msw/wx.rc(12): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
[5/40] Building RC object kicad\CMakeFiles\kicad.dir\__\resources\msw\kicad.rc.res
FAILED: kicad/CMakeFiles/kicad.dir/__/resources/msw/kicad.rc.res 
"D:/devtools/CMake/bin/cmcldeps.exe" RC D:\Kicad\source\resources\msw\kicad.rc kicad\CMakeFiles\kicad.dir\__\resources\msw\kicad.rc.res.d kicad\CMakeFiles\kicad.dir\__\resources\msw\kicad.rc.res "Note: including file: " "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe -DBOOST_ALL_NO_LIB -DBOOST_UUID_FORCE_AUTO_LINK -DGLM_FORCE_CTOR_INIT -DHAVE_STDINT_H -DKICAD -DKICAD_BUILD_ARCH=x64 -DKICAD_BUILD_ARCH_X64 -DKICAD_CONFIG_DIR=kicad -DKICAD_SCRIPTING_WXPYTHON -DKICAD_SPICE -DKICAD_USE_OCC -DNOMINMAX -DPCM -DUNICODE -DWXUSINGDLL -DWX_COMPATIBILITY -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_USE_MATH_DEFINES -I D:\Kicad\source\include -I D:\Kicad\source\kicad -I D:\Kicad\source\resources\msw -I D:\Kicad\source\pcbnew -I D:\Kicad\source\eeschema -I D:\Kicad\source\build\vscode-msvc -I D:\devtools\vcpkg\installed\x64-windows\include\python3.9 -I D:\Kicad\source\scripting -I D:\Kicad\source\kicad\pcm -I D:\Kicad\source\thirdparty\nlohmann_json -I D:\Kicad\source\thirdparty\compoundfilereader -I D:\Kicad\source\build\vscode-msvc\common -I D:\Kicad\source\libs\kimath\include -I D:\Kicad\source\thirdparty\clipper -I D:\Kicad\source\thirdparty\other_math -I D:\Kicad\source\thirdparty\rtree -I D:\Kicad\source\libs\kiplatform\include -I D:\Kicad\source\kicad\pcm\dialogs -I D:\Kicad\source\thirdparty\picosha2 -I D:\Kicad\source\thirdparty\json_schema_validator -I D:\Kicad\source\thirdparty\pybind11\include -I D:\devtools\vcpkg\installed\x64-windows\include -I D:\devtools\vcpkg\installed\x64-windows\include\opencascade -I D:\devtools\vcpkg\installed\x64-windows\lib\mswu -I D:\devtools\vcpkg\installed\x64-windows\include -I D:\devtools\vcpkg\installed\x64-windows\tools\python3\include -DWIN32 /fo kicad\CMakeFiles\kicad.dir\__\resources\msw\kicad.rc.res D:\Kicad\source\resources\msw\kicad.rc
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
D:\devtools\vcpkg\installed\x64-windows\include\wx/msw/wx.rc(12): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
[6/40] Building RC object pagelayout_editor\CMakeFiles\pl_editor.dir\__\resources\msw\pl_editor.rc.res
FAILED: pagelayout_editor/CMakeFiles/pl_editor.dir/__/resources/msw/pl_editor.rc.res 
"D:/devtools/CMake/bin/cmcldeps.exe" RC D:\Kicad\source\resources\msw\pl_editor.rc pagelayout_editor\CMakeFiles\pl_editor.dir\__\resources\msw\pl_editor.rc.res.d pagelayout_editor\CMakeFiles\pl_editor.dir\__\resources\msw\pl_editor.rc.res "Note: including file: " "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe -DBOOST_ALL_NO_LIB -DBOOST_UUID_FORCE_AUTO_LINK -DGLM_FORCE_CTOR_INIT -DHAVE_STDINT_H -DKICAD_BUILD_ARCH=x64 -DKICAD_BUILD_ARCH_X64 -DKICAD_CONFIG_DIR=kicad -DKICAD_SCRIPTING_WXPYTHON -DKICAD_SPICE -DKICAD_USE_OCC -DNOMINMAX -DPL_EDITOR -DUNICODE -DWXUSINGDLL -DWX_COMPATIBILITY -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_USE_MATH_DEFINES -I D:\Kicad\source\include -I D:\Kicad\source\pagelayout_editor -I D:\Kicad\source\resources\msw -I D:\Kicad\source\pagelayout_editor\dialogs -I D:\Kicad\source\common\dialogs -I D:\Kicad\source\build\vscode-msvc -I D:\devtools\vcpkg\installed\x64-windows\include\python3.9 -I D:\Kicad\source\scripting -I D:\Kicad\source\thirdparty\nlohmann_json -I D:\Kicad\source\thirdparty\compoundfilereader -I D:\Kicad\source\build\vscode-msvc\common -I D:\Kicad\source\libs\kimath\include -I D:\Kicad\source\thirdparty\clipper -I D:\Kicad\source\thirdparty\other_math -I D:\Kicad\source\thirdparty\rtree -I D:\Kicad\source\libs\kiplatform\include -I D:\Kicad\source\thirdparty\pybind11\include -I D:\devtools\vcpkg\installed\x64-windows\include -I D:\devtools\vcpkg\installed\x64-windows\include\opencascade -I D:\devtools\vcpkg\installed\x64-windows\lib\mswu -I D:\devtools\vcpkg\installed\x64-windows\include -I D:\devtools\vcpkg\installed\x64-windows\tools\python3\include -DWIN32 /fo pagelayout_editor\CMakeFiles\pl_editor.dir\__\resources\msw\pl_editor.rc.res D:\Kicad\source\resources\msw\pl_editor.rc
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
D:\devtools\vcpkg\installed\x64-windows\include\wx/msw/wx.rc(12): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
[7/40] Building CXX object kicad\pcm\CMakeFiles\pcm.dir\pcm.cpp.obj
FAILED: kicad/pcm/CMakeFiles/pcm.dir/pcm.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_UUID_FORCE_AUTO_LINK -DGLM_FORCE_CTOR_INIT -DHAVE_STDINT_H -DKICAD -DKICAD_BUILD_ARCH=x64 -DKICAD_BUILD_ARCH_X64 -DKICAD_CONFIG_DIR=kicad -DKICAD_SCRIPTING_WXPYTHON -DKICAD_SPICE -DKICAD_USE_OCC -DNOMINMAX -DPCM -DUNICODE -DWXUSINGDLL -DWX_COMPATIBILITY -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_USE_MATH_DEFINES -I..\..\include -I..\..\kicad\pcm\. -I..\..\kicad\. -I..\..\resources\msw -I..\..\pcbnew -I..\..\eeschema -I. -ID:\devtools\vcpkg\installed\x64-windows\include\python3.9 -I..\..\scripting -I..\..\common -I..\..\kicad -I..\..\kicad\pcm\dialogs -I..\..\thirdparty\nlohmann_json -I..\..\thirdparty\compoundfilereader -Icommon -I..\..\libs\kimath\include -I..\..\thirdparty\clipper -I..\..\thirdparty\other_math -I..\..\thirdparty\rtree -I..\..\libs\kiplatform\include -I..\..\thirdparty\picosha2 -I..\..\thirdparty\json_schema_validator -I..\..\thirdparty\pybind11\include -ID:\devtools\vcpkg\installed\x64-windows\include -ID:\devtools\vcpkg\installed\x64-windows\include\opencascade -ID:\devtools\vcpkg\installed\x64-windows\share\wxwidgets\..\..\lib\mswu -ID:\devtools\vcpkg\installed\x64-windows\share\wxwidgets\..\..\include -ID:\devtools\vcpkg\installed\x64-windows\tools\python3\include /DWIN32 /D_WINDOWS /W3 /GR  /utf-8 /wd4290 /wd4800 /Zi /bigobj /EHs /MD /Zi /O2 /Ob1 /DNDEBUG /GF /Gy -std:c++14 /showIncludes /Fokicad\pcm\CMakeFiles\pcm.dir\pcm.cpp.obj /Fdkicad\pcm\CMakeFiles\pcm.dir\pcm.pdb /FS -c ..\..\kicad\pcm\pcm.cpp
D:\devtools\vcpkg\installed\x64-windows\include\curl/curl.h(49): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
[8/40] Building CXX object kicad\pcm\CMakeFiles\pcm.dir\dialogs\dialog_pcm_progress.cpp.obj
FAILED: kicad/pcm/CMakeFiles/pcm.dir/dialogs/dialog_pcm_progress.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_UUID_FORCE_AUTO_LINK -DGLM_FORCE_CTOR_INIT -DHAVE_STDINT_H -DKICAD -DKICAD_BUILD_ARCH=x64 -DKICAD_BUILD_ARCH_X64 -DKICAD_CONFIG_DIR=kicad -DKICAD_SCRIPTING_WXPYTHON -DKICAD_SPICE -DKICAD_USE_OCC -DNOMINMAX -DPCM -DUNICODE -DWXUSINGDLL -DWX_COMPATIBILITY -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_USE_MATH_DEFINES -I..\..\include -I..\..\kicad\pcm\. -I..\..\kicad\. -I..\..\resources\msw -I..\..\pcbnew -I..\..\eeschema -I. -ID:\devtools\vcpkg\installed\x64-windows\include\python3.9 -I..\..\scripting -I..\..\common -I..\..\kicad -I..\..\kicad\pcm\dialogs -I..\..\thirdparty\nlohmann_json -I..\..\thirdparty\compoundfilereader -Icommon -I..\..\libs\kimath\include -I..\..\thirdparty\clipper -I..\..\thirdparty\other_math -I..\..\thirdparty\rtree -I..\..\libs\kiplatform\include -I..\..\thirdparty\picosha2 -I..\..\thirdparty\json_schema_validator -I..\..\thirdparty\pybind11\include -ID:\devtools\vcpkg\installed\x64-windows\include -ID:\devtools\vcpkg\installed\x64-windows\include\opencascade -ID:\devtools\vcpkg\installed\x64-windows\share\wxwidgets\..\..\lib\mswu -ID:\devtools\vcpkg\installed\x64-windows\share\wxwidgets\..\..\include -ID:\devtools\vcpkg\installed\x64-windows\tools\python3\include /DWIN32 /D_WINDOWS /W3 /GR  /utf-8 /wd4290 /wd4800 /Zi /bigobj /EHs /MD /Zi /O2 /Ob1 /DNDEBUG /GF /Gy -std:c++14 /showIncludes /Fokicad\pcm\CMakeFiles\pcm.dir\dialogs\dialog_pcm_progress.cpp.obj /Fdkicad\pcm\CMakeFiles\pcm.dir\pcm.pdb /FS -c ..\..\kicad\pcm\dialogs\dialog_pcm_progress.cpp
D:\devtools\vcpkg\installed\x64-windows\include\wx/defs.h(725): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
[9/40] Building CXX object common\CMakeFiles\common.dir\build_version.cpp.obj
FAILED: common/CMakeFiles/common.dir/build_version.cpp.obj 
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_UUID_FORCE_AUTO_LINK -DGLM_FORCE_CTOR_INIT -DHAVE_STDINT_H -DKICAD_BUILD_ARCH=x64 -DKICAD_BUILD_ARCH_X64 -DKICAD_CONFIG_DIR=kicad -DKICAD_SCRIPTING_WXPYTHON -DKICAD_SPICE -DKICAD_USE_OCC -DNOMINMAX -DUNICODE -DWXUSINGDLL -DWX_COMPATIBILITY -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D_USE_MATH_DEFINES -I..\..\include -I..\..\common\. -I..\..\resources\msw -I..\..\common\.\dialogs -I..\..\common\.\widgets -I..\..\common\.\dialog_about -I..\..\bitmaps_png -I..\..\3d-viewer -I..\..\pcbnew -I. -ID:\devtools\vcpkg\installed\x64-windows\include\python3.9 -I..\..\scripting -I..\..\thirdparty\libcontext -I..\..\thirdparty\nlohmann_json -I..\..\thirdparty\compoundfilereader -Icommon -I..\..\libs\kimath\include -I..\..\thirdparty\clipper -I..\..\thirdparty\other_math -I..\..\thirdparty\rtree -I..\..\libs\kiplatform\include -I..\..\thirdparty\pybind11\include -ID:\devtools\vcpkg\installed\x64-windows\include -ID:\devtools\vcpkg\installed\x64-windows\include\opencascade -ID:\devtools\vcpkg\installed\x64-windows\share\wxwidgets\..\..\lib\mswu -ID:\devtools\vcpkg\installed\x64-windows\share\wxwidgets\..\..\include -ID:\devtools\vcpkg\installed\x64-windows\tools\python3\include /DWIN32 /D_WINDOWS /W3 /GR  /utf-8 /wd4290 /wd4800 /Zi /bigobj /EHs /MD /Zi /O2 /Ob1 /DNDEBUG /GF /Gy -std:c++14 /showIncludes /Focommon\CMakeFiles\common.dir\build_version.cpp.obj /Fdcommon\CMakeFiles\common.dir\common.pdb /FS -c ..\..\common\build_version.cpp
D:\devtools\vcpkg\installed\x64-windows\include\wx/defs.h(725): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
ninja: build stopped: subcommand failed.
Build finished with error(s).

Terminal will be reused by tasks, press any key to close it.
  ```
</details>

You can see it can't find system headers there. At the same time build works perfectly fine if I just press F7.

<details>
<summary>Task in tasks.json</summary>

```js
        {
            "label": "CMake-build",
            "command": "build",
            "type": "cmake",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": []
        }
```
</details>

Build also works perfectly fine if I change 
```
            "command": "build",
            "type": "cmake",
```
to
```
            "command": "${command:cmake.build}",
            "type": "shell",
```

Except the inconsequential warning at the end of the build about not being able to substitute command variable "cmake.build"

**Comment by bobbrow** [comment]
If you are using MSVC to build, are you launching VS Code from a "Developer Command Prompt"?  The extension sets up the MSVC build environment for you if you use our `"type": "cmake"` task or the `cmake.build` command.  The `${command:cmake.tasksBuildCommand}` doesn't do that and you'd need to have the environment already set up.

**Comment by qu1ck** [comment]
No I launch vscode from a standard shortcut it creates from installation. I have msvc environment setup manually because the project uses vcpkg and needs other tools both at cmake configure and build time.

> The extension sets up the MSVC build environment for you if you use our "type": "cmake" task or the cmake.build command.

Except it doesn't setup include paths or overrides them from what cmake provides as evident from build failure.

> The ${command:cmake.tasksBuildCommand} doesn't do that and you'd need to have the environment already set up.

That doesn't work at all, literally can't launch it. https://github.com/microsoft/vscode-cmake-tools/issues/540#issuecomment-961762703

**Comment by bobbrow** [comment]
> > The extension sets up the MSVC build environment for you if you use our "type": "cmake" task or the cmake.build command.
> 
> Except it doesn't setup include paths or overrides them from what cmake provides as evident from build failure.

It sounds like my memory was incorrect then.  I thought the `cmake` task type did that for you.  We should create an issue for that.

> > The ${command:cmake.tasksBuildCommand} doesn't do that and you'd need to have the environment already set up.
> 
> That doesn't work at all, literally can't launch it. [#540 (comment)](https://github.com/microsoft/vscode-cmake-tools/issues/540#issuecomment-961762703)

It works for me (I did test this one), just not when PowerShell is chosen as the terminal.

**Comment by qu1ck** [comment]
Fair enough, I opened #2258 for cmake type launch issue. 

With the latest update the
```
 "command": "${command:cmake.tasksBuildCommand}",
 "type": "shell",
```
configuration now "works" in the sense that it at least launches properly but gives same result as using task type cmake so build still fails.

**Comment by HofiOne** [comment]
Just for the record.

Using macOS 13.1, VSCode 1.73.1, CMake Tools 1.12.27, zsh or bash, none of the above is working.
I was happy when found this thread and I was sure that the 

    command": "${command:cmake.tasksBuildCommand}",
    type": "shell",
        
version will work, but it did not.

These are my issues and tries, at the end the best working current version.
Hope it would help someone to spare a bunch of time whilst strugling with this


"tasks": [
// This should be the first in the task list as it seems, only the first one  is enumerated 
// e.g. during default build task selection
{
	"label": "CMake: Build (task)",
	"detail": "CMake build task",

	// Seems CMake Tools extension is bogus here, cannot return the failing task exit code properly
	// Failing task will not stop the build that way
	//
	// "type": "cmake",
	// "command": "build",
	// "targets": [
	// 	"install"
	// ],
	// 
	// This replacement is working, but has the disadvantage that not all possible original
	// invocation parameters can be passed towards this way
	//
	//"type": "shell",
	//"command": "/Applications/Development/CMake.app/Contents/bin/cmake --build ${command:cmake.buildDirectory} --config ${command:cmake.buildType} --target ${command:cmake.buildTargetName} -j 12 --",

	// These are all failing with 
	// "The terminal process failed to launch: Path to shell executable (...) does not exist."
	//
	//"type": "process",
	//"command": "${input:cmakeTaskBuildCommandNoQuotes}", 
	//"command": "/Applications/Development/CMake.app/Contents/bin/cmake --build ${command:cmake.buildDirectory} --config ${command:cmake.buildType} --target ${command:cmake.buildTargetName} -j 12 --",
	//"command": "/bin/bash -c ${command:cmake.tasksBuildCommand}",
	//"command": "/bin/bash -c ''${command:cmake.tasksBuildCommand}''",
	//"command": "/bin/bash -c \"${command:cmake.tasksBuildCommand}\"",

	// And the winner is...
	//
	"type": "process",
	"command": "/bin/bash",
	"args": [ 
	  "-c", 
	  {
	    "value": "${command:cmake.tasksBuildCommand}",
	  }
	],

**Comment by Finomnis** [comment]
For whoever still wonders what the current state of this matter is, this works pretty well for me.

It seems that the CMake Tools plugin now is an official task type, which makes this problem trivial.

`tasks.json`:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Build",
            "type": "cmake",
            "command": "build",
            "targets": [
                "ALL_BUILD"
            ],
            "group": "build",
            "problemMatcher": [],
            "detail": "Builds the firmware"
        },
        {
            "label": "Build & run on device",
            "type": "cmake",
            "command": "build",
            "targets": [
                "flash"
            ],
            "group": "build",
            "problemMatcher": [],
            "detail": "Flashes the firmware to target",
        },
    ]
}
```

**Comment by gcampbell-msft** [comment]
@Finomnis I believe this is true, we have default tasks that can be used. I am closing this as resolved, due to the fact that @Finomnis is correct, and since there are _many_ changes/improvements in the extension and I believe this issue is solved now. 

If it is not, please create a new issue with new/additional context so that we can investigate and assess. Thanks!

@nico-abram @qu1ck FYI.
