### ISSUE TITLE
Unable to determine what CMake generator to use.

### ISSUE THREAD

**Issue by asktalk** [microsoft/vscode-cmake-tools#549]
Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json or your Kit configuration.

**Comment by vector-of-bool** [comment]
Could I get some information about what platform you are using? What CMake version do you have installed?

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
