### ISSUE TITLE
cmake .. configuration is incomplete showing an error with see also: ~/"CMakeOutput.log"

### ISSUE THREAD

**Issue by sofialovestam** [microsoft/vscode-cmake-tools#561]
### Expected:

1. Push button
2. Thing happens

### Apparent Behavior:

1. Push button
2. Nothing happens

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: 
- **CMake Version**: 
- **VSCode Version**: 
- **CMake Tools Extension Version**: 
- **Compiler/Toolchain**:

**Comment by bobbrow** [comment]
Do you get the same error when you configure in your terminal window (outside of VS Code)?
The output log doesn't always have the configure error in it, so the CMake message is somewhat misleading if you're not having trouble with the compiler check step.
