### ISSUE TITLE
Unhandled exception: Unhandled Promise rejection

### ISSUE THREAD

**Issue by RolfNoot** [microsoft/vscode-cmake-tools#570]
### Brief Issue Summary

1. Unhandled exception: Unhandled Promise rejection
2. Unable to determine what CMake generator to use
### Expected:

Build or Clean

### CMake Tools Log

```
2018-10-27T21:04:43.254Z [debug] [extension] [1906] cmake.clean started
2018-10-27T21:04:43.255Z [debug] [main] Run build clean
2018-10-27T21:04:43.291Z [debug] [main] Starting new CMake driver
2018-10-27T21:04:43.291Z [debug] [main] Starting CMake driver
2018-10-27T21:04:43.291Z [debug] [driver] CMakeDriver Kit set to GCC for arm-none-eabi 7.3.1
2018-10-27T21:04:43.291Z [debug] [driver] Run _refreshExpansions
2018-10-27T21:04:43.291Z [debug] [cms-driver] Run doRefreshExpansions
2018-10-27T21:04:43.291Z [debug] [driver] Run _refreshExpansions cb
2018-10-27T21:04:43.306Z [debug] [cms-client] Started new CMake Server instance with PID 8120
2018-10-27T21:04:44.313Z [debug] [driver] Trying to detect generator supported by system
2018-10-27T21:04:44.441Z [debug] [main] Starting new CMake driver
2018-10-27T21:04:44.442Z [debug] [main] Starting CMake driver
2018-10-27T21:04:44.442Z [debug] [driver] CMakeDriver Kit set to GCC for arm-none-eabi 7.3.1
2018-10-27T21:04:44.442Z [debug] [driver] Run _refreshExpansions
2018-10-27T21:04:44.443Z [debug] [cms-driver] Run doRefreshExpansions
2018-10-27T21:04:44.443Z [debug] [driver] Run _refreshExpansions cb
2018-10-27T21:04:44.449Z [debug] [cms-client] Started new CMake Server instance with PID 10012
2018-10-27T21:04:45.469Z [debug] [driver] Trying to detect generator supported by system
2018-10-27T21:04:45.533Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: clean Error: Impossible: CMake driver died immediately after successful configure {}
2018-10-27T21:13:44.407Z [debug] [extension] [9692] cmake.cleanRebuild started
2018-10-27T21:13:44.407Z [debug] [main] Run build clean
2018-10-27T21:13:44.455Z [debug] [main] Starting new CMake driver
2018-10-27T21:13:44.455Z [debug] [main] Starting CMake driver
2018-10-27T21:13:44.455Z [debug] [driver] CMakeDriver Kit set to GCC for arm-none-eabi 7.3.1
2018-10-27T21:13:44.456Z [debug] [driver] Run _refreshExpansions
2018-10-27T21:13:44.456Z [debug] [cms-driver] Run doRefreshExpansions
2018-10-27T21:13:44.456Z [debug] [driver] Run _refreshExpansions cb
2018-10-27T21:13:44.463Z [debug] [cms-client] Started new CMake Server instance with PID 9240
2018-10-27T21:13:45.467Z [debug] [driver] Trying to detect generator supported by system
2018-10-27T21:13:45.612Z [debug] [main] Starting new CMake driver
2018-10-27T21:13:45.612Z [debug] [main] Starting CMake driver
2018-10-27T21:13:45.612Z [debug] [driver] CMakeDriver Kit set to GCC for arm-none-eabi 7.3.1
2018-10-27T21:13:45.613Z [debug] [driver] Run _refreshExpansions
2018-10-27T21:13:45.613Z [debug] [cms-driver] Run doRefreshExpansions
2018-10-27T21:13:45.613Z [debug] [driver] Run _refreshExpansions cb
2018-10-27T21:13:45.619Z [debug] [cms-client] Started new CMake Server instance with PID 7944
2018-10-27T21:13:46.626Z [debug] [driver] Trying to detect generator supported by system
2018-10-27T21:13:46.693Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: cleanRebuild Error: Impossible: CMake driver died immediately after successful configure {}
```

### Platform and Versions

- **Operating System**: Window 10 Pro 1803
- **CMake Version**: 0.0.17
- **VSCode Version**: 1.28.2
- **CMake Tools Extension Version**: 1.1.2
- **Compiler/Toolchain**: GCC for arm-none-eabi 7.3.1

**Comment by RolfNoot** [comment]
Oops sorry,  cmake version 3.12.3
Updated to 1.1.3 and still the same problem.

**Comment by RolfNoot** [comment]
When I tried to duplicate this on another PC I got an issue with installing:
The extension hangs on: CMake Tools initializing...: Creating backend

For half an hour rignt now....

**Comment by RolfNoot** [comment]
Finally solved it! I was using an old project with cMake files. Tried a fresh new project and it works.

Thanks anyway!

**Comment by RolfNoot** [comment]
Just created a blank project. Trying to do "install", still same message:
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Impossible: CMake driver died immediately after successful configure {}

Why is it so hard to show a decent error message??? Like a file/folder is missing. 

I don't have any clue right now. Mingw is installed, GCC installed, cMake installed. System paths are correct, Folder references are correct... HELP!!!

**Comment by RolfNoot** [comment]
After some tests, funny things seems to happen:
1) Close VS Code
2) delete CMake build folder contents
3) Start VS Code
4) CMake > Configure: Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json or your Kit configuration.
5) Command line: cmake -DCMAKE_TOOLCHAIN_FILE="cmake/arm-none-eabi-toolchain.cmake" .. -G "MinGW Makefiles" ..
6) CMake > Configure: OK
7)  delete CMake build folder contents
8) CMake > Configure: OK

**Comment by RolfNoot** [comment]
Any support whatsoever???

**Comment by KoeMai** [comment]
It is possible to add the prefered generator into the kit file.

**Comment by KoeMai** [comment]
I tried to trace your problem. It seems that the extension does not found a matching build tool for the generators, by using "cmake. Generator" you force the generator. The debugging Information inside of the generator matching function (`getBestGenerator(..) `) are Not that detailed. But it looks like that it does not found "mingw32-make" or it has a bad return Code or it crashs (dll missing) . Could you try to add the prefered generator and the mingw path to your kit in the kitfile

```
{ "name": arm "GCC 7.3.1",
  "compilers": { 
     "C": "[...]",
     "CXX": "[...] "
   },
  "preferredGenerator": { "name": "MinGW Makefiles" },
  "environmentVariables": { "PATH": "${env:PATH};C:\\msys64\\usr\\bin" }
 }```

**Comment by RolfNoot** [comment]
That doesn't work! I use MingW and therefor I have this kit:
```
  {
    "name": "GCC for arm-none-eabi 7.3.1",
    "compilers": {
      "C": "C:\\Program Files (x86)\\GNU Tools Arm Embedded\\7 2018-q2-update\\bin\\arm-none-eabi-gcc.exe",
      "CXX": "C:\\Program Files (x86)\\GNU Tools Arm Embedded\\7 2018-q2-update\\bin\\arm-none-eabi-g++.exe",
      "preferredGenerator": { "name": "MinGW Makefiles" },
       "environmentVariables": { "PATH": "${env:PATH};C:\\MinGW\\bin" }
    }
  }
```

Forcing the generator is the only option to get it working as it seems right now.

A request would be to get a more informative error / debug though...

**Comment by KoeMai** [comment]
Was the `mingw32-make` result from the vscode terminal?

Do you still get the same Unhandled Promise rejection error?
`Unhandled exception: Unhandled Promise rejection: cleanRebuild Error: Impossible: CMake driver died immediately after successful configure {}`

**Comment by RolfNoot** [comment]
It was from an external dos command prompt. I tried to do: 
`"environmentVariables": { "PATH": "${env:PATH};C:\\MinGW\\bin" }`
but this destroyed my path variable (compiler couldn't be found anymore).

I noticed differences in the path from vscode integrated terminal and the external dos prompt so I did a fresh Windows restart.

Finally your suggestion adding` "preferredGenerator": { "name": "MinGW Makefiles" }` in the kits file worked out well and I'm able to remove the generator forcing from the settings.

**Comment by rcdailey** [comment]
I'm still getting this failure @vector-of-bool. I tried the solutions mentioned here but nothing works.

**Comment by MBetters** [comment]
I'm getting it too.

**Comment by Eight9inerEcho** [comment]
Im getting this error now too. Been through the numerous threads on this error and no luck so far. Can I just point the CMake Path directly to the executable? If so, where is it?

Im using only the CMake extension in VS Code. I do not have CMake itself installed. This was working fine upon initial setup but broke shortly after. 

Thanks in advance for the help

**Comment by andreeis** [comment]
The CMake Tools extension does not install the CMake binary. I hope I am not missing something, but I always download one from https://cmake.org/download and install it manually. I assumed everyone did the same.
I am puzzled about you saying this ever worked for you, without installing CMake yourself.
What OS are you on? Windows (pure or MinGW/MSYS), Linux, Mac?

**Comment by andreeis** [comment]
@Eight9inerEcho, the problem you have, even if it's similar, it is highly unlikely to be related to this old report, so I opened a new one here: https://github.com/microsoft/vscode-cmake-tools/issues/1722. Let's continue our investigation over there.

**Comment by Eight9inerEcho** [comment]
Environment is windows. After this post I was doing more digging and realized that cmake was in fact installed as part of a toolchain install I had done previously. Presumably, the installer created a new PATH variable which is why VS code found it. 

So now I know what directory to find the cmake executable in, but even when pointing VS code explicitly to that location, I get the same error.

**Comment by andreeis** [comment]
What's the output of "cmake --version"?
Increase your logging verbosity with "cmake.loggingLevel": "Debug" in your .vscode/settings.json, reload your project and share with us the text in the "CMake/Build" output channel.
Does the same happen when you create a new small project (for example, with the quick start command in the palette)?

**Comment by Eight9inerEcho** [comment]
Cmake version is 3.14.5

here's the output from CMake/Build

> [main] Building folder: PX4-Autopilot 
> [rollbar] Unhandled exception: Unhandled Promise rejection: build Error: Build failed: Unable to configure the project {}

**Comment by andreeis** [comment]
Can you share the output also from a configure command, not just a build command? It should be longer than that. And did you set verbosityLevel to debug?
Then can you upgrade your cmake to latest and see if this solves the problem?
To not lose track of a potential bug, I will downgrade cmake on a system over here (to the 3.14 that you mention) just to double check if the extension fails to address something when cmake is that old.

**Comment by Eight9inerEcho** [comment]
The configuration happens automatically when I select a build kit (not an expert on how this works so apologies for my ignorance here)

> [main] Safe constructing new CMakeTools instance
[variant] Constructing VariantManager
[main] Constructing new CMakeTools instance
[main] Starting CMakeTools second-phase init
[variant] Loaded new set of variants
[main] CMakeTools instance initialization complete.
[kit] Reading kits file C:\Users\armer\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Successfully loaded 0 kits from C:\Users\armer\AppData\Local\CMakeTools\cmake-tools-kits.json
[kit] Reading kits file c:\PX4\home\PX4-Autopilot\.vscode\cmake-kits.json
[kit] Successfully loaded 1 kits from c:\PX4\home\PX4-Autopilot\.vscode\cmake-kits.json
[main] Injecting new Kit into CMake driver
[extension] Configuring workspace on open file:///c%3A/PX4/home/PX4-Autopilot
[main] Configuring folder: PX4-Autopilot 
[main] Saving open files before configure/build
[extension] [3892] cmake.buildType started
[extension] [3892] cmake.buildType finished (returned "RelWithDebInfo")
[extension] [1797] cmake.buildDirectory started
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] CMakeDriver Kit set to PX4 detect
[driver] Trying to detect generator supported by system
[driver] Command version test return code -1
[driver] Command version test return code -1
[driver] Command version test return code -1
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] CMakeDriver Kit set to PX4 detect
[driver] Trying to detect generator supported by system
[driver] Command version test return code -1
[driver] Command version test return code -1
[driver] Command version test return code -1
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
[extension] [1797] cmake.buildDirectory finished (returned null)
[main] Starting new CMake driver
[main] Starting CMake driver
[cmakefileapi-driver] Creating instance of CMakeFileApiDriver
[driver] CMakeDriver Kit set to PX4 detect
[driver] Trying to detect generator supported by system
[driver] Command version test return code -1
[driver] Command version test return code -1
[driver] Command version test return code -1
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.


The toolchain install instructions for this project specifically say that not to upgrade Cmake. Not sure why but I try real hard to RTFM so I intentionally did not upgrade. 

below is a screenshot showing an attempted build with the same issue

![image](https://user-images.githubusercontent.com/72224980/112887810-d64d1b80-9090-11eb-88f5-4feacb1f9e7e.png)

**Comment by Eight9inerEcho** [comment]
I really think this is a problem with VS code having the wrong path for the Cmake executable. How can I find out where the Cmake executable was installed by the toolchain so I can point to in manually?

**Comment by andreeis** [comment]
Try to use the available settings that influence the generator decision: "cmake.generator" or "cmake.preferredGenerator" or preferred generator in your kit definition. If none is specified, the extension tries to select one from a list of defaults and for windows what it usually looks for is "Ninja". Do you have ninja installed on your windows?

More info about CMake generators: https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html.
