### ISSUE TITLE
Can't find GCC compiler

### ISSUE THREAD

**Issue by SolarJuice** [microsoft/vscode-cmake-tools#576]
I've already installed g++, gdb, and make via MSYS2. (See the first picture)

However, when I click CMake: Configure in VS Code, I can't see the GCC compiler, but only what the last picture shows.

According to the CMake Extension author's video below (at 1:06), I should be able to see GCC compiler:
https://youtu.be/wP4cwAtU-g8?t=66

So, how can I use GCC compiler?
Thanks!

-----

![image](https://user-images.githubusercontent.com/24984500/47998611-e77be300-e0f7-11e8-9e04-cc26ad6a6729.png)
![image](https://user-images.githubusercontent.com/24984500/47998748-4d686a80-e0f8-11e8-9f62-6a6643bae157.png)
![image](https://user-images.githubusercontent.com/24984500/47998828-7e489f80-e0f8-11e8-9142-ec8d42e7ec7f.png)

**Comment by NovaSurfer** [comment]
You need to [add your GCC/G++  location to your `cmake-kits.json` ](https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html)

I've installed vs code like 30 minutes ago, after this [video from CppCon](https://youtu.be/JME1i3vCRR8)
And currently I'm trying to do the same thing as you - add GCC compiler to VSCode on my work PC, I've installed mingw-w64 and add path to gcc in `cmake-kits.json` 
```json
  {
    "name" : "MinGW-w64-GCC",
    "compilers": {
      "CXX": "C:/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++.exe",
      "C": "C:/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/gcc.exe"
    }
  },
...
```

then restart vs_code and now I can select GCC compiler
![](https://habrastorage.org/webt/0x/0s/ix/0x0sixqpgit1y0pndujqznxkpl4.png)

But as soon as I'm trying to build (`> Cmake: Build`) quick start project (`> Cmake: Quick Start`) I'm getting error:

> Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json or your Kit configuration.

**Comment by SolarJuice** [comment]
What you did reminded me to Scan for Kits.
I didn't use your method. Instead I used the command "CMake: Scan for Kits".
After that I can select GCC compiler as well when click "CMake: Configure".
![image](https://user-images.githubusercontent.com/24984500/48008029-c83d7f80-e110-11e8-9aad-29c0f8e2dd60.png)
![image](https://user-images.githubusercontent.com/24984500/48008190-13579280-e111-11e8-99a6-8bcc170a7bc4.png)

However now my problem is when I run "CMake: Configure" using GCC compiler, the following error occurs, different than your error:
![image](https://user-images.githubusercontent.com/24984500/48008153-fde26880-e110-11e8-82d1-44b28a0d6ffd.png)

**Comment by NovaSurfer** [comment]
Finally, cmake-tool can detect my GCC compiler after I've [added migw-w64 to the PATH environment](http://www.mingw.org/wiki/howto_install_the_mingw_gcc_compiler_suite) variable.
Maybe it will help you.
But I'm still getting two erros:
- `Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json or your Kit configuration.`
- `Unhandled exception: Unhandled Promise rejection: build Error: Impossible: CMake driver died immediately after successful configure {}` 
I think that I'm got the same kind of errors like #570 and #539.

**Comment by vector-of-bool** [comment]
@SolarJuice what is the path to your CMake executable on the host machine?

@NovaSurfer I'd defer to the issues you linked. These ones have been persistent and I'm still investigating just what is happening since those errors can appear for a variety of reasons.

**Comment by grays820** [comment]
i got same error。。。need help！

**Comment by tacticalmelonfarmer** [comment]
I too am having this issue, scanning for kits properly finds my gcc-8.2.1 installation from MSYS2, but when actually selecting the kit it throws an unhandled exception

`[rollbar] Unhandled exception: Unhandled Promise rejection: selectKit Error {}`

**Comment by KoeMai** [comment]
MSys2 does not currently supported, by "Scan for kits". But you can create your own kit.
The important part is the `enviromentVariable`.

 ```
 {
    "name": "GCC 7.4.0",
    "compilers": {
      "C": "C:\\msys64\\usr\\bin\\gcc.exe",
      "CXX": "C:\\msys64\\usr\\bin\\g++.exe"
    },
    "preferredGenerator": {
      "name": "Makefiles"
    },
    "environmentVariables": {
      "PATH": "${env:PATH};C:\\msys64\\usr\\bin"
    }
  }
```

Where did you install cmake? Inside of Msys2 or the windows version?

**Comment by tacticalmelonfarmer** [comment]
windows version

**Comment by tacticalmelonfarmer** [comment]
im using a compiler installed through msys not the built-in mingw compiler used by msys.

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If @KoeMai's fix did not address this, or if you require further assistance, please let us know and we can reopen it.
