### ISSUE TITLE
cant specify cmake lists in cmake.configureSettings

### ISSUE THREAD

**Issue by xzcvczx** [microsoft/vscode-cmake-tools#577]
### Brief Issue Summary

when using -DCMAKE_PREFIX_PATHS you use a semi-colon as a path separator, it seems that 
```
"cmake.configureSettings": {
  CMAKE_PREFIX_PATH: "/path/to/a;/path/to/b"
}
```
is not handled correctly by cmake tools the only way i could find to make it work was to use -DCMAKE_PREFIX_PATH=... in configureArgs, i also found that i couldn't get -L to work in configureArgs.

### Apparent Behavior:

it seems the ; is being handled incorrectly, i also tried using `"\"path1;path2\""`

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.12.3 
- **VSCode Version**: 1.28.2 
- **CMake Tools Extension Version**: 1.1.2 
- **Compiler/Toolchain**: clang 10

**Comment by vector-of-bool** [comment]
Hello! Sorry for the delay.

Try passing as a JSON list like so:

```json
"cmake.configureSettings": {
  "CMAKE_PREFIX_PATH": [
    "/path/to/a",
    "/path/to/b"
  ]
}
```
