### ISSUE TITLE
Target debugging is no longer supported with the legacy driver

### ISSUE THREAD

**Issue by bradyjohn** [microsoft/vscode-cmake-tools#581]
Brief Issue Summary

I am unable to use cmake: target debug (CTRL + F5)

    Target debugging is no longer supported with the legacy driver

Platform and Versions

VSC 1.28.2
C/C++ 0.20.1
CMake 0.0.17
CMake Tools 1.1.2 (vector of bool)
CMake Tools Helper 0.2.1
Doxygen Documentation Generator 0.4.1
Include Autocomplete 0.0.4
Python 2018.9.2
Swig(.tpl) 0.0.6
Compiler/Toolchain: GCC 5.4.0

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
