### ISSUE TITLE
cmake configurations BUILD_TESTING strange things

### ISSUE THREAD

**Issue by FlorisColpaert** [microsoft/vscode-cmake-tools#583]
If I build the project from terminal it builds currect with the flag -DBUILD_TESTING=OFF, If i add this configutation this in the project settings and build in VSC. because the BUILD_TESTING argument is not set in the internal cmake sub projects and it fails to build. Tried it with "OFF", false,... nothing does the job...
"cmake.configureSettings": {
        "BUILD_TESTING": "OFF"
    },

**Comment by vector-of-bool** [comment]
Sorry for the delay. There's been a lot on my plate.

You can make CMake Tools print the options it is sending to CMake by turning the log level to maximum. Set `cmake.loggingLevel` to `trace`, and `cmake.enableTraceLogging` to `true`. When you run the configure step, the output channel will contain a line of `CMake flags are [...]`. Paste the contents of that line here and I'll take a closer look.

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
