### ISSUE TITLE
find_package inconsistent with Qt

### ISSUE THREAD

**Issue by LegatusLarvae** [microsoft/vscode-cmake-tools#589]
Hi,
I was making a CMake project in VSC and had problems using Qt5 modules. I'm new to CMake, so I thought I made a mistake and made a new CMake project in QtCreator to see what it should look like (just a simple empty QtQuick project, exactly how Qt creates it without any changes).

In QtCreator I can configure, compile and run the project without a problem. But when I open it in VSC, I get errors.

This is the CMakeLists.txt created by Qt:

cmake_minimum_required(VERSION 3.1)

project(QML_Input LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Qt5 COMPONENTS Core Quick REQUIRED)

add_executable(${PROJECT_NAME} "main.cpp" "qml.qrc")
target_compile_definitions(${PROJECT_NAME} PRIVATE $<$<OR:$<CONFIG:Debug>,$<CONFIG:RelWithDebInfo>>:QT_QML_DEBUG>)
target_link_libraries(${PROJECT_NAME} PRIVATE Qt5::Core Qt5::Quick)

When I open this in VSC, it can't find the Qt packages anymore. If I add 'set(Qt5_DIR xxx)', it finds Qt but the headers are missing, thus I get errors for the #include's.

I have Windows 10, VSC 1.29.1, CMake 3.9.4 and Qt 5.11 with msvc2017_x64

**Comment by vector-of-bool** [comment]
It's likely that QtCreator is being clever and telling CMake where Qt5 lives since it already knows. Don't set `Qt5_DIR` if you can help it. [Check here](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure): You can specify `PATHS` to help `find_package()` find the Qt5 packages. You pass for `PATHS` the directory where your Qt5 installation lives.

As for failing to find headers? I'm not sure on this one. First try fixing `find_package()` and see if the header issue still occurs.

**Comment by LegatusLarvae** [comment]
Hi,
thanks for your reply. I added the Qt directory to the system user registry to make it available permanently, now it finds the package without setting `Qt5_DIR`. But it still doesn't find the headers.

**Comment by vector-of-bool** [comment]
When you say "doesn't find the headers," are you referring to the IntelliSense engine, or the actual compilation of the file?

**Comment by lygstate** [comment]
qt is fine for me

**Comment by LegatusLarvae** [comment]
I checked and I can compile and run the app. The problem seems to be the editor only, so I guess it's IntelliSense.

**Comment by lygstate** [comment]
IntelliSense would fix by the newest version along with my newest pull request

**Comment by LegatusLarvae** [comment]
Can you post a like reagarding this update? I didn't find anything.

**Comment by vector-of-bool** [comment]
Sorry for the delay. The mentioned PR has not been merged.

Fortunately, this should be fixable by a tweak to your `CMakeLists.txt`. I'm assuming the green underlines appear on `#include` directives in _your_ header files? If so, it means that CMake Tools has not found configuration information for your header file. All you need to do is add your project headers to your source lists in `CMakeLists.txt`

**Comment by bobbrow** [comment]
This issue is being closed because it appears to have been abandoned. If you require further assistance, please let us know and we can reopen it.
