### ISSUE TITLE
cpptools Integration - trying to to understand

### ISSUE THREAD

**Issue by enelson1001** [microsoft/vscode-cmake-tools#599]
### Brief Issue Summary
I have just started using VSCode and CMake Tools (CMT).  I came across some problems with include statements in header files.  I have looked at issue #481 as it seems close to what I am seeing.
1. I used CMake: Edit usr-local CMake kits to add my toolchain otherwise my toolchain did not show even though it is in my environmental PATH.  
**Question - Shouldn't CMT automatically detect my compiler if it was in my PATH?**
2. Started new project and selected my toolchain kit and is listed in bottom menu. When popup came up "CMake would like to configure intelliSense for this folder" I clicked allowed.
3. If I opened a header file in my project 1st I would receive a bunch of green squiggle lines on includes.
 
![image](https://user-images.githubusercontent.com/43481343/49104415-24408300-f23b-11e8-9be1-b2427fd87639.png)

But if I open Greetings.cpp 1st and then Greetings.h most green squiggles go away.
![image](https://user-images.githubusercontent.com/43481343/49104493-594cd580-f23b-11e8-9f1b-1841f412d853.png)

Reading issue #481 states you need to open the cpp file first before the header file which the OP thought was fixed.  
**Question - Do we need to open up the cpp file first before the header file?**

4. I want to include header file from external library (esp-idf) whose components are part of the build directory but their CMakeLists.txt files do not contain the *.h files.  In picture below, the build folder shows the driver folder and the freetos folder but I still get the green squiggly lines trying to include headers from their folders.
 
![image](https://user-images.githubusercontent.com/43481343/49105013-b8f7b080-f23c-11e8-8263-c7e7b0953487.png)

If I take the suggestion and add these to IncludePath a new c_cpp_properties file is created and then all the green squiggly lines come back.
![image](https://user-images.githubusercontent.com/43481343/49105355-97e38f80-f23d-11e8-9a5d-c16076770f67.png)

**Question - How do I add these includes and not get the green squiggly lines**

5. If I look at the newly created c_cpp_properties.json file is lists the wrong compiler path.
![image](https://user-images.githubusercontent.com/43481343/49105476-d9743a80-f23d-11e8-835d-fdf8378736d7.png)

**Question - Why is the wrong compiler path listed?**

### Platform and Versions

- **Operating System**:  Linux Mint 18
- **CMake Version**:  3.12.4
- **VSCode Version**:  1.29
- **CMake Tools Extension Version**:  1.1.2
- **Compiler/Toolchain**:  xtensa-esp32-elf-gcc

**Comment by vector-of-bool** [comment]
> Shouldn't CMT automatically detect my compiler if it was in my PATH?

It should. What is you compiler path, and what is the output from `--version`?

> Do we need to open up the cpp file first before the header file?

For an unknown header, cpptools will use the configuration information from a source file which immediately includes that header. If you haven't yet opened a source file that includes the header, it has no choice but to guess. If the header file is associated with a target, then cpptools will not have to guess the configuration.

> How do I add these includes and not get the green squiggly lines?

For this, I do not know. cpptools has a debug more where it will print the how/why it is choosing the configuration for a file. That's you best bet to find out.

> Why is the wrong compiler path listed?

That file is generated by cpptools. I do not know how its default content is decided.

**Comment by enelson1001** [comment]
1. Here is my path.
/home/ed/bin:/home/ed/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ed/esp32-smooth/esp-idf/tools:/home/ed/esp32-smooth/xtensa-esp32-elf/bin

Here is the version.
ed@ed-ideacentre-AIO-910-27ISH ~/esp32-smooth/xtensa-esp32-elf/bin $
xtensa-esp32-elf-gcc-5.2.0 --version
xtensa-esp32-elf-gcc-5.2.0 (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a)
5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

2. If the header file is associated with a target, then cpptools will *not*
have to guess the configuration.
ATask.h and BTask.h are in target in the include folder of target and
smooth/core/Application.h, smooth/core/Task.h and
smooth/core/task_priorites.h are in target in the externals folder but
still get the green squiggly lines if I open header file first.

3. It sounds like the cpptools integration isn't as useful as I thought it
would be and will revert back to c_cpp_properties.json file where I place
all my includePaths and browse paths so my includes will be found.  Other
that this issue CMT is very good.

Thanks

**Comment by vector-of-bool** [comment]
When you open the file in which the green underlines appear, do you receive a warning about missing configuration for that file?

**Comment by huming2207** [comment]
@vector-of-bool @enelson1001 Hi guys, 

It looks like this issue is very similar to mine: https://github.com/vector-of-bool/vscode-cmake-tools/issues/604

Based on my experience, I have just found that CLion works fine with ESP-IDF, KDevelop also fine for ESP-IDF with pure C code but cannot recognise C++ at all. It actually partially works with your plugin and VSCode but there are a lot of annoying false alarms. So I'm suspecting if it can be something wrong with Espressif themselves who designed their CMake build system.

@vector-of-bool, If you need me to test something for solving these issues, please reply me and I will assist you as much as I can.

**Comment by vector-of-bool** [comment]
The goal is that you should not need to edit `c_cpp_properties.json` at all when you are working with a CMake project. If you are finding yourself needing to specify options here, then either there is 1) a CMake Tools bug, 2) a cpptools bug, or 3) your project is misconfigured.

I've seen a lot of instances of (3), and its the easiest thing to fix. I also see instances of (1) and (2), but they are more difficult. Trying to rule out what has gone wrong is the best I can do from where I am.

**Comment by enelson1001** [comment]
vector-of-bool
I created a new project and allowed CMT to configure intellisense.
When I open header files in my project I am receiving the following
notifications.  This time I am not getting any green squiggly lines
under the includes but just these notifications that pop-ups.

[image: image.png]

But I can peek at the Definition.
[image: image.png]

No errors in build.

This is the folder structure.
[image: image.png]

This is the CMakeLists.txt under main folder
[image: image.png]

Why are the notifications popping up?

Thanks

**Comment by huming2207** [comment]
@enelson1001 hey mate, your images are corrupted

**Comment by enelson1001** [comment]
Lets try this again 
Notifications
![selection_015](https://user-images.githubusercontent.com/43481343/49344698-2ee28a00-f638-11e8-84a2-99148e8181c5.png)

Peek Definition
![selection_016](https://user-images.githubusercontent.com/43481343/49344709-546f9380-f638-11e8-9e83-a99c87480939.png)

Folder Structure
![selection_017](https://user-images.githubusercontent.com/43481343/49344720-6e10db00-f638-11e8-987b-1334a4590807.png)

CMakeLists.txt under main folder
![selection_018](https://user-images.githubusercontent.com/43481343/49344741-9b5d8900-f638-11e8-8d6b-f6512a5fd76f.png)

Kit being used
![selection_019](https://user-images.githubusercontent.com/43481343/49344751-b0d2b300-f638-11e8-9b75-6f7b8f408b86.png)


Thanks

**Comment by vector-of-bool** [comment]
This has actually come up often enough that [I've written a section for it in the documentation just yesterday](https://vector-of-bool.github.io/docs/vscode-cmake-tools/common_issues.html#i-see-cmake-tools-is-unable-to-provide-intellisense-configuration). Take a look and see if it fixes your issue. In your case, you will need to add your headers to the `COMPONENT_SRCS` variable.

**Comment by enelson1001** [comment]
Added the includes in the CMakeLists.txt file as shown below and now the pop-ups have disappeared.

![selection_021](https://user-images.githubusercontent.com/43481343/49385928-ae756500-f6db-11e8-9a16-f3db1f3cbcf2.png)


Could you please bold this statement in the new section you wrote yesterday.
"If the file which receives this message is outside of your project, it is safe to ignore it."

I redid another previous project and removed c_cpp_properties.json and the build directory, updated the CMakeLIsts.txt file and restarted the project and  was getting green squiggly lines on the includes outside my project but everything built and ran OK. I reread your new section and it would be helpful if that sentence is bold and stands out.

Thanks for helping me out on this problem.
This issue can be closed.

**Comment by enelson1001** [comment]
One more thing maybe you should include in write-up.

I noticed that when I tried converting project to use cpptools integration it did not always make the settings.json file.

**I assume that CMT when using cpptools integration should always have  the following settings file?**

![selection_022](https://user-images.githubusercontent.com/43481343/49387923-365d6e00-f6e0-11e8-9172-a8bbe381a615.png)

I ended up copying the settings.json file to the .vscode folder and everything worked OK.

Thanks

**Comment by vector-of-bool** [comment]
I'll update the docs as noted.

When you configure your project with CMake, you should have a pop-up message from cpptools asking if you want to enable the integration. Confirming this will add the noted settings to the `settings.json` file without any manual intervention.
