### ISSUE TITLE
Compatibility issues with Espressif ESP-IDF

### ISSUE THREAD

**Issue by huming2207** [microsoft/vscode-cmake-tools#604]
### Brief Issue Summary

First of all, thanks for your great plugin to allow CMake projects works with VSCode. But I've found some issues with ESP-IDF CMake project. When an ESP-IDF CMake project (especially with C++ code and/or header-only libraries) is opened, the plugin cannot handle the included headers correctly.

### Expected:

1. Open an ESP-IDF project
2. Everything works fine 

### Apparent Behavior:

1. Open an ESP-IDF project
2. It may returns this:

![image](https://user-images.githubusercontent.com/4463497/49266046-c5804100-f4a8-11e8-96c0-9bef41d37858.png)

But actually the "missing" headers do exist with correct filesystem permission applied. If I right click the header file and click "Go to definition", it will even jump to that header file correctly, although there are warning exists with underlines.

Also, sometimes if I open some header files, a warning like this will also pops up:

![image](https://user-images.githubusercontent.com/4463497/49266359-00cf3f80-f4aa-11e8-93ca-3fd42bd57f13.png)

### CMake Tools Log

There is no significant logs that indicates a warning/error so far. I will provide that later on my own desktop PC at home, if necessary.

### Developer Tools Log

(Same as above)

### Platform and Versions

- **Operating System**: Ubuntu 18.10, XFCE
- **CMake Version**: 3.12.1
- **VSCode Version**: 1.29.1
- **CMake Tools Extension Version**:  1.13
- **Compiler/Toolchain**: xtensa-esp32-elf-gcc 5.2.0

**Comment by huming2207** [comment]
Hello @vector-of-bool, 

I've done another test with one of my incompleted ESP32 project.

Here is my project: https://github.com/huming2207/QueSera

I haven't got time to continue working on this project these days as I was busy dealing with some other business for work.

Here are the warning screenshots:

![image](https://user-images.githubusercontent.com/4463497/49327644-7117b700-f5b7-11e8-8e6d-182c58d508f9.png)


![image](https://user-images.githubusercontent.com/4463497/49327516-1a11e200-f5b7-11e8-80bc-20fcf946880d.png)

Here is the devtool's log, you can find there are some warnings and errors here: [devtool.log](https://github.com/vector-of-bool/vscode-cmake-tools/files/2635820/devtool.log)


Here is the CMake Tools Log:

```
[cms-client] Configuring using the "Unix Makefiles" CMake generator
[cms-client] Configuring using the "Unix Makefiles" CMake generator
[cmake] Found Git: /usr/bin/git (found version "2.19.1") 
[cmake] Checking Python dependencies...
[cmake] Python requirements from /home/hu/esp/esp-idf/requirements.txt are satisfied.
[cmake] 
[cmake] -- Building empty aws_iot component due to configuration
[cmake] 
[cmake] Component names: soc log heap xtensa-debug-module app_trace freertos vfs newlib esp_ringbuf driver esp_event ethernet lwip tcpip_adapter partition_table app_update spi_flash mbedtls micro-ecc bootloader_support nvs_flash pthread smartconfig_ack wpa_supplicant esp32 cxx u8g2 asio jsmn aws_iot bootloader bt coap console nghttp esp-tls esp_adc_cal tcp_transport esp_http_client esp_http_server esp_https_ota esptool_py expat wear_levelling sdmmc fatfs freemodbus idf_test json libsodium mdns mqtt openssl protobuf-c protocomm spiffs ulp wifi_provisioning main
[cmake] Component paths: /home/hu/esp/esp-idf/components/soc;/home/hu/esp/esp-idf/components/log;/home/hu/esp/esp-idf/components/heap;/home/hu/esp/esp-idf/components/xtensa-debug-module;/home/hu/esp/esp-idf/components/app_trace;/home/hu/esp/esp-idf/components/freertos;/home/hu/esp/esp-idf/components/vfs;/home/hu/esp/esp-idf/components/newlib;/home/hu/esp/esp-idf/components/esp_ringbuf;/home/hu/esp/esp-idf/components/driver;/home/hu/esp/esp-idf/components/esp_event;/home/hu/esp/esp-idf/components/ethernet;/home/hu/esp/esp-idf/components/lwip;/home/hu/esp/esp-idf/components/tcpip_adapter;/home/hu/esp/esp-idf/components/partition_table;/home/hu/esp/esp-idf/components/app_update;/home/hu/esp/esp-idf/components/spi_flash;/home/hu/esp/esp-idf/components/mbedtls;/home/hu/esp/esp-idf/components/micro-ecc;/home/hu/esp/esp-idf/components/bootloader_support;/home/hu/esp/esp-idf/components/nvs_flash;/home/hu/esp/esp-idf/components/pthread;/home/hu/esp/esp-idf/components/smartconfig_ack;/home/hu/esp/esp-idf/components/wpa_supplicant;/home/hu/esp/esp-idf/components/esp32;/home/hu/esp/esp-idf/components/cxx;/home/hu/Projects/QueSera/components/u8g2;/home/hu/esp/esp-idf/components/asio;/home/hu/esp/esp-idf/components/jsmn;/home/hu/esp/esp-idf/components/aws_iot;/home/hu/esp/esp-idf/components/bootloader;/home/hu/esp/esp-idf/components/bt;/home/hu/esp/esp-idf/components/coap;/home/hu/esp/esp-idf/components/console;/home/hu/esp/esp-idf/components/nghttp;/home/hu/esp/esp-idf/components/esp-tls;/home/hu/esp/esp-idf/components/esp_adc_cal;/home/hu/esp/esp-idf/components/tcp_transport;/home/hu/esp/esp-idf/components/esp_http_client;/home/hu/esp/esp-idf/components/esp_http_server;/home/hu/esp/esp-idf/components/esp_https_ota;/home/hu/esp/esp-idf/components/esptool_py;/home/hu/esp/esp-idf/components/expat;/home/hu/esp/esp-idf/components/wear_levelling;/home/hu/esp/esp-idf/components/sdmmc;/home/hu/esp/esp-idf/components/fatfs;/home/hu/esp/esp-idf/components/freemodbus;/home/hu/esp/esp-idf/components/idf_test;/home/hu/esp/esp-idf/components/json;/home/hu/esp/esp-idf/components/libsodium;/home/hu/esp/esp-idf/components/mdns;/home/hu/esp/esp-idf/components/mqtt;/home/hu/esp/esp-idf/components/openssl;/home/hu/esp/esp-idf/components/protobuf-c;/home/hu/esp/esp-idf/components/protocomm;/home/hu/esp/esp-idf/components/spiffs;/home/hu/esp/esp-idf/components/ulp;/home/hu/esp/esp-idf/components/wifi_provisioning;/home/hu/Projects/QueSera/main
[cmake] The ASM compiler identification is GNU
[cmake] Found assembler: /home/hu/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
[cmake] The C compiler identification is GNU 5.2.0
[cmake] The CXX compiler identification is GNU 5.2.0
[cmake] Check for working C compiler: /home/hu/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
[cmake] Check for working C compiler: /home/hu/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -- works
[cmake] Detecting C compiler ABI info
[cmake] Detecting C compiler ABI info - done
[cmake] Detecting C compile features
[cmake] Detecting C compile features - done
[cmake] Check for working CXX compiler: /home/hu/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++
[cmake] Check for working CXX compiler: /home/hu/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ -- works
[cmake] Detecting CXX compiler ABI info
[cmake] Detecting CXX compiler ABI info - done
[cmake] Detecting CXX compile features
[cmake] Detecting CXX compile features - done
[cmake] Adding linker script /home/hu/Projects/QueSera/build/esp32/esp32_out.ld
[cmake] Adding linker script /home/hu/esp/esp-idf/components/esp32/ld/esp32.common.ld
[cmake] Adding linker script /home/hu/esp/esp-idf/components/esp32/ld/esp32.rom.ld
[cmake] Adding linker script /home/hu/esp/esp-idf/components/esp32/ld/esp32.peripherals.ld
[cmake] Adding linker script /home/hu/esp/esp-idf/components/esp32/ld/esp32.rom.libgcc.ld
[cmake] Adding linker script /home/hu/esp/esp-idf/components/esp32/ld/esp32.rom.spiram_incompatible_fns.ld
[cmake] Building empty aws_iot component due to configuration
[cmake] Component libraries: soc;log;heap;xtensa-debug-module;app_trace;freertos;vfs;newlib;esp_ringbuf;driver;esp_event;ethernet;lwip;tcpip_adapter;app_update;spi_flash;mbedtls;micro-ecc;bootloader_support;nvs_flash;pthread;smartconfig_ack;wpa_supplicant;esp32;cxx;asio;jsmn;aws_iot;bt;coap;console;nghttp;esp-tls;esp_adc_cal;tcp_transport;esp_http_client;esp_http_server;esp_https_ota;expat;wear_levelling;sdmmc;fatfs;freemodbus;idf_test;json;libsodium;mdns;mqtt;openssl;protobuf-c;protocomm;spiffs;ulp;wifi_provisioning;main
[cmake] Configuring done
[cmake] Generating done

```


You may also refer to this article written by Espressif, which may help for you to solve this issue: [Build System (CMake) - Build System Metadata](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system-cmake.html#build-system-metadata)

If you need any further assistances, please reply me soon and I will provide my help as much as I can.

Regards,
Jackson

**Comment by vector-of-bool** [comment]
The important bit is the "unable to provide IntelliSense configuration information" message. This shows up when you open a file that isn't known to CMake. This is usually because the headers are not added to a target. Try adding these header files to the source lists for the target and see if anything changes?

**Comment by huming2207** [comment]
@vector-of-bool Thanks for your reply. It looks like the whole include path setting is somehow screwed up.

For example, if I add one of the components into the include path, then another component which it depends on also needs to add into the include path:

![image](https://user-images.githubusercontent.com/4463497/49336868-079eb380-f65e-11e8-9965-965954e0b149.png)

![image](https://user-images.githubusercontent.com/4463497/49336883-50ef0300-f65e-11e8-950d-672a6c8c8a07.png)

Here are the files generated by the ESP-IDF's CMake build system (the`build` directory): [build.tar.gz](https://github.com/vector-of-bool/vscode-cmake-tools/files/2636730/build.tar.gz)

Could you please help me and take a look and see if they actually missed something? Thanks in advance!!

Regards,
Jackson

**Comment by vector-of-bool** [comment]
Do not tweak the `c_cpp_properties.json` file. You need to edit your `CMakeLists.txt` add your `*.h` files to your `COMPONENT_SRCS` list. Run CMake re-configure and try again.

**Comment by huming2207** [comment]
@vector-of-bool Thanks. Now looks like problem solved. I will try again tomorrow with my company's project and confirm with you again then.

**Comment by vector-of-bool** [comment]
The IntelliSense configuration does not use the compilation database, and it is all on a per-file basis. If a source file is not associated with a target, that source file will have no associated configuration information. If a header file is not attached to a target, that header file will have no configuration information, and will therefore have no include directories. This causes the include errors you see in the editor.

**Comment by huming2207** [comment]
@vector-of-bool Thanks for your reply. But how does the VSCode c/C++ plugin eventually knows the CMake indexing details? Does your plugin help it to parse the related data from `compile_commands.json`?

**Comment by huming2207** [comment]
Since I have provided my header locations to `COMPONENT_ADD_INCLUDEDIRS`, so I think the ESP-IDF's build should somehow pass this information to the `compile_commands.json` or some other build manifests that allows IDE or some editor plugins to parse. I'm not sure if the build system has actually serialized these stuff to the `compile_commands.json`. If it doesn't, then I probably should report a bug to them?

**Comment by vector-of-bool** [comment]
The cpptools integration does not use `compile_commands.json`. CMake offers the required information via cmake-server mode, which CMake Tools uses to obtain this information more reliably and correctly that is available in `compile_commands.json`.

If the header dirs in `COMPONENT_ADD_INCLUDEDIRS` do not appear in `compile_commands.json`, I can't be sure what is going wrong. I'd need to see what their CMake code is doing.

**Comment by huming2207** [comment]
Hi @vector-of-bool, thanks for your reply. I have no idea for the CMake server. I will redirect it to the ESP-IDF maintainers and see what they will comment on it.

**Comment by huming2207** [comment]
Hi @vector-of-bool  I've just got the reply from the ESP-IDF guys. That is what he said: https://github.com/espressif/esp-idf/issues/2772#issuecomment-445723575

Looks like it is possible that some of the include directories haven't been handled correctly.

By the way, how did you debug the communication/parsing between your plugin and CMake server? Is there any MITM proxies (e.g. Fiddler or MitmProxy) can do the trick?

**Comment by huming2207** [comment]
Hi @bobbrow and @bjosa ,

Thanks for your PR! 

I would like to help to test it if it is fixed or not. Is there any instructions for building this plugin and load it into VSCode?

Regards,
Jackson

**Comment by huming2207** [comment]
I'll close this issue for now as it marked as fixed anyway. I'm looking forward to getting the next update and I'll test it out by then.
