### ISSUE TITLE
CMake Configuration broken after upgrade to 1.1.3

### ISSUE THREAD

**Issue by matsaleh13** [microsoft/vscode-cmake-tools#607]
### Brief Issue Summary

After VS Code auto-updated CMake Tools to v1.1.3, my CMake configuration broke, and I could no longer build. When I tried to do a clean reconfigure, I got the output shown in the log section below. In addition, the kit "Clang 6.0.1 for MSVC with Visual Studio Community 2017 (amd64)" had disappeared from my list of kits.

### Expected:

1. Configure project.
2. No errors, able to build.

### Apparent Behavior:

1. Configure project.
2. CMake (Tools) reports errors shown below.

### CMake Tools Log

Output of build panel:

  ```cmake
  [cms-client] Configuring using the "Ninja" CMake generator
  [cmake] The C compiler identification is Clang 6.0.1
  [cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeDetermineCompilerId.cmake:793 (message):
  [cmake]   The Clang compiler tool
  [cmake] 
  [cmake]     "C:/Program Files/LLVM/bin/clang.exe"
  [cmake] 
  [cmake]   targets the MSVC ABI but has a GNU-like command-line interface.  This is
  [cmake]   not supported.  Use 'clang-cl' instead, e.g.  by setting 'CC=clang-cl' in
  [cmake]   the environment.  Furthermore, use the MSVC command-line environment.
  [cmake] Call Stack (most recent call first):
  [cmake]   C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeDetermineCCompiler.cmake:113 (CMAKE_DIAGNOSE_UNSUPPORTED_CLANG)
  [cmake]   CMakeLists.txt:2 (project)
  [cmake] 
  [cmake] 
  [cmake] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  [cmake] Configuring incomplete, errors occurred!
  ```

Also, when the above problem occurs, it seems that the kit `Clang 6.0.1 for MSVC with Visual Studio Community 2017 (amd64)` is missing from the list of available kits, leaving only the entries for MSVC amd64 and win32.

After trying a number of things (uninstall/reinstall CMake Tools, uninstall/reinstall other extensions, etc.) I finally reverted CMake Tools back to v 1.1.2, then did a "clean reconfigure" and the problem did not occur.

NOTE: I reverted CMake Tools using a new feature in the VS Code Insiders build (see: https://github.com/Microsoft/vscode/issues/12764#issuecomment-442370545). Then, I copied the v1.1.2 extension folder from the .vscode-insiders\extensions folder to .vscode\extensions.

I was able to repeatedly reproduce this problem by changing the version from 1.1.2 to 1.1.3 and back. It reliably works in 1.1.2 but not 1.1.3.

### Platform and Versions

- **Operating System**: Windows 10 Professional version 1803 build 17134.407
- **CMake Version**: 3.12.1
- **VSCode Version**: 1.29.1 (and 1.30.0-insider)
- **CMake Tools Extension Version**: 1.1.3 (works fine in 1.1.2)
- **Compiler/Toolchain**: Visual C++ 2017

NOTE: I did not include the actual CMake Tools log file because it appears to be a jumbled mess because of my uninstalling/installing different versions of CMake Tools.

**Comment by vector-of-bool** [comment]
Thank you for a very detailed report!

It looked to be that discovery of `clang-cl` is failing in 1.1.3. I'll look into it.

**Comment by yiakwy** [comment]
Hi, have a look at #618 I think we can do better.

**Comment by j-m** [comment]
Any news on this? Downgrading doesn't work for me.
The kit file was renamed from cmake-tools.json in 1.1.2 to cmake-tools-kits.json in 1.1.3, could that have had any bearing?
I'm using Clang 8.0.0 and CMake 3.14, and the error occurs on a different line:
CMakeDetermineCompilerId.cmake:859
