### ISSUE TITLE
[rollbar] Unhandled exception: Unhandled Promise rejection: build TypeError: Cannot read property '0' of undefined {}

### ISSUE THREAD

**Issue by narutojxl** [microsoft/vscode-cmake-tools#608]
when i  build a cpp project in VS Code, it print 

> [rollbar] Unhandled exception: Unhandled Promise rejection: build TypeError: Cannot read property '0' of undefined {}

My VS Code version="1.29.1",   ubuntu 14.04,   when type `cmake  --version`, its output is "cmake version 3.12.3" ,  g++ --version  ="g++ (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4".  I also install some VS Code  extension,  C/C++ 0.20.1,   CMake 0.0.17,  CMake Tools 1.1.3. BTW,  when i installed ubuntu14.04.5,  there is a cmake has been install  in `/usr/bin/cmake  /usr/lib/cmake /usr/bin/X11/cmake  /usr/share/cmake `, all cmakes installed by myself are all installed as default  in  `/usr/local/`.

 

CMakeLists.txt is as follows:

>cmake_minimum_required(VERSION 2.8.3)
project(svd_p3p)
add_compile_options(-std=c++11)
find_package(catkin REQUIRED COMPONENTS
  roscpp
)
find_package(Eigen3 REQUIRED)
catkin_package(
  INCLUDE_DIRS include
#LIBRARIES svd_p3p
#CATKIN_DEPENDS roscpp
#DEPENDS system_lib
)
include_directories(
 include
  ${catkin_INCLUDE_DIRS}
  ${EIGEN3_INCLUDE_DIR}
)
 add_library(
   svd_p3p
   src/svd_p3p.cpp
 )
 add_executable(localization_error  src/localization_error.cpp)
 target_link_libraries(localization_error
   svd_p3p
   ${catkin_LIBRARIES}  
 )

when i uninstall cmake 3.12.3,   type  `cmake --version`, its output is cmake version 2.8.12.2. Reload VS Code,  its output is `[main] CMake Server is not available with the current CMake executable. Please upgrade to CMake 3.7.1 or newer.
[rollbar] Unhandled exception: Unhandled Promise rejection: build TypeError: Cannot read property '0' of undefined {}`

Again i install cmake 3.7.1, type `cmake --version`, output cmake version 3.7.1, but reload VS Code and rebuild project, it didn't find cmake 3.7.1, its output is the same as shown above.

Again i uninstall cmake 3.7.1, install  cmake 3.7.2 , reload VS Code, its output is `[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: connect ENOENT /tmp/cmake-server-0.6890532608944027 {}`

Any help will be much appreciated, thanks in advance!

**Comment by narutojxl** [comment]
when i uninstall all cmakes installed by myself, then reload VS Code is OK, it can build successfully, but can not debug. When launch debug, its output is 

> [build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/jxl/jxl_ws/src/svd_p3p/build --config Debug --target all -- -j 6
[build] [1/4  25% :: 0.000] Building CXX object CMakeFiles/svd_p3p.dir/src/svd_p3p.cpp.o
[build] [2/4  50% :: 7.713] Linking CXX shared library devel/lib/libsvd_p3p.so
[build] [3/4  75% :: 8.063] Building CXX object CMakeFiles/localization_error.dir/src/localization_error.cpp.o
[build] [4/4 100% :: 8.862] Linking CXX executable devel/lib/svd_p3p/localization_error
[build] Build finished with exit code 0
[main] =======================================================
[main] No executable target was found to launch. Please check:
[main]  - Have you called add_executable() in your CMake project?
[main]  - Have you executed a successful CMake configure? 
[main] No program will be executed

According to [Target Debugging and Launching in CMake Tools]( https://vector-of-bool.github.io/docs/vscode-cmake-tools/index.html), 

> Debugging is only supported when using CMake Server mode. This mode will be enabled automatically on CMake versions at least as new as 3.7.2, but is completely unavailable on older CMake versions.

I am a ROS users, when i try to remove cmake 2.8.12.2 installed by  ubuntu 14.04 or ROS-indigo(I am not sure which installed this cmake), it reminds me it will also remove many ROS bags, which i do not want. So  without  removing the native cmake installed by ubuntu or ROS, how to installed cmake >3.7.2, and then let VS Code's CMake extension tool to use this cmake,  so  i can debug project with VS Code.

**Comment by TheErk** [comment]
I guess you could simply install a newer cmake version in an alternative path

/usr/local/cmake-3.13/etc...

you can get pre-compiled version here: https://cmake.org/download/

In vscode configuration you should be able to point cmake.cmakePath to the right cmake.
Or you may change your PATH variable (in your .bashrc) in order to put /usr/local/cmake-3.13/bin before
/usr/bin/ so that "which cmake" shows the version of cmake you want to use.
If you relaunch vscode in the modified environment it'll probably pickup the appropriate cmake version.

When you change CMake version you shall remove previously configured build directory which contains the old reference to /usr/bin/cmake

**Comment by narutojxl** [comment]
I tried to install cmake 3.13.1 to `/home/jxl/cmake-3.13.1/INSTALL_JXL/` and  modified  `vscode cmake.cmakePath=/home/jxl/cmake-3.13.1/INSTALL_JXL/bin/cmake` and  `export PATH=/home/jxl/cmake-3.13.1/INSTALL_JXL/bin/cmake:$PATH`, reload vscode . it  output: 

> [cms-client] Configuring using the "Ninja" CMake generator
[cms-client] Configuring using the "Ninja" CMake generator
[cmake] The C compiler identification is GNU 4.8.4
[cmake] The CXX compiler identification is GNU 4.8.4
[cmake] Check for working C compiler: /usr/bin/gcc-4.8
[cmake] Check for working C compiler: /usr/bin/gcc-4.8 -- works
[cmake] Detecting C compiler ABI info
[cmake] Detecting C compiler ABI info - done
[cmake] Detecting C compile features
[cmake] Detecting C compile features - done
[cmake] Check for working CXX compiler: /usr/bin/g++-4.8
[cmake] Check for working CXX compiler: /usr/bin/g++-4.8 -- works
[cmake] Detecting CXX compiler ABI info
[cmake] Detecting CXX compiler ABI info - done
[cmake] Detecting CXX compile features
[cmake] Detecting CXX compile features - done
[cmake] Using CATKIN_DEVEL_PREFIX: /home/jxl/jxl_ws/src/svd_p3p/build/devel
[cmake] Using CMAKE_PREFIX_PATH: /home/jxl/carto_ws/install_isolated;/home/jxl/jxl_ws/devel;/opt/ros/indigo
[cmake] This workspace overlays: /home/jxl/carto_ws/install_isolated;/home/jxl/jxl_ws/devel;/opt/ros/indigo
[cmake] Found PythonInterp: /usr/bin/python (found version "2.7.6") 
[cmake] Using PYTHON_EXECUTABLE: /usr/bin/python
[cmake] Using Debian Python package layout
[cmake] Using empy: /usr/bin/empy
[cmake] Using CATKIN_ENABLE_TESTING: ON
[cmake] Call enable_testing()
[cmake] Using CATKIN_TEST_RESULTS_DIR: /home/jxl/jxl_ws/src/svd_p3p/build/test_results
[cmake] Looking for pthread.h
[cmake] Looking for pthread.h - found
[cmake] Looking for pthread_create
[cmake] Looking for pthread_create - not found
[cmake] Looking for pthread_create in pthreads
[cmake] Looking for pthread_create in pthreads - not found
[cmake] Looking for pthread_create in pthread
[cmake] Looking for pthread_create in pthread - found
[cmake] Found Threads: TRUE  
[cmake] Found gtest sources under '/usr/src/gtest': gtests will be built
[cmake] Using Python nosetests: /usr/bin/nosetests-2.7
[cmake] catkin 0.6.19
[cmake] CMake Error at CMakeLists.txt:22 (find_package):
[cmake]   By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
[cmake]   asked CMake to find a package configuration file provided by "Eigen3", but
[cmake]   CMake did not find one.
[cmake] 
[cmake]   Could not find a package configuration file provided by "Eigen3" with any
[cmake]   of the following names:
[cmake] 
[cmake]     Eigen3Config.cmake
[cmake]     eigen3-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
[cmake]   "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] See also "/home/jxl/jxl_ws/src/svd_p3p/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "/home/jxl/jxl_ws/src/svd_p3p/build/CMakeFiles/CMakeError.log".
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.

In CMakeLists.txts, i have find Eigen3, but the local cmake can not find it, missing something??

**Comment by narutojxl** [comment]
In  `/usr/share/cmake-2.8/Modules/` there is  FindEigen3.cmake, but in our locally installed cmake `~/cmake-3.13.1/INSTALL_JXL/share/cmake-3.13/Modules/` there is no FindEigen3.cmake file, so `jxl@lenovo:/usr/share/cmake-2.8/Modules$  sudo cp -r FindEigen3.cmake   ~/cmake-3.13.1/INSTALL_JXL/share/cmake-3.13/Modules/`, reload vscode, now it can build successfully, but can not debug,  when launch debug(F5), there is active launch target is shown in the status bar to the right of the Debug button not as  [Selecting a Launch Target](https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html)  said,  launch.json is:

> {
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/devel/lib/svd_p3p/localization_error",
            //"program": "${command:cmake.launchTargetPath}",
            "args": [
                "/home/jxl/jxl_ws/src/svd_p3p/build/devel/lib/svd_p3p/amcl_laser_track_transform.txt",
                "/home/jxl/jxl_ws/src/svd_p3p/build/devel/lib/svd_p3p/amcl_laser_track_sample_datas.txt"
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [
                {
                    "name": "PATH",
                    "value": "/home/jxl/cmake-3.13.1/INSTALL_JXL/bin/cmake:$PATH"
                },
            ],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

**Comment by andreeis** [comment]
We fixed several similar issues since this was opened and also fileApi deprecates CMakeServer. It's recommended that you upgrade CMake Tools to latest (today that is 1.3.1) and CMake to latest or at least 3.15. Reopen if you still have problems.
