### ISSUE TITLE
Unable to scan toolkits.

### ISSUE THREAD

**Issue by pokowaka** [microsoft/vscode-cmake-tools#611]
### Brief Issue Summary

Unable to use under windows 10. Scanning for toolkit fails

### Expected:

Be able to scan for toolkit

### CMake Tools Log

[kit] Error: ENOENT: no such file or directory, open 'C:\Users\XX\AppData\Local\Temp\vs-cmt-0.2646040883366907.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\XX\AppData\Local\Temp\vs-cmt-0.5676718415170368.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\XX\AppData\Local\Temp\vs-cmt-0.7996598566719535.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\XX\AppData\Local\Temp\vs-cmt-0.5296463357321997.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\XX\AppData\Local\Temp\vs-cmt-0.5546743853638219.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\XX\AppData\Local\Temp\vs-cmt-0.058505082376307804.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\XX\AppData\Local\Temp\vs-cmt-0.3845789596045024.bat.env'

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: cmake version 3.12.18081601-MSVC_2
- **VSCode Version**: 1.29.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017

### Other Notes/Information

Completely removing cmake-tools does not fix the issue.

**Comment by pokowaka** [comment]
I've done some debugging, and can now provide you with something useful:

The generation of the batch file in:


async function collectDevBatVars(devbat: string, args: string[], major_version:number, common_dir:string): Promise<Map<string, string>|undefined>

depends on the existence of the file ${devbat}.  However it is possible for that file not to exists, causing no .env file to be written.

In my case: 

devbat="C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat"

Which does not exist, causing the following failure in the batch script:

call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat" amd64 || exit


(Note that I do have a working VS install in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build)

Weirdness likely happened as part of some automation we are tying to do here which calls choco install of visual studio.

**Comment by pokowaka** [comment]
Introduced in https://github.com/vector-of-bool/vscode-cmake-tools/commit/3d042b3fe045b5d7dc53110d2dbab38bc24f837f

Options:
 - Include the guid in the name, so that multiple VS installs do not git merged into one.
 - Revert the change.

@lygstate any ideas or suggestions? This bug makes the plugin unusable for me

**Comment by pokowaka** [comment]
I have a possible solution, I will send a pull request shortly.

**Comment by blakehurd** [comment]
Hello, per the wording of this issue, would this potentially help with CMake Tools not discovering msvc_x64 / x64 kit when it scans? It picks up amd64, x86, amd64_arm, etc., but does not clearly pick up x64 separately even though the requisite exe/etc. are located right next to x86 per the Visual Studio Installer. Ended up needing to define a kit anyway to specify a vcpkg toolchain, but would've helped to have this at the start.

**Comment by andreeis** [comment]
This was fixed several releases ago. Let us know if anything isn't working as expected, after upgrading to latest CMake Tools.
