### ISSUE TITLE
Using ${buildKit} in c_cpp_properties.json not working

### ISSUE THREAD

**Issue by hriekehof** [microsoft/vscode-cmake-tools#615]
### Brief Issue Summary

It's really great that since version 1.1.2 the ${buildKit} variable is use able for defining the build directory. With this i can multiple toolchains with separate build folders without rebuilding everything.
I currently get an error with cpp-tools though, which looks for the compile_commands.json

![image](https://user-images.githubusercontent.com/9348635/50217126-22746600-0388-11e9-8f5a-9abc8aa15cfa.png)

This is true since my `cmake.buildDirectoty` includes the ${buildKit} variable. It seems the same variable can't be used in the c_cpp_properties.json. I have to add the exact path by hand and also have to change it, when i switch my kit for different toolchain file.

### Expected:

Would be great if ${buildKit} would work in `c_cpp_properties.json` but i'm not sure if this is the right approach. It might be more of an issue for the cpp-tools. 

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.13.1
- **VSCode Version**: 1.30.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: arm-none-eabi-gcc

**Comment by StiventoUser** [comment]
Hi, is there any news about it?

**Comment by hriekehof** [comment]
i think this issue would also be resolved when the "configuration provider" for the cpp tools would work correctly. I need the buildKit variable to find the compile_commands.json with multiple kits.
I wasn't aware when i wrote the ticket, that there is a configuration provider for the cpp_tools extension.

In my current configuration the cmake-tools.configuration provider seems not to work correctly when multiple kits with multiple toolchain files are configured. In this case intellisense is not working correctly with the configuration provider. This is why i want to use the compile_commands.json and directly and there it would be handy when the $buildKit variable would work

**Comment by mjvk** [comment]
Would it not be possible to have something like ${command:cmake.buildDirectory} with the ${buildKit} and such already resolved, similar to ${command:cmake.launchDirectory}? This would also help me for other artifacts being produced such as coverage reports.

**Comment by bobbrow** [comment]
@hriekehof , can you provide us with more information about your configuration?  As you indicated, fixing the configuration provider seems like the better approach since cpptools doesn't have an awareness of extension-specific variables and commands.

**Comment by hriekehof** [comment]
sorry for answering so late. I think the problem i had here was during a time when the configuration provider of the `cmake-tools` extenstion was not working correctly. So i wanted to use the `compile_commands.json` directly in the cpp extension. 
The place of the file switches with different build configurations using the `${buildKit}` variable. So i had to update the `c_cpp_properties.json` everytime  i switched the kits. 

I guess this is not a real problem right now anymore since the `configurationProvider` just works i assume. 
Atm i use the `cmake-integration` extension for its support of multiroot workspaces so i cannot test this quickly right now :)

For me this can be closed

**Comment by bobbrow** [comment]
Ok, thanks for following up.  FWIW, we are testing a preview version of the extension with multi-root support and plan to make it available soon.

**Comment by hriekehof** [comment]
ah great to hear that. i looking forward to it
