### ISSUE TITLE
[Fea] CMake projects Xcode equivalent generator support

### ISSUE THREAD

**Issue by yiakwy** [microsoft/vscode-cmake-tools#618]
## Background

In xcode, we can configure cmake to export a "cmake_command.json" file, which will be used by xcode later to generate a xcode project

> cmake ${args} -G xcode -H"${ROOT}" -B"${ROOT}/xcode/"

It is user-friendly to make better use of existing CMake project configured in vim and xcode.

However, cmake does not support vscode generator. The current generators it support compromise:

1. Unix Makefile
2. Ninja
3. Xcode
4. CodeBlocks
...
8. Sublime Text 2
9. Eclipse CDT4

One single instruction, all of the project will be generated based on our existing CMake system. I would like to know whether an equivalent method is there.

### Brief Issue Summary

I am using VSCode in Ubuntu 18.04 system. But more often I would like to code in vim for c++ projects development. I would like to generate VSCode project using a single instruction based on existing CMake system (multi targets and modules) so that I can immediately edit vscode editor without touching its configuration system again (I don't need to use it. g++/clang++ + CMake is just enough. I have my own scripts to manage tasks.). Just like what I did in Xcode (MacOS 13)

### Expected:

> cmake ${args} -G code -H"${ROOT}" -B"${ROOT}/vscode/"

The documentation is too complex. Compared to own my experience in Xcode and Cmake projects, it could be as simple as one single instruction.

**Question**

Could it be possible and as simple as one statement?

### Apparent Behavior:

Import existing Cmake projects into vscode and generates corresponding files in an assigned directory, for example "vscode/". And I have multiple editors environment in parallel.

The concept of CMake generator is confused in vscode. It could be either a generator of a cmake project or one with vscode configurations files for existing CMake projects.

### Platform and Versions

- **Operating System**:  Ubuntu 18.04
- **CMake Version**:  Latest
- **VSCode Version**:  Latest
- **CMake Tools Extension Version**:  I am considering whether this is a right tool to my problem. 
- **Compiler/Toolchain**:  clang++, libc++,llvm

**Comment by KoeMai** [comment]
Vscode-cmake Tool is not part of cmake and it does not has its own project files build system. 

Your setup sounds like a prepare workspace, which an already configured cmake build. It is possible to use the vscode cmake tool without configuration. There for you can select the kit "unspecified" and use your preconfigured cmake build environment.

**Comment by yiakwy** [comment]
@KoeMai 

What do you mean by "use the vscode cmake tool without configuration" ?

I referred an article which used vscode v1.0.0 configuration as reference.

Here are my vscode configuratoin:

## task.json

```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "command": "sh",
    "args": ["-c"],
    "options": {
        "cwd": "${workspaceRoot}/vscode" 
    },
    "tasks": [
        {
            "label": "cmake",
            "type": "shell",
            "command": "cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug ..",
            "problemMatcher": [
                "$gcc"
            ]
        }, {
            "label": "make",
            "args": ["make -j 8"],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

## c_cpp_properties.json

```javascript
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/clang++-6.0",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "clang-x64"
        }
    ],
    "version": 4
}
```

## launch.json

Do I need to specify every targets in my cmake  sub projects ?

```javascript
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "lldb-mi",
            "request": "launch",
            "target": "./bin/pcl_viewer",
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

**Comment by KoeMai** [comment]
Vscode-cmaketool does the configuration you deacribe in the backend for you. And it works already.the cmake tool extension. Checks for a cmakelists.txt in an opened folder and allows directly to build Your project. Please try it out or read the documentation.

**Comment by yiakwy** [comment]
@KoeMai Thanks for your answer. Let me make the problem specific:
1) first part the documentation "Get started", is about how to generate a cmake file which is definitely unrelated to my topic
2) Yes "> CMake: Build" will start building a project, but how does the vscode find the debugger and comipler? No instructions about it. We just found it along the way.
3) A CMake project typically has many modules. Where can we set a target for a debuger, for example llvm lldb ?

**Comment by bobbrow** [comment]
To pass args to the target while debugging, use this setting:
```
    "cmake.debugConfig": {
        "args": [ "arg1", "arg2" ]
    },
```

**Comment by Sunbreak** [comment]
CMake use `Unix Makefile` by default. VSCode CMake Tools use `Ninja` by default

Any idea how to config VSCode CMake Tools use `Xcode` on macOS?

**Comment by bobbrow** [comment]
@Sunbreak, try setting the `cmake.generator` setting if you want to select a specific generator.

**Comment by gcampbell-msft** [comment]
Seems like this question is answered. 

In short, you can explicitly set your generator, in kit scenarios, by setting `cmake.generator`. 
The easier way to do this and have more flexibility is to switch to CMake Presets, and you'll have full control over your configuration and what generator is being used. 

THanks!
