### ISSUE TITLE
Debug build stops (like #387)

### ISSUE THREAD

**Issue by alexbichkov** [microsoft/vscode-cmake-tools#621]
Same as the topic Build stops (like #387) #492

[vector-of-bool.cmake-tools-unresponsive.cpuprofile.txt](https://github.com/vector-of-bool/vscode-cmake-tools/files/2713574/vector-of-bool.cmake-tools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `cmake-tools`
- Extension Version: `1.1.3`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/sania/vector-of-bool.cmake-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by alexbichkov** [comment]
Trying to compile debug config with gcc 7.3 in Ubuntu 16.04 LTS, but extension is unresponsive, occupies all CPU cores, build process progresses very slowly. No problems with release config though.

**Comment by andreeis** [comment]
We did not have this exact symptom in the repros we worked on while going through our extension GitHub issues but there were several fixes in this area. Please upgrade to latest CMake Tools and reopen if this problem is not solved.
