### ISSUE TITLE
Indentation within if/function/macro/etc

### ISSUE THREAD

**Issue by rcdailey** [microsoft/vscode-cmake-tools#628]
When typing if conditions, for loops, functions, macros, and other commands with a corresponding "end" command, there is no automatic indentation. Today, I get this:

```
if(WIN32)
add_library(foo main.cpp)
endif()
```

I expect indentation within `if` and `endif` scope to be indented:

```
if(WIN32)
    add_library(foo main.cpp)
endif()
```

**Comment by Quincunx271** [comment]
CMakeTools doesn't do CMake language support, just things regarding running CMake. I think this issue should be on the [CMake](https://github.com/twxs/vs.language.cmake) extension.
