### ISSUE TITLE
Environment Issues

### ISSUE THREAD

**Issue by ca-mtg** [microsoft/vscode-cmake-tools#629]
It seems as though the extension creates a new command line environment rather than using the VSCode environment. I have a large project with many environment variables required, which cannot be part of my bashrc for various strange compatibility reasons. I was able to get VSCode to source two scripts on startup using tasks.json to set these environment variables, but when I use the cmake extension it seems to make a new terminal session without using this environment setup. As a result, the configuration fails and I'm unable to use the extension for both building and also intellisense. 

Is there a way to do what I'm looking for that I've overlooked? Thanks in advance for any help!

### Platform and Versions
- **Operating System**: Oracle Linux (RHEL based, I believe)
- **CMake Version**: Project uses 3.2.3, but I have 3.12.3 installed for the sake of the extension.
- **VSCode Version**: 1.30.2
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: GCC 5.3.0

**Comment by Randshot** [comment]
@ca-mtg the hard coded build flags were removed, since the user can manually add them via `buildArgs`.
Going to close this one for now.

**Comment by Randshot** [comment]
Sry, wrong PR :)

**Comment by andreeis** [comment]
@ca-mtg, you can define environment variables in the kit that you are using.
Let us know if this doesn't work well for you.
https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html
