### ISSUE TITLE
Full RAM usage upon directory/file deletion

### ISSUE THREAD

**Issue by siniarskimar** [microsoft/vscode-cmake-tools#631]
### Brief Issue Summary

Directory/file used in cmake configure step gets deleted or switching branches results in 100% RAM usage, slowing down the computer and forcing the user to reboot the computer.

### Expected:

1. Important file/directory tries to get deleted (eg. directory used during configure step) or become unavailable (eg. git checkout)
2. Error popup

### Apparent Behavior:

1. Important file/directory to gets deleted (eg. directory used during configure step) or becomes unavailable (eg. git checkout)
2. 'Administrator privileges' popup (Choice doesn't matters)
3. "Cannot move file/directory to trash. Delete permanently?" VSCode popup (Choice doesn't matters)
4. RAM gets used up to 100%
5. Computer slows down, forcing to reboot the computer

### Platform and Versions

- **Operating System**: Windows 7 
- **CMake Version**: 3.13.1 
- **VSCode Version**: 1.30.2 
- **CMake Tools Extension Version**: 1.1.3 
- **Compiler/Toolchain**: GCC 8.2.1 (MSYS MINGW64)

### Other Notes/Information

Looking at process manager this might be a CMake Server issue.
When deleting a file/directory sometimes an error can be seen about Promise error

**Comment by siniarskimar** [comment]
Version controls extensions don't have anything to do here. This bug happens only when some action is taken like branch change or revert to older commit.
In case of subdirectories (add_subdirectory) this might be that CMake server holds a lock on directory but not on the files it contains. I think it's like that because if i try to delete a directory used in CMake add_subdirectory all files under it are gone without the need of administrator privileges.

**Comment by sialiuk** [comment]
I faced the same issue.

**Comment by siniarskimar** [comment]
This issue seems to be fixed with the CMake Server File Api
