### ISSUE TITLE
Add possibility to save 'code model' received from CMake server into predefined JSON file

### ISSUE THREAD

**Issue by vbspam** [microsoft/vscode-cmake-tools#638]
### Add possibility to save 'code model' received from CMake server into predefined JSON file.

The CMake [code model](https://cmake.org/cmake/help/v3.9/manual/cmake-server.7.html#type-codemodel) contains lot of useful debugging information. Together with [JSON Tree](https://marketplace.visualstudio.com/items?itemName=ChaunceyKiwi.json-tree-view) extension (with properly [configured](#notes) 'Customized View Mapping') makes the build system debugging way easier.

#### What is the goal?

Everytime the build system gets configured, store the code model to file (e.g. binaryDir + "code_model.json"

#### Suggestion

Not being VSCode extension specialist, I do not feel confident enough to propose pull request. I however modified my local CMake-Tools extension in the following way:

- Insert following code after [this](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/src/extension.ts#L413) line
```typescript
                const compdb_path =  path.join( await cmt.binaryDir, 'code_model.json');                
                pr_1.fs.writeFile(compdb_path, JSON.stringify(codeModel, null, 2));
                log.debug('Code model generated to: ', compdb_path);
```

#### Notes

The JSON Tree extension must be configured in the following way to give more then just simple JSON outline:
```json
    "jsonTreeView.customizedViewMapping": {
        "projects": "name",
        "configurations": "name",
        "targets": "name"
    },
```

**Comment by andreeis** [comment]
We are not going to implement this for CMake Server since it is deprecated, but in a way this ask will be achieved for fileApi when we fix this issue: https://github.com/microsoft/vscode-cmake-tools/issues/984.
