### ISSUE TITLE
FetchContent_Populate failing and when custom_targets are executed

### ISSUE THREAD

**Issue by meibye** [microsoft/vscode-cmake-tools#651]
### Brief Issue Summary

Several issues have been experienced with current tools version.

1. FetchContent_Populate CMake command fails when trying to populate an external project/module after having deleted the directory holding the project/module. A restart of VSC is needed in order to get it to work again.

2. I have defined a CMake custom_target (clean-all) to make needed cleanup of the build and external project/module directories (in fact I am deleting these). Sometimes the clean-all target does exactly as expected and nothing more. However, at other times the configuration step is run before the target is executed. What are the rules for forcing the configuration step? Is it due to dirty files= and how can I see that?

3. Where is the functionality of the CMake pane in VSC described?

4. How can I help provide better diagnostic logs when filing issues? Are there some settings that might help?

5. When will a new release of the extension be released?

### Platform and Versions

- **Operating System**: Ubuntu 16.04.1
- **CMake Version**: 3.13.2
- **VSCode Version**: 1.31.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: GCC 8.1.0

**Comment by bobbrow** [comment]
Are you able to share a small example project that demonstrates the behavior you describe?  It will save us some time during investigation.

We (Microsoft) recently assumed maintenance responsibilities for this extension.  We don't have a firm date yet, but we plan to release an update of the extension in the next month or two after we get a handle on the existing issues and make some minor changes required by our compliance process.
