### ISSUE TITLE
Cannot find debug adapter for type 'cppdbg'.

### ISSUE THREAD

**Issue by husaia123** [microsoft/vscode-cmake-tools#653]
when I try to debug it comes up with "Cannot find debug adapter for type 'cppdbg'." but on my configuration.json file the type is cppdbg and when i try to change it to any other type it says its not supported

**Comment by KoeMai** [comment]
Did you install the vscode-cpptools extension?

**Comment by bobbrow** [comment]
This issue is being closed because we require more information from you in order to investigate it. We can reopen and investigate once the necessary information is provided. Thank you!

**Comment by sunshinemyson** [comment]
@bobbrow I have some issue with latest release v1.37.1, it does worked in previous version, after upgrade it, it doesn't work anymore. Please let me know what kind of information is required ? Thanks

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:25.463Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-58-generic

**Comment by VictorGerin** [comment]
This problem have happened with me, and after reload problem solved

**Comment by bobbrow** [comment]
`cppdbg` is a debugger type defined by the Microsoft C/C++ extension.  If that extension is not installed (or activated), VS Code won't understand that debug adapter.  If you get into a state where you see this message, can you confirm that the C++ extension is active?

**Comment by DavidSungsuKim** [comment]
Hi, 

I am also experiencing this problem. I checked several times that I have enabled vscode.cpptools, but the same error message happens.

How can I fix this?

**Comment by bobbrow** [comment]
@DavidSungsuKim you may have installed the C/C++ extension, but that doesn't mean it's "activated".  For example, on ARM/ARM64 devices, the extension does not work yet.  You can manually invoke any of the `"C/C++:"` commands from the command palette to check.

**Comment by neologist91** [comment]
I am encountering this issue as well when working with VSCode on a Raspberry Pi 4 with Raspbian 10 installed. 

In this case I am using VSCode OSS (headmelted), and I have the C/C++ extension enabled and my launch.json and build.json appropriately configured.

**Comment by PierreFV** [comment]
Hello, 
I am having similar issues as well : I am working on two electronic cards from Nvidia (Jetson Nano) and one of those is working perfectly but the other gives me the "Couldn't find a debug adapter descriptor for debug type 'cppdbg' (extension might have failed to activate'" error. My launch.json is exactly the same on both Jetson (cf screenshot), and I'm using the same version of gcc on both (7.5.0). 
![image](https://user-images.githubusercontent.com/46575145/97165154-8d143b00-1783-11eb-909f-b1dafe0b20e0.png)
Does anyone have an idea to help me ? I'm far from being an expert so please tell me if I forgot to include some informations.
Thanks !

**Comment by andreeis** [comment]
@ghost, the extension does not support headmelted. Can you try with the regular VSCode and let us know if you still encounter the problem?

@PierreFV, we can't think of anything that would cause the problem that you are seeing. Did you try a repair/reinstall of VSCode and the extensions that you use?

**Comment by PierreFV** [comment]
@andreeis Thanks ! It worked after a few trys and re-installing the C/C++ extension on VSCode (no idea why though, since I didn't change anything).

**Comment by Bill0412** [comment]
@PierreFV Thanks! It turns out I forgot to install the C++ Extension. Now I've added the extension to the defaultExtentions: https://github.com/Bill0412/dotfiles/blob/master/vscode/settings.json
