### ISSUE TITLE
Conflict with cpptools' own auto configuration

### ISSUE THREAD

**Issue by zhihaoy** [microsoft/vscode-cmake-tools#667]
### Background

cpptools itself has a auto-configuration that prompts to pick up `compile_commands.json`

  https://github.com/Microsoft/vscode-cpptools/issues/1297

And for generators that support this (Ninja and make), only this choice is prompted, CMake Tools's cpptools integration is NOT prompted.

I'm wandering whether it's possible to let CMake Tools be the configurator.

**Comment by sean-mcmanus** [comment]
Both should be prompted. If CMake Tools isn't prompting that sounds like a bug. The C/C++ extension will also prompt to configure based on compile_commands.json if the CMake Tools doesn't register itself as a configuration provider (I think after 5 seconds or something).

The prompt just adds either compileCommands or configurationProvider fields to c_cpp_properties.json. If you have configurationProvider set, then the compileCommands shouldn't be used.

**Comment by zhihaoy** [comment]
Thanks for the explanation.  Now I went back to MSBuild configuration (which generates no `compile_commands.json`), and it seems that CMake tools no longer prompts anything... I have no `c_cpp_properties.json` file at all.  So my last resolution is to open a source file, let cpptools prompts for Configuration Help, which generates a basic `c_cpp_properties.json`.  I then manually removed the "include*" entry and added
```json
            "configurationProvider": "vector-of-bool.cmake-tools"
```
everything seems to work fine.

**Comment by sean-mcmanus** [comment]
The prompt to set the configurationProvider is actually provided by our C/C++ extensions so it doesn't appear to be a CMake Tools bug. My guess is that you clicked the "Don't Allow" button? That is the only thing I see that would cause it to stop appearing. The compile_commands.json prompt should be independent of the other prompt.

**Comment by zhihaoy** [comment]
> My guess is that you clicked the "Don't Allow" button? That is the only thing I see that would cause it to stop appearing. The compile_commands.json prompt should be independent of the other prompt.

I clicked "Don't Allow" on cpptools' "compile_commands.json" prompt once, if that causes CMake Tools to stop prompting auto-configuration, that would harsh.  I mean, if a user see two prompts, you would expect him/her to "Don't Allow" at least one of them...?

**Comment by bobbrow** [comment]
cpptools hopes to do away with the prompts in a future release.  We are working on UI for the configuration experience that should make this process more straightforward.

**Comment by sean-mcmanus** [comment]
@zhihaoy Yeah, clicking Don't Allow for compile_commands.json is not expected to affect the CMake Tools prompt. I don't have a repro and I didn't see any way this bug could occur in the code (the code that does the prompting is open source if you want to review it). I found a different bug, but it was for the compile_commands.json prompt not appearing: https://github.com/Microsoft/vscode-cpptools/pull/3399 .

**Comment by andreeis** [comment]
@zhihaoy, is this still happening for you? Install latest CMake Tools (1.3.1 as of today). We are closing this issue until we hear that this is still a problem.
