### ISSUE TITLE
CMake generating of VS projects inside VS Code on Windows not working

### ISSUE THREAD

**Issue by renebarto** [microsoft/vscode-cmake-tools#671]
### Brief Issue Summary

When I generate for Visual Studio 14.0 x86_amd64 inside VS Code on Windows, it seems incorrect arguments are passed to the compiler. If I run CMake on the command line, everything works as expected. It may have something to do with the path environment variable, which may have spaces.

Platform and Versions
Operating System: Windows 10
CMake Version: 3.10
VSCode Version: 1.32.3
CMake Tools Extension Version: 1.1.3
Compiler/Toolchain: Visutal Studio 2015 / 14.0
### Expected:

Select kit: Visual Studio 14.0 - x86_amd64
Select build variant: Debug
The VS solution and projects are correctly generated, without errors.

### Apparent Behavior:

Select kit: Visual Studio 14.0 - x86_amd64
Select build variant: Debug

The Microsoft compiler complains about unrecognized source files types while trying to build the compiler test program:

1. Push button
2. Nothing happens

### CMake Tools Log

[cmake] The C compiler identification is MSVC 19.0.24215.1
[cmake] The CXX compiler identification is MSVC 19.0.24215.1
[cmake] Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
[cmake] Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- broken
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
[cmake]   The C compiler
[cmake] 
[cmake]     "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe"
[cmake] 
[cmake]   is not able to compile a simple test program.
[cmake] 
[cmake]   It fails with the following output:
[cmake] 
[cmake]     Change Dir: d:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeTmp
[cmake]     
[cmake]     Run Build Command:"D:/Projects/Trial/sdk/sysroots/x86_64-wrlinuxsdk-mingw32/usr/bin/make.exe" "cmTC_0c051/fast"
[cmake]     D:/Projects/Trial/sdk/sysroots/x86_64-wrlinuxsdk-mingw32/usr/bin/make.exe -f CMakeFiles/cmTC_0c051.dir/build.make CMakeFiles/cmTC_0c051.dir/build
[cmake]     make.exe[1]: Entering directory 'd:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeTmp'
[cmake]     Building C object CMakeFiles/cmTC_0c051.dir/testCCompiler.c.obj
[cmake]     cd D:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeTmp && "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe"  /nologo   /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1   /FoCMakeFiles/cmTC_0c051.dir/testCCompiler.c.obj /FdCMakeFiles/cmTC_0c051.dir/ /FS -c D:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeTmp/testCCompiler.c
[cmake]     Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
[cmake]     Copyright (C) Microsoft Corporation.  All rights reserved.
[cmake]     
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'Files/Git/DFXDVER=0x601', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'Files/Git/DFXDVER=0x601' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/nologo', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/nologo' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/DWIN32', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/DWIN32' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/D_WINDOWS', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/D_WINDOWS' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/W3', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/W3' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/MDd', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/MDd' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/Zi', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/Zi' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/Ob0', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/Ob0' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/Od', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/Od' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/RTC1', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/RTC1' ignored
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/FoCMakeFiles/cmTC_0c051.dir/testCCompiler.c.obj' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/FdCMakeFiles/cmTC_0c051.dir/', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/FdCMakeFiles/cmTC_0c051.dir/' ignored
[cmake]     cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/FS', object file assumed
[cmake]     cl : Command line warning D9027 : source file 'C:/Program Files/Git/FS' ignored
[cmake]     testCCompiler.c
[cmake]     Linking C executable cmTC_0c051.exe
[cmake]     cd D:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeTmp && "C:/Program Files/CMake/bin/cmake.exe" -E vs_link_exe --intdir=CMakeFiles/cmTC_0c051.dir --manifests  -- "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/link.exe" /nologo @CMakeFiles/cmTC_0c051.dir/objects1.rsp  /out:cmTC_0c051.exe /implib:cmTC_0c051.lib /pdb:D:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeTmp/cmTC_0c051.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib 
[cmake]     LINK: command "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/link.exe C:/Program Files/Git/nologo @CMakeFiles/cmTC_0c051.dir/objects1.rsp /out:cmTC_0c051.exe /implib:cmTC_0c051.lib /pdb:D:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeTmp/cmTC_0c051.pdb /version:0.0 /machine:x64 C:/Program Files/Git/debug C:/Program Files/Git/INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:cmTC_0c051.exe.manifest" failed (exit code 1181) with the following output:
[cmake]     Microsoft (R) Incremental Linker Version 14.00.24215.1
[cmake]     Copyright (C) Microsoft Corporation.  All rights reserved.
[cmake]     
[cmake]     CMakeFiles/cmTC_0c051.dir/testCCompiler.c.obj 
[cmake]     LINK : fatal error LNK1181: cannot open input file 'C:/Program Files/Git/nologo.obj'
[cmake]     make.exe[1]: *** [CMakeFiles/cmTC_0c051.dir/build.make:98: cmTC_0c051.exe] Error 127
[cmake]     make.exe[1]: Leaving directory 'd:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeTmp'
[cmake]     make.exe: *** [Makefile:126: cmTC_0c051/fast] Error 2
[cmake]     
[cmake] 
[cmake]   
[cmake] 
[cmake]   CMake will not be able to correctly generate this project.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
[cmake] See also "d:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeOutput.log".
[cmake] See also "d:/Projects/Trial/FDCSIB_SW_WRL9/cmake-wrl-debug/CMakeFiles/CMakeError.log".
[cms-driver] Error during CMake configure: [cmake-server] Configuration failed.
[driver] Switching to kit: VisualStudio.14.0 - x86_amd64

```
[2019-04-08 17:13:26.054] [exthost] [info] ExtensionService#_doActivateExtension vector-of-bool.cmake-tools {"startup":false,"activationEvent":"workspaceContains:CMakeLists.txt"}
[2019-04-08 17:13:26.054] [exthost] [info] ExtensionService#loadCommonJSModule c:\Users\320012620\.vscode\extensions\vector-of-bool.cmake-tools-1.1.3\out\src\extension
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: 
- **CMake Version**: 
- **VSCode Version**: 
- **CMake Tools Extension Version**: 
- **Compiler/Toolchain**: 

### Other Notes/Information

As said above, I believe this has something to do with spaces in paths, especially the path to Git. I have no idea where this path is specified, it may be set internally in VS Code.

**Comment by andreeis** [comment]
Please install the latest CMake Tools. There have been many bug fixes and improvements in this area. And very important, don't forget to rescan for kits. I didn't reproduce the space problem on a QuickStart CMake project, with VS14 kit and CMake Tools 1.3.1.

**Comment by roddypratt** [comment]
I had a similar problem with options like "/Zi" being interpreted as filenames causing lots of errors like the above.

```
[cmake] cl : Command line warning D9024 : unrecognized source file type 'C:/Program Files/Git/Zi', object file assumed
[cmake] cl : Command line warning D9027 : source file 'C:/Program Files/Git/Zi' ignored
```

In my case the problem was fixed by changing  the default shell for vscode from "git bash"  to cmd.exe
