### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vengala-reddy** [microsoft/vscode-cmake-tools#672]
- Issue Type: `Performance`
- Extension Name: `cmake-tools`
- Extension Version: `1.1.3`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Vengala Reddy\vector-of-bool.cmake-tools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bobbrow** [comment]
If this is still a problem, can you please attach the file listed in the issue report?
