### ISSUE TITLE
Kits stored in wrong location when user-data-dir set via command-line-arguments

### ISSUE THREAD

**Issue by stephenwhittle** [microsoft/vscode-cmake-tools#673]
### Brief Issue Summary
When storing some configuration data such as 'cmake-tools-kits.json', the extension does not correctly respect `user-data-dir`, `extensions-data-dir` when those are passed into VSCode on the command line. This makes it impossible for the extension to be compliant with the expected behaviour for a portable VSCode installation. 

### Expected:
1. Run VSCode from the command-line, specifying arguments for all the relevant directories (in my case)
```
set VSCODE_CLI=1 & ELECTRON_RUN_AS_NODE=1 <path>/vscode/code.exe <path>/vscode/resources/app/out/cli.js --user-data-dir <path>/vscode --extensions-data-dir <path>/vscode/data --extensions-dir <path>/vscode/data --extensionHomePath <path>/vscode/extensions
```
2. Scan for kits
3. cmake-tools-kits.json should be stored in the indicated directory rather than Appdata/Local

### Apparent Behavior:
1. Run VSCode from the command-line, specifying arguments for all the relevant directories (in my case)
```
set VSCODE_CLI=1 & ELECTRON_RUN_AS_NODE=1 <path>/vscode/code.exe <path>/vscode/resources/app/out/cli.js --user-data-dir <path>/vscode --extensions-data-dir <path>/vscode/data --extensions-dir <path>/vscode/data --extensionHomePath <path>/vscode/extensions
```
2. Scan for kits
3. cmake-tools-kits.json is placed into Appdata/Local

### CMake Tools Log

```
[kit] Found Kit: Clang 7.0.1 for MSVC with Visual Studio Community 2017 (amd64)
[kit] Found Kit: Clang 7.0.1 for MSVC with VisualStudio.14.0 (amd64)
[extension] Saving kits to C:\Users\Stephen\AppData\Local\CMakeTools\cmake-tools-kits.json
[extension] Saving new kits to C:\Users\Stephen\AppData\Local\CMakeTools\cmake-tools-kits.json
```

### Platform and Versions
- **Operating System**: Windows 10 x64
- **VSCode Version**: 1.33.0
- **CMake Tools Extension Version**: 1.1.3

**Comment by Randshot** [comment]
This probably an oversight on our part. I at least didn't know that this was possible.

**Comment by alan-wr** [comment]
Hi,

https://code.visualstudio.com/docs/editor/command-line
--user-data-dir <dir> | Specifies the directory that user data is kept in, useful when running as root.

The options is specified by root use.

This defect should be closed as invalid.
