### ISSUE TITLE
Multiple Visual Studio with same instance id cause kits cannot be generated when the first instance do not contain the C++ compiler

### ISSUE THREAD

**Issue by tsing80** [microsoft/vscode-cmake-tools#675]
### Brief Issue Summary

When the computer have multiple visual studio with same instance id installed. (e.g. Visual Studio SSDT 2017 and Visual Studio Community Edition 2017), and the first instance (SSDT 2017) that is without C++ compiler is listed in the vswhere.exe output.It cause the tools-kit for Visual Studio 2017 cannot be generated in cmake-tools-kits.json due to SSDT 2017 do not have a c++ compiler, due to vsInstallations() in kits.ts filter out duplicate entries  by using the instance id.

Steps to reproduce:

1. Install  Visual Studio Community Edition 2017
2. Install Visual Studio SSDT 2017
3. Run the "CMake: Scan for kits"   command  in Visual Studio Code

**Comment by KoeMai** [comment]
Could you add the vswhere output. This would help to remove not required vs instances.

**Comment by tsing80** [comment]
sorry, I don't have that output now. I have removed SSDT 2017 to work around the problem.

**Comment by andreeis** [comment]
@tsing80, please upgrade to latest CMake Tools and let us know if this still happens. We did numerous bug fixes and improvements in the kits area.

**Comment by bobbrow** [comment]
(and don't forget to rescan for Kits) 😃
