### ISSUE TITLE
Wrong Windows Kit include paths lead to missing #definitions.

### ISSUE THREAD

**Issue by johannesstricker** [microsoft/vscode-cmake-tools#679]
I am building a project that uses definitions which are available from Windows 10 only, but when I try to build the project, the definitions are not found.
It seems that cmake tools is setting the Windows Kits include paths wrong. Upon configuration it outputs `[cmake] Selecting Windows SDK version  to target Windows 10.0.18890.` but I checked the additional include paths and they point to
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
C:\Program Files (x86)\Windows Kits\8.1\Include\um
C:\Program Files (x86)\Windows Kits\8.1\Include\shared
C:\Program Files (x86)\Windows Kits\8.1\Include\winrt
```
I guess they should all point to the `Windows Kits\10\..` directories, right? If it matters, I am using the latest Windows Insider Preview `Build 18890.rs_prerelease.190426-1618` and CMake version `3.14.0`.

The definitions which are missing are these
```
#define _DPI_AWARENESS_CONTEXTS_
DECLARE_HANDLE(DPI_AWARENESS_CONTEXT);
typedef enum DPI_AWARENESS {
    DPI_AWARENESS_INVALID           = -1,
    DPI_AWARENESS_UNAWARE           = 0,
    DPI_AWARENESS_SYSTEM_AWARE      = 1,
    DPI_AWARENESS_PER_MONITOR_AWARE = 2
} DPI_AWARENESS;
#define DPI_AWARENESS_CONTEXT_UNAWARE           ((DPI_AWARENESS_CONTEXT)-1)
#define DPI_AWARENESS_CONTEXT_SYSTEM_AWARE      ((DPI_AWARENESS_CONTEXT)-2)
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE ((DPI_AWARENESS_CONTEXT)-3)
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 ((DPI_AWARENESS_CONTEXT)-4)
```

**Comment by andreeis** [comment]
If CMake is not automatically selecting the latest sdk, try this setting:
"cmake.configureSettings": {
  "CMAKE_SYSTEM_VERSION": "10"
}

Reactivate the issue if this didn't help.
