### ISSUE TITLE
cmake.buildDirectory doesn't handle `..` in its path

### ISSUE THREAD

**Issue by agirault** [microsoft/vscode-cmake-tools#681]
### Brief Issue Summary

`cmake.buildDirectory` doesn't interpret `..`, making it impossible to build in a directory out of the source directory.

### Expected:

1. Set `cmake.buildDirectory` to `"${workspaceRoot}/../build"`
2. Expects CMake to configure the project in `"${workspaceRoot}/../build"`

### Apparent Behavior:

1. Set `cmake.buildDirectory` to `"${workspaceRoot}/../build"`
2. CMake configures the project in `"${workspaceRoot}/build"`

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.14.3
- **VSCode Version**: 1.33.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Clang 10.0.0

**Comment by bobbrow** [comment]
This appears to work for me in version 1.3.1.  Please let us know if you continue to have problems with this after upgrading to the latest version of the extension.
