### ISSUE TITLE
HELP WANTED 3: Revenge of the Sith - Seeking a new primary maintainer

### ISSUE THREAD

**Issue by vector-of-bool** [microsoft/vscode-cmake-tools#691]
Yes, you read that right: I'm looking for a new maintainer. I won't write about the reasons here: that information will appear in a blog post.

I'm looking to do a full proper hand-off for the project, including extension publication rights and repository ownership.

**Note:** With 275,000 installs, I'm not going to immediately drop it in the lap of the first person to ask. I will need to establish a basis of trust.

Even after doing a hand-off, I may not be completely _hands_-off. I may or may not continue to participate and submit patches.

If you (or your org) are interested, please **comment** below, **AND** send me an **email** to `vectorofbool(at)gmail(dot)com`.

---

@KoeMai @Randshot,

Sorry for this sudden announcement, I didn't even realize that you've still been active in the repository in my absence. Background details are on the way.

**Comment by lygstate** [comment]
I'd like do contribution:)

**Comment by KaungZawHtet** [comment]
How about official c++ extension team? They promised the community for cmake capability on vs code but still no news from them. I think they can maintain this awesome extension and they need this to fullfill thier promise. We don't want this cool extension inactive.

**Comment by bobbrow** [comment]
Hi @KaungZawHtet, I am from the Microsoft C/C++ extension team.  There are some details we need to work out, but we are talking with @vector-of-bool about this.

**Comment by KaungZawHtet** [comment]
Nice! We are awaiting good news.

**Comment by dgellow** [comment]
@vector-of-bool All the best, thank you for your work on this extension 🙏

**Comment by DavidA2014** [comment]
@bobbrow Any progress with Microsoft C/C++ extension team maintaining this project? I'm really missing support for multi-root workspaces.

**Comment by bobbrow** [comment]
The repo has now been transferred to Microsoft.  In the coming days/weeks we will be spending time reviewing the existing issues and PR's and coming up with schedules for the work we plan to do with this extension.  As always, community contributions are accepted and encouraged!

**Comment by s-martin** [comment]
Thanks to @bobbrow an the Microsoft team for picking up this important extension.

And a very big thanks to @vector-of-bool for creating this wonderful extension and putting all the work in! You really made one of our first CMake projects at my last job a lot easier!
