### ISSUE TITLE
Target debugging is no longer supported with the legacy driver

### ISSUE THREAD

**Issue by GouZi2019** [microsoft/vscode-cmake-tools#693]
I get a problem when press ”Launch the debugger for the selected target"

CMake Tools Log:
Target debugging is no longer supported with the legacy driver

Platform and Versions
Operating System: macOS 10.14.4
CMake Version: 3.11.0
VSCode Version: 1.34.0 
CMake Tools Extension Version: 1.1.3

**Comment by KoeMai** [comment]
Is it really cmake 3.11? Is the setting `useCMakeServer` set to false in workspace or user settings?
Was another warning visible before?

**Comment by bobbrow** [comment]
This message should only appear for older versions of CMake unless you've disabled the `useCMakeServer` setting as @KoeMai indicated.  If you change this to `true` and continue to see the problem, please reopen the issue and we'll investigate further.

Thank you!
