### ISSUE TITLE
MSVC toolkits not all discovered

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [microsoft/vscode-cmake-tools#694]
### Brief Issue Summary

I have Visual Studio 2019 installed with both v142 and v141 (2017) components installed.

CMake: Scan for kits, only discovers the 2019 (v142) variants.

### Expected:

1. Scan for kits
2. Discover 2019 and 2017 kits

### CMake Tools Log
```
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\MIRKO~1.VON\AppData\Local\Temp\vs-cmt-0.2514990336779097.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\MIRKO~1.VON\AppData\Local\Temp\vs-cmt-0.26170400545166683.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\MIRKO~1.VON\AppData\Local\Temp\vs-cmt-0.9801477462501873.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\MIRKO~1.VON\AppData\Local\Temp\vs-cmt-0.6965579478793926.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\MIRKO~1.VON\AppData\Local\Temp\vs-cmt-0.7803225876546676.bat.env'
[kit] Error: ENOENT: no such file or directory, open 'C:\Users\MIRKO~1.VON\AppData\Local\Temp\vs-cmt-0.800201198256695.bat.env'
[kit] Found Kit: Visual Studio Community 2019 - x86
[kit] Found Kit: Visual Studio Community 2019 - amd64
[kit] Found Kit: Visual Studio Community 2019 - x86_amd64
[kit] Found Kit: Visual Studio Community 2019 - x86_arm
[kit] Found Kit: Visual Studio Community 2019 - amd64_arm
[kit] Found Kit: Visual Studio Community 2019 - amd64_x86
[driver] Switching to kit: Visual Studio Community 2019 - x86
```
### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.14.3
- **VSCode Version**: 1.35.0-insider
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017/2019

### Other Notes/Information
The [kit] Error, occur during the "scanning for 2017..." pop-up.

**Comment by KoeMai** [comment]
Could you add the vswhere output? I have no environment for reconstruction.

**Comment by Mirko-von-Leipzig** [comment]
I unfortunately installed VS 2017 as well (which fixed the problem).
I now uninstalled 2017 again, in an attempt to get back to the same state; but the ENOENT errors are no longer displayed in the VSCode console.
It does not pick up the v141 toolkits though (which did work with 2017 installed).

vswhere.exe output:
----------------------------------------------------------------------------------------------------
Visual Studio Locator version 2.2.11+gf1a9c6c78d [query version 2.1.1046.44959]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 0fea5f8b
installDate: 2019/03/20 10:08:50 AM
installationName: VisualStudio/16.1.1+28922.388
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
installationVersion: 16.1.28922.388
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Community 2019
description: Free, fully-featured IDE for students, open-source and individual developers
channelId: VisualStudio.16.Release
channelUri: https://aka.ms/vs/16/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660893#16.1.1
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660909
updateDate: 2019-05-30T09:47:22.6310745Z
catalog_buildBranch: d16.1
catalog_buildVersion: 16.1.28922.388
catalog_id: VisualStudio/16.1.1+28922.388
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 16.1.1
catalog_productLine: Dev16
catalog_productLineVersion: 2019
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 1
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productSemanticVersion: 16.1.1+28922.388
catalog_requiredEngineVersion: 2.1.3095.63072
properties_campaignId:
properties_channelManifestId: VisualStudio.16.Release/16.1.1+28922.388
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe

**Comment by Colengms** [comment]
VS can install multiple VC toolset minor versions.

https://devblogs.microsoft.com/cppblog/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2019/

Cmake-tools could surface each of them, rather than 1 per VS product install directory.

This could be useful if, for example, a new VC toolset introduces a problem, requiring fallback to a prior toolset for some projects.  :/

**Comment by bobbrow** [comment]
We need to rework the Kits a bit.  In the meantime, you should be able to add `"-T v141"` to `cmake.configureArgs` to select your toolset.

**Comment by Colengms** [comment]
In my case it would be `"-Tversion=14.25"`.

Specifying this in `settings.json` would apply to all kits.  But, this is only a valid toolset if using one of my VS 2019 kits.  Ninja doesn't support specifying a toolset.  It will fail if any toolset is provided.

If I add `"cmake.configureArgs": ["-Tversion=14.25"]`, despite not specifying a value for `cmake.generator`, CMake Tools uses Ninja instead of the preferredGenerator (`"Visual Studio 16 2019"`) specified for my currently selected kit (VS). 

There does not appear to be a way to specify the toolset in a kit.  That would seem a good solution (if the preferredGenerator setting there was honored).

I can also add `"cmake.generator": "Visual Studio 16 2019"` to settings.json.  (Oddly, it still uses Ninja unless I delete my CMake build output dir and relaunch VS Code.)  However, this overrides the setting for all kits.  So, I can no longer switch to my Clang 10 kit (for example).  Regardless of what kit I select, it uses VS and builds with cl.exe from the toolset I've specified.

```
[cmake] -- The C compiler identification is MSVC 19.25.28610.4
[cmake] -- The CXX compiler identification is MSVC 19.25.28610.4
```

If CMake Tools were to surface each toolset version as separate kits, and/or allow the toolset version to be specified in the kit, that would unblock my other kits.

**Comment by bobbrow** [comment]
You're right, might suggestion won't work well.  I've been fiddling with this today.  #1084 complicates things as you pointed out (preferredGenerator not honored), but you can work around it by setting `"cmake.preferredGenerators": []`.

Then you can add new Kits to your "user-local" kits and they will be picked up as expected.
```
  {
    "name": "Visual Studio Enterprise 2019 Release - amd64 - v141",
    "visualStudio": "23208765",
    "visualStudioArchitecture": "amd64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "v141"
    }
  },
```

**Comment by ompadu** [comment]
Hi, is there update on this issue?

**Comment by andreeis** [comment]
We were not able to address this problem for our latest 1.5 release and it is triaged for the upcoming 1.6.
Let us know if the latest suggestion from bobbrow doesn't work for you (the one about adding a new kit in the user local kits json file).

**Comment by ompadu** [comment]
It worked, I am leaving my config here for reference. 

```
{
    "name": "Visual Studio Build Tools 2019 Release - amd64 (v141)",
    "visualStudio": "434fa394",
    "visualStudioArchitecture": "x64",
    "preferredGenerator": {
      "name": "Visual Studio 16 2019",
      "platform": "x64",
      "toolset": "v141"
    }
 },
```

**Comment by lygstate** [comment]
No, it's different, as toolset only support for `Visual Studio` generator, but I am talking about "Ninja" or "Ninja Multi-Config" Genearator

**Comment by SergMariaDB** [comment]
MSVC ARM build tool kits are not discovered also

**Comment by gcampbell-msft** [comment]
@SergMariaDB @lygstate @Mirko-von-Leipzig Have you considered migrating to CMake Presets? This could let you have more configuration specific control over what toolsets are being used. 

Thanks!

**Comment by Mirko-von-Leipzig** [comment]
I no longer work on the project that this affected so its now a non-issue for me now.
