### ISSUE TITLE
Add a command that returns the resolved value of cmake.buildDirectory

### ISSUE THREAD

**Issue by zrno** [microsoft/vscode-cmake-tools#695]
### Brief Issue Summary

Using ${config:cmake.buildDirectory} in launch.json with visual cpp debugger doesn't work. After a successful cmake configure the ${config:cmake.buildDirectory} is not correctly resolved. In my example in settings.json the cmake.buildDirectory looks like this:
`"cmake.buildDirectory": "${workspaceFolder}/../CMakeBuild/vscode/NSW-51770/${buildKit}/${buildType}",`

The ${buildKit} and ${buildType} are not resolved but just copied into the resulting string.

### Expected:

cmake.buildDirectory is correctly resolved

### Platform and Versions
- **Operating System**: Windows
- **CMake Version**: 3.14
- **VSCode Version**: 1.34
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2019

**Comment by KoeMai** [comment]
The config build directory is the expansion template for cmake extension. It is used to generate the build directory. If you want to get the directory for debugging then try (the lauchTargetDirectory)[https://vector-of-bool.github.io/docs/vscode-cmake-tools/debugging.html#debugging-launch.json].

**Comment by zrno** [comment]
Thanks for the answer. I can not use launchTargetDirectory as I have multiple targets in my project. The launch.json has several targets listed. Example launch.json:
`    
"configurations": [
    {
        "name": "Target1 Launch",
        "program": "${config:cmake.buildDirectory}/Target1/Target1.exe",
    },
    {
        "name": "Target2 Launch",
        "program": "${config:cmake.buildDirectory}/Target2/Target2.exe",
    },
`
Using ${config:cmake.buildDirectory} isn't working. Any solution for that?

**Comment by KoeMai** [comment]
With the present extension it is not possible. It requires a new command.

**Comment by zrno** [comment]
Thanks for the fast response. Anything I need to do to put open a feature request? Or is this open issue already enough?

**Comment by bobbrow** [comment]
Do you need to list out all of your targets in the `launch.json`?

The following works for me today:
```
        {
            "name": "Launch CMake active target",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${command:cmake.launchTargetPath}"
        }
```

It looks like `command:cmake.launchTargetDirectory` is not available in 1.1.3, but when we release the next update it will be available to set as the value for "cwd" should you need it.

If that doesn't work for you, we can leave this issue open as a feature request for a new command to return the resolved build directory.

**Comment by giantmustache** [comment]
The launchTargetDirectory is not always the same as the buildDirectory.

For example, if I have multiple targets in my project, I will get a subdirectory:

- project1
  - CMakeLists.txt contains add_executable()
- project2
  - CMakeLists.txt contains add_executable()

The build directory would be

- bin --> would be buildDirectory
  - project1 --> would be launchTargetDirectory
    - project1.exe
  - project2 --> would be launchTargetDirectory
    - project2.exe

**Comment by bobbrow** [comment]
@giantmustache, you are correct.  There are cases where the build directory might be desirable, but for the simple case `launchTargetDirectory` would put you in the same directory as the executable (`launchTargetPath`).

**Comment by giantmustache** [comment]
I was able to work around this using vs power tools. For those looking for an answer:

I created a new command in my workspace settings like so:

	"ego.power-tools": {
		"commands": {
			"expandedBuildDirectory": {
				"script": "expandedBuildDirectory.js"
			}
		}
	}

Then I created the command as follows:

    // expandedBuildDirectory.js
	exports.execute = async (args) => {
		const vscode = args.require('vscode');

		// tried to use path first, but that contains a / at the front of the path
		const buildFolder = vscode.workspace.getConfiguration('cmake').get('buildDirectory').replace('${workspaceRoot}', vscode.workspace.workspaceFolders[0].uri.fsPath);
		return buildFolder.replace(/\\/g, '/');
	};

**Comment by bobbrow** [comment]
As I have been reviewing the existing issues, I found that there is already one tracking this request.  #564
