### ISSUE TITLE
cmake tool start C++ debug target fail

### ISSUE THREAD

**Issue by 1106944911** [microsoft/vscode-cmake-tools#698]
Hi all, cmake debug C++ project error,  can't debug,  "[extension] [8621] cmake.debugTarget finished (returned undefined)," anyone help me ?
question:
  1  why have two target debug program, main debug and extension debug
 2  extension debug program start fail

vscode output:

[extension] [5328] cmake.launchTargetPath started
[rollbar] Invoking function [] with Rollbar wrapping [Processing "data" event from proc stdout]
[rollbar] Invoking function [] with Rollbar wrapping [Resolving process on "close" event]
[rollbar] Invoking function [] with Rollbar wrapping [Processing "data" event from proc stdout]
[rollbar] Invoking function [] with Rollbar wrapping [Resolving process on "close" event]
[extension] [5328] cmake.launchTargetPath finished (returned "/home/huangzheng/project/TrafficGo2/build/bin/trafficgo")
[extension] [8621] cmake.debugTarget started
[rollbar] Invoking function [] with Rollbar wrapping [Processing "data" event from proc stdout]
[rollbar] Invoking function [] with Rollbar wrapping [Resolving process on "close" event]
[rollbar] Invoking function [] with Rollbar wrapping [Processing "data" event from proc stdout]
[rollbar] Invoking function [] with Rollbar wrapping [Resolving process on "close" event]
[rollbar] Invoking function [] with Rollbar wrapping [Processing "data" event from proc stdout]
[rollbar] Invoking function [] with Rollbar wrapping [Resolving process on "close" event]
[cache] Reading CMake cache file /home/huangzheng/project/TrafficGo2/build/CMakeCache.txt
[cache] File exists
[cache] File contents read successfully
[cache] Parsing CMake cache string
[cache] Read line in cache with name=CMAKE_AR, typename=FILEPATH, valuestr=/usr/bin/ar
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_BUILD_TYPE, typename=STRING, valuestr=Debug
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_COLOR_MAKEFILE, typename=BOOL, valuestr=ON
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_COMPILER, typename=FILEPATH, valuestr=/usr/bin/g++
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_COMPILER_AR, typename=FILEPATH, valuestr=/usr/bin/gcc-ar
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_COMPILER_RANLIB, typename=FILEPATH, valuestr=/usr/bin/gcc-ranlib
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_FLAGS, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_FLAGS_DEBUG, typename=STRING, valuestr=-g
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_FLAGS_MINSIZEREL, typename=STRING, valuestr=-Os -DNDEBUG
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_FLAGS_RELEASE, typename=STRING, valuestr=-O3 -DNDEBUG
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_FLAGS_RELWITHDEBINFO, typename=STRING, valuestr=-O2 -g -DNDEBUG
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_C_COMPILER, typename=FILEPATH, valuestr=/usr/bin/gcc
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_C_COMPILER_AR, typename=FILEPATH, valuestr=/usr/bin/gcc-ar
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_C_COMPILER_RANLIB, typename=FILEPATH, valuestr=/usr/bin/gcc-ranlib
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_C_FLAGS, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_C_FLAGS_DEBUG, typename=STRING, valuestr=-g
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_C_FLAGS_MINSIZEREL, typename=STRING, valuestr=-Os -DNDEBUG
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_C_FLAGS_RELEASE, typename=STRING, valuestr=-O3 -DNDEBUG
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_C_FLAGS_RELWITHDEBINFO, typename=STRING, valuestr=-O2 -g -DNDEBUG
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS_DEBUG, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS_MINSIZEREL, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS_RELEASE, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_EXPORT_COMPILE_COMMANDS, typename=BOOL, valuestr=TRUE
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_INSTALL_PREFIX, typename=PATH, valuestr=/usr/local
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_LINKER, typename=FILEPATH, valuestr=/usr/bin/ld
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_MAKE_PROGRAM, typename=FILEPATH, valuestr=/usr/bin/gmake
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS_DEBUG, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS_RELEASE, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_NM, typename=FILEPATH, valuestr=/usr/bin/nm
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_OBJCOPY, typename=FILEPATH, valuestr=/usr/bin/objcopy
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_OBJDUMP, typename=FILEPATH, valuestr=/usr/bin/objdump
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_PROJECT_NAME, typename=STATIC, valuestr=trafficgo
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_RANLIB, typename=FILEPATH, valuestr=/usr/bin/ranlib
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS_DEBUG, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS_RELEASE, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_SKIP_INSTALL_RPATH, typename=BOOL, valuestr=NO
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_SKIP_RPATH, typename=BOOL, valuestr=NO
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS_DEBUG, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS_RELEASE, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO, typename=STRING, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_STRIP, typename=FILEPATH, valuestr=/usr/bin/strip
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_VERBOSE_MAKEFILE, typename=BOOL, valuestr=FALSE
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=trafficgo_BINARY_DIR, typename=STATIC, valuestr=/home/huangzheng/project/TrafficGo2/build
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=trafficgo_SOURCE_DIR, typename=STATIC, valuestr=/home/huangzheng/project/TrafficGo2
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_AR-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_CACHEFILE_DIR, typename=INTERNAL, valuestr=/home/huangzheng/project/TrafficGo2/build
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CACHE_MAJOR_VERSION, typename=INTERNAL, valuestr=3
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CACHE_MINOR_VERSION, typename=INTERNAL, valuestr=12
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CACHE_PATCH_VERSION, typename=INTERNAL, valuestr=4
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_COLOR_MAKEFILE-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_COMMAND, typename=INTERNAL, valuestr=/usr/local/bin/cmake
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CPACK_COMMAND, typename=INTERNAL, valuestr=/usr/local/bin/cpack
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CTEST_COMMAND, typename=INTERNAL, valuestr=/usr/local/bin/ctest
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_CXX_COMPILER-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_CXX_COMPILER_AR-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_CXX_COMPILER_RANLIB-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_CXX_FLAGS-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_CXX_FLAGS_DEBUG-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_CXX_FLAGS_RELEASE-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_C_COMPILER-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_C_COMPILER_AR-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_C_COMPILER_RANLIB-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_C_FLAGS-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_C_FLAGS_DEBUG-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_C_FLAGS_MINSIZEREL-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_C_FLAGS_RELEASE-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_C_FLAGS_RELWITHDEBINFO-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_EXECUTABLE_FORMAT, typename=INTERNAL, valuestr=ELF
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS_DEBUG-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS_MINSIZEREL-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS_RELEASE-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_EXPORT_COMPILE_COMMANDS-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_EXTRA_GENERATOR, typename=INTERNAL, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_GENERATOR, typename=INTERNAL, valuestr=Unix Makefiles
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_GENERATOR_INSTANCE, typename=INTERNAL, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_GENERATOR_PLATFORM, typename=INTERNAL, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_GENERATOR_TOOLSET, typename=INTERNAL, valuestr=
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_HOME_DIRECTORY, typename=INTERNAL, valuestr=/home/huangzheng/project/TrafficGo2
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_INSTALL_SO_NO_EXE, typename=INTERNAL, valuestr=0
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_LINKER-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_MAKE_PROGRAM-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS_DEBUG-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS_RELEASE-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_NM-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_NUMBER_OF_MAKEFILES, typename=INTERNAL, valuestr=2
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_OBJCOPY-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_OBJDUMP-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_PLATFORM_INFO_INITIALIZED, typename=INTERNAL, valuestr=1
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_RANLIB-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_ROOT, typename=INTERNAL, valuestr=/usr/local/share/cmake-3.12
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS_DEBUG-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS_RELEASE-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_SKIP_INSTALL_RPATH-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_SKIP_RPATH-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS_DEBUG-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS_RELEASE-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_STRIP-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Read line in cache with name=CMAKE_UNAME, typename=INTERNAL, valuestr=/usr/bin/uname
[cache] Constructing a new cache entry from the given line
[cache] Read line in cache with name=CMAKE_VERBOSE_MAKEFILE-ADVANCED, typename=INTERNAL, valuestr=1
[cache] Skipping *-ADVANCED variable
[cache] Parsed 73 cache entries
[cache] Parsed 73 entries from /home/huangzheng/project/TrafficGo2/build/CMakeCache.txt
[cache] Get cache key CMAKE_LINKER=/usr/bin/ld
[cache] Get cache key CMAKE_CXX_COMPILER=/usr/bin/g++
[proc] Executing command: /usr/bin/gdb --version
[rollbar] Invoking function [] with Rollbar wrapping [Processing "data" event from proc stdout]
[rollbar] Invoking function [] with Rollbar wrapping [Resolving process on "close" event]
[main] Debug configuration from cache:  {"type":"cppdbg","name":"Debug trafficgo","request":"launch","cwd":"${workspaceRoot}","args":[],"MIMode":"gdb","miDebuggerPath":"/usr/bin/gdb","setupCommands":[{"description":"Enable pretty-printing for gdb","text":"-enable-pretty-printing","ignoreFailures":true}],"program":"/home/huangzheng/project/TrafficGo2/build/bin/trafficgo"}
[main] Starting debugger with following configuration. {"workspace":"file:///home/huangzheng/project/TrafficGo2","config":{"type":"cppdbg","name":"Debug trafficgo","request":"launch","cwd":"${workspaceRoot}","args":[],"MIMode":"gdb","miDebuggerPath":"/usr/bin/gdb","setupCommands":[{"description":"Enable pretty-printing for gdb","text":"-enable-pretty-printing","ignoreFailures":true}],"program":"/home/huangzheng/project/TrafficGo2/build/bin/trafficgo"}}
[extension] [8621] cmake.debugTarget finished (returned undefined)

launch.json:
   {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [                                 
        {
            "name": "trafficgo123",
            "type": "cppdbg",
            "request": "launch",
            "program": "${command:cmake.launchTargetPath}",
            // "program": "/home/huangzheng/project/TrafficGo2/build/bin/trafficgo",
            // "preLaunchTask": "cmake",
            // "customLaunchSetupCommands": [
            //     { "text": "target-run", "description": "run target", "ignoreFailures": false }
            //  ],
            //  "launchCompleteCommand": "exec-run",
            "args": ["-conf"],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [
                {"name": "IVA_SVC_CONFIG",  "value": "iva"},
                {"name": "IVA_ALG_CONFIG",   "value": "test"}
            ],
            "externalConsole": true,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}     

envronment:
 1 centos 7
 2 
![image](https://user-images.githubusercontent.com/5948147/58883820-c4f38c00-8711-11e9-92dc-c72f3f6d2e9c.png)
3 cmake version 3.12.4

**Comment by KoeMai** [comment]
It looks like a bug.
May be it is simular to the problem of this (issue) [https://github.com/Microsoft/vscode/issues/70125#issuecomment-471938288].

**Comment by andreeis** [comment]
Please upgrade to latest CMake Tools and reactivate if you still see problem.
