### ISSUE TITLE
CMAKE_C_COMPILER set incorrectly on Windows with Clang

### ISSUE THREAD

**Issue by ChristianKuehnel** [microsoft/vscode-cmake-tools#699]
### Brief Issue Summary

I want to use vscode-cmake-tools with clang on Windows. I configured clang as my compiler in the `cmake-tools-kits.json`:
```json
[
  {
    "name": "clang",
    "compilers": {
      "CC": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
    }
  }
]
```

It has to be `-cl` version of clang executable, to target the MSVC ABI on Windows.

I'm using clang 8 from the installer from the llvm website: http://releases.llvm.org/download.html#8.0.0

### Expected:

When I now cmake clean reconfigure on my project, the `build\CMakeCache.txt` should point all compilers to `clang-cl.exe`:

```json
CMAKE_CC_COMPILER:FILEPATH=C:/Program Files/LLVM/bin/clang-cl.exe
CMAKE_CXX_COMPILER:FILEPATH=C:/Program Files/LLVM/bin/clang-cl.exe
CMAKE_C_COMPILER:FILEPATH=C:/Program Files/LLVM/bin/clang-cl.exe
```

### Apparent Behavior:

The result is:
```json
CMAKE_CC_COMPILER:FILEPATH=C:/Program Files/LLVM/bin/clang-cl.exe
CMAKE_CXX_COMPILER:FILEPATH=C:/Program Files/LLVM/bin/clang-cl.exe
CMAKE_C_COMPILER:FILEPATH=C:/Program Files/LLVM/bin/clang.exe
```

The first two line are correct, but the 3rd line is incorrect. It must also be `clang-cl.exe`. Otherwise configuring will fail. So the `CMAKE_C_COMPILER:FILEPATH` line should identical to `CMAKE_CC_COMPILER:FILEPATH`.

If I change the 3rd line manually, this error disappears.

### CMake Tools Log

```
[cmake] The C compiler identification is Clang 8.0.0
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineCompilerId.cmake:859 (message):
[cmake]   The Clang compiler tool
[cmake] 
[cmake]     "C:/Program Files/LLVM/bin/clang.exe"
[cmake] 
[cmake]   targets the MSVC ABI but has a GNU-like command-line interface.  This is
[cmake]   not supported.  Use 'clang-cl' instead, e.g.  by setting 'CC=clang-cl' in
[cmake]   the environment.  Furthermore, use the MSVC command-line environment.
[cmake] Call Stack (most recent call first):
[cmake]   C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeDetermineCCompiler.cmake:114 (CMAKE_DIAGNOSE_UNSUPPORTED_CLANG)
[cmake] 
[cmake] 
[cmake] Configuring incomplete, errors occurred!
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.13
- **VSCode Version**:  1.35.0
- **CMake Tools Extension Version**: 1.13
- **Compiler/Toolchain**: clang 8.0.0

**Comment by KoeMai** [comment]
Does it work with the following kit file modification?

```
[
  {
    "name": "clang",
    "compilers": {
      "C": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
      "CC": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
    }
  }
]
```

**Comment by ChristianKuehnel** [comment]
Nope, this it the first thing that I tried :)

Am Fr., 7. Juni 2019 um 23:48 Uhr schrieb KoeMai <notifications@github.com>:

**Comment by KoeMai** [comment]
I tried to reconstruct the problem, But it didn´t work. 
My working configuration looks like this

```
{
    "name": "Clang 8.0.0 for MSVC with VisualStudio.11.0 (amd64)",
    "visualStudio": "VisualStudio.11.0",
    "visualStudioArchitecture": "amd64",
    "compilers": {
      "C": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe",
      "CXX": "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
    }
  }
```

`visualStudio `and `visualStudioArchitecture `are needed to select the correct Visual Studio Environment.

Is your kit configuration created by CMake scan for kits command?

**Comment by andreeis** [comment]
@ChristianKuehnel, please upgrade to latest CMake Tools and let us know if this problem still occurs.
