### ISSUE TITLE
Target debugging keyboard shortcut conflicts with VSCode defaults

### ISSUE THREAD

**Issue by willyd** [microsoft/vscode-cmake-tools#700]
### Brief Issue Summary

When I hit `Ctrl+F5` CMake tools asks me to configure a project even when I am trying to debug a python file. `Ctrl+F5` is bound with [Start withtout debugging](https://code.visualstudio.com/docs/editor/debugging#_run-mode) by vscode itself.

I think you should avoid to override VSCode own keyboard shortcuts. Or disable them if there is not CMakeLists.txt in the workspace root.

### Expected:

The debugger launches the python script I am trying to debug.

### Apparent Behavior:

CMake tools asks me to configure the project even though this is not a C++ project. There might be some .cpp files and CMakeLists.txt somehwere in the source tree but these are only used to build python extensions.

### Platform and Versions

- **Operating System**: Ubuntu 18.05
- **CMake Version**: 3.14.3
- **VSCode Version**: 1.35.1
- **CMake Tools Extension Version**: 1.1.3

### Other Notes/Information

Work around: disable the extension for the workspace.

**Comment by bobbrow** [comment]
This issue has been addressed in CMake Tools 1.2.0 which is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.

**Comment by damdaepark** [comment]
I am using CMake Tools 1.3.1 and the same problem happens to me. Are you sure the problem has been solved?

**Comment by andreeis** [comment]
Actually, this was partially fixed in 1.2. For cases where the CMake Tools extension still activates because of trigger files located somewhere in the repo folders structure, the command is still active in 1.3.1. The complete fix is coming in 1.4.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
