### ISSUE TITLE
scanForKits gives exception "Unhandled Promise rejection"

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#703]
- **Operating System**: VS Code running on Windows 10, with remote connection to Centos 7.6 - **CMake Version**: 3.13
- **VSCode Version**: 1.35.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: RH Developer Toolset GCC 7.3.1

I have added a kit to cmake-tools-kits.json to specify GCC 7.3.1:

    [
      {
        "name": "GCC 4.8.5",
        "compilers": {
          "C": "/usr/bin/gcc",
          "CXX": "/usr/bin/g++"
        }
      },
      {
        "name": "GCC for x86_64-redhat-linux 4.8.5",
        "compilers": {
          "C": "/usr/bin/x86_64-redhat-linux-gcc",
          "CXX": "/usr/bin/x86_64-redhat-linux-g++"
        }
      },
      {
        "name": "GCC 7.3.1 from RedHat Developer Toolset 7",
        "compilers": {
          "C": "/opt/rh/devtoolset-7/root/usr/bin/gcc",
          "CXX": "/opt/rh/devtoolset-7/root/usr/bin/g++"
        }
      }
    ]

Since adding the third entry, when I select any kit in the list I get this exception:

    [rollbar] Unhandled exception: Unhandled Promise rejection: scanForKits [cmake-server] Failed to activate protocol version: Generator "Visual Studio 15 2017" not supported. {}

Any thoughts please?

**Comment by DavidA2014** [comment]
I think the reason for this is that my user settings contained:

    "cmake.generator": "Visual Studio 15 2017",

but I was running a remote SSH session on a Linux machine that did not have that generator.  I deleted the setting and the exception did not occur.

**Comment by andreeis** [comment]
We are closing this issue for now. Please upgrade to latest CMake Tools and let us know if you encounter any other issues.
