### ISSUE TITLE
Hangs with 'CMake Tools initializing...: Creating backend' if opt-in ignored

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#704]
- **Operating System**: Centos 7.6
- **CMake Version**: 3.13.1
- **VSCode Version**: 1.35.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: RH Devtoolset 7

This occured when running a remote SSH session on Centos 7.6 from Windows 10.

After opening a folder, CMake Tools hung with:

    CMake Tools initializing...: Creating backend

The log contained:

    'Asking user for permission to user Rollbar...'

This was for a new CMake Tools install. I realised that I hadn't opted in for sharing debug info for CMake Tools.  The pop-up asking for that had disappeared and CMake tools was hanging.

It was hard to identify what was the problem.  I think this needs to be made more user friendly.

**Comment by exbutterfly** [comment]
Hi,
I faced to the same issue when using remote-ssh extension from Windows 10 to Ubuntu 18.04.
As a workaround, i put `"cmake.rollbar-optin3": false` in `settings.json` config file.
It worked for me.
Hope someone thinks is useful.

Regards,

Operating System: Ubuntu 18.04
CMake Version: 3.10.2
VSCode Version: 1.36.0
CMake Tools Extension Version: 1.1.3

**Comment by felipegutierrez** [comment]
hi, where can I find the `settings.json` file for Visual Studio Code on Ubuntu?

**Comment by bobbrow** [comment]
If you run the "Preferences: Open Workspace Settings" command, you can edit the settings.  You can also get there by pressing <kbd>CTL</kbd>+<kbd>,</kbd>

**Comment by bobbrow** [comment]
This should be fixed in newer versions of CMake Tools.  We don't use the rollbar module anymore.
