### ISSUE TITLE
How to verify CMakeTools is configuring Intellisense

### ISSUE THREAD

**Issue by williamwest0520** [microsoft/vscode-cmake-tools#711]
How do I verify that CMakeTools is set up to configure Intellisense. All I'm seeing is the information about how to say yes or no when you first configure. Nothing about "What if I said no and I change my mind?" I can't remember whether I said yes or no originally.

I've just had a handful of issues with the C/C++ extension, and currently my code is covered in red squiggles that it shouldn't have, and I want to see whether CMakeTools is playing its part correctly.

**Comment by bobbrow** [comment]
cpptools has a "Change Configuration Provider" command you can use to check.

![image](https://user-images.githubusercontent.com/12818240/61482142-c63de880-a94e-11e9-9d45-a4763bbaca9e.png)

![image](https://user-images.githubusercontent.com/12818240/61482128-be7e4400-a94e-11e9-8847-0cce0e85921b.png)

CMake Tools has a `configureOnOpen` setting you can use to make sure that CMake is configured when you open your folder.  IntelliSense configurations can't be sent to cpptools until you have configured, so this is a good setting to enable.  (We may make this the default in the future and remove the popup to reduce confusion).

![image](https://user-images.githubusercontent.com/12818240/61482338-351b4180-a94f-11e9-81a6-f8cd8e9537b2.png)

If both of those are set and you're still not getting the configurations sent, you can [enable Debug logging](https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/Enabling%20logging.md) in cpptools to see what's going wrong.

**Comment by williamwest0520** [comment]
That's exactly what I was looking for. CMake Tools was not active, and turning it on removed my squiggles, so that's great.
