### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#712]
This extension is now being maintained by Microsoft. We want to thank @vector-of-bool for all of his hard work that got the extension into the state it is in today.

We are currently reviewing the existing issues and pull requests so please be patient with us while we get caught up on the backlog.

Thanks!

**Comment by bobbrow** [comment]
This issue has been addressed in CMake Tools 1.2.0 which is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.

**Comment by H-G-Hristov** [comment]
@bobbrow Congratulations on the first release as the new maintainer!
I have a couple of off-topic questions: https://marketplace.visualstudio.com/items?itemName=vector-of-bool.cmake-tools displays the older version still. I guess that is the meaning of the note above and it will be updated later. (I am not familiar with the marketplace release process).

Do you have any roadmap when will future updates be released? What will be the release cadence?
I think as there alot of issues/features that remain to be implemented it would be beneficial if there are smaller but more frequent releases bi-monthly or even a monthly release. Maybe even a beta channel would be good to have.

**Comment by bobbrow** [comment]
There was a hiccup in the process and we had to temporarily unpublish while the Marketplace team does some work to migrate CMake Tools 1.1.3 to our publisher id so that auto-upgrade to 1.2.0 can happen.  It may take a day to resolve since we're on opposite sides of the world.

We haven't settled on a release cadence yet.  Right now, we'll be doing them based on critical mass.  For example, we have plans to get CMake FileAPI and multi-root support done in the next two months or so and we'll have another release then. 

We plan to port over the "insiders" logic we have from cpptools into this extension so we can have a beta channel since that has been super helpful for us get feedback and find unexpected issues in cpptools early.

**Comment by H-G-Hristov** [comment]
A new release in a couple of months with these two features sounds quite exciting.
Will CMake FileAPI and multi-root support require a huge architectural change in the extension from the perspective of third party contributors? I'm interested in tinkering with the extension in a connection of an issue I have.

**Comment by bobbrow** [comment]
How big of a change are you thinking about?  FileAPI is mostly adding a new driver and some related parts so it's relatively isolated.  Multiroot may change some abstractions but shouldn't be too hard to merge in.

It really depends on what you plan to do.  You are welcome to tinker with the code and we can help you merge stuff in (if necessary) when the time comes.

**Comment by vector-of-bool** [comment]
@bobbrow. Funnily enough (but not really surprising), the publisher ID change has now broken _downgrades_ (when using the `Install Another Version...` menu in the extensions panel). I was contacted by a user in the CppLang Slack to produce a VSIX for the prior release as the upgrade had broken functionality that they found critical to their workflow, and they confirmed that manually installing the old VSIX successfully downgrades. Do you think it prudent to publish a VSIX for 1.1.3? Unfortunately, I didn't have the foresight to attach a VSIX for each release to the release in GitHub.

**Comment by bobbrow** [comment]
I will do that.  It looks like someone posted the 1.1.3 vsix in an issue.
