### ISSUE TITLE
Exception following VSCode startup after following Getting Started instructions

### ISSUE THREAD

**Issue by itbgcthate** [microsoft/vscode-cmake-tools#713]
Reference issue #701, "Error: spawn ctest ENOENT", closed by the initiator.
Reference issue #522, "Stuck with 'Configuring project: Saving open files'", open.

I'm opening a new issue because #701 was closed by the initiator without a description for how it was mitigated. Issue #522 appears to be common to a number of situations.
------------------------------

I get the following exception after restarting VSCode when following instructions in the Getting Started document during initial setup. Everything configures and builds fine until VSCode is restarted.

[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: spawn ctest ENOENT {"folder":{"uri":{"$mid":1,
"fsPath":"c:\Users\Me\Documents\Projects\Embedded\VSCode\MyProject","_sep":1,
"external":"file:///c%3A/Users/Me/Documents/Projects/Embedded/VSCode/MyProject",
"path":"/c:/Users/Me/Documents/Projects/Embedded/VSCode/MyProject","scheme":"file"},
"name":"MyProject","index":0}}

It seems to be having a problem with the definition of "external".

**Comment by lyk7539511** [comment]
Same issue, have you worked out any approach to solve the problem? @itbgcthate

**Comment by itbgcthate** [comment]
I have not.

**Comment by emanspeaks** [comment]
Are you both using MinGW by chance? Make sure that CTest is on your system PATH, and then do a Scan for Kits.  There's a bug with MinGW kits that it saves off your PATH variable when you do a scan, so if CTest was not on the path at the time you first scanned, it will not find CTest subsequently when using that kit.  See #760.

**Comment by bobbrow** [comment]
Is this still an issue?  We made some fixes to MinGW scenarios recently and would ask that you try again.  If it is still an issue, can you please provide instructions for how to reproduce the problem? (e.g. a repository to clone, and which version of CMake and MinGW you are using.)

Thank you!
