### ISSUE TITLE
Error upgrading CMake with Remote-WSL extension

### ISSUE THREAD

**Issue by MarkusWalzth** [microsoft/vscode-cmake-tools#718]
### Brief Issue Summary

Hi, I try to use your plugin together with WSL. The plugin itself works fine on native Ubuntu and Windows 10, but working on WSL gives me the following Errors:

```
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open TypeError: Cannot read property 'on' of undefined {"folder":{"uri":{"$mid":1,"fsPath":"/home/maggo/programming/test/cmake-test","external":"file:///home/maggo/programming/test/cmake-test","path":"/home/maggo/programming/test/cmake-test","scheme":"file"},"name":"cmake-test","index":0}}
[rollbar] Unhandled exception: Error during CMake upgrade TypeError: Cannot read property 'on' of undefined {"version":"3.13.2","linuxURL":"https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Linux-x86_64.sh","windowsURL":"https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-win64-x64.msi"}

```

I already tried to switch off all other plugins, to avoid side effects, but nothing helped yet. Building in the terminal with cmake and make works as expected. 

### Expected:

Configure and build CMake project in designated folder

### CMake Tools Log
```
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open TypeError: Cannot read property 'on' of undefined {"folder":{"uri":{"$mid":1,"fsPath":"/home/maggo/programming/test/cmake-test","external":"file:///home/maggo/programming/test/cmake-test","path":"/home/maggo/programming/test/cmake-test","scheme":"file"},"name":"cmake-test","index":0}}
[rollbar] Unhandled exception: Error during CMake upgrade TypeError: Cannot read property 'on' of undefined {"version":"3.13.2","linuxURL":"https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Linux-x86_64.sh","windowsURL":"https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-win64-x64.msi"}
```

### Platform and Versions

- **Operating System**: Windows 10 WSL
- **CMake Version**: 3.15.0
- **VSCode Version**: 1.36.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: clang 8.0.0

**Comment by bobbrow** [comment]
Have you tried using the [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) extension?  It makes the experience work much more like native Ubuntu.

**Comment by MarkusWalzth** [comment]
Yes. And it seems I forgot to mention this. Sry!!
I've installed the some of the"Remote" packages available (Remote - WSL, - SSH*, - Development). 

Additional active extensions : 
 - C/C++ extension from Microsoft

I also tried to experiment with the "CMake" extension from twxs and the "CMake Tools Helper" extension, but nothing worked so far.

Here is the code I try to configure/generate/build/run:

CMakeLists.txt:
```
cmake_minimum_required( VERSION 3.5 )
project( cmake-test )

set( CMAKE_CXX_STANDARD 17 )

add_executable( out main.cpp )
```

main.cpp:
```
#include<iostream>

int main(void) {

    std::cout << "F*** this" << std::endl;

    return 0;
}
```

Fun part is, that I can call 'cmake .. && make && ./out' from a build folder created in the root directory from the shell inside vs code....

**Comment by bobbrow** [comment]
I don't reproduce the problem.  There must be something else going on.

Just for sanity, can you confirm that the extensions have been installed in the WSL instance?  VS Code needs to install the linux versions when you start using the Remote extensions and this doesn't happen automatically.

![image](https://user-images.githubusercontent.com/12818240/62068936-0bcea100-b1ec-11e9-854d-9a635baa904f.png)

**Comment by bobbrow** [comment]
Oh, wait.  My bad.  This looks like it's related to the CMake auto-upgrade code.

**Comment by Quincunx271** [comment]
There's an official CMake APT repository for CMake ([blog post announcement](https://blog.kitware.com/ubuntu-cmake-repository-now-available/), which links to instructions on setup at https://apt.kitware.com/). I don't know how the CMake auto-upgrade code works, but perhaps it could recommend setting up this apt repo?

**Comment by danielmrussell** [comment]
I have the same problem.  When hitting "Build" in VS Code, started from a WSL console, an error popuup says "No index file found." There is absolutely no further information about the origin of the error, and no link, etc. 

In Output, it reads:

`[variant] Loaded new set of variants
[kit] Successfully loaded 11 kits from /home/drussell/.local/share/CMakeTools/cmake-tools-kits.json
[main] Configuring folder: waveweaver 
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: No index file found. {"folder":{"uri":{"$mid":1,"fsPath":"/mnt/f/projects/waveweaver","external":"file:///mnt/f/projects/waveweaver","path":"/mnt/f/projects/waveweaver","scheme":"file"},"name":"waveweaver","index":0}}
[main] Building folder: waveweaver 
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: No index file found. {}
[main] Building folder: waveweaver 
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: No index file found. {}
[main] Building folder: waveweaver 
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: No index file found. {}
[main] Building folder: waveweaver 
[rollbar] Unhandled exception: Unhandled Promise rejection: build Error: No index file found. {}`

**Comment by danielmrussell** [comment]
After sudo apt-get install clang, and similar for gcc, then scanning for Cmake kits so the system could auto build them again, it fixed it.  Might be worth a shot.

**Comment by MarkusWalzth** [comment]
I'm hella sorry, but just got a notification for new mesages in this thread NOW....

I solved the problem by deleting an reinstalling the whole windows10 partition 2 weeks later (i did this not because of this issue ;) )

An other user mailed me once with his solution:
"After sudo apt-get install clang, and similar for gcc, then scanning for Cmake kits so the system could auto build them again, it fixed it. Might be worth a shot."

it didn't work for me that time

**Comment by bobbrow** [comment]
We actually removed this feature last year because it didn't work consistently.  Thanks for closing the issue.
