### ISSUE TITLE
use cmake with `remote container` plugin

### ISSUE THREAD

**Issue by oak-tree** [microsoft/vscode-cmake-tools#721]
I just discover `remote-container` plugin of `vcode`. This plugin has great potential. In our use case, we are using `cpp` with `Cmake`. Is it an option to combine `cmake-tool` with `Remote-containers`? At the moment Cmake is not capable of finding the Cmake in the running container
- **Operating System**: 
- **VSCode Version**:

**Comment by xgdgsc** [comment]
Also hoping it work with remote sftp.

**Comment by bobbrow** [comment]
@oak-tree do you have CMake installed in your container?  This extension is just a shell over CMake itself and CMake doesn't have any direct interoperability with the vscode remote extensions that I am aware of.

@xgdgsc,  If CMake can't work directly with your sftp setup (did you map the remote to another folder?), then the extension won't be able to either.  Can you explain your configuration a bit more?

**Comment by xgdgsc** [comment]
I open remote withe the vscode remote development kit, the sftp extension and installed cmake-tools inside the remote 

![DeepinScreenshot_select-area_20190830073344](https://user-images.githubusercontent.com/1189869/63983270-898e1100-caf8-11e9-810b-db6c5510eee7.png)

I use cmake-tools on the remote machine at work everyday without problems. I try to remote develop from home machine for now.
