### ISSUE TITLE
CMake GLOB source files: CMake Tools' is unable to provide IntelliSense configuration information

### ISSUE THREAD

**Issue by comphilip** [microsoft/vscode-cmake-tools#722]
### CMake GLOB source files: CMake Tools' is unable to provide IntelliSense configuration information

Use `FILE (GLOB )` to collect C++ source files, instead of manually adding everyone of them. CMake tools cannot provide IntelliSense configuration information on new created .hpp or .cpp files.

### Expected:

1. CMakeLists.txt with following partial definition
   ```CMake
   file (GLOB SRC_FILES 
       ${PROJECT_SOURCE_DIR}/*.h
       ${PROJECT_SOURCE_DIR}/**/*.h
       ${PROJECT_SOURCE_DIR}/*.hpp
       ${PROJECT_SOURCE_DIR}/**/*.hpp
       ${PROJECT_SOURCE_DIR}/*.c
       ${PROJECT_SOURCE_DIR}/**/*.c
       ${PROJECT_SOURCE_DIR}/*.cpp 
       ${PROJECT_SOURCE_DIR}/**/*.cpp
   )
   add_executable(${PROJECT_NAME} ${SRC_FILES})
   ```
2. Create new .hpp or .cpp file under projects.
3. `C/C++` extension call `CMake Tools` to generate intellisense configuration information, and `CMake Tools` runs `CMake: Configure` to update `compile_commands.json` file.

### Apparent Behavior:
1. CMakeLists.txt with following partial definition
   ```CMake
   file (GLOB SRC_FILES 
       ${PROJECT_SOURCE_DIR}/*.h
       ${PROJECT_SOURCE_DIR}/**/*.h
       ${PROJECT_SOURCE_DIR}/*.hpp
       ${PROJECT_SOURCE_DIR}/**/*.hpp
       ${PROJECT_SOURCE_DIR}/*.c
       ${PROJECT_SOURCE_DIR}/**/*.c
       ${PROJECT_SOURCE_DIR}/*.cpp 
       ${PROJECT_SOURCE_DIR}/**/*.cpp
   )
   add_executable(${PROJECT_NAME} ${SRC_FILES})
   ```
2. Create new .hpp or .cpp file under projects.
3. `C/C++` extension reports `'CMake Tools' is unable to provide IntelliSense configuration information`
4. Have to manully run `CMake: Configure` command to fix this issue.

### CMake Tools Log

```
```

### Developer Tools Log

```
workbench.main.js:sourcemap:240 [Extension Host] provideCustomConfiguration
workbench.main.js:sourcemap:240 [Extension Host] failed to provide configuration
```

### Platform and Versions
- **Operating System**: Ubuntu 18.04.2 LTS
- **CMake Version**: 3.14.5
- **VSCode Version**: 1.36.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: GCC 7.4.0

### Other Notes/Information
**C/C++ Extension Version**: 0.24.1

**Comment by s-martin** [comment]
The necessity to reconfigure CMake when using `file(GLOB` is a known limitation of CMake itself (and not the CMake Tools extension).

Therefor it's recommended to not use `GLOB`, but hardcode file names.

See also:
https://stackoverflow.com/questions/32411963/why-is-cmake-file-glob-evil/32412044
https://stackoverflow.com/questions/1027247/is-it-better-to-specify-source-files-with-glob-or-each-file-individually-in-cmak/1060061#1060061

**Comment by Quincunx271** [comment]
You can use the [`CONFIGURE_DEPENDS`](https://cmake.org/cmake/help/latest/command/file.html#glob-recurse) option and it will do what you want:

```cmake
# GLOB_RECURSE also simplifies your glob expressions
file (GLOB_RECURSE SRC_FILES CONFIGURE_DEPENDS
    ${PROJECT_SOURCE_DIR}/*.h
    ${PROJECT_SOURCE_DIR}/*.hpp
    ${PROJECT_SOURCE_DIR}/*.c
    ${PROJECT_SOURCE_DIR}/*.cpp 
    # Alternative: *.[hc] and *.[hc]pp
)
add_executable(${PROJECT_NAME} ${SRC_FILES})
```

`CONFIGURE_DEPENDS` will cause CMake to reconfigure if the glob result changes. There are disadvantages to it (I've heard that it can cause issues when merging branches, and not all generators support it), but IMO it's worth using.

**Comment by bobbrow** [comment]
Thank you for the question. Based on the discussion above, we do not plan to implement this support at this time.  If we receive more votes on this request, we can revisit the decision.
