### ISSUE TITLE
CMake long build time for "Hello World"

### ISSUE THREAD

**Issue by ducmtran** [microsoft/vscode-cmake-tools#727]
### Brief Issue Summary

I am trying to build a hello world program from [here](https://github.com/exercism/cpp/tree/master/exercises/hello-world) and CMake Tools take a very long time to build and run the test (2-3 minutes). I am new with C++ and CMake so I don't know if there is something very obvious that I'm missing. Creating a blank project with CMake Quick Start seems to work fine

### Behavior:

1. CMake: Configure
2. CMake: Build

### CMake Tools Log

[build] Starting build
[proc] Executing command: C:\cmake-3.15.2-win64-x64\bin\cmake.exe --build c:/Users/MinhDuc/Documents/Programming/exercism/cpp/hello-world/build --config Debug --target all -- -j 6
[build] Scanning dependencies of target hello-world
[build] [ 25%] Building CXX object CMakeFiles/hello-world.dir/hello_world.cpp.obj
[build] [ 50%] Linking CXX executable hello-world.exe

..then it takes a lot of time before moving on and completing the build

### Platform and Versions

- **Operating System**: Windows x64
- **CMake Version**: 3.15.2
- **VSCode Version**: 1.36.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: gcc 7.3.0

**Comment by bobbrow** [comment]
Hmm...  The project builds for me in close to 30 seconds with GCC.

```
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/git/cpp/exercises/hello-world/build --config Debug --target all -- -j 10
[build] [1/5  20% :: 1.297] Building CXX object CMakeFiles/hello-world.dir/hello_world.cpp.obj
[build] [2/5  40% :: 1.784] Building CXX object CMakeFiles/hello-world.dir/hello_world_test.cpp.obj
[build] [3/5  60% :: 18.230] Building CXX object CMakeFiles/hello-world.dir/test/tests-main.cpp.obj
[build] [4/5  80% :: 26.303] Linking CXX executable hello-world.exe
[build] [5/5 100% :: 26.730] cmd.exe /C "cd /D D:\git\cpp\exercises\hello-world\build && D:\git\cpp\exercises\hello-world\build\hello-world.exe"
```

It's much faster building with Visual Studio
```
[build] Starting build
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --build d:/git/cpp/exercises/hello-world/build --config Debug --target all -- -j 10
[build] [1/5  20% :: 1.094] Building CXX object CMakeFiles\hello-world.dir\hello_world.cpp.obj
[build] [2/5  40% :: 1.266] Building CXX object CMakeFiles\hello-world.dir\hello_world_test.cpp.obj
[build] [3/5  60% :: 4.230] Building CXX object CMakeFiles\hello-world.dir\test\tests-main.cpp.obj
[build] [4/5  80% :: 6.857] Linking CXX executable hello-world.exe
[build] LINK : hello-world.exe not found or not built by the last incremental link; performing full link
[build] [5/5 100% :: 6.999] cmd.exe /C "cd /D D:\git\cpp\exercises\hello-world\build && D:\git\cpp\exercises\hello-world\build\hello-world.exe"
```

This doesn't look like a bug in the extension to me.  Perhaps it's just a slow compiler?

**Comment by ducmtran** [comment]
@bobbrow Thanks for the response. I also try gcc 9.1.0 and have the same issue.

Yes I also realized after posting the issue that it does not seems like it's a specific issue with the extension. I try to build by running cmake from the terminal and it's still as slow

The test framework included in the build is pretty large so maybe that's the issue. If it does take 30 secs for you then I guess it's expected to take that long to build on my laptop (even though I have never had big issue with build time in other languages before). And Visual Studio probably optimizes the framework better?

I guess you can close the issue since it's not because of the extension. I just want some thoughts on this problem.

**Comment by bobbrow** [comment]
Thanks for the follow up.
