### ISSUE TITLE
[enhancement] variants matrix multiple drop down

### ISSUE THREAD

**Issue by atsju** [microsoft/vscode-cmake-tools#728]
### Brief Issue Summary

I am following the variants tutorial [here](https://vector-of-bool.github.io/docs/vscode-cmake-tools/variants.html).
This fits exactly my needs but as explained in tutorial, 

> 4 × 2 × 4 × 3 = ninety-six different variants

### Expected:

Would it be possible to do multiple dropdown, one for each axes of the matrix ?
If not, at least do a special handling for the `buildType` if prensent in variants because this alone multiplies by 3 (if using cmake default release, debug, relWithDebug) the number of variants.

**Comment by lygstate** [comment]
Well, At least, getting buildType to be dropDown, and possibly the windows kits to dropdown.

**Comment by andreeis** [comment]
@lygstate, yes you can implement this if you would like and have time. We are thinking that it might help others who wouldn't want this behavior to control this new UI from a new setting.
