### ISSUE TITLE
Allow kits to be specified at other locations besides .vscode/cmake-kits.json

### ISSUE THREAD

**Issue by mjvankampen** [microsoft/vscode-cmake-tools#731]
I'm trying to get vscode-cmake-tools to integrate with conan package manager. For this the most logical way for me would be for conan to generate a vscode-cmake-tools kit (https://github.com/mjvk/conan-vscode_cmakekit_generator). This works well, the only thing I am missing for now is the ability to point the cmake-tools extension to a kit generated by conan. This could be as simple scanning the build directory for cmake-kits.json or allowing a user to point directly to a file in the workspace.

What do you think of this?

**Comment by bobbrow** [comment]
We'll track this as a feature request.  We prioritize issues based on upvotes (e.g. 👍 reactions) and then move it to a milestone when we're about to start work on it.  If anyone from the community wants to jump in and help before we get to it, we'll be happy to review the design.

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.
