### ISSUE TITLE
Element with id XXX already registered

### ISSUE THREAD

**Issue by DexterMagnific** [microsoft/vscode-cmake-tools#734]
### Brief Issue Summary

I have a
```
Element with id ::.::test is already registered
```

error in a popup

### Expected:

No error popup

### Apparent Behavior:

I think it's because I have multiple `test/` folders. But the associated CMake projects are different.

### CMake Tools Log

```
<!-- Paste the log contents HERE -->
```

### Developer Tools Log

```
<!-- Paste the log contents HERE -->
```

### Platform and Versions

- **Operating System**: Linux
- **CMake Version**: 3.13.4
- **VSCode Version**: 1.37.0
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: standard GCC on x86_64

**Comment by bobbrow** [comment]
This appears to be a duplicate of #587.  If not, please let us know and we can reopen this one.

**Comment by DexterMagnific** [comment]
Yes, it is the same. It is linked I think to having the same folder name (here we have a test/ folder under each of our components).
