### ISSUE TITLE
Consider absorbing twxs's CMake extension

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#738]
Currently we need to install twsx's CMake extension https://github.com/twxs/vs.language.cmake to get proper CMake support. Please, consider absorbing/implementing the respective functionality into vscode-cmake-tools too to make the extension feature complete and more convenient and better supported.

**Comment by bobbrow** [comment]
Thank you for the feedback.  This is a duplicate of #93.  Can you please go add your 👍 to that issue so we can track the demand?
