### ISSUE TITLE
Add context menu items like "configure" for right clicking on explorer items.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode-cmake-tools#741]
### Current Behavior

It's not intuitive to know you have to type into the command palette.

### Expected:

Intuitively, right clicking on a CMakeLists.txt (or maybe ANY file in the project folder) should manifest a CMakeTools submenu containing actions like Configure in it.

**Comment by bobbrow** [comment]
I like the idea.  Should be doable in `package.json`

**Comment by bobbrow** [comment]
Leaving this issue open until we release the fix.

**Comment by andreeis** [comment]
CMake Tools 1.4.0 Beta is available on GitHub.
https://github.com/microsoft/vscode-cmake-tools/releases/tag/1.4.0-beta

Please try it out and let us know if you encounter any issues.

**Comment by andreeis** [comment]
This fix is available in CMake Tools #1.4.0 which has been released.
