### ISSUE TITLE
Rename and Reorganize "cmake:" commands to be more consistent and easier to remember/spot in GUI.

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode-cmake-tools#743]
### Brief Issue Summary

The command display names seem inconsistent and difficult to grok. For instance, it's hard to see "cmake: Set the current build variant."

### Expected:

All command names should be short, sweet, visually grokkable immediately, and organized as logically as possible. Preferably, commonly accessed functions should be at the top of the list, so alphabetically organized smartly as well. For instance,

cmake: set the current build variant

is quite difficult to spot. It requires scrolling already, then careful reading of an almost sentence-long amount of information.

cmake: Set Variant

and similarly for other options like that would vastly improve the readability and mental organization.

Thanks!

**Comment by bobbrow** [comment]
If you or anyone else has any specific suggestions for command renaming, would you be able to list them out here, or better yet, open a PR with your suggestions and we can discuss them?  All command names live in `package.json`.

**Comment by MathiasMagnus** [comment]
How can we contribute with localization?

**Comment by bobbrow** [comment]
@MathiasMagnus we're working on setting up a process for this.  There are some files our localization team uses to track all of their work and we don't commit those files to this repo, so it's not super straightforward yet.

We're pushing for the process to be for you to simply open a PR with the suggested changes. After that we'll do some work behind the scenes and then replace your PR with an automated PR that has the changes and is synced with our internal system.

**Comment by H-G-Hristov** [comment]
> ### Brief Issue Summary
> The command display names seem inconsistent and difficult to grok. For instance, it's hard to see "cmake: Set the current build variant."
> 
> ### Expected:
> All command names should be short, sweet, visually grokkable immediately, and organized as logically as possible. Preferably, commonly accessed functions should be at the top of the list, so alphabetically organized smartly as well. For instance,
> 
> cmake: set the current build variant
> 
> is quite difficult to spot. It requires scrolling already, then careful reading of an almost sentence-long amount of information.
> 
> cmake: Set Variant
> 
> and similarly for other options like that would vastly improve the readability and mental organization.
> 
> Thanks!
Set variant ? What variant? Dog variant?  Cat variant? Compiler variant?

**Comment by bobbrow** [comment]
This issue has been addressed in CMake Tools 1.2.0 which is available in the VS Code Marketplace or on the [Releases Page](https://github.com/microsoft/vscode-cmake-tools/releases/tag/v1.2.0)

Because the publisher id has changed, VS Code does not automatically upgrade you yet. The Marketplace team will enable this in the next few days.  If you want to install 1.2.0 now, please make sure you uninstall any earlier versions of CMake Tools manually to avoid any conflicts.
