### ISSUE TITLE
reveal and auto-reveal for project outline

### ISSUE THREAD

**Issue by amir-arad** [microsoft/vscode-cmake-tools#745]
Project explorer has a reveal command (right-click an editor tab, and choose "reveal in sidebar" to focus the explorer on that file)
and an autoReveal setting (`explorer.autoReveal` - automatically reveal the active editor tab in the explorer)
It's my main navigation feature, It's the only thing I miss in the awesome project outline.

**Comment by Shapovalov-Dmitry** [comment]
Found this issue while searching how to reveal in the outline. It can be achieved now - three dots menu in the header of the outline → Follow cursor
![image](https://user-images.githubusercontent.com/35997118/90544073-473d6400-e18f-11ea-8ec1-de3ba7a5e58d.png)

**Comment by cdleonard** [comment]
Not clear why this issue is still open or how it related to cmake but the "follow cursor" tip for outline is amazing!

**Comment by andreeis** [comment]
@cdleonard, thank you for reminding us of this GitHub issue. Cool finding about "follow cursor".
@amir-arad, I am closing this for now and let us know if there is anything else that think will be useful to be implemented in CMake Tools and which is not achieved already.
