### ISSUE TITLE
EACCES Error on startup of visual studio code

### ISSUE THREAD

**Issue by MaximumProgrammer** [microsoft/vscode-cmake-tools#751]
#Brief Summary

Dear Team i am getting this kind of error and i don't know how to handle it,

**Failed to start CMake Client(....): EACCES: permission denied, mkdir '/build'**

This mainly happens on the startup of visual studio code.

### Platform and Versions

- **Operating System**: Ubuntu 18.04
- **CMake Version**: 3.15.2
- **VSCode Version**: 1.37.1
- **CMake Tools Extension Version**:  1.1.0
- **Compiler/Toolchain**: GCC 5.3, Clang.

**Comment by bobbrow** [comment]
Can you share some of your settings?  For example, there may be a problem with how you set `"cmake.buildDirectory"`.  It looks like maybe a variable didn't resolve.

**Comment by ZeroCool11000** [comment]
This is my whole settings file 

{
    "files.autoSave": "afterDelay",
    "workbench.editor.labelFormat": "short",
    "workbench.settings.openDefaultKeybindings": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "editor.fontSize": 13.5,
    "debug.console.fontSize": 13.5,
    "terminal.integrated.fontSize": 13.5,
    "window.zoomLevel": -1,
    "cmake-tools-helper.cmake_download_path": "/home/mgruber/.vscode/extensions/maddouri.cmake-tools-helper-0.2.1/cmake_download",
    "cmake.configureOnOpen": false,
    "cmake.useCMakeServer": true, 
    "workbench.settings.openDefaultSettings": true,
    "explorer.confirmDelete": false,
    "vssolution.solutionExplorerIcons": "mix",
    "vssolution.trackActiveItem": true,
    "svn.enableProposedApi": "product",
    "terminal.integrated.shell.linux": "/bin/sh",
    "files.associations": {
        "*.json": "cpp"
    },
    "[c]": {
                "editor.defaultFormatter": "xaver.clang-format"
        },
    "[cpp]": {
                "editor.defaultFormatter": "xaver.clang-format"
    },
    "telemetry.enableTelemetry": false,
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.formatting": "Disabled",
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.intelliSenseEngine": "Disabled",
    "cquery.launch.command": "/home/mgruber/git/cquery/build/release/bin/cquery",
    "cquery.cacheDirectory": "/home/mgruber/.cquery-cache/", 
    "cquery.highlighting.enabled.types": true,
    "cquery.highlighting.enabled.freeStandingFunctions": true,
    "cquery.highlighting.enabled.memberFunctions": true,
    "cquery.highlighting.enabled.freeStandingVariables": true,
    "cquery.highlighting.enabled.memberVariables": true,
    "cquery.highlighting.enabled.namespaces": true,
    "cquery.highlighting.enabled.macros": true,
    "cquery.highlighting.enabled.enums": true,
    "cquery.highlighting.enabled.typeAliases": true,
    "cquery.highlighting.enabled.enumConstants": true,
    "cquery.highlighting.enabled.staticMemberFunctions": true,
    "cquery.highlighting.enabled.parameters": true,
    "cquery.highlighting.enabled.templateParameters": true,
    "cquery.highlighting.enabled.staticMemberVariables": true,
    "cquery.highlighting.enabled.globalVariables": true,
    "beautify.onSave": true,
    "editor.formatOnSave": true,
    "clang-format.executable" : "/usr/bin/clang-format-10" ,
    "editor.formatOnType" : true,
    "C_Cpp.clang_format_style": "file",
    "C_Cpp.clang_format_fallbackStyle": "Google", 
    "C_Cpp.clang_format_path": "/usr/bin/clang-format-10",
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "cmake.cmakePath":"/usr/bin/cmake"
}

is it possible that this related to the cmake version ?

best regards,
