### ISSUE TITLE
Allow variant name substitution in cmake.buildDirectory

### ISSUE THREAD

**Issue by ggilles** [microsoft/vscode-cmake-tools#764]
### Brief Issue Summary

It would be very convenient to be able to have a different build directory for each variant in a project. This would minimize build time when switching variants in a project.

### Expected:

For example, given the following `cmake-variant.json` file:
```json
{
  "buildType": {
    "default": "debug",
    "choices": {
      "debug": {
        "short": "Debug",
        "buildType": "Debug"
      },
      "release" : {
        "short": "Release",
        "buildType": "Release"
      }
    }
  },
  "myVariant" : {
    "default": "AllFeatures",
    "choices": {
      "AllFeatures" : {
        "short": "AllFeatures",
        "long": "Enable all features"
      },
      "Lightweight" : {
        "short": "Lightweight",
        "long": "No optional feature"
      }
    }
  }
}
```

I would expect to be able to reference the variant name in `cmake.buildDirectory` like this:
```json
"cmake.buildDirectory": "${workspaceRoot}/build/${buildType}_${myVariant}"
```
Selecting the variant `Debug + AllFeatures` would select the `<workspace-root>/build/Debug_AllFeatures` build directory.

### Apparent Behavior:

Issue #272 suggest that this problem should already be solved, but in practice, selecting the variant `Debug + AllFeatures` selects the `<workspace-root>/build/Debug_${myVariant}` build directory, i.e. the variant name is not substituted in the `cmake.buildDirectory` variable.

### Platform and Versions

Tested on MacOS with cmake 3.13.3, VScode 1.38 and cmake-tools 1.1.3

**Comment by bobbrow** [comment]
Can you try `${variant:myVariant}` instead?  https://vector-of-bool.github.io/docs/vscode-cmake-tools/changelog.html?highlight=variant has more details about this breaking change.

**Comment by ggilles** [comment]
It works! I couldn't find that info by myself, thanks a lot for this!
