### ISSUE TITLE
CMake Kits manual editing bug

### ISSUE THREAD

**Issue by Misfittech** [microsoft/vscode-cmake-tools#765]
CMake Tools Version 1.1.3, on windows 10 x64

I am having a problem manually editing the cmake-tools-kits.json. 

I hit "Ctrl-shift-P" to open command pallet and then run:
"CMake: Edit user-local CMake Kits"

This opens the file "C:\Users\xxxx\AppData\Local\CMakeTools\cmake-tools-kits.json" which is different than the documentation here: 
https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html#kits

The file is empty as I have no "standard" compilers installed on the computer.  So I enter my compiler information:
```
[
    {
        "name": "arm-none-eabi 8-2019-q3",
        "compilers" : {
            "CC": "C:/Program Files (x86)/GNU Tools ARM Embedded/8 2019-q3-update/bin/arm-none-eabi-gcc.exe",
            "CXX": "C:/Program Files (x86)/GNU Tools ARM Embedded/8 2019-q3-update/bin/arm-none-eabi-g++.exe"
        }
    }
]
```

Then I save the file.
When I click the [No active kits] in the status bar it requests to scan for kits, which does and then deletes my compiler. 

I am new to CMake so I assume I must be doing something wrong....

**Comment by bobbrow** [comment]
The documentation you linked to was trying to explain the difference between "user-local" kits and "project" kits.  The command you invoked opens the "user-local" kits which are in a shared location and will be replaced when you rescan for kits.

It sounds like what you want to do is create a `cmake-kits.json` file in the `${workspaceFolder}/.vscode` directory instead.  This will add your manual kit to the list.
