### ISSUE TITLE
The documentation on "Configuring a project" fails to actually ever mention how to configure a project,

### ISSUE THREAD

**Issue by danielmrussell** [microsoft/vscode-cmake-tools#769]
### Brief Issue Summary

When googling for how to configure a project using the CMake Tools GUI, no answer can be found. What button? What menu? where is it? Can't find it. 

The actual documentation goes into interesting theory about *implementation* but actually fails to mention *how* a user induces a configure step.

### Expected:

Explain how to configure stuff using the GUI.

**Comment by bobbrow** [comment]
Which documentation are you looking at?  My search takes me here: https://vector-of-bool.github.io/docs/vscode-cmake-tools/getting_started.html#configuring-your-project

**TL;DR**
* First, let the extension scan for "Kits" (aka: compilers)
  * (1.5: if you want to change the compiler, click the text in the status bar to pick a new one)
* Second, select a build variant (e.g. Debug, Release, etc)
* Third, click the "Build" button

This can all be controlled via the status bar:
![image](https://user-images.githubusercontent.com/12818240/64898519-44abc380-d63c-11e9-84eb-7cc0d45dd582.png)

If you need to pass any options to CMake, you do it with [`cmake.configureSettings`](https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#cmake-configuresettings) or [`cmake.configureArgs`](https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#cmake-configureargs).  You can access the VS Code settings UI by pressing <kbd>CTL</kbd>+<kbd>,</kbd>

**Comment by danielmrussell** [comment]
This may be that I find the documentation navigation confusing/obscure and
relied on google, which tends to give back these URLs

https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html
https://vector-of-bool.github.io/docs/vscode-cmake-tools/configuring.html

Now, I *did* try to use the navigation to find what I was looking for and
somehow failed.
:(

**Comment by bobbrow** [comment]
Thank you for the feedback.  Do you think it would be valuable if we added a link back to the "getting started" page at the top of those topics you shared?

**Comment by danielmrussell** [comment]
Maybe with a short sentence or two so people understand the context. The
problem is I have to learn like 20 different things, as a software
developer, so it would help to make it fast to scan for the information as
well. Maybe short blurb.

**Comment by thomthom** [comment]
> If you need to pass any options to CMake, you do it with cmake.configureSettings or cmake.configureArgs. You can access the VS Code settings UI by pressing CTL+,

But this goes into the project settings under source control. How do you provide options which are machine specific?

**Comment by s-martin** [comment]
Visual Studio Code differentiates between user settings (local) and workspace settings (could be versioned), see https://code.visualstudio.com/docs/getstarted/settings

**Comment by thomthom** [comment]
But if I set `cmake.configureSettings` at user settings - then that would affect all projects. Isn't there a way to configure locally per-project?

**Comment by bobbrow** [comment]
@thomthom do you want "machine specific" settings or "per-project" settings?  VS Code allows for both as @s-martin references.

The way to configure machine specific is to use the user settings.

The way to configure per-project is to use the workspace settings.  This writes a `settings.json` file in the `${workspaceFolder}/.vscode` folder but if you don't want it in version control, can you use .gitignore?

**Comment by thomthom** [comment]
`settings.json` in the project folder contains important settings beyond just CMake. I have never been able to exclude it.

What I got in mind is that I have a project which is Win and Mac. I build on multiple Win and Mac machines. The location of dependent external libraries might exist in different locations from machine to machine. So it can't go into the project settings.

But if I set the CMake configuration in the user setting - then that will affect all project on that machine, right? That might conflict between projects if different projects uses different versions of dependencies.

(Mind you, I've been learning CMake for a short while, so maybe I'm missing some fundamental concepts on how to setup CMake. Best/recent CMake practices is a challenge to locate IMO.)

**Comment by bobbrow** [comment]
I would expect Mac vs Windows settings be encoded in the CMakeLists.txt, not through the configuration settings.  For example: [find_package](https://cmake.org/cmake/help/v3.13/command/find_package.html), [find_library](https://cmake.org/cmake/help/v3.15/command/find_library.html), or [find_path](https://cmake.org/cmake/help/v3.15/command/find_path.html).

Let me know if one of those would work for you instead.

**Comment by thomthom** [comment]
I haven't dived too deep into those yet. I'll read up some more on CMake and dependency handling. 
Thank you for taking the time to respond to a CMake n00b.

**Comment by bobbrow** [comment]
Documentation has moved to this repository.  We also wrote a new "getting started" with CMake Tools tutorial on the C++ language page for VS Code. https://code.visualstudio.com/docs/cpp/cmake-linux
