### ISSUE TITLE
No way to configure or choose generator (Ninja/Unix Make) or configure options/variables

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [microsoft/vscode-cmake-tools#772]
### Brief Issue Summary

Possibly related to #392 

### Expected:

I should have some way or method to persistently set cmake variables and choose ninja vs unix makefiles when first configuring a project.

### Apparent Behavior:

I get absolutely no control over CMake vars except for editing the CMakeCache.txt by hand (or cmake-gui) but these changes seem not to persist or be picked up quickly.

### Bug

When trying to run command `CMake: Edit the CMake Cache`, I get
`[rollbar] Unhandled exception: Unhandled Promise rejection: editCache Error: command 'vscode.previewHtml' not found {}`

### Platform and Versions

Operating System: Ubuntu 18.04
CMake Version: 3.15.3
VSCode Version: 1.33.0
CMake Tools Extension Version: 1.1.3
Compiler/Toolchain: GCC 7.3.0

**Comment by bobbrow** [comment]
Open `File` -> `Preferences` -> `Settings` to open the Settings UI.

![image](https://user-images.githubusercontent.com/12818240/64899113-b127c200-d63e-11e9-9836-17f8eb9be732.png)

In the search panel, type "cmake" to filter out all of the other stuff.  You can find settings to control which generator you would like to use, any variables you would like to pass to CMake, etc.

**Comment by Zingam** [comment]
@devshgraphicsprogramming You could vote for this feature request #529

**Comment by Jagdish587** [comment]
![Untitled](https://user-images.githubusercontent.com/10627507/87658102-58064e80-c779-11ea-881c-28f9d6a2090e.png)

**Comment by Jagdish587** [comment]
Open **File -> Preferences -> Setting ->** Search for **ninja** , you get CMake default generator , by default its **ninja** , you can choose your option

**Comment by hamaney** [comment]
> Open **File -> Preferences -> Setting ->** Search for **ninja** , you get CMake default generator , by default its **ninja** , you can choose your option

It worth mentioning that **Ninja** option is case-sensitive
