### ISSUE TITLE
[cms-driver] Found no matching code model for the current build type

### ISSUE THREAD

**Issue by poterba** [microsoft/vscode-cmake-tools#774]
### Brief Issue Summary

Debug can't be started for projects with overridden in CMakeLists.txt CMAKE_BUILD_TYPE

Create CMakeLists.txt:
```cmake
cmake_minimum_required (VERSION 2.6)
project (Main)
add_executable(Main main.cpp)

string(TOUPPER "${CMAKE_BUILD_TYPE}" TMP_CMAKE_BUILD_TYPE)
set(CMAKE_BUILD_TYPE "${TMP_CMAKE_BUILD_TYPE}" CACHE STRING "DEBUG RELEASE RELWITHDEBINFO MINSIZEREL" FORCE)
```

with some main.cpp. For example, minimal:
```c
int main(){}
```

Compile and try to launch debug (I've done it all via Status Bar buttons).

### Expected:

Launched debug.

### Apparent Behavior:

Nothing.

### CMake Tools Log

```
[cms-driver] Found no matching code model for the current build type. This shouldn't be possible
[cms-driver] Found no matching code model for the current build type. This shouldn't be possible
[cms-driver] Found no matching code model for the current build type. This shouldn't be possible
[main] Failed to prepare executable target with name 'undefined'
```

### Developer Tools Log

Fails check in [cms-driver.ts](../tree/develop/src/drivers/cms-driver.ts) after this:
```ts
const build_config = this._codeModel.configurations.find(conf => conf.name == this.currentBuildType);
```

At this moment _codeModel contains configuration named "DEBUG", while currentBuildType is "Debug". So search ends unsuccessfully.

### Platform and Versions

- **Operating System**: Darwin x64 18.7.0
- **CMake Version**: 3.15.3
- **VSCode Version**: 1.38.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Clang 10.0.1

**Comment by bobbrow** [comment]
Related to #766 

Out of curiosity, why do you want to change the build type in your CMakeLists.txt?

**Comment by vptrbv** [comment]
Well, it's legacy I deal with at new place. However, the only [examples](https://cmake.org/cmake/help/v3.0/variable/CMAKE_BUILD_TYPE.html) at official documentation are in uppercase. Agree, examples not for CMAKE_BUILD_TYPE, but I can understand intention to keep everything in consistent way.

**Comment by renn0xtek9** [comment]
Any update on that issue: FYI in terminal you would just 
```
cd build 
./foobar_target
```
That should not be unrealistically hard to solve right?
