### ISSUE TITLE
Make the Windows tests run reliably

### ISSUE THREAD

**Issue by KoeMai** [microsoft/vscode-cmake-tools#775]
The PR Review tests only on Travis. There are windows tests configured for AppVeyor. These tests are disabled, they are run slower. I execute them on my fork.

Since last merge the tests are [instabile](https://ci.appveyor.com/project/KoeMai/vscode-cmake-tools-6ek1x/builds/27418994), [last successful build](https://ci.appveyor.com/project/KoeMai/vscode-cmake-tools-6ek1x/builds/27419143).

Broken test:
1) Kits scan test
       Detect an MinGW compiler file on windows:
     AssertionError: object tested must be an array, a map, an object, a set, a string, or a weakset, but undefined given
      at Context.test (C:\projects\vscode-cmake-tools-6ek1x\test\unit-tests\kit-scan.test.ts:115:49)

**Comment by elahehrashedi** [comment]
the kits can test is failing single-root-UI test as well (The other tests are updated with the new API and working).

This specific test was being ignored for a period of time, so it never failed (we were showing outputs only when a test failed, now there will be some outputs to make sure we are not skipping any test, we can revert to hiding outputs when we are sure all test are running).
