### ISSUE TITLE
cmake.configureOnOpen is ignored by mistake when using custom cmake.sourceDirectory

### ISSUE THREAD

**Issue by 1354092549** [microsoft/vscode-cmake-tools#783]
# Brief Issue Summary

When I use the following vscode config file: 
```json5
{
    "cmake.sourceDirectory": "${workspaceRoot}/foo/bar",
    "cmake.configureOnOpen": true
}
```
My project is not configured on open.

### Expected:

My project should be configured on open, of course.

### Platform and Versions

- **Operating System**: Windows 10 x64
- **CMake Version**: 3.14.6
- **VSCode Version**: 1.38.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2019

**Comment by bobbrow** [comment]
This is because the extension is not currently activating unless you have a CMakeLists.txt directly in the `${workspaceFolder}`.

We fixed this with https://github.com/microsoft/vscode-cmake-tools/pull/716, which will be in version 1.2.0.  (coming soon)
