### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/cache.get.cache.key.missing"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#786]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Get cache key {0}=[[Missing]]

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Is "Missing" localizable here? Please confirm or advise.

**Comment by bobbrow** [comment]
{0} is not localized
"Missing" should be localized.

**Comment by PDostalek** [comment]
thanks
