### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/cm-upgrade.installer.failed"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#787]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The CMake installer returned non-zero [{0}]: {1}

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
What will be inserted for the first placeholder in square brackets?

**Comment by bobbrow** [comment]
I'm actually deleting the file that contains this string, so it will be removed from the xlf soon.

**Comment by PDostalek** [comment]
perfect, thx
