### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/kit.founds.kits.in.directory"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#788]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Found {0} kits in directory {1}

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Please, define placeholders

**Comment by PDostalek** [comment]
I assume numbered placeholder and path, please confirm

**Comment by bobbrow** [comment]
Yes. {0} is a number
{1} is a folder path

**Comment by PDostalek** [comment]
Thanks
