### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/drivers/cms-client.cant.yet.handle.message"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#790]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Can't yet handle the {0} messages

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Please clarify the placeholder.

**Comment by bobbrow** [comment]
{0} is a message name and should not be localized.

**Comment by bobbrow** [comment]
It's not another resource.  It's a protocol message which is a hard-coded string.
