### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/extension.post.folder.open"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#792]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Post-folder-open

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Is this translatable? If so, please, explain meaning.

**Comment by bobbrow** [comment]
This is for tracking progress while logging. The state being reported is that the folder has been opened and some final configuration will happen.

**Comment by PDostalek** [comment]
@bobbrow therefore not localizable ?

**Comment by bobbrow** [comment]
correct, not localizable

**Comment by PDostalek** [comment]
Thanks !
