### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/proc.processing.data.event.stderr"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#793]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Processing "data" event from proc stderr

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Please confirm if event names can be translated or not

**Comment by bobbrow** [comment]
do not translate "data"

**Comment by PDostalek** [comment]
thx, closing
