### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/tree.target.tooltip"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#795]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Target {0}

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Please clarify if "Target" is a noun or a verb here. If it is a noun, please clarify the placeholder.

**Comment by bobbrow** [comment]
it is a noun

**Comment by PDostalek** [comment]
thx
