### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/cpptools.unknown language"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#796]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Unknown language: {0}

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Does it mean a programming language or some language like English, French, etc.?

**Comment by bobbrow** [comment]
It is referring to a programming language

**Comment by PDostalek** [comment]
thx, closing
