### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "package.cmake-tools.configuration.cmake.outputLogEncoding.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#797]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Encoding of the output from external commands (eg.cmake -- build)

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
We assume eg. is translatable and there is just lack of space between this and "cmake -- build" . Please, confirm.

**Comment by bobbrow** [comment]
Yes. there is a space missing between `eg.` and `cmake`

**Comment by PDostalek** [comment]
thx
