### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/kit.ok.running"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#798]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
OK running {0} {1}, env vars: {3}

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Please provide more context for this string. What are the placeholders and what is meant by "env vars". Thanks.

**Comment by bobbrow** [comment]
{0} is a script file name
{1} are the arguments passed to the script
{3} is a list of environment variables

**Comment by PDostalek** [comment]
perfect, thx
