### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/kit.clang.for.msvc"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#799]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Clang {0} for MSVC with {1} ({2})

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Could you provide more info for the placeholders?

**Comment by bobbrow** [comment]
{0} is a version number for the Clang compiler
{1} is a string like "Visual Studio 16.2"
{2} is a build architecture like "x86" or "x64"

**Comment by PDostalek** [comment]
perfect
