### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/cmake-tools.debugging.documentation.button"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#800]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Debugging documentation

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Resource ID is "0; "./src/cmake-tools.debugging.documentation.button"", so we translated it as button. Is this segment a button or message?

**Comment by bobbrow** [comment]
It is a label that appears on a button. When the button is clicked it will navigate the user to debugging documentation.

**Comment by PDostalek** [comment]
Thank you
