### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/kit.detected.kit.for.version"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#801]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Detected VsKit for version

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Could we have more context here? what is after the segment?

**Comment by bobbrow** [comment]
After this string is displayed, additional information is also printed to the debug log.  The English string may not be very good.  Perhaps we should change it.  "VsKit" refers to a Visual Studio C++ compiler toolset.

**Comment by PDostalek** [comment]
Thanks for the comment
