### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/cache.parsed.entries.from"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#802]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Parsed {0} entries from {1}

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Could you provide more info for the placeholders?

**Comment by bobbrow** [comment]
{0} is a number
{1} is a file path

**Comment by PDostalek** [comment]
Thanks for clarification
