### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/extension.start.selection.of.kits"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#803]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Start selection of kits. Found {0} kits.

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Could you provide more info for the placeholders? Numbered ?

**Comment by bobbrow** [comment]
it is a number

**Comment by PDostalek** [comment]
ok, thanks
