### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "package.cmake-tools.configuration.cmake.cmakePath.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#804]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Name/path of the CMake executable to use

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Does "/" mean "and" or "or"?

**Comment by bobbrow** [comment]
It means "or"

**Comment by bobbrow** [comment]
@PDostalek did we give you the information you needed?  There are a number of loc issues still open in this repo.

Thanks!

**Comment by PDostalek** [comment]
Closing, many thanks
