### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "package.c_cpp.debuggers.miDebuggerPath.description"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#808]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The path to the MI debugger (such as gdb). When unspecified, it will search path first for the debugger.

File Name:
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
Would you please advise what is "it" here?

**Comment by bobbrow** [comment]
This should be the same as `c_cpp.debuggers.miDebuggerPath.description` in the vscode-cpptools.xlf.  
I believe "it" is the debugger extension (e.g. cpptools)

**Comment by PDostalek** [comment]
Thanks
