### ISSUE TITLE
Add "externalConsole":true for quick debug using cppvsgdb

### ISSUE THREAD

**Issue by zeyugao** [microsoft/vscode-cmake-tools#814]
### Unable process stdin with debugger using cppvsgdb

Currently the extension generates the config for cpptools as below

```
function createMSVCDebugConfiguration(target) {
    return {
        type: 'cppvsdbg',
        name: `Debug ${target.name}`,
        request: 'launch',
        cwd: '${workspaceRoot}',
        args: [],
        program: target.path
    };
}
```

However, with the missing of ```"externalConsole":true```, we can not process the stdin with debugger, which is the only way with cppvsgdb to allow me to do so.

### Expected:

Add options for enabling ```"externalConsole":true```. so that we can process the stdin without having to create a launch.json

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.15.3
- **VSCode Version**: 1.38.1
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017

**Comment by bobbrow** [comment]
Did you try adding:

```
    "cmake.debugConfig": {
        "externalConsole": true
    }
```
to your settings?  You should be able to override any of the defaults from launch.json in this setting.

**Comment by zeyugao** [comment]
@bobbrow Thanks, it works. I didn't discovered the option ```debugConfig```
