### ISSUE TITLE
Scan kits: stuck at Visual Studio Build Tools 2019

### ISSUE THREAD

**Issue by SuperSamus** [microsoft/vscode-cmake-tools#817]
### Brief Issue Summary

If I scan for kits while having Visual Studio Build Tools 2019 installed (on Windows), as soon as CMake starts scanning this kit it will never finish (thus the file that lists the kits is never saved, so I can't even use the other ones without manual editing).
The extension is stuck with bottom left notification: 

> Scanning for kits: Checking Visual Studio Build Tools 2019 with amd64_x86

### Expected:

Scanning Visual Studio Build Tools 2019 isn't an eternal operation.

### Platform and Versions

- **Operating System**: Windows 10 1903
- **VSCode Version**: 1.38.1 (had the issue on previous versions too)
- **CMake Tools Extension Version**: 1.1.3 (also tested on 1.1.2 an 1.0)
- **Compiler/Toolchain**: Visual Studio Build Tools 2019 16.3.1 (still didn't work on previous versions) (I also have Mingw and Clang installed, no problems with them, the scanning works if I don't have VS2019)

**Comment by digimatic** [comment]
I don't know but perhaps it is caused by this (I reprorted to MS and CMake): https://developercommunity.visualstudio.com/content/problem/756901/vctoolsversion-props-have-moved.html

**Comment by bobbrow** [comment]
I don't reproduce the problem, but I also have the 2017 Build Tools installed and there's a bug in 1.1.3 around Kits.  In the pending release, I see both, but it looks like I'll need to set up another machine with just the 2019 Build Tools and maybe another compiler.

@digimatic, thanks for linking that issue. I'll keep that in mind as I investigate.

**Comment by bobbrow** [comment]
I tried another machine with just VS Build Tools 16.3.2, MinGW from [here](mingw.org), and Clang 9.0 and I don't repro.  I also tried deleting all of the user-local kits before scanning.

![image](https://user-images.githubusercontent.com/12818240/66369763-889b9b00-e952-11e9-87bd-95247efb126a.png)

**Comment by SuperSamus** [comment]
I still have the issue...
Here are some logs from a fresh CMakeTools install.
[log.txt](https://github.com/microsoft/vscode-cmake-tools/files/3746509/log.txt)
What should I attempt to fix the issue? I tried to:

- Uninstall and reinstall VS Build 2019 (now on 16.3.5);
- Uninstall and reinstall CmakeBuildTools;
- Open VSCode as admin.

![immagine](https://user-images.githubusercontent.com/40663462/67143303-7bdc4880-f26a-11e9-9fe6-0c6ad05b86bb.png)

**Comment by H-G-Hristov** [comment]
On my work laptop the extension is unable to find neither the manually LLVM, nor Visual Studio 2019 Preview. It only finds my QNX environment. Thus I can only see QNX GCC toolkits and neither Clang nor MSVC ones.
Does the currently released extension support newer VS2019 versions?

**Comment by bobbrow** [comment]
We will release 1.2.0 next week with some updates in this area.
