### ISSUE TITLE
[Feature request] Need to add some custom variable definitions in configuring

### ISSUE THREAD

**Issue by Beniko95J** [microsoft/vscode-cmake-tools#821]
Hi, thank you for this awesome extension. It really makes a lot of things easy for me.

Now I would like to ask whether I can add some custom variable definitions in the configuring part? For example, when I used command-line for configuring my project, I can add some custom variables using "cmake -DSOME_VARIABLE=SOME_VALUE ...". I thought I can still define some variables when this pops up, however it doesn't support this.

![image](https://user-images.githubusercontent.com/30772597/65941028-faf91080-e464-11e9-9e46-13dc5f566594.png)
![image](https://user-images.githubusercontent.com/30772597/65941114-34318080-e465-11e9-9994-6b34f7ef3a0d.png)

So I would like to ask for this new feature for this extension.

Thanks!

**Comment by bobbrow** [comment]
We have this feature. 😃 
Some documentation here: https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#cmake-configuresettings

This is how you use it:
* Open the settings editor (<kbd>CTL</kbd>+<kbd>,</kbd>)
* If that opens the UI editor, search for "cmake configure settings" and click on the link to "edit in settings.json" under the "Cmake: Configure Settings" header
* Add the following to the JSON file:
```json
  "cmake.configureSettings": {
    "SOME_VARIABLE": "SOME_VALUE"
  }
```
* If the setting doesn't take effect immediately (there might be a bug here), you can run the "Reload Window" command to reset the CMake extension.
