### ISSUE TITLE
Support clang.exe/clang++.exe

### ISSUE THREAD

**Issue by omcnoe** [microsoft/vscode-cmake-tools#823]
CMake Tools should detect clang.exe/clang++.exe (clang that understands GNU arguments) as a kit, CMake now supports these compilers on Windows. Currently kit detection only creates a clang-cl.exe kit (clang that understands MSVC's cl.exe arguments).

Manually editing `cmake-tools-kits.json` to create a clang/clang++ kit works, CMake Tools should create this kit itself during "scan for kits".

CMake Tools incorrectly tries to use gdb for debugging when using the kit, it should use the same debugger it uses for the clang-cl.exe kit. The default vscode Windows C/C++ debug config in `launch.json`, with `"program": "${command:cmake.launchTargetPath}"` makes debugging work with my clang/clang++ kit.

**Comment by Zingam** [comment]
@bobbrow I could look into this next. It seems easy enough. Do you have any specific requirements or recommendations about the implementation?

**Comment by bobbrow** [comment]
@Zingam I can't think of any special requirements for the implementation. That would be great if you had some time to look into this!

**Comment by oninoshiko** [comment]
Just chiming in that I hit this and was fairly surprised by it. It would be nice to have.

**Comment by andreeis** [comment]
This should be fixed in CMake Tools 1.5.0 which was published today.
Let us know if you encounter any issues with this release.
