### ISSUE TITLE
Critical memory leak in cmake.exe

### ISSUE THREAD

**Issue by eugeneko** [microsoft/vscode-cmake-tools#840]
I have rare critical memory leak in cmake.exe process.

I have two instances of VSCode with two branches of this project:
https://github.com/rokups/rbfx

About once or twice a week CMake starts comsuming memory until it gets to 100%, at which point my PC completely freezes (that's why it's critical).

This time I managed to suspend CMake before it destroys my system.
CMake builds were completely finished.
However, some files in repository are locked for write.
I was rebasing branch in the repo opened in VSCode -- it may have triggered something, or maybe not.
I didn't find any interesting logs.
![image](https://user-images.githubusercontent.com/8576192/67150125-482a0e80-f2bc-11e9-8374-8fc446f2d5d6.png)

I understand it's kinda obscure bug report and it may not be realted to VSCode-cmake-tools itself.

However, I'm looking for workaround and for other people who might have same issue.

I wonder how can I prevent cmake.exe from existing in background while I'm working with VSCode.
I also wonder if there are any cmake.exe logs than I can attach.

It'd be also great if the extension monitored processes it spawned and didn't let them run unattended.

PS: Now I will try to confirm that it is cmake.exe who actually caused my freezes.
I'm going to submit this issue now, resume the process and hope I could stop it before it kills my PC.

PPS: When I resumed it, cmake.exe memory dropped back to 30MB and then started growing at the rate about 35MB/s. It has grown up to 4GB, at which point I got out of memory and decided to stop the experiment.

PPPS: When I killed cmake.exe, my RAM comsumption dropped from 16GB to 6GB. I have no idea why. cmake.exe itself was consuming only about 4GB.

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.13.3
- **VSCode Version**: 1.39.0
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017 x86, ninja

**Comment by Zingam** [comment]
How is this VSCode CMake Tools issue? Isn't that just a CMake issue? Shouldn't you report it at the CMake web/repo site?

**Comment by eugeneko** [comment]
In case, you missed, the main part of this issue is the _question_.
How can I prevent VSCode CMake Tools from keeping cmake.exe alive?

> How is this VSCode CMake Tools issue?

cmake.exe is launched by VSCode CMake Tools.
cmake.exe is kept alive by VSCode CMake Tools even if it's not building anything.
I've never had this issue using CMake w/o VSCode CMake Tools.

Maybe it's purely CMake bug.
Maybe VSCode CMake Tools is misusing CMake in some way and this is causing this defect.
How could I know whose defect it is?
Moreover, I cannot report CMake defect because I have no clue what is VSCode CMake Tools actually doing with CMake.

**Comment by Zingam** [comment]
https://cmake.org/cmake/help/v3.15/manual/cmake-server.7.html

**Comment by bobbrow** [comment]
I don't know how to prevent a bug in CMake, but you can try upgrading to a newer version and see if the bug has already been fixed.  If you open a bug on CMake they would want you to try on the latest version anyway.

**Comment by eugeneko** [comment]
> I don't know how to prevent a bug in CMake

Sorry for confusion, I mean how can I prevent VSCode CMake Tools from using CMake in this way?

I'll also try to update CMake now.

**Comment by eugeneko** [comment]
@Zingam, @bobbrow 
I'm getting this message:
```
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.
```
I suppose it would be better if VSCode CMake Tools didn't use cmake-server then.

**Comment by Zingam** [comment]
@eugeneko  I suppose cmake-server will be used for older CMake versions and for newer the new API will be used, when implemented: https://github.com/microsoft/vscode-cmake-tools/pull/720#issue-301780922

**Comment by bobbrow** [comment]
Yes, cmake-file-api support is on our radar.  If the CMake server is still causing you problems with version 3.15, you can try disabling it with this setting:

`"cmake.useCMakeServer": false,`

**Comment by eugeneko** [comment]
>  If the CMake server is still causing you problems with version 3.15, you can try disabling it with this setting:

Thanks! I'll have it as backup.
Do you know what kind of features I will lose if I disable cmake server?

**Comment by bobbrow** [comment]
You lose the ability to automatically configure IntelliSense (with the C++ extension) for your source files.  You also lose auto-discovery of targets and the project outline.  There may be other things that I'm not thinking of right now, but those are the main ones.  You can still configure, build, and debug targets, but you have to type in their names manually instead of selecting one from a list.

**Comment by vector-of-bool** [comment]
I can actually confirm that I have also seen this exact issue multiple times. Interestingly, I don't believe this to be a "leak" so much as some horrible misuse of the Windows filesystem notification APIs. `procmon` reveals that the CMake process is being bombarded with an unending stream of filesystem change notifications, and I assume CMake is buffering them up continuously. They won't stop until you kill the CMake process, and CMake itself will hold a lock on a directory preventing it from being deleted. Once it has exhausted RAM, Windows will begin paging things out as fast as possible. Once the pagefile is full, the system will grind to a halt.

In my experience, this occurs whenever I try to delete a large number of files and directories recursively within the purview of CMake's filesystem watches (basically the source directory and everything below it).

Unfortunately, there isn't anything that CMake Tools is "doing wrong" to trigger this, and there is no way to tell CMake to _not_ watch the filesystem. The goals of CMake Server were never fully realized, and it was never widely used (CMake Tools is the only client that actually keeps a persistent connection open, AFAIK), and the result is that a lot of these kinds of bugs simply go unnoticed by the CMake developers.

**Comment by eugeneko** [comment]
I can confirm it happens even for the latest version of CMake.
Fortunatelly, I've found a way to spot this defect before it destroys my system.

All occurrences of this bug have same scenario for me:

1) Add new CMake subdirectory in existing CMake project.
2) Configure CMake from VSCode so it starts observing this new CMakeLists.txt and related files.
3) Do git rebase or change branges or whatever, so this new subdirectory gets deleted and recreated.
4) CMake server starts eating.

In this case git fails to rebase due to locked files, and that's how I spot the bug in time to kill `cmake.exe`.

Maybe VSCode cmake tools can e.g. monitor `cmake.exe` and kill it in case of abnormal memory consumption?

**Comment by bobbrow** [comment]
That's a good idea.  We can have this issue track the implementation of a workaround.

**Comment by bobbrow** [comment]
Now that we have cmake-file-api(7) implemented, there is no need to use the CMake Server implementation.  Therefore, we won't be doing any additional work to support the old API.
