### ISSUE TITLE
cmake-variants.json Changes Require Deleting Build Folder

### ISSUE THREAD

**Issue by MBetters** [microsoft/vscode-cmake-tools#842]
# Brief Issue Summary

Changes to `cmake-variants.json`'s `settings` object aren't picked up in subsequent builds.

### Expected:

1. Make change to any `settings` object in `.vscode/cmake-variants.json`
2. Perform any action (Configure, Clean Reconfigure, etc.)
3. The change you made should be reflected in the build.

### Apparent Behavior:

1. Make change to any `settings` object in `.vscode/cmake-variants.json`
2. Perform any CMake Tools action (`Configure`, `Clean Reconfigure`, etc.)
3. The change does not reflect itself in the configure/build. For example, if I change one of the arguments in my `release` variant's `settings` from `ON` to `OFF` and use a `message(...)` call in my `CMakeLists.txt` to log the value of that setting, it still says `ON` even though I changed it to be `OFF`. To make it fully switch to `OFF`, I have to delete the `build` folder before running any CMake Tools actions (`Configure`, `Clean Reconfigure`, etc.).

### Platform and Versions

- **Operating System**: Windows
- **CMake Version**: 3.16.0-rc1
- **VSCode Version**: 1.40.0-insider
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: Visual C++ 2017, Visual Studio 15 2017 Win64

### Other Notes/Information

Maybe I have a misconception about what `cmake-variants.json` is supposed to do. I feel like it should update subsequent `Configure` / `Clean Reconfigure` / etc. without requiring deleting the build folder, but maybe I'm misunderstanding something.

If someone actually picks this up, I'll add the Developer Tools logs if they need them.

**Comment by bobbrow** [comment]
I think a full review on extension state needs to be done.  There are various settings that affect the configure/build steps and I'm not seeing them take effect immediately as one would expect.  The workaround is generally to run the `Reload Window` command, but that's far from ideal.  Do you still need to delete the `build` folder if you make a change to the variants and then reload the window?

**Comment by MBetters** [comment]
Yes, calling `Reload Window` will cause `cmake-kits.json` changes to work for subsequent `Configure` calls.

**Comment by MBetters** [comment]
It sounds like what this extension needs to do (and isn't doing) is to update the Variants state whenever `cmake-kits.json` has been changed.

**Comment by bobbrow** [comment]
Yep. That's what I was hinting at in my comment. :)

**Comment by krister-ts** [comment]
Still an issue in v1.17.15 where changing CMakelists.txt or selecting another variant requires build folder deletion.
