### ISSUE TITLE
Problems with std::cin

### ISSUE THREAD

**Issue by nag11nag** [microsoft/vscode-cmake-tools#848]
### Brief Issue Summary

Unable to use CIN for console input

### Expected:

Using the following c_cpp_properties.json

[c_cpp_properties.txt](https://github.com/microsoft/vscode-cmake-tools/files/3776430/c_cpp_properties.txt)

This code hangs at the CIN in the VSC debug console.

```cpp
			std::cout << "Please select..." << std::endl;
			std::cout << "\t1. Encrypt" << std::endl;
			std::cout << "\t2. Decrypt" << std::endl;
			std::cout << "\t?. Quit" << std::endl;
			std::cout << "> ";
			std::getline(std::cin, option);

			std::cout << "You entered: " << option << std::endl;
```

### Apparent Behavior:

The above code hangs in the VSC debug console.
But when running from the VS Command prompt, the code works as expected (the CIN works)

### CMake Tools Log

The Debug Console generates...
```
-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded 'D:\Users\micro\Desktop\workspace\ITP365\itp365_20201_hw01\build\main.exe'. Symbols loaded.
Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\apphelp.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\msvcp140d.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\vcruntime140d.dll'. Cannot find or open the PDB file.
Loaded 'C:\Windows\System32\ucrtbased.dll'. Cannot find or open the PDB file.
The thread 22860 has exited with code 0 (0x0).
Please select...
	1. Encrypt
	2. Decrypt
	?. Quit
1
2
```

### Platform and Versions

- **Operating System**: Windows 10 (1903)
- **CMake Version**: 3.15.2
- **VSCode Version**: 1.39.2
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: MS Visual C++

**Comment by bobbrow** [comment]
This is a bug with vscode itself.  I was pretty sure there was an issue open for this in the vscode repo, but I can't seem to find it to figure out the status.

**Comment by nag11nag** [comment]
Is it worth pushing the issue up to the VSCode team?

**Comment by bobbrow** [comment]
I would think so.  They will close the issue as a duplicate, but at least we'll be able to find the duplicate issue and see the status at that point. 😃

**Comment by realivanjx** [comment]
https://github.com/microsoft/vscode/issues/83477

**Comment by bobbrow** [comment]
Unfortunately that bug appears to have been incorrectly triaged.  If you are able to get it to work with the following setting, then this is definitely their bug:

```
    "cmake.debugConfig": {
        "externalConsole": true
    }
```

Just note, you won't be able to type directly into the VS Code debug window.  You have to type into the console window that appears.

**Comment by realivanjx** [comment]
Yes it works after i set to use external console. I put the settings inside `launch.json` instead.

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cl.exe - Build and debug active file",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true,
            "preLaunchTask": "cl.exe build active file"
        }
    ]
}
```

**Comment by ExtSolTech** [comment]
I have some issue on Windows version of VS Code. Not helped "externalConsole": true flag for me.
Cin step out, leave empty the varialable, cin cant break my running application. Cout not show any output.
Same code is working fine on Ubuntu. Both Cin and Cout.
![image](https://user-images.githubusercontent.com/44647576/145305570-f544a743-e594-4cda-8723-220453d0438d.png)
![image](https://user-images.githubusercontent.com/44647576/145305649-617371dc-974b-460d-a5e5-9af2f2152e82.png)
