### ISSUE TITLE
ANSI escape codes not displaying correctly in build output

### ISSUE THREAD

**Issue by steve-lorimer** [microsoft/vscode-cmake-tools#851]
### Brief Issue Summary

ANSI escape codes not displaying correctly

### Expected:

Colorized output in the `CMake/Build` output log

Example of running cmake in a terminal window:

![image](https://user-images.githubusercontent.com/6157939/67814136-4e18b000-fa71-11e9-9c49-8d8d71604fd9.png)

### Apparent Behavior:

[cmake] [1;34mFound library /usr/lib/gcc/x86_64-linux-gnu/7/libquadmath.so[m
[cmake] [31mseagull_test.test will not run through valgrind[m
[cmake] [1;35mgoogle benchmark not detected[m
[cmake] [1;35mwill not build mmap_benchmark, missing dependency benchmark[m
[cmake] [1;34mFound library /usr/lib/x86_64-linux-gnu/libcurl.so[m
[cmake] [1;35mwill not build zoolander database helpers, missing dependency postgres[m
[cmake] [1;35mwill not build kafka, missing dependency rdkafka++[m
[cmake] Configuring done
[cmake] Generating done

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.39.2
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: gcc-7.4

**Comment by bobbrow** [comment]
I'm pretty sure vscode doesn't support colors in the output window.  I was thinking that they should be trimming out escape characters though.  We'll need to ask them.

**Comment by jorisvanemden** [comment]
> I'm pretty sure vscode doesn't support colors in the output window. I was thinking that they should be trimming out escape characters though. We'll need to ask them.

vscode can display color in output:
![image](https://user-images.githubusercontent.com/35329465/108067718-7ad74900-7061-11eb-8779-741a369dedcc.png)

It would be very nice to get the color in the output. Maybe you need to add "-fdiagnostics-color=always" to your CMAKE_CXX_FLAGS to see some useful color.

**Comment by andreeis** [comment]
Your snippet shows the terminal window, not the output window. Were you referring to that? We don't think VSCode supports colors in the output tab (in your snippet, 2 tabs to the left from terminal). If you find such a case please share a new image with colors in the output tab.
Thanks for the fdiagnosics-color tip, we will experiment with it and see where we get.

**Comment by wkonkel** [comment]
This extension has colors in the OUTPUT tab:

https://github.com/IBM-Cloud/vscode-log-output-colorizer

**Comment by Timmmm** [comment]
As of CMake 3.24 you can now set [`-DCMAKE_COLOR_DIAGNOSTICS=TRUE`](https://cmake.org/cmake/help/latest/variable/CMAKE_COLOR_DIAGNOSTICS.html). However you are correct, the `OUTPUT` pane doesn't support colour.

Bit of a shame because the problems matcher doesn't really work properly either (it shows problems from random files that you have open, rather than from the build you just did).

**Comment by Timmmm** [comment]
Actually I discovered a weird workaround.

If you press this button to do the build then the output goes to the `OUTPUT` pane, and you get broken ANSI sequences.

![image](https://user-images.githubusercontent.com/376842/218701593-d75e895c-f252-406a-88e3-bf819def7612.png)

However if you use Ctrl-Shift-B, then it builds in a terminal and the colours work??! I don't think I have anything special in my `tasks.json`:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "cmake",
			"label": "CMake: build",
			"command": "build",
			"targets": [
				"all"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": [],
			"detail": "CMake buildf",
			"presentation": {
				"echo": true,
				"revealProblems": "onProblem",
				"focus": false,
				"panel": "shared",
				"showReuseMessage": false,
				"clear": true
			}
		}
	]
}
```

**Comment by Timmmm** [comment]
Also the problem matcher works more sensibly that way (if you change `problemMatcher` to include `$gcc`.

**Comment by gcampbell-msft** [comment]
Closing in favor of tracking this request here: #478

**Comment by moefear85** [comment]
[salvation](https://github.com/microsoft/vscode-cmake-tools/issues/2783#issuecomment-1841819111)
