### ISSUE TITLE
cmake.configureSettings don't work with boolean values

### ISSUE THREAD

**Issue by senyai** [microsoft/vscode-cmake-tools#856]
Let's say I have `MY_VALUE` option:
`"cmake.configureSettings": {"MY_VALUE": true}`
'true' or 'false' values aren't working for me, but '"ON"' and '"OFF"' do.

cmake tools 1.1.3, vscode 1.39.2

**Comment by bobbrow** [comment]
This works for me.  Can you provide any additional information that might help us diagnose this?

#### settings.json
```
{
    "cmake.configureSettings": {
        "MyOption": true
    }
}
```

#### CMakeLists.txt
```
project(foo)
add_executable(foo src/1.cpp)

option(MyOption "test booleans" OFF)
message(STATUS "MyOption is ${MyOption}")
```

#### Output
```
[cmake] MyOption is TRUE
[cmake] Configuring done
[cmake] Generating done
```

**Comment by senyai** [comment]
Thank you @bobbrow, you example is working for me. And I see the option is working in my project too. I really tested this before posting the issue. Not sure what has changed. Closing the issue.
