### ISSUE TITLE
Duplicated launch targets

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#863]
Maybe this is fixed already but I am unable to find such issue.
Whenever I need to select a launch target I see duplicated entries:

![Screenshot from 2019-11-01 13-41-51](https://user-images.githubusercontent.com/3337419/68022823-16e31280-fcae-11e9-8d3b-06c1da08f62f.png)

Maybe whenever there is just one target in the project it should be selected by default and no select popup menu should be displayed.

**Comment by Zingam** [comment]
I can still see the duplicated entries in 1.2.1.

**Comment by KoeMai** [comment]
I tried to [reconstruct ](https://github.com/KoeMai/vscode-cmake-tools/commit/d18925d3c07b28d8338a4447044858602d616972) the dublicate entries. But I don´t see it. Are this duplicate launch configurations or execution targets? When is the dialog shown? How does the launch configuration looks like? And which tool versions are used?

**Comment by Zingam** [comment]
When I click on "Debug" on the status bar. I have been observing this for a while now with this project of mine:
https://github.com/Zingam/GunBox
I tried to quickly debug it but couldn't get any idea what was going on. The above screenshot was made on Ubuntu. Here a a couple of screenshot on Windows.

Here I clicked: [all]  "Set the active target to build" on the status bar.

![Untitled](https://user-images.githubusercontent.com/3337419/69029201-f53b9800-09dc-11ea-83f1-95bb875bc64d.png)


Here I clicked: [Debug] "Select target to launch" on the status bar.

![Untitled2](https://user-images.githubusercontent.com/3337419/69029226-02588700-09dd-11ea-9a07-11ce5619c94e.png)

**Comment by KoeMai** [comment]
The project contains to executable targets from different projects (see cmake: project outline). 
May be it is helps to add the project into the target description.

![twoExecuableTargets](https://user-images.githubusercontent.com/21360085/69124841-df91a580-0aa4-11ea-858e-7c902a79ad88.PNG)

**Comment by Zingam** [comment]
@KoeMai This is puzzling. I have just one add_executable in the source. Also that other library ThirdParty/glad also appears twice.
I use Visual Studio 2019 mostly and I don't observe that kind of duplicated executable targets there.

![image](https://user-images.githubusercontent.com/3337419/69191847-ffb87780-0b2b-11ea-8ff5-2a733fe51719.png)

**Comment by Zingam** [comment]
These are the debug targets as seen in VS2019 and exactly as expected:

![image](https://user-images.githubusercontent.com/3337419/69192123-9d13ab80-0b2c-11ea-8ab1-dd4b131986a7.png)

**Comment by Zingam** [comment]
The duplication of targets in the outline happens because I have multiple `project` commands in my `CMakeLists.txt`-s. When I removed all `project` commands but the one in the root `CMakeLists.txt` the Project outline started to look good.

The structure was:

- `project` 1 in the root `CMakeLists.txt` adds `project` 2's and project 3's `CMakeLists.txt`
   - `project` 2 in `sub-`CMakeLists.txt` (contains a library target) adds `project` 4's `CMakeLists.txt` 
   -   `project` 3 in sub-`CMakeLists.txt` (contains an executable target)
   -  `project` 4 in sub-`CMakeLists.txt` (contains a library target)

I don't think that my `CMakeLists.txt` are wrong. I would blame the way the tree is constructed.

**Comment by Zingam** [comment]
The CMake server returns a list of `project`s:
https://cmake.org/cmake/help/v3.16/manual/cmake-server.7.html#type-codemodel
https://cmake.org/cmake/help/v3.16/manual/cmake-file-api.7.html#object-kind-codemodel
And the extension just puts them into the Outliner:
```TypeScript
updateCodeModel(model: cms.CodeModelContent|null, exCtx: {launchTargetName: string|null, defaultTargetName: string}) {
    if (!model || model.configurations.length < 1) {
      return;
    }
    this._codeModel = model;
    const config = model.configurations[0];
    const updates: BaseNode[] = [];
    const new_children: BaseNode[] = [];
    for (const pr of config.projects) {
      const item = new ProjectNode(pr.name);
      item.update(pr, {...exCtx, nodesToUpdate: updates});
      new_children.push(item);
    }
    this._children = new_children;

    this._changeEvent.fire(null);
    for (const node of updates) {
      this._changeEvent.fire(node);
    }
  }
```
I cannot see a reason why the extension should iterate over all projects and their sub-projects. I think it should just use the top-level project (or too-level projects when the extension starts supporting multiple top-level projects).

**Comment by Zingam** [comment]
A simple sample project:

[CMakeMultiProject.zip](https://github.com/microsoft/vscode-cmake-tools/files/3964267/CMakeMultiProject.zip)

**Comment by bobbrow** [comment]
Thanks for the example.  I created a PR for this.

**Comment by bobbrow** [comment]
Ha, I spoke too soon.  I only fixed the build selector.  I need to fix the launch one too.
