### ISSUE TITLE
Can't find gcc: No active kit, on mac Catalina.

### ISSUE THREAD

**Issue by ezorzin** [microsoft/vscode-cmake-tools#865]
Issue Type: <b>Bug</b>

1. Open a c++ project.
2. select a kit (click [No actvie kit]).
3. VSCode can't find any kit, but gcc 9 is present.

Extension version: 1.1.3
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bobbrow** [comment]
What is the path to gcc on your mac?

**Comment by bobbrow** [comment]
If you add `gcc` to your $PATH, the extension should find it.  Otherwise, if you are suggesting another directory for us to search, please let us know.

**Comment by bobbrow** [comment]
We're closing this issue as we do not have enough information to investigate it.

**Comment by bobbrow** [comment]
(you may also want to try the "scan for kits" command)
