### ISSUE TITLE
Can't package with nodejs 12.13.0

### ISSUE THREAD

**Issue by barcharcraz** [microsoft/vscode-cmake-tools#866]
### Brief Issue Summary

Node moved their LTS to 12.13.0 recently and I can't get `vsce package` to run for
vscode-cmake-tools anymore

### Expected:
1. run `yarn`
2. run `npm install -g vsce`
3. run `vsce package`
4. get a visx package

### Apparent Behavior:
1. `yarn` -- runs OK
2. `npm install -g vsce` -- runs OK
3. `vsce package`
```
Executing prepublish script 'npm run vscode:prepublish'...
 ERROR  Command failed: npm run vscode:prepublish
warning cmake-tools@1.2.0: The engine "vscode" appears to be invalid.
Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1476
error Command failed with exit code 3221226505.
npm ERR! code ELIFECYCLE
npm ERR! errno 3221226505
npm ERR! cmake-tools@1.2.0 vscode:prepublish: `yarn run compile-production`
npm ERR! Exit status 3221226505
npm ERR!
npm ERR! Failed at the cmake-tools@1.2.0 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chbarto\AppData\Roaming\npm-cache\_logs\2019-11-01T23_17_44_312Z-debug.log
```

It looks like this error is in libuv someplace. Looking at libuv `src/win/util.c` I see MAX_ENV_VAR_LENGTH is 32767. My largest env var is ~2000 bytes (It's PATH).
### Platform and Versions

- **Operating System**: Microsoft Windows 10 Enterprise (x64) Build 19013.1
- **CMake Tools Extension Version**: master
- **nodejs version**: v12.13.0
- **vsce version**: 1.69.0
- **yarn version**: 1.19.1

**Comment by barcharcraz** [comment]
interestingly if I go into package.json and change yarn to npm in it's `"scripts"` section things work

**Comment by arungk981** [comment]
did anyone find a solution for this?
This is the error Jenkins throws while running a build
" npm run ng build --prod  
Assertion failed: len < MAX_ENV_VAR_LENGTH, file c:\ws\deps\uv\src\win\util.c, line 1478 "

**Comment by bobbrow** [comment]
I created a libuv issue for this: https://github.com/libuv/libuv/issues/2587

**Comment by bobbrow** [comment]
Actually, it's a yarn issue: https://github.com/yarnpkg/yarn/issues/7783

Another way to work around it is to delete the contents of NOTICE.txt.

**Comment by bobbrow** [comment]
This appears to be fixed with latest tools.  Node 12.18.4 works.
