### ISSUE TITLE
workspaceFolderBasename not resolved

### ISSUE THREAD

**Issue by rhaschke** [microsoft/vscode-cmake-tools#869]
The variable `${workspaceFolderBasename}` [officially listed here](https://code.visualstudio.com/docs/editor/variables-reference) is not resolved in `cmake.buildDirectory`, but yields: 
`Invalid variable reference ${workspaceFolderBasename} in string`.

If `cmake.buildDirectory` is empty, cmake configure fails as well (obviously).
It would be great if the user would be prompted for a `buildDirectory` in this case.

**Comment by bobbrow** [comment]
The variables you referenced are resolved by VS Code when you use them in `tasks.json` or `launch.json`. Extensions have to explicitly build support for them when they are used elsewhere.

`cmake.buildDirectory` defaults to `${workspaceFolder}/build` when not set. Did you set it to an invalid location, or the empty string `""`?

**Comment by rhaschke** [comment]
Indeed I tried to customize the build directory and thus changed the default value.
As I wanted to be asked for the build directory each time, I also tried the empty string in the user settings.

**Comment by Zingam** [comment]
> The variables you referenced are resolved by VS Code when you use them in `tasks.json` or `launch.json`. Extensions have to explicitly build support for them when they are used elsewhere.

@bobbrow Do you have any tips how can this be implemented?

**Comment by bobbrow** [comment]
In cpptools we treat them as additional environment variables and pass them into the [resolver](https://github.com/microsoft/vscode-cpptools/blob/6f7689811090863f3ae3f9ad85e28fee86aaa251/Extension/src/common.ts#L305) as such.  I haven't looked to see how CMake Tools does this yet.

**Comment by bobbrow** [comment]
This was fixed in 1.3.0
