### ISSUE TITLE
can't detect gcc 9.2.0 on linux with non-English output

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vscode-cmake-tools#870]
$gcc --version
gcc (GCC) 9.2.0
Copyright © 2019 Free Software Foundation, Inc.

CMakeTools ver:0.0.17

$cmake --version
cmake version 3.16.0-rc3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

log:
[Extension Host] [CMakeTools] 2019-11-03T19:46:26.486Z [debug] [extension] [2484] cmake.scanForKits started
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.487Z [debug] [extension] Rescanning for kits
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.487Z [debug] [kit] Scanning for Kits on system
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.488Z [debug] [kit] Scanning directory /usr/bin for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.488Z [debug] [kit] Skipping scan of not existing path /home/john/.local/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.488Z [debug] [kit] Found 0 kits in directory /home/john/.local/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.488Z [debug] [kit] Skipping scan of not existing path /home/john/.local/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.488Z [debug] [kit] Found 0 kits in directory /home/john/.local/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.488Z [debug] [kit] Scanning directory /bin for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.489Z [debug] [kit] Scanning directory /usr/bin/site_perl for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.489Z [debug] [kit] Scanning directory /usr/bin/vendor_perl for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.489Z [debug] [kit] Scanning directory /usr/local/sbin for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.489Z [debug] [kit] Scanning directory /usr/bin/core_perl for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.489Z [debug] [kit] Scanning directory /usr/local/bin for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.490Z [debug] [kit] Scanning directory /usr/bin/site_perl for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.490Z [debug] [kit] Scanning directory /usr/bin/vendor_perl for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.490Z [debug] [kit] Scanning directory /usr/bin/core_perl for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.491Z [debug] [kit] Scanning directory /var/lib/snapd/snap/bin for compilers
2workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.492Z [debug] [kit] Scanning directory /usr/lib/jvm/default/bin for compilers
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.492Z [debug] [kit] Found 0 kits in directory /usr/bin/site_perl
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.493Z [debug] [kit] Found 0 kits in directory /usr/bin/vendor_perl
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.493Z [debug] [kit] Found 0 kits in directory /usr/bin/core_perl
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.494Z [debug] [kit] Found 0 kits in directory /usr/local/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.494Z [debug] [kit] Found 0 kits in directory /usr/bin/site_perl
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.494Z [debug] [kit] Found 0 kits in directory /usr/bin/vendor_perl
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.495Z [debug] [kit] Found 0 kits in directory /usr/bin/core_perl
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.495Z [debug] [kit] Found 0 kits in directory /usr/local/sbin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.496Z [debug] [kit] Found 0 kits in directory /var/lib/snapd/snap/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.497Z [debug] [kit] Found 0 kits in directory /usr/lib/jvm/default/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.498Z [debug] [kit] Found 0 kits in directory /usr/lib/jvm/default/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.526Z [debug] [kit] Testing GCC-ish binary: /bin/gcc
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.596Z [debug] [kit] Testing GCC-ish binary: /bin/x86_64-pc-linux-gnu-gcc
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.602Z [debug] [kit] Testing GCC-ish binary: /bin/x86_64-pc-linux-gnu-gcc-9.2.0
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.636Z [debug] [kit] Testing GCC-ish binary: /usr/bin/gcc
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.692Z [debug] [kit] Testing GCC-ish binary: /usr/bin/x86_64-pc-linux-gnu-gcc
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.703Z [debug] [kit] Testing GCC-ish binary: /usr/bin/x86_64-pc-linux-gnu-gcc-9.2.0
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.751Z [debug] [kit] Bad GCC binary /usr/bin/x86_64-pc-linux-gnu-gcc-9.2.0 -v output: 使用内建 specs。
COLLECT_GCC=/usr/bin/x86_64-pc-linux-gnu-gcc-9.2.0
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
线程模型：posix
gcc 版本 9.2.0 (GCC) 

workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.752Z [debug] [kit] Bad GCC binary /usr/bin/x86_64-pc-linux-gnu-gcc -v output: 使用内建 specs。
COLLECT_GCC=/usr/bin/x86_64-pc-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
线程模型：posix
gcc 版本 9.2.0 (GCC) 

workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.752Z [debug] [kit] Bad GCC binary /usr/bin/gcc -v output: 使用内建 specs。
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
线程模型：posix
gcc 版本 9.2.0 (GCC) 

workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.752Z [debug] [kit] Found 0 kits in directory /usr/bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.752Z [debug] [kit] Bad GCC binary /bin/x86_64-pc-linux-gnu-gcc-9.2.0 -v output: 使用内建 specs。
COLLECT_GCC=/bin/x86_64-pc-linux-gnu-gcc-9.2.0
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
线程模型：posix
gcc 版本 9.2.0 (GCC) 

workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.752Z [debug] [kit] Bad GCC binary /bin/x86_64-pc-linux-gnu-gcc -v output: 使用内建 specs。
COLLECT_GCC=/bin/x86_64-pc-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
线程模型：posix
gcc 版本 9.2.0 (GCC) 

workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.753Z [debug] [kit] Bad GCC binary /bin/gcc -v output: 使用内建 specs。
COLLECT_GCC=/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
线程模型：posix
gcc 版本 9.2.0 (GCC) 

workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.753Z [debug] [kit] Found 0 kits in directory /bin
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.753Z [debug] [rollbar] Updated Rollbar payload {"kit":{"name":"__unspec__"}}
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.753Z [debug] [main] Injecting new Kit into CMake driver
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.753Z [info] [driver] Switching to kit: __unspec__
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.769Z [debug] [driver] CMakeDriver Kit set to __unspec__
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:26.780Z [debug] [cms-client] Started new CMake Server instance with PID 13300
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:27.783Z [debug] [cache] Reading CMake cache file /home/john/文档/project/test/build/CMakeCache.txt
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:27.785Z [debug] [cache] Parsing CMake cache string
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:27.797Z [debug] [extension] Saving kits to /home/john/.local/share/CMakeTools/cmake-tools-kits.json
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:27.797Z [debug] [extension] Saving new kits to /home/john/.local/share/CMakeTools/cmake-tools-kits.json
workbench.desktop.main.js:sourcemap:243 [Extension Host] [CMakeTools] 2019-11-03T19:46:27.800Z [debug] [extension] [2484] cmake.scanForKits finished (returned undefined)

**Comment by senyai** [comment]
#825

**Comment by bobbrow** [comment]
It seems the issue is related to gcc printing out non-English characters.  We've had a lot of trouble reproducing this behavior in house and therefore have been unable to put together a reliable fix.

**Comment by xspeed1989** [comment]
> It seems the issue is related to gcc printing out non-English characters. We've had a lot of trouble reproducing this behavior in house and therefore have been unable to put together a reliable fix.

mybe it is

c/c++ extesion has the same problem!

**Comment by ChristianS99** [comment]
Invoking gcc with LANG="" environment variable could fix this until it can be properly fixed.

At least startting code with empty LANG works around this.

**Comment by bobbrow** [comment]
@ChristianS99 how did you set up your work environment prior to this?  We still haven't been able to get a repro for this language issue.  I tried setting all the env variables like LANG, etc but gcc still prints English messages for me.  I'm trying to add Spanish as a language to my Ubuntu installation, but it doesn't seem to be working.

**Comment by ChristianS99** [comment]
I did nothing special, I'm on Gentoo Linux and have nls (native language support) enabled.
with this, a few mo-files get installed and used.
Maybe Ubuntu doesn't install translations for gcc (on purpose?).
The translation files I have are cpplib.mo, gcc.mo, libstdc++.mo. Maybe you can search if you find them, but I would guess that Ubuntu omits them.

can you check your gcc -v output for [enable|disable]-nls? If it is enabled, and just the language files aren't installed, it should be enough, to get the files (I could provide them maybe) to the right place.
If it is disabled at all, you could compile gcc yourself (and enable nls) or use a different distribution that has gcc with nls

**Comment by flying-sheep** [comment]
When compiling, I get

```
[rollbar] Ausnahmefehler: Unbehandelte Promise-Ablehnung: build Error: Unknown diagnostic severity level: Warnung {}
```

“Warnung” is German for “Warning”.

You really should invoke gcc with LANG set to some defined value.

**Comment by listenerri** [comment]
any progress on this?

**Comment by skoehler** [comment]
Seeing the same error message over and over again:
````
[rollbar] Ausnahmefehler: Unbehandelte Promise-Ablehnung: build Error: Unknown diagnostic severity level: Warnung {}
````

I don't understand why this is such a big issue. On German systems, programs prints German messages. On Spanish systems, programs print Spanish messages, etc. - Why wasn't this anticipated a long time ago?

Until you have finished supporting all languages, would you please be so kind and call `cmake` and `gcc` with `LANG=C` on systems with languages that you do not support? There is also the `LC_*` family of variables that you will need to control. This is just the easiest way to deliver something to an international audience.

**Comment by flying-sheep** [comment]
> Until you have finished supporting all languages

You misunderstood the issue. When parsing output, one doesn’t need to support more than one language, because you’re treating the output as machine-readable message, not one for human consumption. Therefore `LANG=C` is the correct thing to do forever: You tell the software to give you the message it displays in the source code, which hopefully shouldn’t change.
