### ISSUE TITLE
WSL: Building via buttons/shortcuts not properly supported throughout the UI

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cmake-tools#876]
First I'd like to acknowledge that I am not quite sure if this is Cpp Tools issue or CMake Tools one.

I installed WSL, the Ubuntu 18.04 image from Windows Store, I installed the latest test GNU toolchain from a ppa, which I suppose is 9.2.1.
I created a test CMake project and enabled C++20 and C++ Concepts via the compiler switch `-fconcepts`. My goal was to test the Concepts support in the GNU 9 compiler.

Then I started VS Code and opened the CMake folder in the Ubuntu WSL image. I was able to compile and run the project. If I use the build button from the CMake menu that is added by the extension the compilation is successful.
If I try to build the project by clicking any other button outside of this menu I get an error that concepts require the `-fconcepts` switch.
So I suppose that the CMake configuration is not properly outside of the CMake menu by any other UI elements which I guess are added by the Cpp Tools extension.

I use version 1.1.3 of the extension still. I'll retest it whenever the extension is auto-updated. I have not noticed any commits related to this issue yet included in version 1.2.

[Concepts.zip](https://github.com/microsoft/vscode-cmake-tools/files/3818864/Concepts.zip)

**Comment by bobbrow** [comment]
Can you clarify where else you are trying to build this? I tried the Build button and the project outline and they both work fine.  The CMake Build command also works.

**Comment by bobbrow** [comment]
And just to double-check, are you using the Remote-WSL extension?
