### ISSUE TITLE
Invalidate the CMake cache after updating the extension

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#879]
Maybe the extension should invalidate the cache and reconfugure the project cleanly after the extension was updated?
I run into an issue of something not able to recognize the correct compiler path (MSVC).

**Comment by bobbrow** [comment]
An extension update shouldn't invalidate your cache.  The extension just invokes your tools.  A CMake or compiler upgrade should though.

**Comment by Zingam** [comment]
Actually VS2019 got an update today. Maybe that was the reason. I don't remember in what order I started VS Code vs VS2019.
In any case I had to select the option "Clean Reconfugure" to get my sample running.
