### ISSUE TITLE
Should use ${SystemRoot} ${ProgramFiles} ${SystemDrive} instead of "C:\\Windows" "C:\\Program Files" "C:".

### ISSUE THREAD

**Issue by szzhiyang** [microsoft/vscode-cmake-tools#883]
Not every Windows PC uses `C` as system drive letter. Please replace `C:\\Windows` `C:\\Program Files` `C:\\Program Files (x86)` `C:` to `${SystemRoot}` `${ProgramFiles}` `${ProgramFiles(x86)}` `${SystemDrive}`, thanks.

**Comment by szzhiyang** [comment]
Hi @bobbrow, the source files shown in the following screenshot hardcode `C:\\` as Windows system drive, which may bring inconvenience to the users whose Windows system drive is not `C:\\`. They should use `${SystemRoot}` `${ProgramFiles}` `${ProgramFiles(x86)}` `${SystemDrive}` instead.

![image](https://user-images.githubusercontent.com/30952626/68495228-b7c36600-028a-11ea-9877-ffc599a54167.png)

**Comment by bobbrow** [comment]
Yes, we should fix this.

**Comment by Zingam** [comment]
@bobbrow Is it necessary to add these variables to the extension:  `${SystemRoot} ${ProgramFiles} ${ProgramFiles(x86)} ${SystemDrive}` or should I just use `process.env` to get the system paths as necessary?

**Comment by bobbrow** [comment]
Sorry that I was unclear on this one.  I wasn't planning on adding new variables for this.  I was agreeing that we should get them from the environment.

**Comment by Zingam** [comment]
@bobbrow I'll submit a PR to fix this issue later.

**Comment by Zingam** [comment]
@andreeis Didn't you merge the fix for this?

**Comment by bobbrow** [comment]
Yes, this was fixed. The replacement PR didn't link back to this issue.  @andreeis can you make sure this was added to the CHANGELOG?

**Comment by andreeis** [comment]
Yes, it's mentioned:
- Use variables instead of hardcoded values for system path references. [PR #1690](https://github.com/microsoft/vscode-cmake-tools/pull/1690)

**Comment by bobbrow** [comment]
Cool.  Looks like we can put the issue number in there instead of the PR now.

**Comment by andreeis** [comment]
Yes definitely, will do with my next PR.

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.
