### ISSUE TITLE
Can't choose MSYS Generator after update

### ISSUE THREAD

**Issue by xubury** [microsoft/vscode-cmake-tools#885]
Hi, I have this issue that I can't use MSYS Makefiles after an update. I am using MSYS2+mingw64 and I have to use MSYS Makefiles to configure normally.So I set "cmake.generator" to "MSYS Makefiles", but it keep switching to Mingw Makefiles for some reason. See the screenshot below.
Really appreciate any help, Thanks!
![20191108162136](https://user-images.githubusercontent.com/46261364/68461381-1534c400-0245-11ea-9bc8-0e9ff87f1b2c.png)

**Comment by xubury** [comment]
So I thought editing cmake-tools-kits.json would work, but after setting generator variable to MSYS makefiles it switch to Unix Makefiles.
Manually using `cmake -G  "MSYS Makefiles"` works which means my cmake should be able to work with MSYS Makefiles.
![20191108164643](https://user-images.githubusercontent.com/46261364/68462417-73fb3d00-0247-11ea-8ab6-bf6189fa65e4.png)
![20191108164713](https://user-images.githubusercontent.com/46261364/68462591-cb011200-0247-11ea-97d8-e579967a2e0a.png)

**Comment by xubury** [comment]
This problem may be related to #880 
If I don't use the mingw64 shell, i got the same error.
![20191108204428](https://user-images.githubusercontent.com/46261364/68477821-5a6aed00-0269-11ea-8b7a-7dfbc099aa35.png)

**Comment by bobbrow** [comment]
1.2.2 was released today.  Please give that a try and let us know if you continue to have issues.
