### ISSUE TITLE
 The "path" argument must be of type string - issue after update 1.2.1

### ISSUE THREAD

**Issue by paulelsner** [microsoft/vscode-cmake-tools#886]
### Brief Issue Summary
Hi, after the update today I get the following issue:

 ```[kit] Successfully loaded 5 kits from /home/xx/repos/xxx/.vscode/cmake-kits.json
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined {"folder":{"uri":{"$mid":1,"fsPath":"/home/xx/repos/xxx","external":"file:///home/xx/repos/xxx","path":"/home/xx/repos/xxx","scheme":"file"},"name":"xxx","index":0}}
[rollbar] Unhandled exception: Unhandled Promise rejection: build TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined {}
```
I cannot configure and cannot build anymore :(
### Platform and Versions

- **Operating System**: remote on Ubuntu with Windows as host
- **CMake Version**: 3.15.1
- **VSCode Version**: 1.40.0
- **CMake Tools Extension Version**: 1.2.1
- **Compiler/Toolchain**: Clang 7

**Comment by paulelsner** [comment]
Furhter testing shows that it is not connected to the vscode update 1.40.0 but the the extension update. And the issue happens on Mac as well on Linux. Windows works fine.

I found a workaround:
open `/home/xx/.vscode/extensions/ms-vscode.cmake-tools-1.2.1/dist/main.js`

and remove all lines from the function `getVSInstallForKit`

You do not need to search for VisualStudio installations on Linux anyhow ;)

**Comment by bobbrow** [comment]
That function won't be called on linux unless there is a Visual Studio Kit in your cmake-kits.json.  Is that the case?  Do you have Visual Studio Kits committed to your repo?  Can you share your Kits file(s)?

**Comment by paulelsner** [comment]
Yes there are Kits for Windows, Linux and Mac defined, since we do cross platform development.

This is my shortend Kit file
```[
    {
        "name": "My Clang 7 C++17",
        "compilers": {
            "C": "/usr/bin/clang-7",
            "CXX": "/usr/bin/clang++-7"
        },
        "cmakeSettings": {
            "CMAKE_CXX_STANDARD": "17",
            "CMAKE_CXX_STANDARD_REQUIRED": "ON",
            "CMAKE_CXX_EXTENSIONS": "OFF",
            "CMAKE_POSITION_INDEPENDENT_CODE": "ON"
        }
    },
    {
        "name": "My AppleClang C++14",
        "compilers": {
            "C": "/usr/bin/clang",
            "CXX": "/usr/bin/clang++"
        },
        "cmakeSettings": {
            "CMAKE_CXX_STANDARD": "14",
            "CMAKE_CXX_STANDARD_REQUIRED": "ON",
            "CMAKE_CXX_EXTENSIONS": "OFF",
            "CMAKE_POSITION_INDEPENDENT_CODE": "ON"
        }
    },
    {
        "name": "My Visual Studio 2017 (x86)",
        "visualStudio": "VisualStudio.15.0",
        "visualStudioArchitecture": "amd64_x86",
        "preferredGenerator": {
            "name": "Visual Studio 15 2017"
        }
    }
]
```

**Comment by bobbrow** [comment]
Thanks. That was unexpected.  We'll get a fix in for this.

**Comment by paulelsner** [comment]
Thanks!

**Comment by Victsz** [comment]
@bobbrow Can you take a look for this https://github.com/microsoft/vscode-cpptools/issues/3731#issuecomment-552345471
After update cmake tools 1.2.1, the cpp tools cannot find the source files

**Comment by bobbrow** [comment]
1.2.2 was released today.  Please give that a try and let us know if you continue to have issues.

**Comment by paulelsner** [comment]
Work now. Thanks!
