### ISSUE TITLE
message(DEBUG "...") doesn't display in VSCode output?

### ISSUE THREAD

**Issue by thomthom** [microsoft/vscode-cmake-tools#892]
### Brief Issue Summary

While working on my projects I added some `message(DEBUG "...")` statements.  I also set `"cmake.loggingLevel": "debug"`.

### Expected:

What I expected to see was the `message` statements from `DEBUG` and above.

### Apparent Behavior:

What I do see is that there is some extra info the the VSCode Output `[driver]` messages etc. But none of the `message(DEBUG "...")` statements.

If I use `message(STATUS "...")` then I do see the messages.

Have I misinterpreted the `cmake.loggingLevel` settings? Is that not controlling the log level of CMake when it runs?

### CMake Tools Log

```
[driver] Start configure 
[driver] Runnnig pre-configure checks and steps
[driver] Run _refreshExpansions
[cms-driver] Run doRefreshExpansions
[driver] Run _refreshExpansions cb
[cmake] Configuring done
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.
[cmake] 
[cmake] 
[cmake] Generating done
[cache] Reading CMake cache file c:/Users/Thomas/SourceTree/traceup/cext/build/Release/CMakeCache.txt
[cache] Parsing CMake cache string
[extension] [1947] cmake.configure finished (returned 0)
[kit] OK running C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat amd64, env vars: undefined
```

### Platform and Versions

- **Operating System**: Windows 10
- **CMake Version**: 3.15.4
- **VSCode Version**: 1.40.0
- **CMake Tools Extension Version**: 1.2.1
- **Compiler/Toolchain**: Visual C++ 2019

**Comment by bobbrow** [comment]
Sorry, I meant to respond to this earlier, but lost track of it.  YOu shouldn't need to set cmake.loggingLevel to Debug to make this work because it is controlled by a different mechanism.

This works for me in 3.14, but it didn't work for me in 3.15.  It could be a CMake bug, but I haven't had the time to try a lot of different configurations.

**CMakeLists.txt**
```
project(foo)
add_executable(foo src/1.cpp)
message(DEBUG "debug message")
```

**Output**
```
[cmake] DEBUGdebug message
[cmake] Configuring done
[cmake] Generating done
```

**Comment by thomthom** [comment]
Gotcha. I recently upgraded to CMake 3.15 because of some good new features/improvement in that version.

So is the `message` type being mapped to VSCode's Output types?

> but it didn't work for me in 3.15. It could be a CMake bug, but I haven't had the time to try a lot of different configurations.
I didn't even try this with `cmake` directly from the terminal. After I set up CMake Tools I've exclusively done everything from VSCode. (Great extension btw!)

**Comment by CarloWood** [comment]
Add to CMakeLists.txt:

    # Use cmake --log-level=debug to get debug output.
    set( CMAKE_MESSAGE_LOG_LEVEL "STATUS" )

The latter is the default, which you can change on the command line.

**Comment by thomthom** [comment]
Can I also use `cmake.configureArgs` for this?

**Comment by thomthom** [comment]
I've tried with 

```
  "cmake.configureArgs": [
    "--log-level=DEBUG"
  ],
```

And that didn't seem to yield any `message(DEBUG ...)` messages.

```
  "cmake.buildArgs": [
     "--log-level=DEBUG"
  ],
```

This will lead to an error `[build] ninja: fatal: -l parameter not numeric: did you mean -l 0.0?`

Is there any way to control the warning level for CMake via CMakeTools that doesn't require editing `CMakeList.txt` files?

**Comment by thomthom** [comment]
Ah! After updating to CMake 3.16 the above worked as expected. Must be 3.15 being bugged.

**Comment by CarloWood** [comment]
Why are you CC-ing me?

On Mon, 23 Mar 2020 09:47:13 -0700
Thomas Thomassen <notifications@github.com> wrote:

> I've tried with 
> 
> ```
>   "cmake.configureArgs": [
>     "--log-level=DEBUG"
>   ],
> ```
> 
> And that didn't seem to yield any `message(DEBUG ...)` messages.
> 
> ```
>   "cmake.buildArgs": [
>      "--log-level=DEBUG"
>   ],
> ```
> 
> This will lead to an error `[build] ninja: fatal: -l parameter not
> numeric: did you mean -l 0.0?`
> 
> Is there any way to control the warning level for CMake via
> CMakeTools that doesn't require editing `CMakeList.txt` files?
> 



-- 
Carlo Wood <carlo@alinoe.com>

**Comment by thomthom** [comment]
I wasn't, I'm replying to the issue via GitHub. Must be the notification system from GitHub.

**Comment by bobbrow** [comment]
That's great!  I'll close the issue.
