### ISSUE TITLE
Scan for kits fails if there is a non-executable file with base name "clang-cl" in PATH

### ISSUE THREAD

**Issue by Lightirius** [microsoft/vscode-cmake-tools#895]
### Brief Issue Summary
Apparently cmake-tools extension tries to execute any file with base name "clang-cl" found in PATH and fails on non-executable files.

### Apparent Behavior:

1. Add any folder with "clang-cl.txt" file to PATH
2. Run cmake-tools scan for kits command
3. Scan for kits fails with:
[rollbar] Unhandled exception: Unhandled Promise rejection: scanForKits Error: spawn UNKNOWN {}

### CMake Tools Log

[extension] [9178] cmake.scanForKits started
[extension] Rescanning for kits
[kit] Scanning for Kits on system
[kit] Checking for kit: Visual Studio Build Tools�2019 Release - x86
[kit] Checking for kit: Visual Studio Build Tools�2019 Release - amd64
[kit] Checking for kit: Visual Studio Build Tools�2019 Release - x86_amd64
[kit] Checking for kit: Visual Studio Build Tools�2019 Release - x86_arm
[kit] Checking for kit: Visual Studio Build Tools�2019 Release - amd64_arm
[kit] Checking for kit: Visual Studio Build Tools�2019 Release - amd64_x86
[kit] Scanning directory C:\Windows\system32 for compilers
[kit] Scanning directory C:\Program Files (x86)\Common Files\Oracle\Java\javapath for compilers
[kit] Scanning directory C:\Windows for compilers
[kit] Scanning directory C:\Windows\System32\WindowsPowerShell\v1.0\ for compilers
[kit] Scanning directory C:\Program Files\dotnet\ for compilers
[kit] Scanning directory C:\Windows\System32\OpenSSH\ for compilers
[kit] Scanning directory C:\Windows\System32\Wbem for compilers
[kit] Scanning directory C:\Program Files\7-Zip for compilers
[kit] Scanning directory D:\apps\scoop\apps\yarn\current\Yarn\bin for compilers
[kit] Skipping scan of not existing path D:\apps\scoop\apps\yarn\current\global\node_modules\.bin
[kit] Found 0 kits in directory D:\apps\scoop\apps\yarn\current\global\node_modules\.bin
[kit] Scanning directory D:\apps\scoop\apps\python\current for compilers
[kit] Scanning directory D:\apps\scoop\apps\nodejs\current for compilers
[kit] Scanning directory D:\apps\scoop\apps\nodejs\current\bin for compilers
[kit] Scanning directory D:\apps\scoop\apps\python\current\Scripts for compilers
[kit] Scanning directory C:\Users\Lightirius\AppData\Local\Microsoft\WindowsApps for compilers
[kit] Skipping scan of not existing path 
[kit] Found 0 kits in directory 
[kit] Scanning directory D:\path for compilers
[kit] Scanning directory C:\Users\Lightirius\AppData\Local\Programs\Microsoft VS Code Insiders\bin for compilers
[kit] Skipping scan of not existing path C:\MinGW\bin
[kit] Found 0 kits in directory C:\MinGW\bin
[kit] Skipping scan of not existing path C:\Program Files (x86)\LLVM\bin
[kit] Skipping scan of not existing path C:\Program Files\LLVM\bin
[kit] Scanning directory C:\Program Files (x86)\Common Files\Oracle\Java\javapath for compilers
[kit] Scanning directory C:\Windows\system32 for compilers
[kit] Scanning directory C:\Windows for compilers
[kit] Scanning directory C:\Windows\System32\Wbem for compilers
[kit] Scanning directory C:\Windows\System32\WindowsPowerShell\v1.0\ for compilers
[kit] Scanning directory C:\Windows\System32\OpenSSH\ for compilers
[kit] Scanning directory C:\Program Files\dotnet\ for compilers
[kit] Scanning directory C:\Program Files\7-Zip for compilers
[kit] Scanning directory D:\apps\scoop\apps\yarn\current\Yarn\bin for compilers
[kit] Skipping scan of not existing path D:\apps\scoop\apps\yarn\current\global\node_modules\.bin
[kit] Scanning directory D:\apps\scoop\apps\nodejs\current\bin for compilers
[kit] Scanning directory D:\apps\scoop\apps\nodejs\current for compilers
[kit] Scanning directory D:\apps\scoop\apps\python\current for compilers
[kit] Scanning directory D:\apps\scoop\apps\python\current\Scripts for compilers
[kit] Scanning directory C:\Users\Lightirius\AppData\Local\Microsoft\WindowsApps for compilers
[kit] Scanning directory C:\Users\Lightirius\AppData\Local\Programs\Microsoft VS Code Insiders\bin for compilers
[kit] Skipping scan of not existing path 
[kit] Scanning directory D:\path for compilers
[kit] Skipping scan of not existing path C:\MinGW\bin
[kit] Found 0 kits in directory C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[kit] Found 0 kits in directory C:\Windows
[kit] Found 0 kits in directory C:\Windows\System32\WindowsPowerShell\v1.0\
[kit] Found 0 kits in directory C:\Program Files\dotnet\
[kit] Found 0 kits in directory C:\Windows\System32\OpenSSH\
[kit] Found 0 kits in directory D:\apps\scoop\apps\yarn\current\Yarn\bin
[kit] Found 0 kits in directory C:\Program Files\7-Zip
[kit] Found 0 kits in directory D:\apps\scoop\apps\python\current
[kit] Found 0 kits in directory D:\apps\scoop\apps\nodejs\current
[kit] Found 0 kits in directory D:\apps\scoop\apps\nodejs\current\bin
[kit] Found 0 kits in directory D:\apps\scoop\apps\python\current\Scripts
[kit] Found 0 kits in directory C:\Users\Lightirius\AppData\Local\Microsoft\WindowsApps
[kit] Found 0 kits in directory D:\path
[kit] Found 0 kits in directory C:\Users\Lightirius\AppData\Local\Programs\Microsoft VS Code Insiders\bin
[kit] Found 0 kits in directory C:\Windows\System32\Wbem
[kit] Testing Clang binary: D:\path\clang-cl.txt
[rollbar] Unhandled exception: Unhandled Promise rejection: scanForKits Error: spawn UNKNOWN {}
[kit] Found 0 kits in directory C:\Windows\system32
[kit] OK running C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat x86, env vars: undefined
[kit] Detected VsKit for version
[kit]  DisplayName: Visual Studio Build Tools�2019 Release - x86
[kit]  InstanceId: 92f9a1bd
[kit]  InstallVersion: 16.3.29424.173
[kit]  Selected Preferred Generator Name: undefined undefined
[kit] OK running C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat amd64, env vars: undefined
[kit] Detected VsKit for version
[kit]  DisplayName: Visual Studio Build Tools�2019 Release - amd64
[kit]  InstanceId: 92f9a1bd
[kit]  InstallVersion: 16.3.29424.173
[kit]  Selected Preferred Generator Name: undefined undefined
[kit] OK running C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat x86_arm, env vars: undefined
[kit] Detected VsKit for version
[kit]  DisplayName: Visual Studio Build Tools�2019 Release - x86_arm
[kit]  InstanceId: 92f9a1bd
[kit]  InstallVersion: 16.3.29424.173
[kit]  Selected Preferred Generator Name: undefined undefined
[kit] OK running C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat amd64_arm, env vars: undefined
[kit] Detected VsKit for version
[kit]  DisplayName: Visual Studio Build Tools�2019 Release - amd64_arm
[kit]  InstanceId: 92f9a1bd
[kit]  InstallVersion: 16.3.29424.173
[kit]  Selected Preferred Generator Name: undefined undefined
[kit] OK running C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat x86_amd64, env vars: undefined
[kit] Detected VsKit for version
[kit]  DisplayName: Visual Studio Build Tools�2019 Release - x86_amd64
[kit]  InstanceId: 92f9a1bd
[kit]  InstallVersion: 16.3.29424.173
[kit]  Selected Preferred Generator Name: undefined undefined
[kit] OK running C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat amd64_x86, env vars: undefined
[kit] Detected VsKit for version
[kit]  DisplayName: Visual Studio Build Tools�2019 Release - amd64_x86
[kit]  InstanceId: 92f9a1bd
[kit]  InstallVersion: 16.3.29424.173
[kit]  Selected Preferred Generator Name: undefined undefined

### Developer Tools Log
From extension debug console:
[CMakeTools] 2019-11-10T09:59:29.747Z [fatal] [rollbar] Unhandled exception: Unhandled Promise rejection: scanForKits Error: spawn UNKNOWN {}
main.js:57398
Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:548:9)
	at Object.execute (d:\dev\projects\cmake-tools\dist\main.js:57850:22)
	at getClangVersion (d:\dev\projects\cmake-tools\dist\main.js:56456:29)
	at d:\dev\projects\cmake-tools\dist\main.js:56988:31
	at d:\dev\projects\cmake-tools\dist\main.js:56666:49
	at Array.map (<anonymous>)
	at scanDirectory (d:\dev\projects\cmake-tools\dist\main.js:56666:40)
	at async scanDirForClangCLKits (d:\dev\projects\cmake-tools\dist\main.js:56984:18)
	at async Promise.all (index 38)
	at async d:\dev\projects\cmake-tools\dist\main.js:57111:24

### Platform and Versions
- **Operating System**: Windows 10 1903
- **CMake Version**: 3.15.5
- **VSCode Version**: 1.41 Insiders
- **CMake Tools Extension Version**: 1.2.1
- **Compiler/Toolchain**: clang

**Comment by bobbrow** [comment]
1.2.2 was released today.  Please give that a try and let us know if you continue to have issues.
