### ISSUE TITLE
Headers are not found for Intellisense, despite cmake-tools being set as the Configuration Provider

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-cmake-tools#898]
After update to cmake tools 1.2.1
I change the configurationProvider accordingly
"C_Cpp.default.configurationProvider": "ms-vscode.cmake-tools",

but the intellisense engine not working
![image](https://user-images.githubusercontent.com/8154646/68592005-07916f80-04cd-11ea-9128-e339d0e1097d.png)
![image](https://user-images.githubusercontent.com/8154646/68592027-17a94f00-04cd-11ea-9a0e-6807039547ae.png)
ssh remote to centos
I tried cmake reconfigure , windows reload, reset intellisense database

**Comment by bobbrow** [comment]
The configurationProvider string has not changed yet because we need to release an update of cpptools that will support both.  For now, please don't change this manually.  We recommend you use the `C/C++: Change Configuration Provider` command to set this setting.
