### ISSUE TITLE
"Install Another Version..." gives error "Failed to install 'ms-vscode.cmake-tools'"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cmake-tools#904]
Looks like I need to manually install the vsix at https://github.com/microsoft/vscode-cmake-tools/releases/download/1.1.3/cmake-tools-1.1.3.vsix ….maybe the user could be directed to that?

**Comment by Victsz** [comment]
How to install the vsix to remote vscode server ?

**Comment by bobbrow** [comment]
The publisher id change breaks this functionality in VS Code.  This would be their issue.
