### ISSUE TITLE
CTest status bar button text appears malformed

### ISSUE THREAD

**Issue by dstodev** [microsoft/vscode-cmake-tools#911]
### Brief Issue Summary

Formatting of the text for CTest in the status bar appears malformed.

### Expected:
CTest button has text like "X tests passing".

### To reproduce:
1. Enable CTest via include(CTest)
2. Build simple program
3. Notice CTest button in the status bar appears malformed

### Apparent Behavior:
CTest button has text like "X/Y tests passing', passing, total)}"
As shown: 
![image](https://user-images.githubusercontent.com/31356674/68826113-59630280-0651-11ea-893a-98696da310c6.png)

### Platform and Versions

- **Operating System**: Windows 10 -- Version10.0.18362 Build 18362
- **CMake Version**: 3.15.4
- **VSCode Version**: 1.40.1
- **CMake Tools Extension Version**: 1.2.2
- **Compiler/Toolchain**: Visual C++ 2017

### Other Notes/Information

Issue occurs with _only_ CMake Tools enabled. A very simple repository which demonstrates this bug is here: https://github.com/dstodev/cmake-tools-ctest-bug

**Comment by bobbrow** [comment]
Thanks for reporting the issue.  Too bad it just missed our update. ☹️  I have a fix in PR.

**Comment by dstodev** [comment]
Thank you!

**Comment by willvousden** [comment]
The colours also seem to be at odds with the colour scheme.  Is this intentional?

Bright yellow in a low-contrast colour scheme (Solarized) is pretty unpleasant, and it seems impossible to remove.

<img width="713" alt="Screenshot 2019-11-27 at 09 30 35" src="https://user-images.githubusercontent.com/152388/69944148-deba3400-14e6-11ea-9331-b36cf9e08a1c.png">

**Comment by bobbrow** [comment]
@willvousden I moved your issue to a separate topic.

**Comment by andreeis** [comment]
CMake Tools 1.2.3 was published today and includes a fix for this issue (except #952). Let us know if you encounter any other problems.
