### ISSUE TITLE
platform undefined/toolset {} message after connecting to CMake server

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#913]
There were two warning messages - 

```
[cms-client] Configuring using the "Unix Makefiles" CMake generator with plattform "undefined" and toolset {}
[cms-client] Configuring using the "Unix Makefiles" CMake generator with plattform "undefined" and toolset {}
```

_Originally posted by @thomthom in https://github.com/microsoft/vscode-cmake-tools/issues/825#issuecomment-550359093_

**Comment by bobbrow** [comment]
Here's what I found out.  `platform` (misspelled) corresponds to `CMAKE_GENERATOR_PLATFORM` and is not used by this generator.  `toolset` corresponds to `CMAKE_GENERATOR_TOOLSET` and is also not used by this generator.  I think we should update the message to exclude the optional values when they are not set.

**Comment by andreeis** [comment]
CMake Tools 1.2.3 was published today and includes a fix for this issue. Let us know if you encounter any other problems.
