### ISSUE TITLE
Clean reconfigure fails if CMake build directories are locked

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cmake-tools#920]
If any of the files in the build directory is locked the clean reconfigure command may fail. If reconfigure is tried a few times before the files are unlocked. The following message may appear:
![image](https://user-images.githubusercontent.com/47526411/68949342-7ec34e00-07c2-11ea-8348-444dadbf2422.png)
VSCode needs to be restarted for the clean reconfigure to work again otherwise it is shown on every attempt to clean reconfigure the project.

**Comment by bobbrow** [comment]
Are the build directories locked because you are in the middle of a build?  Are you able to cancel it before configuring?  Or does CMake get "stuck" some other way?  Do you have repro steps we can follow to get into this state?

**Comment by H-G-Hristov** [comment]
I had some files opened in Notepad++. I believe CMakeCache.txt I also had a Command Prompt opened, which must have prevented the build directory to be cleaned up/deleted by the extension.

**Comment by bobbrow** [comment]
If you can help us know the exact steps you took to get into this state, that will help us investigate the problem.

**Comment by bobbrow** [comment]
I'm sorry, but we don't have enough information to investigate this issue.
