### ISSUE TITLE
Don't touch CMakCache.txt

### ISSUE THREAD

**Issue by thothothotho** [microsoft/vscode-cmake-tools#922]
### Brief Issue Summary

Regularly, my CMakeCache.txt get blasted.  It has happened numerous time since the time I'm using this extension, for presumably various reasons.  It was quite stable those months, nothing
to complain about.  But very recently (probably a couple of weeks ago), the problem came back.
At the moment, the extension seems to loose the track of the current toolchain.  When I select it, it regerates a fresh CMakeCache.txt.

This bug is not really to report the problem in the hope it will be fixed, but to suggest a very 
conservative approach.

This extension does a marvelous job by gluing  cmake's state with the cpptools extension, so
that code navigation, error navigation, building a target (F7) ... work like in visual studio (or XCode).  This is the absolute killer feature.  Anything else is barely useful in comparison.  Especially cmake configuration.  

So this is very sad you screw my CMake settings just to help me choose the toolchain I have already chosen a long time ago.  I'm talking about a huge project with many nested CMakeList, 
that is not obvious to configure.  Rebuilding the whole stuff because one subtle `-DFoo` reverts to its default state costs 1 hour of building time.

What I request is a pure readonly mode of the cmake state.  If I don't click on `Select a Kit`, or the `CMakeBuildType` selector, then don't touch anything, please.  If you can't figure what is the current toolchain, then leave it blank.  If you need to set a CMake variable, just to make the plumbing work (cmake server stuff, I don't know), then just do something like:

      cmake -DSOME_MAGICAL_CMAKE_VARIABLE=...

Basically, opening a project and pressing F7 is an _almost read only operation_ on the `CMakeCache.txt` that should just do
 
     cmake --build ...

(don't even provide what you think is the CMAKE_BUILD_TYPE like:

    [proc] Executing command: /usr/local/bin/cmake --build /home/john/src/foo/build --config RelWithDebInfo --target all -- -j 6

 At some point, it was stored by the extension at some other place and could become out of sync with the *authority* file − the `CMakeCache.txt`.)

### About the bug

Here, I'll give some context on the bug itself.  
I have several compilers installed, I also have ccache installed.  And I have additional sym links in `$HOME/bin` like:

```
 ls -al $HOME/bin
lrwxrwxrwx  1 fred fred   14 oct.   8 15:48 c++ -> /usr/bin/g++-8
lrwxrwxrwx  1 fred fred   14 oct.   8 15:48 g++ -> /usr/bin/g++-8
lrwxrwxrwx  1 fred fred   14 oct.   8 15:48 gcc -> /usr/bin/gcc-8
```
So my system is a deep and obscure forest of symlinks pointing to each others.

Usually, `CMAKE_CXX_COMPILER` is set (not by me) to some randomly intermediate symlink.
So, trying to guess what is the _current toolchain_, might be a very fun game to play.  I'm not surprised you get it wrong.

### Platform and Versions

- **Operating System**:  linux ubuntu 18  
- **CMake Version**:  3.13.4
- **VSCode Version**: 1.40.0
- **CMake Tools Extension Version**:  1.2.2
- **Compiler/Toolchain**: gcc-8 or clang

**Comment by thothothotho** [comment]
If you're reluctant to change the behavior, I would be glad  to just have a setting named `dont_touch_cmakecache`.

**Comment by bobbrow** [comment]
I'm sorry for the inconvenience.  I think there's a bug here.  I'm seeing the Kits dropdown appear when it shouldn't.  The extension should leave you alone after you choose "[Unspecified]" from the kits list.

**Comment by thothothotho** [comment]
> I'm sorry for the inconvenience. I think there's a bug here. I'm seeing the Kits dropdown appear when it shouldn't. The extension should leave you alone after you choose "[Unspecified]" from the kits list.

I tried `Unspecified`, but it also blasted my settings.  It just lets cmake choose the kit.

**Comment by bobbrow** [comment]
So, prior to 1.2.x, how were you configured?  Did you pick a Kit?  Did you switch build variants from time to time or do you never use the CMAKE_BUILD_TYPE?

(This is mostly me asking out of curiosity, since we only recently started maintaining this extension and are still learning the code base and customer scenarios.  I still think there would be value in having a "dont use kits" setting for developers who can rely on a stable cache)

**Comment by gcampbell-msft** [comment]
No updates since my comment on July 5, 2023. Closing.
