### ISSUE TITLE
Pass command line arguments for "Run Without Debugging"

### ISSUE THREAD

**Issue by DreamWaterFound** [microsoft/vscode-cmake-tools#924]
I'm so sorry to bother you with this little question ... 

I know how to pass command line arguments to a debug target, but when I executed `CMake: run without debugging`, I found no argument was passed to the target. Did I miss any steps? 

I will be very grateful to you if this problem was solved. Thank you.

**Comment by bobbrow** [comment]
You did not miss any steps.  This functionality has not been implemented.  I will mark as a feature request.

**Comment by DreamWaterFound** [comment]
Thank you for your reply!

Should I close this issue now, or should I keep it open until this new feature is implemented? (Sorry, I'm not familiar with the process of open source software maintenance)

**Comment by bobbrow** [comment]
Please leave it open.  We will close it when the feature is implemented or if we don't think we can get to it in a reasonable time frame.

**Comment by DreamWaterFound** [comment]
Thanks! :thumbsup:

**Comment by fatfatson** [comment]
still not implemented today?

**Comment by bobbrow** [comment]
Not yet.  If you want to take a look at the code, we'd accept a PR.

**Comment by ki9gpin** [comment]
I am new using github. I need this feature too. would someone please accept  this PR. It would great help
https://github.com/microsoft/vscode-cmake-tools/pull/1201

**Comment by PLUkraine** [comment]
Is this feature still in scope?

**Comment by MartinMajewski** [comment]
This is a bummer! Running without a debugger is not that uncommon, isn't it?
Especially, since the ssh-remote debugger has still issues, running without it is common practice for me. Having no way to pass arguments on startup is a show stopper for this the cmake tools.

Any workaround for this?

**Comment by andreeis** [comment]
A good workaround is to use launch.json which can define program launch args and you can invoke the run without debugger via the command "Debug: Start without Debugging" in the pallette (as opposed to CMake: Run without debugging").
.vscode/launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${command:cmake.launchTargetPath}",
            "args": ["arg1", "arg2", "arg3"],
            "stopAtEntry": false,
            "cwd": "${command:cmake.launchTargetDirectory}",
            "environment": [],
            "console": "externalTerminal"
        }
    ]
}

Regarding opened PRs, we are catching up on them this week. Thank you for your patience.

**Comment by andreeis** [comment]
CMake Tools 1.7.0 was released today and it contains a fix for this issue. Upgrade the extension in VSCode and let us know if you encounter any other problems.

**Comment by JodiTheTigger** [comment]
For anyone trying to figure out how to actually do this, you need to add the `args` array to `cmake.debugConfig` in your `settings.json`
```json
"cmake.debugConfig": {
    "args": [
        "-first", 
        "-second"
    ]
 }
```

**Comment by neel** [comment]
@JodiTheTigger  Thanks. But I have multiple targets. Different targets need different set of arguments to run. How can I specify that target specific arguments ?

**Comment by JodiTheTigger** [comment]
> @JodiTheTigger Thanks. But I have multiple targets. Different targets need different set of arguments to run. How can I specify that target specific arguments ?

Sounds like a new bug/feature request to me. I've given up using cmake launch without debugger, and moved back to running manually via the command line.

**Comment by bobbrow** [comment]
If you have multiple configurations that need different sets of arguments to run and you want to save those to a file so you don't have to type them out all the time, the solution is to use `launch.json`.  [More information here](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md#debug-using-a-launchjson-file).
