### ISSUE TITLE
Ubuntu: F5 opens "Select environment", debugging fails

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#925]
On Ubuntu when using F5/Ctrl+F5 or the corresponding commands from the drop down menu: Select environment QuickSelect is opened. If I continue selecting options I get a message that launch.json does not exist and a new file is created. Even after completing all the steps I get an error that the compilation fails. And this repeats on every run.

If I click Debug on the status bar - debugging starts as expected.

If it matters. I have the snap package.

A few screenshots:

![Screenshot from 2019-11-17 08-42-13](https://user-images.githubusercontent.com/3337419/69004223-5baab280-0918-11ea-8788-0da3d231c0f7.png)
![Screenshot from 2019-11-17 08-47-18](https://user-images.githubusercontent.com/3337419/69004224-5c434900-0918-11ea-8399-a20ab8633292.png)
![Screenshot from 2019-11-17 08-51-11](https://user-images.githubusercontent.com/3337419/69004225-5c434900-0918-11ea-98dc-9eb71678955d.png)
![Screenshot from 2019-11-17 08-59-18](https://user-images.githubusercontent.com/3337419/69004288-93662a00-0919-11ea-8013-ca90a3c1116d.png)
![Screenshot from 2019-11-17 09-01-46](https://user-images.githubusercontent.com/3337419/69004289-93fec080-0919-11ea-8aae-4fae6be6ff8f.png)

**Comment by bobbrow** [comment]
F5 is VS Code's keybinding to use `launch.json`.  CTL+F5 is CMake Tools' keybinding and it works for for me.  CMake Tools does not create a launch.json.  It creates the debugger configuration at runtime.

**Comment by Zingam** [comment]
![VSCode-CMake-CPPTools](https://user-images.githubusercontent.com/3337419/69475721-11727700-0dd9-11ea-9e50-1beed0906ded.png)

Is it possible to make all these commands/shortcuts uniform, consistent and to behave as a part of a single unit? At the moment VSCode does one thing, CPPTools another, CMake a third and we still need [twsx's CMake extension](https://marketplace.visualstudio.com/items?itemName=twxs.cmake) for syntax highlighting, etc.

**Comment by bobbrow** [comment]
The problem here is that CMake Tools attempts to bypass the launch.json experience and make debugging easier for you.  The other problem is that there is legacy from before we took ownership and many developers would be confused if we suddenly changed the keybindings.

**Comment by Zingam** [comment]
That makes sense. Well, maybe for version 2.0.0.
I personally expect/desire the CMake extension for VSCode to behave like the CMake support in VS2019. Especially now that MS is in charge. I started using VS201x's CMake integration a while ago and I think is the best integration yet. It took a few years but it is great now. I personally filed hundreds of issues/feature requests.

**Comment by bobbrow** [comment]
We do not plan to change the keyboard shortcuts at this time.  Closing...
