### ISSUE TITLE
Don't require "cmake.generator" if CMAKE_MAKE_PROGRAM is specified

### ISSUE THREAD

**Issue by olegkhar** [microsoft/vscode-cmake-tools#934]
### Brief Issue Summary

When CMAKE_MAKE_PROGRAM is specified (via cmake.configureSettings block), "cmake.generator" shouldn't be necessary.

**Comment by damkrat** [comment]
For this same purpose i've set "cmake.generator" : "null" in settings.json and changed this line of code
in main.js

if (gen) => if (gen && gen.name !== "null") {

```
        args.push('-B' + bindir);
        const gen = this.generator;
        if (gen && gen.name !== "null") {
            args.push(`-G${gen.name}`);
            if (gen.toolset) {
```
I've not found another solution yet....
