### ISSUE TITLE
scan for kits and ccache

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-cmake-tools#936]
Hoping it could scan for ccache under `/usr/lib/ccache`

**Comment by andreeis** [comment]
Did you try to use DCMAKE_CXX_COMPILER_LAUNCHER?
Here's some info I found about integrating CCache with CMake. Let us know if what you are trying to achieve is different and we will see how we can help in the CMake Tools VSCode extension.

https://stackoverflow.com/questions/1815688/how-to-use-ccache-with-cmake

https://www.virag.si/2015/07/use-ccache-with-cmake-for-faster-compilation/

**Comment by bobbrow** [comment]
Closing this issue as not having enough information to proceed.

**Comment by srogatch** [comment]
Please, see https://stackoverflow.com/questions/68459598/how-to-remove-dcmake-c-compilerfilepath-dcmake-cxx-compilerfilepath-from-vis . Apparently, VS Code CMake extension adds `-DCMAKE_C_COMPILER:FILEPATH=/bin/x86_64-linux-gnu-gcc-9` and `-DCMAKE_CXX_COMPILER:FILEPATH=/bin/x86_64-linux-gnu-g++-9` that override `-DCMAKE_CXX_COMPILER_LAUNCHER=ccache` and `-DCMAKE_CUDA_COMPILER_LAUNCHER=ccache`. How to remove these overrides?

**Comment by bobbrow** [comment]
The extension adds CMAKE_C|CXX_COMPILER path based on information it gets from the Kits (or CMakePresets.json).  If you are setting the compiler launcher directly via the workspace settings and that's all that your project needs to configure successfully, then you should be able to set the active Kit to "[Unspecified]" and the extension shouldn't try to set a compiler for you.  You can use the "CMake: Select a Kit" command to make this change. Let us know if that works for you.
