### ISSUE TITLE
Suggestion: Scan and select command for CMake executable

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#943]
While implementing this #942 I noticed that it might be a good idea to add an UI/commands similar to `Scan for/Select Kit` to:
- Scan the system for CMake executables
- Test the executables' version
- Present the user with a QuickSelect to let the user pick the desired version

This can make sense in the following context:
- CMake can be installed in location in the PATH
- CMake may be installed in C:\\Program Files'\\CMake but not included in the PATH
- VS2019 can have a bundled version
- On Linux CMake might be installed as a snap package
- On Linux might be installed as standard package, e.g.
etc.

I think that this maybe good to have before adding snaps support for linux #838

**Comment by bobbrow** [comment]
I don't think UI is appropriate for this because it's usually a one-time setup for a folder, but a command would be ok.  If cmake cannot be located on the PATH, the extension can suggest to scan for a cmake that works.

**Comment by Zingam** [comment]
@bobbrow Please, provide feedback:

These are some of my draft notes/thoughts/ideas of what I think could be done to improve the user experience with setting/detecting the CMake executable.

The changes could be done in one or more PR and will also make some preparations (or implement) necessary for #838.

1. Add a command "Scan for CMake executables"
   If multiple CMake executables are detected, prompt the user to select one, the result will be stored in cmake.cmakePath

2. On `getCMakePath()` call, check if there is a proper path set in `cmake.cmakePath`
   If no "proper" path is set in `cmake.cmakePath` prompt the user to set the correct path or to execute "Scan for CMake executables".

3. If necessary optionally a check could be implemented to test if the path in `cmake.cmakePath`points to a valid CMake executable

Extra: Snaps support on Linux

At least for the moment I think that snaps need to be called via the command:
     `snap run cmake`

If "Scan for CMake executable" detects `/snap/bin/cmake` will set `cmake.cmakePath` to snap.
`getCMakePath()` and `getCTestPath()` will return an object containing the needed information, something like:

```
   {
      cmakePath? <-- path to CMake
      ctestPath? <-- path to CTest
      isSnap?    <-- if the selected CMake is a snap package
   }
```
   
This object will be used for proper CMake invocation.

Visual Studio can also provide a bundled `Ninja`, which needs to be added to the environment (`PATH`) if the bundled CMake  #942 is used (add a configurable `cmake.generatorPath` for that purpose).

**Comment by bobbrow** [comment]
I think this plan looks good.  Let's keep Ninja detection separate from this.

**Comment by gcampbell-msft** [comment]
Looks like #942 solved this, closing this issue.
