### ISSUE TITLE
Quick Debugging Never Attaches

### ISSUE THREAD

**Issue by brporter** [microsoft/vscode-cmake-tools#944]
### Brief Issue Summary

When launching the debugger using the 'Quick Debugging' feature, the debugger never attaches.

### Expected:

Debugger to attach.

### CMake Tools Log

```
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /Users/brporter/projects/spong/build --config Debug --target spong -- -j 6
[build] [100%] Built target spong
[build] Build finished with exit code 0
[proc] Executing command: /usr/bin/lldb-mi --version
[proc] Executing command: /usr/bin/gdb --version
[proc] Executing command: /usr/bin/lldb --version
[proc] Executing command: /usr/bin/lldb --version
```

### Developer Tools Log

C/C++ output window contains
```
Finished installing dependencies

Failed to read response from server: 2
Failed to read response from server: 22
```

### Platform and Versions

- **Operating System**: macOS
- **CMake Version**: 3.15.4
- **VSCode Version**: 1.40.1
- **CMake Tools Extension Version**: 1.2.2
- **Compiler/Toolchain**: Apple clang version 11.0.0 (clang-1100.0.33.12)

### Other details

I'm producing a macOS bundle, if that matters.

**Comment by bobbrow** [comment]
Those error messages are from the cpptools language server, not debugging.  macOS Catalina currently has issues with debugging.  Have you seen https://github.com/microsoft/vscode-cpptools/issues/3829?

**Comment by brporter** [comment]
> Those error messages are from the cpptools language server, not debugging. macOS Catalina currently has issues with debugging. Have you seen [microsoft/vscode-cpptools#3829](https://github.com/microsoft/vscode-cpptools/issues/3829)?

I had not seen that issue, thank you! That does seem to be my problem as well.
