### ISSUE TITLE
"delete cache and reconfigure" doesn't delete the cache

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cmake-tools#945]
### Brief Issue Summary

There should be other ways to repro. One way is to:
1. Create a CMake project
2. Build it
3. Copy it to another directory
4. Run any of these commands: configure / build / delete cache and reconfigure, there will be a pop up window like 
![image](https://user-images.githubusercontent.com/44103947/69672374-d24c5c00-104c-11ea-8ed3-8cb0f5ec48ac.png)
5. Close the window and run "delete cache and reconfigure" manually.

### Expected:

Delete the cache and reconfigure. (The "clean configure" button in that screen shot actually works).

### Apparent Behavior:

The cache is never deleted.

**Comment by andreeis** [comment]
Not a regression, there is an acceptable workaround (use the "clean configure" button from the popup window), triaging for 1.3.
