### ISSUE TITLE
Unexpected behaviors after cancelling build

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cmake-tools#946]
### Brief Issue Summary

Tested on Windows (Not sure if this is OS related)
1. Create a project
2. Finish the current configure/build process so we don't have something blocking
3. Run build (or clean rebuild if build doesn't run long enough), and run 'cancel build' during building.

### Expected:

Once cancelled, running "build" or "clean rebuild" should restart building, and "configure" should do configure

### Apparent Behavior:

Looks like "build" or "clean rebuild" don't trigger any action anymore, and "configure" would result in a "saving file" pop up window forever.

**Comment by andreeis** [comment]
There are more issues to fix in the area of post build cancel.
One related item is https://github.com/microsoft/vscode-cmake-tools/issues/781

**Comment by bobbrow** [comment]
This should have been fixed in 1.3.0
