### ISSUE TITLE
Why doesn't cmake-tools offer VS2019 64-bit kit for x86?

### ISSUE THREAD

**Issue by DavidA2014** [microsoft/vscode-cmake-tools#950]
- **Operating System**:  Windows 10
- **CMake Version**: 3.14.5 
- **VSCode Version**: 1.40.2 
- **CMake Tools Extension Version**: 1.2.2 
- **Compiler/Toolchain**: Visual C++ 2019 

I have VS Build Tools 2019 installed on my 64-bit Intel x86 system.  The only build kit shown by cmake-tools that is appropriate for this system is:

![image](https://user-images.githubusercontent.com/7724321/69975868-ecd87680-151f-11ea-8446-da2d95078804.png)

The other kits are amd64 or arm.

Why does cmake-tools not offer VS2019 32-bit and 64-bit kits for x86?

**Comment by andreeis** [comment]
I don't reproduce this problem. VSCode detects both for me.
Let's find what makes your scenario different than mine. 
Maybe somehow a reduced installation of the VS Build Tools 2019? You see both toolsets present on your machine?
Any other VS installations besides VS Build Tools 2019?

**Comment by DavidA2014** [comment]
@andreeis Thanks for your reply. Both toolsets are on the machine. The installer shows:
![image](https://user-images.githubusercontent.com/7724321/70043269-1218c380-15b8-11ea-9461-cc6585aeda23.png)
A x64 VS 2019 tool prompt is available:
![image](https://user-images.githubusercontent.com/7724321/70043346-3674a000-15b8-11ea-8dbe-8eecbd9e055b.png)
I also have VS 2017 Professional installed.
Here is the full list of kits offered by cmake-tools:
![image](https://user-images.githubusercontent.com/7724321/70043475-7176d380-15b8-11ea-8093-6aa892f8aa36.png)

**Comment by andreeis** [comment]
Oh, amd64_x86 means 64bit compiler tools targeting x86 architecture. It looks like your CMake Tools detects it. Maybe the naming amd64_x86 was confusing.
Try amd64_x86 kit and let us know if you encounter any problems.

**Comment by DavidA2014** [comment]
@andreeis Sorry, I am not convinced. I built using amd64_x86 and then looked at the properties of the built executable using File Explorer. The compatibility checker suggests that the file is 32-bit, whereas we are expecting 64-bit.

**Comment by andreeis** [comment]
Yes, if you built with amd64_x86, the compiler tools are 64 bit but the produced binary is 32 bit, which is what I understood you wanted, to build for 32 bit with 64 bit toolset.
If you want to produce a 64 bit binary, then you use "Visual Studio Build Tools 2019 Release - amd64" (if you want also the compiler to be 64 bit) or "Visual Studio Build Tools 2019 Release - x86_amd64" (if you want the compiler to be 32 bit).
Let us know if what you want to do is different than what I understood and explained above.

**Comment by DavidA2014** [comment]
@andreeis Thank you, I understand now.  I was confused by the 'amd' label as I am working on Intel, but I understand now that amd64 applies to both AMD and Intel 64-bit processors.  Perhaps 'x86-64' would be better, but then you might label the kits something like 'x86-64_x86-64' which might be confusing. Thanks again.
