### ISSUE TITLE
Not possible to debug since vscode update 1.40.2

### ISSUE THREAD

**Issue by LuisAyuso** [microsoft/vscode-cmake-tools#954]
### Brief Issue Summary

The Extension Debug button in the bottom bar prompts error, normal debug tab on the left prompts same error:

ConvertToDto unexpected type

Extension Target selection works as usual.

### Expected:

1. Open CMake Project
2. Select Target to debug (bottom bar)
3. Click Debug
4. Debugger session starts

### Apparent Behavior:

1. Open CMake Project
2. Select Target to debug (bottom bar)
3. Click Debug
4. Bang! ConvertToDto unexpected type

### CMake Tools Log

```
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build xxxxxxxxxxxxxxxxx --config Debug --target xxxxxxxxxxxx -- -j 16
[build] [1/6  16% :: 0.004] xxxxxxxxxxxxxxxxxxx
[build] [2/4  50% :: 0.009] xxxxxxxxxxxxxxxxxxx
[rollbar] Unhandled exception: Unhandled Promise rejection: Update code model for cpptools TypeError: Cannot read property 'getApi' of undefined {}
[build] Build finished with exit code 0
[proc] Executing command: /usr/bin/gdb-7 --version
[proc] Executing command: gdb --version
```

### Platform and Versions

- **Operating System**:  Ubuntu 18.04
- **CMake Version**: 3.16
- **VSCode Version**: 1.40.2
- **CMake Tools Extension Version**: 1.2.3
- **Compiler/Toolchain**: gcc 7.4

**Comment by LuisAyuso** [comment]
This issue is actually coming  from the c++ extension and not CMake tools, sorry for inconvenience

**Comment by sean-mcmanus** [comment]
@LuisAyuso Why do you says it's coming from the C++ extension?

@bobbrow @andreeis Could this be a CMake Tools bug? Pierson seems to think so.

**Comment by LuisAyuso** [comment]
sorry for the delay, I commented about this here: https://github.com/microsoft/vscode-cpptools/issues/4703#issuecomment-563155650
