### ISSUE TITLE
Variant expansion initially empty when referenced from settings.json

### ISSUE THREAD

**Issue by allsey87** [microsoft/vscode-cmake-tools#955]
### Brief Issue Summary
Using variants in `settings.json` such as:
```json
"cmake.buildDirectory": "${workspaceFolder}/build-${variant:buildFor}-${variant:buildType}",
```
results in an empty directory called `build--` being created when I select a variant from the GUI. Once this process is complete, I get the proper directory being created and used for the build, but this empty, incorrectly named build directory is left behind.

### Expected:

No directory `build--` should be created. I guess this could be solved by parsing and loading `cmake-variants.json` before processing `settings.json`.

### Platform and Versions

- **Operating System**: Arch Linux
- **CMake Version**: 3.15.5
- **VSCode Version**: Code - OSS 1.40.1
- **CMake Tools Extension Version**: 1.2.3
- **Compiler/Toolchain**: GCC 9.2

**Comment by Zingam** [comment]
Maybe these are related: #632 #334 #564 #869

**Comment by SafwenBenJha** [comment]
I would like to mention that also variant expansion does not work in tasks.json

```
{   "version": "2.0.0",
    "tasks": [
        {
            "label": "echo test",
            "type": "shell",
            "command": "echo ${variant: myvariantname}",
            "problemMatcher": []
        }
    ]
}
```


This will always output an empty string instead of the actual value.
Is there a workaround?
