### ISSUE TITLE
Manually removing build folder leads to unexpected behaviour

### ISSUE THREAD

**Issue by epavese** [microsoft/vscode-cmake-tools#956]
### Brief Issue Summary

Manually removing the build folder from outside VSCode leads to unexpected behaviour, namely that CMake fails to configure properly. Workaround: switch kits which causes the build folder to be recreated, HOWEVER creating the empty build folder alone externally does not solve the issue.

### Expected:

1. Remove your build folder completely (ie, rm -rf build/)
2. refresh in VSCode if necessary
3. Run CMake : Configure command
4. Configuration should happen as if running the cmake command externally

### Apparent Behavior:

CMake fails to configure properly, most notably for my example project the first output lines are

[cmake] The C compiler identification is unknown
[cmake] The CXX compiler identification is unknown
[cmake] Check for working C compiler: /usr/bin/cc
[cmake] Check for working C compiler: /usr/bin/cc -- works
[cmake] Detecting C compiler ABI info
[cmake] Detecting C compiler ABI info - done
[cmake] Check for working CXX compiler: /usr/bin/c++
[cmake] Check for working CXX compiler: /usr/bin/c++ -- works

### Platform and Versions

- **Operating System**: Ubuntu 18.04
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.40.2
- **CMake Tools Extension Version**: 1.2.3
- **Compiler/Toolchain**: Happens regardless of selected kit, even with no kit

**Comment by andreeis** [comment]
I am not reproducing this problem with configuring. Can you create a standalone repro for us to try? Maybe there's some special circumstance I didn't think about when testing.
