### ISSUE TITLE
Fails to provide the includePath after recent CMAKE tools Update

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-cmake-tools#959]
Came from https://github.com/microsoft/vscode-cpptools/issues/3731#issuecomment-562402577

The situation is after update to 1.2.1 the cpp tools not working from cpp-tools teams view the cpp extension cannot get include path from cmake setting,

You can see from https://github.com/microsoft/vscode-cpptools/issues/3731#issuecomment-552690361

And due to https://github.com/microsoft/vscode-cmake-tools/issues/904, I cannot down grade

If there is a way, I can get intellisense work again?/

**Comment by bobbrow** [comment]
Based on your report in that issue, it looks like you don't have the right Kit selected or you haven't run the `CMake: Configure` command yet.

Can you [enable logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp) for cpptools and share what is printed out under `Custom configurations received:` in the log?  If you can't find this string in the log it means that CMake Tools is not providing the configuration to cpptools (likely for one of the reasons above).

**Comment by Victsz** [comment]
CMake: Configure 
![image](https://user-images.githubusercontent.com/8154646/70369222-d865f680-18f0-11ea-8803-d5b253f54556.png)
I think it run automatically .

And the kit should be correct as well because I have no problem to build the project.

And I cant find the "Custom configurations received:" in Debug log level

**Comment by bobbrow** [comment]
Are you still having a problem?  This log output looks like everything is working ok.

**Comment by andreeis** [comment]
Please reactivate if you are still experiencing this problem and it would help if you attach a standalone repro.

**Comment by moechofe** [comment]
I think, I still have this problem. I came here from the original link that OP posted.
I have a cpp project that use this cmake extension.
My program compile and the symbol are completed by vscode but the editor keep telling me the headers are not found.
It's annoying because every file in the list became red everywhere.

**Comment by bobbrow** [comment]
@moechofe can you open a new issue and share details about your project, what settings you are using, and maybe also the log output from the extension (using `"cmake.loggingLevel": "debug"` setting)?

Thank you!
