### ISSUE TITLE
CMake Tools is sending x64 intelliSenseMode for x86 compiler

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode-cmake-tools#960]
When using CMake Tools as a configuration provider for vscode-cpptools, I'm seeing that it returns x64 intelliSenseMode for x86 compiler.  'msvc-x86' is expected:

```
  "intelliSenseMode": "msvc-x64",
  "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe",
```

It looks like the only 2 values it returns are msvc-x64 and clang-x64.  The following is from cpptools.ts, line ~270.

```
intelliSenseMode: is_msvc ? 'msvc-x64' : 'clang-x64',
```

The x86 intelliSenseModes are relatively recent additions in cpptools, so this probably predates them.  Though, if the compiler is gcc, gcc intelliSenseMode's should be used.

**Comment by andreeis** [comment]
Closing since this is fixed in CMake Tools Beta2. Please reactivate if you encounter any other symptoms of this issue.
