### ISSUE TITLE
Default defines is ignored

### ISSUE THREAD

**Issue by wduminy** [microsoft/vscode-cmake-tools#961]
### Brief Issue Summary
When using CMake Tools as a configuration provider for vscode-cpptools, the `C_Cpp.default.defines` setting is ignored.  The effect is that some code regions become inactive and are dimmed.
When I remove the configuration provider, the region dimming works as expected.

Entries below is from `settings.json`
```json
"C_Cpp.default.defines": ["TESTING"],
"C_Cpp.dimInactiveRegions": true,
```

### Platform and Versions

- **Operating System**:  macOS
- **CMake Version**:  3.15.5
- **VSCode Version**: 1.40.2
- **CMake Tools Extension Version**: 1.2.3
- **Compiler/Toolchain**: Clang 11.0.0

**Comment by bobbrow** [comment]
This is expected behavior.  When you use the configuration provider, cpptools does not allow you to override the provider with any of your other settings.  To get this effect, you would need to add the define to your CMakeLists.txt or configuration settings.

**Comment by wduminy** [comment]
This is good news.  

> To get this effect, you would need to add the define to your CMakeLists.txt 

I do have an entry in `CMakeLists.txt`, but applies only to one target - that could be the problem:
```
	target_compile_definitions(test_app PUBLIC "TESTING")
```
> or configuration settings.

Which file and what setting would you recommend?

**Comment by bobbrow** [comment]
Is the setting used by multiple targets?  You'd need to add it to the CMakeLists.txt for each target it applies to.

The way I would usually do this is with
```
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DTESTING")
```
Perhaps you use custom variants, but I'm less familiar with that route.

**Comment by wduminy** [comment]
I tried `c_cpp_properties.json` - but my region is still dimmed:
```j
	"configurations": [
		{
...
			"defines": [
				"TESTING"
			],
...
```

**Comment by bobbrow** [comment]
cpptools will never override the configuration provider with any of your settings.  The define has to come from CMake Tools, so you need to add it to your CMake project.

**Comment by wduminy** [comment]
> Is the setting used by multiple targets? You'd need to add it to the CMakeLists.txt for each target it applies to.

My setting applies only to one target. I do not want to apply it to other targets.

With the global setting, intellisense works - but my build fails for other targets.
```
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DTESTING")
```

So generally I think having a configuration setting that is target independent and only applies to intellisense is a nice to have feature.  Perhaps I should create a new request?

Thanks for your help.

**Comment by wduminy** [comment]
Another possibility is that cmake-tools picks up the defines from the selected build target.  That would be ideal.
