### ISSUE TITLE
Can't debug in Visual Studio Code

### ISSUE THREAD

**Issue by zhouhao27** [microsoft/vscode-cmake-tools#965]
### Brief Issue Summary

Can't make the Visual Studio Code debugger work.

### Expected:

1. Run `CMake Configuration`

<img width="585" alt="Screenshot 2019-12-10 at 4 01 19 PM" src="https://user-images.githubusercontent.com/8099731/70507693-d35eac80-1b67-11ea-848e-92d4b72309da.png">

The result:
```
[cmake] Configuring done
[cmake] CMake Deprecation Warning:
[cmake]   The 'cmake-server(7)' is deprecated.  Please port clients to use the
[cmake]   'cmake-file-api(7)' instead.
[cmake] 
[cmake] 
[cmake] Generating done
```

2. Select Clang 11.0

<img width="538" alt="Screenshot 2019-12-10 at 4 15 43 PM" src="https://user-images.githubusercontent.com/8099731/70507966-67c90f00-1b68-11ea-9a3a-edcf4d41725a.png">

3. Allow `IntelliSense for this folder`

<img width="503" alt="Screenshot 2019-12-10 at 4 15 53 PM" src="https://user-images.githubusercontent.com/8099731/70508058-98a94400-1b68-11ea-877a-6fb36e1a8209.png">

4. Build

<img width="358" alt="Screenshot 2019-12-10 at 4 18 06 PM" src="https://user-images.githubusercontent.com/8099731/70508124-b9719980-1b68-11ea-808d-be5007cb2df2.png">

The result:
```
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /Users/xxx/Desktop/cmake/hello/build --config Debug --target all -- -j 6
[build] Scanning dependencies of target say-hello
[build] [ 25%] Building CXX object CMakeFiles/say-hello.dir/hello.cpp.o
[build] [ 50%] Linking CXX static library libsay-hello.a
[build] [ 50%] Built target say-hello
[build] Scanning dependencies of target hello
[build] [ 75%] Building CXX object CMakeFiles/hello.dir/main.cpp.o
[build] [100%] Linking CXX executable hello
[build] [100%] Built target hello
[build] Build finished with exit code 0
```

5. Set the break point and run Debug

<img width="397" alt="Screenshot 2019-12-10 at 4 08 23 PM" src="https://user-images.githubusercontent.com/8099731/70508208-f178dc80-1b68-11ea-8a41-2e0fe129d56b.png">

<img width="861" alt="Screenshot 2019-12-10 at 4 19 44 PM" src="https://user-images.githubusercontent.com/8099731/70508215-f50c6380-1b68-11ea-9ae8-ebfe484dd2bc.png">

### Apparent Behavior:

1. It seems the editor hangs
2. The information in `Output`

```
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /Users/xxx/Desktop/cmake/test/build --config Debug --target hello -- -j 6
[build] [ 50%] Built target say-hello
[build] [100%] Built target hello
[build] Build finished with exit code 0
[proc] Executing command: /usr/bin/lldb-mi --version
[proc] Executing command: /usr/bin/gdb --version
[proc] Executing command: /usr/bin/lldb --version
[proc] Executing command: /usr/bin/lldb --version
```

### Platform and Versions

- **Operating System**: macOS 10.15
- **CMake Version**: 3.15.5
- **VSCode Version**: 1.40.2
- **CMake Tools Extension Version**: 1.2.3
- **Compiler/Toolchain**: Xcode

**Comment by Hadatko** [comment]
As long as i know cmake is only for building final image/binary. You need install extension for debugging for device you want to. E.g. i am debugging arm embedded device so i am using gdb debugger or cortex debugger.

**Comment by bobbrow** [comment]
Are you hitting this issue?  https://github.com/microsoft/vscode-cpptools/issues/3829
We're working on it (with the C++ extension).

**Comment by zhouhao27** [comment]
@bobbrow Yes, I have the same issue. Thanks for your information.  

Based on [this youtube video](https://www.youtube.com/watch?v=wP4cwAtU-g8&list=PLK6MXr8gasrGmIiSuVQXpfFuE1uPT615s&index=7), we even don't need to setup launch.json or task.json to debug. Is that true?

**Comment by bobbrow** [comment]
That is correct. You shouldn't need a launch.json or tasks.json. If you do need to override a setting for debugging, you can use the `cmake.debugConfig` setting.

**Comment by kaidokert** [comment]
The problem is this:

`[proc] Executing command: /usr/bin/lldb --version`

The default lldb gets picked, which will not work. The launch command of ` /usr/bin/lldb --interpreter=mi` will just fail with 

```
Starting: "/usr/bin/lldb" --interpreter=mi
lldb: unrecognized option `--interpreter=mi'
```
The root of the issue is in this fallback codepath in this plugin: https://github.com/microsoft/vscode-cmake-tools/blob/50fc5ba265ee13f53dc9f273d0f1635c8861bd7d/src/debugger.ts#L163

If your compiler is "/usr/bin/clang" it tries to use "/usr/bin/lldb" as a debugger, and does not respect the "miDebuggerPath" setting in launch.json ( as launch.json might not even exist here ).

It works fine when hardcoding something like : `let clang_debugger_path = '/Applications/Xcode.app/Contents/Developer/usr/bin/lldb-mi';` instead, which is what the plugin code should probably be trying by default, or alternatively look for `lldb-mi` provided by `vscode-cpptools`

**Comment by bobbrow** [comment]
FYI, `miDebuggerPath` can be set via the `cmake.debugConfig` setting:
```
    "cmake.debugConfig": {
        "miDebuggerPath": "/path/to/lldb-mi"
    },
```

**Comment by hroumani** [comment]
@bobbrow your suggestion did the trick for me, before than:
`[main] Starting debugger with following configuration. ... "miDebuggerPath":"gdb"`

So it was effectively ignoring:
`"miDebuggerPath": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\gdb.exe"`

In `launch.json`.

**Comment by bobbrow** [comment]
I believe this issue was addressed but was never closed.  If any of you are still having issues, we encourage you to open a new issue.
