### ISSUE TITLE
PRE_BUILD

### ISSUE THREAD

**Issue by Hadatko** [microsoft/vscode-cmake-tools#966]
### Brief Issue Summary

Add support for PRE_BUILD cmd.

### Expected:

I see that only Visual Studio support PRE_BUILD cmd. Is there a way how to execute pre build cmd? If it cannot be part of CMakeList, could it be part of cmake json setting option?

**Comment by bobbrow** [comment]
@andreeis, we should take a look and see if we can hook into the VS Code tasks system when building. Then you could author a task in tasks.json and we could just instruct VS Code to run it before doing our build step.

**Comment by Hadatko** [comment]
I solved my issue with dependency building. 
```
ADD_CUSTOM_COMMAND(
    OUTPUT ${EXECUTABLE_OUTPUT_PATH}/service/erpc_message_linux2rtos_server.cpp ${EXECUTABLE_OUTPUT_PATH}/service/erpc_message_rtos2linux_client.cpp
    COMMAND ${ProjDirPath}/erpc/erpcgen -g c -o ${EXECUTABLE_OUTPUT_PATH} ${ProjDirPath}/source/erpc_message/erpc_message.erpc
    COMMAND ${ProjDirPath}/erpc/erpcgen -g py -o ${ProjDirPath}/../containers/erpc ${ProjDirPath}/source/erpc_message/erpc_message.erpc
)
```
But still i don't understand why PRE_BUILD cmd is supported only for VIsual Studio. But for me is this issue no longer necessary as i solved it different way.

**Comment by gcampbell-msft** [comment]
@Hadatko We will mark this as `stale-exempt` to prevent it from going stale, as this is a valid feature request. Thanks for bringing this to our attention!

**Comment by Hadatko** [comment]
:-*

**Comment by gcampbell-msft** [comment]
Based on the documentation here: https://cmake.org/cmake/help/latest/command/add_custom_command.html, this is documented by Kitware to not be recommended, because it has specific behavior _only for Visual Studio Generators_. With this in mind, I don't think that we will be implementing this. 

Thanks for your contributions!
