### ISSUE TITLE
Integrate with cpptools after initial prompt

### ISSUE THREAD

**Issue by williamwest0520** [microsoft/vscode-cmake-tools#967]
### Brief Issue Summary

If I reject the cpptools integration prompt when first installed, how do I get the option back?

### Other Notes/Information

Looking at "Set Up Include Paths for C++ IntelliSense?"
https://vector-of-bool.github.io/docs/vscode-cmake-tools/how_do_i.html#hdi-intellisense
How do I get this option a second time, or just set it up manually?

**Comment by bobbrow** [comment]
You can use the "Change Configuration Provider" command.

**Comment by williamwest0520** [comment]
I have found that. Any ideas on when the CMake Tools option doesn't appear in the list?

**Comment by bobbrow** [comment]
It should appear after you run the "CMake: Configure" command.

**Comment by williamwest0520** [comment]
And when it doesn't?

**Comment by bobbrow** [comment]
I've never known a case where it didn't.  Can you provide a repro?

**Comment by williamwest0520** [comment]
I'm not entirely sure what information to provide. It's another user's computer here where I work. We have the CMake Tools extension installed, and we're all working from the same git repository, but when he has CMake Tools configure the project, he doesn't get anything in the CMake Project Outline, and the configuration provider option is not available. Neither of these problems are present in my vscode.

**Comment by bobbrow** [comment]
Can you enable logging by setting the `cmake.loggingLevel` setting to `"debug"`?  Then:
1. Reload the window
2. Configure your project
3. Share the contents of the Output Window with the "CMake/Build" channel selected.
![image](https://user-images.githubusercontent.com/12818240/72471008-ac168300-3796-11ea-8a5e-23ed863a64ef.png)

**Comment by williamwest0520** [comment]
[main] Starting new CMake driver
[main] Starting CMake driver
[main] CMake Server is not available with the current CMake executable. Please upgrade to CMake 3.7.1 or newer.
[legacy-driver] Creating instance of LegacyCMakeDriver
[driver] CMakeDriver Kit set to GCC 4.8.5
[driver] Trying to detect generator supported by system
[driver] Command version test return code ENOENT
[driver] Command version test return code ENOENT
[driver] Command version test return code 0
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[cache] Reading CMake cache file /home/[directories]/CMakeCache.txt
[cache] Parsing CMake cache string
[driver] Setting new variant , Disable optimizations - include debug information.
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[driver] Start configure
[driver] Runnnig pre-configure checks and steps
[driver] Using compilers in GCC 4.8.5 for configure
[driver] Run _refreshExpansions
[driver] Run _refreshExpansions cb
[legacy-driver] Invoking CMake /usr/bin/cmake with arguments ["--no-warn-unused-cli","CMAKE_MAKE_PROGRAM","-DCMAKE_BUILD_TYPE:STRING=Debug","-DBUILD_TESTS:STRING=ON","-DBUILD_WITH_CUDA:STRING=OFF","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-DCMAKE_C_COMPILER:FILEPATH=/bin/gcc","-DCMAKE_CXX_COMPILER:FILEPATH=/bin/g++","-H/home/[directories]","-B/home/[directories]","-GUnix Makefiles"]
[proc] Executing command: /usr/bin/cmake --no-warn-unused-cli CMAKE_MAKE_PROGRAM -DCMAKE_BUILD_TYPE:STRING=Debug -DBUILD_TESTS:STRING=ON -DBUILD_WITH_CUDA:STRING=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/bin/g++ -H/home/[directories] -B/home/[directories] "-GUnix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Warning (dev) at Source/StandardPlugins/SerialPort/CMakeLists.txt:3 (INCLUDE):
[cmake]   Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
[cmake]   and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
[cmake]   cmake_policy command to set the policy and suppress this warning.
[cmake]
[cmake]   The included script
[cmake]
[cmake]     /home/[directories]/CMake/SetupQt.cmake
[cmake]
[cmake]   affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
[cmake]   compatibility, so the effects are applied to the including context.
[cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
[cmake]
[cmake] CMake Warning (dev) at Source/StandardPlugins/UdpPort/CMakeLists.txt:3 (INCLUDE):
[cmake]   Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
[cmake]   and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
[cmake]   cmake_policy command to set the policy and suppress this warning.
[cmake]
[cmake]   The included script
[cmake]
[cmake]     /home/[directories]/CMake/SetupQt.cmake
[cmake]
[cmake]   affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
[cmake]   compatibility, so the effects are applied to the including context.
[cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
[cmake]
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /home/l[directories]
[cache] Reading CMake cache file /home/[directories]/CMakeCache.txt
[cache] Parsing CMake cache string


I just noticed the "CMake Server is not available with the current CMake executable" line. Could it be that his CMake is just too old and that's causing issues? He has 2.8.12.2.

**Comment by bobbrow** [comment]
Yes.  That is the problem.  We can't provide configurations to cpptools without CMake Server.  You'll need to upgrade CMake to enable this feature.

Thanks for providing the log.

**Comment by williamwest0520** [comment]
Well that's an easy fix. Thanks for all the help.
