### ISSUE TITLE
Remote extension Host terminated unexpectedly when running "CMake:Configure" 

### ISSUE THREAD

**Issue by Lennon925** [microsoft/vscode-cmake-tools#970]
VSCode Version：1.41.0
CMake Tools Version：1.2.3

Install CMake Tools on remote linux machine and open project using remote-ssh, when running "CMake:Configure" frist time, it's OK.But run this command again,  the extension host terminated unexpectedly.
![1](https://user-images.githubusercontent.com/39362073/70775942-c1bf1400-1db6-11ea-90e6-4f029b982664.PNG)
![2](https://user-images.githubusercontent.com/39362073/70775947-c388d780-1db6-11ea-891b-d164be733de6.PNG)

![捕获](https://user-images.githubusercontent.com/39362073/70769246-b9a9a900-1da3-11ea-884f-c48849f15f62.PNG)

**Comment by Lennon925** [comment]
I change to another machine which is Linux ubuntu, after running "CMake Configure", the CMake:Project Outline is empty. I don't know if it's relate with OS.
![333](https://user-images.githubusercontent.com/39362073/70786381-84af4d80-1dc7-11ea-838d-9439496e1058.PNG)

**Comment by Lennon925** [comment]
In linux suse system, if your project is small, you can run "CMake:Configure" again and again, and CMake:Project Outline show results correctly. But if your project is big, it's OK to run "CMake:Configure" first time, When you run it again, Extension Host terminated unexpectedly and CMake:Project outline is empty.
In linux ubantu system, CMake:Project Outline is always empty even though you run "CMake:Configure" many times.

**Comment by Lennon925** [comment]
@bobbrow Hi Bob, do you know who is the owner of CMake Tools Project?  It seems that many issues don't get replied.

**Comment by Lennon925** [comment]
I guess it's related with this: Server pass too big data to client to draw CMake:Project Tree. Anyone can confirm this and fix it?

**Comment by bobbrow** [comment]
Hi @Lennon925, we try to add tags or respond to issues within a day of being posted. However, right now it is the holiday season in the United States, so many people are on vacation (including myself). Please excuse our delay in responding right now.

**Comment by Lennon925** [comment]
> Hi @Lennon925, we try to add tags or respond to issues within a day of being posted. However, right now it is the holiday season in the United States, so many people are on vacation (including myself). Please excuse our delay in responding right now.

Thanks for your reply and sorry about I forgot Christmas Day. Happy Christmas.

**Comment by Lennon925** [comment]
I clone CMake-Tools source code and found:

>  public static async fromFilePath(dbpath: string): Promise<CompilationDatabase|null> {
    if (!await fs.exists(dbpath)) {
      return null;
    }
    const data = await fs.readFile(dbpath);
    try {
      const content = JSON.parse(data.toString()) as CompileCommand[];
      return new CompilationDatabase(content);
    } catch (e) {
      log.warning(localize('error.parsing.compilation.database', 'Error parsing compilation database "{0}": {1}', dbpath, e));
      return null;
    }
  }

const data = await fs.readFile(dbpath);  // 69 line of src\compdb.ts
This line results in remote extension host crash when compile-command.json is large. (Currently I am using remote-ssh)

**Comment by Lennon925** [comment]
In addition, how to debug extensions using remote-ssh when you develop remote extensions. It seems that extensions can't be actived on remote-ssh debug mode. I reported this issue on https://github.com/microsoft/vscode-remote-release/issues/1830

**Comment by andreeis** [comment]
Hi @Lennon925 , thank you for your understanding with our slow reply over the holidays break. I was not on vacation, but indeed as @sean-mcmanus said (on issue https://github.com/microsoft/vscode-cpptools/issues/4768) I wasn't able to follow closely the issues and PRs on CMake-Tools due to other work items and assignments that took longer than expected.  

Just by reading all the related reports I don't have a quick answer for you but I want to start reproducing the problem, try your experimental fix and some other ideas @sean-mcmanus is having. I need to do some debugging of the CMake Tools codebase (for which I'm pretty new) to gain the understanding needed for recommending a good approach for you in developing your extension or most likely for fixing our CMake Tools extension to support better your scenario.

Let me give you more info later on Monday next week.

**Comment by Lennon925** [comment]
> Hi @Lennon925 , thank you for your understanding with our slow reply over the holidays break. I was not on vacation, but indeed as @sean-mcmanus said (on issue [microsoft/vscode-cpptools#4768](https://github.com/microsoft/vscode-cpptools/issues/4768)) I wasn't able to follow closely the issues and PRs on CMake-Tools due to other work items and assignments that took longer than expected.
> 
> Just by reading all the related reports I don't have a quick answer for you but I want to start reproducing the problem, try your experimental fix and some other ideas @sean-mcmanus is having. I need to do some debugging of the CMake Tools codebase (for which I'm pretty new) to gain the understanding needed for recommending a good approach for you in developing your extension or most likely for fixing our CMake Tools extension to support better your scenario.
> 
> Let me give you more info later on Monday next week.

Thank you very much!

**Comment by bobbrow** [comment]
So, just to confirm, the issue here is that it takes too long to parse the `compile_commands.json` file?

**Comment by sean-mcmanus** [comment]
Yeah, it could be the JSON.parse call (I didn't see that before, and "readFile" was mentioned so I just assumed that was the cause) -- changing it to use something asynchronous like JSONStream might work.

@Lennon925 Our C/C++ extension doesn't hit this issue because it parses compile_commands.json in our separate process and not TypeScript.

**Comment by Lennon925** [comment]
> So, just to confirm, the issue here is that it takes too long to parse the `compile_commands.json` file?

Yes. It's fs.readFile. I tried to use stream to read file but it didn't work.

**Comment by Lennon925** [comment]
> Yeah, it could be the JSON.parse call (I didn't see that before, and "readFile" was mentioned so I just assumed that was the cause) -- changing it to use something asynchronous like JSONStream might work.
> 
> @Lennon925 Our C/C++ extension doesn't hit this issue because it parses compile_commands.json in our separate process and not TypeScript.

I think you are right. this issue can be solved by parsing compile-command.json in a separate process like language server process.

**Comment by Lennon925** [comment]
> Hi @Lennon925 , thank you for your understanding with our slow reply over the holidays break. I was not on vacation, but indeed as @sean-mcmanus said (on issue [microsoft/vscode-cpptools#4768](https://github.com/microsoft/vscode-cpptools/issues/4768)) I wasn't able to follow closely the issues and PRs on CMake-Tools due to other work items and assignments that took longer than expected.
> 
> Just by reading all the related reports I don't have a quick answer for you but I want to start reproducing the problem, try your experimental fix and some other ideas @sean-mcmanus is having. I need to do some debugging of the CMake Tools codebase (for which I'm pretty new) to gain the understanding needed for recommending a good approach for you in developing your extension or most likely for fixing our CMake Tools extension to support better your scenario.
> 
> Let me give you more info later on Monday next week.

Any update?

**Comment by andreeis** [comment]
I actually ended up taking some unexpected out of office time, back in office now and looking at this today.

**Comment by andreeis** [comment]
Hi @Lennon925 , would you be able to share with us a repro project? Thanks.

**Comment by gcampbell-msft** [comment]
@Lennon925 Could you confirm if this issue is still occurring? Thanks!
