### ISSUE TITLE
On changing the build folder setting the `compileCommand` path is not updated

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cmake-tools#972]
Changing `cmake.buildDirectory` doesn't update
```
...\.vscode\c_cpp_properties.json
           "compileCommands": "${workspaceFolder}/build/compile_commands.json"
```

**Comment by bobbrow** [comment]
This extension does not write to `c_cpp_properties.json`.  You would need to do this manually.

However, the preferred integration with cpptools is via `"configurationProvider"` because it can update automatically depending on the Kits/Variants that you set in CMake Tools.
