### ISSUE TITLE
Map build shortcut (shift + F7) to build button 

### ISSUE THREAD

**Issue by rafmudaf** [microsoft/vscode-cmake-tools#976]
### Feature request

Currently, when a build target is set and I hit the "build" button from the status bar / side bar, the target shown in the status bar is compiled. When I use the hot key (shift + F7), I'm forced to type the target I want to build. A better scenario would be to have the same functionality at the "build" button. 

### Expected:

1. Set a build target
2. Using only the shortcut for build (shift + F7), launch the build step
3. Probably run some test or see that my code doesnt compile
4. Make changes in code
5. Using only the shortcut for build (shift + F7), launch the build step

**Comment by nickaleks** [comment]
Why can't you use F7 to just build the target from the status bar?

**Comment by rafmudaf** [comment]
Oh ... user error. Thanks @nickaleks.
