### ISSUE TITLE
build Error: spawn chcp ENOENT {}

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode-cmake-tools#977]
Windows 10

Insiders build vscode:1.42.0
cmake tools: 1.2.3
compiler mingw 7.3
cmake 3.16

cmake project configured successfully , 
the issue was raised on build step.

switching to vscode's builtin terminal and call: cmake --build . works fine
all tools : mingw toolchain and cmake both exist in Windows PATH env variable

> [build] Starting build
> [rollbar] Unhandled exception: Unhandled Promise rejection: build Error: spawn chcp ENOENT {}
> 

attempt to run a build again returns:

> A CMake task is already running. Stop it before trying to run a new CMake task.
> 
> [build] Starting build
> [build] Build finished with exit code -1

**Comment by bobbrow** [comment]
Thanks for reporting this.  I have a PR out to fix it.

**Comment by andreeis** [comment]
Closing since this is fixed in CMake Tools Beta2. Please reactivate if you encounter any other symptoms of this issue.
