### ISSUE TITLE
can not find build kit

### ISSUE THREAD

**Issue by degawang** [microsoft/vscode-cmake-tools#986]
![微信图片_20191225111613](https://user-images.githubusercontent.com/18233018/71430652-185a1580-2708-11ea-8def-4bdfcfdde484.jpg)

### Brief Issue Summary

already have visual studio 2013 15 17 19 and gcc 9.2 installed,and env varible setted,when I choose the build kit, only several vs2019 options to be choosen

### Platform and Versions

- **Operating System**: 
- **CMake Version**:  3.15.6
- **VSCode Version**: 1.14.1
- **CMake Tools Extension Version**:  1.2.3
- **Compiler/Toolchain**: visual studio 2019 Enterprise

**Comment by bobbrow** [comment]
We rely on `vswhere.exe` to locate Visual Studio installations.  It states that it has limited support for VS 2015 and earlier versions, but we'd need to look into it more.

You can also try adding the path to your GCC installation to:
```
    "cmake.mingwSearchDirs": [
        "C:\\path\\to\\mingw"
    ],
```
Make sure you specify the parent folder of the `bin` folder.  The rerun the "CMake: Scan for Kits" command.

**Comment by degawang** [comment]
thank you bobbrw,`CMake: Scan for Kits` works for me.

**Comment by bobbrow** [comment]
Thanks for confirming.  Let us know if you need anything else.
