### ISSUE TITLE
No way to change active workspace folder?

### ISSUE THREAD

**Issue by leonid-s-usov** [microsoft/vscode-cmake-tools#989]
### Brief Issue Summary

A workspace with several folders uses the topmost folder as the active one, without a chance to switch.

### Expected:

When having a workspace with multiple folders (in my case, a folder represents a standalone project), I would like to either set the active folder manually, or have the system automatically change the active folder based on the current open file.

### Apparent Behavior:

CMake tools work with the same folder until it's removed from the workspace, in which case the tools switch to the next available folder.

### Platform and Versions

- **Operating System**:  macos
- **CMake Version**:  3.16.2
- **VSCode Version**: Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
- **CMake Tools Extension Version**: 1.2.3
- **Compiler/Toolchain**: xtensa ESP toolchain

**Comment by bobbrow** [comment]
Thanks for the feedback.  Issue #271 is tracking multiroot support and PR #958 which adds this support is currently under review.
