### ISSUE TITLE
Ability to export cmake tools variables

### ISSUE THREAD

**Issue by njames93** [microsoft/vscode-cmake-tools#993]
I was wondering if it's possible to export the cmake tools [variables](https://vector-of-bool.github.io/docs/vscode-cmake-tools/settings.html#variable-substitution) in such a way that they could be referenced in launch.json

**Comment by bobbrow** [comment]
Which variables do you want?  I think all of them are available except for ${generator}.  The syntax is different for some of them.  `${command:cmake.buildType}` and `${command:cmake.buildKit}` should work along with a couple of other commands not listed in the docs yet (`launchTarget`, `launchTargetPath`, `launchTargetDirectory`, `buildDirectory`)

**Comment by bobbrow** [comment]
Actually, `buildKit` was just added and isn't in a public release yet.  It will be in the next one.

**Comment by schnort** [comment]
I'm suffering quite a bit on this right now.  I am trying to support multiple targets  (windows GCC, cross compile w/GCC for hardware target, cross compile w/GCC for instruction set simulator target) and need a way to have launch.json be configured so the right GDB gets called with the right parameters).

Basically "miDebuggerPath" needs a specific value based on the kit chosen.   I've tried putting the path into a variable in the CMake Cache, but I can't figure out how to pull that out in launch.json

Even then, I need different pre-launch commands.

I'd RATHER not have multiple configurations and just have it figure it out from the CMake configuration stuff.

**Comment by bobbrow** [comment]
@schnort I moved your feature request to #999.  Let's discuss it in that issue.

**Comment by andreeis** [comment]
Moving this to backlog (for the concept of exporting variables in general), while #999 should be addressed earlier.
