### ISSUE TITLE
Include target environment variables when debugging

### ISSUE THREAD

**Issue by georgantas** [microsoft/vscode-cmake-tools#994]
### Brief Issue Summary

I have a CMake project, and when it is built, it produces the following configuration properties in the Visual Studio solution:

![Untitled](https://user-images.githubusercontent.com/18753033/71744334-e85ff000-2e34-11ea-9a7e-841405eb0b12.png)

I've set up my `launch.json` as follows to mimic the above debug configuration, and this works:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${command:cmake.launchTargetPath}",
            "args": ["-test", "yes"],
            "stopAtEntry": false,
            "cwd": "${command:cmake.launchTargetDirectory}",
            "environment": [
            {
                "name": "PATH",
                "value": "C:/Long/List/of;C:/Paths;%PATH%" // copy-pasted, not looking at the CMake configuration
            }],
            "externalConsole": false
        }
    ]
}
```

However, I've had to copy-paste the environment variables section into my launch.json. Is there any way to dynamically include the environment variables from the CMake configuration?

I've tried the following, but this does not work as expected:

```
"environment": [
            {
                "name": "PATH",
                "value": "${env:PATH}"
            }],
```

**Comment by Georgantas** [comment]
EDIT: Correction in the image: "Working directory" is "${TargetDir}". I had made a temporary edit.

**Comment by Georgantas** [comment]
I think I'd need something like `${command:cmake.env.PATH}` to make this work.
