### ISSUE TITLE
 [loc][Query][vscode-cmake-tools] Localizability of 0; "./src/extension.found.duplicate.kits"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vscode-cmake-tools#996]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Found Visual Studio kits with the old ids saved in the cmake-tools-kits.json.

ID & File Name:
0; "./src/extension.found.duplicate.kits"
Src\vscode-extensions\vscode-cmake-tools.xlf

Query:
What's saved in the cmake-tools-kits.json file: the kits or IDs?

**Comment by bobbrow** [comment]
> What's saved in the cmake-tools-kits.json file: the kits or IDs?
Both.  The "kit" is Visual Studio.  The "old id" was a non-unique id.  The "new id" is unique and allows us to support multiple versions of Visual Studio in the json file.

**Comment by PDostalek** [comment]
Many thanks
