### ISSUE TITLE
CMake Tools keeps on reconfiguring over and over.

### ISSUE THREAD

**Issue by RolfNoot** [microsoft/vscode-cmake-tools#997]
### Brief Issue Summary

If the compiler location is specified in the CMake file itself and different from the selected compiler location, CMake Tools keep on reconfiguring over and over.

### Expected:

CMake Tools should try to reconfigure and if fails, at least not keep reconfiguring

### Apparent Behavior:

CMake Tools keep on reconfiguring

### CMake Tools Log

```
[cmake] Configuring done
[cmake] You have changed variables that require your cache to be deleted.
[cmake] Configure will be re-run and you may have to reset some variables.
[cmake] The following variables have changed:
[cmake] CMAKE_C_COMPILER= /usr/bin/gcc-7
[cmake] CMAKE_CXX_COMPILER= /usr/bin/g++-7
```

**Comment by bobbrow** [comment]
I'm not sure I fully understand.  Are you both selecting a Kit and setting CMAKE_C[XX]_COMPILER in CMakeLists.txt?

**Comment by RolfNoot** [comment]
Yes. So that brings me to another question. What does selecting a kit do and do you still need to set CMAKE_C(XX)_COMPILER if you select a kit?

**Comment by bobbrow** [comment]
A Kit is a way to specify a compilation environment.  See the documentation here: https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html.

You don't have to use Kits though if you are able to configure your project without them.  Just select the `[Unspecified]` Kit and the extension will let CMake figure it out for you.

**Comment by RolfNoot** [comment]
Thanks! It wasn’t quite clear for me which settings / variables the kit affect. Now it is all clear, no more issues left.

Thanks!
