### ISSUE TITLE
Give us your feedback

### ISSUE THREAD

**Issue by esweet431** [microsoft/vscode-cmake-tools#998]
The C++ team at Microsoft is interested in your feedback to help us better understand your workflow and build the right features for you.  Sign-up for a 25 minute call with a member of the C++ development team here: https://outlook.office365.com/owa/calendar/CMakeToolsExtensionforVisualStudio@microsoft.onmicrosoft.com/bookings/

A confirmation and link to join the call will be sent to the email address you provide. 

Thanks!

**Comment by DavidA2014** [comment]
@esweet431 I need to cancel my scheduled call with you today. How can I do that?

**Comment by esweet431** [comment]
@DavidA2014 I just cancelled our call. Please let me know if another time works better. Thanks!

**Comment by DavidA2014** [comment]
@esweet431 I could actually do it now if that is convenient. Can you contact me directly?
