### ISSUE TITLE
Need a command to populate miDebuggerPath in launch.json

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cmake-tools#999]
I'm suffering quite a bit on this right now.  I am trying to support multiple targets  (windows GCC, cross compile w/GCC for hardware target, cross compile w/GCC for instruction set simulator target) and need a way to have launch.json be configured so the right GDB gets called with the right parameters).

Basically "miDebuggerPath" needs a specific value based on the kit chosen.   I've tried putting the path into a variable in the CMake Cache, but I can't figure out how to pull that out in launch.json

Even then, I need different pre-launch commands.

I'd RATHER not have multiple configurations and just have it figure it out from the CMake configuration stuff.

_Originally posted by @schnort in https://github.com/microsoft/vscode-cmake-tools/issues/993#issuecomment-572297128_

**Comment by bobbrow** [comment]
Can you help me understand your requirements better?  What are the mappings from the compiler kits to the debugger commands?  Are you using toolchains?

**Comment by schnort** [comment]
Yes, or yes, I will be.

**Background:**  

We're trying to move to CMake/VSCode for our development platform for our SoC product.

Our SoC contains multiple heterogenous cores (MCU, several DSPs, etc) all building out of the same code tree.  We also have emulation libraries provided by the DSP vendors that let us build our DSP code for the host.

Between the various targets we have multiple compiler chains:
- Mainline GCC or Clang for host
- Mainline GCC or Clang for target processor.
- GCC/Clang derivative from vendor, who has unhelpfully put a prefix in front of all their tool names, (dsp-clang.exe, dsp-ar.exe, dsp-cc.exe, etc.)
- non GCC/Clang tools for target processor.

And various debuggers:
- GDB for host
- GDB for instruction set simulator
- GDB for hardware target
- non GDB for hardware target

**Desire**

Somehow I want to not have to have each developer hand-edit their launch.json file to support whatever setup we're currently configered for and have it 'just happen'.  

It would be nice if it somehow to choose the launch configuration based on the selected target.  Or update launch.json base on the target.  Or have variable expansion that was powerful enough to make that happen.

It very well may be I'm trying to round hole a square peg.

**Comment by hwmaier** [comment]
We are in a similar situation and we are now using the new CMake preset feature to support multiple hardware and BSPs in a single project. If the feature requested here https://github.com/microsoft/vscode-cmake-tools/issues/1976 would be available I guess this issue could also be solved. Eg. passing a BSP specific setting like "miDebuggerPath" from a BSP specific preset to the debugger launch configuration.
